id: code-security
group: security
product: Code Security
canned_pattern: code|security
docs_path: /code-security
contact_path: /request/code-security
articles:
  - path: /code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-alerts-for-vulnerable-dependencies
    title: 脆弱な依存関係のアラートについて
    subtitle: GitHub は、リポジトリに影響を与える脆弱性を検出すると Dependabot アラートを送信します。
  - path: /code-security/security-advisories/about-coordinated-disclosure-of-security-vulnerabilities
    title: セキュリティ脆弱性の調整された開示について
    subtitle: 脆弱性の開示は、セキュリティの報告者とリポジトリメンテナの調整された取り組みです。
  - path: /code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot
    title: Dependabot でアクションを最新に保つ
    subtitle: Dependabot を使用して、使用するアクションを最新バージョンに更新することができます。
  - path: /code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
    title: 依存関係の更新の構成オプション
    subtitle: Dependabot がリポジトリを維持する方法をカスタマイズするために使用できるすべてのオプションの詳細情報。
options:
  - category: documentation
    title: ヘルプ ドキュメント
    subtitle: アカウントとプロファイルのドキュメントを確認します。
    img: microsites/documentation.svg
    cta: Start exploring
    url:
      docs_url: /code-security
  - category: documentation
    title: Guides
    subtitle: GitHub がコードのセキュリティを向上させるのに役立つさまざまな方法について説明します。
    img: microsites/documentation.svg
    cta: Learn more
    url:
      docs_url: /code-security/guides
  - category: github_blog
    title: 新着情報
    subtitle: 最新の Code Security の更新プログラムをブログで確認してください。
    img: microsites/blog.svg
    cta: Learn more
    url: 'https://github.blog/?s=Security'
video:
  title: 自動セキュリティ レビュー - GitHub コード スキャン
  subtitle: GitHub Code Scanning を有効にすることは、セキュリティ研究者のチームを招待して、すべての pull request をレビューするように依頼するようなものです。 CodeQL または静的コード分析パートナーのいずれかを使用してコード スキャンを構成することで、運用環境に移行する前に、すべてのコードがセキュリティの脆弱性をシームレスに確認できます。
  url: 'https://www.youtube.com/embed/z0wvGf3O69E?rel=0&amp;vq=hd720'
community:
  id: 21
  status: open
  path: 'https://github.com/orgs/community/discussions/categories/new-to-github'