### YamlMime:Yaml
ms.openlocfilehash: 868d0b0368e651a4de3cf1c54d92e959e3cc84e0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139894193"
Slug: a-deep-dive-into-serverless-applications-on-power-apps-and-azure
Title: Power Apps と Azure でのサーバーレスアプリケーションの詳細
Summary: 毎月2021では、Azure ソリューションでの低レベルのアプリケーション開発 (LCAD) のための今月のウェビナーを含む毎月のブログをリリースします。 lcad on Azure は、低レベルの Microsoft Power Apps と使い慣れた Azure 製品を統合する堅牢な開発機能を示す新しいソリューションです。  
Content: >-
  <p>2021では、 &nbsp; Azure ソリューションでの低レベルのアプリケーション開発 (LCAD) のための今月のウェビナーを含む毎月のブログをリリースする予定です。 lcad on Azure は、低レベルの Microsoft Power Apps と使い慣れた Azure 製品を統合する堅牢な開発機能を示す新しいソリューションです。&nbsp;&nbsp;</p>


  <p>今月&#39;s ウェビナーでは、 <em>Power Apps と Azure のサーバーレスアプリケーションについて詳しく説明し</em>ます。 &nbsp;このブログでは、 <a href="https://azure.microsoft.com/en-us/solutions/low-code-application-development/" target="_blank">Azure での低レベルのアプリケーション開発につい</a>て簡単に説明し、サーバーレスのパワーアプリを構築する理由についての概要と、<a href="https://info.microsoft.com/ww-Landing-ADeepDiveintoServerlessApplications.html?LCID=EN-US" target="_blank">ウェビナー&#39;s のデモ</a>での注目事項について説明します。</p>


  <h2>Azure での低コードアプリケーションの開発とは&nbsp;</h2>


  <p><a href="https://azure.microsoft.com/en-us/solutions/low-code-application-development/" target="_blank">azure の低レベルのアプリケーション開発 (lcad)</a>が作成されました。開発者は、より少ないコードでより迅速にビジネスアプリケーションを構築できるようになりました。さらに、より具体的には Power Apps &mdash; 、azure サービスを使用して Power Apps の拡張と拡張を行うことができます。&nbsp;&nbsp;</p>


  <p>たとえば、製造会社に勤務している pro 開発者は、基幹業務 (LOB) アプリケーションを構築して、倉庫の従業員が受信した在庫を追跡できるようにする必要があります。 このアプリケーションのビルド、テスト、および展開には数か月かかります。 ただし、Power Apps&#39; では、時間とリソースを節約するのに数時間かかることがあります。 &nbsp;ただし、倉庫の従業員が、現在の在庫が特定の数に達したときに、追加の在庫の調達注文を自動的に配置することが必要になるとします。 これまでは、開発チームが以前のアプリケーションイテレーションを再作成するために、別の大きなリフトを必要としていました。 Power Apps と Azure の統合により、プロフェッショナルな開発者は Visual Studio (VS) コードで api を構築し、Azure portal に発行し、api をカスタムコネクタとしてアプリケーションに統合 Power Apps にエクスポートできます。 その後、その同じ API は Power Apps&#39; studio で無期限に再利用できるようになります。その後、他のアプリケーションで使用できるようになり、会社や開発者はより多くの時間とリソースを節約できます。&nbsp;&nbsp;</p>


  <h2>サーバーレス アプリケーション</h2>


  <p>サーバーレスアプリケーションとは何ですか。 サーバーレスは、クラウドプロバイダーがサーバーの割り当てとプロビジョニングを動的に管理するクラウドコンピューティング実行モデルです。 サーバーレスアプリケーションは、イベントがトリガーされ、クラウドプロバイダーによって完全に管理されるステートレスなコンピューティングコンテナーで実行されます。 さらに、このモデルでは、サーバー管理の必要性を減らすことによってワークロードを削減することで、開発者やチームにとって大きなメリットが得られます。また、このモデルは、チームがハードウェアや関連コストを&#39;しないため、はるかにコストがかかります。 &nbsp;論理的な次の質問は、 &quot; サーバーレスに移行するシナリオです。 &quot; 要求が頻繁に行われず、&#39;t が待機時間に依存していない場合に、非同期および同時実行タスクを実行するときに、このオプションを選択できます。 また、開発の反復処理を迅速に検討する&#39;、Mvp を構築し、コードを変更するか、ビジネス要件を変更してそのコードをすぐにデプロイします。&nbsp;</p>


  <p>サーバーレスのコード&#39;の利点を理解したうえで、どのようにして作業を開始するのかを&#39;ます。 コアには、コンテナーにコードを記述できるクラウド関数があります。 イベントに対する反応として、アプリケーションにとって重要な、任意のマネージサービスまたはカスタムソースによって実行がトリガーされることがあります。 持続性のある <a href="https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp" target="_blank">関数</a>により、サーバーレスのコンピューティング環境でステートフル関数を記述できます。 最後に、サーバーレスコードはイベントドリブンで、特定のトリガーに応答して実行されます。これは、ストレージアカウント番号にアップロードされているファイルに応答してコードを実行するときに、HTTP または blob トリガーになることがあります。</p>


  <h2>サーバーレス Power Apps</h2>


  <p>Azure でサーバーレスアプリケーションを作成するのは非常に便利ですが &nbsp; 、Microsoft Power Apps を使用して作成するのはなぜでしょうか。 複数の異なるフレームワーク、ホスティングオプション、システム間での複雑な統合を利用する場合、ビジネスアプリケーションを迅速に構築することは簡単ではありません。 サーバーレステクノロジ (Azure Functions と Logic Apps) を利用すると、Api の構成要素を使用して、さまざまなアプリケーションにデータを格納するカスタムバックエンド、サービス、またはデータモデル (Dataverse いる) に接続できます。 これらの api を活用して Power Apps または Microsoft Power Automate と緊密に統合し、非常に重要なデータを、迅速に構築、管理、分散されたアプリでビジネスユーザーに拡張します。 さらに、&#39;Fusion 開発&#39; チームの開発、アナリストによる造語という用語は、バックエンドサーバーレス api を構築し、Azure API management を使用して、カスタムコネクタとして<a href="https://powerapps.microsoft.com/en-us/blog/azure-api-management-connector-on-the-power-platform/" target="_blank">Microsoft Power Apps に直接</a>インポートすることができます。 市民の開発 &nbsp; 者や、専門の開発者が&#39;いる人は、Power App でこれらの api を活用できるため、フロントエンドコードを構築しなくても、開発者&#39;の作業全体を減らすことができます。 このため、サーバーレスアプリケーションの構築によって保存された時間とリソースに積み上がり始まっます。</p>


  <h2>ウェビナーで予想されること</h2>


  <p>Simona ウェビナーでは、事前に作成した web API を構築する方法に &nbsp; ついて説明します。 このプロセス全体で、彼女は Api をテストしてデバッグします。 その後、aka.ms/joke でテストできる場所への API の公開について説明します。これにより、ランダムな単語を使用して簡単 &nbsp; に生成できます。 最後に、Azure portal およびチャレンジ &nbsp; ビューアーを使用して Power Apps に API をエクスポートして、テキストメッセージとしてジョークを送信する Power Automate AI チャットボットでアプリを拡張します。<br>

  <br>

  サーバーレス Api の詳細と、それらを Power Apps にエクスポートする方法については、2月25日の<a href="https://info.microsoft.com/ww-Landing-ADeepDiveintoServerlessApplications.html?LCID=EN-US" target="_blank">ウェビナー</a>にご調整ください。 さらに、Azure &#39;での低レベルのアプリケーション開発については、Ignite 中のライブ&#39; セッション、データ損失防止、Ignite での Power Apps 用の新しいガバナンスポリシー、3月の SAP on Azure Power Apps ウェビナーなどが含まれています。</p>


  <h2>詳細情報</h2>


  <ul>
      <li><a href="https://azure.microsoft.com/en-us/solutions/low-code-application-development/" target="_blank">Azure 上の Lcad</a>。</li>
      <li><a href="https://powerapps.microsoft.com/en-us/power-apps-and-azure/" target="_blank">Azure plus Power Apps pro 開発者向け</a>です。</li>
      <li><a href="https://www.youtube.com/playlist?list=PL8IYfXypsj2Dp-jDh4TpkxnYlGmIccKfM" target="_blank">Azure &mdash; での低レベルのアプリケーション開発YouTube</a>。</li>
  </ul>


  <h3>Power Apps と &nbsp;Azure のドキュメント</h3>


  <ul>
      <li><a href="https://docs.microsoft.com/en-us/powerapps/developer/data-platform/azure-integration" target="_blank">Azure 統合ドキュメント</a>。</li>
      <li><a href="https://powerapps.microsoft.com/en-us/blog/azure-api-management-connector-on-the-power-platform/" target="_blank">Azure API Management の統合</a>に関するお知らせ。</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/api-management/export-api-power-platform" target="_blank">Azure API Management の統合に関するドキュメント</a>。</li>
  </ul>


  <h3>サーバーレスドキュメント</h3>


  <ul>
      <li><a href="https://docs.microsoft.com/en-us/azure/azure-functions/functions-compare-logic-apps-ms-flow-webjobs" target="_blank">サーバーレスオプションを比較</a>します。</li>
      <li><a href="https://docs.microsoft.com/en-us/learn/modules/choose-azure-service-to-integrate-and-automate-business-processes/" target="_blank">サーバーなしのオプションモジュールを比較</a>します。</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/azure-functions/" target="_blank">Azure Functions ドキュメント</a>。</li>
      <li><a href="https://azure.microsoft.com/en-us/services/functions/" target="_blank">Azure Functions web サイト</a>。</li>
  </ul>
