### YamlMime:Yaml
ms.openlocfilehash: 819cedd9b591c50892d6f267344e5f42b4efdc02
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891019"
Slug: a-sample-application-for-pulling-data-from-sql-into-an-azure-event-hub
Title: Azure Event Hub にデータをプルSQLサンプル アプリケーション
Summary: 私がDinar Gainitdinov で生成した最近の記事とコード サンプルでは、いくつかの複雑な結合とクエリを実行し、更新されたレコードを Azure Event Hub にプッシュする簡単なアプリケーションを構築する方法を示しています。
Content: >-
  <p>制御するデバイスから Azure <a href="https://azure.microsoft.com/en-us/documentation/articles/?suite=iot-suite"></a> にデータを<a href="https://azure.microsoft.com/en-us/documentation/samples/?service=iot-hub"></a>プッシュしたり、他のストリーミングデータや静的データと組み合わせて分析したりするためのドキュメント記事やコード サンプルが多数存在します。 最近、パブリック Web フィードから <a href="https://azure.microsoft.com/en-us/documentation/articles/event-hubs-pulling-public-data/" target="_blank">データをプル</a> し、Azure にプッシュする方法の例も公開しました。</p>


  <p>3 つ目のまれなシナリオでは、テーブルからデータをプルSQL Azure、そのデータを Azure Event Hub にプッシュします。 たとえば、元のストリーミング ソースから SQL Azure にデータをプッシュする必要があるケースがいくつかあるので、複雑な結合とクエリを実行してから、更新されたレコードを Azure Event Hub にプッシュできます。 私がDinar Gainitdinov で生成した最近の記事とコード サンプルでは、これを実現する簡単なアプリケーションを構築する方法を示しています。</p>


  <p>テクニカル ドキュメント <a href="https://azure.microsoft.com/en-us/documentation/articles/event-hubs-pulling-sql-data/">と</a> <a href="https://github.com/Azure-Samples/event-hubs-dotnet-import-from-sql" target="_blank">SqlToEventHub ソリューション コード</a> を確認してテストしてください。</p>
