### YamlMime:Yaml
ms.openlocfilehash: 282571a1bae6394b9bcd2c235c5d3a2e9fa26a43
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891016"
Slug: a-sample-application-for-pulling-data-from-the-web-into-an-azure-event-hub
Title: Web から Azure Event Hub にデータをプルするためのサンプルアプリケーション
Summary: 制御していないパブリック web サイトからデータをプルし、そのデータを Azure Event Hub にプッシュする方法について説明します。
Content: >-
  <p>Azure に制御するデバイスからデータをプッシュする場合や、他のストリーミングデータや静的データと組み合わせて分析する場合は、さまざまな <a href="https://azure.microsoft.com/en-us/documentation/articles/?suite=iot-suite">ドキュメント記事</a> と <a href="https://azure.microsoft.com/en-us/documentation/samples/?service=iot-hub">コードサンプル</a> が用意されています。</p>


  <p>&rsquo;あまり詳しく説明していないのは、管理していないパブリック web サイト &rsquo; からデータをプルし、そのデータを Azure Event Hub にプッシュする方法です。 最近の記事と「ディナール Gainitdinov で生成されたコードサンプル」では、C# の数行の単純なアプリケーションを構築する方法を示しています。 このコードの強化 up バージョンを使用して、リアルタイムの車両データと Microsoft Dynamics のメンテナンスレコードを結合し、別のバージョンを使用して、シアトル地域のトラフィックが気象にどのように影響を受けたかを分析しました。 もちろん、web サイトから著作権データを収集しておらず、すべての使用条件に準拠していることを確認してください。</p>


  <p>いくつかのお気に入りのデータフィードで試してみるには、 <a href="https://azure.microsoft.com/en-us/documentation/articles/event-hubs-pulling-public-data/">技術ドキュメント</a> と GenericWebToEH ソリューションコードを確認してください。</p>
