### YamlMime:Yaml
ms.openlocfilehash: cd44a78c8598080aa8ceb924715e53c688897d78
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891357"
Slug: advancing-indatacenter-critical-environment-infrastructure-availability
Title: データセンター内の重要な環境インフラストラクチャの可用性の向上
Summary: 重要な環境インフラストラクチャの可用性に影響を与える可能性がある多くの要因があります。インフラストラクチャの構成要素の信頼性、データセンターの構築段階での制御、効果的な正常性監視とイベント検出スキーム、堅牢なメンテナンス プログラム、オペレーショナル エクセレンスにより、関連するリスクへの影響を慎重に考慮してすべてのアクションが確実に実行されます。
Content: >-
  <p>Azure クラウド コンピューティング プラットフォームの基盤の 1 つは、世界中のデータセンターの IT インフラストラクチャに電力と冷却を提供する重要な環境 <em>(CE) インフラストラクチャの可用性です。&ldquo;信頼性の向上に関する<a href="https://www.aka.ms/AdvancingReliability" target="_blank"></a>シリーズの今日の投稿では、Ive&rsquo; は、これらの重要なシステムに関連するさまざまなリスクを特定して軽減する方法を説明するために、Cloud Operations and InnovationEngineering&nbsp; チームの信頼性エンジニアリング ディレクター <strong>Randy Kong</strong> に質問しました。&rsquo;&nbsp;&nbsp;次に示すのは、Microsoft とパートナーがこの領域で行う長さのハイライトです。この領域では、お客様とパートナーが Azure&rdquo;&mdash;</em> プラットフォーム上で実行する重要なアプリケーションに対する世界レベルの信頼性を確保するためのビューが示されています。Mark Russinovich、CTO、Azure</p>


  <hr>

  <p>重要な環境 (CE)&mdash; インフラストラクチャの可用性に影響を与える可能性がある多くの要因インフラストラクチャの構成要素の信頼性、データセンターの構築段階での制御、効果的な正常性監視とイベント検出スキーム、堅牢なメンテナンス プログラム、オペレーショナル エクセレンスにより、関連するリスクへの影響を慎重に考慮してすべてのアクションが確実に実行されます。</p>


  <p>Microsoft&mdash; は、高可用性 CE インフラストラクチャの設計、構築、試運転、運用に業界をリードするほか、CE インフラストラクチャの可用性を高め、維持するための信頼性エンジニアリング分野でのベスト プラクティスの開発と実装にも投資しています。 &quot;&mdash;&nbsp;&quot;一般に、このブログの信頼性エンジニアリングとは、さまざまな障害モード、効果、メカニズムによって、予想される有用なライフの間にシステム機能に影響を与える可能性がある時間の潜在的なリスクを事前に特定して評価するエンジニアリングの分野を指します。 簡単な&nbsp;&rsquo;例として、よりエネルギー効率の高い空き空き冷却を使用してデータセンターを冷却する場合、制御された温度、湿度、大気質の環境を提供する CE インフラストラクチャが確実に提供されます。 目的の 1 つは、プリントサーキット ボード アセンブリなどの不適切な条件下で電気ショートやオープンが発生する可能性があるという問題を防ぐことです。</p>


  <p>ハイパースケール クラウド データセンターの CE&mdash; は、通常、無停電電源装置 (UPS)、配電ユニット (PDU)、自動転送スイッチ (ATS)、エア処理ユニット (AHU)、ジェネレーターなどの多様なベンダーの基本コンポーネントを組み合って構築されます。 このマルチベンダーのマルチテクノロジ環境では、本質的な複雑さと堅牢性のバリエーションが導入され、主にベンダーのコンピテンシーとエクスペリエンスに依存します。 たとえば、これらの既製コンポーネントに関する情報が不十分な場合など、CE インフラストラクチャの正常性の監視も制限されます。 したがって、監視は、&ldquo;&rdquo;主に、電力管理システム (EPMS) やビルオートメーション システム (BAS) からのなど、高レベルの障害効果検出に依存します。</p>


  <p>ただし、障害の影響に基づく検出スキームでは、通常、問題のある要素を迅速に検出して特定する必要が生じるため、障害が発生した場合にサービスの迅速な回復が遅れる可能性があります。 グローバルな&mdash;&mdash;運用の規模によってさらに課題が生じ、ローカル条件のバリエーションによって、通常は時間ベースの予防メンテナンス アプローチの有効性に対する機器の課題に対するストレスが異なる可能性があります。 &ldquo;&rdquo;一部の地域では気温、湿度、または大気の品質の変化が大きくなるので、対応する環境ストレス条件下での低下率を考慮しない場合、時間ベースのメンテナンス アプローチが無駄になったり、システムの信頼性を更新する機会を失う可能性があります。</p>


  <h2>CE 信頼性エンジニアリングへの投資</h2>


  <p>このような課題に対処するために、Microsoft は CE 信頼性エンジニアリング機能の確立に投資しています。 &nbsp;関連する信頼性エンジニアリングとテクノロジの多くは、過去数十年の間に電子業界から生み出され、データセンター CE インフラストラクチャの信頼性のベスト プラクティスとソリューションを適応、拡張、イノベーションする十分な機会があります。 たとえば、最新の CE コンポーネントについては、機器の選択と認定の段階で、アプリケーション固有の信頼性リスク評価において CE ベンダーとの密接なパートナーシップを求めていました。 &mdash;運用段階では、ベンダー ベースと密接に協力して、個々のケースの根本原因分析からフリート全体の正常性動作データ分析まで、物理的およびデータの詳細な分析を通じて継続的な改善を進めます。 これらのパートナーシップは、Microsoft とベンダーの両方が、関連する信頼性の傾向、潜在的なリスクの領域、および基になる要因に対する明確でデータ駆動型の可視性を持つのに役立ちます。これにより、効果的な解決策を導入し、多くの場合、より結果的な影響が発生する前に事前に行えます。 信頼性エンジニアリングでは、潜在的な CE インフラストラクチャ リスクの理解を向上させる一方で、信頼性エンジニアリングは、高いクリティカル度領域の障害モードとメカニズムに関連するパラメーターをキャプチャするなどの、より積極的で効果的なインフラストラクチャの正常性検出を引き起す可能性がある研究および開発 (RD&amp;) の取り組みにも重点を置いて行います。 内部および外部パートナーシップは、データ マイニングや機械学習から物理障害 (PoF) 手法まで、関連するアプローチの RD&amp; で確立されています。</p>


  <p>Microsoft が CE 空間にイノベーションを導入し続ける中で、信頼性エンジニアリングは、初期段階のリスク分析と軽減策を通じて、設計された信頼性と組み込みの信頼性の両方を推進することで、これらのソリューションの堅牢性を確保する上で中心的な役割を果たしています。 たとえば、 <a href="https://www.microsoft.com/security/blog/2020/11/23/iot-security-how-microsoft-protects-azure-datacenters/" target="_blank">Microsoft Sphere ベースの IoT</a> ソリューションは、機械および電力 CE システムから安全にデータを取得するために開発されています。 信頼性エンジニアリングは、内部および外部の製品設計および製造パートナーと密接に連携して、ソリューションの概念、プロトタイプ、設計、プロセス開発、製品のデプロイのステージ全体で分析および PoF ベースのテストアプローチの両方を適用します。 1 つのケースは、&rsquo; 製造中またはアセンブリ中の、または使用ライフサイクルにおける、電子パッケージ関連の欠陥に関する懸念です。 有限要素分析 (FEA) に基づくシミュレーション ツールを使用して、熱機械ストレス ポイントを識別しました。これらのストレス ポイントは、予想される寿命内に障害が発生する可能性があるという点で、設計がまだ紙の上に描画されているだけの場合でも同様です。 その後、これらのポイントは、環境ストレス テスト中や製造プロセスの手順中に、関連する力学ストレスを導入できる密接に追跡され、特徴付けされます (たとえば、歪みゲージを使用)。 このようなストレスが発生した後もシステムが機能している可能性がある場合でも、欠陥の早期開始を特定するために、サンプルは重大なジャンクションで物理的に横断的にセクションされます。 これらの詳細な分析により、製品またはプロセスの設計変更を同時に行って障害の可能性を排除し、最終的なシステムの可用性を向上できます。</p>


  <p>複雑な CE&mdash; インフラストラクチャ自体でも同様の設計 for エクセレンス (DFX) 戦略が調査され、可能な限りインフラストラクチャを物理的にデプロイする前に、事前のリスク識別と防止の機会を実現できます。 信頼性エンジニアリングの分野におけるこれらの CE 関連の投資とテクノロジの進歩は、Microsoft&rsquo; CE&rsquo; インフラストラクチャが、世界クラスのクラウド コンピューティング サービスに対するお客様の可用性の期待を満たすために、追加の堅牢性メカニズムを構築するのに役立ちます。</p>
