### YamlMime:Yaml
ms.openlocfilehash: 4bf8ca599649f879587616f996f63e128b413baf
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910151"
Slug: announcing-availability-of-azure-managed-application-in-azuregov
Title: AzureGov での Azure マネージド アプリケーションの可用性の発表
Summary: サービス カタログを使用したAzure Managed Applicationsは、AzureGov Cloud で一般提供されています。
Content: >-
  <p style="font-style: normal; font-weight: 400;">Azure Managed Applicationsサービス プロバイダー (MSP)、独立系ソフトウェア ベンダー (ISV) パートナー、エンタープライズ IT チームが、特定のエンド カスタマーのエンタープライズ サービス カタログを通じて利用できるフル マネージドのターンキー クラウド ソリューションを提供できます。 お客様は、マネージド アプリケーションを自分のサブスクリプションにすばやくデプロイし、パートナーまたは中央 IT チームに依存して、ライフサイクル全体のメンテナンス操作とサポートを行えます。 </p>


  <p style="font-style: normal; font-weight: 400;">これは、企業が Azure を使用する入り口です。</p>


  <h2 style="font-style: normal;">配布チャネルとしての組織サービス カタログ</h2>


  <p style="font-style: normal; font-weight: 400;">Service Catalog を使用すると、組織内のユーザーが使用できる承認されたアプリケーションとサービスのカタログを作成できます。 カスタマイズされた仮想マシンのオファー、サーバー、データベースから複雑なインハウス アプリケーションまで、何でも含まれます。 このようなソリューションのカタログを維持すると、特に企業の中央 IT チームにとって役立ちます。これにより、組織に優れたソリューションを提供しながら、特定の組織の標準に準拠することができます。 ＩＴ チームは、これらのアプリケーションを制御、更新、および管理できます。 組織の従業員は、IT 部門が推奨し、承認している数多くのアプリケーションを簡単に見つけることができます。 顧客には、自分で作成されたサービス カタログマネージド アプリケーション、または組織内の他のユーザーによって共有されているアプリケーションだけが表示されます。</p>


  <p>Enterpriseロール ベースのアクセス制御を使用して、サービス カタログに公開するユーザーを制御できます。 このロールは、サービス カタログ管理者に変換されます。その後、サービス カタログのコンシューマーに対して別のロールを持つ場合があります。</p>


  <h2>発行</h2>


  <p>サービス カタログへの発行は、Azure Portal、CLI、または PowerShell を使用して簡単に実行できます。 必要な主なコンポーネントは、a) プロビジョニングされるリソースを記述するテンプレート ファイルと、b) これらのリソースをプロビジョニングするために必要な入力をポータルに表示する方法を示す UI 定義ファイルです。 必要なファイルは、.zipファイルにパッケージ化され、ポータルの [サービス カタログ] ブレードを使用してアップロードされます。 発行ポータルのスクリーンショットを次に示します。 Service Catalog マネージド <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-overview">アプリケーションを発行および使用する方法の詳細を確認します</a>。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fa482a0e-fbb2-4f65-8ee9-ddab806a0905.png"><img alt="image" border="0" height="574" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f3c9b90f-39a9-4137-a7cf-5024ce1e6d86.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="イメージ" width="356"></a></p>


  <h2>価格</h2>


  <p style="font-style: normal; font-weight: 400;">マネージド アプリケーションを顧客のサービス カタログに発行するパートナーに対する追加料金はありません。</p>


  <p style="font-style: normal; font-weight: 400;">お客様は、通常の課金コンストラクトを使用して、マネージド アプリケーションの一部である Azure リソースの使用に対して課金されます。 たとえば、マネージド アプリケーションの一部として、仮想マシンが顧客サブスクリプションにプロビジョニングされた場合、顧客は仮想マシンの使用に対して課金されます。 同様に、パートナーがライフサイクル操作に対して顧客に請求する料金は、顧客の Azure 請求書に新しい品目として&rsquo;表示されます。</p>


  <h2>[Authorizations]</h2>


  <p>マネージド アプリケーションの一部であるリソースを含むリソース グループは、顧客に対してロックされます。 顧客は、このリソース グループ内のリソースへの読み取り専用アクセス権を持っています。 その結果、お客様は、マネージド アプリケーションの一部であるリソースを誤って削除または更新することはできません。 発行元は、ロック解除されたマネージド アプリケーションを発行することもできます。そうすると、顧客は変更を加え、基になるコンポーネントを削除できます。</p>


  <p>ただし、マネージド アプリケーションの発行元は、顧客テナントでアプリケーションを保守、サービス、アップグレードするために必要なアクセス許可を&rsquo;取得します。 これらのアクセス許可は、一般的な <a href="https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-built-in-roles">Azure RBAC ロールによって定義されます</a>。 詳細については、「その他のリソース」セクションを参照してください。</p>


  <h2>Customers サービス カタログ&rsquo;での発行</h2>


  <p>サービス カタログに発行する際の主な機能を理解するのに役立つ簡単な概要を次に示します。</p>


  <table border="0" cellpadding="2" cellspacing="0" width="1056">
   <tbody>
    <tr>
     <td valign="top" width="222">&nbsp;</td>
     <td valign="top" width="832"><strong>サービス カタログ マネージド アプリケーション</strong></td>
    </tr>
    <tr>
     <td valign="top" width="222"><strong>発行ツール</strong></td>
     <td valign="top" width="832">
     <ul>
      <li>Azure CLI</li>
      <li>Azure PowerShell (Service-Service&gt; Catalog マネージド アプリケーション定義の作成)</li>
      <li>Azure portal</li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="222"><strong>Consumption Tool</strong></td>
     <td valign="top" width="832">
     <ul>
      <li>Azure Portal ([その他のサービスマネージド&gt; アプリケーション] に移動)、Azure CLI、Azure PowerShell</li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="222"><strong>料金</strong></td>
     <td valign="top" width="832">
     <ul>
      <li>パートナーに公開する料金はかかりません。</li>
      <li>マネージド アプリケーションの一部としてプロビジョニングされる Azure リソースに対して請求された顧客。</li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="222"><strong>Artifactsに必要なパッケージ</strong></td>
     <td valign="top" width="832">
     <ul>
      <li>mainTemplate.json</li>
      <li>createUIDefinition.json</li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="222"><strong>ケースの使用 </strong><br>
  (お客様)</td>
     <td valign="top" width="832">
     <ul>
      <li>承認された IT サービスとアプリケーションの簡単な検出可能性</li>
      <li>単純な取得とデプロイ</li>
      <li>Azure リソースの基になる複雑さからエンド ユーザーを抽象化します。</li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="222"><strong>ユース ケース</strong><br>
  (パートナー)</td>
     <td valign="top" width="832">
     <ul>
      <li>承認されたアプリ/サービスを、エンド カスタマー組織内の開発者と事業単位に提供します。</li>
      <li>Azure リソースの基になる複雑さからエンド ユーザーを抽象化します。</li>
      <li>顧客テナントにデプロイされたマネージド アプリに、改ざんや意図しない変更が含めずに行う必要があります。</li>
      <li>サービス カタログで定義されたアプリケーションを使用して、企業の標準を使用してガバナンスを確保します。</li>
     </ul>
     </td>
    </tr>
   </tbody>
  </table>


  <p>この新しいサービスを試して、ユーザーの音声チャネルまたは以下<a href="https://feedback.azure.com/forums/281804-azure-resource-manager"></a>のコメントからフィードバックをお寄せください。</p>


  <h2>その他の技術情報</h2>


  <ul>
   <li>Marketplace マネージド <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-author-marketplace">アプリケーションを発行する</a></li>
   <li>サービス カタログ <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-publishing">マネージド アプリケーションを発行する</a></li>
   <li>マネージド アプリケーション <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-createuidefinition-overview">の UIDefinition を作成する方法</a></li>
   <li><a href="https://github.com/Azure/azure-managedapp-samples">マネージド アプリケーションのサンプル GitHubリポジトリ</a></li>
  </ul>
