### YamlMime:Yaml
ms.openlocfilehash: 0cd798205f4dd40592e2fd13267d195437ceaf86
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891243"
Slug: announcing-linux-on-app-service-environment-general-availability
Title: '一般提供 Linux on App Service Environment 発表 '
Summary: Linux またはコンテナー化された web アプリを Azure Virtual Network にデプロイすることに関心がある場合は、 現時点では、Linux on App Service Environment (ASE) の一般公開を発表しています。これは、Linux と App Service Environment の App Service の機能を組み合わせたものです。
Content: >-
  <p>Linux またはコンテナー化された web アプリを Azure Virtual Network にデプロイすることに関心がある場合は、 現時点では、 <strong>Linux on App Service Environment (ASE) の一般</strong>公開を発表しています。これは、Linux と App Service Environment の App Service の機能を組み合わせたものです。 パブリックプレビューで発表したように、Linux のお客様は、Linux およびコンテナー化された <strong>アプリを App Service Environment にデプロイ</strong>できるようになります。これは、セキュリティで保護されたネットワークアクセスや、高スケールで実行されるアプリのためにアプリケーションを VNet にデプロイする場合に最適です。</p>


  <h2>Linux on ASE でできること</h2>


  <p>Linux on ASE では、独自のカスタムコンテナーを使用するか、組み込みのイメージのいずれかを使用してコードを取り込むことによって、Linux web アプリケーションを Azure virtual network (VNet) にデプロイできます。</p>


  <p>独自のカスタム Docker コンテナーを使用する場合は、次の方法でイメージを取り込むことができます。</p>


  <ul>
   <li>DockerHub</li>
   <li>Azure Container Registry</li>
   <li>独自のプライベートレジストリ</li>
  </ul>


  <p>組み込みのイメージの1つを使用する場合は、次のような多くの一般的なスタックがサポートされています。</p>


  <ul>
   <li>ノード</li>
   <li>PHP</li>
   <li>Java</li>
   <li>.NET Core</li>
   <li>その他</li>
  </ul>


  <p>また、Windows、Linux、コンテナー化された web アプリケーションの両方を同じ ASE にデプロイし、同じ VNet を共有することもできます。 <strong>Windows と linux の web アプリを同じ App Service Environment に配置できる</strong>場合でも、Windows と linux の web アプリは別々の App Service プランに配置する必要があることに注意してください。 Linux on ASE では、分離された SKU と Dv2 vm、および追加のスケーリング機能を使用します (1 つの ASE では、Windows と Linux の間で最大<strong>100 の App Service プランインスタンス</strong>)。</p>


  <p>インターネットにアクセス可能なエンドポイントが必要かどうかに応じて、次の2種類の ase を作成できます。</p>


  <ul>
   <li>インターネットにアクセス可能なエンドポイントを持つ<em>外部 ASE</em></li>
   <li>内部ロードバランサー (ILB) を使用した VNet 内のプライベート IP アドレスを持つ <em>内部 ASE</em> 。</li>
  </ul>


  <p>ここでの考慮事項は、ASE でホストされているアプリを公開する IP の種類です。 開始する手順については、こちらを参照 <a href="https://docs.microsoft.com/en-us/azure/app-service/environment/create-external-ase#create-an-ase-and-a-linux-web-app-using-a-custom-docker-image-together">してください。</a> ASE のネットワークを構成する方法の詳細については、こちらを参照 <a href="https://docs.microsoft.com/en-us/azure/app-service/environment/network-info">してください。</a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8afcd6bd-9e8c-40bb-996e-abd1d747b301.png"><img alt="Creating a new App Service plan in App Service Environment " border="0" height="630" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/76e67fc1-bb42-4620-bb10-9a467adbf785.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="プランの App Service" width="1367"></a></p>


  <h2>プレビューからの価格の変更</h2>


  <p>App Service Environment にデプロイされた linux およびコンテナー化されたアプリは、linux の通常の App Service に戻り、App Service Environment 価格で提供されます。これは、Linux App Service プランのパブリックプレビューからの50% の割引が GA 用に削除されるためです。</p>


  <h2>追加された新しいリージョン</h2>


  <p>パブリックプレビュー以降、Linux &rsquo; s 20 以上のリージョンのすべての App Service に Linux on ASE が拡張されました。これには次のものが含まれます。</p>


  <ul>
   <li>オーストラリア東部</li>
   <li>オーストラリア南東部</li>
   <li>ブラジル南部</li>
   <li>カナダ中部</li>
   <li>カナダ東部</li>
   <li>インド中部</li>
   <li>米国中部</li>
   <li>東アジア</li>
   <li>米国東部</li>
   <li>米国東部 2</li>
   <li>東日本</li>
   <li>西日本</li>
   <li>韓国中部</li>
   <li>韓国南部</li>
   <li>米国中北部</li>
   <li>北ヨーロッパ</li>
   <li>米国中南部</li>
   <li>インド南部</li>
   <li>東南アジア</li>
   <li>英国南部</li>
   <li>英国西部</li>
   <li>米国中西部</li>
   <li>西ヨーロッパ</li>
   <li>インド西部</li>
   <li>米国西部</li>
   <li>米国西部 2</li>
  </ul>


  <h2>ファースト ステップ</h2>


  <p>新しい web アプリを作成し、OS (組み込みイメージ) として Linux を選択するか、Docker (カスタムコンテナー) を選択するか、新しい Web App for Containers (カスタムコンテナー) を作成するだけで、Linux web アプリを新しい ASE に作成することができます。 新しい App Service プランを作成する場合は、分離された Sku のいずれかを選択することを忘れないでください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/58931a42-e20e-4abf-9d93-1146e09d39e9.png"><img alt="Creating a new App Service Plan" border="0" height="614" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5fd8ac4f-ee14-479f-9e40-f99bef7060e5.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="プランの App Service" width="1556"></a></p>


  <p>詳細な手順が必要な場合は、次の手順に従って、最初の Linux/コンテナー化された web アプリを ASE に作成する方法をお使い <a href="https://docs.microsoft.com/en-us/azure/app-service/environment/create-external-ase#create-an-ase-and-a-linux-web-app-using-a-custom-docker-image-together">ください。</a></p>


  <p>ご意見をお待ちしており &rsquo; ます。 Linux on ASE については、<a href="https://feedback.azure.com/forums/169385-web-apps?category_id=333220">こちら</a>からご意見をお寄せください。</p>


  <h2>よく寄せられる質問 (FAQ)</h2>


  <p><strong>Q:</strong> 特に、App Service Environment の新機能については、すべての展開にどれくらいの時間がかかりますか。</p>


  <p><strong>A:</strong> ASE は、App Service アプリを高スケールで安全に実行するための完全に分離された専用の環境を提供するため、ASE で web アプリを作成するときにプロビジョニングする多くの異なる部分があります。 フロントエンドを共有する代わりに、HTTP/HTTPS の終了と ASE 内のアプリ要求の自動負荷分散を担当する専用のフロントエンドがあります。</p>


  <p>そのため、ASE に web アプリをデプロイする場合や、スケーリング操作を実行する場合、操作には数時間以上かかることがあります。 これは、約束された SLA ではありません。 スケーリング処理のスケジュールを設定して、拡張プロセスにかかる時間を考慮することをお勧めします。 ASE でのアプリのスケーリングとデプロイ時間の向上は、チームが向上させるための最優先事項です。</p>


  <p><strong>Q:</strong> NSG とルーティングルールを使用して ASE をロックダウンする場合は、どうすればよいですか。</p>


  <p><strong>A:</strong> App Service Environment を使用することは、ネットワークアクセスを制御し、アプリケーションへのアクセスをロックダウンするための優れたユースケースです。 これを行うには、次のようにします。</p>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/app-service/environment/network-info#network-security-groups">ネットワークセキュリティグループ (NSGs)。</a> 受信および送信のセキュリティ規則を設定できます。</li>
   <li><a href="https://docs.microsoft.com/en-us/azure/app-service/environment/network-info#routes">ルート</a>。インターネットに直接アクセスしない送信トラフィックを制御できます (ExpressRoute ゲートウェイや仮想アプライアンスなど)。</li>
  </ul>


  <p>これは ASE レベルで実行されます。アプリレベルではありません (App Service ポータルでは、Linux およびコンテナーアプリ用に淡色表示されている [ネットワーク &rdquo; ] という名前 &ldquo; の左側のメニューにオプションがあります。 これは、NSGs とルートを使用したネットワークアクセスの制御には関係ありません。</p>


  <p>また、ASE 管理の目的で、ASE が機能するために必要なネットワークリソースのドメインと Ip がいくつかあります。 Windows のみの ASE で<a href="https://docs.microsoft.com/en-us/azure/app-service/environment/network-info#ase-dependencies">は、ここに記載</a>されています。また、ASE ポータルにも表示されます。 これらの受信および送信アクセスの依存関係に加えて、Linux/コンテナーには次のような他の依存関係があります。</p>


  <ul>
   <li>docker.io</li>
   <li>ubuntu.com</li>
   <li>docker.com</li>
   <li>treasuredata.com</li>
   <li>mono-project.com</li>
  </ul>


  <p><strong>Q:</strong> ASE に Docker Compose/Kubernetes Config を使用して複数コンテナーアプリをデプロイできますか?</p>


  <p><strong>A:</strong> ASE に複数コンテナーアプリをデプロイすることはできますが、Linux での App Service での複数コンテナーサービスはまだプレビュー段階です。 複数コンテナーアプリをデプロイする方法の詳細については、こちらを参照 <a href="https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-multi-container">してください。</a></p>


  <p><strong>Q:</strong> ASE 内のコンテナーに Function app をデプロイできますか。</p>


  <p><strong>A:</strong> ASE 内のコンテナーに関数アプリをデプロイすることはできますが、Linux 機能の機能はまだプレビュー段階です。 Linux アプリに関数をデプロイする方法の詳細については、こちらを参照 <a href="https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli-linux">してください。</a></p>
