### YamlMime:Yaml
ms.openlocfilehash: e8a87ebad05f597f236af3bac67fbd92a04e0e96
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910167"
Slug: announcing-app-service-environment-v2
Title: App Service Environment v2 リリースのお知らせ
Summary: Azure App Service Environment v2 と分離価格プランのリリースの発表
Content: >-
  <p>App Service Environment へのアップグレードを発表いたします。 App Service Environment (ASE) は、ネットワークの分離と拡張機能の向上を実現する、Azure App Service の強力 &nbsp; な機能を提供します。 これは基本的に、顧客 &rsquo; の Azure Virtual Network (VNet) のサブネットに Azure App Service をデプロイしたものです。 &nbsp;この機能は、ネットワーク制御と分離に関してお客様が探していることを顧客に提供していましたが、App Service のような &rdquo; PaaS ではありません &ldquo; でした。 私たちは、ASEv2 についてのフィードバックを受け取りました。その後、マルチテナント App Service の場合と同じようにユーザーエクスペリエンスを実現しながら、ASE が提供する特典を提供します。 わかりやすくするために、省略形 ASEv2 を使用して、新しい App Service Environment と初期バージョンを ASEv1 として参照します。</p>


  <h3>プランベースのスケーリングの App Service</h3>


  <p>App Service Plan (ASP) は、すべてのアプリが含まれているスケーリングコンテナーです。 ASP をスケーリングする場合は、ASP のすべてのアプリをスケーリングすることもできます。 これは、マルチテナント App Service および ASE に当てはまります。 つまり、アプリを作成するには、ASP を選択するか ASP を作成する必要があります。 ASEv1 で ASP を作成する場合、ASE を場所として選択し、ワーカープールを選択する必要がありました。 デプロイ &rsquo; するワーカープールの容量が不足している場合は、ASP を作成する前にワーカープールを追加する必要があります。</p>


  <p>ASEv2 では、ASP を作成するときに、現在の場所として ASE を選択しますが、ワーカープールを選択するのではなく、ASE の外部と同様に価格カードを使用します。 管理するワーカープールがこれ以上ありません。 ASP を作成または拡張すると、必要なワーカーが自動的に追加されます。 ASE 内の Asp とマルチテナントサービスの Asp を区別するために、分離されたという名前の新しい価格プランを作成しました。 ASP の作成時に分離価格プランを選択すると、関連する ASP を ASEv2 で作成する必要があることを意味します。 ASEv2 を既にお持ちの場合は、その場所と使用するワーカーのサイズとして ASE を選択するだけです。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e8a2f7b9-13fc-4220-8d29-4528b135dbae.png"><img alt="Creating an ASP in an ASEv2" border="0" height="319" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/edc274d3-f75c-43c1-9134-aec3df2051da.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="ASEv2 での ASP の作成" width="640"></a></p>


  <h3>ASE の作成</h3>


  <p>ASE の導入が制限されているその他の項目の1つは、機能の可視性でした。 多くのお客様は、ASE の機能が存在していることを認識していませんでした。 ASE を作成するには、アプリの作成とは完全に分離された ASE 作成フローを探す必要がありました。 ASEv1 では、Asp を作成するために、ワーカープールにワーカーを追加する必要があります。 これで、asp の作成時またはスケーリング時にワーカーが自動的に追加されるようになったので、ASEv2 作成エクスペリエンス教義を ASP 作成フローに配置できるようになりました。</p>


  <p>ASP の作成時に新しい ASEv2 を作成するには、ASE ではない場所を選択し、新しい分離された SKU カードの1つを選択します。 これを行うと、ASE 作成 UI が表示され、新しい VNet または既存の VNet に新しい ASEv2 を作成することができます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fda25968-0d56-464b-84b2-c2887a21c4cf.png"><img alt="Creating an ASE while creating an app" border="0" height="319" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a5814af3-9044-4885-a035-e777968b58f3.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="アプリの作成中に ASE を作成する" width="640"></a></p>


  <h3>その他の利点</h3>


  <p>システムアーキテクチャに加えられた変更により、ASEv2 には ASEv1 よりも多くの利点があります。 ASEv1 を使用すると、既定のスケールの最大値は50ワーカーでした。 ASEv2 では、既定の最大小数点以下桁数は100になりました。 つまり、最大100の ASP インスタンスを ASEv2 でホストできます。 これは、ASP 100 から100の個々の asp までのすべてのインスタンスと、その間に何でも存在する可能性があります。</p>


  <p>また、ASEv2 は Dv2 ベースの専用ワーカーを使用するようになりました。これは CPU &rsquo; の速度が向上し、コアと ssd あたりのメモリが2倍になっています。 新しい ASE 専用ワーカーのサイズは、1コア 3.5 GB、2コア 7 GB、および4コア 14 GB です。 最終的には、ASEv2 の1コアは ASEv1 の2コアよりも優れたパフォーマンスを発揮します。</p>


  <p>ASEv2 の詳細については、「 <a href="https://docs.microsoft.com/azure/app-service/app-service-environment/intro">App Service Environment の概要</a>」を参照してください。 ASE 関連のドキュメントの一覧については、App Service の <a href="https://docs.microsoft.com/azure/app-service/app-service-environment/readme">ドキュメント</a>も参照してください。</p>
