### YamlMime:Yaml
ms.openlocfilehash: 5c8208c00526848a247542cd7586f3673c17142d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895183"
Slug: announcing-the-preview-of-azure-shared-disks-for-clustered-applications
Title: クラスター化されたアプリケーション用の Azure 共有ディスクのプレビューの発表
Summary: この Azure のみの機能により、お客様は、フェールオーバーと高可用性のためのよく知られたデプロイパターンを損なうことなく、最も多くの IO 集中型ワークロードを実行できます。
Content: >-
  <div style="background:#eee;border:1px solid #ccc;padding:5px 10px;"><strong>2020 年7月17日に更新され</strong>ました。 Azure 共有ディスクの一般提供が開始されました。 詳細については、<a href="https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-azure-shared-disks-and-new-azure-disk-storage-enhancements/" target="_blank">Azure 共有ディスクの一般提供の発表に関するブログ記事と、新しい Azure Disk Storage の機能強化</a>に関する記事 &nbsp; をご覧ください。</div>


  <p>現時点では、 <b>業界 &rsquo; 初</b> の共有クラウドブロックストレージである Azure 共有ディスクの制限付きプレビューについて発表します。 Azure 共有ディスクは、Storage エリアネットワーク (san) 上で現在オンプレミスで実行されている最も要求の厳しいエンタープライズアプリケーションを含め、クラウドに移行するブロック記憶域ワークロードの次の波を可能にします。 これには、クラスター化されたデータベース、並列ファイルシステム、永続コンテナー、machine learning アプリケーションが含まれます。 この固有の機能により、高速フェールオーバーと高可用性のためのよく知られたデプロイパターンを損なうことなく、待機時間の影響を受けやすいワークロードを実行できます。 これには、Windows 用に構築されたアプリケーションや、<a href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/global_file_system_2/ch-overview-gfs2" target="_blank">グローバルファイルシステム 2</a> (GFS2) などの Linux ベースのクラスター化されたファイルシステムが含まれます。</p>


  <p>azure 共有ディスクを使用すると、お客様は Windows サーバーで実行されているクラスター化された環境を azure に移行できるようになりました (<a href="https://www.microsoft.com/cloud-platform/windows-server-2008">サポートが終了</a>した Windows server 2008 など)。 この機能は、Windows Server 上で実行される <a href="https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/always-on-failover-cluster-instances-sql-server?view=sql-server-ver15#Overview" target="_blank">SQL Server フェールオーバー クラスター インスタンス (FCI)</a>、<a href="https://docs.microsoft.com/en-us/windows-server/failover-clustering/sofs-overview" target="_blank">スケールアウト ファイル サーバー (SoFS)</a>、<a href="https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-plan-high-availability" target="_blank">リモート デスクトップ サーバー (RDS)</a>、および <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-high-availability-guide-wsfc-shared-disk" target="_blank">SAP ASCS/SCS</a> をサポートするように設計されています。</p>


  <p>この <a href="https://aka.ms/AzureSharedDiskPreviewSignUp" target="_blank">フォーム</a>に入力して、開始してアクセスを要求することをお勧めします。</p>


  <h2>Azure 共有ディスクの活用</h2>


  <p>Azure 共有ディスクは、現在、クラスター環境で実行されているアプリケーションに対して一貫したエクスペリエンスを提供します。 これは、現在 <a href="https://www.t10.org/members/w_spc3.htm" target="_blank">SCSI 永続的予約 (PR)</a> を利用しているすべてのアプリケーションが、この既知のコマンドセットを使用してクラスター内のノードをディスクに登録できることを意味します。 その後、アプリケーションは、1 つ以上のノードによるディスクに対する読み取りまたは書き込みについて、サポートされているさまざまなアクセス モードからいずれかを選択できます。 これらのアプリケーションは、可用性の高い構成でデプロイできます。また、Azure のディスク持続性の保証も利用できます。</p>


  <p>次の図は、2ノードのクラスター化されたデータベースアプリケーションの例を示しています。ノード間のフェールオーバーを調整します。<br>

  &nbsp;&nbsp; <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3cbaf477-16c9-40c2-80a4-f985f85d7058.png"><img alt="2-node failover cluster" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0c75bf54-5409-4ebf-b3c0-83b4f8b7cd14.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="モデル" width="907"></a><br>

  フローは次のとおりです。</p>


  <ol>
      <li>Azure VM 1 と &nbsp; AZURE vm 2 の両方で実行されているクラスター化アプリケーションは、ディスクへの読み取りまたは書き込みの目的を登録します。</li>
      <li>その後、Azure VM 1 上のアプリケーションインスタンスは、ディスクへの書き込みに排他的な予約を行います。</li>
      <li>この予約は Azure ディスクに適用され、データベースはディスクに排他的に書き込むことができるようになりました。 Azure VM 2 のアプリケーションインスタンスからの書き込みは成功しません。</li>
      <li>Azure VM 1 上のアプリケーションインスタンスがダウンした場合、Azure VM 2 のインスタンスは、データベースのフェールオーバーを開始し、ディスクを引き継ぐことができます。</li>
      <li>この予約は Azure ディスクに適用されるようになりました。 Azure VM 1 でのアプリケーションからの書き込みは受け入れられなくなります。 これで、Azure VM 2 のアプリケーションからの書き込みのみが受け入れられるようになります。</li>
      <li>クラスター化されたアプリケーションは、データベースのフェールオーバーを完了し、Azure VM 2 からの要求を処理できます。</li>
  </ol>


  <p>次の図は、複数のノードで構成されている複数のノード (Machine Learning モデルのトレーニングなど) を実行するために、ディスクからデータを読み取る複数のノードで構成されていることを示しています。<br>

  &nbsp;&nbsp; <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b0e465e7-1d9d-400d-be5f-6d61e1f55dac.png"><img alt="n-node cluster with multiple readers" border="0" height="760" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5e54ca2a-6f17-4a4a-833a-1646cb98caef.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="モデル" width="1024"></a><br>

  フローは次のとおりです。</p>


  <ol>
      <li>アプリケーションによって、すべての Virtual Machines レジスタがディスクに登録されます。</li>
      <li>その後、Azure VM 1 上のアプリケーションインスタンスは、他の Virtual Machines からの読み取りを開いたまま、ディスクへの書き込みに排他的な予約を行います。</li>
      <li>この予約は Azure ディスクに適用されます。</li>
      <li>これで、クラスター内のすべてのノードがディスクから読み取るれようになります。 クラスター内のすべてのノードに代わって、結果がディスクに書き戻されるのは1つのノードのみです。</li>
  </ol>


  <h2>ディスクの種類、サイズ、価格</h2>


  <p>Azure 共有ディスクはプレミアム ssd で利用でき、P15 (256 GB) を含むディスクのサイズをサポートしています。 Azure Ultra ディスクのサポートはまもなく提供される予定です。 Azure 共有ディスクは、(OS ディスクではなく) データディスクとしてのみ有効にすることができます。 Azure 共有ディスク (プレミアム ssd) に追加でマウントするたびに、ディスクサイズに基づいて課金されます。 限られたプレビュー料金の詳細については、 <a href="https://azure.microsoft.com/en-us/pricing/details/managed-disks/" target="_blank">Azure Disks の価格</a> に関するページを参照してください。</p>


  <h2>Azure 共有ディスクと Azure Files</h2>


  <p>Azure 共有ディスクは、複数の仮想マシンで利用できるブロック記憶域への共有アクセスを提供します。 ノード間の通信には、 <a href="https://docs.microsoft.com/en-us/windows-server/failover-clustering/failover-clustering-overview" target="_blank">Windows Server フェールオーバークラスター (WSFC)</a>、 <a href="https://wiki.clusterlabs.org/wiki/Pacemaker" target="_blank">Pacemaker</a>、 <a href="https://corosync.github.io/corosync/">corosync</a>などの一般的な Windows および Linux ベースのクラスターマネージャーを使用し、書き込みロックを有効にする必要があります。 サーバーメッセージブロック (SMB) プロトコルまたはネットワークファイルシステム (NFS) プロトコルを使用してアクセスできる、完全に管理されたファイルサービスを azure で探している場合は、「 <a href="https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-create-premium-fileshare" target="_blank">azure プレミアムファイル</a>」または「 <a href="https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-quickstart-set-up-account-create-volumes?tabs=azure-portal" target="_blank">Azure NetApp Files</a>」を参照してください。</p>


  <h2>作業の開始</h2>


  <p>Azure Resource Manager テンプレートを使用して Azure 共有ディスクを作成できます。 プレビューで Azure 共有ディスクの使用を開始する方法の詳細については、 <a href="https://aka.ms/azureshareddiskdocs" target="_blank">ドキュメントのページ</a>を参照してください。 リージョンの可用性と Ultra ディスクの可用性に関する更新については、「 <a href="https://aka.ms/azurediskfaq" target="_blank">Azure Disks</a>に関する FAQ」を参照してください。 ここでは、Azure 共有ディスクをカバーする Microsoft Ignite 2019 の Mark Russinovich の <a href="https://myignite.techcommunity.microsoft.com/sessions/82058" target="_blank">ビデオ</a> を示します。</p>


  <p>今後数週間にわたって、ポータルと SDK のサポートを有効にする予定です。 Azure Backup と &nbsp; Azure Site Recovery のサポートは現在使用できません。 すべてのディスク操作の詳細な手順については、 <a href="https://aka.ms/azuredisksdocs" target="_blank">Managed Disks のドキュメント</a> を参照してください。</p>


  <p>プレビューへの参加をご希望の場合は、 <a href="https://aka.ms/AzureSharedDiskPreviewSignUp" target="_blank">アクセスを要求</a>することで開始できます。</p>
