### YamlMime:Yaml
ms.openlocfilehash: 22e169ae2378d0a4a6b6de599a28baa1ceb3bdd4
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910128"
Slug: announcing-the-public-preview-for-adaptive-application-controls
Title: アダプティブアプリケーション制御のパブリックプレビューの発表
Summary: 'Microsoft Ignite では、ホワイトリストルールを使用してアプリケーションをマルウェアから保護する新しいアダプティブアプリケーション制御を発表しました。 現時点では、これらの機能を Azure Security Center のパブリックプレビューで利用できることをご紹介します。 '
Content: >-
  <p>Microsoft Ignite では、ホワイトリストルールを使用してアプリケーションをマルウェアから保護する <a href="https://azure.microsoft.com/en-us/blog/azure-security-center-extends-advanced-threat-protection-to-hybrid-cloud-workloads/">新しいアダプティブアプリケーション制御を発表</a> しました。 現時点では、これらの機能を Azure Security Center のパブリックプレビューで利用できることをご紹介します。&nbsp;</p>


  <p>ホワイトリストに登録するなどのアプリケーション制御を使用すると、悪意のある悪意のあるアプリケーションへの露出を制限できます。 アプリケーション制御では、急速に進化するマルウェアや新しいエクスプロイトに対応するのではなく、すべての既知の良好なアプリケーションをブロックするだけです。 通常は固定された一連のアプリケーションを実行する専用サーバーでは、大規模な保護を追加できます。 現時点では、アプリケーション制御ソリューションは既に存在していましたが、通常、サーバーやサーバーグループごと、および大規模で一意のルールが必要な場合は、複雑で管理が困難です。</p>


  <p>アダプティブアプリケーション制御では、machine learning を利用して Azure 仮想マシンの動作を分析し、アプリケーションのベースラインを作成し、仮想マシンをグループ化して、適切なホワイトリスト登録規則を推奨し、自動的に適用します。 これらのルールのアラートを表示、変更、および受信するには Azure Security Center を使用します。</p>


  <p>現在、アダプティブアプリケーション制御は、Azure で実行されている Windows の仮想マシン (すべてのバージョン、クラシックまたは Azure Resource Manager) で利用できます。 開始するには、Security Center を開き、[アプリケーションホワイトリスト] タイルを選択します。</p>


  <h2>アダプティブアプリケーション制御を有効にし、ポリシーを適用する</h2>


  <p>[アダプティブアプリケーション制御] ブレードでは、選択した仮想マシンのグループの適応型アプリケーション制御を簡単に有効にすることができます。 推奨事項を表示し、最初は監査モードで実行を許可するアプリケーションを決定し、アプリケーションがルールに違反した場合にアラートを受け取るポリシーを作成することができます。 独自のポリシーを作成して適用すると、アプリケーションの保護が強化され、管理の複雑さが軽減されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2d0c9526-e120-4cf1-a7b5-5bbe588a9723.png"><img alt="image" border="0" height="366" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f69bdc14-9381-4ad5-811b-ae62e4aee075.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="626"></a></p>


  <h2>アダプティブアプリケーション制御ポリシーの監視と編集</h2>


  <p>[アダプティブアプリケーション制御] ブレードでは、アダプティブアプリケーション制御ポリシーを使用して構成された仮想マシンの既存のグループを簡単に管理および監視できます。 特定のグループ内の Vm に適用されているホワイトリスト登録の規則を表示および変更し、それらの規則の違反についてアラートを受け取ることができます。 また、特定のアダプティブアプリケーション制御ポリシーが適用されるモードを変更し、強制モードを使用して未承認のアプリケーションのブロックを開始することもできます。 アプリケーションのセキュリティ対策を可視化することによって、制御を維持できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7baaabe4-8ef2-40b4-8e5d-f4a2993ae139.png"><img alt="image" border="0" height="373" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1edb65bb-7a87-4afa-be43-e1533429e3ab.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="626"></a></p>


  <p>これらの新機能は Azure Security Center の standard 価格レベルでご利用いただけます。最初の60日間 <a href="https://azure.microsoft.com/en-us/">無料でお試し</a> いただけます。</p>


  <p>アダプティブアプリケーション制御の詳細については、 <a href="https://aka.ms/asc-applicationwhitelisting">ドキュメント</a> を参照してください。</p>
