### YamlMime:Yaml
ms.openlocfilehash: 4e0b143ac262f5abda1e58807b3d0861f2bdce5e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904350"
Slug: announcing-azure-service-health-general-availability-configure-your-alerts-today
Title: 一般提供 Azure Service Health の発表-今すぐアラートを構成する
Summary: 本日、Azure サービスの問題が影響を受ける場合のガイダンスとサポートを提供するパーソナライズされたダッシュボードである Azure Service Health の一般提供 (GA) を発表します。
Content: >-
  <p>本日、Azure サービスの問題が影響を受ける場合のガイダンスとサポートを提供するパーソナライズされたダッシュボードである <strong>Azure Service Health</strong>の一般提供 (GA) を発表します。 一般的な状態情報を提供するパブリック <a href="https://status.azure.com/" target="_blank">ステータスページ</a> とは異なり、Azure Service Health はリソースに合わせて調整された情報を提供します。 また、リソースの可用性に影響する可能性がある計画済みメンテナンスやその他の変更の準備にも役立ちます。 Azure Service Health を使用すると、アラートを簡単に構成して、関連するチームに、リソースに影響するサービス正常性イベントが通知されるようにすることができます。</p>


  <p>2017年7月に Azure Service Health のプレビューを開始しました。 お客様のフィードバックに基づいてサービスを進化させてきました。これには Service Health アラートの統合も含まれます。 まだ行っ &rsquo; ていない場合は、 <a href="https://www.aka.ms/ash-alerts" target="_blank">Service Health アラートを設定</a>します。</p>


  <p>次の短いビデオを視聴して Azure Service Health の動作を確認してください。</p>


  <p><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Blogs/Azure/Azure-Service-Health/player" width="960"></iframe></p>


  <p>Azure Service Health のカスタマイズされたダッシュボードから <strong>、</strong> 次のものを表示できます。</p>


  <p><strong>サービスの問題</strong> &ndash; リソースに影響を与える Azure サービスの継続的な問題。 問題がいつ開始され、どのサービス、リージョン、および特定のリソースが影響を受けているかをすばやく把握します。 懸案事項を参照するリンクをチームと共有するか、PDF の概要をダウンロードして、Azure portal へのアクセス権を持たないユーザー &rsquo; と共有します。</p>


  <p><strong>計画済みメンテナンス</strong> &ndash; リソースに影響を与える、Azure の今後のメンテナンスアクティビティ。 メンテナンスがいつ開始されるかを理解します。 また、仮想マシンのメンテナンスの場合は、Service Health 影響を受ける Vm の正確な一覧も表示され、スケジュールに従ってメンテナンスを実行することができます。</p>


  <p><strong>正常性の勧告</strong> &ndash; 以前の Azure 機能が廃止された場合や使用量クォータを超えた場合など、ダウンタイムを防止するための推奨アクションの概要。</p>


  <p><strong>正常性の履歴</strong> &ndash; 問題が解決された後のインシデントの概要など、リソースの正常性に影響を与えた過去のサービスの問題。<br>

  リソースのリソース正常 &ndash; 性のリソースレベルの正常性の洞察。 特定のリソース (VM など) を検索して、現在または過去の正常性の問題を確認します。</p>


  <p><strong>正常性アラート</strong> &ndash; Service Health イベントのプロアクティブ通知。 アラートを作成して、特定のサブスクリプション、サービス、またはリージョンを選択し、電子メール、SMS、webhook、Azure mobile app などを使用して &ndash; アラートを生成するアクショングループを作成します。</p>


  <p>Service Health アラートは完全に構成可能であるため、組織内の適切なユーザーに適切な通知を行うことができます。 次に例を示します。</p>


  <ul>
      <li>テスト/開発サブスクリプションのリソースが影響を受けたときに開発チームに <strong>電子メールを送信 </strong>するアラート</li>
      <li>運用サブスクリプションのリソースが影響を受けたときに <strong>webhook </strong>を使用して ServiceNow を更新するアラート</li>
      <li>特定のリージョンのリソースが影響を受けたときに、特定の数に <strong>SMS </strong>を送信するアラート</li>
  </ul>


  <p><a href="https://www.aka.ms/ash-portal" target="_blank">まず</a> 、サービス正常性アラートを作成してみましょう。</p>


  <p>最後に、Azure portal の右上隅にある [フィードバック] ボタンを選択する <strong>Azure Service Health</strong> &ndash; についてのフィードバックをお寄せいただき、気に入った点と改善点についてお知らせします。</p>


  <h2>リソース</h2>


  <p><a href="https://www.aka.ms/ash-acom" target="_blank">Azure Service Health &ndash; の概要] ページ</a></p>


  <p><a href="https://www.aka.ms/ash-docs" target="_blank">Azure Service Health &ndash; のドキュメント</a></p>


  <p><a href="https://www.aka.ms/ash-portal" target="_blank">Azure portal 内の Azure Service Health &ndash;</a></p>
