### YamlMime:Yaml
ms.openlocfilehash: b759e771a49d1105d6e698b37deb5b03db3872a4
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139896655"
Slug: announcing-full-powershell-cmdlet-support-for-azure-automation
Title: PowerShell コマンドレットの完全なサポートを発表Azure Automation
Summary: 質問して、回答しました。 この週は、新しいモジュールの最新バージョンのリリースAzure PowerShell示します。 この更新プログラムには、アカウント、資産、スケジュールされた Runbook の新しいコマンドレットが含まれています。
Content: >-
  質問して、回答しました。 この週は、最新バージョンの Azure PowerShell モジュールのリリースと、Azure Automation を管理するための <strong>23</strong> の新しい <strong>PowerShell</strong> <strong></strong> コマンドレットと共に、PowerShell ISE/コンソール内または <a href="https://azure.microsoft.com/blog/2014/08/20/azure-automation-capabilities-in-depth-the-azure-automation-powershell-cmdlets/">Azure Automation</a> Runbook 内でローカルにリリースされます。 この更新プログラムには、アカウント、資産、スケジュールされた Runbook の新しいコマンドレットが含まれています。


  &nbsp;

  <h2>新しいコマンドレット:</h2>

  <ul>
      <li>New-AzureAutomationAccount</li>
      <li>Remove-AzureAutomationAccount</li>
      <li>Get-AzureAutomationScheduledRunbook</li>
      <li>New-AzureAutomationVariable</li>
      <li>Set-AzureAutomationVariable</li>
      <li>Remove-AzureAutomationVariable</li>
      <li>Get-AzureAutomationVariable</li>
      <li>Get-AzureAutomationCredential</li>
      <li>New-AzureAutomationCredential</li>
      <li>Remove-AzureAutomationCredential</li>
      <li>Set-AzureAutomationCredential</li>
      <li>Get-AzureAutomationCertificate</li>
      <li>New-AzureAutomationCertificate</li>
      <li>Set-AzureAutomationCertificate</li>
      <li>Remove-AzureAutomationCertificate</li>
      <li>Get-AzureAutomationConnection</li>
      <li>New-AzureAutomationConnection</li>
      <li>Remove-AzureAutomationConnection</li>
      <li>Set-AzureAutomationConnectionFieldValue</li>
      <li>Get-AzureAutomationModule</li>
      <li>New-AzureAutomationModule</li>
      <li>Set-AzureAutomationModule</li>
      <li>Remove-AzureAutomationModule</li>
  </ul>

  &nbsp;

  <h2>注意が必要な更新プログラム:</h2>

  <ul>
      <li>Get-AzureAutomationJobジョブの状態に対するサーバー側のフィルター処理がサポートされる</li>
  </ul>

  &nbsp;


  MSDN の Azure Automation コマンドレットの詳細については、こちらを参照するか、<a href="https://msdn.microsoft.com/en-us/library/dn690262.aspx"></a>最新の Azure PowerShellインストール<a href="https://azure.microsoft.com/en-us/documentation/articles/install-configure-powershell/">してください</a>。


  &nbsp;


  次のAzure Automation?このサービスについては、こちらを <a href="https://aka.ms/Q2p1ap" target="_blank">確認し</a>、Twitter のAzure Automation <a href="https://twitter.com/AzureAutomation" target="_blank">に従ってください</a>。


  個人的に連絡を取りたい場合は、 ブログで連絡 <a href="https://jodoglevy.com" target="_blank">するか、</a> Twitter でフォロー <a href="https://twitter.com/jodoglevy" target="_blank">してください</a>。


  今後の機能について、Azure Automationエンジニアリング チームと関わりを持ち合お考えですか? 短いアンケート <a href="https://microsoft.qualtrics.com/SE/?SID=SV_0VAgcjc4xF2CDvn">に記入</a> すると、連絡します。
