### YamlMime:Yaml
ms.openlocfilehash: 58425bad5d9a255995e24c7b0741fa0e1501c432
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891261"
Slug: announcing-azure-spring-cloud-enterprise-fully-managed-vmware-tanzu-components-and-configurability-for-spring-boot-apps
Title: Azure spring Cloud Enterprise の発表-完全に管理された VMware Tanzu コンポーネントと Spring Boot アプリの高度な構成
Summary: Azure spring Cloud Enterprise は、エンタープライズ開発者のニーズに合わせて最適化された Spring 用の管理されたサービスです。 Vmware と協力して、Microsoft のクラウドプラットフォームの専門知識を VMware Tanzu ポートフォリオのイノベーションと組み合わせることができました。 Azure Spring Cloud Enterprise は、構成、統合、柔軟性、サポートに関するエンタープライズ要件に対応するために構築された商用の Tanzu コンポーネントを追加します。
Content: >-
  <p>2019では、Microsoft および非常に重要な (VMware) は、Spring Boot アプリケーション用の完全に管理されたサービスである <a href="https://azure.microsoft.com/en-us/services/spring-cloud/" target="_blank">Azure Spring Cloud</a>を発表しました。 企業の開発者が大規模に Spring Boot アプリケーションを実行する際に直面する一般的な課題の多くを解決するために、を設定しています。 このサービスは、動的スケーリング、セキュリティ修正プログラム、 &nbsp; 監視のためのすぐに使用できるインストルメンテーションを &nbsp; 管理し &nbsp; 、開発者がアプリに専念できるようにします。 その後、 <a href="https://www.youtube.com/watch?v=EfgiW6xJseM" target="_blank">Kroger</a>、<a href="https://customers.microsoft.com/en-us/story/1358540087031302788-swiss-re-accelerates-java-app-modernization-using-azure-spring-cloud" target="_blank">スイスの Re</a>、 <a href="https://customers.microsoft.com/en-us/story/1388620728739667057-raleys-uses-azure-spring-cloud-to-optimize-scale-and-drive-innovation" target="_blank">Raley &rsquo; </a>、<a href="https://devblogs.microsoft.com/java/deploy-spring-boot-applications-by-leveraging-enterprise-best-practices/" target="_blank">デジタル</a>性を含む多くのお客様と協力して、サービスの導入を支援してきまし &rsquo; た。</p>


  <p>さらに、いくつかのお客様についても学習しました。 多くの場合、オンプレミスで数千の Spring Boot アプリケーションを実行していて、Spring 近代化プロジェクトを加速させる高度な機能が必要です。 Microsoft では、学習に基づいて、企業のお客様のニーズを満たすために、市販にサポートされているコンポーネントを備えた新しい Azure Spring Cloud レベルで作業を開始しました。 ここでは、プレビュー段階で Azure Spring Cloud Enterprise &nbsp; の &nbsp; 可用性について発表します。</p>


  <p>Azure spring Cloud Enterprise は、エンタープライズ開発者のニーズに合わせて最適化された Spring 用の管理されたサービスです。 Vmware と共同で、Microsoft のクラウドプラットフォームの専門知識と <a href="https://tanzu.vmware.com/tanzu" target="_blank">Vmware Tanzu</a> ポートフォリオのイノベーションを組み合わせることができました。 Azure Spring Cloud Enterprise &nbsp; は、構成、統合、柔軟性、サポートに関するエンタープライズ要件に対応するために構築された商用の Tanzu コンポーネントを追加します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/09012c5c-aa23-4153-b937-f67901515176.png"><img alt="Img 1" border="0" height="640" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/68b9f2bf-7fd6-462c-95c7-5eef47919b40.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Img 1" width="1024"></a></p>


  <p><em><strong>図 1:</strong> &nbsp;Azure Spring Cloud の価格レベルの選択の例 &mdash; </em><em>(Enterprise レベルを含む)</em></p>


  <h2>商用の VMware Tanzu コンポーネント</h2>


  <p>azure Spring Cloud Enterprise では、お客様は、管理された azure インフラストラクチャに関して、お客様が認識している VMware Tanzu コンポーネントを使用できます。 Tanzu Build Service、Tanzu Application Configuration Service、および Tanzu Service Registry は、プレビュー期間中に利用できます。 お客様は、インスタンスの作成中または作成後に、必要な Tanzu コンポーネントを柔軟 &nbsp; に選択できます。 Microsoft と VMware は引き続き、Tanzu spring cloud Gateway や spring cloud Data Flow * などのさらに多くの Tanzu コンポーネントをサービスに追加し、顧客に価値を高めます。</p>


  <p>* Azure Spring Cloud Enterprise ロードマップは確認されず、変更される可能性があります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f6337412-d824-4632-ba21-93d1a906c18a.png"><img alt="VMware Tanzu settings and component selection in Azure portal" border="0" height="640" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a83ba9e9-aad9-4a61-9fd1-aed64b4b7eee.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="図2" width="1024"></a></p>


  <p><em><strong>図 2:</strong>Azure portal での VMware Tanzu の設定とコンポーネントの選択の例 &mdash;</em></p>


  <h2>高度な設定と柔軟性</h2>


  <p>多くの場合、大規模な企業では複雑なワークフローがあり、環境や開発プロセスのために追加の構成オプションが必要になります。 Tanzu ビルドサービスでは、コンテナーの作成とガバナンスを自動化する、カスタマイズ可能な Buildpack 構成がサポートされています。 また、開発者 &nbsp; は、無制限のスケーリングとグローバルデプロイオプションを使用して azure プラットフォームの完全なメリットを得られるだけでなく、azure サービスとの統合も実現します。 また、お客様は、Tanzu コンポーネント上に構築された既存の spring ワークロードを、サービスを使用してオンデマンドの spring cloud infrastructure を提供することで、Azure spring cloud Enterprise に移行することができます。</p>


  <h2>Spring Runtime のサポート</h2>


  <p>Azure spring Cloud Enterprise &nbsp; には、spring プロジェクトの VMware spring Runtime サポートが含まれています。 これにより、Spring の専門家にアクセスし、エンタープライズでの使用を目的として設計された、一般的な Spring プロジェクトにアクセスできます。 専門家の支援を受けて、Spring エコシステムの可能性を最大限に引き出し、Spring アプリケーション開発をすぐに始められるようにすることができます。</p>


  <h2>Azure と完全に統合</h2>


  <p>azure Spring Cloud Enterprise は、完全に管理された環境で azure 上で実行されます。 Azure のすべてのメリットが得られます。経験はなじみのある直感的なものです。 任意 &mdash; のプロビジョニングツール Azure portal、Azure CLI、Azure Resource Manager テンプレート、または Terraform を使用してインスタンスを作成するだけです。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c2abdc63-976c-453c-9e4c-8d0328a1b808.png"><img alt="Azure Spring Cloud Enterprise creation review" border="0" height="640" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c86bd4e1-c848-45e8-bbb2-37c0b73a0ca7.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="図3" width="1024"></a></p>


  <p><em><strong>図 3:</strong> &nbsp;Azure Spring Cloud Enterprise 作成レビューの例 &mdash;</em></p>


  <p>インスタンスを作成してアプリケーションを展開した後は、任意の Application Insights またはその他のアプリケーションパフォーマンス管理 (APM) ツールで簡単に監視できます。 standard レベルと同様に、Azure Spring Cloud &nbsp; Enterprise には、ログ、メトリック、分散アプリのトレース、アラートを集計するためのすぐに使用できるサポートが付属しています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d22f56c3-93fb-4f8c-88d8-2e36b7bd301e.png"><img alt="Application transactions are visible through Application Insights “Application Map”" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6776cae7-a04c-4b0f-8c56-ca1fbe51960d.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="図4" width="960"></a></p>


  <p><em><strong>図 4:</strong> &nbsp;Application Insights &ldquo; アプリケーションマップを通じて表示されるアプリケーショントランザクション &nbsp; の例 &mdash;&rdquo;</em></p>


  <h2>はじめに</h2>


  <p>Azure Spring Cloud Enterprise には、高度な構成機能とマネージ Tanzu コンポーネントが用意されています。これらのコンポーネントはすべて、お客様が VMware と Microsoft の期待する企業によって支えられています。 サービスを試して、フィードバック &mdash; を共有することをお勧めし<a href="https://aka.ms/spring-cloud-enterprise" target="_blank">ます。 [Contact Me] をクリック &quot; して、プレビューにサインアップしてください。 &quot; </a> &nbsp;</p>


  <p>また、<a href="https://tanzu.vmware.com/content/blog/introducing-azure-spring-cloud-enterprise-tier" target="_blank">VMware からの Azure Spring Cloud Enterprise の</a>詳細について &nbsp; も学習できます。</p>
