### YamlMime:Yaml
ms.openlocfilehash: 3e04dbe549191e344efe761d4ddbf3bce976eb5d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895199"
Slug: announcing-the-general-availability-of-azure-application-insights-sdk-for-node-js-1-0
Title: Node.js 1.0 用 Azure アプリケーションインサイト SDK の一般提供を発表します。
Summary: Microsoft では、Azure で Node.js アプリを構築して実行する開発者のために、優れたエクスペリエンスを実現することを約束しています。 現在、Azure アプリケーションの一般提供を発表しています...
Content: >-
  <p>Microsoft では、Azure で Node.js アプリを構築して実行する開発者のために、優れたエクスペリエンスを実現することを約束しています。 現時点では、 <a href="https://docs.microsoft.com/en-us/azure/application-insights/" target="_blank">Azure アプリケーションインサイト SDK for Node.js 1.0</a>の一般公開が発表されました。これは、多くの成功イテレーションの概念であり、お客様からのフィードバックをリッスンするように構築されています。</p>


  <p>Application Insights は、アプリケーション<strong>、サービス、およびコンポーネント</strong>を展開した後、運用環境で監視するアプリケーションパフォーマンス管理ツールです。これにより、<strong>パフォーマンスのボトルネックやその他の問題を検出し、迅速に診断</strong>することができます。 <a href="https://github.com/Microsoft/ApplicationInsights-node.js/releases" target="_blank">1.0 リリース</a>では、主に Node.js 用の Application Insights SDK のパフォーマンス、信頼性、安定性が向上しています。</p>


  <p>Node.js 用の Application Insights SDK は<a href="https://github.com/Microsoft/ApplicationInsights-node.js/" target="_blank">GitHub でホスト</a>されているオープンソースプロジェクトです。</p>


  <h2>作業の開始</h2>


  <p>インサイト Azure アプリケーションを初めて使用する場合は、Node.js アプリケーションまたはサービスの監視を設定するための詳細な手順について説明している「<a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs" target="_blank">入門ガイド」</a>を参照してください。 Node.js アプリを実行している場所に関係なく Application Insights を使用できます。 Azure またはオンプレミスの Virtual Machines、Linux での<a href="https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-nodejs" target="_blank">Web Apps</a>、<a href="https://azure.github.io/azure-iot-sdk-node/" target="_blank">モノのインターネット</a>デバイスと電子デスクトップアプリでも使用できます。 必要なのは、アプリケーションに数行のコードを挿入して、実稼働環境での問題の診断に役立つ使用状況のテレメトリとデータの取得を開始することだけです。</p>


  <h2>アプリケーション マップ</h2>


  <p><a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-app-map" target="_blank">アプリケーションマップ</a> は、アプリケーションコンポーネントの依存関係の視覚的なレイアウトです。 負荷やパフォーマンス、エラー、アラートといった KPI がコンポーネントごとに表示されるので、パフォーマンスの問題やエラーの原因となっているコンポーネントを容易に検出することができます。 任意のコンポーネントから、Application Insights イベントなどのより詳細な診断に移動できます。 アプリで azure サービスを使用している場合は、azure 診断と推奨事項 (SQL Database Advisor によって提供されるものなど) をクリックすることもできます。 Node.js 用の Application Insights SDK の1.0 リリースでは、この領域にいくつかの機能強化が加えられており、Redis、MongoDB、PostgreSQL などのサードパーティ製品とサービスのアイコンを表示することで、依存関係を簡単に識別できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e90f4bd4-906f-4103-9685-5c5be7a358e7.png"><img alt="1101" border="0" height="484" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/487d816c-3b79-41ec-a7ba-412348e0200f.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="1101 " width="1024"> </a> この<a href="https://github.com/Microsoft/ApplicationInsights-node.js/issues" target="_blank">機能を試し</a>て、ニーズに合わせてアプリケーションマップに表示する他のことをお知らせください。</p>


  <h2>NPM モジュールのサポートの強化</h2>


  <p>Node.js は、サードパーティのモジュールエコシステムからのものであり、NPM に何千ものパッケージが含まれています。 現在、Node.js アプリケーションではこれまで以上に NPM パッケージが使用されています。多くの場合、複雑な問題を実際に診断できるように、これらのモジュールから洞察を得る必要があります。 Application Insights は、すぐに使用できる優れた診断エクスペリエンスを提供し、アプリケーション全体 (依存関係を含む) の詳細な診断情報を提供することを目的としています。 Node.js 用の Application Insights SDK の1.0 リリースでは、2つの追加モジュールに自動インストルメンテーションが追加されました。 <a href="https://www.npmjs.com/package/pg" target="_blank">PostgreSQL</a> と <a href="https://www.npmjs.com/package/winston" target="_blank">winston</a> logging framework は、すぐにサポートされる npm パッケージの一覧と、 <em>bunyan</em>、 <em>console、mongodb、mongodb-core、mysql、redis、</em> および <em>pg プール</em>に参加しています。</p>


  <h2>このリリースでの重大な変更</h2>


  <p>互換性に影響する変更は、常にハード的に決定されるため、 &rsquo; 軽く使用することはありません。 しかし、他の Application Insights sdk との一貫性を保ち、将来の拡張を可能にするために、このリリースには api 間の重大な変更もいくつか含まれています。 新しいメソッドとプロパティの名前、および移行手順については、GitHub プロジェクトページの<a href="https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/README.md" target="_blank">README</a>を参照してください。 また、この SDK の既定の構成は、アプリがオフラインのときに、既定でテレメトリをディスクに保存することによって変更されています。</p>


  <h2>試してみる</h2>


  <p><a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs" target="_blank">Node.jsの Application Insights</a>を試して、現在の Node.js アプリとサービスの監視を開始するためのすべてのことをお勧めします。</p>


  <p>お客様からのフィードバックに基づいて、より多くのサードパーティモジュールを自動的にインストルメント化し、アプリケーションマップの統合とコンテキストの追跡を向上させることで、お客様 &rsquo; のエクスペリエンスをさらに強化します。</p>


  <p>ご意見をお聞かせください。質問がある場合や、Application Insights SDK for Node.js の問題が発生している場合は、GitHub の<a href="https://github.com/Microsoft/ApplicationInsights-node.js/issues/" target="_blank">プロジェクトページ</a>で問題を開いてください。</p>
