### YamlMime:Yaml
ms.openlocfilehash: ae318de27788681eb52c4f7b8465bb64091d724f
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890891"
Slug: announcing-the-1-0-0-release-of-application-insights-windows-sdks
Title: Application Insights Windows sdk の1.0.0 リリースの発表
Summary: Application Insights Windows sdk が1.0.0 マイルストーンに達したことをお知らせします。 1.0.0 マイルストーンに達したことにより、SDK の変更に関する安定性が向上し、サポート期間が長くなります。
Content: >-
  Application Insights Windows sdk が1.0.0 マイルストーンに達したことをお知らせします。 1.0.0 マイルストーンに達したことにより、SDK の変更に関する安定性が向上し、サポート期間が長くなります。 引き続き SDK の機能強化と新機能をご利用いただけますが、今後、この SDK バージョンでは互換性に影響する変更を避けることができます。 1.0.0 SDK には、エクスペリエンスを向上させるためにいくつかの API の変更と、安定性とパフォーマンスの向上に関する修正が含まれています。 変更の完全な一覧については、 <a href="https://go.microsoft.com/fwlink/?LinkID=616551">リリースノート</a>を参照してください。

  <h2>サポートされているプラットフォーム</h2>

  Application Insights は、現在使用している可能性のある多くのアプリケーションの種類をサポートしており、追加のプラットフォームのサポートを迅速に追加しています。 Application Insights、あらゆる環境でアプリケーションをサポートすることに努めています。

  <ul>
      <li>ASP.Net Web アプリケーション</li>
      <li>Windows アプリケーション</li>
      <li>Java Web アプリケーション</li>
  </ul>

  その他のサポートされているプラットフォーム (1.0.0 が近日公開予定)

  <ul>
      <li>Javascript ベースの Web ページ</li>
      <li>iOS</li>
      <li>Mac OS X</li>
      <li>Android</li>
      <li>PHP</li>
      <li>Python</li>
      <li>Ruby</li>
      <li>node.js</li>
  </ul>

  サポートされているすべてのプラットフォームの詳細については、「作業の開始 <a href="https://azure.microsoft.com/documentation/articles/app-insights-platforms/">」を参照</a> してください。 Sdk がアプリケーションにコンパイルされると、実行されているすべてのコードを完全に理解することが重要になります。 これをサポートするために、すべての sdk がオープンソースであるか、オープンソースであることがわかります。詳細については、 <a href="https://github.com/Microsoft/ApplicationInsights-Home">GitHub ホーム</a>にアクセスするか、投稿をお寄せください。

  <h2>Sdk の機能</h2>

  Sdk には、すぐに使用できる自動テレメトリキャプチャの豊富なセットが用意されています。 <a href="https://azure.microsoft.com/documentation/articles/app-insights-get-started/">Application Insights の</a>概要は、SDK をアプリケーションに統合して再構築するのと同じほど簡単です。 各プラットフォーム固有の SDK は、そのプラットフォームの最高値であるテレメトリを自動的に収集します。

  <h3></h3>

  <h3>Context プロパティ</h3>

  各 SDK は、各テレメトリ項目に共通のコンテキストプロパティのセットを自動的に入力します。 すべてのテレメトリ項目について収集することで、Application Insights ポータルで任意のテレメトリの種類の<a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/#segment-your-data">多次元スライス</a>を実行できます。 さらに、Sdk は userID や sessionID などの関連付け値を収集します。これにより、異なるテレメトリの種類間の相関関係が可能になります。 次の一覧は、SDK によって自動的に提供されるいくつかのコンテキストプロパティを示しています。 収集対象をより細かく制御する場合は、これらの値をすべてコードで指定できます。

  <ul>
      <li>アプリケーションのバージョン</li>
      <li>Language</li>
      <li>Locale</li>
      <li>Model Name</li>
      <li>OEM 名</li>
      <li>[ネットワークの種類]</li>
      <li>OS バージョン</li>
      <li>ブラウザーのバージョン</li>
      <li>UserId</li>
      <li>SessionId</li>
      <li>OperationId</li>
      <li>国/地域</li>
  </ul>

  <h3></h3>

  <h3>使用状況のテレメトリ</h3>

  すべてのクライアント Sdk は、基本的な <a href="https://go.microsoft.com/fwlink/?LinkID=616552">利用統計情報</a> を自動的に収集します。 これには、匿名方式でのユーザーとセッションの追跡が含まれます。 この基本的なテレメトリは、アプリケーションが成功していて、顧客が使用しているかどうかを理解するために不可欠です。 また、基本的な利用統計情報は無料で <a href="https://azure.microsoft.com/pricing/details/application-insights/">無制限</a> で、月ごとのクォータには課金されません。


  最近 (SDK 0.17 では、現在は 1.0)、ユーザーとセッションのカウント方法に重要な変更が加えられました。 今日までは、"セッション" の定義は広範なものでした。セッションは、ユーザーまたは別のコンピューティングエンティティ (たとえば、RESTful エンドポイントを呼び出す別のアプリ) によって発生する可能性があります。これは、多くの場合に混乱し、メトリック値が大きくなる可能性があります。 SDK 1.0 を開始すると、Application insights のセッションは "ユーザーセッション" を意味します。 この変更の影響は次のとおりです。

  <ul>
      <li>ASP.NET と Java Web sdk では、ユーザーとセッションの cookie が生成されなくなりましたが、JavaScript SDK を使用してこれらを提供しています。Web アプリのユーザーとセッションの追跡を実装するために、JS SDK によるインストルメンテーションが必要になりました。</li>
      <li>SDK 1.0 でインストルメント化されたアプリでは、ユーザーとセッションの数が少なくなる可能性があります。特に、ユーザーが発信していない呼び出しの重要度が低いアプリの場合には、</li>
  </ul>

  詳細については、 <a href="https://azure.microsoft.com/documentation/articles/app-insights-release-notes-dotnet/">リリースノート</a> と <a href="https://azure.microsoft.com/documentation/articles/app-insights-web-track-usage/#sessions">ドキュメントのページ</a>を参照してください。

  <h3>ページ ビュー</h3>

  また、Sdk はページビューテレメトリを自動的に収集します。 Web アプリケーションの場合は、従来のビューを使用して、pageviews とページビューのパフォーマンスを最大限に活用できます。 モバイルデバイスアプリの場合、Sdk は各プラットフォームの UI ビューのレンディングを表すページビューを収集します。 これにより、ユーザーがアプリケーションに関与しているかどうかを把握できるだけでなく、アプリケーションのどの部分が最も頻繁に使用されているかを把握することができます。

  <h3>クラッシュと例外</h3>

  アプリケーション内の障害を診断できることは、製品の成功にとって非常に重要です。 困難な障害の診断を支援するために、AppInsights SDK は、 <a href="https://azure.microsoft.com/documentation/articles/app-insights-windows-crashes/">クライアントアプリのクラッシュ</a> と <a href="https://azure.microsoft.com/documentation/articles/app-insights-asp-net-exceptions/">サーバーのエラーと例外</a>に関連するテレメトリを収集します。 Sdk では、この診断情報の収集に膨大な量の値を提供し、アプリの障害モードについて深い洞察を得ることができます。 IOS のクラッシュの場合、これにはコンピューターコードのクラッシュレポートを読み取り可能なスタックトレースに変換するための、シンボル認証のサポートが含まれます。 サーバーアプリの場合、これにより、要求の失敗と依存関係のエラーとの関連付けが可能になります。

  <h3>要求と依存関係のテレメトリ</h3>

  サーバーおよびサービスアプリケーションでは、Web Sdk と Java Sdk によって、すべての受信プロセス要求の自動テレメトリコレクションと、すべての出力依存関係呼び出しの詳細が提供されます。 この情報は、サーバーアプリの <a href="https://azure.microsoft.com/documentation/articles/app-insights-web-monitor-performance/">パフォーマンス</a> と運用上の特性を理解するために重要です。 Sdk は、期間とパフォーマンス、状態コード、および他のテレメトリデータとの相関関係に関する情報など、データ収集の詳細レベルを提供します。

  <h3>パフォーマンス カウンター</h3>

  Application Insights sdk は、アプリケーションが実行されているコンピューターのパフォーマンスカウンターを収集する機能をサポートしています。 Sdk は、プロセッサ CPU や使用可能なメモリなどの基本的なパフォーマンスカウンターを収集するだけでなく、windows マシンからの <a href="https://blogs.msdn.com/b/visualstudioalm/archive/2015/04/01/application-insights-choose-your-own-performance-counters.aspx">カスタムパフォーマンスカウンター</a> の収集をサポートしています。 パフォーマンスカウンターを収集すると、アプリケーションホスト環境がアプリケーションに与える影響を監視および診断するための十分な洞察を得ることができます。

  <h3>トレーステレメトリ</h3>

  Application Insights sdk を使用すると、<a href="https://go.microsoft.com/fwlink/?LinkID=616916">トレース (またはログ) テレメトリ</a>を収集できます。 Log4Net、NLog、Log4J、LogBack、など、使用する可能性のある既存の一般的なトレースログフレームワークの多くからテレメトリを自動的にキャプチャするように Sdk を構成することができます。 自動収集に加えて、常に SDK API を使用してトレーステレメトリを直接ログ記録することができます。

  <h3>カスタムテレメトリ</h3>

  SDK には、シンプルで強力な API が用意されています。 この API を使用すると、カスタムテレメトリデータをログに記録できます。 すべての自動テレメトリは、API を使用して制御、補強、または置換できます。 また、2つの専用のカスタムテレメトリの種類、イベント、メトリックも公開しています。 カスタムイベントとメトリックは、テレメトリデータを収集するための強力なツールです。 カスタムイベントは、アプリケーション内の追跡されたアクションの1つの独立したインスタンスを表します。 カスタムメトリックは、時系列ベースのデータのログ記録をサポートしています。データ値の単純なログ記録により、時間の経過と共に平均と合計のメトリックを抽出できます。 さらに、すべてのテレメトリカスタムテレメトリと同様に、プロパティを使用して、後から多次元分析を行うことができます。

  <h2>開始するには?</h2>

  Application Insights の価値と、sdk によって提供される機能を理解する最善の方法は、既存のアプリケーションに Application Insights を追加するか、新しいプロトタイプアプリケーションで試してみることです。 <a href="https://azure.microsoft.com/documentation/articles/app-insights-platforms/">作業の開始</a>プロセスは、5分以内に実行する必要があります。 また、新しいアプリケーションは<a href="https://azure.microsoft.com/pricing/details/application-insights/">free レベル</a>の一部として作成されるので、Application Insights のリスクをすばやく評価することができます。


  既存の Application Insights お客様の<a href="https://go.microsoft.com/fwlink/?LinkID=616915">アップグレード</a>は簡単です。 NuGet パッケージマネージャーを使用して、参照を最新の安定したバージョンにアップグレードします。
