### YamlMime:Yaml
ms.openlocfilehash: ba6bf2e01308b5b37304fd4e86363ddb540df5b3
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139896297"
Slug: annotations-detail-blade-now-available-in-application-insights
Title: '[注釈の詳細] ブレードが [アプリケーション] ページで使用インサイト'
Summary: Application インサイト の注釈機能の詳細ブレードが利用可能です。
Content: >-
  <p>リリース注釈<a href="https://azure.microsoft.com/en-us/blog/application-insights-announces-availability-of-release-annotations/" target="_blank" title="に関するブログ投稿">の</a>最後のブログ記事では、Application インサイト という名前の新しい機能の提供を<em>発表しました。</em> また、この機能の詳細ブレードは、次の 2 つのスプリントで使用できる予定になることも説明しました。 皆さん、良いニュースです。今&rsquo;すぐ利用 <em>できます</em>。</p>


  <p>機能は可能な限&rsquo;りシンプルです。詳細を表示する [注釈] をクリックすると、新しいブレードが右側に開きます。 このブレードには、リリース ID、要求元、ソース管理ブランチ、リリース定義、環境など、リリースに関するさまざまな情報が表示されます。 動作&rsquo;の簡単な方法を次に示します。</p>


  <p><img alt="image" border="0" height="368" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fc9e824e-85eb-4fe9-a920-4ab56d4fd8c0.png" style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-image: none" title="image" width="610"></p>


  <p>この機能を追加すると、リリース注釈に大きな価値が生まれると思います。 Application&rsquo; インサイト でリリースをテレメトリに関連付けようとするときに、より多くの識別情報を迅速に取得インサイト。</p>


  <p>App インサイト ALM チームは、この追加により、Web アプリとサービスの毎日の監視と分析に注釈が役立つ可能性を期待しています。 詳細ブレードに&rsquo;&rsquo;表示されない追加のリリース データがある場合は、お知らせください。データの可用性を調査します。</p>


  <p>もうすぐお知らせします。新しいお知らせについては、Azure ブログの投稿をご覧ください。</p>


  <p>いつものように、[Application インサイト User Voice] ページで新機能や改善された機能に関するアイデアを共有してください。質問がある場合は、<a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights"><u>Application インサイト フォーラムを参照してください</u></a>。</p>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-68318793-1', 'auto');ga('send', 'pageview');

  </script>
