### YamlMime:Yaml
ms.openlocfilehash: 136445667dc10c85b679a1271159b0fda6657f7e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910163"
Slug: announcing-application-consistent-backup-for-linux-vms-using-azure-backup
Title: 仮想マシンを使用した Linux VM のアプリケーション整合性バックアップのAzure Backup
Summary: Azure Backupは、オンプレミスとクラウドの両方でエンタープライズ データを保護するクラウドファーストのバックアップ ソリューションです。 Azure で実行されているLinux Virtual Machinesのバックアップが既に提供されています。.
Content: >-
  <p>Azure Backupは、Azure で実行されているファイル システムの <a href="https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-first-look-arm">一貫性Linux Virtual Machinesバックアップを提供します</a>。 現在、これを拡張して、一般的な <b> </b>Linux ディストリビューション (Ubuntu、Red Hat Enterprise Linux など) で実行されている MySQL、InterSystems Cach&eacute;、SAP HANA などのエンタープライズ クリティカルなアプリケーションのアプリケーション整合性バックアップを作成します。 このフレームワークを使用すると、VM バックアップ プロセスの一環として、カスタムの事前スクリプトと事後スクリプトを柔軟に実行できます。 これらのスクリプトを使用すると、アプリケーションの整合性を保証するバックアップを作成しながら、アプリケーションの IOs を一時保存できます。</p>


  <h2>価値提案</h2>


  <ul>
   <li><b>バックアップ ワークフローのカスタマイズ: </b>これで、VM スナップショットの作成中にカスタム スクリプトを実行することで、バックアップ中にアプリケーションと実稼働環境を柔軟に制御できます。 フレームワークを利用する方法の例を次に示します。

   <ul>
    <li>事前スクリプトを使用して、アプリケーションネイティブ API を使用してアプリケーション IOs を一時静止またはリダイレクトし、VM スナップショットを作成する前にメモリ コンテンツをディスクにフラッシュすることができます。 その後、事後スクリプトを使用して、スナップショットの完了後に IOs を解凍し、通常のアプリケーション操作を再開できます。 これにより、実行中のすべてのアプリケーションのアプリケーション整合性 VM バックアップが保証されます。 一部のアプリケーションでは、静止ロジックに干渉しないように fsfreeze を無効にする必要があります。そのため、Azure Backup を使用して Linux VM のバックアップを実行する間に既定で実行される Linux <em>fsfreeze</em> を無効にする機能も用意されています。</li>
    <li>ネイティブ アプリケーション API を呼び出して、アプリケーションのバックアップとデータベース ログのバックアップを取得することもできます。VM バックアップの一環として、データは Recovery Services コンテナーに移動され、VM の侵害シナリオ (VM の削除や破損など) に対して保護されます。</li>
   </ul>
   </li>
  </ul>


  <blockquote>

  <ul>

  </ul>

  </blockquote>


  <ul>
   <li><b>アプリケーションとディストリビューションに依存しない: </b>このフレームワークは Linux ディストリビューションとバージョンに依存し、ゲスト アプリケーションにアプリケーションの IOs を一時停止および再開する API がある限り、サポートされている <a href="https://docs.microsoft.com/en-us/azure/backup/backup-azure-backup-faq#what-can-i-back-up">Linux</a> ディストリビューションすべてでシームレスに動作します。</li>
   <li><b>github のサンプル スクリプト: </b>パートナーや ISV と協力して、一般的な Linux アプリケーション用のオープン ソース スクリプトを <a href="https://github.com/MicrosoftAzureBackup">GitHub</a> で提供しています。 このリリースの時点で、これらは MySQL、Cach&eacute; 用に配置され、アプリケーションと密接にSAP HANA。<strong>&nbsp;</strong></li>
  </ul>


  <h2>しくみ</h2>


  <p>Azure Backup、次の図で説明するように、高速で効率的な Azure Linux VM バックアップを実行するための一連の手順を完了します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f2dca00d-728c-4ce9-ad56-e6fd06bf993a.png"><img alt="workflow" border="0" height="595" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b64fe2c1-6168-4ea8-b54a-9dd15748affe.png" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; float: none; margin-left: auto; display: block; border-top-width: 0px; margin-right: auto" title="ワークフロー" width="418"></a></p>


  <h2>作業の開始</h2>


  <p>以下のビデオでは、事前スクリプトと事後スクリプトを実行するためのフレームワークを構成する方法について、さまざまな手順について説明します。 詳細については、アプリケーション整合性 Linux <a href="https://docs.microsoft.com/azure/backup/backup-azure-linux-app-consistent#steps-to-configure-pre-script-and-post-script">VM バックアップを構成する手順を参照してください</a>。</p>


  <p><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Series/Azure-Backup/Application-consistent-backup-for-Linux-VMs-using-Azure-Backup/player" width="960"></iframe></p>


  <h2>MySQL キャッシュのサンプル &amp; スクリプト&eacute;</h2>


  <p>フレームワークをブートストラップするために、クラスター化されたデプロイを含むデモ スクリプトを使用して <a href="https://www.intersystems.com/our-products/cache/cache-overview/">、InterSystems Cach&eacute;</a> DB と <a href="https://www.mysql.com/">MySQL</a> DB の例を使用しました。 これを参照として使用して、独自のスクリプトを作成し、このフレームワークの機能を活用できます。</p>


  <p>Capside による Azure Backup を使用した MySQL アプリケーション整合性バックアップ</p>


  <p><a href="https://community.intersystems.com/post/caché-application-consistent-backups-azure-backup">&eacute; Intersystems による Azure Backupを使用したアプリケーション整合性バックアップのキャッシュ</a></p>


  <h2>オープンソース コミュニティへの貢献を求める</h2>


  <p>開発者、ISV、技術技術者、パートナーに対して、オープンソースの GitHub リポジトリにスクリプトを投稿して<a href="https://github.com/MicrosoftAzureBackup">いっていただけます。</a> スクリプトは、すべてのユーザーが直接使用したり、要件に基づいてカスタマイズしたりするために使用できます。 投稿に関心 <a href="https://azure.microsoft.com/en-us/blog/key-updates-to-azure-backup-for-azure-linux-vms/preview/linuxazurebackupteam@service.microsoft.com">linuxazurebackupteam@service.microsoft.com</a> をお持ちのお客様は、メールをお送りください。GitHub で公開し、使用ガイドラインを説明し、投稿の確認を受け取る必要があります。</p>


  <h2>関連リンクと追加コンテンツ</h2>


  <ul>
   <li>この機能の詳細については、以下をご覧ください。 Azure アプリケーション整合性 <a href="https://docs.microsoft.com/azure/backup/backup-azure-linux-app-consistent">Linux VM のバックアップに関するドキュメントを確認する</a></li>
   <li>ヘルプが必要ですか? サポートについては、Azure Backup <a href="https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=windowsazureonlinebackup">フォーラムに</a> 連絡してください</li>
   <li>新しいアイデアを寄 <a href="https://feedback.azure.com/forums/258995-azure-backup">稿し、既存のアイデアAzure Backup</a> 投票することで、より良いアイデアを得る方法を教えて。</li>
   <li>最新のニュースと更新情報については、Twitter <a href="https://twitter.com/azurebackup">@AzureBackup</a> でフォローしてください</li>
   <li>新しい <a href="https://azure.microsoft.com/en-us/services/backup/">Azure Backup</a>、無料の <a href="https://azure.microsoft.com/en-us/pricing/free-trial/">Azure 試用版サブスクリプションにサインアップしてください</a></li>
  </ul>
