### YamlMime:Yaml
ms.openlocfilehash: 203a1361da98f0750cc6ab690ab6f85d19326852
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904327"
Slug: application-insight-analytics-schema-updates
Title: 'Application Insight Analytics: スキーマの更新'
Summary: 'Application インサイト の強力なクエリ言語である Analytics のスキーマVisual Studio強化インサイト。 メトリックを performanceCounters と customMetrics に分け、クライアント側からページ読み込みデータを表示する browserTimings を導入しました。 '
Content: >-
  <p>Application Visual Studio <a href="https://azure.microsoft.com/documentation/articles/app-insights-analytics-tour/">の</a>強力なクエリ言語である <a href="https://azure.microsoft.com/documentation/articles/app-insights-overview/">Analytics のスキーマインサイト</a>。 メトリック&rsquo;を <b>performanceCounters</b> と <b>customMetrics</b> に分離し、クライアント側からページ読み込みデータを表示する <b>browserTimings</b>&rsquo; を導入しました。 これらの変更により、データの検出可能性が向上し、クエリが簡素化され、テレメトリの新しいメトリックとディメンションが公開されます。</p>


  <p><img alt="image" border="0" height="480" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/94e5487d-c409-4c85-bd11-63acb3bfa41b.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="192"></p>


  <h2>performanceCounters スキーマ</h2>


  <p>このスキーマは、アプリケーションから報告されたパフォーマンス カウンターを探す必要がある単一の場所です。 パフォーマンス カウンターが Application インサイト SDK によって自動的に収集される場合でも、他のパフォーマンス カウンター<a href="https://azure.microsoft.com/documentation/articles/app-insights-web-monitor-performance/#system-performance-counters"></a>を送信するようにアプリケーションを構成した場合でも、データはこのスキーマで確認できます。</p>


  <p>たとえば、報告されているパフォーマンス カウンターを確認するには、</p>


  <p><img alt="image" border="0" height="320" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a76e6c63-0bbb-4905-b919-0f0fd6a75dd7.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="360"></p>


  <p>最近の利用可能なメモリのグラフを取得するには、次のようにします。</p>


  <p><img alt="image" border="0" height="275" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9aa9080c-f301-45d5-8b4f-427dabb0166b.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="480"></p>


  <p>performanceCounters スキーマは、各パフォーマンス カウンター <b>の</b>カテゴリ、 <b>カウンター</b> 名、 <b>インスタンス</b> 名を公開します。 カウンター インスタンス名は一部のパフォーマンス カウンターにのみ適用され、通常はカウントが関連付けられているプロセス名を示します。 各アプリケーションのテレメトリには、そのアプリケーション&rsquo;のカウンターだけが表示されます。 サンプル&rsquo; テレメトリで使用できるカウンターを確認します。</p>


  <p><img alt="image" border="0" height="211" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bd54ec75-5cac-404c-b81f-d5667178f552.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="480"></p>


  <p>他のテレメトリと同様に、<b>performanceCounters</b> にも、<b></b>アプリcloud_RoleInstanceホスト コンピューターの ID を示す列が表示されます。 たとえば、異なるコンピューター上でのアプリのパフォーマンスを比較するには、次のようにします。</p>


  <p><img alt="image" border="0" height="292" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6992ca4c-f7dd-4ad7-828a-48899b9ac8d8.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="480"></p>


  <h2>customMetrics スキーマ</h2>


  <p><a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/#track-metric">TrackMetric() を使用して</a>独自のテレメトリを送信&rsquo;している場合は、<b>customMetrics スキーマで確認</b>できます。 次に例を示します。</p>


  <p><img alt="image" border="0" height="324" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a18850d9-61b8-4052-9563-44b1efe7a916.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="480"></p>


  <h2>browserTimings スキーマ</h2>


  <p>最後に、クライアント側のメトリックを公開します。 多くのお客様がこれを求め、お客様の要求をサポートいたします。</p>


  <p>これらのメトリックを表示するには、<a href="https://azure.microsoft.com/documentation/articles/app-insights-javascript/">クライアント側テレメトリのためにアプリをセットアップ</a>します。</p>


  <p>新しいスキーマには、<b>networkDuration</b>、<b>sendDuration</b>、<b>receiveDuration、processingDuration</b>、<b>totalDuration</b> のメトリック<b>が</b>含まれています。 これらのメトリックは、ページ読み込み <a href="https://azure.microsoft.com/documentation/articles/app-insights-javascript/#page-load-performance">プロセスの異なるステージの長さを示します</a>。 (ユーザーが&rsquo;ページを読み取る時間の長さは示されます)。</p>


  <p><b>name</b> は、ページ名でフィルター処理するために使用できます。また、ページ名やページ名<b>client_OSプロパティ</b><b>client_Browser</b>。 また、クライアント側のメトリックをすばやく分析してバケット別にグループ化する <b>performanceBucket</b> プロパティも提供します。</p>


  <p>たとえば、サイト上で最も人気のあるページと読み込み時間を確認するには、</p>


  <p><img alt="image" border="0" height="265" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f43a6aed-592f-4a45-9769-5989938e71ee.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="480"></p>


  <h2>ご意見をお寄せください</h2>


  <p>これらの変更が、アプリケーションの使用状況とパフォーマンスをよりよく&rsquo;理解するのに役立ちます。 データはそこにあるので、クエリを実行する必要があります。</p>


  <p>いつものように、次のいずれかのチャネルを使用して、ご質問やフィードバックをお寄せください。</p>


  <ul>
   <li><a href="https://visualstudio.uservoice.com/forums/357324-application-insights/category/161991-analytics">Application インサイト Ideas でアイデアを提案して投票する</a></li>
   <li><a href="https://social.msdn.microsoft.com/Forums/vstudio/home?forum=ApplicationInsights">Application インサイト Community で会話に参加する</a></li>
   <li><a href="https://analytics.applicationinsights.io/demo">Application Analytics を試す</a></li>
  </ul>
