### YamlMime:Yaml
ms.openlocfilehash: 0eeaae618ec9bba216e80bdc11b1fab59879a630
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891851"
Slug: application-packages-and-task-dependencies-now-available-on-azure-batch
Title: アプリケーション パッケージとタスクの依存関係が、Azure Batch
Summary: 'お約束のように、プレビュー機能を一般提供の実稼働可能な Batch サービスに移植する作業に苦労しています。 最も一般的な機能の 2 つ、アプリケーション パッケージとタスクの依存関係が利用可能になりました。 '
Content: >-
  <p>昨年、クラウド ベースのジョブ スケジューリング サービスをリリースしました。このサービスは、<a href="https://azure.microsoft.com/en-us/services/batch/">Azure Batch。</a> この高度にスケーラブルなサービスと共に、いくつかの高度な機能を含む Batch Apps もプレビューしました。 お約束のように、これらの&rsquo;プレビュー機能を一般提供の実稼働可能な Batch サービスに移植する作業に苦労しました。 本日、&rsquo;最も一般的な機能であるアプリケーション パッケージとタスクの依存関係の <i>2</i> <i>つを発表しました</i>。</p>


  <h2>アプリケーション パッケージ</h2>


  <p>各ワークロードには、実行可能ファイル、ライブラリ、追加のメタデータなど、共通のファイル セットが必要です。 この一連のファイルはワークロード固有であり、ジョブまたはタスクを実行する前に VM にダウンロードする必要があります。 アプリケーション パッケージ機能を使用すると、これらのファイル パッケージをプール内のコンピューティング ノードに簡単に管理してデプロイできます。 複数のバージョンを&rsquo;アップロードして管理し、プール内のノードにこれらのアプリケーション パッケージの 1 つ以上を自動的にデプロイできるので、アプリケーションを構成する多様なファイルを管理する複雑さを大幅に減らします。 さらに、&rsquo;これらのファイルを移動するために Azure Storage を管理する必要はもう一度必要とされません。Batch では、ストレージ アカウントを使用してこれらのパッケージを安全に格納してデプロイすることで、バックグラウンドですべての詳細が処理されます。</p>


  <p>アプリケーション パッケージは単なる ZIP ファイルであり、コンピューティング ノードで必要な任意の数のファイルを含めることもできます。 ストレージ&rsquo; アカウントのリンク、複数のバージョンのアップロード、既存のアプリケーションの削除、各アプリケーションの既定のバージョンの構成など、これらのアプリケーションを管理できます。 これらのアクションは、Batch アカウントに移動 <a href="https://portal.azure.com">Azure portal</a> を使用して簡単に実行できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/31752532-5f92-48f0-9b78-44db9a89bd25.png"><img alt="clip_image002" border="0" height="173" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f1fa73d9-9b48-41d1-9d70-2c5984024b9f.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="clip_image002" width="360"></a></p>


  <p>コンピューティング&rsquo; ノードにアプリケーション パッケージをインストールする方法は非常に簡単でした。これは、プールに対して 1 つ以上のアプリケーション パッケージ参照を指定することで行われます。 これは、プールの作成時に行います。</p>


  <pre class="prettyprint">

  // Create the unbound CloudPool

  CloudPool myCloudPool =
      batchClient.PoolOperations.CreatePool(poolId: &quot;myPool&quot;,
                                            osFamily: &quot;4&quot;,
                                            virtualMachineSize: &quot;small&quot;,
                                            targetDedicated: &quot;1&quot;);

  // Specify the application and version to install on the compute nodes

  myCloudPool.ApplicationPackageReferences = new List&lt;ApplicationPackageReference&gt;

  {
      new ApplicationPackageReference {
          ApplicationId = &quot;litware&quot;,
          Version = &quot;1.1001.2b&quot; }
  };


  // Commit the pool so that it&#39;s created in the Batch service. As the nodes join

  // the pool, the specified application package will be installed on each.

  await myCloudPool.CommitAsync();</pre>


  <p>アプリケーション パッケージ&rsquo;がプール内のコンピューティング ノードにインストールされると、タスクのコマンド ラインに代わって作成された環境変数を使用して、パッケージ内のファイルを実行できます。 この変数は名前付けスキームに準拠しています。 <code>AZ_BATCH_APP_PACKAGE_appid#version</code> ここで、appid はアプリケーション名を参照し、バージョンは実行するバージョンを参照します。 Azure Portal で既定のバージョンを選択&rsquo;した場合は、appid を参照することもできます。 <code>AZ_BATCH_APP_PACKAGE_appid.</code></p>


  <h2>タスクの依存関係</h2>


  <p>多くのジョブとワークロードでは、タスク間の依存関係が必要です。Batch Apps はステージを介してこれをサポートしています。 Batch&rsquo; アプリスタイルのステージをレプリケートするために使用される Batch にタスクの依存関係機能を追加しました。一般的には、タスク間の依存関係を表します。 この機能は、アクティビティまたは作業を実行する必要がある順序を決定するタスク間のリレーションシップを構築するのに役立ちます。 タスクには、複数の先行するタスクと、複数の成功するタスクを含めできます。</p>


  <p>この機能には、ポイント クラウドを生成する前処理タスクやレンダリング タスク、事前にレンダリングされたタスクに依存するフレーム タスク、最終的な出力のために個々のフレームまたはタスクがマージ タスクに結合される場所も含まれます。 前処理タスクの ID を使用して、依存関係を呼び出します。</p>


  <pre class="prettyprint">

  frameTask.DependsOn = TaskDependencies.OnId(&quot;prerender&quot;); </pre>


  <p>また、さまざまなタスクに依存するタスクを作成することもできます。 最初に完了する他のすべてのタスクに依存するマージ タスクがある可能性があります。 これは、別のヘルパー メソッド OnIdRange を呼び出 &ldquo;すだけで実現できます&rdquo;。</p>


  <pre class="prettyprint">

  makeMovieTask.DependsOn = TaskDependencies.OnIdRange(startFrame, endFrame); </pre>


  <p>これらの機能は Batch サービスに大きな追加機能であり、開発者が定型コードを残して組み込みによって、より迅速に市場に出し、オーバーヘッドを削減するのに役立ちます。 これらの機能は現在ライブであり、新しい Azure.Batch 3.1 NuGet パッケージで使用できます。対応する機能は、Azure portal で使用できます。 また、ここでサンプル コードをダウンロード <a href="https://github.com/Azure/azure-batch-samples/tree/master/CSharp/ArticleProjects/TaskDependencies">できます</a>。</p>


  <p>アプリケーション パッケージとタスクの <a href="mailto:wabatch@microsoft.com">wabatch@microsoft.com</a> 依存関係の両方を試し、直接、または公式フォーラムに投稿してフィードバックをお送り <a href="https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=azurebatch">ください</a>。</p>


  <p>ご協力に感謝いたします。</p>


  <p>Azure Batch チーム</p>
