### YamlMime:Yaml
ms.openlocfilehash: af0b5fb8909712f2176af6927707c1a8cab1171a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909381"
Slug: application-insights-temporary-limitations-and-performance-improvements-update
Title: Application Insights-一時的な制限とパフォーマンスの向上 (更新)
Summary: 'Application Insights のパフォーマンス、信頼性、および拡張性の向上を続けています。 サンプリングとフィルター処理をサポートする新しいバージョンの Application Insights sdk と、動的サンプリングをサポートするプレビューバージョンが用意されています。 '
Content: >-
  <p><a href="https://azure.microsoft.com/services/application-insights/">Application Insights</a>のパフォーマンス、信頼性、および拡張性の向上を続けています。 &nbsp;<a href="https://azure.microsoft.com/en-us/blog/announcing-azure-portal-general-availability/">Azure portal</a>は最近一般公開され、Azure の既定のポータルエクスペリエンスです。 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-filtering-sampling/">サンプリングとフィルター処理</a>をサポートする新しいバージョンの Application Insights sdk と、<a href="https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/2.0.0-beta3">動的サンプリング</a>をサポートするプレビューバージョンが用意されています。&nbsp;</p>


  <p>10月以降、クエリのパフォーマンスとシステム全体の信頼性を向上させるために、サービスでのデータの管理方法に変更を加えました。 &nbsp;この変更を有効にするために、<a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/">検索クエリ</a>を実行できる<a href="https://azure.microsoft.com/en-us/blog/application-insights-temporary-limitations-and-performance-improvements/">期間が短縮</a>されました。 Standard またはプレミアム価格プランを使用している場合 &rsquo; でも、 &rsquo; 7 日を超えて戻る検索クエリを実行することはできません。 &nbsp;データリファクタリングは完了しましたが、残念ながらこの変更のロールアウトは予想より長くかかっています。 1月に、7日間を超えて検索クエリを復元するために必要な最終的な変更のロールアウトを開始します。 2月中旬までは、価格プランによって提供された生データ保有期間の上限まで、7日を超えてもう一度検索できるようになります。 暫定的には、Standard とプレミアムのお客様は引き続き<a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-export-telemetry/">連続エクスポート</a>を使用して7日を経過したデータにアクセスできます。&nbsp;</p>


  <p><a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/">メトリックスエクスプローラー</a> は、7日を超えて標準およびカスタムプロパティでフィルター処理およびグループ化する機能など、詳細なメトリックデータを引き続き提供します。</p>


  <p>適切なタイミングで適切な情報にアクセスすることは、アプリケーションに関する問題の監視、診断、トラブルシューティングにおいて非常に重要であることを理解しています。 そのため、エクスペリエンスとサポートインフラストラクチャを継続的に変更および改善し、Application Insights より有益で有益なエクスペリエンスを実現しています。</p>


  <p>お客様のご意見をお待ちしております。そのため、ユーザーの声と <a href="https://social.msdn.microsoft.com/Forums/en-US/home?forum=ApplicationInsights">MSDN フォーラム</a>にフィードバック、ご提案、ご質問をお寄せください。</p>
