### YamlMime:Yaml
ms.openlocfilehash: e7f783ab848c0be9be89ba30c4acade8d06a42f9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895150"
Slug: applicationsecuritygroups
Title: すべての Azure リージョンでアプリケーションセキュリティグループが一般公開されるようになりました
Summary: >+
  すべての Azure リージョンで、アプリケーションセキュリティグループ (ASG) の一般提供が発表されます。 この機能により、Azure の仮想ネットワークのセキュリティマイクロセグメンテーションが提供されます。

Content: >-
  <p>すべての Azure リージョンで、アプリケーションセキュリティグループ (ASG) の一般提供が発表されます。 この機能により、Azure の仮想ネットワークのセキュリティマイクロセグメンテーションが提供されます。</p>


  <p><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Intro.PNG" style="width: 800px; height: 412px; margin-right: auto; margin-left: auto; float: none; display: block;"></p>


  <h2>ネットワークセキュリティマイクロセグメンテーション</h2>


  <p>ASGs を使用すると、明示的な IP アドレスではなく、ワークロードに基づいてきめ細かなネットワークセキュリティポリシーを定義し、アプリケーションで集中管理することができます。 ネットワークの信頼されたセグメントからのトラフィックをフィルター処理することによって、モニカーとセキュリティで保護されたアプリケーションの Vm をグループ化する機能を提供します。</p>


  <p>きめ細かなセキュリティトラフィック制御を実装すると、ワークロードの分離が向上し、個別に保護されます。 侵害が発生した場合、この手法により、ネットワークをハッカーから横方向に探索することによる潜在的な影響が制限されます。</p>


  <h2>セキュリティ定義の簡略化</h2>


  <p>ASGs では、次の手順を使用して、アプリケーションパターンに基づくトラフィックのフィルター処理を簡略化できます。</p>


  <ul>
   <li>アプリケーショングループを定義し、アーキテクチャに適したモニカーのわかりやすい名前を指定します。 これは、アプリケーション、ワークロードの種類、システム、層、環境、または任意のロールに使用できます。</li>
   <li>ASGs とネットワークセキュリティグループ (NSG) を使用してルールのコレクションを1つ定義します。すべてのサブネット上の仮想ネットワーク全体に1つの NSG を適用できます。 1つの NSG を使用すると、トラフィックポリシーと管理のための1つの場所を完全に把握できます。</li>
   <li>独自のペースでスケールします。 Vm をデプロイするときに、適切な ASGs のメンバーにします。 VM で複数のワークロードが実行されている場合は、複数の ASGs を割り当てるだけです。 アクセスは、ワークロードに基づいて付与されます。 セキュリティの定義について心配する必要はありません。 さらに重要なのは、ゼロ信頼モデルを実装して、明示的に許可されているアプリケーションフローへのアクセスを制限することです。</li>
  </ul>


  <h2>単一のネットワークセキュリティポリシー</h2>


  <p>ASGs では、同じサブネット内に複数のアプリケーションをデプロイし、ASGs に基づいてトラフィックを分離する機能が導入されています。 ASGs を使用すると、サブスクリプションの NSGs の数を減らすことができます。 場合によっては、仮想ネットワークの複数のサブネットに単一の NSG を使用できます。 ASGs を使用すると、構成を一元化することができ、動的な環境では次の利点が得られます。</p>


  <ul>
   <li>一元化された<strong>NSG ビュー</strong>: すべてのトラフィックポリシーを単一の場所に配置します。 これ &rsquo; により、変更の操作と管理が簡単になります。 Vm のグループとの間で新しいポートを許可する必要がある場合は、1つの規則に変更を加えることができます。</li>
   <li><strong>集中ログ</strong>: <a href="https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-overview" target="_blank">nsg フローログ</a>との組み合わせでは、ログの1つの構成にトラフィック分析の利点が複数あります。</li>
   <li><strong>ポリシーの適用</strong>: 特定のトラフィックを拒否する必要がある場合は、優先順位の高いセキュリティ規則を追加し、管理規則を適用できます。</li>
  </ul>


  <h2>東西部トラフィックのフィルター処理</h2>


  <p>ASGs を使用すると、複数のワークロードを分離し、仮想ネットワークに対して追加の保護レベルを提供できます。</p>


  <p>次の図では、複数のアプリケーションが同じ仮想ネットワークにデプロイされています。 説明されているセキュリティ規則に基づき、ワークロードは互いに分離されます。 いずれかのアプリケーションからの VM が侵害された場合、水平探索が制限されるため、攻撃者の潜在的な影響を最小限に抑えることができます。</p>


  <p>この例では、 &rsquo; アプリケーション1からの web サーバー vm の1つが侵害されたと仮定して、アプリケーションの残りの部分は引き続き保護されます。データベースサーバーなどの重要なワークロードへのアクセスでも、引き続きアクセスできません。 この実装により、ネットワークに複数の追加のセキュリティ層が提供されるため、このような侵入に悪影響を及ぼすことなく、このようなイベントに簡単に対応できるようになります。</p>


  <p><img alt="" height="346" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/EastWest.PNG" style="width: 1000px; height: 432px; margin-right: auto; margin-left: auto; float: none; display: block;" width="800"></p>


  <h2>北南部トラフィックのフィルター処理</h2>


  <p>NSG の追加機能と組み合わせることで、オンプレミスと azure サービスからワークロードを分離することもできます。</p>


  <p>次の図では、仮想ネットワーク内の複数のワークロードの種類に対して比較的複雑な環境が構成されています。 アプリケーションでは、セキュリティ規則を記述することによって、各 VM に適切なポリシーセットが適用されます。 前の例と同様に、ブランチの1つが侵害された場合、仮想ネットワーク内の探索は制限されるため、侵入による影響を最小限に抑えることができます。</p>


  <p>この例では、 &rsquo; VPN を使用して接続されているいずれかのブランチ上のユーザーを想定して、ワークステーションを侵害し、ネットワークにアクセスできるようにします。 通常、ネットワークの他の部分を分離することによって、このブランチにはネットワークのサブセットのみが必要です。その他すべてのアプリケーションは引き続き保護され、アクセスできなくなります。 ネットワーク全体に対して、別のセキュリティ層を使用します。</p>


  <p>もう1つの興味深いシナリオとして、いずれかの web サーバーで侵害が検出された場合は、調査用に VM を分離することをお勧めします。 ASGs では、最初のセキュリティポリシーで、検疫 Vm 用に事前に定義された特別なグループを簡単に割り当てることができます。 これらの Vm は、この処理の反応と軽減に役立つ追加の特典を提供するアクセスを失います。</p>


  <p><img alt="" height="442" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/NorthSouth.PNG" style="width: 1000px; height: 552px; margin-right: auto; margin-left: auto; float: none; display: block;" width="800"></p>


  <h2>まとめ</h2>


  <p>アプリケーションセキュリティグループは、NSGs の最新の機能強化と共に、1つの管理エクスペリエンス、複数のディメンションの制限の向上、高度な単純化、アーキテクチャとの自然な統合など、ネットワークセキュリティ領域に関して複数の利点をもたらしました。今日では、仮想ネットワーク上でこれらの機能を体験してください。</p>


  <p>詳細については、「 <a href="https://docs.microsoft.com/en-us/azure/virtual-network/security-overview#application-security-groupshttps://docs.microsoft.com/azure/virtual-network/security-overview" target="_blank">Nsg の概要</a>」の記事を参照してください。 NSGs と ASGs を実装する方法については、次の <a href="https://docs.microsoft.com/en-us/azure/virtual-network/create-network-security-group-preview" target="_blank">チュートリアル</a>を参照してください。</p>


  <p>常に、お客様のご意見をお寄せください。 お客様の ASGs のご提案やご意見をお待ちしております。また、 <a href="https://feedback.azure.com/forums/217313-networking?category_id=77468https://feedback.azure.com/forums/217313-networking?category_id=77466" target="_blank">ユーザーの声チャネル</a>を通じて今後のシナリオもご利用いただけます。 Azure のネットワークセキュリティ領域で、さらに興味深い更新プログラムをご期待ください。</p>
