### YamlMime:Yaml
ms.openlocfilehash: 58d7dba1fa5d886ddb75d4cc641c189753b2e140
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895156"
Slug: application-insights-tools-in-visual-studio-2015-rtm-2
Title: Visual Studio 2015 RTM の Application インサイト Tools
Summary: 2015 Visual Studio今朝、開発サイクルのすべてのフェーズをサポートする多くの機能がリリースされました。
Content: >-
  2015 Visual Studio今朝、開発サイクルのすべてのフェーズをサポートする多くの機能がリリースされました。 まだ行っていない場合は、<a href="https://blogs.msdn.com/b/visualstudio/archive/2015/07/20/visual-studio-2015-and-visual-studio-2013-update-5-released.aspx">2015 Visual Studioページを</a>確認してください。これらの機能の中には、Visual Studioアプリケーションインサイトツールが含Visual Studio。

  <h2>Application Insights とは何か?</h2>

  <a href="https://www.visualstudio.com/products/application-insights-vs.aspx">Application インサイト</a>は、ライブ アプリケーションのパフォーマンスと使用状況を監視する拡張可能な分析ソリューションです。 Windows デバイスと ASP.NET Web アプリだけでなく、iOS、Android、J2EE など、さまざまなプラットフォーム上の Web アプリケーションとスタンドアロン アプリケーションの両方で動作します。 (ここでは、Visual Studio dev として使用する方法に焦点を当てながら説明しますが、ボード全体で一様に動作する方法を説明する価値があります)。


  アプリケーションインサイト開発チームを対象とします。 パフォーマンスと可用性 <a href="https://azure.microsoft.com/documentation/articles/app-insights-detect-triage-diagnose/">の問題とクラッシュ</a> を検出して診断するために使用します。  <a href="https://azure.microsoft.com/documentation/articles/app-insights-overview-usage/">使用パターンを分析し</a> 、各新機能の成功を測定します。 DevOps サイクルに組み込み、次のリリースを計画できるよう、各新しいリリースに関するデータを収集するように設計されています。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/19/AI.png"><img class="alignnone size-medium wp-image-320561" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AI-636x300.png" alt="Application Insights" width="636" height="300" /></a>

  <h2>アプリケーションを使用したアプリケーション インサイトのVisual Studio</h2>

  アプリケーションアプリケーションの使用を開始インサイトはVisual Studio非常に簡単です。


  書き込みアクセス<a href="https://azure.com/">権Microsoft Azure</a>サブスクリプションが必要です。サインアップは無料で、Application インサイト の  <a href="https://azure.microsoft.com/pricing/details/application-insights/">freepricing </a> レベルを選択できます。


  新しいプロジェクトを作成する場合は、[アプリケーションの構成] チェック ボックスがインサイト確認してください。


  <img class="alignnone size-medium wp-image-320641" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AIVS-636x319.jpg" alt="Application Insights checkbox in File New Dialog" width="636" height="319" />


  または、既存のプロジェクトがある場合は、プロジェクトコンテキスト メニューの [アプリケーションの追加] インサイト、または [アプリケーションの追加] ダイアログ接続済みサービスします。


  これらのコマンドを実行すると、SDK がプロジェクトに追加され、Application インサイト でデータが格納、分析、表示されるリソースが作成されます。


  Application インサイトをデバッグ、テスト、および実稼働で使用できます。

  <h2>Visual Studio 2015 の Application インサイト Tools の新機能</h2>

  <h3>新しいプロジェクトの種類のサポート:</h3>

  <ul>
   <li><a href="https://azure.microsoft.com/documentation/articles/app-insights-asp-net-five/">ASP.NET 5</a></li>
   <li>Windows アプリ (近日公開予定)</li>
   <li>Windows 8.1 ユニバーサル</li>
  </ul>

  <h3>アプリケーション インサイトのVisual Studio 接続済みサービス</h3>

  [アプリケーション] ダイアログインサイト 接続済みサービス (Visual Studio-Add-Project)&gt; で&gt;見接続済みサービス。

  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/19/Connected.png"><img class="alignnone size-medium wp-image-320581" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Connected-539x369.png" alt="Connected" width="539" height="369" /></a>

  <h3>プロジェクトへの AI の追加が完了しました。次は何ですか?</h3>

  Application インサイトを新規または既存のプロジェクトに追加すると、Project の [サービス参照] フォルダーの下に[開始] ヘルプへのリンクが表示されます。


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/link.png"><img class="alignnone size-full wp-image-320582" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/link.png" alt="link" width="345" height="130" /></a>

  <h2>プロジェクトに [アプリケーション] インサイト表示しない</h2>

  一部の種類のプロジェクトでは、Application インサイト構成は完全に自動化されません。 ただし、引き続き手動でアプリケーション インサイト追加できます。 サポートされている <a href="https://azure.microsoft.com/documentation/articles/app-insights-platforms/">プラットフォームの全範囲を参照してください</a>。

  <h2>Application インサイト サービスの更新プログラム</h2>

  [<a href="https://azure.microsoft.com/updates/?service=application-insights">サービスの更新</a>プログラム] ページでは、Application インサイト に対して、新機能と機能強化が継続的に行インサイト。

  <h2>コメント/フィードバック</h2>

  現在の取り組みについて非常に関心を持っています。そのため、質問や問題を <a href="https://social.msdn.microsoft.com/Forums/vstudio/home?forum=ApplicationInsights">Forums</a> に送信し、バグを報告してください <a href="https://connect.microsoft.com/VisualStudio">Connect</a>  (アプリケーション インサイト を選択)、User Voice に提案してください。
