### YamlMime:Yaml
ms.openlocfilehash: 98f2e881340ab225c96d25617cbb723fd343bcf0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904306"
Slug: application-insights-powershell-script-available-for-creating-release-annotations
Title: 'Application Insights: リリース注釈の作成に使用できる Powershell スクリプト'
Summary: 現在 VSTS を使用していないユーザーベースをサポートするために、どこからでもリリース注釈を作成するために使用できる Powershell スクリプトを用意したいと考えています。
Content: >-
  <h2>どこからでも注釈をリリース</h2>


  <p>多くのユーザーが<a href="https://azure.microsoft.com/en-us/blog/application-insights-announces-availability-of-release-annotations/" target="_blank">リリースの注釈</a>について理解し、Application Insights リソースへの追加を開始しました。 この時点までは、これらのリリース注釈を確認する唯一の方法は、Visual Studio Team Services リリースに追加することです。 この統合は VSTS ユーザーにとってすばらしいことです。</p>


  <p>この機能が発表された後、多くのユーザーからのフィードバックをすぐに受け取りました。これらの注釈は非常に優れており、それらを使用すること &ldquo; をお勧めし &rsquo; ますが、現時点ではアプリのリリースに対して他のものを使用しています。 &rdquo; ええ、そうですね。 したがって、現在 VSTS を使用していないユーザーベースをサポートするために、どこからで &rsquo; もリリース注釈を作成するために使用できる Powershell スクリプトを用意しておきます。</p>


  <p>Powershell スクリプトは<a href="https://github.com/Microsoft/ApplicationInsights-Home/blob/master/API/CreateReleaseAnnotation.ps1">GitHub</a>で確認できます。</p>


  <p>一般的な使用法は次のようになります。</p>


  <pre class="prettyprint">

  .\CreateReleaseAnnotation.ps1 -applicationId &quot;&lt;appId&gt;&quot; -apiKey &quot;&lt;apiKey&gt;&quot; -releaseName &quot;&lt;releaseName&gt;&quot; -releaseProperties @{&quot;ReleaseDescription&quot;=&quot;Release with annotation&quot;;&quot;TriggerBy&quot;=&quot;John Doe&quot;}</pre>


  <p>つまり、API キーを生成し、このと appId を Azure portal からコピーするだけで済みます。 これらの準備ができたら、Powershell スクリプトを使用し、必要に応じて属性を入力することができます。</p>


  <p><strong><em>更新</em></strong>: <a href="https://github.com/roryprimrose" target="_blank">rory</a>のおかげで、Octopus Deploy ワークフローで Application Insights リリース注釈を作成できるようになりました。 テンプレートとそのドキュメントについては<a href="https://library.octopusdeploy.com/#!/step-template/actiontemplate-application-insights-annotate-release" target="_blank">、GitHub を参照して</a>ください。</p>


  <h2>今後の予定</h2>


  <p>注釈の機能が拡張され、ユーザーに複数の種類が導入され、カスタム注釈が許可されるようになったため、この Powershell スクリプトを変更して追加のオプションをサポートする予定です。 当然ながら、特定の種類の注釈やカスタムの注釈を使用できるようになったときに、いつでもこのスクリプトをコピーして調整することができます。</p>


  <p>API の成熟度に応じてより多くの直接アクセスを許可することをお勧めします。また、ポータル &rsquo; の UI を使用して注釈を挿入するより簡単な方法も紹介します。 監視を続け、 &rsquo; 進化を続けます。</p>


  <p>常に、Application Insights ユーザーの声のページで新機能や改善された機能についてアイデアを共有し、 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights"><u>Application Insights フォーラム</u></a>で質問することができます。</p>
