### YamlMime:Yaml
ms.openlocfilehash: 9cf442a0ca647e20da0d2515d74219381d3a6ec7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904332"
Slug: application-gateway-analytics-via-goaccess
Title: GoAccess による Application Gateway Analytics
Summary: Azure アプリケーションゲートウェイは、トラフィックパターンや、呼び出し元の IP、要求された URL、リターンコードなどの有用な情報を記録する顧客のアクセスログを提供します。
Content: >-
  <p>Azure アプリケーションゲートウェイは、トラフィックパターンや、呼び出し元 &rsquo; の IP、要求された URL、リターンコードなどの有用な情報を記録する顧客のアクセスログを提供します。 これらのログは Azure Storage にプッシュして、Azure Log Analytics、Excel、Power BI などの分析のためにさまざまなツールで解析できます。 これらのメカニズムを設定して使用する際の難易度は、お客様 &rsquo; の習熟度と基本設定に大きく左右されます。</p>


  <p>お客様は、次のようなさまざまなシナリオで traffic analytics を必要とします。</p>


  <ul>
   <li>販売キャンペーンなど、予想される高トラフィックイベントのライブ監視。</li>
   <li>セキュリティインシデントなど、運用上の問題のデバッグとトラブルシューティングを行います。</li>
   <li>観察されたトラフィック (クライアントの統計情報) に基づいて顧客がだれであるかを把握します。</li>
   <li>アプリケーションのどの部分または Url が要求されているか (上位の要求された Url) を把握します。</li>
   <li>アプリケーションがどのように実行されているかを把握します (障害と待機時間)。</li>
  </ul>


  <p>既存の Application Gateway traffic analytics toolkit に追加して、公開されている<a href="https://aka.ms/appgwgoaccessreadme" target="_blank">Azure クイックスタートテンプレート</a>を使用して、Application Gateway アクセスログと一般的なオープンソースの<a href="https://goaccess.io/" target="_blank">goaccess</a>リアルタイムの log analyzer フレームワークを統合することをお勧めします。 この統合により、お客様は AppGW トラフィックフローに関する洞察を得ることができます。 GoAccess は、ターミナルや HTML などの複数の出力形式に対応した、豊富なダッシュボードにデータを表示します。</p>


  <p>このツールは、次のような、アプリケーションゲートウェイの重要な HTTP トラフィック統計情報を提供します。</p>


  <ul>
   <li>要求の合計、成功した要求、失敗した要求、一意の訪問者数など、全体的なトラフィックの統計。</li>
   <li>1日あたりのユニークな訪問者の数が多い。</li>
   <li>HTTP 状態コードの分布。</li>
   <li>上位の要求されたファイル/Url、404の Url。</li>
   <li>クライアント統計情報: ビジターのホスト名/Ip、クライアントオペレーティングシステム、ブラウザー。</li>
   <li>トラフィックボリュームの時間の分布。</li>
  </ul>


  <p>スクリーンショットには次のものがあります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/97cbafe6-deb5-4e8c-9c76-6a24bcca10af.png"><img alt="goaccessgraphs" border="0" height="854" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7ea7e1a7-3c77-4392-813b-72067056bb69.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="goaccessgraphs ふ" width="2458"></a></p>


  <p>また、実行するために必要なリソースに関して、GoAccess も効率的で軽量です。</p>


  <p>では、バックグラウンドで何が起こるかを見てみましょう &rsquo; 。 GoAccess 統合用の Azure クイックスタートテンプレートは、デプロイ時に次のことを行います。</p>


  <ul>
   <li>サブスクリプションで Linux VM を作成して実行します。</li>
   <li>GoAccess と web サーバーをインストールして実行します。</li>
   <li>構成されたストレージアカウントからのアクセスログを増分方式でフェッチする Azure コネクタをインストールして実行します。</li>
  </ul>


  <p>テンプレートには、デプロイ時に顧客からの入力としていくつかの値が必要です。これらは、テンプレートの Readme ファイルに記載されています。 デプロイが完了したら、お客様は、ブラウザーで https:// &lt; Public-dnsnameofvm &gt; /report.html の URL を指定する必要があります。ここ &lt; で、Public-dnsnameofvm &gt; は、テンプレートによってインストールされる VM の入力の1つとして指定した DNS 名です。</p>


  <p>セットアップを次に示します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7377271d-c6f7-4917-8de1-a3053193c437.png"><img alt="image" border="0" height="302" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8fe33773-e54a-44ec-b464-0a98d722e3da.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="624"></a></p>


  <p>&rsquo;Catch とは あまり重要ではありませんが、注意点がいくつかあります。</p>


  <ul>
   <li>ストレージアカウントへのログストリーミングの通常の待機時間を超えて、表示される統計の更新には最大5分の遅延が発生する場合があります。 ログがストレージアカウントに到達すると、データが更新されるまでに最大5分かかることがあります。</li>
   <li>このソリューションでは、顧客のサブスクリプションの下で VM を実行します。これにより、顧客は、生成される可能性のある VM と帯域幅のコストについて責任を負うことになります。</li>
  </ul>


  <p>お客様が Application Gateway Analytics のこのクイックスタートテンプレートを活用していただけることを願っています。 テンプレートおよびサポートオプションの詳細については、 <a href="https://aka.ms/appgwgoaccessreadme" target="_blank">Readme</a>を参照してください。</p>


  <p><a href="https://feedback.azure.com/forums/217313-networking" target="_blank">Azure フィードバック</a>チャネルを通じてお客様からのフィードバックをお待ちしております。 バックログで優先順位を付けたい機能については、引き続き投票してください。</p>
