### YamlMime:Yaml
ms.openlocfilehash: 66259d56c3c0fa588496d49b59baebb60f3c09f5
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904313"
Slug: application-insights-java-sdk
Title: Java 用 Application インサイト SDK の紹介
Summary: アプリケーション インサイト、JAVA 用の SDK がサポートされます。 詳細については、Application インサイトを使用して、アプリケーションの可用性、パフォーマンス、使用状況の完全なビューを取得する方法を確認してください。
Content: >-
  <span style="font-family: Calibri; font-size: medium;">Java Web アプリケーションを発行する場合は、ユーザーが Java Web アプリケーションで何を行っているのか、その実行方法を明確に確認する必要があります。将来の作業に対する最も効果的な計画は、ユーザーが既に提供した機能 (好きな機能、それに従うパターン、困難と思う機能) を深く理解した上で得られるものになります。また、アプリケーションのパフォーマンスが高い (応答の速さ、負荷の下でのパフォーマンスの変化など) を知りたい場合もあります。パフォーマンスの低下または例外がスローされた場合は、すぐに通知を受け取り、強力なフィルターと検索機能でイベント トレースを調査する必要がある問題を診断します。</span>


  <span style="font-family: Calibri; font-size: medium;"><a href="https://azure.microsoft.com/services/application-insights" target="_blank">Visual Studio Application インサイト</a>は、強力な使用状況分析、パフォーマンス監視、診断分析を備え、このすべての機能を提供するサービスです。それを使用するには、アプリケーションに SDK を追加し、Web ポータルの Application インサイトにテレメトリを送信します。そこで、メトリックとイベントをスライスしてダイスし、必要なアラートを構成します。</span>


  <span style="font-family: Calibri; font-size: medium;">サーバー、Web ページ、および Windows Phone Store Apps や Windows など、いくつかの種類のクライアント アプリケーションからテレメトリを送信できます。API は、さまざまなプラットフォーム間で統一されています。Web テスト サービスもあります。Web テスト サービスでは、Web サイトが一定の間隔で ping を実行して、それが確実にアップし、応答します。</span>


  <span style="font-size: large;"><span style="font-family: Calibri;"><span style="font-size: medium;"><a href="https://www.eclipsecon.org/na2015/" target="_blank">EclipseCon では、この</a>週、Java 用の Application インサイト SDK を紹介します。ここでは、Java Web アプリケーション用に Application インサイトを設定する一般的な計画を示します。次の順序に従う必要は"ない" 点に注意してください。</span> </span></span>

  <table border="1" width="700" cellspacing="0" cellpadding="0">

  <tbody>

  <tr>

  <td valign="top" width="356">

  <p align="left"><span style="font-family: Calibri; font-size: medium;"><strong>追加するインストルメンテーション</strong></span></p>

  </td>

  <td valign="top" width="342"><span style="font-family: Calibri; font-size: medium;"><strong>インサイト受け取った場合</strong></span></td>

  </tr>

  <tr>

  <td valign="top" width="356"><span style="font-family: Calibri; font-size: medium;">サーバーの分析情報: SDK を Java Web アプリケーションに追加する</span></td>

  <td valign="top" width="342"><span style="font-family: Calibri; font-size: medium;">応答時間、要求の量、ユーザー数のサーバー側メトリック。パフォーマンスが低下した場合のアラート。</span></td>

  </tr>

  <tr>

  <td valign="top" width="356"><span style="font-family: Calibri; font-size: medium;">クライアント分析情報: Web ページにアプリケーション インサイト スクリプトを追加する</span></td>

  <td valign="top" width="342"><span style="font-family: Calibri; font-size: medium;">ページ ビュー、ユーザーとセッションの数、戻り率、ブラウザーの種類。</span></td>

  </tr>

  <tr>

  <td valign="top" width="356"><span style="font-family: Calibri; font-size: medium;">可用性 Web テスト</span></td>

  <td valign="top" width="342"><span style="font-family: Calibri; font-size: medium;">応答時間をグラフにし、停止に関するアラートを取得します。</span></td>

  </tr>

  <tr>

  <td valign="top" width="356"><span style="font-family: Calibri; font-size: medium;">カスタム テレメトリの追加 - クライアント側、サーバー側、または両方</span></td>

  <td valign="top" width="342"><span style="font-family: Calibri; font-size: medium;">カスタム イベント、メトリック、および例外を送信して、アプリケーションがどのように使用されているのか追跡します。</span></td>

  </tr>

  <tr>

  <td valign="top" width="356"><span style="font-family: Calibri; font-size: medium;">Application インサイト Logging Appender をログ フレームワークに追加する</span></td>

  <td valign="top" width="342"><span style="font-family: Calibri; font-size: medium;">Application インサイト ポータルで、強力なスライスとダイス機能を使用して、アプリケーション ログを直接探索します。</span></td>

  </tr>

  </tbody>

  </table>

  <h4></h4>

  &nbsp;

  <h2><span style="font-family: Calibri; font-size: large;"><strong>Java アプリケーションに対してどのような分析情報を取得できますか?</strong></span></h2>Java Web アプリに対して得られる一連の分析情報を絶えず拡張し、アプリケーションの可用性、パフォーマンス、使用状況の完全な 360° ビューを取得するのに役立ちます

  <span style="font-family: Calibri; font-size: medium;">。現在利用できる</span>機能は次の場所です。アプリの実行方法を監視する – アプリケーションのパフォーマンスを確認し、障害について迅速に


  <span style="font-size: medium;"><span style="font-family: Calibri;"><b></b>確認します。この情報は、SDK を Web プロジェクトに追加するときに自動的に取得されます。</span></span>


  <img style="float: none; margin-left: auto; margin-right: auto; border-width: 0px;" title="アプリケーションの健全性" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/clip_image001.png" alt="Application health" width="586" height="503" border="0" />


  <span style="font-size: medium;"><span style="font-family: Calibri;"><strong>アプリケーションの使用パターンを分析する </strong>– 導入、対話、エンゲージメントの傾向を理解します。Web ページに JavaScript スニペットを挿入して、最も注目を集めるページ、ユーザーのプロファイル、アプリでほとんどの時間を費やす場所を確認します。 </span></span>


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/03/09/UsageAnalytics.png"><img style="float: none; margin-left: auto; margin-right: auto; border: 0px;" title="Usage Analytics" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/UsageAnalytics_thumb.png" alt="Usage Analytics" width="582" height="702" border="0" /></a>


  <span style="font-size: medium;"><span style="font-family: Calibri;"><b>カスタム イベント、メトリック</b> 、および例外テレメトリを追跡する – テレメトリ API を使用して、アプリケーションに数行のコードを挿入して、ユーザーが何を行っているのかを確認したり、問題の診断に役立ちます。</span></span>


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/03/06/clip_image004.png"><img style="float: none; margin-left: auto; margin-right: auto; border-width: 0px;" title="メトリックス エクスプローラー" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/clip_image004_thumb.png" alt="Metrics Explorer" width="784" height="435" border="0" /></a>


  <span style="font-size: medium;"><span style="font-family: Calibri;"><b>Application インサイト</b> ポータルでトレース ログを探索します。トレース ログは Application インサイト に自動的に送信され、そこで探索して検索できます。ログ 記録フレームワークの構成インサイトアプリケーション の追加機能を追加します (Log4J と Logback でサポートされています)。</span></span>


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/03/06/clip_image005.png"><img style="float: none; margin-left: auto; margin-right: auto; border-width: 0px;" title="診断検索" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/clip_image005_thumb.png" alt="Diagnostic search" width="584" height="689" border="0" /></a>


  <span style="font-size: medium;"><span style="font-family: Calibri;"><b>アプリケーションの正常性を監視する</b> – Web アプリケーションをデプロイした後、Web テストを設定して、その可用性と応答性を監視できます。Application インサイトは、世界中のポイントから定期的に Web 要求を送信し、アプリケーションの応答が遅い場合や応答しない場合にアラートを生成できます。</span></span>


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/03/06/clip_image007.jpg"><img style="float: none; margin-left: auto; margin-right: auto; border-width: 0px;" title="Webtest" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/clip_image007_thumb.jpg" alt="Webtest" width="666" height="308" border="0" /></a>

  <h4></h4>

  <h4></h4>

  <h2><span style="font-family: Calibri; font-size: large;"><strong>Application インサイト SDK for Java をプロジェクトに追加する</strong></span></h2>

  <span style="font-family: Calibri; font-size: medium;">Eclipse を使用してプロジェクトを開発する場合は、Application インサイト SDK for Java を動的 Web プロジェクトに簡単に追加できます。実行</span>する必要があるのは、EclipseCon の週に使用できる最新バージョンの <a href="https://marketplace.eclipse.org/content/azure-toolkit-eclipse"><span style="font-family: Calibri; font-size: medium;">Azure Toolkit for Eclipse</span></a><span style="font-family: Calibri; font-size: medium;"> (By Microsoft Open Technologies) </span> をインストールし、プロジェクトを右クリックし、[アプリケーション インサイト の構成] を選択し、インストルメンテーション キーを指定する必要があります。<a href="https://azure.microsoft.com/documentation/articles/app-insights-java-eclipse/"><span style="font-family: Calibri; font-size: medium;">これを行う方法に関するステップ バイ ステップ ガイド</span></a><span style="font-family: Calibri; font-size: medium;">。</span>


  <img style="float: none; margin-left: auto; margin-right: auto; border-width: 0px;" title="Eclipse plugin" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/clip_image008.png" alt="Eclipse plugin" width="800" height="600" border="0" />


  <span style="font-family: Calibri; font-size: medium;">Java プロジェクトに SDK を追加するには、Maven、Gradle、手動など、さまざまな方法があります。 <a href="https://go.microsoft.com/fwlink/?LinkId=524037" target="_blank">この記事</a></span><span style="font-family: Calibri; font-size: medium;"> では、これらすべてのオプションについて詳しく説明します。 </span>

  <h4></h4>

  <h2><span style="font-family: Calibri; font-size: large;"><strong>Visual Studio Online を使用して、Java アプリケーションを計画、コード化、ビルド、テスト、デプロイできますか?</strong></span></h2>

  <span style="font-family: Calibri; font-size: medium;">Visual Studio </span><a href="https://www.visualstudio.com/features/java-vs"><span style="font-family: Calibri; font-size: medium;">Online</span></a> には、お気に入りの Java ツールと <span style="font-family: Calibri; font-size: medium;"> Eclipse や Jenkins</span> などのサービスを補完する、Java チーム向けクラウドでホストされるツールが用意されています。

  <h4></h4>

  <h2><span style="font-family: Calibri; font-size: large;"><strong>次は何ですか?</strong></span></h2>SDK をプロジェクトに追加したので、さらにインストルメンテーションを追加して、Java アプリケーションに関するさまざまな分析情報

  <span style="font-family: Calibri; font-size: medium;">を取得できます。 </span>


  <span style="font-family: Calibri; font-size: medium;">使用を開始するリンクを次に示します。 </span>

  <ul>
   <li><span style="font-family: Calibri; font-size: medium;"><a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-web-track-usage/" target="_blank">Web アプリケーションの使用状況を追跡する</a></span> – Web ページにスクリプトを追加して、ページ ビュー、<span style="font-family: Calibri; font-size: medium;">ユーザー、セッションを追跡します </span></li>
   <li><span style="font-family: Calibri; font-size: medium;"><a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-java-trace-logs/" target="_blank">Application インサイト で Java</a></span> トレース ログを探索する - お気に入りのログ 記録フレームワークからログをキャプチャして、要求イベントやページ ビュー イベントと共にスライスおよびダイス<span style="font-family: Calibri; font-size: medium;">できます </span></li>
   <li><span style="font-family: Calibri; font-size: medium;"><a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-web-track-usage-custom-events-metrics/" target="_blank">Application インサイト API を使用してカスタム テレメトリを記述</a></span><span style="font-family: Calibri; font-size: medium;">する - アプリでユーザーが何を行うのかを追跡する </span></li>
   <li><span style="font-family: Calibri; font-size: medium;"><a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-monitor-web-app-availability/" target="_blank">Web サイトの可用性と応答性を監視</a></span><span style="font-family: Calibri; font-size: medium;"> する - Web テストを設定する </span></li>
   <li><span style="font-family: Calibri; font-size: medium;"><a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-java-track-http-requests/" target="_blank">Java Web アプリケーションで HTTP 要求を追跡する</a></span><span style="font-family: Calibri; font-size: medium;"> - アプリケーションに送信された HTTP 要求に関する情報を表示する</span></li>
  </ul>

  <h4></h4>

  <h1><span style="font-family: Calibri; font-size: large;"><strong>どう思いますか。</strong></span></h1>

  <span style="font-family: Calibri; font-size: medium;">フィードバックをお寄せください。どうすればこれを向上させるでしょうか。お知らせください。</span>
