### YamlMime:Yaml
ms.openlocfilehash: 9c451684a4cfcb036eafd6677e21925081de518d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904318"
Slug: application-insights-content-pack-for-power-bi
Title: Application インサイト Content Pack for Power BI
Summary: 新しい Application インサイト Content Pack for Power BI について学習します。
Content: >-
  <p>Power BI 用の<a href="https://azure.microsoft.com/en-us/services/application-insights/">新しい Application インサイト</a> コンテンツ パックを<a href="https://powerbi.com"></a>使用すると、カスタマイズ可能なダッシュボードとレポートのコレクションでユーザーに対する新しい分析情報を取得できます。&nbsp;視覚化には、国/地域別のユーザーの場所を示すマップと、概要統計とアクティビティの時系列の両方が含まれます。</p>


  <p>アプリケーションを監視するために <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-overview/">Visual Studio Application インサイト</a> を既に設定している場合 (&rsquo;これは簡単です)、このコンテンツ パックは、過去 30 日間のアプリケーション使用状況の傾向を視覚化する機能の優れた拡張機能を提供します。 このPower BI、同じダッシュボード上の複数のソースのデータを結合できます。そのため、たとえば、売上データと Web サイトの使用状況を同じリアルタイム プレゼンテーションにプルできます。</p>


  <p>セットアップには 2 分かかります。 すぐに&#39;ダッシュボードの例を次に示します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5aee0a97-3e6c-486b-bcba-4f3ecb809988.png"><img alt="AIPBIDashboard" border="0" height="331" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f96a2791-3e9a-4427-a44f-dce851d2e9f9.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="AIPBIDashboard" width="684"></a></p>


  <p>このマップには、このアプリケーション&rsquo;ユーザーの場所が表示され、グラフには過去 30 日間のユーザー数が表示されます。<br>

  当然ながら、ダッシュボードは簡単に変更できます。そのため、必要な場所&#39;最も関連性の高いデータをすばやく取得できます。&nbsp; さらに良い場合は、設定が非常に簡単です。 見&rsquo;てみ&hellip;</p>


  <h2>ダッシュボードまで 2 分</h2>


  <p>アプリケーション を使用してアプリケーション ダッシュボードを起動インサイト実行するには、わずか数分Power BI。 この&#39;手順を説明します。</p>


  <ol>
   <li>Azure プレビュー ポータルでアプリ&rsquo;の [アプリケーションインサイト概要<a href="https://portal.azure.com/">] ブレードに移動します</a>。&nbsp;間&rsquo;近で、ここからいくつかの情報が必要です。 (アプリ用に&rsquo; Application <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-overview/">インサイトをまだ</a>設定していない場合は、しばらく時間を取ってそれを行います。</li>
   <br>
   <li>Power BI <a href="https://powerbi.com/groups/me/getdata/services/application-insights">の Application インサイト コンテンツ</a> パックに移動し、[ データの取得] 、 [サービス] 、 [アプリケーション インサイト] の順にConnect。<br>
   <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7ab87190-7dda-438c-a218-91d178bb8e40.png"><img alt="ConnectFlow" border="0" height="258" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8117efba-8722-4f27-aeaf-ca94f742fd43.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="ConnectFlow" width="589"></a></li>
   <br>
   <li>[アプリケーションConnect&ldquo;にインサイト&rdquo;ページで、Azure プレビュー ポータルから 3 つの必須値をコピーして貼り付Power BI。<br>
   <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/26c5169c-e422-40cf-8f37-4bfeed4dd6d8.png"><img alt="AppInsightPowerBIConfigure" border="0" height="344" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/45a1179c-0957-4a4b-a018-bec574fa148b.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="AppInsightPowerBIConfigure" width="809"></a></li>
   <br>
   <li>&ldquo;&rdquo; 次のページで、[サインイン] をクリックし ([認証方法] を [OAUTH2] のままにします)、資格情報の入力を求めるメッセージが表示されたら、Azure プレビュー ポータルでアプリケーションにアクセスするために必要な資格情報を入力します。</li>
   <br>
   <li>Power BIデータが&rsquo;インポートされ、約 1 分後に、独自のアプリケーションに対して上記のようなダッシュボードが表示されます。</li>
  </ol>


  <h1>まとめ</h1>


  <p>これで、&rsquo;アプリケーションの重要な使用状況&rsquo;の統計情報 (ユーザー数、セッション数、地域など) を表示するダッシュボードが作成されました。他の方法を選択して、データの表示、再配置、または他のソースからのデータとの結合を行うことができます。</p>


  <p>これは Application インサイト コンテンツ&rsquo; パックの最初のイテレーションであり、Power BIの機能はすべて確実に多く実行できます。&nbsp;新機能や改善された機能については、Application インサイト User Voice ページでアイデアを共有してください。質問がある場合は、Application インサイト フォーラムをご<a href="https://social.msdn.microsoft.com/Forums/en-US/ApplicationInsights/">覧ください</a>。</p>
