### YamlMime:Yaml
ms.openlocfilehash: 0c52196e7ebf8f5396509dca274921d27e4b7a61
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895158"
Slug: application-insights-temporary-limitations-and-performance-improvements
Title: アプリケーション インサイト - 一時的な制限とパフォーマンスの向上
Summary: 過去数か月間に Application インサイト のパフォーマンスと安定性が大幅に向上し、ユーザーのエクスペリエンスを迅速かつ信頼性の高いものにすることを目指しています。
Content: >-
  <p>過去&rsquo;数か月間に <a href="https://azure.microsoft.com/services/application-insights/"><u>Application インサイト</u></a> のパフォーマンスと安定性が大幅に向上し、エクスペリエンスを迅速かつ信頼性の高いものにすることを目指しました。 Application&rsquo; インサイトがプレビューの間、ほぼ毎日改善されています。 リファクタリングの一環として、一&rsquo;部のデータを移動し、小さな制限を課す必要があります。</p>


  <h1>検索クエリ期間の一時的な削減</h1>


  <h3>何が起こるか</h3>


  <ul>
   <li>
   <p>2015 年 10 月 28 日 (水曜日の午後、太平洋時間) に、検索クエリを実行できる期間を一時的に <a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/"><u>短縮します</u></a>。 Standard&rsquo;&rsquo; または プレミアム&rsquo; 価格レベルを使用している場合でも、7 日以上前に戻る検索クエリを実行できると思われます。</p>
   </li>
   <li>
   <p><a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/"><u>メトリックス エクスプローラー</u></a> プランに従って、すべての集計データを 1 分間の細分性まで提供 <a href="https://azure.microsoft.com/pricing/details/application-insights/"><u>し続ける予定です</u></a>。</p>
   </li>
  </ul>


  <h3>それはなぜでしょうか?</h3>


  <ul>
   <li>
   <p>これは、改善プログラムの計画的な部分として行っています。 データ ストレージ アプローチをリファクタリングし、さまざまなインデックスから検索クエリとメトリック クエリを提供し、パフォーマンスを大幅に向上させます。</p>
   </li>
  </ul>


  <h3>これは一時的なものですか?</h3>


  <ul>
   <li>
   <p><strong>はい</strong>。 標準のデータ保有期間は、今後数週間で復元される予定です。 クエリ&rsquo;のパフォーマンスの向上にすぐに気付きます。</p>
   </li>
  </ul>


  <h1>継続的な機能強化</h1>


  <p>この&rsquo;一時的な措置によってご不便をおかけして申し訳ございません。 この変更は、継続的な改善プログラムの一部です。 過去数か月間の実績の一部を次に示します。</p>


  <ul>
   <li>
   <p><strong>UI のパフォーマンス: </strong>ページとクエリの読み込み速度が 2 倍になった。 キャッシュ&rsquo;、プリフェッチ、データ ボリュームのシリアル化/シリアル化の縮小、コードのリファクタリング、クエリのパフォーマンス、非同期呼び出し、UI geo ディストリビューションなどについて改善しました。</p>
   </li>
   <li>
   <p><strong>UI の信頼性</strong>: Application インサイト コンポーネントの一部の負荷により、サービスに自信を持って依存できると考える重要な信頼性の向上が実現されました。</p>
   </li>
   <li>
   <p><strong>データのスケーラビリティ:</strong> トラフィックの増加はここ数か月で 2 倍に増え、容量を増やす必要があります。 追加のデータ収集のエンド ポイントは、世界中の多くの異なるデータ センターにデプロイされ、米国中南部に追加の処理データ センターが追加されました。</p>
   </li>
  </ul>


  <p>もちろん、Application&rsquo; インサイトを使用して、すべての問題を検出、トリアージ、診断し、継続的な改善を提供しています。 これらの変更により、Application インサイトエクスペリエンスが向上すると考インサイト、お客様から直接ご意見をお聞かしく思います。 ユーザーの声とフォーラムに関するフィードバック、提案、または質問をお寄 <a href="https://social.msdn.microsoft.com/Forums/en-US/home?forum=ApplicationInsights"><u>せください</u></a>。</p>
