### YamlMime:Yaml
ms.openlocfilehash: 9d73ea6f733c6f574828b49deba4af82f6407645
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904319"
Slug: application-insights-connector-for-microsoft-flow-and-azure-logic-apps
Title: コネクタを使用して Application Insights プロセスを自動化し、Flow と Logic Apps
Summary: Azure アプリケーションインサイトは、テレメトリデータに対してクエリを実行し、洞察を得るための強力な検索機能を提供します。 多くの場合、同じクエリを繰り返し実行して、サービスが正常に機能しているかどうかを検証したり、傾向や異常を検出したりすることがあります。 これらの反復的なクエリを自分のワークフローに変えることは、時間を節約し、これらの洞察をアクションに変えることができるようにするのは賢明ではないでしょうか。
Content: >-
  <p><a href="https://azure.microsoft.com/services/application-insights/" target="_blank">Azure アプリケーションインサイト</a>は、テレメトリデータに対してクエリを実行し、洞察を得るための強力な検索機能を提供します。</p>


  <p>多くの場合、同じクエリを繰り返し実行して、サービスが正常に機能しているかどうかを検証したり、傾向や異常を検出したりすることがあります。 &rsquo;反復的なクエリを独自のワークフローに変換することは、時間を節約し、それらの洞察をアクションに変えることができるようにするのに便利です。 これで、 <a href="https://flow.microsoft.com/services/shared_applicationinsights/?slug=azure-application-insights" target="_blank">Microsoft Flow</a>と<a href="https://docs.microsoft.com/azure/logic-apps/logic-apps-what-are-logic-apps" target="_blank">Azure Logic Apps</a>に Application Insights コネクタを使用して、自動化されたワークフローを視覚的に作成できるようになりました。</p>


  <p>現在プレビュー中の Application Insights コネクタを使用して、Application Insights アクションを使用してテレメトリデータを照会または視覚化するワークフローを作成できます。 これらは、選択した他のアクションと共に自動的に実行 &nbsp; することができます。 電子メール通知の送信、Visual Studio Team Services でのバグの作成、余裕や Microsoft Teams でのメッセージの投稿など、数百の操作が可能です。</p>


  <p>Microsoft Flow 統合のサンプルスクリーンショットを次に示します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/625f2b9b-4061-4129-92be-11f0d546da74.png"><img alt="Azure Application Insights connector for Microsoft Flow" border="0" height="469" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/02937edb-3fef-43ab-ad75-21639e85e16a.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="Microsoft Flow の Azure アプリケーションインサイトコネクタ" width="610"></a></p>


  <p>Azure Logic Apps 統合のサンプルスクリーンショットを次に示します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/eb57aebe-05ae-46f2-8334-37fde075a332.png"><img alt="Azure Application Insights connector for Azure Logic Apps" border="0" height="610" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3102cf7b-4682-4769-b84a-33571c34dbd5.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="Azure Logic Apps の Azure アプリケーションインサイトコネクタ" width="573"></a></p>


  <p><a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-automate-with-flow" target="_blank">コネクタを使用</a>して Azure アプリケーションインサイトプロセスを自動化する方法の詳細については Microsoft Flow または<a href="https://docs.microsoft.com/en-us/azure/application-insights/automate-with-logic-apps" target="_blank">Azure Logic Apps</a>を参照してください。</p>


  <p>今すぐ <a href="mailto:aiflowfb@microsoft.com">aiflowfb@microsoft.com</a> お試しください。</p>


  <p>皆様からのご意見をお待ちしており &rsquo; ます。</p>
