### YamlMime:Yaml
ms.openlocfilehash: de1af79f86f343e4417a4611e03ad175c01aa987
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139894593"
Slug: application-aware-availability-solutions-with-azure-site-recovery
Title: Application-Awareを使用した可用性ソリューションAzure Site Recovery
Summary: 過去数か月間、Microsoft ではこれらのアプリケーション グループと密接に連携して取り組み、ASR を使用してクラス最高のディザスター リカバリーと可用性ソリューションをデプロイできます。
Content: >-
  Azure Site Recoveryを使用すると、アプリケーションに <a href="https://aka.ms/asr_workload_aod">対応した可用性をオンデマンド ソリューションにデプロイ </a>できます。 Windows Server または Linux ベースのアプリケーション、Microsoft ファースト パーティのエンタープライズ アプリケーション、または他のベンダーのオファリングを使用する場合は、Azure Site Recovery を使用して、ディザスター リカバリーを有効にしたり、オンデマンド DevTest 環境をデプロイしたり、Azure に移行したりすることができます。 ASR レプリケーション テクノロジでは、すべてのディスクとデータを使用して仮想マシン全体を保護できます。 これにより、マシン上で実行されている <strong><em>任意のアプリケーション</em></strong> と互換性があります。


  Microsoft は、SharePoint、Exchange、Dynamics、SQL Server などのクラス最高のエンタープライズ アプリケーションの開発に関する深い専門知識と経験を持SQL Server。 過去数か月間、Microsoft ではこれらのアプリケーション グループと密接なパートナーシップを結び、ASR を使用してカスタマイズされたディザスター リカバリーと可用性ソリューションをデプロイできます。Azure Site Recoveryソリューションはテスト済みであり、<strong>SharePoint、Dynamics AX、Exchange 2013、リモート デスクトップ サービス、SQL Server、IIS</strong> アプリケーション、System Center ファミリ (Operations Manager など) でサポートされています。Microsoft アプリケーションに加えて、SAP や Linux の異なるディストリビューションで実行されているアプリケーションなど、サード パーティ製アプリケーションの広範なテストとサポートも行っています。


  Azure Site Recovery機能は、アプリケーション レベルの保護と回復を念頭に置いて設計されています。

  <ul>
      <li><b><i>最も重要な</i></b> アプリケーションのニーズを満たす、30 秒という低い RPO でのほぼ同期レプリケーション。</li>
      <li><strong><em>単一層または</em></strong> N 層アプリケーションのアプリ整合性スナップショット</li>
      <li><b><i>柔軟に選択し、 &amp; アプリ レベルのレプリケーションと統合できます</i></b>。 AD レプリケーション、レプリケーション、データベース可用性グループ (該当する場合SQL Always On、Exchangeなど、クラス最高のアプリケーション レベルのオファリングを活用します。 他の層には、ASR の組み込みレプリケーションを使用します。</li>
      <li><b><i>拡張可能な復旧計画。 </i></b>アプリケーション全体をモデル化し、アプリケーション対応の復旧/移行ワークフローを整理します。 必要に応じて、シングル クリックエンドからエンド アプリケーションの回復をトリガーします。</li>
      <li>ASR <b><i>と</i></b> Azure での高度なネットワーク管理。 アプリケーションに固有のすべてのネットワーク構成を自動化します。IP アドレスの予約、ロード バランサーの構成、またはトラフィック マネージャーを使用して低い RTO 切り替えを実現します。</li>
      <li><b><i>実稼働可能な</i></b> アプリケーション固有のスクリプトを提供するリッチ オートメーション ライブラリ。 それらをダウンロードし、ASR ベースのソリューションに統合します。</li>
  </ul>

  &nbsp;


  SharePoint または Dynamics AX のデプロイを管理している場合は、ASR を使用して、DR または DevTest のスタンドアロン デプロイを維持するコストとオーバーヘッドを排除できます。 ASR では、ファーム全体をレプリケートし、ディザスター リカバリーや、実稼働に似たテスト コピーの作成のためにオンデマンドで起動できます。 プライマリ ファームにデプロイされた新しいアプリケーションまたは構成の変更は数分以内に自動的にレプリケートされます。そのため、セカンダリ ファームを最新の状態に保つために複雑なプロセスに投資する必要はありません。


  SQLサーバーは、多くの重要なエンタープライズ アプリケーションの基盤です。 <a href="https://aka.ms/asr_workload_sql">ASR を使用すると、別のサイト</a>または Azure SQL Serverを簡単にレプリケートおよび復旧できます。 ASR は、SQL Always On 可用性グループなどのクラス最高のネイティブ ディザスター リカバリー ソリューションと統合し、ASR 復旧計画の一部としてフェールオーバー操作を管理することもできます。


  サーバー Exchange、DAG はクラス最高のディザスター リカバリー ソリューションを提供し、推奨されるデプロイ オプションです。 ASR 復旧計画を DAG と統合して、スクリプト化されたアクションを介してサイト間の DAG フェールオーバーを調整できます。 1 台Exchangeクラスター化されていないサーバーなど、小規模な Exchange 2013 のデプロイの場合、お客様は Azure Site Recovery を使用して、セカンダリ オンプレミス サイトにサーバーを保護できます。


  Windows Server リモート デスクトップ サービスは、ユーザーがセッション ベースのデスクトップ、仮想マシン ベースのデスクトップ、またはアプリケーションにアクセスできるテクノロジを提供します。 ASR を使用すると、RDS デプロイ用のディザスター リカバリーまたはクラウド バースト ソリューションをデプロイし、忠実度の高いデスクトップ エクスペリエンスを常に顧客が利用できます。


  IGNITE カンファレンスで、これらのアプリケーション固有のソリューションとサポートされている構成について詳細に説明します。 ASR 関連の <a href="https://aka.ms/asr_at_ignite">セッションは、今週 IGNITE でチェックアウトすることをお勧めします</a>。 また、これらのソリューションを環境に簡単にデプロイするのに役立つ詳細な技術ガイダンスについては、今後数週間以内にドキュメント サイトを通じて共有します。これは現在も続く取り扱いであり、より多くのアプリケーションをカバーし、アプリケーションに対応した豊富なエクスペリエンスを Azure Site Recovery。


  ASR を使用してディザスター リカバリーをデプロイするためのベスト プラクティスについては、 <a href="https://aka.ms/asr_ignite_app_aware">Ignite セッションからの記録を確認してください</a>。
