### YamlMime:Yaml
ms.openlocfilehash: 52a0a9cb8c0319b3a59fc4146f17d1fe6db87af0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904326"
Slug: application-insights-analytics-grid
Title: サービスでの新しいグリッド コントロール
Summary: Visual Studio Application インサイト の Analytics の強力な新しいグリッド表示に気付インサイト。 フィルター処理、並べ替え、グループ化、ページ表示が備わるので、大きなクエリ結果を探索するのに最適です。
Content: >-
  <p>Visual Studio Application インサイト の <a href="https://blogs.msdn.microsoft.com/bharry/2016/03/28/introducing-application-analytics/">Analytics</a> の強力な新しいグリッド表示に気付インサイト? フィルター処理<strong>、並べ替え、グループ</strong>化、ページ表示が備わるの<strong>で</strong>&ndash;、大きなクエリ結果を探索するのに最適です。 また、例外 <strong>スタックやカスタム プロパティなどの</strong> 入れ子になったデータを拡張できます。 これはすべて、最後のクエリから返されたデータに対して機能し、再び実行する必要があります。</p>


  <h2>並べ替えとグループ化</h2>


  <p>列の頭をクリックして結果を並べ替える。 もう一度クリックしてもう一方の方法を並べ替え、3 回目は元の順序に戻します。 この機能を使用すると、ポータルから受け取った結果が並べ替わるだけで、クエリは再び実行されません。 クエリに take、&quot;limit&quot; &quot;&quot;&quot; 演算子、または top&quot;&rsquo; 演算子が含まれている場合でも、返された結果のセットだけが表示されます。</p>


  <p>複数の&rsquo;列で並べ替えたい場合は、グループ化を使用します。 テーブル設定で [グループ化を有効にする] が選択されている必要があります。 テーブルの上のスペースに列見出しをドラッグします。</p>


  <p><img alt="New grid control - Application Insights Analytics" border="0" height="289" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/acfb022b-abc6-4b70-8732-29afd1442557.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="複数の列によるグループ化" width="480"></p>


  <h2>フィルター処理</h2>


  <p>各&rsquo;列のヘッドにフィルター アイコンがあります。 文字列と数値にはさまざまな条件を使用できます</p>


  <p><img alt="New grid control - Application Insights Analytics" border="0" height="294" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0f9a12a7-eebb-4754-a9c7-8d5c3c809ac5.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="列にフィルターを適用する" width="250"></p>


  <h2>入れ子になったデータ構造</h2>


  <p>行を展開してすべてのプロパティを表示すると、例外スタック トレースやカスタム ディメンション (それ以外の場合は長い JSON 行として表示される項目) などの項目を展開できます。</p>


  <p><img alt="New grid control - Application Insights Analytics" border="0" height="290" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d15aec61-804b-48a7-8a9a-9d38f729706e.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="入れ子になったデータ構造" width="480"></p>


  <h2>&hellip;とすべての通常の情報</h2>


  <p>&rsquo;&rsquo;気が付かない場合に備えて、期待していたすべてのことを行えます。列セレクター ボタンが右にある列を選択し、ヘッダーをドラッグして列を再配置し、境界をドラッグして列のサイズを変更します。 長いデータはページに分割されます。 各ページの下部にある コントロールを参照して&nbsp;、ページ間を移動し、ページあたりのレコードの最大数を設定します。</p>


  <p>いつものように、次のいずれかのチャネルまたは以下のコメント スレッドを使用して、ご質問やフィードバックをお寄せください。</p>


  <ul>
   <li><a href="https://analytics.applicationinsights.io/demo">Application インサイト Analytics を試す</a></li>
   <li><a href="https://visualstudio.uservoice.com/forums/357324-application-insights/category/161991-analytics">Application インサイト Ideas でアイデアを提案して投票する</a></li>
   <li><a href="https://social.msdn.microsoft.com/Forums/vstudio/home?forum=ApplicationInsights">Application インサイト Community で会話に参加する</a></li>
  </ul>
