### YamlMime:Yaml
ms.openlocfilehash: a5a5f65243d412e7531c94ed6752219b304b1ecf
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904304"
Slug: application-insights-pricing-effective-june-1
Title: Application インサイト Pricing Effective 6 月 1 日 (更新)
Summary: Application インサイト のパブリック プレビューの一環として、アプリケーションごとのデータ量に基づいており、すべての開発チームに大きな価値を提供するように設計された、クラウド対応の新しい価格モデルを開始します。 価格は 2015 年 6 月 1 日に適用され、パブリック プレビュー中は 50% の割引が適用されます。
Content: >-
  <p><a href="https://www.buildwindows.com/">Microsoft BUILD</a> カンファレンスおよび <a href="https://azure.microsoft.com/blog/2015/04/29/announcing-application-insights-public-preview-2/">Merav Davidsons&rsquo;</a> の最近のブログ記事では、Visual Studio <a href="https://azure.microsoft.com/services/application-insights/">Application インサイト</a>がパブリック プレビューの準備ができていることを発表しました。 Application インサイト パブリック&rsquo; プレビューの一環として、アプリケーションごとのデータ量に基づいて<a href="https://azure.microsoft.com/pricing/details/application-insights/"></a>おり、すべての開発チームに大きな価値を提供するように設計された、クラウド対応の新しい価格モデルを開始します。 価格は 2015&nbsp; 年 6 月 1 日に適用され、パブリック プレビュー中は 50% の割引が適用されます。 Free レベル <strong>では、</strong>データの量と保持期間にいくつかの制限があるほとんどの機能を利用できます。 &nbsp;&nbsp;アプリケーションのデータ量が増え、データ量が増えるにつれて、またはより豊富な分析のためにデータにアクセスしたい場合は、<strong>Standard</strong> レベルと <strong>プレミアム</strong> レベルを利用して、各レベルに含まれるデータ ポイントの月間クォータを増やし、データを長い期間保持し、連続エクスポート機能を有効にできます。<a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/"></a> データの量に対して支払います。 Web アプリの場合、&rsquo;デプロイされているサーバーの&rsquo;数は関係ありません。 使用していないリソースに対してペナルティを受けることなく、動的にスケーリングを行&rsquo;いたいと思っています。 Free、Standard、プレミアム レベルに加えて、各 Application インサイト リソースは無料<strong>の 30 日間試用版プレミアムされます</strong>。 これには、プレミアム レベルのすべての機能がありますが、月額料金はかからないので、Application インサイト の完全なエクスペリエンスを利用し、特定のアプリケーションに適したレベルを決定できます。</p>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/05/21/Pricing-Blog-0-Pricing-Tiers.png"><img alt="Pricing Blog 0 - Pricing Tiers" class="alignnone size-medium wp-image-297371" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing-Blog-0-Pricing-Tiers-596x369.png" width="596"></a></p>


  <h2>Application インサイト の価格の管理</h2>


  <p>Application インサイト リソースの価格レベルを選択するには&ldquo;、リソースを開き、設定 コマンドをクリックして、[<strong>クォータ + 価格] オプションを選択</strong>&rdquo;します。</p>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/05/21/Pricing-Blog-1-Settings-with-arrow.jpg"><img alt="Pricing Blog 1 - Settings (with arrow)" class="alignnone size-medium wp-image-297392" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing-Blog-1-Settings-with-arrow-593x369.jpg" width="593"></a></p>


  <p>[クォータと価格の &ldquo;<strong>構成] ブレードが開</strong>&rdquo; きます。</p>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/05/21/Pricing-Blog-2-Quota-and-pricing-config-blade.jpg"><img alt="Pricing Blog 2 - Quota and pricing config blade" class="alignnone size-medium wp-image-297421" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing-Blog-2-Quota-and-pricing-config-blade-357x369.jpg" width="357"></a></p>


  <p>ブレードを時計回りに操作する場合、最初のタイルは今月の &ldquo;<strong>データです</strong>&rdquo;。 これは、今月これまでに使用された現在&rsquo;のレベルクォータの割合を示しています。 各カレンダー月の最初の日に累積テレメトリリセットの数。 (これは、このリソース サブスクリプションの課金サイクルと必ずしも同じではない点に&rsquo;注意してください)。この数には、クォータがないセッション テレメトリ (セッションの数、地域、環境データ、デバイスの種類データなど) を除き、Application インサイト によって収集されたデータすべてが含まれます。 クォータにカウントされるデータ ポイントの種類は次のとおりです。</p>


  <ol>
   <li><strong>要求</strong>: マネージド アプリケーションによって受信された、または TrackRequest API 経由で送信された要求</li>
   <li><strong>例外:</strong> 収集された未処理の例外/クラッシュ、または TrackException API 経由で送信された各例外</li>
   <li><strong>依存関係:</strong> マネージド アプリケーションからのリモート依存関係への各呼び出し</li>
   <li><strong>ページ ビュー</strong>: Web サイト、モバイル アプリケーション、または TrackPage API 経由で送信された各ページ</li>
   <li><strong>パフォーマンス カウンター</strong>: 収集されたパフォーマンス データの各インスタンス (既定のカウンターまたはユーザー指定の <a href="https://blogs.msdn.com/b/visualstudioalm/archive/2015/04/01/application-insights-choose-your-own-performance-counters.aspx">カウンターとして</a>)</li>
   <li><strong>カスタム イベント</strong>: TrackEvent API を介して送信される各イベント</li>
   <li><strong>カスタム metrics</strong>: TrackMetric API を介して送信される各メトリック</li>
   <li><strong>トレース ログ</strong>: ログ アダプターまたは TrackTrace API <a href="https://azure.microsoft.com/documentation/articles/app-insights-asp-net-trace-logs/">からの各トレース</a> エントリ</li>
   <li><strong>Web テスト データ:</strong> テストの成功/失敗に関する Web テストによって生成されたデータ</li>
  </ol>


  <p>Web テストから送信されたデータは、間もなくクォータに対してカウントされます。 次のタイルでは、選択した価格レベルに含まれるクォータを超えたテレメトリ データの収集を有効にするかどうかを構成できます。 このオプションは、Free レベルでは使用できません。 既定では、アプリケーション インサイトリソースは、この追加のテレメトリを収集することはできません。これは明示的にオプトイン モデルです。 この下に [価格レベル &ldquo;<strong>] タイル</strong>&rdquo; があります。 これをクリックすると、[価格レベルの選択 &ldquo;] ブレードが開&rdquo; きます。 ここでは、使用する価格レベルを選択できます。 6 月 1 日より後に作成された Application インサイト リソースはすべて Free レベルで作成され、いつでも Standard、プレミアム、または 30 Day プレミアム 試用版レベルに移行できます。 いつでも 30 日間 プレミアム 試用版を開始できますが、開始すると、リソースは 30 日間このレベルに残されます。 試用版の最後に、リソースは、試用版を開始する前の価格レベルに戻されます。 試用版の最後に別の価格レベルに変更する場合は、このブレードを使用して、試用期間中の任意の時点でそのレベルを選択できます。</p>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/05/27/Pricing-Blog-3-Pricing-tier-blade.jpg"><img alt="" class="alignnone wp-image-302581 size-medium" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing-Blog-3-Pricing-tier-blade-594x369.jpg" width="594"></a></p>


  <p>最後に、このブレードの一番下のタイルである [データ ポイント ボリューム] には、過去 30 日間にこのアプリケーションで処理されたデータ ポイントの数が表示されます。これにより、傾向を監視し、データ 量に最も影響を与えるデータの種類を把握できます。<strong></strong>&rdquo; &ldquo;</p>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/05/21/Pricing-Blog-4-Data-volume.jpg"><img alt="Pricing Blog 4 - Data volume" class="alignnone size-medium wp-image-297481" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing-Blog-4-Data-volume-533x369.jpg" width="533"></a></p>


  <h2>6 月 1 日の変更点</h2>


  <p>2015 年 6 月 1 日に Application インサイト の価格を有効にした場合、アクティブなすべての Application インサイト リソースを <strong>30 日間 プレミアム 試用版</strong>の価格レベルに移行します。 つまり、今後 30 日間は、Application インサイト&rsquo; の最高レベルの機能とデータ ボリューム クォータを取得し、この移行中に継続的エクスポートを採用しているユーザーが影響を受けずにいます。 (上で説明したように、この変更後に作成された Application インサイト リソースはすべて Free 価格レベルで開始され、30 日間試用版を使用する場合はプレミアムされます)。30 日間の試用版の最後に、すべてのリソースが既定で Free 価格レベルに戻されます。 連続エクスポートを使用している場合は、30 日間の試用版の終了前に Standard または プレミアム の価格レベルを選択して、中断のないエクスポート機能を確保してください。 もちろん、メール&rsquo;でも通知します。</p>


  <h2>まとめ</h2>


  <p>Application インサイト<a href="https://azure.microsoft.com/pricing/details/application-insights/">クラウド</a>対応&rsquo;価格モデルの実装は、2015 年 6 月 1 日に開始されます。 このモデルは、アプリケーションごとのデータ量に基づいており、すべての開発チームに無料で大きな価値を提供するように設計されています。 Application インサイト で監視されているすべてのアプリケーションは、この時点で 30 日間の プレミアム 試用版に追加され、現在 Application インサイト から取得しているのと同じエクスペリエンスが提供されます。 ただし、30 日間の試用版では、テレメトリボリュームと必要な機能 (データ保有期間と連続エクスポートの長さ) に基づいて、アプリケーションに最適な価格レベルを検討し、試用版の終了後にアプリケーションに使用するレベルとして選択する必要があります。</p>


  <h2>更新 (6 月 27 日)</h2>


  <p>サービスを評価する時間を長くプレミアム、Premium 試用版<strong>を延長しています</strong>。 6 月 17 日より前プレミアム試用版が有効になっているすべてのリソースについて、試用版は 7 月 17 日まで自動的に延長されます。 お使いの部分で必要&ndash;なアクションはありません。これは、すべてのアプリケーション リソースとリソースインサイトされます。 現在のデータ ボリュームを監視して、適切なアプリケーション レベルと価格レベルを選択<a href="https://azure.microsoft.com/pricing/details/application-insights/">インサイトすることをお勧めします</a>。 また、Standard レベルと プレミアム <a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/">レベル</a>でのみ使用できる継続的エクスポートのような機能を試してください。 価格プランの詳細&ldquo;&rdquo;については、各 Applications Insight の概要ブレードの 設定 オプションから評価できる [クォータと価格の構成] ブレードを参照してください。</p>


  <h2>更新 (9 月 4 日)</h2>


  <p>今週は、クォータのリソースに対してカウントされるデータ ポイント ボリュームに Web テスト データを&#39;しました。</p>
