### YamlMime:Yaml
ms.openlocfilehash: ad8a290df513f900a83c8044d365dcaedf660777
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912952"
Slug: application-insights-work-item-integration-with-github
Title: 'アプリケーション インサイト: 作業項目と作業項目の統合GitHub'
Summary: Application インサイトチームは、Application インサイト から直接作業項目 (問題 GitHub) を作成するサポートを追加しました。
Content: >-
  <p>1 か月以上前に、Application <a href="https://azure.microsoft.com/en-us/blog/application-insights-work-item-integration-with-visual-studio-team-services/" target="_blank">インサイト の新</a>しい機能セットを発表しました。作業項目と Visual Studio Team Services。 今日は、分析をワークフローに統合しようとしているユーザーに対して、より良いニュースがあります。 同じようなエクスペリエンスの作業を終えたGitHub。 数分で、Application インサイト リソースを構成して、重要な Application インサイト データを含む問題を GitHub プロジェクトに書き込む必要があります。</p>


  <h3>作業項目の統合の構成</h3>


  <p>Application インサイト リソースと GitHubの統合の構成は、VSTS に使用される手順と非常に似た動作をします。 そのリソースの設定ブレードに移動します。 [&rsquo;設定] ブレードの [構成] &ldquo;セクションに&rdquo; [作業項目] と表示されている項目を &ldquo;メモします。&rdquo;</p>


  <p><img height="360" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9434e196-ddd0-4402-981e-81b56a3969ed.png" width="303"></p>


  <p>これをクリックすると、作業項目の構成ブレードが開きます。 構成ブレードの&ldquo;上部にある&rdquo; [追跡システム] ドロップダウンがアクティブで、2 つの選択肢があります。そのうちの 1 つは GitHub。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/aadb0523-b41d-484d-9c9a-6320b88e261e.png"><img alt="image" border="0" height="44" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/10993b9c-c058-4011-82a1-0c1accff4c6f.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="イメージ" width="360"></a></p>


  <p>[GitHub] を選択します。 その後、接続するプロジェクトにマップする URL GitHub入力する必要があります。</p>


  <p><img alt="image" border="0" height="407" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d8e672a4-4af9-4d1f-8248-38929b8ca3d2.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="480"></p>


  <p>その情報が表示された後、[承認] ボタンをクリックすると、選択した GitHub プロジェクトでアクセスを承認するようにリダイレクトされ、作業項目 (問題) をそこに書き込むことになります。</p>


  <p><img alt="image" border="0" height="244" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/535a0139-2201-4e8e-8d4d-9e67c93d6bfd.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="480"></p>


  <p>注: この時点で、GitHubにまだログインしていない場合は、ログインするように求めるメッセージも表示されます。</p>


  <p>承認プロセス&rsquo;が完了したら、[OK] をクリックします。 [&rsquo;検証に成功しました] という &ldquo;メッセージが表示され&rdquo; 、ブレードが閉じます。 これで&rsquo;、問題の作成を開始する準備ができましたGitHub。</p>


  <h3>作業項目の作成</h3>


  <p>Application インサイトから作業項目を作成するのは非常に簡単です。 現在、作業項目を作成できる場所には、プロアクティブ検出とアクティビティの個々のインスタンス (例外、エラー、要求など) の 2 つの場所があります。 後者の簡単な例を示しますが、どちらの場合も機能は同じです。</p>


  <p>この例では、Azure&rsquo; に発行したテスト Web アプリを確認します。 [エラー] ブレードを見て、このアプリのアクティビティにドリルダウンし始めました (ただし、[検索] ボタンまたは [エラー] ボタンを使用してこの同じ情報メトリックス エクスプローラー)。</p>


  <p><img alt="image" border="0" height="321" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/aed665c7-5978-4b62-84fd-c46e508ba361.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="610"></p>


  <p>この Web アプリで発生した例外が多数表示されるのを確認できます。 この例外のグループにドリルダウンすると、一覧が表示され、個々の例外を選択できます。</p>


  <p><img alt="image" border="0" height="445" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f8652452-769d-49eb-b8d4-9fc9c3a97a4b.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="610"></p>


  <p>この例外の詳細&ldquo;&rdquo;&ldquo;ブレードを見て、ブレードの上部に[新しい作業項目] と [作業項目の表示] という 2 つのボタンが表示されています。&rdquo;作業項目を作成するには、これらのボタンの最初のボタンをクリックするだけで、新しい作業項目ブレードが開きます。</p>


  <p><img alt="image" border="0" height="358" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a1535dd4-643b-4e5b-89c9-3ff6dc17191a.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="610"></p>


  <p>ご覧のとおり、平均的なシナリオで必要なほぼすべての情報が自動的に入力されています。 この例外で使用できる詳細情報はすべて、詳細フィールドに追加されています。 必要に合ってタイトルをオーバーライドするか、キャプチャした詳細に を追加できます。 作業項目&rsquo;を作成する準備&ldquo;ができたら、[OK&rdquo;] ボタンをクリックすると、問題が [問題] に書き込GitHub。</p>


  <h3>作業項目の表示</h3>


  <p>Application インサイト&rsquo; で 1 つ以上の作業項目を作成したら、その作業項目を GitHub。 作業項目に関連Azure portal&ldquo;&rdquo;イベントの詳細ブレードで[作業項目の表示] ボタンが有効になります。 一覧を表示するには、ボタンをクリックします。</p>


  <p><img alt="image" border="0" height="130" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/83395f11-3203-48d3-b1de-56daac2a94d0.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="610"></p>


  <p>表示する作業項目のリンクをクリックすると、次の場所にGitHub。</p>


  <p><img alt="image" border="0" height="409" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d0c1e470-0c75-4868-b8c8-161be9fd9324.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="image" width="610"></p>


  <p>この問題の下部には、GitHub で問題を表示しているユーザーが Azure portal と Application インサイト に戻る可能性があるリンクがあります。</p>


  <p>それが&rsquo;すべてです。 ご覧のように、この機能は非常に簡単に設定できます。Application インサイトから問題を作成するのは簡単です。</p>


  <p>VSTS 作業項目の統合<a href="https://azure.microsoft.com/en-us/blog/application-insights-work-item-integration-with-visual-studio-team-services/" target="_blank"></a>に関する前の投稿で詳しく説明した通り、この機能を改善するための今後の計画が多く含まれる予定です。 GitHub &ldquo;との統合を完了すると、他の ALM &ldquo;&rdquo;&rsquo;システムの目標に対するサポートの一環として、Application インサイト へのリンクも提供されました (この機能は、Application インサイト&rdquo; から作成された VSTS 作業項目にも追加されています)。</p>


  <p>これは、この機能セットのもう 1 つの大きなマイルストーンですが、複数のプロファイルを設定する機能、イベントに基づいて作業項目を自動的に作成する機能、作業項目を作成するための他のソース ポイント (アラートなど) の追加など、多くの目標がまだ先に残っています。 引き続き作業項目の統合を改善および進化させ、柔軟性を高め、日常のワークフローへのシームレスな統合を実現します。</p>


  <p>いつものように、[Application インサイト UserVoice] ページで新機能または改善<a href="https://visualstudio.uservoice.com/forums/357324-application-insights">された機能に関するアイデアを共有してください</a>。 ご質問がある場合は、<a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights"><u>Application インサイト フォーラムをご覧ください</u></a>。</p>
