### YamlMime:Yaml
ms.openlocfilehash: d5072ec44b4062c4dc64d558eb937399b4e0f3f5
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904315"
Slug: application-insights-integrates-alooma
Title: 'Visual Studio Application Insights 拡張性: alooma を使用してテレメトリデータを Amazon Redshift にエクスポートする'
Summary: Application Insights は他のツールとの統合用に構築されており、これをさらに簡単にするための計画についての情報をお伝えしたいと思います。 しかし、最初に、統合パートナーの1つである Alooma を紹介します。
Content: >-
  <p><a href="https://azure.microsoft.com/services/application-insights/">Visual Studio Application Insights</a>は他のツールとの統合のために構築されています。今日 &rsquo; の計画については、今後もさらに簡単に行うことができます。 しかし、最初に、1つ目の例として、統合パートナー &ndash; の1つを<a href="https://www.alooma.com/">紹介します。</a> alooma &rsquo; s SaaS サービスを使用すると、Application Insights によって収集された未加工のテレメトリイベントを、Amazon Redshift などのデータウェアハウスに直接簡単に変換できます。 このデータは、分析ツールと BI ツールのホストがアクセスできるようになります。</p>


  <p><img alt="Export Application Insights data to Amazon Redshift with Alooma" border="0" height="279" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b4b98fe2-45a8-4c53-ba1b-6169add7d854.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="alooma を使用して Application Insights データを Amazon Redshift にエクスポートする" width="800"></p>


  <p>簡単に言うと、次のことが可能になります。</p>


  <ul>
   <li>データソースを簡単に統合: さまざまな組み込みコネクタを使用するか、Alooma &rsquo; Web api とモバイル api を使用して独自のものを作成します。</li>
   <li>データを即座に変換: ストリーム変換を使用すると、リアルタイムでデータのフィルター処理、クリーンアップ、修正、強化を行うことができます。</li>
   <li>データの格納方法を制御する: データをテーブルに Automap するか、データ探索ツールを使用して最適なマッピングを作成します。</li>
   <li>スキーマの変更をインテリジェントに処理: データに新しいフィールドが表示されたとき、または既存のフィールドが別の形式で表示されたときに通知を受け取ります。 新しいスキーマからのイベントは、どのように読み込むかを決定するまで保持されます。データは失われません。</li>
   <li>透過的な監視: 組み込みのダッシュボードを使用してパイプラインのパフォーマンスを監視したり、Alooma &rsquo; API を介して独自に構築したりできます。</li>
  </ul>


  <p>alooma を Application Insights と統合すると、詳細な手順については、 <a href="https://www.alooma.com/blog/application-insights-amazon-redshift">alooma を使用した Amazon Redshift へのエクスポート Application Insights を</a>簡単 &ndash; に確認できます。</p>


  <h2>Application Insights との統合</h2>


  <p>alooma は、Application Insights の最初のパートナー統合の1つです。 &rsquo;エンジニアリングチームは開発/DevOps サイクルをサポートするために多数のツールを使用する必要があることに注意してください。 私たちと同様に、特定のタスクに適したクラス最高のツールを使用し、特定のカスタムワークフローに合わせてこれらのツールを揺れ動くする必要があります。</p>


  <p>これらのニーズに対処するために、REST api やオープンソースの sdk などの業界標準の拡張機能を使用して簡単に統合できるオープンで拡張可能なプラットフォームとして Application Insights を設計しました。 これらの拡張ポイントの一部は現在利用可能であり、近日中に追加でお知らせします。</p>


  <h2>拡張機能のメカニズム</h2>


  <p>Application Insights はデータ中心のソリューションであるため、最初のフォーカスはデータ層での統合を可能にすることです。 これらは、次の2つの広範なカテゴリに分類されます。</p>


  <ol>
   <li>Application Insights へのデータの送信: アプリケーションコンポーネント、環境、インフラストラクチャ、またはアプリケーションのライフサイクルからのテレメトリデータは、Application Insights sdk または REST API を使用して送信できます。 このデータは Application Insights &rsquo; 豊富な情報モデルを使用して格納され、 <a href="https://azure.microsoft.com/documentation/articles/app-insights-portal/">Application Insights ポータル</a>のメトリックエクスプローラーと検索エクスプローラーを使用してさらに分析や視覚化を行うことができます。</li>
   <li>他のツールで Application Insights データを使用すると、Application Insights によって収集および保存されたテレメトリデータから重要な値をロック解除できます。 現在、この機能を有効にするには、<a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/">連続エクスポート</a>を使用し、 <a href="https://azure.microsoft.com/documentation/articles/app-insights-export-power-bi/">Power BI との統合</a>と、現在は alooma 統合を使用します。 では、その他の API ベースのデータソリューションが機能します。 この作業に従って、Application Insights ユーザーの声に関するフィードバックをお寄せください (追加の項目には、webhook コールバックと警告システムの統合が含まれます)。</li>
  </ol>


  <p>お客様は既にこれらのメカニズムを使用して、カスタム統合を有効にしています。 また、パートナーと協力して、より効率的な統合エクスペリエンスを実現しています。 Sdk と統合の完全な一覧については、 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-platforms/">言語、プラットフォーム、統合インデックス</a>に関する記事をご覧ください。</p>


  <p>新しい機能や改善された機能については、Application Insights ユーザーの声でご意見をお寄せください。質問がある場合は、 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights">Application Insights フォーラム</a>にアクセスしてください。</p>


  <p>潜在的なパートナーシップの機会については、まで <a href="mailto:aipartners@microsoft.com">aipartners@microsoft.com</a> お問い合わせください。</p>
