### YamlMime:Yaml
ms.openlocfilehash: eb5cf44a5ca7c2ed91f9b8de73bd53c8fcdf3d0b
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904320"
Slug: application-insights-announces-availability-of-release-annotations
Title: アプリケーション インサイトリリース注釈の提供を発表
Summary: リリース注釈 (以前は "配置マーカー" と呼ばれる) が Application インサイト で公開されました。
Content: >-
  <p><em>Baaaaaccccckckkk</em>&rsquo;!</p>


  <p>リリース注釈 (&ldquo;&rdquo;以前は配置マーカーと呼ばれる) が Application インサイト に公開されたのを知らせたくなれインサイト。 これは、Application インサイト が Visual Studio Online (現在は <em>Visual Studio Team Services) から</em>新しい Azure portal に移動して以来、最も要求される機能の 1 つでした。</p>


  <p>リリース注釈は メトリックス エクスプローラー に表示され、リリースが行った時間をブレードで使用できる多くのメトリックに関連付けできます。 これは、悪い (または良い) デプロイがサービスまたはアプリに悪影響を与えるかどうかを理解するのに役立ちます。</p>


  <h2>リリース注釈の有効化</h2>


  <p>リリース注釈をアプリに表示&rsquo;するにはメトリックス エクスプローラー VSTS のビルドに追加する必要があります。&nbsp;それらを使用するには、Marketplace の拡張機能をVisual Studio<a href="https://marketplace.visualstudio.com/items/ms-appinsights.appinsightsreleaseannotations">できます</a>。</p>


  <p><img alt="image" border="0" height="468" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8772554f-8eab-47d7-921a-771e1888d91c.png" style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-image: none" title="image" width="610"></p>


  <p>リリース注釈拡張機能のページにドリルダウンしたら、[インストール] ボタンをクリックします。</p>


  <p><img alt="image" border="0" height="186" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/88635e7e-4c44-4faa-af9e-1d683a7281c6.png" style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-image: none" title="image" width="480"></p>


  <p>その&rsquo;後、拡張機能を VSTS サブスクリプションに関連付ける承認ウィンドウが表示されます。</p>


  <p><img alt="image" border="0" height="360" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/84306e3f-ac5f-476d-b5de-65e69069ac88.png" style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-image: none" title="image" width="336"></p>


  <p>確認した後は、&rsquo;VSTS リリースへのリリース注釈の追加を開始する準備が整います。</p>


  <h2>VSTS リリースへのリリース注釈の追加</h2>


  <p>リリース注釈が有効になっているので、VSTS で選択したサブスクリプションに関連付けられている任意のリリースに追加できます。&nbsp; 既存のリリースを編集し、[タスクの追加] をクリックし、使用可能なタスクの一覧から [リリース注釈] を選択します ([デプロイ] セクションに表示されます)。</p>


  <p><img alt="Add Task" border="0" height="286" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ReleaseAnnotationTask.png" style="background-image: none; padding-top: 0px; padding-left: 0px; padding-right: 0px; border-image: none" width="610"></p>


  <p>ステップを追加したら&rsquo;、Application インサイト から API キーを生成して追加し、ステップの属性の入力を完了する必要があります。 このプロセスの詳細な手順については、ドキュメント ページを <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-annotations/">参照してください</a>。 これが完了すると、次回リリースが実行されると、リリース注釈が生成されます。</p>


  <p>Ive が既&rsquo;にかなり得 &ldquo;た質問の 1 つは、ステップ 順でこのタスクをどこに置くのかは重要ですか?&rdquo; 答えはノーです。 実際には、必要に合ってこのタスクを 2 回追加&rsquo;できます。 現在、通常の状況では&rsquo;、それを行う意味はあまりないでしょう。 &rsquo;&ldquo;&rdquo;ただし、実行にかなりの時間がかかる非常に複雑なリリースがある場合は、リリースの各フェーズをマークする必要がある可能性があります。その場合、複数のリリース注釈タスクが発生する可能性があります。 関連する注釈を関連付け、長い期間を持つ可能性があるイベントを表す方法について、将来の設計上の可能性について既に説明しています。&nbsp; これは、VSTS リリース機能の機能が拡張されるにつれて、より重要になります。</p>


  <h2>注釈の表示</h2>


  <p>これで&rsquo;、リリース注釈を表示する準備ができました。 これらは、すべてのブレードでメトリックス エクスプローラーされます。 [リリース] ブレードメトリックス エクスプローラー、&rsquo;使用可能なグラフの上部に情報アイコンとしてリリース注釈が表示されます。 いずれかの上にマウス ポインターを&rsquo;合わせると、リリースに関する詳細情報の一部を提供する情報バルーンが表示されます。 この情報と注釈の相対的な位置を使用して、リリースを他の使用可能なメトリックと関連付け、リリースがリソースに影響を与える可能性があるかどうかを判断できます。</p>


  <h4><img alt="image" border="0" height="328" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/338b578e-cdcd-4624-8135-d2b89685f0d1.png" style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-image: none" title="image" width="610"></h4>


  <p>もう 1 つの重要な点は、リリースに関するより広範なデータを提供するリリース注釈の詳細ブレードで現在作業している点です。 この機能は、次の 2 つのスプリントで使用できます。</p>


  <h2>注釈の将来</h2>


  <p>現在の注釈機能は、その初期段階にあると理解することが非常に重要です。 注釈&rsquo;という単語が言及されるたびに、適切なケースに&rdquo;&ldquo;注意してください。 これは、リリース注釈は、Application インサイト で使用できる多くの種類の注釈の最初の機能にすすむためです。 現在&rsquo;、さまざまな運用イベントを内部的に注釈としてテストし、他の多くのユーザー向け概念設計のドラフトを作成しています。</p>


  <p>また、Wed&rsquo; は、手動注釈を作成したり、リソースまたはサブスクリプション全体で再利用できるカスタムの種類の注釈を定義したりできる機能をユーザーに提供するのも好みです。 Application インサイト のより多くの場所で注釈を使用できるようにし、サード パーティ製品からの注釈の直接挿入 (API 経由)、スイム レーンでの複数の種類の注釈の表示、期間 (または複数のフェーズ) を持つイベントの表現方法、同時に作成された複数の注釈のグループ化、ユーザーが生成/表示する注釈の種類を選択するサブスクリプション モデルを計画しています。 注釈&rsquo;を作業項目&rsquo;に関連付け、またはデータを直接表示する点で、気に入った処理に言及Visual Studio。</p>


  <p>チームはここに大きな計画を立&rsquo;てているが、機能の優先順位付けと進化に役立つフィードバックも求める。 最も重要なのは、Azure ブログで確認し続け、進行状況に関するより多くのお知らせを確認してください。 始めたばかりです。</p>


  <p>新機能や改善された機能については、Application インサイト User Voice ページでアイデアを共有してください。質問がある場合は、<a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights"><u>Application インサイト フォーラムをご覧ください</u></a>。</p>
