### YamlMime:Yaml
ms.openlocfilehash: 505ebc3078418cd4d81516962c42e9896b6473c0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890311"
Slug: article-tips-for-migrating-your-applications-to-the-cloud
Title: '記事: ヒントアプリケーションをクラウドに移行する方法に関する記事'
Summary: '[この記事は、チームによってSQL Azureされました。]Windows Azure で表現されている会社のお客様の多くが関心を持つため、Huey と Wade Wegner は一連の Windows を保持することを決定しました。'
Content: <p>[この記事は、チームによってSQL Azureされました。]</p><p>Windows Azure で表現されている会社のお客様の多くが関心を持つため、Huey と Wade Wegner は Microsoft テクノロジ センターで Windows Azure Migration Labs のセットを保持することを決定しました。 その目的は、お客様が自分のアプリケーションをラボに取り込み、実際にアプリケーションをラボに移行SQL Azure。 このプロセスを通じて、すべての顧客は、Web アプリケーションと SQL データベースを Windows Azure プラットフォームに正常に移行し、SQL Azure 移行ウィザードを使用しました。 今度は、この記事の MSDN マガジンから、この記事で行われた方法を、今度は、取り上 <a href="https://msdn.microsoft.com/en-us/magazine/ff872379.aspx">手と</a> Wade から説明します。</p>  <p>記事については、こちらを参照 <a href="https://msdn.microsoft.com/en-us/magazine/ff872379.aspx">してください</a>。</p>
