### YamlMime:Yaml
ms.openlocfilehash: d4b115b935ce99eccb3b11ef595a70907bce0c3b
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910110"
Slug: august-update-for-web-apps-and-app-service-environments-in-the-azure-preview-portal-2
Title: Azure プレビュー ポータルでのWeb Apps環境App Service 8 月の更新
Summary: Azure プレビュー ポータルでの Web アプリと App Service 環境の 8 月の更新には、設定とツールのメニューでのカテゴリ化、App Service プランの参照の改善、App Service 環境の新しい UI 機能が含まれます。
Content: >-
  <h1>Web Appsツールと設定メニューの機能強化</h1>


  <p><br>

  ユーザーからのフィードバックに基づいて、[<strong>ツール] メニュー</strong>と [ツール<strong>] メニュー設定</strong>が引き続き改善されています。 先月、探している <strong>ツールと</strong> 設定を見つけやすくするカテゴリ化を追加しました。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/58f7d176-07b7-42e6-86f9-2cf6dabbf1f3.png"><img alt="Web Apps_Tools_Categorization" border="0" height="577" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c93c2735-312d-4c62-928a-137ea3de665d.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Web Apps_Tools_Categorization" width="1024"></a></p>


  <p>&nbsp;</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d8e708aa-4cc7-4a30-a0df-29083f92e82d.png"><img alt="Web Apps_Settings_Categorization" border="0" height="577" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/20affd92-f020-4ecf-8017-3f2491e94c55.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Web Apps_Settings_Categorization" width="1024"></a></p>


  <p>&nbsp;</p>


  <p>カテゴリ化に加えて、次の項目も追加設定。</p>


  <h3>継続的デプロイ</h3>


  <p><br>

  以前は、この機能の唯一のエントリ ポイントは、リソース ブレード (1) のピン留めされた部分で、発行カテゴリ (2) の<strong>下の 設定</strong> メニューに表示<strong></strong>されるのと同じ機能でした。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/94509aee-3ad1-4852-8e3b-80c57b6e6db6.png"><img alt="Web Apps_Continuous Deployments" border="0" height="577" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e3a1a49e-7aab-4192-804d-bec02cf08449.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Web Apps_Continuous Deployments" width="1024"></a></p>


  <p>&nbsp;</p>


  <h3>モバイル 設定</h3>


  <p><br>

  既存の任意のデバイスにプッシュ通知やオフライン同期などのモバイル機能を追加Web Apps。 <a href="https://azure.microsoft.com/blog/2015/08/20/azure-mobile-apps-august-2015-update/">2015</a> 年 8 月の更新プログラムに関するブログ記事「Azure Mobile Apps」で、<a href="https://azure.microsoft.com/blog/author/matthew-henderson/">大</a>きな詳細を説明しています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/53027425-f949-41d9-939f-4916afcc75fc.png"><img alt="Web Apps_Mobile Setting" border="0" height="577" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/aa90d803-b693-4896-afef-674ebcceccab.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Web Apps_Mobile の設定" width="1024"></a></p>


  <p>&nbsp;</p>


  <h3>[ツール] メニューで Kudu にアクセスできる</h3>


  <p><br>

  Project Kudu は、すべてのアプリと共にApp Serviceアプリです。 <strong>Kudu では</strong>、Web ジョブ、継続的インテグレーション、<strong>サイト</strong>拡張機能など、機能の<strong>バックエンド</strong><strong>機能が提供されます</strong>。 また、開発/デバッグ&ldquo;&rdquo;時に重要な環境情報と機能拡張ポイントのコレクションも備え、それを知る人には隠れた価値があります。</p>


  <p>このリリースでは、 <strong>Kudu</strong> の検出が非常に簡単になります。 [ツール] メニューの [ <strong>開発]</strong> セクションで <strong>確認</strong> できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4ee82885-3a79-4aac-a847-2491cdd14e94.png"><img alt="Web Apps_Develop_Kudo" border="0" height="577" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/119ceb60-dfb5-43e8-bdac-2b0a6478d257.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Web Apps_Develop_Kudo" width="1024"></a></p>


  <p>&nbsp;</p>


  <h3>新しいネットワーク構成エクスペリエンス</h3>


  <p><br>

  新しい <strong>[ネットワーク</strong> ] タイルでは、アプリの高度なネットワーク接続を設定し、接続が確立されると関連する接続情報を表示する、より簡単で統合されたエクスペリエンスが提供されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6e33e667-2782-40f2-b52d-7da830987757.png"><img alt="Web Apps_Networking Experience" border="0" height="577" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/00d2d529-0747-4e8b-9a10-52512cefc69a.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Web Apps_Networking Experience" width="1024"></a></p>


  <p>&nbsp;</p>


  <h3>プランApp Service参照する</h3>


  <p><br>

  <strong>App Serviceプランの参照</strong>エクスペリエンスに、各 App Service プラン<strong></strong>にデプロイされたアプリの<strong>数が含まれる。</strong></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f44c8726-7cad-4357-959f-34ff96c1cb91.png"><img alt="Web Apps_Browse App Service plans" border="0" height="577" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b2ee140d-7ea3-4736-b77a-5b60e37753b5.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Web Apps_参照App Serviceプラン" width="1024"></a></p>


  <p>&nbsp;</p>


  <h3>環境の削除エクスペリエンスApp Service強化</h3>


  <p><br>

  <strong>App Service環境</strong> では、削除エクスペリエンスが向上しています。 これで、データ <strong>を削除</strong><strong>App Service Environment</strong>、含まれているすべてのリソース<strong>が連鎖</strong>的に削除されます。 新しいエクスペリエンスには、この操作の結果として影響を受けるすべてのリソースの一覧が含まれています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/749c60d3-bcde-4faa-bdba-dd50efde08e2.png"><img alt="Web Apps_Delete" border="0" height="577" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bd8a642a-a00a-43e0-ae03-28e9ea742d7b.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Web Apps_Delete" width="1024"></a></p>


  <p>&nbsp;</p>


  <h3>ファイル システムStorageの情報App Service Environment</h3>


  <p><br>

  このリリースでは、[ファイル システム] リソース ブレード<strong>Storage</strong>情報を<strong>App Service Environment</strong>しました。 この新しい UI を使用すると、アプリにデプロイされているすべてのアプリで使用されるファイル システムの合計を監視 <strong>App Service Environment</strong>。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/19ac71f2-6bbb-4a1b-aefc-81bb7b64cf8d.png"><img alt="Web Apps_System Storage Info" border="0" height="577" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/86e1bacb-4242-466f-9638-964504b91614.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Web Apps_System Storage Info" width="1024"></a></p>
