### YamlMime:Yaml
ms.openlocfilehash: f378c77fabdfeb08522085b0b2012ee44cf65d87
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893240"
Slug: automate-application-lifecycle-management-with-github-actions
Title: GitHub Actions を使用してアプリケーション ライフサイクル管理を自動化する
Summary: '2021 年には、毎月、Azure 上のローコード アプリケーション開発 (LCAD) ソリューションの月のウェビナーに関する月次ブログをリリースします。 '
Content: >-
  <p>2021 年には、毎月、Azure 上のローコード アプリケーション開発 (LCAD) ソリューションの月のウェビナーに関する月次ブログをリリースします。 LCAD on Azure は、ローコードの Microsoft Power Apps と使い慣れた Azure 製品を統合する堅牢な開発機能を示す新しいソリューションです。&nbsp;</p>


  <p>今月のウェ&rsquo;ビナーでは、&lsquo;<a href="https://info.microsoft.com/ww-ondemand-develop-test-and-deliver-applications-with-github-actions-for-power-platform.html?lcid=en-us" target="_blank">アプリケーション ライフサイクル管理 (ALM)</a> プロセスを開発し、GitHubとPower Apps。&rsquo;&nbsp;このブログでは、Azure 上の LCAD とは何か、ウェビナーと使用事例で最も一般的な 3 つの製品について説明し、ウェビナー&#39;のコンテンツの詳細を学習するためのサポート ドキュメントを提供します。&nbsp;</p>


  <h2>Azure でのローコード アプリケーション開発 (LCAD) とは</h2>


  <p>Azure 上のローコード アプリケーション開発 (LCAD) は、開発者が少ないコードでビジネス アプリケーションをより迅速に構築し、Power Platform&mdash; を活用し、より具体的には Power Apps Azure サービスを使用して Power Apps をスケーリングおよび拡張するのに役立つ) を支援するために作成されました。&nbsp;</p>


  <p>たとえば、製造会社に働くプロ開発者は、倉庫の従業員が受信在庫を追跡するのに役立つ、業務ラインオブビジネス (LOB)&nbsp; アプリケーションを構築する必要があります。 このアプリケーションのビルド、テスト、デプロイには数か月&nbsp;かかりますが、Power Apps では、ビルドに数時間かかる可能性があります。時間とリソースが&nbsp;節約されます。</p>


  <p>ただし、現在の在庫&nbsp;が決して低い値にヒットした場合に、追加の在庫の調達注文をアプリケーションに自動的に配置する必要がある場合は、倉庫の従業員が必要とします。 以前は、開発チームが以前のアプリケーションのイテレーションをリワークするために、別の大きなリフトが必要でした。 Power Apps と Azure の統合により、プロの開発者は Visual Studio (VS) Code で API をビルドし、それを Azure portal に発行し、API を Power Apps にエクスポートして、カスタム コネクタとしてアプリケーションに統合することができます。 その後、その同じ API を Power Apps&rsquo; Studio&mdash; で無期限に再利用可能にし、将来他のアプリケーションで使用し、会社や開発者の時間とリソースを多く保存します。&nbsp;</p>


  <p>これは、Azure 上の LCAD ソリューションの機能を強調するシナリオの 1 つにす。 ソリューション自体の詳細については、&nbsp;Azure 上の <a href="https://azure.microsoft.com/en-us/solutions/low-code-application-development/" target="_blank">LCAD のサポート ドキュメントを参照してください</a>。 今月の&rsquo;ウェビナーでは、上記のシナリオのようなアプリケーション ライフサイクル管理を自動化する機能に焦点を当て、GitHub Actions を使用して開発者向けの開発プロセスをさらに迅速化し、合理化します。&nbsp;</p>


  <h2>ウェビナー コンテンツ</h2>


  <p>&lsquo;このウェビナーでは、Fusion 開発&rsquo;&nbsp;を、市民開発者自身を利用してローコード アプリケーションを構築し、開発チームへの負担をさらに軽減するプロセスとして説明します。また、プロの開発者は、これらのアプリケーションをカスタム コードで拡張することで、市民開発者&#39;に半分の方法で会います。&nbsp;</p>


  <p>ウェビナーには、次の 2 つのデモが含まれています。&nbsp;API&nbsp; Management と Power Apps の統合と、GitHub Actions を使用して継続的インテグレーション、&nbsp;&nbsp;継続的デリバリー (CI/CD) パイプラインを作成する方法に関する 1 つ。&nbsp;</p>


  <p>API Management と Power Apps の統合では、Power Apps と Azure の機能拡張機能を一緒に使用する方法、API を Power Apps にエクスポートする方法、Microsoft Teams 経由で API Management を Power Apps に接続する方法について、ライセンス コストを追加する必要はありません。</p>


  <p>簡単に検出して使用するために Azure API Management でサポートされる API を Power Platform に迅速に発行する Azure API Management コネクタを導入し、Azure サービスに接続するアプリの作成にかかる時間を大幅に短縮しました。</p>


  <p>つまり、企業は、azure でホストされている既存の資産から真のメリットを得て、Azure portal を数回クリックして市民開発者が利用できるようすることで、Power Apps または Power Automate Maker エクスペリエンスでカスタム コネクタを作成するための追加の手順を排除できます。</p>


  <p>GitHub <a href="https://help.github.com/articles/about-github-actions" target="_blank">Actions のデモ</a>では、自動化されたソフトウェア開発&#39;ワークフローを構築する開発者向けの機能について説明します。 Microsoft Power Platform&nbsp; 用 GitHub Actions を使用すると、開発者はリポジトリにワークフローを作成して、アプリのビルド、テスト、パッケージ化、リリース、デプロイ、自動化の実行、Microsoft Power Platform 上に構築されたボットとその他のコンポーネントの管理を行うことができます。</p>


  <p>ウェビナーは現在<a href="https://info.microsoft.com/ww-ondemand-develop-test-and-deliver-applications-with-github-actions-for-power-platform.html?lcid=en-us" target="_blank">オンデマンド</a>で利用できます。また、2 月のウェビナーでは、SAP on AzureとPower Apps。</p>


  <h2>サポート ドキュメント</h2>


  <p>Power Apps Azure Web サイト:</p>


  <ul>
      <li><a href="https://azure.microsoft.com/en-us/solutions/low-code-application-development/" target="_blank">Azure Web サイトの LCAD</a>。</li>
      <li><a href="https://powerapps.microsoft.com/en-us/power-apps-and-azure/" target="_blank">Azure plus Power Apps pro developers および Microsoft</a> Power Apps。</li>
  </ul>


  <p>Power Platformと Azure API Management 統合:</p>


  <ul>
      <li><a href="https://powerapps.microsoft.com/en-us/blog/azure-api-management-connector-on-the-power-platform/" target="_blank">Azure API Managementコネクタについては、Power Platformブログ記事をご覧ください</a>。</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/api-management/export-api-power-platform" target="_blank">Azure から Export API API Management手順Power Platform手順に従って説明します</a>。</li>
  </ul>


  <p>Power PlatformアクションGitHub自動化されたソフトウェア開発ライフサイクル (SDLC) ワークフロー:</p>


  <ul>
      <li><a href="https://powerapps.microsoft.com/en-us/blog/github-actions-for-the-power-platform-now-available-in-preview/" target="_blank">GitHubに関するPower Platformは、プレビューのブログ投稿で利用できます</a>。</li>
      <li><a href="https://docs.microsoft.com/en-us/power-platform/alm/devops-github-actions" target="_blank">GitHubアクションの概要Power Platformします</a>。</li>
      <li><a href="https://docs.microsoft.com/en-us/power-platform/alm/devops-github-available-actions" target="_blank">機能に関するドキュメント</a>。</li>
      <li><a href="https://www.youtube.com/watch?v=Bk4KpE_6YtY&amp;feature=youtu.be" target="_blank">ソース管理と自動デプロイのデモ</a>。</li>
      <li><a href="https://github.com/microsoft/powerplatform-actions-lab" target="_blank">ソース管理と自動デプロイのデモのハンズオン ラボ</a>。</li>
      <li><a href="https://github.com/microsoft/powerplatform-actions" target="_blank">Power Platformと GitHub アクション リポジトリ</a>。</li>
  </ul>
