### YamlMime:Yaml
ms.openlocfilehash: 2d5405c4f281e3e044dee2f06e5c03373f2d2bed
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912942"
Slug: automation-and-configuration-of-your-azure-on-premises-and-hybrid-cloud-resources-at-scale
Title: 大規模な Azure、オンプレミス、ハイブリッド クラウド リソースの自動化と構成
Summary: 現在、お客様はハイブリッド クラウド全体でインフラストラクチャとアプリケーションを自動化して構成する必要があります。 適切に管理された環境を大規模に維持するには、お使Windowsと Linux システムの両方に次の機能が必要です。
Content: >-
  <p>現在、お客様はハイブリッド クラウド全体でインフラストラクチャとアプリケーションを自動化して構成する必要があります。 適切に管理された環境を大規模に維持するには、次の機能が、Windowsと Linux システムの両方に必要です。</p>


  <ul>
   <li>インフラストラクチャとアプリケーションの構成を適用して監視します。</li>
   <li>計画外のダウンタイムなしで、オペレーティング システムの更新プログラムを適用する時間と方法を制御します。</li>
   <li>アラートを解決し、バックアップとディザスター リカバリーを調整し、セキュリティの問題を自動的に修復します。</li>
   <li>インベントリを収集し、レポート、診断、および法開始のための変更を追跡します。</li>
   <li>Azure とオンプレミスの両方のデータセンターのシステム間でプロセスを自動化します。</li>
   <li>セキュリティで保護された一元化されたリポジトリからすべての自動化資産と構成資産を管理します。</li>
  </ul>


  <p>これらの要件に対処するために、新しい自動化と構成機能がリリースされたのは、Azure portal。</p>


  <h2>Azure 仮想マシンの統合</h2>


  <p>仮想マシンとの統合により、VM ブレードから直接、Windowsおよび Linux コンピューターの更新管理、インベントリ、および変更の追跡が可能になります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/556eb62e-2c57-41de-bc65-63697fee7b09.png"><img alt="UpdateManagementVMBlade" border="0" height="467" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f19f0e07-a524-4d44-97b3-d04d276fcb25.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="UpdateManagementVMBlade" width="983"></a></p>


  <p>更新管理を使用すると、Windows と Linux のコンプライアンス状態を常に確認できます。また、定義済みのメンテナンス範囲内で更新プログラムのインストールを調整するスケジュールされたデプロイを作成できます。 特定の更新プログラムを除外する機能も利用できます。詳細なトラブルシューティング ログを使用して、デプロイ中の問題を特定できます。</p>


  <p>VM のゲスト内リソースのインベントリを使用すると、インストールされているアプリケーションと、追跡する他の構成項目を表示できます。豊富なレポートと検索を使用すると、VM 内で構成されているすべてのものを理解するのに役立つ詳細情報をすばやく見つけるのに役立ちます。</p>


  <p>変更の追跡では、サービス、デーモン、ソフトウェア、レジストリ、およびファイル間の変更を自動的に収集して、問題の原因をすばやく特定し、望ましくない変更が発生した場合の診断とアラートを有効にします。</p>


  <h2>Azure 環境とハイブリッド環境全体での大規模な管理</h2>


  <p>Azure とオンプレミスのリソースを大規模に管理するために、これらの機能は Azure の Automation &amp; 構成サービスにも追加されています。 環境全体で統一されたビューを取得し、Azure portal から正しく構成、更新、管理されるようにアクションを実行できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0ef71e94-8dd8-4595-ac55-3c4be976e09a.png"><img alt="ChangeTrackingAutomationAccount" border="0" height="588" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/78b4134b-6813-4b9d-a66f-560c1625eeec.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="ChangeTrackingAutomationAccount" width="960"></a></p>


  <p>Azure portal &amp; のオートメーション構成には、PowerShell の望ましい状態構成サービスを使用した構成管理があります。 また、Azure VM とハイブリッド データセンターで実行されているコンピューターの両方で、更新管理を実行し、インベントリを収集し、変更を追跡する機能も含まれています。</p>


  <p>また、Linux コンピューターのハイブリッド worker サポートを追加することで、Linux タスクを自動化する機能が追加されました。 つまり、現在のデータ センターと同様に、ローカル データセンターと Azure Linux VM のタスクを一貫した方法で調整Windowsできます。</p>


  <p>また、Python を使用して Runbook を作成し、Automation サービスまたは Linux または Windows ハイブリッド worker からこれらの Python Runbook を実行する機能も発表します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/54b7e7fe-06a0-4829-8cdb-0cbc2b05550d.png"><img alt="Python" border="0" height="543" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9e6fb35b-9deb-494d-9fce-5852d56bbd03.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="Python" width="974"></a></p>


  <p>これにより、最も使いやすいオートメーション言語を使用し、PowerShell とサービス内のグラフィカル Runbook の既存のサポートに追加できます。</p>


  <h2>Automation 構成機能 &amp; の価格</h2>


  <p>私たちの目標は、Azure リソースとハイブリッド環境の統合管理を有効に設定します。 Azure にこれらの新機能が追加されたので、これらの機能を使用するコストが変更され、必要な分だけ支払う必要があります。</p>


  <p>Azure コンピューターと Azure 以外のコンピューターの両方の更新管理機能については、Azure Log Analytics に格納されているログに対してだけ料金を支払います。 プロセスの自動化には、毎月 500 分の無料が含まれます。その後、Runbook ジョブの分ごとに料金が発生します。 構成管理には、毎月 5 つのハイブリッド ノードが無料で、Azure 以外のコンピューターごとに 1 時間あたりの料金が含まれます。 Azure Log Analytics に格納されているログに対して支払います。 これらの機能のコストの詳細については、Automation の価格に関する <a href="https://azure.microsoft.com/en-us/pricing/details/automation/" target="_blank">ページを参照してください</a>。</p>


  <p>Automation &amp; 構成から新機能を使用するには、大規模なタスクを実行するときに仮想マシン ブレードまたは Automation アカウントを使用します。</p>


  <p>構成に関するドキュメント ページの既存の機能<a href="https://docs.microsoft.com/en-us/azure/automation/" target="_blank">と&amp;</a>新機能についてAzure Automation Twitter でのAzure Automation<a href="https://twitter.com/AzureAutomation" target="_blank">に従ってください</a>。</p>
