### YamlMime:Yaml
ms.openlocfilehash: 8e61f2523687e1c964125179d3bd77bd0936f1bf
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893242"
Slug: automate-always-on-availability-group-deployments-with-sql-virtual-machine-resource-provider
Title: 仮想Always On プロバイダーを使用して可用性グループSQLデプロイを自動化する
Summary: Azure Virtual Machines (VM) 上の SQL Server 用の高可用性ソリューションを構成するための新しい自動化された方法が、SQL VM リソース プロバイダーを使用して利用できるのを共有して楽しみに思います。
Content: >-
  <p><strong>Azure Virtual Machines (</strong><a href="https://azure.microsoft.com/en-us/blog/sql-server-on-azure-virtual-machine-resource-provider/" target="_blank"><strong>VM</strong></a><strong></strong>) 上の SQL Server 用の高可用性ソリューションを構成するための新しい自動化された方法が、SQL VM リソース プロバイダーを使用して利用できるのを共有して楽しみに思います。</p>


  <p><strong>今すぐ始めるには、次の表の手順に従ってください。</strong></p>


  <p>高可用性アーキテクチャは、データベース、ハードウェア、またはネットワークの障害が発生しても引き続き機能するように設計されています。 すべてのオペレーティング システム ディスクとデータ ディスクプレミアム Storageを使用する Azure Virtual Machine インスタンスでは、99.9% の可用性が提供されます。 この SLA は、計画外の &ndash; ハードウェア メンテナンス、予期しないダウンタイム、および計画メンテナンスの 3 つのシナリオの影響を受えます。</p>


  <p>アプリケーションに冗長性を提供するには、計画済みまたは計画外のメンテナンス イベント中に少<a href="https://docs.microsoft.com/en-us/azure/virtual-machines/windows/tutorial-availability-sets" target="_blank"></a>なくとも 1 つの仮想マシンを使用できる可用性セットに 2 つ以上の仮想マシンをグループ化することをお勧めします。 または、データ センターの障害から保護するために、同じ Azure リージョン内の 2 つ以上の Availability Zones に 2 つ以上の VM インスタンスをデプロイできます。これにより、少なくとも 99.99% の時間で少なくとも 1 つのインスタンスへの仮想マシン接続が保証されます。 詳細については、「SLA for &ldquo; Virtual Machines」<a href="https://azure.microsoft.com/support/legal/sla/virtual-machines/" target="_blank">を参照してください</a>。&rdquo;</p>


  <p>これらのメカニズムにより、仮想マシン インスタンスの高可用性が確保されます。 Azure VM で同じ SLA をSQL Server<a href="https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-sql-server-iaas-overview" target="_blank">するには、Azure VM</a> 上の仮想マシンに対して高可用性<a href="https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-sql-high-availability-dr" target="_blank">SQL Server構成する必要があります</a>。 現在、手動構成の簡単で信頼性の高い代替手段として、SQL VM リソース プロバイダー (RP) を使用して Azure VM 上の SQL Server 用<a href="https://azure.microsoft.com/en-us/blog/sql-server-on-azure-virtual-machine-resource-provider/" target="_blank">に Always On 可用性グループ</a> (AG) を構成する新しい自動化された方法を導入しています<a href="https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-portal-sql-availability-group-tutorial" target="_blank"></a>。</p>


  <p><a href="https://azure.microsoft.com/en-us/blog/sql-server-on-azure-virtual-machine-resource-provider/" target="_blank">SQL VM</a> リソース プロバイダーは、Always On Azure リソースのプロビジョニングを調整し、それらを接続して一緒に動作することで、AG のセットアップを自動化します。 VM RP SQLを使用すると、Always On 3 つの手順で AG を構成できます。</p>


  <table border="1" cellpadding="2">
      <tbody>
          <tr>
              <td valign="top"><strong>手順</strong></td>
              <td valign="top"><strong>SQL VM RP リソースの種類</strong></td>
              <td valign="top"><strong>デプロイするメソッド</strong></td>
              <td valign="top"><strong>前提条件</strong></td>
          </tr>
          <tr>
              <td valign="top"><strong>手順 1 Windows &ndash; フェールオーバー クラスター</strong></td>
              <td valign="top">SqlVirtualMachineGroup</td>
              <td valign="top"><a href="https://github.com/Azure/azure-quickstart-templates/tree/master/101-sql-vm-ag-setup" target="_blank">&ndash;自動 ARM テンプレート</a></td>
              <td valign="top">VM は、SQL Server 2016 または 2017 Marketplace イメージから作成し、同じサブネット内に存在する必要があります。また、AD ドメインに参加する必要があります。</td>
          </tr>
          <tr>
              <td valign="top"><strong>手順 2 &ndash; 可用性グループ</strong></td>
              <td valign="top">該当なし</td>
              <td valign="top">手動</td>
              <td valign="top">手順 1</td>
          </tr>
          <tr>
              <td valign="top"><strong>手順 3 可用性 &ndash; グループ リスナー</strong></td>
              <td valign="top">SqlVirtualMachineGroup/AvailabilityGroupListener</td>
              <td>
              <p>3.1 内部リソースの&ndash;手動Azure Load Balancerする</p>

              <p>3.2 自動 ARM テンプレート AG &ndash; <a href="https://github.com/Azure/azure-quickstart-templates/tree/master/101-sql-vm-aglistener-setup" target="_blank">リスナーの作成と構成</a></p>
              </td>
              <td>
              <p>3.1 手動 &ndash; なし</p>

              <p>3.2 自動化された &ndash; 手順 2</p>
              </td>
          </tr>
      </tbody>
  </table>


  <h2>前提条件</h2>


  <p>最初に、VM イメージSQL AG レプリカをホストする ALWAYS ON VM インスタンスAzure Marketplace SQL Serverデプロイする必要があります。 現在、SQL VM リソース プロバイダーは、Always On 2016 および SQL Server 2017 Enterprise エディションの自動 SQL Server AG をEnterpriseしています。</p>


  <p>各 SQL VM インスタンスは、Azure VM でホストされている Active Directory ドメインに参加するか、ネットワーク ペアリングを介してオンプレミスから Azure に拡張する必要があります。 VM インスタンスは、Active Directory ドメインに手動で参加するか、Azure クイック スタート ドメイン参加テンプレート <a href="https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-domain-join" target="_blank">を実行して参加できます</a>。</p>


  <p>AG SQLホストする VM インスタンスAlways On、同じ VNet と同じサブネットに含む必要があります。</p>


  <p><strong>1.フェールオーバー クラスター Windows構成する</strong></p>


  <p>Microsoft.SqlVirtualMachine/SqlVirtualMachineGroup リソースは、バージョンとエディション、完全修飾ドメイン名、クラスターを管理する AD アカウント、クラウド監視としてのストレージ アカウントなど、Windows フェールオーバー クラスターに関するメタデータを定義します。 最初の VM SQL SqlVirtualMachineGroup に参加すると、Windows フェールオーバー クラスター サービスがブートストラップされ、VM がクラスターに参加します。 この手順は、Azure クイック スタートで <a href="https://github.com/Azure/azure-quickstart-templates/tree/master/101-sql-vm-ag-setup" target="_blank">101-sql-vm-ag-setup</a> として使用できる ARM テンプレートを使用して自動化できます。</p>


  <p><strong>2. ALWAYS ON AG を構成する</strong></p>


  <p>フェールオーバー Windowsはクラスター サービス手順で構成する場合、プライマリ Always On AG レプリカの SSMS 経由で Always On AG を作成できます。 この手順は手動で実行する必要があります。</p>


  <p><strong>3. AG リスナー Always On作成する</strong></p>


  <p>Always On AG リスナーには、1 つのAzure Load Balancer (LB) が必要です。 Load Balancer、より &ldquo;迅速な&rdquo; フェールオーバーと再接続を可能にする AG リスナーのフローティング IP アドレスを提供します。 可用性グループSQL一部の VM が同じ可用性セット内にある場合は、Basic Load Balancer。 それ以外の場合は、 を使用する必要Standard Load Balancer。 このLoad Balancer VM インスタンスと同じ VNet 内SQL必要があります。 SQL VM RP では、AG リスナーの内部Load Balancerがサポートされます。 AG リスナーをプロビジョニングする前に、ILB を手動で作成する必要があります。</p>


  <p>ILB 名、可用性グループ名、クラスター名、SQL VM リソース ID、および AG リスナーの IP アドレスと名前を指定して、Microsoft.SqlVirtualMachine/Sql 仮想マシン グループ/AvailabilityGroupListener リソースをプロビジョニングすると、AG リスナーが作成および構成されます。 SQL設定を処理し、ILB バック エンド プールと正常性プローブを構成し、最後に指定された IP アドレスと名前で AG リスナーを作成します。 この手順の結果、同じ VNet 内の VM は、AG リスナー名を使用Always On AG に接続できます。 この手順は、Azure クイック スタートで <a href="https://github.com/Azure/azure-quickstart-templates/tree/master/101-sql-vm-aglistener-setup" target="_blank">101-sql-vm-aglistener-setup</a> として使用できる ARM テンプレートを使用して自動化できます。</p>


  <p>VM RP Always On AG をSQLすると、インフラストラクチャとネットワークAlways On 可用性グループの詳細を処理することで、アプリケーションの構成が簡略化されます。 適切なリソース依存関係設定と内部再試行ポリシーを備え、信頼性の高いデプロイ方法を提供します。 Azure ALWAYS ON 可用性グループ でのAlways On 可用性グループの高可用性SQL向上させるために、VM RP を使用してSQL ServerデプロイしてみてくださいVirtual Machines。</p>


  <p>現在、リソース プロバイダーによって有効<a href="https://azure.microsoft.com/en-us/services/virtual-machines/sql-server/" target="_blank">SQL Server Azure Virtual Machine</a> 機能を利用して、これらの拡張された機能を利用しましょう。 質問がある場合、または提案を行う場合は、 <a href="https://aka.ms/sqlfeedback" target="_blank">UserVoice からお問い合わせください</a>。 皆様のご意見をお待ちしております。</p>
