### YamlMime:Yaml
ms.openlocfilehash: 6cb6dbcc67a8e5dac553eed9270767f27509ea13
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139894585"
Slug: automating-vm-configuration-using-powershell-dsc-extension
Title: PowerShell DSC 拡張機能を使用した VM 構成の自動化
Summary: PowerShell DSC 拡張機能と関連する Azure PowerShell DSC コマンドレットは、Azure SDK で使用できます。 これで、vm エージェントと PowerShell DSC 拡張機能を有効にすることで、Azure PowerShell DSC コマンドレットを使用して PowerShell DSC 構成をアップロードし、Azure VM に適用することができます。
Content: >-
  4 月の <a href="https://www.buildwindows.com/">//build/</a> カンファレンスで、Jeffrey Snover は Azure VM をプロビジョニングし、<a href="https://blogs.msdn.com/b/powershell/archive/2014/04/03/configuring-an-azure-vm-using-powershell-dsc.aspx">PowerShell DSC (Desired State Configuration)</a> とカスタム スクリプト拡張機能を使用して構成する方法を示しました。 Azure VM エージェントと拡張機能は Microsoft Azure Infrastructure Services の一部であり、概要が必要な場合は、以前のブログ「VM エージェントと拡張機能パート <a href="https://azure.microsoft.com/blog/2014/04/11/vm-agent-and-extensions-part-1/">1</a>、パート <a href="https://azure.microsoft.com/blog/2014/04/15/vm-agent-and-extensions-part-2/">2</a>」を確認し、カスタム スクリプト拡張機能を使用して <a href="https://azure.microsoft.com/blog/2014/04/24/automating-vm-customization-tasks-using-custom-script-extension/">VM</a> カスタマイズ タスクを自動化することもできます。


  PowerShell DSC に慣れ親しくない方のために、PowerShell DSC は、コマンドレットと PowerShell の使用経験を活用して、Windows リソースの自律的でべき等で透過的なデプロイ、構成、コンプライアンスを実現する宣言型モデルです。 DSC の使用に関する詳細については、このブログ <a href="https://blogs.technet.com/b/privatecloud/archive/2014/04/25/desired-state-configuration-blog-series-part-1-learning-about-dsc.aspx">記事を参照してください</a>。 PowerShell MVP <a href="https://onedrive.live.com/?cid=7F868AA697B937FE&amp;id=7F868AA697B937FE%21110">によって作成された DSC</a> ブックも参照できます。


  現在、PowerShell DSC 拡張機能と、<a href="https://azure.microsoft.com/en-us/downloads/">Azure SDK</a> の一部である Azure PowerShell DSC コマンドレットについて発表します。 Azure PowerShell DSC コマンドレットを使用して、VM エージェントと PowerShell DSC 拡張機能を有効にすることで、PowerShell DSC 構成をアップロードして Azure VM に適用できます。 必要なバージョンがインストールされていない場合は、PowerShell DSC 拡張機能によって VM 上の PowerShell DSC が更新されます。PowerShell DSC を呼び出して、受信した DSC 構成を適用します。


  新しい拡張機能の詳細については、このトピックに <a href="https://blogs.msdn.com/b/powershell/archive/2014/08/07/introducing-the-azure-powershell-dsc-desired-state-configuration-extension.aspx">関する PowerShell ブログ</a> を参照してください。


  フィードバックをお寄せください <a href="https://twitter.com/Azure">@Azure</a> 。Twitter またはフィードバック フォーラムで、ご意見をお寄 <a href="https://feedback.azure.com/forums/34192--general-feedback">せください。</a>
