### YamlMime:Yaml
ms.openlocfilehash: 20ea0fd45c76d63eff73f4250fce6c9c1ffef0f8
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912935"
Slug: availability-monitoring-with-application-insights
Title: エンドポイント監視から Application Insights 可用性テストへの移行
Summary: 新しい Azure portal で Application Insights を使用した可用性の監視は、クラシックポータルのエンドポイントの監視に置き換わるものです。 新しいポータルで同等のテストを作成し、クラシックポータルに移動せずに管理できるようにしました。
Content: >-
  <p>Azure web apps に <a href="https://blogs.msdn.microsoft.com/mast/2013/03/03/windows-azure-portal-update-configure-web-endpoint-status-monitoring-preview/">エンドポイント監視</a> を使用していますか。 <b>2016 年4月 4</b>日に、 &rsquo; 新しいより強力な<a href="https://azure.microsoft.com/documentation/articles/app-insights-monitor-web-app-availability/">可用性テスト</a>に置き換えます。 新しいテストが既に作成されています。 ただし、2016年4月4日に切り替えるまでは無効になることにご注意ください。</p>


  <p>新しいテストはユーザーによる編集が可能で、必要に応じて切り替えることができます。 特に、サブスクリプションの所有者に設定したため &rsquo; 、通知の電子メールアドレスを確認する必要があります。 <i>CentralUS</i>リソースグループ内の<a href="https://portal.azure.com/">Azure portal</a>内のテストが見つかり&#39;ことになります。</p>


  <p>このスイッチの詳細については、Azure の &nbsp; <a href="https://azure.microsoft.com/documentation/articles/app-insights-migrate-azure-endpoint-tests/">ドキュメント</a>を参照してください。</p>
