### YamlMime:Yaml
ms.openlocfilehash: 8c593681f978e95a0c8b00ace34c82375646f85b
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889916"
Slug: azure-time-series-insights-api-reference-data-ingress-and-azure-portal-updates
Title: Azure Time Series インサイト API、参照データ、イングレス、Azure Portal の更新
Summary: 本日は、お客様からのフィードバックに基づいて Time Series インサイトいくつかの更新プログラムがリリースされる予定です。 Time Series インサイトは、何十億もの IoT イベントを同時に簡単に探索および分析できる、フル マネージドの分析、ストレージ、視覚化サービスです。
Content: >-
  <p>本日は、お客様からのフィードバックに基づいて Time Series インサイトいくつかの更新プログラムがリリースされる予定です。 Time Series インサイトは、何十億もの IoT イベントを同時に簡単に探索および分析できる、フル マネージドの分析、ストレージ、視覚化サービスです。 Azure への時系列データ ストリーミングを数分で視覚化して探索できます。コードを 1 行も記述する必要はありません。 製品、価格、および概要の詳細については、<a href="https://azure.microsoft.com/en-us/services/time-series-insights/" target="_blank">Time Series インサイトしてください</a>。 また、製品を自分 <a href="https://insights.timeseries.azure.com/demo" target="_blank">で体験できる</a> 無料のデモ環境も提供しています。&nbsp;</p>


  <h2>イングレス テレメトリを使用したよりスマートな環境管理</h2>


  <p>管理者は、Time Series 環境を計画し、管理し、インサイト環境で使用状況と正常性テレメトリを使用Azure portal。 これをより効果的に行うには、ポータルの Time Series インサイト 環境レベルでイングレスとストレージの監視を追加しました。 また、メトリック アラートの追加にも取り組み、環境の状態に関連する重要な情報を自動的に通知できます。 今後数か月後に &ndash; 更新プログラムのAzure portal環境テレメトリを追加し続ける予定です。</p>


  <p>ポータルの [概要] ページで、次の統計を確認できます。</p>


  <ul>
   <li>受信メッセージの受信: Event Hubs と Azure IoT Hubs から読み取られたメッセージの数。</li>
  </ul>


  <ul>
   <li>受信受信バイト数:&nbsp; イベント ソースから読み取られた未加工バイト数。 生の数には、通常、プロパティ名と値が含まれます。</li>
  </ul>


  <ul>
   <li>イングレス格納バイト数: 格納され、クエリに使用できるイベントの合計サイズ。</li>
  </ul>


  <ul>
   <li>イングレス格納イベント: クエリに格納され、使用できるフラット化されたイベントの数。</li>
  </ul>


  <p><br>

  <em>次に示すのは、次のページの環境テレメトリAzure portal</em></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c7bf6411-ec35-44c1-baa7-aa09a7eb2b63.jpg"><img alt="environment-telemetry-in-azure-portal" border="0" height="533" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d6df26a7-3fea-4691-b0d5-01f87f42498f.jpg" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="environment-telemetry-in-azure-portal" width="1024"></a></p>


  <h2>より優れた参照データ管理を使用してデータを視覚化および分析しやすくする</h2>


  <p>また&rsquo;、お客様から、デバイス メタデータを使用してデバイス テレメトリを拡張するより簡単な方法が必要ですが、長いドキュメントは必要ないというフィードバックも聞かされました。 現在、新しい Reference Data API ドキュメントに、プログラムで参照データを構成、アップロード、更新する方法を示す詳細なサンプルが含まれるのでお知らせします。 これらの顧客は、デバイス メタデータを参照データとしてインポートすることで、データにタグを付け、ディメンションを追加して、スライスとフィルター処理を容易にすることができます。 API を使用していないお客様の場合、参照データを視覚的に管理して上記と同じシナリオを実現するために、UX に組み込まれるソリューションを提供するために取り組み中です。&nbsp; 9 月にこの機能を含むポータルの更新プログラムを探します。</p>


  <p>ドキュメントのリビジョンへのリンクは次のとおりです。</p>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/time-series-insights/time-series-insights-add-reference-data-set" target="_blank">Azure Portal を使用して Time Series Insights 環境の参照データ セットを作成する</a></li>
  </ul>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/time-series-insights/time-series-insights-manage-reference-data-csharp" target="_blank">C# を使用して Azure Time Series Insights 環境の参照データを管理する</a></li>
  </ul>


  <h2>Time Series の機能をアプリインサイト追加する</h2>


  <p>お客様は、さまざまなシナリオに対応する Time Series インサイト上に内部アプリケーションと外部アプリケーションの両方を構築しています。 同様に、Microsoft は<a href="https://www.microsoft.com/en-us/internet-of-things/iot-central-saas-solutions" target="_blank"></a>&rsquo;、Microsoft インサイトやコネクテッド ファクトリ <a href="https://azure.microsoft.com/en-us/blog/azure-iot-suite-connected-factory-now-available/" target="_blank">PCS</a> IoT CentralなサービスAzure IoTを内部的に使用しています。 この領域の一般的な質問の 1 つは、クエリ API を使用して、&#39;now など、1 分を差し引いた相対期間を検索できる点です。&#39; では、最新のデータを確実に表示するために、すべてのクエリ実行で検索スパンをリセットする必要が生じずにいます。</p>


  <p>このサービスの更新により、1 つのクエリ テンプレートを使用して、最新のデータに対して反復可能なクエリを定義して実行できるよう、検索範囲の機能が向上しています。 動的検索スパンでは、現在の &ldquo;UTC 時刻を返す utcNow&rdquo; 関数を追加しました。 &ldquo;timeSpan&rdquo; &ldquo;&rdquo; リテラルも追加され、datetime 値から時刻を減算できるサブ関数に加えて、期間を定義できます。</p>


  <p>更新&rsquo;後の動的検索スパン JSON の例を次に示します。</p>


  <p><code>{<br>

  &nbsp;&nbsp; &quot;searchSpan&quot;: {<br>

  &nbsp;&nbsp;&nbsp;&nbsp; &quot;from&quot;: {<br>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &quot;sub&quot;: {<br>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &quot;left&quot;: { &quot;utcNow&quot;: {} },<br>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &quot;right&quot;: { &quot;timeSpan&quot;: &quot;PT1M&quot;}<br>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }},<br>

  &nbsp;&nbsp;&nbsp;&nbsp; &quot;to&quot;: { &quot;utcNow&quot;: {} }<br>

  }}</code></p>


  <p>詳細については、クエリ構文の <a href="https://docs.microsoft.com/en-us/rest/api/time-series-insights/time-series-insights-reference-query-syntax" target="_blank">ドキュメント ページを参照してください</a>。&nbsp;</p>


  <h2>より多くのデータイングレス形式をサポートする</h2>


  <p>最後に、Azure Stream Analytics&rsquo; の同僚から、顧客がマルチコンテンツ JSON としてデータを送信する際に柔軟性を高めしたいと考えています。 現在の更新プログラムには、マルチコンテンツ JSON ペイロードを受信する機能が含まれています。スループットを最適化しているお客様にとって便利な JSON データ形式です (バッチ処理シナリオでは一般的です)。 たとえば、次のペイロードには、整形式の JSON の連結された 5 つのセグメントが含まれています。</p>


  <p><code>{ &quot;id&quot;:&quot;device1&quot;,&quot;timestamp&quot;:&quot;2016-01-08T01:08:00Z&quot;}<br>

  {&quot;id&quot;:&quot;device2&quot;,&quot;timestamp&quot;:&quot;2016-01-08T01:09:00Z&quot;}<br>

  { &quot;id&quot;:&quot;device1&quot;,&quot;timestamp&quot;:&quot;2016-01-08T01:08:00Z&quot;}<br>

  [<br>

  &nbsp;&nbsp;&nbsp; {&quot;id&quot;:&quot;device2&quot;,&quot;timestamp&quot;:&quot;2016-01-08T01:09:00Z&quot;},<br>

  &nbsp;&nbsp;&nbsp; { &quot;id&quot;:&quot;device3&quot;,&quot;timestamp&quot;:&quot;2016-01-08T01:10:00Z&quot;}<br>

  ]<br>

  { &quot;id&quot;:&quot;device4&quot;,&quot;timestamp&quot;:&quot;2016-01-08T01:11:00Z&quot;}</code></p>


  <p>現在、お客様は、1 つの JSON オブジェクト、JSON 配列、入れ子になった JSON オブジェクト/配列、複数の JSON 配列、マルチコンテンツ JSON、またはその任意の組み合わせなど、任意の JSON 形式を送信できます。 サポートされている JSON オブジェクトの詳細については、ドキュメントを参照 <a href="https://docs.microsoft.com/en-us/azure/time-series-insights/time-series-insights-send-events#supported-json-shapes" target="_blank">してください</a>。</p>


  <p><br>

  これらの新&rsquo;しい更新プログラムに関して楽しみに思っていますが、今後の予定についてさらに楽しみに思っています。そのため、<a href="https://twitter.com/MSFTAzureTSI" target="_blank">Twitter</a> でフォローすることで、Time Series インサイト のすべての最新情報を最新の情報にしてください。 ビッグ データ グループの同僚&rsquo;は、大規模なデータ分析のための世界で最も強力なプラットフォームを構築する中で、興味深いことにも取り組しています。 ビッグ データ体験の詳細については、Web <a href="https://azure.microsoft.com/en-us/solutions/data-lake/" target="_blank">サイトを参照してください</a>。&nbsp;</p>
