### YamlMime:Yaml
ms.openlocfilehash: 46181649080e41f4125a022abf507f8e6e3bbb6e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139894875"
Slug: azure-data-lake-introduces-java-sdks-in-public-preview-for-big-data-processing-in-java-applications
Title: Azure Data Lake Java Sdk がパブリックプレビューに導入されました
Summary: 現時点では、Azure Data Lake Analytics 用の Java sdk とパブリックプレビューの Azure Data Lake Store について発表します。
Content: >-
  <p>現時点では、 <a href="https://azure.microsoft.com/en-us/services/data-lake-analytics/">Azure Data Lake Analytics</a>用の Java sdk とパブリックプレビューの<a href="https://azure.microsoft.com/en-us/services/data-lake-store/">Azure Data Lake Store</a>について発表します。 これにより、Java で記述されたアプリケーション内からビッグデータの処理と分析を統合することができます (C# と Node.js は既に統合されています)。</p>


  <h2>Java Sdk とは何ですか。</h2>


  <p>これらの Java Sdk を使用すると、新規または既存の Java アプリケーションを Azure Data Lake と統合して、ビッグデータを格納および処理することができます。</p>


  <ul>
      <li><a href="https://azure.microsoft.com/en-us/services/data-lake-analytics/">Azure Data Lake Analytics</a>は、ビッグデータの処理を容易にするために分散コードとインフラストラクチャを管理する複雑なタスクを実行するために、リソースを動的にプロビジョニングするビッグデータサービスです。 Java SDK を使用すると、ビッグデータ (U-SQL) ジョブの送信と監視、U-SQL メタデータカタログの参照、ユーザーアカウントの作成/管理を行うことができるコードを埋め込むことができます。また、Azure portal 内から既に実行できるすべての操作を行うことができます。</li>
      <li><a href="https://azure.microsoft.com/en-us/services/data-lake-store/">Azure Data Lake Store</a> は、データスケールとしてアプリケーションに変更を加えることなく、任意のサイズ、種類、速度のデータを簡単にキャプチャできる単一のリポジトリです。 Java SDK を使用すると、ファイルシステムに格納されている項目の読み取り、書き込み、管理、データへのアクセスの管理、アカウントの作成/管理、および Azure portal 内から既に実行できるすべての操作を行うことができます。</li>
  </ul>


  <h2>利用を始めるには?</h2>


  <p>作業を開始するには、「はじめに」のガイドにアクセスします。</p>


  <ul>
      <li><a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-java-sdk/">Data Lake Analytics</a> Java SDK のファーストステップガイド</li>
      <li><a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-get-started-java-sdk/">Data Lake Store</a> Java SDK のファーストステップガイド</li>
  </ul>


  <p>使用を開始するには、Azure Data Lake Analytics/storeの<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-portal/#create-data-lake-analytics-account">パブリックプレビュー</a>にサインアップした<a href="https://azure.microsoft.com/en-us/pricing/free-trial/">Azure サブスクリプション</a>が必要です。 これで、Azure Data Lake Analytics およびストア用の Java sdk の使用を開始する準備が整いました&#39;。</p>


  <p>初期状態では、Java Sdk は <a href="https://adxsnapshots.azurewebsites.net/?dir=com/microsoft/azure/azure-mgmt-datalake-analytics/1.0.0-SNAPSHOT">Azure スナップショットリポジトリ</a>で利用できますが、まもなく中央の Maven リポジトリで使用できるようになります。 この変更が発生すると、ドキュメントが反映されます。</p>


  <h2>ソースコードはどこにありますか。</h2>


  <p>Java sdk のソースコードは、GitHub (<a href="https://ttps://github.com/Azure/azure-sdk-for-java/tree/1.0.0-beta1/azure-mgmt-datalake-analytics">Data Lake Analytics</a>と<a href="https://github.com/Azure/azure-sdk-for-java/tree/1.0.0-beta1/azure-mgmt-datalake-store">Data Lake Store</a>) で利用できます。だれでも投稿できます。 詳細については、以下のリンクをご覧ください。</p>


  <ul>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/pricing/free-trial/">試用版サブスクリプションを取得する</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-portal/#create-data-lake-analytics-account">Azure Data Lake Analytics/ストアパブリックプレビューへのアクセスを要求する</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-java-sdk/">Java SDK を使用した Azure Data Lake Analytics の概要</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-get-started-java-sdk/">Java SDK を使用した Azure Data Lake Store の概要</a></li>
      <li>&nbsp;<a href="https://github.com/Azure/azure-sdk-for-java/tree/autorest/azure-mgmt-datalake-analytics">Java SDK ソースコードの Data Lake Analytics</a></li>
      <li>&nbsp;<a href="https://github.com/Azure/azure-sdk-for-java/tree/autorest/azure-mgmt-datalake-store">Java SDK ソースコードの Data Lake Store</a></li>
  </ul>


  <h4>Azure Data Lake Analytics について</h4>


  <ul>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-overview/">Azure Data Lake Analytics の概要</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-portal/">ポータルでの Azure Data Lake Analytics の概要</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-data-lake-tools-get-started/">Azure Data Lake Analytics とツールの概要</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-use-interactive-tutorials/">Azure Data Lake Analytics の対話型チュートリアル</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-analyze-weblogs/">Azure Data Lake Analytics を使用した web ログの分析</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-u-sql-get-started/">U-SQL の概要</a></li>
  </ul>


  <h4>Azure Data Lake Store</h4>


  <ul>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-overview">Azure Data Lake Store の概要</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-get-started-portal">ポータルからの Azure Data Lake Store の概要</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-secure-data">Azure Data Lake Store を使用したデータのセキュリティ保護</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-hdinsight-hadoop-use-portal">Azure Data Lake Store を使用した Azure HDInsight の接続</a></li>
  </ul>
