### YamlMime:Yaml
ms.openlocfilehash: ac3706d2be66b8946ff99aaa86838b6e8588c762
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139894515"
Slug: azure-monitor-aad-activity-logs-using-diagnostic-settings
Title: 'Azure Monitor: 診断設定AADアクティビティ ログをルーティングする'
Summary: 現在、Azure Active Directory (AAD) チームと協力して、診断設定を使用して AAD アクティビティ ログのパブリック プレビューをお知らせAzure Monitorしています。 Azure Monitor診断...
Content: >-
  <p>現在、Azure Active Directory (AAD) チームと協力して、診断設定を使用して AAD アクティビティ ログのパブリック プレビューをお知らせAzure Monitorしています。 Azure Monitor設定を使用すると、Azure サービスから Azure ストレージ アカウント、Event Hubs 名前空間、Log Analytics ワークスペースの 3 つの宛先にログ データをストリーミングできます。 これにより、任意の Azure サービスからデータ アーカイブ、 <a href="https://azure.microsoft.com/en-us/blog/use-azure-monitor-to-integrate-with-siem-tools/">SIEM</a> ツール、またはカスタム ログ処理ツールにログを簡単にルーティングできます。 今日のお&rsquo;知らせでは、AAD 監査ログとサインイン ログをこれらの同じ宛先にルーティングし、すべての Azure サービス ログを 1 つのパイプラインに一元化できます。</p>


  <p>これまでは、Azure サブスクリプション内にデプロイされた Azure Azure Monitorによって処理されるログ データはすべて取得されました。 多くの場合、この種類のデータ &ldquo;はリソース レベルのログ データとして記述&rdquo; され、リソース診断設定を使用して構成されます。 AADログ データは、テナント レベルのサービスから取得された最初の種類<strong></strong>のログ データで、Azure Monitor。 テナント レベルのサービスは&rsquo;、Azure サブスクリプション内のリソースとしてデプロイされるのではなく、テナント全体でAADされます。 この新しい種類の&ldquo;&rdquo;テナント レベルのログ データを処理するために、Azure Monitorの診断設定であるテナント診断設定が導入されました。 ログAAD、ポータルの AAD &ldquo;領域で [監査ログ] に移動し、[データのエクスポート] をクリックして、テナント診断設定を設定。&rdquo;</p>


  <p><img alt="image" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/00a242b3-2593-4248-b143-5f2993e82aa1.png" style="margin-right: auto; margin-left: auto; float: none; display: block;"></p>


  <p>これにより、診断設定を作成Azure Monitor、または削除できる、使い慣れた診断設定エクスペリエンスが引き出されます。</p>


  <p><img alt="image" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/300855ae-7574-4202-a834-9e2a10672db1.png" style="margin-right: auto; margin-left: auto; float: none; display: block;"></p>


  <p>image この機能の詳細と使用を開始するには、<a href="https://cloudblogs.microsoft.com/enterprisemobility/2018/07/26/azure-ad-activity-logs-in-azure-monitor-diagnostics-now-in-public-preview/">Enterprise Mobility and Security ブログの Alex Simonss&rsquo; の投稿を参照してください</a>。 また、パブリック プレビュー期間中は、AAD アクティビティ ログを Log Analytics にルーティングすることはできませんが、2018 年 10 月までにはこれを有効にしています。 ログを公開するサービスの完全な一覧については、Azure Monitor <a href="https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-diagnostic-logs-schema#service-specific-schemas-for-resource-diagnostic-logs">ドキュメントを参照してください</a>。</p>
