### YamlMime:Yaml
ms.openlocfilehash: 3e1ca439bd7f93221992a56d548cabdba9631e03
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909304"
Slug: azure-iot-supports-new-security-hardware-to-strengthen-iot-security
Title: Azure IoTは、IoT セキュリティを強化する新しいセキュリティ ハードウェアをサポートしています
Summary: >
  Microsoft IoT Microsoft の詳細については、IoT を簡素化し、アクセスしやすく、実装が容易な IoT ソリューションを通じて、すべてのビジネスがデジタル変革を行う方法について説明します。  Microsoft は、デバイスのオペレーティング システム、それらを制御するクラウド サービス、分析情報を取得する高度な分析、インテリジェントなアクションを可能にするビジネス アプリケーションなど、企業が開始する必要があるすべてのものなど、IoT の取り組み中の組織に対応する幅広い IoT オファリングを備えた、最も包括的な IoT ポートフォリオを提供しています。 Microsoft IoT がビジネスを変革する方法を確認するには、次のページを www.InternetofYourThings.com。
Content: >-
  <div>

  <p>&rsquo;IoT セキュリティのリーダーシップに対する Microsoft のコミットメントは、引き続き Azure IoT&rsquo;&nbsp; IoT&nbsp; デプロイのセキュリティ保護における信頼と信頼のレベルを証明します。Azure IoT&nbsp; では、デバイス ID コンポジション エンジン (DICE) とさまざまな種類のハードウェア セキュリティ モジュール (HSM&nbsp;) がサポートされています。DICE&nbsp; は、デバイスの識別と構成証明のための Trusted Computing Group (TCG)&nbsp; の今後の標準です。これにより、製造元はシリコン ゲートを使用してハードウェアに基づいてデバイス識別を作成し、新しいデバイスの DNA のセキュリティ ハードウェア部分を最初から作成できます。 HSM は、デバイス ID をセキュリティで保護し、ハードウェア ベースのデバイス構成証明やゼロ タッチ プロビジョニングなどの高度な機能を提供するために使用されるコア セキュリティ テクノロジです。</p>

  </div>


  <div>さらに、&nbsp;Azure IoTチームは、標準組織や主要な業界パートナーと協力して、最新のセキュリティのベスト プラクティスを採用して、さまざまなハードウェア セキュリティ モジュール (HSM) のサポートを展開しています。&nbsp;HSM は、IoT デバイスでの信頼性の高い回復力のあるハードウェア ルートを提供します。 Azure IoT プラットフォームは、HSM のサポートを Azure IoT Hub Device Provisioning や Azure IoT Hub デバイス管理 のようなプラットフォーム サービスと透過的に統合します。これにより、お客様と開発者は、アプリケーションに関連する特定のリスクの特定に集中し、セキュリティ展開の戦術を減らします。&nbsp;</div>


  <div>&nbsp;</div>


  <div>IoT デバイスのデプロイは、リモートで自律的であり、なりすまし、改ざん、移動などの脅威に対して開放することができます。 この場合、HSM は、認証、整合性、機密性、プライバシーなどへの信頼を高める主要な防御層を提供します。 Azure IoTは、主要な HSM 製造元と直接取り組み、さまざまな HSM に簡単にアクセスして、お客様や開発者のデプロイ固有のリスクに対応しています。&nbsp;</div>


  <div>&nbsp;</div>


  <div>このAzure IoTチームは、オープン標準を活用して、セキュリティで保護された堅牢なデプロイのベスト プラクティスを開発します。&nbsp;このような今後の標準の 1 つは、Trusted Computing Group (TCG) のデバイス ID コンポジション エンジン (DICE) です。このフレームワークは、認証、セキュア ブート、リモート構成証明などのさまざまなセキュリティ ソリューションを構築するために、アンカーの信頼に最小限の HSM&nbsp; フットプリントを必要とするスケーラブルなセキュリティ フレームワークを提供します。DICE は、IoT デバイスを継続的に特徴付ける制約コンピューティングの新しい現実への応答です。&nbsp;そのミニマリスト アプローチは、Trusted Computing Group s (TCG) や <a href="https://trustedcomputinggroup.org/">tpm&rsquo; </a>(TPM<a href="https://trustedcomputinggroup.org/work-groups/trusted-platform-module/">トラステッド プラットフォーム モジュール</a>)&nbsp; などの従来のセキュリティ フレームワーク標準への代替パスであり、Azure IoT プラットフォームでもサポートされています。&nbsp;&nbsp;この記事の執筆時点で、Azure IoT プラットフォームでは、STMicroelectronics や <a href="https://www.micron.com/">Ofsic</a> などのシリコン ベンダーの HSM での DICE の HSM サポートと、TPM 1.2&nbsp; のサポートが提供されています。<a href="https://developer.spyrus.com/azure-iot-hub/">Spyrus や Spyrus</a>&rsquo; など、ベンダー固有のプロトコルを使用した HSM Rosetta。</div>


  <div>&nbsp;</div>


  <div>最後に、リスク評価に関する大きなガイダンスは、ソリューション アーキテクトが HSM の選択を含む適切なセキュリティ上の決定を行うのに役立ちます。 コストが高すぎて採用しきれなきセキュリティ ソリューションをオーバーエンジニアリングする可能性はあり得ますが、コスト上の理由からソリューション セキュリティ エンジニアリングをショートカットする可能性もあります。&nbsp;そのため、最適なソリューションを実現するために、セキュリティとコストの間のこの相互関係を理解する必要があります。&nbsp;この最後に、Azure IoT チームは <a href="https://blogs.microsoft.com/microsoftsecure/2016/10/26/securing-the-internet-of-things-introducing-the-security-program-for-azure-iot/">Azure IoT </a>用のセキュリティ プログラムを提供し、顧客とソリューション アーキテクトが IoT インフラストラクチャのセキュリティにアクセスし、IoT デプロイに対する適切なセキュリティ アプローチを見つけるのに役立ちます。&nbsp;</div>


  <div>&nbsp;</div>


  <div>セキュリティ体験は、お客様と開発者が IoT デプロイをセキュリティで保護する上で最高の信頼と信頼を実現するために継続的に取り組む Azure IoT チームの取り組みです。&nbsp;これには、さまざまなハードウェア ベースのセキュリティとセキュリティ標準をサポートして、IoT デバイスの信頼のハードウェア ルートをセキュリティで保護する必要があります</div>


  <div>&nbsp;</div>


  <h2>Microsoft IoT の詳細を確認する</h2>


  <div><br>

  Microsoft は、アクセスしやすく、実装が容易な IoT ソリューションを通じて、すべてのビジネスがデジタル変革できるよう、IoT を簡素化しています。 Microsoft には、IoT &mdash; の取り組み中の組織に対応する幅広い IoT オファリングを備えた最も包括的な IoT ポートフォリオがあります。たとえば、企業がデバイスのオペレーティング システムから始める必要があるすべてのもの、それらを制御<a href="https://www.microsoft.com/en-us/cloud-platform/cortana-intelligence-suite"></a>するクラウド サービス、分析情報を得るために<a href="https://www.microsoft.com/en-us/dynamics365/field-service"></a>高度な分析、インテリジェントなアクションを実現するビジネス アプリケーションなどです。 <a href="https://www.microsoft.com/en-us/internet-of-things/"> </a> Microsoft IoT がビジネスを変革する方法を確認するには、次のページ <a href="https://www.InternetofYourThings.com">www.InternetofYourThings.com</a>。</div>


  <div>&nbsp;</div>


  <div>&nbsp;</div>
