### YamlMime:Yaml
ms.openlocfilehash: 3802a42896430337978891f360a54fca766356be
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903670"
Slug: azure-web-application-gallery-on-azure-microsoft-com
Title: Azure Web アプリケーション ギャラリー (azure.microsoft.com
Summary: >
  Azure Web アプリケーション ギャラリーを使用すると、人気のあるコミュニティ ASP.NET、PHP、Python、Java、Node.JS アプリケーションを Azure Websites で簡単に探索、検出、インストールできます。 ユーザーは、個人用ブログから e コマース Web サイト、企業の Web サイトまで、わずか数分で、アプリケーションを参照および表示して動的な Web サイトを構築できます。
Content: >-
  <a href="https://azure.microsoft.com/en-us/gallery/">Azure ギャラリーでは</a>、さまざまな Web サイトから人気のあるオープン ソース コミュニティ Web アプリケーションを簡単にMicrosoft Azureできます。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/09/21/galleryindex.png"><img style="margin: 0px; border: 0px;" title="galleryindex" alt="galleryindex" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/galleryindex_thumb.png" width="1026" height="662" border="0" /></a>


  &nbsp;


  Azure Web サイト用に提供されるアプリケーションの一覧を表示するには、ここをクリック <a href="https://azure.microsoft.com/en-us/gallery/web/">してください</a>。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/09/21/index1.png"><img style="margin: 0px; border: 0px;" title="index1" alt="index1" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/index1_thumb.png" width="996" height="770" border="0" /></a>


  &nbsp;


  これらのアプリケーションをクリックして詳細を確認し、[Web アプリの作成] をクリックしてアプリケーション <strong>を作成します。 </strong>


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/09/21/detailspage.png"><img style="margin: 0px; border: 0px;" title="detailspage" alt="detailspage" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/detailspage_thumb.png" width="1026" height="694" border="0" /></a>


  &nbsp;


  探しているアプリケーションが見つからない場合は、お気に入りフォーラムで提案 <a href="https://feedback.azure.com/forums/169385-websites">を共有してください</a>。
