### YamlMime:Yaml
ms.openlocfilehash: 49a73752bbd8c20b54fc90b1032352500521398a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904285"
Slug: azure-diagnostics-integration-with-application-insights
Title: Azure 診断 Application Insights との統合
Summary: azure SDK 2.8 では、azure Cloud Services プロジェクトと azure Windows vm の Application Insights に Azure 診断テレメトリが導入されました。
Content: >-
  <p>Azure クラウドサービスの応答速度が遅い &rsquo; 場合は、CPU またはメモリのボトルネックが発生している &rsquo; かどうか、または予期せず &rsquo; に失敗したか、開始 &rsquo; されていないかを確認する必要があります。システムログを表示します。 <a href="https://azure.microsoft.com/en-us/blog/announcing-the-azure-sdk-2-8-for-net/" target="_blank">azure SDK 2.8</a>では、azure Cloud Services プロジェクトと azure Windows vm のテレメトリを<a href="https://azure.microsoft.com/en-us/services/application-insights" target="_blank">Application Insights</a>に<a href="https://azure.microsoft.com/en-us/documentation/articles/cloud-services-dotnet-diagnostics/" target="_blank">Azure 診断</a>しまし &rsquo; た。 パフォーマンスカウンター、Windows イベントログ、およびアプリトレースはすべて、Application Insights SDK によってアプリ内から送信された<a href="https://azure.microsoft.com/documentation/articles/app-insights-start-monitoring-app-health-usage/" target="_blank">応答時間</a>、<a href="https://azure.microsoft.com/documentation/articles/app-insights-dependencies/" target="_blank">依存関係</a>、および<a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/" target="_blank">その他のイベント</a>と共に表示されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2fd47aac-298d-4aea-9867-f47097ad8852.png"><img alt="Overview Blade" border="0" height="610" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0b6c1f85-7599-4886-ac3c-614032e0b86a.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="概要ブレード" width="561"></a></p>


  <h2>Application Insights リソースを設定する</h2>


  <p><a href="https://azure.microsoft.com/documentation/articles/app-insights-cloudservices/" target="_blank">Cloud Services アプリに Application Insights SDK</a>をまだ追加していない場合は、ここで作成 &rsquo; します。 または、Azure 診断データだけを表示する場合は、そのデータを表示する<a href="https://azure.microsoft.com/documentation/articles/app-insights-create-new-resource/" target="_blank">新しい Application Insights リソースを作成</a>します。</p>


  <h2>Azure 診断を Application Insights に送信する</h2>


  <ul>
   <li>Visual Studio を開きます。 または、 <a href="https://github.com/FrictionFree/WAD2AI" target="_blank">PowerShell を使用</a>することもできます。</li>
  </ul>


  <p>まだクラウドサービスプロジェクトを発行し &rsquo; ていない場合は、次のようになります。</p>


  <ul>
   <li>ソリューションエクスプローラーで、各 web ロールまたは worker ロール (プロジェクトではなくロール) のプロパティを開きます。</li>
   <li>[ <strong>Application Insights に診断データを送信することを</strong>確認します。</li>
   <li>アプリの Application Insights リソースを選択します。</li>
   <li>サービスを発行します。</li>
  </ul>


  <p>クラウドサービスまたは仮想マシンが既に実行されている場合:</p>


  <ul>
   <li>サーバーエクスプローラーまたは Cloud Explorer で、クラウドサービスまたは仮想マシンを右クリックし、[ <strong>診断の有効化/更新</strong>] を選択します。</li>
   <li>[ <strong>Application Insights に診断データを送信することを</strong>確認します。</li>
   <li>アプリの Application Insights リソースを選択します。</li>
   <li>更新プログラムを適用します。</li>
  </ul>


  <p><img alt="Send Azure Diagnostics to Application Insights" border="0" height="458" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d4b3e0f3-cee3-4a0a-a8c9-1bdcd127ba0d.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Visual Studio から Application Insights に Azure 診断を送信する" width="610"></p>


  <h3>&nbsp;</h3>


  <h2>Application Insights ポータルで Azure 診断データを表示する</h2>


  <p>診断テレメトリが Application Insights ポータルに表示されます。</p>


  <ul>
   <li><strong>イベントログの Windows</strong>

   <ul>
    <li>個々のイベントを調査するには、 <a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/" target="_blank"><em>検索</em></a> を使用します。</li>
    <li>さまざまな種類のイベントの数を確認するには、 <a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/" target="_blank"><em>メトリックスエクスプローラー</em></a> を使用します。 [<em>カスタム</em>] カテゴリの下に表示される [ <em>Azure 診断イベント</em>] メトリックを選択します。</li>
   </ul>
   </li>
   <li><strong>アプリケーショントレースと <a href="https://msdn.microsoft.com/library/ms751538(v=vs.110).aspx" target="_blank">ETW</a> トレース</strong>: ログトレースを検索して検査するには、 <a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/" target="_blank"><em>Search</em></a> を使用します。</li>
   <li><strong>パフォーマンスカウンター</strong>: [概要] ブレードから [サーバー] タイルを開くか、<a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/" target="_blank"><em>メトリックスエクスプローラー</em></a> &nbsp; または<em><a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-analytics/" target="_blank">Application Insights Analytics</a></em>を使用して、独自のグラフを作成します。 <em>使用可能なメモリ</em>と<em>% Processor Time</em>パフォーマンスカウンターは、[<em>パフォーマンスカウンター</em> ] カテゴリに表示されますが、[<em>カスタムメトリック</em>] の下にもあります。</li>
  </ul>


  <p><img alt="View Azure Diagnostics telemetry in Application Insights" border="0" height="410" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/30ab484f-b7f0-43c2-b84e-0f1a35e46b93.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Application Insights で Azure 診断テレメトリを表示する" width="610"></p>


  <h2>結合された診断の使用</h2>


  <p>Azure 診断および Application Insights SDK は、ライブアプリケーションの補完的なビューを提供します。 Azure 診断では、システムの観点、パフォーマンスカウンター、ロールライフサイクルデータ、およびその他の Windows イベントが提供されます。一方、SDK はアプリ内からデータを送信し、要求、例外、依存関係、および追加した<a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/" target="_blank">カスタムテレメトリ</a>についての情報を送信します。</p>


  <p>&rsquo;ご覧のとおり、それぞれが1つのオプションでオンになっており、Azure portal の同じリソースにデータストリームを送信できます。 &rsquo;セットアップが簡単になり、2つのストリームの組み合わせによって優れた診断値が得られます。</p>


  <p>ここでは、特にこの組み合わせを使用する &rsquo; いくつかのシナリオについて説明します。</p>


  <ul>
   <li>パフォーマンスの低下: &rsquo; 問題の診断に役立つシステムイベントとパフォーマンスデータが表示されます。</li>
   <li>ロールのクラッシュ、リサイクル、またはロールライフサイクルデータの開始 &ndash; の失敗は、この種類の問題を特定するのに非常に役立ちます。</li>
  </ul>


  <p>すべてのデータを1か所に表示 &rsquo; することで、VM にログインしたり、他の場所に移動してイベントログ &ndash; を検索したりする必要がなくなり &rsquo; ます。ここでは、アプリとシステムテレメトリを関連付けることができます。</p>


  <p>Application Insights ユーザーの声のページで新機能や改善された機能についてアイデアを共有してください。質問がある場合は、 <a href="https://social.msdn.microsoft.com/Forums/en-US/ApplicationInsights/" target="_blank">Application Insights フォーラム</a>にアクセスしてください。</p>
