### YamlMime:Yaml
ms.openlocfilehash: 46033c0cb21f5e528b39e4aa04b79418c6bb8f57
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890242"
Slug: azure-layered-approach-to-physical-security
Title: 物理的なセキュリティに対する Azure のレイヤード アプローチ
Summary: Azure は、インフラストラクチャ、アプリケーション、およびデータをホストするために、一から構築された、安全性の高い基盤を提供するのに役立ちます。
Content: >-
  <p><em>これは、セキュリティで保護された基盤を提供する方法<a href="https://azure.microsoft.com/en-us/blog/tag/azure-security/"></a>に関する 4 部Microsoft Azureブログ記事シリーズの最初のブログです。</em></p>


  <p>多くのお客様から、クラウド セキュリティが最も懸念事項の 1 つだとお聞きしています。 お客様から&rsquo;聞いたもう 1 つのことは、Azure でのセキュリティ保護の責任と Azure の実行を明確にしたいと考えています。 Azure は、インフラストラクチャ、アプリケーション、およびデータをホストするために、一から構築された、安全性の高い基盤を提供するのに役立ちます。 お客様のデータを保護することの重要性を理解しています。これは、データを含むデータセンターのセキュリティ保護に取り組む理由です。 Microsoft は、Azure プラットフォームの物理的なセキュリティなど、セキュリティに 10 億ドルを超える投資を行っています。そのため、他のビジネス イニシアチブに時間とリソースを割り当ててみることができます。 今後数か&rsquo;月間、セキュリティで保護された基盤のブログ シリーズの一部として、Azure&rsquo; プラットフォームの構成に役立つ物理、インフラストラクチャ (論理) および運用セキュリティのコンポーネントについて説明します。 現在、私たちは物理的なセキュリティに焦点を当てました。</p>


  <p>物理的なセキュリティとは、顧客データが格納されている領域への物理的なアクセスを厳密に制御する方法で、Microsoft がデータセンターを設計、構築、運用する方法を指します。 データセンターは、国際的に認められているすべてのクラウド サービス プロバイダーの標準と認定の最も包括的な<a href="https://azure.microsoft.com/en-us/overview/trusted-cloud/" target="_blank"></a>ポートフォリオに準拠している認定を受けています。 Microsoft には、Azure をサポートする物理的な施設の設計、構築、運用に専念する部門があります。 このチームは、最先端の物理セキュリティの維持に注力しています。</p>


  <p>物理的なセキュリティに対して、レイヤード アプローチを採用しています。 Microsoft&rsquo;&rsquo; が管理するデータセンターには、アクセス承認、施設の境界、建物の境界、建物内、データセンターのフロアなど、広範な保護レイヤーがあります。 このレイヤーアプローチにより、承認されていないユーザーがデータとデータセンター リソースに物理的にアクセスするリスクが軽減されます。</p>


  <p>物理的なセキュリティの最初の層は、データセンターに到着する前にアクセスを要求する処理から始まります。 コンプライアンスや監査の目的など、アクセスに対して有効な業務上の正当な理由を指定する必要があります。 すべての申請は、Microsoft の社員によって、アクセスの必要性に基づいて承認されます。 これは、データセンターでタスクを完了するために必要な個人の数を最小限に抑え続けるために役立ちます。 アクセス許可が付与されると、承認された業務上の正当な理由に基づいて、個人はデータセンターの個別の領域にのみアクセスできます。 入館許可は、一定の期間に制限されており、許可された期間を超過すると失効します。</p>


  <p>セキュリティの次の層は、建物の境界&rsquo;です。 データセンターに到着したら、十分に定義されたアクセス ポイントを通過する必要があります。 通常は、スチールやコンクリートでできた高いフェンスが、周辺を 1 インチごとに取り囲んでいます。 データセンターの周辺にはカメラが設置され、セキュリティ チームが1 年の 365 日間、週 7 日間の 24 時間体制で、ビデオを監視しています。</p>


  <p>データセンターの境界にアクセスしたら、データセンター&rsquo;に入るために追加のセキュリティ対策を渡す必要があります。 データセンターの玄関には、厳格な研修と経歴のチェックを受けたプロのセキュリティ担当者が常駐しています。 また、これらのセキュリティ責任者は、データセンター内のカメラのビデオを 24 時間 365 日監視しながら、データセンターを定期的に巡回しています。 建物に入った後、データセンター内で移動を続けるには、生体認証による 2 段階認証に合格する必要があります。 ID が検証された場合は、アクセスを承認したデータセンターの一部を入力し、承認された期間だけそこに残することができます。</p>


  <p>データセンターフロアの要求された部分の入り口に到着したら、完全なボディ メタル検出スクリーンに合格する必要があります。 未承認のデータが把握されないままデータセンターを入退館するリスクを低減するために、データセンターの各階には、承認されたデバイスしか持ち込みできません。 さらに、ビデオ カメラは、すべての仮想マシン ラックの前面と背面を監視します。 仮想マシンで行&mdash;うすべての操作は、ハード ディスクがクリーンアップおよび消去されるまで仮想マシンに初めて入った場合に追跡されます。 全身の金属検査によるスクリーニングは、データセンターの各階を退出するたびに、繰り返し行われます。 データセンターを離れるには、追加のセキュリティ スキャンを通過する必要があります。&nbsp;&nbsp;</p>


  <p>クラウド プラットフォームのセキュリティを確保するために、世界中のデータセンターの保護が最優先事項です。 お客様のデータをセキュリティで保護することの重要性とセキュリティ侵害のリスクを理解しています。これは、10 億ドルを超える投資を世界規模のセキュリティに投資し、残業でこれらの投資を拡大し続ける理由です。 データとデータセンターのリソースが高度にセキュリティで保護されているのを知って、ビジネス上の優先順位に集中できます。</p>


  <p>データセンターのセキュリティが実際に動作しているのを確認するには、次のビデオをご覧ください。</p>


  <p align="center"><iframe allow="autoplay; encrypted-media" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/r1cyTL8JqRg" width="560"></iframe></p>
