### YamlMime:Yaml
ms.openlocfilehash: a8bfe9b60dec494dbe73c73549adcbb55aa3f452
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139896179"
Slug: azure-iot-hub-device-provisioning-service-preview-automates-device-connection-configuration
Title: Azure IoT Hub device Provisioning Service プレビューでは、デバイスの接続と構成が自動化されます。
Summary: '現在、Azure IoT Hub Device Provisioning Service のパブリックプレビューが発表されています。 device provisioning service は、Azure IoT ハブと連携して、お客様が IoT hub へのゼロタッチデバイスプロビジョニングを構成できるようにする新しいサービスです。 '
Content: >-
  <p>本日、Azure IoT Hub Device Provisioning Service のパブリックプレビューを再発表&#39;ます。 device provisioning service は、Azure IoT ハブと連携して、お客様が IoT hub へのゼロタッチデバイスプロビジョニングを構成できるようにする新しいサービスです &nbsp; 。 Device Provisioning Service を使用すると、セキュリティで保護されたスケーラブルな方法で何百万ものデバイスをプロビジョニングできます。これにより、従来よりも時間がかかり、接続されているデバイスのボリュームを管理する製造元や企業がリソースを大量に消費しているプロセス &nbsp; を自動化できます。 デバイスプロビジョニングサービスは、デバイスをクラウドに登録するだけでなく、デバイスを構成することも含め、完全な自動プロビジョニングを提供する唯一のクラウドサービスです。 Device Provisioning Service は、今日の米国東部、西ヨーロッパ、東南アジアで利用でき、最終的にはグローバルに利用できるようになります。</p>


  <p>プロビジョニングサービスを使用しない場合、デバイスを Azure IoT Hub に接続するには手動の作業が必要です。 デバイスのセキュリティが侵害された場合にデバイスごとのアクセスを失効させるには、各デバイスに一意の id が必要です。 この方法は、ほとんどのデバイスでは使用できませんが、IoT のスケールでは、数百万のデバイスに接続の資格情報を個別に配置する必要があります。</p>


  <p>&iuml;接続の問題を解決する方法は、製造時にデバイスに IoT Hub 接続情報をハードコーディングすることですが、これは一部のシナリオでのみ機能します。 多くの場合、プロビジョニングを完了するには、デバイスを購入したユーザーやデバイスの用途など、デバイスの製造時には利用できなかった情報が必要です。</p>


  <p>デバイスが接続された後も、 <a href="https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins">必要なツインの状態</a> とソフトウェアやファームウェアの更新プログラムを使用して構成する必要があります。 これは、デバイスの展開を計画するときに考慮することができます。</p>


  <p>ここでは、デバイスプロビジョニングサービスが顧客を大量に保存するため、登録時にデバイスを自動的に構成して IoT Hub することができます。 Device Provisioning Service には、デバイスをプロビジョニングするために必要なすべての情報が含まれています。デバイスのボックスを解除してから再フラッシュしなくても、後でサプライチェーンの情報を簡単に更新できます。</p>


  <p>Device Provisioning Service が有効にするプロビジョニングシナリオの一部を次に示します。</p>


  <ul>
   <li>工場での接続情報のハードコード IoT Hub を必要としない、単一の IoT ソリューションへのゼロタッチプロビジョニング (初期セットアップ)。</li>
   <li>ソリューション固有のニーズに基づいてデバイスを自動的に構成します。</li>
   <li>複数のハブ間でデバイスを負荷分散します。</li>
   <li>販売トランザクションデータ (マルチテナント機能) に基づいてデバイスを所有者 &rsquo; の IoT ソリューションに接続します。</li>
   <li>ユースケースに応じて特定の IoT ソリューションにデバイスを接続します (ソリューションの分離)。</li>
   <li>最も近い geo ロケーションを使用してデバイスを IoT hub に接続します。</li>
   <li>デバイスの変更 (所有権や場所の変更など) に基づいて再プロビジョニングします。</li>
  </ul>


  <p>このようなシナリオはすべて、現在も同じ基本的なフローを使用して Device Provisioning Service で実現できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/00868aff-fb7b-42ec-99ff-a212b0644bc9.png"><img alt="image" border="0" height="229" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c64c2a4c-885b-49ae-b047-1b144a2e3d59.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="480"></a></p>


  <p>&nbsp;</p>


  <p>Device Provisioning Service は、ハードウェアセキュリティモジュール (Hsm) を使用してキーを安全に格納するデバイスで最適に機能します。 Hsm は、キーの格納に最大限のセキュリティを提供します。また、更新されたデバイス SDK により、HSM を使用して、デバイスとクラウドの間の信頼のルートを非常に簡単に確立できます。 Microsoft は複数の HSM メーカーとパートナーシップを結んでおり、 <a href="https://azure.microsoft.com/en-us/blog/azure-iot-supports-new-security-hardware-to-strengthen-iot-security/">Azure ブログ</a>に含まれるパートナーシップと HSM のオプションについて確認できます。 デバイスが HSM を使用できない場合でも、デバイスプロビジョニングサービスに接続できます。 シミュレートされた <a href="https://aka.ms/simulatedhsm">TPM またはソフトウェアベースの x509 証明書</a>の使用方法については、こちらを参照してください。</p>


  <p>詳細につい<a href="https://aka.ms/provisioningconcepts">ては、「デバイスのプロビジョニングに関連するすべての技術概念」を参照して</a>ください。</p>


  <p>Azure IoT は、セキュリティで保護された信頼性の高い方法で IoT ソリューションのデプロイと管理を行うことが困難になるサービスを提供するためにコミットされています。 <a href="https://portal.azure.com/">Azure portal</a>で独自の Device Provisioning Service を作成し、 <a href="https://aka.ms/dpssdk">GITHUB</a>でデバイス SDK を確認することができます。 Device Provisioning Service の詳細と、 <a href="https://docs.microsoft.com/en-us/azure/iot-dps/">ドキュメントセンター</a>での使用方法について説明します。 セキュリティで保護されたデバイスの登録についてフィードバックをお寄せください (これはプレビューの時点で&#39;)。そのため、 <a href="https://feedback.azure.com/forums/321918-azure-iot/">Azure IoT ユーザーの声フォーラム</a>から引き続き提案を送信してください。</p>
