### YamlMime:Yaml
ms.openlocfilehash: 1ffaadafb52c761aae0ca2d27749dfc65b414ae0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889574"
Slug: azure-security-center-can-identify-attacks-targeting-azure-app-service-applications
Title: Azure Security Center は Azure App Service アプリケーションを対象とする攻撃を特定できます
Summary: Azure の最も一般的なサービスの1つは App Service で、インフラストラクチャを管理することなく、お客様が選択したプログラミング言語で web アプリケーションを構築してホストすることができます。
Content: >-
  <p>Azure &rsquo; の最も一般的なサービスの1つは <a href="https://azure.microsoft.com/en-us/services/app-service/" target="_blank">App Service</a> で、インフラストラクチャを管理することなく、お客様が選択したプログラミング言語で web アプリケーションを構築してホストすることができます。 App Service は、自動スケールと高可用性を提供し、Windows と Linux の両方をサポートしています。 また、GitHub、Visual Studio Team Services、または任意の Git リポジトリからの自動化されたデプロイもサポートしています。 <a href="https://azure.microsoft.com/en-us/blog/announcing-new-azure-security-center-capabilities-at-rsa-2018/" target="_blank">RSA で</a>は、Azure Security Center がクラウドのスケールを活用して App Service アプリケーションを対象とする攻撃を特定することを発表しました。</p>


  <p>Web アプリケーションの脆弱性は、インターネット上のほとんどすべての組織に共通の動的インターフェイスであるため、攻撃者によって頻繁に悪用されます。 App Service 上で実行されているアプリケーションへの要求は、世界中の Azure データセンターにデプロイされている複数のゲートウェイを経由し、それぞれの要求を対応するアプリケーションにルーティングします。 最近、App Service のお客様をサポートするためのセキュリティオファリングを構築することを目的とした、Security Center と App Service を embarked しています。</p>


  <p>Azure がクラウドプロバイダーとして提供する可視性を活用することにより、Security Center は App Service 内部ログを分析して、複数のターゲットでの攻撃方法を特定します。 たとえば、は、さまざまな web サイトで同じ URI (Uniform Resource identifier) にアクセスしようとします。 通常、この種の攻撃者は、複数の web サイト上の同じ web ページに対して、特に脆弱なページやプラグインを検索するパターンを示すことになります。 Security Center は、Web アプリケーションファイアウォール (WAF) の音色を通過する可能性がある動作を検出し、アラートを通知することができます。</p>


  <p>WAFs は、web アプリケーションを保護するために採用されている広範な保護メカニズムです。 通常、WAFs は、要求された Uri に対してルールベースの文字列分析を実行し、一般的な攻撃を正しく特定します。 例としては、SQL インジェクション、クロスサイトスクリプティング、その他の HTTP 違反などがあります。 既知の攻撃を軽減するために、ルールベースのアプローチは、新しい脆弱性の発生率に対応できません。</p>


  <p>Security Center は、クラウドの規模を活用して、新たな攻撃に焦点を合わせながら、App Service アプリケーションに対する攻撃を特定します。攻撃者は偵察段階であるため、スキャンによって複数の web サイトの脆弱性を特定し、Azure でホストされます。 Security Center &rsquo; s の新機能には、すべてのインターフェイスを網羅した分析モデルと機械学習モデルが含まれています。これ &rsquo; により、お客様は、HTTP 経由でも、いずれかの管理方法を使用して、アプリケーションを操作できます。 さらに、Azure のファーストパーティサービスとして、Security Center も、この PaaS の基盤となるコンピューティングノードをカバーするホストベースのセキュリティ分析を提供するための一意の場所にあります。 このため、Security Center は、既に悪用されている web アプリケーションに対する攻撃を検出できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8af5852b-1cd3-4eec-ba0f-30392943ed89.png"><img alt="image" border="0" height="502" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/168a8058-bbdb-4e81-b30e-b2fd9fca0f29.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="347"></a></p>


  <p>Web アプリケーションを管理することによって、ワークロードをセキュリティ上の脆弱性にさらすことができます。これは、およびアドレスと考える必要があります。 これらの脆弱性により、web アプリケーションが悪用され、攻撃者がワークロードのフットプリントを獲得する可能性があります。 Security Center には、windows と Linux の両方の web アプリケーションの一連の推奨事項が用意されています。セキュリティのベストプラクティスに従って、web アプリケーションを正しく構成するプロセスについて説明します。</p>


  <p>この機能のパブリックプレビューは、Security Center の Standard および試用版レベルで追加料金なしでご利用いただけます。</p>


  <p>Security Center 脅威検出の詳細については、 <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-detection-capabilities" target="_blank">「」を参照</a>してください。または、<a href="https://azure.microsoft.com/en-us/blog/how-azure-security-center-helps-reveal-a-cyberattack/" target="_blank">ブルートフォース攻撃</a>、 <a href="https://azure.microsoft.com/en-us/blog/how-azure-security-center-detects-a-bitcoin-mining-attack/" target="_blank">bitcoin マイニング</a>、<a href="https://azure.microsoft.com/en-us/blog/how-azure-security-center-detects-ddos-attack-using-cyber-threat-intelligence/" target="_blank">サイバー脅威インテリジェンスを使用した DDoS 攻撃</a>、および悪意を持っ<a href="https://azure.microsoft.com/en-us/blog/how-azure-security-center-aids-in-detecting-good-applications-being-used-maliciously/" target="_blank">て使用されている適切なアプリケーション</a>を SQL 検出 Security Center 方法について、セキュリティ研究者からのケーススタディを確認してください。</p>
