### YamlMime:Yaml
ms.openlocfilehash: 0918a9e854177d0c1da9875e05b7fd4113f8d363
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895605"
Slug: azure-security-center-now-generally-available-proven-to-improve-security
Title: セキュリティを強化するために、一般提供が開始される Azure Security Center
Summary: これらのツールの最新の Azure Security Center が一般公開されていることをお知らせします。
Content: >-
  <p>サイバーセキュリティの可視性と制御を維持することは、一定の課題です。 また、攻撃者がイノベーションを行うにつれて、膨大な作業になる可能性があります。 平均して、組織が侵害を検出するまでに200日以上かかることがあります。 侵害の平均コストが何百万ドルに達した場合、杭はそれほど高くありません。</p>


  <p>Microsoft では、クラウドサービスを大規模に実現することによって得られた脅威インテリジェンスについて、Microsoft &rsquo; の独自の観点を活用する新しいアプローチが必要 &mdash; であると考えています。 この新しい方法では、セキュリティをプラットフォームに統合し、パートナーのソリューションを組み込みます。 これらのすべての分野の <a href="https://aka.ms/I1stiu">機能</a> を強化するために、毎年、研究および開発に $10億を超える投資を行っています。</p>


  <p>Azure では、この投資は、物理的、ネットワーク、および運用上のセキュリティの堅固な基盤を構築するのに役立ちます。 Microsoft では、業界のベストプラクティスに基づいて、幅広いコンプライアンス認定を通じて機能を実証しています。</p>


  <p>また、Azure にデプロイするリソースのセキュリティ目標を達成するのに役立つツールに投資しています。 本日は、これらのツールの最新の Azure Security Center が一般公開されていることをお知らせします。</p>


  <p>プレビュー期間中 Azure Security Center は、Chronodrive、Jet.com、Metro 銀行などのお客様が Azure リソースのセキュリティ状態を可視化して、クラウドセキュリティポリシーと監視対象のセキュリティ構成を管理し、アクティブな攻撃を検出して対応できるようにします。</p>


  <p>Azure Security Center は、リソースのセキュリティの正常性を向上させるために50万を超える推奨事項を提供しています。 機械学習や Microsoft &rsquo; の幅広いグローバル脅威インテリジェンスを含む高度な分析を使用して、1か月 &ndash; あたり14万を超える脅威を検出し、実行可能なアラートを提供し、検出と応答時間を大幅に短縮しました。</p>


  <p>追加のセキュリティ制御が推奨されているシナリオでは、Azure Security Center を使用すると、 &nbsp; Azure に組み込まれているコントロールの検索、デプロイ、構成を簡単に行うことができ、パートナーのソリューションも簡単になります。 Barracuda、Check Point、F5、For Et、Imperva、Trend Micro のソリューションは既に用意されています。 Cisco と &nbsp; Qualys のソリューションは、今後数週間にわたって提供される予定です。 また、お客様のインフラストラクチャを保護するためにさまざまなセキュリティツールを採用していることがわかっているので、エコシステムは成長し続けます。</p>


  <h3>新機能 &rsquo;</h3>


  <p>また、いくつかの新機能が追加されました。</p>


  <ul>
      <li><strong>ログ統合。</strong> Azure 用の新しい <a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-integrating-alerts-with-log-integration/">コネクタ</a> を使用すると、Azure Security Center アラートなどのセキュリティデータを、HP ARCSIGHT、IBM &nbsp; qradar、およびその他のイベント管理ソリューションに追加するプロセスを効率化できます。</li>
      <li><strong>その他の Azure リソースの種類のサポート。</strong> Security Center は、システムの更新状態、OS 構成、ディスク暗号化など、RedHat やその他多くの Linux <a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-faq/#virtual-machines">ディストリビューション</a>のセキュリティをより広範囲に監視できるようになりました。 また、Cloud Services (Web ロールと Worker ロール) のセキュリティの正常性を監視し、古い OS インスタンスを <a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-update-os-version/">更新</a>することをお勧めします。</li>
      <li><strong>電子メール通知。</strong> 新しい重要度の高いセキュリティのアラートが検出されたときに電子メール通知を使用して、脅威に迅速に対応します。</li>
      <li><strong>新しい検出。</strong> Security Center は、水平方向の動き、発信攻撃、および悪意のあるスクリプトを検出する機能が改善され、研究者は常に新 <a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-detection-capabilities/">機能</a>を追加しています。</li>
      <li><strong>セキュリティインシデント。</strong> Analytics を使用して個別のセキュリティアラート間のドットを接続することで、Security Center が攻撃キャンペーンと関連するすべてのアラートを <a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-incident/">1 つのビュー</a> で提供できるようになりました。これにより、攻撃者によってどのようなアクションが行われたか、どのリソースが影響を受けたかをすばやく把握できます。</li>
      <li><strong>REST Api。</strong> 既存の変更管理またはセキュリティオペレーションシステムと統合する必要があるお客様には、 <a href="https://msdn.microsoft.com/en-US/library/mt704034(Azure.100).aspx">REST API のドキュメント</a>を公開しました。</li>
      <li><strong>統合された脆弱性評価。</strong> 今後数週間にわたって、お客様はわずか数回のクリックで Qualys などのパートナーから脆弱性評価ソリューションをデプロイできるようになります。</li>
  </ul>


  <p>他のパブリッククラウドは、Azure Security Center によって提供される継続的な監視を提供しません。 また、マイクロソフトがさまざまな企業や消費者の製品やサービスから収集できる脅威インテリジェンスの幅と多様性を他のベンダーに適合させることはできません。 このインテリジェンスを機能させるには、まず、Azure Security Center を使用します。</p>


  <h3>詳細情報</h3>


  <ul>
      <li><a href="https://azure.microsoft.com/services/security-center/">Azure Security Center</a></li>
      <li><a href="https://azure.microsoft.com/pricing/details/security-center/">料金情報</a></li>
      <li><a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-data-security/">プライバシー情報</a></li>
  </ul>
