### YamlMime:Yaml
ms.openlocfilehash: 082c0cbcaf15a67c355b37a7383187d333eeb5ca
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890005"
Slug: azure-active-directory-news-application-proxy-general-availability-and-many-more-new-additions
Title: 'Azure Active Directoryニュース: アプリケーション プロキシ一般提供と、さらに多くの新しい追加'
Summary: 今年は、新しいチームから 1 日でリリースされた最大の機能セットAzure Active Directoryしています。 多くの機能は初めてパブリック プレビューで提供され、その他は 12 月 11 日に一般公開されています。
Content: >-
  今年は、新しいチームから 1 日でリリースされた最大の機能セットAzure Active Directoryしています。 多くの機能は初めてパブリック プレビューで提供され、その他は 12 月 11 日に一般公開されています。


  Azure Active Directory アプリケーション プロキシ の一般提供発表から、<a href="https://msdn.microsoft.com/en-us/library/azure/dn768219.aspx">Azure Active Directory</a> では、オンプレミスでホストされているあらゆる種類の Web アプリケーションへのシングル サインオンとセキュリティで保護されたリモート アクセスを提供できます。 アプリケーション プロキシ、Web アプリケーションの発行が可能になります。また、プレミアム <a href="https://msdn.microsoft.com/library/azure/dn532272.aspx">エディションと Basic エディションの両方で使用できます</a>。 これで、SaaS アプリケーションと同じ方法でオンプレミスの Web アプリを配信し、エンド ユーザーに対して一部のスムーズなエクスペリエンスを実現できます。


  その他のリリースアプリケーション プロキシの詳細については、Active Directory チームのブログ <a href="https://blogs.technet.com/b/ad/">を参照してください</a>。

  <h2>その他の機能強化:</h2>

  <b>パスワード ライトバック</b>はAzure Active Directoryからオンプレミスディレクトリに一般提供されています。 クラウド上のパスワードの変更は、同期を使用してオンプレミスのディレクトリにAzure Active Directoryできます。


  <a href="https://go.microsoft.com/fwlink/?LinkID=519058"><b>管理単位</b></a> 大規模な企業がディレクトリをサブ分割し、複雑な組織全体で管理アクセス許可を委任するために、パブリック プレビューが予定されています。


  <b>パスワード SSO をサポートする SaaS</b> アプリケーションを、管理者が自分のテナントに手動Azure Active Directoryできます。 この機能は、パブリック プレビューで導入されています。 この Azure Active Directory テナントへのアプリケーションのカスタム追加は、シングル サインオン方法や、Azure Active Directory アプリケーション ギャラリーに存在するかどうかに依存しない、アプリケーションへのほぼすべてのリンクを追加してエンドユーザーの <a href="https://azure.microsoft.com/en-us/marketplace/active-directory/">アクセス パネル</a> に割り当て可能な時点まで拡張されます。


  上記の追加により、Azure Active Directory アクセス パネル は、アプリケーション ギャラリーまたはカスタム、オンプレミスから発行された Web アプリケーション (アプリケーション プロキシ 経由) およびパブリックにアクセスできるリンクを持つ任意のアプリケーションから SaaS アプリケーションを起動するポイントになります。


  <b>セキュリティで</b> 保護されたセルフサービス パスワード リセットのオプションとしてのセキュリティの質問も、パブリック プレビューで公開される予定です。 電話または電子メール アカウントにアクセスできないユーザーは、定義済みのセキュリティに関する多くの質問に回答して、ID を証明し、myapps.microsoft.com Web ページ (アクセス パネル) からパスワードをリセットするアクセス許可を取得できます。


  引き続き、このブログAzure Active Directory、Azure Multi-Factor Authentication、Hybrid Identity のニュースを引き続き共有します。
