### YamlMime:Yaml
ms.openlocfilehash: 837569fb6c10502ebb7a416d98905f712141cfe7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890560"
Slug: azure-hdinsight-application-platform-install-solutions-built-for-the-apache-hadoop-ecosystem
Title: 'Azure HDInsight アプリケーションプラットフォーム: Apache Hadoop エコシステム用に構築されたソリューションをインストールする'
Summary: Apache Hadoop エコシステム用に構築したソリューションまたはアプリケーションを簡単に配布、検出、インストールできることをお知らせします。
Content: >-
  <p>Azure HDInsight は、クラウドによって機能強化された Apache Hadoop ディストリビューションです。 これは、必要に応じてテラバイトからペタバイトにスケーリングすることで、あらゆる量のデータを処理することを意味します。 任意の時点 &ndash; で任意の数のノードを作成できます。使用するコンピューティングとストレージに対してのみ課金されます。</p>


  <p>Apache Hadoop エコシステム用に構築したソリューションまたはアプリケーションを簡単に配布、検出、インストールできることをお知らせします。 これらのソリューションは、データインジェスト、データラングリング、監視、視覚化、パフォーマンスの最適化、セキュリティ、分析、視覚化、レポートなどのさまざまなシナリオにまたがることができます。</p>


  <p><u>このエクスペリエンスの主な特徴を次に示します。</u></p>


  <p><b>作成、展開、管理の容易さ</b></p>


  <ul>
   <li>これらのアプリは、既存の HDInsight クラスターだけでなく、新しいクラスターの作成時にもインストールできます。&nbsp;</li>
  </ul>


  <p><b>クラスターへのネイティブアクセス</b></p>


  <ul>
   <li>アプリはエッジノードにインストールされ、クラスター全体にアクセスできます。</li>
  </ul>


  <p><b>クラスターでのアプリの構成の容易さ</b></p>


  <ul>
   <li>これらのアプリケーションのエンドユーザーは、すべてのノードでパッケージをインストールまたは管理し、アプリケーションを構成する必要はありません。</li>
  </ul>


  <p><b>既存の HDInsight クラスターにソリューションをインストールします。</b></p>


  <ul>
   <li>ソリューションプロバイダーは、既に HDInsight クラスターが実行されているユーザーがソリューションを使用できるようにすることができます。 これにより、ユーザーはこれらのソリューションを簡単に使用して、生産性を向上させることができます。</li>
  </ul>


  <p>ユーザーは、[ <b>アプリケーション </b>] ブレードを選択して、クラスター上のアプリを検出してインストールすることができます。</p>


  <p>次のスクリーンショットでは、既存のクラスターがあり、Datameer アプリケーションを検出できます。 その後、Datameer アプリケーションをクリックすると、既存のクラスターにすばやく簡単にインストールできます。</p>


  <p><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fe29ccc1-715c-4d5b-ba94-cf62638dffad.png" style="border-width: 0px; width: 610px; height: 302px; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title=""></p>


  <p>&rsquo;クラスターに Datameer をインストールすると、インストールされているアプリの一覧に表示されるようになります。</p>


  <p><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cd5dbb08-7e86-4524-9112-a02258907ea4.png" style="border-width: 0px; width: 610px; height: 295px; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title=""></p>


  <p>Datameer がインストールされているので、[インストールされているアプリ] ブレードから Datameer Studio にアクセスできるようになりました。これにより、HDInsight で実行されている、エンドツーエンドのセルフサービスのビッグ Data Analytics プラットフォームで &rsquo; 、新しいプロジェクトを開始できます。 次のスクリーンショットは、Datameer Studio を示しています。</p>


  <p><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ddda0f50-62ee-4e40-8a15-81592bc6611f.png" style="border-width: 0px; width: 610px; height: 218px; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title=""></p>


  <p>インストールされているアプリケーションを削除することもできます。 このスクリーンショットでは、アプリケーションを右クリックして簡単に削除できる色合いアプリケーションをインストールしました。 色合いのインストールの詳細について <a href="https://azure.microsoft.com/en-us/documentation/articles/hdinsight-apps-install-custom-applications/">は、こちら</a>を参照してください。</p>


  <p>次のスクリーンショットは、アプリケーションを削除する方法を示しています。</p>


  <p><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/954ea67a-aaab-4d6f-9348-695402a580db.png" style="border-width: 0px; width: 610px; height: 523px; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title=""></p>


  <p>これは、Hadoop を使用してエンドユーザーの生産性を向上させるソリューションを検出およびインストールするための非常に簡単な方法です。 <b>同じ方法を使用して、カスタムアプリケーションを作成し、チームと共有することができます。</b></p>


  <p>Datameer は、ソリューションを簡単に使用できるようにするために、このエクスペリエンスを開発しています。 クラウドソリューションの Datameer &rsquo; <b>の Sr 製品マネージャー</b>によれば、Alejandro は次のようになります。</p>


  <p><b><i>&quot;Azure HDInsight アプリケーションプラットフォームは、クラウドでの Datameer のデプロイを迅速に構成してテストするために&#39;に見られた、最も堅牢で安定したフレームワークです。ソリューションのさまざまなデプロイオプションや、同じポータル内のマーケティング資料を反復的にテストできる柔軟性がありました。これまで、クラウドベースのソリューションを市場に投入する最も簡単かつ迅速な方法になります。&quot;</i></b></p>


  <p>Datameer の詳細については、 <a href="https://azure.microsoft.com/en-us/marketplace/partners/datameer/datameerdatameer/">Azure Marketplace に掲載</a>されている datameer の一覧を参照してください。</p>


  <p>Apache Hadoop エコシステム用に構築したソリューションがあり、HDInsight で使用できるようにする必要がある場合は、使用可能にする方法について次のドキュメントをお読みください。</p>


  <p><b>ドキュメント &amp; の &rsquo; 操作方法</b></p>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/hdinsight-apps-install-custom-applications/">カスタム HDInsight アプリケーションをインストールする</a></p>


  <p><a href="https://msdn.microsoft.com/en-us/library/mt706515.aspx">アプリに関する MSDN ドキュメント</a></p>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-customize-cluster-linux/">スクリプト アクションを使用して Linux ベースの HDInsight クラスターをカスタマイズする</a></p>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/hdinsight-apps-publish-applications/">Azure Marketplace への HDInsight アプリケーションの発行</a></p>


  <p><b>まとめ</b></p>


  <p>このエクスペリエンスは、ビッグデータを使用して顧客の生産性を向上させるために、簡単に配布できるソリューションであることを願っています。 お客様がソリューションを簡単に見つけて使用できるように、この機能を活用するために独立系ソフトウェアベンダー (Isv) を招待します。 参加したい場合は、に <a href="mailto:hdipartners@microsoft.com">hdipartners@microsoft.com</a> お問い合わせください。</p>
