### YamlMime:Yaml
ms.openlocfilehash: 86a8202cfc46550a306e16c5c3751fd2cae13295
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139894867"
Slug: azure-is-the-home-for-your-enterprise-java-applications
Title: Azure は、エンタープライズ Java アプリケーションのホームです
Summary: マイクロサービス アーキテクチャはますます普及し、開発者はコンテナーとマネージド サービスを使用してクラウド プラットフォーム上により多くのアプリケーションを構築しています。 Java エコシステムは複雑であり、エンタープライズ規模でクラウドで Java アプリケーションを実行するのは困難な場合があります。 お客様から、Java アプリケーションの最新化と、エンタープライズ レベルのプラットフォーム (Azure 上の Java) での実行を支援するように求めがあります。
Content: >-
  <p>Java は、エンタープライズ アプリケーションから複雑なロボットまですべてを作成するために 700 万を超える開発者によって使用される、最も一般的なプログラミング言語の 1 つです。 過去数年間、Java エコシステムが進化し、Spring などのオープンソース ツールとフレームワークの成長が加速してきました。 マイクロサービス アーキテクチャはますます普及し、開発者はコンテナーとマネージド サービスを使用してクラウド プラットフォーム上により多くのアプリケーションを構築しています。 Java エコシステムは複雑であり、エンタープライズ規模でクラウドで Java アプリケーションを実行するのは困難な場合があります。 お客様から、 <a href="https://azure.microsoft.com/en-us/develop/java/?ocid=AID3032702" target="_blank">Java</a> アプリケーションを最新化し、エンタープライズ レベルのプラットフォーム (Azure) で実行する支援を求めがあります。</p>


  <p>Spring Boot アプリケーションのマネージドターゲットとして VMware を使用した Azure Spring Cloud の開発から jClarity の取得、Microsoft Java エンジニアリング グループの作成まで、さまざまなお客様のワークロードをサポートするために、Java に多大な投資を行いました。 <a href="https://www.microsoft.com/openjdk" target="_blank">OpenJDK の Microsoft Build</a> では、Azure でサポートされる新しい Java ランタイム オプションが提供され、Azure で調整された最適化の可能性が提供されます。一般公開されました。 Red Hat、Oracle、IBM とのコラボレーションを通じて、Java Enterprise Edition および Jakarta Enterprise Edition アプリケーション サーバーの全範囲がサポートされ、<a href="https://aka.ms/jbosseap-blog-build2021" target="_blank">Red Hat JBoss Enterprise Application Platform (EAP)</a> と AZURE Virtual Machines 上の <a href="https://aka.ms/websphere-blog-build2021" target="_blank">IBM WebSphere</a> 向けオファーが新たにリリースされました。</p>


  <p>また、Microsoft は Java を広範囲に使用しています。 Java は会社としての成功にとって非常に重要であり、LinkedIn、SQL Server、Azure、Minecraft、Yammer などの最も戦略的な製品の一部を推進するのに役立ちます。 内部システム (お客様のワークロードを含め)ではなく、数十万台の Java 仮想マシン (JVM) を実稼働環境で実行しています。LinkedIn だけで、数千もの Java マイクロサービスが実稼働環境に用意されています。 Microsoft では、企業の Java ワークロードを内部と外部の両方で実行する専門知識を活用して、お客様のビジネスの変革を支援しています。</p>


  <p style="margin-left: 40px;">"クラウドへの移行について次のように話します。たとえば、サーキット のピストトップに引き込み、タイヤを変更する代わりに、エンジン全体を変更する必要があったとします<em>。また、この機能への切り替Microsoft Azure</em>、そのエンジンを文字通り一夜にして変更しました。"— Doug Wilson、<a href="https://mybuild.microsoft.com/sessions/db6c0213-d07f-4ee1-8d5c-26154d7632b6" target="_blank">Kroger</a>、ソフトウェア エンジニアリングのシニア ディレクター</p>


  <h2>好きなツールとフレームワークを使用して構築する</h2>


  <p>Azure では、統合された開発環境 (ID)、ビルド、自動化、継続的インテグレーションと継続的デリバリー (CI/CD)、およびソース コード管理 (SCM) 全体で Java ショップに人気のある DevOps ツールとのファーストクラスの統合が提供されます。 Azure Toolkits for IntelliJ と Eclipse を使用すると、IntelliJ、Eclipse、Visual Studio Code などのお気に入りの IDE から、高可用性でスケーラブルな Java アプリを簡単に作成、開発、構成、テスト、Azure にデプロイできます。 Maven および Gradle 用のプラグインを使用すると、Azure サービスをネイティブに構築して操作できます。また、GitHub Actions、Jenkins、Terraform を使用してワークフローとデプロイを自動化できます。</p><p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fee88c01-33aa-4445-9b07-984c06620b44.png"><img width="835" height="535" title="イメージ - ビルド" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" alt="Azure supports a wide range of developer tooling options for Java" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a75a5934-9ad7-4972-b99e-ea0431bf66d7.png" border="0"></a></p>


  <p style="text-align: center;"><em>Azure では、Java 用のさまざまな開発者ツール オプションがサポートされています。</em></p>


  <p>Microsoft は Java コミュニティに取り組み、Java 開発者エクスペリエンスを向上させるプロジェクトをサポートしています。 OpenJDK に直接貢献しました。ARM に Windows と macOS からのポートを実装し、Windows での Java ビルドを高速化するための機能強化に貢献し、Shenandoah ガベージ コレクターの開発を加速させるのに役立ちます。 Microsoft Build では、 <a href="https://aka.ms/openjdk-blog-build2021" target="_blank">OpenJDK の Microsoft Build</a> の一般提供を発表します。オープン ソースであり、だれでもどこでもデプロイできる、OpenJDK の無料の長期サポート (LTS) ディストリビューションです。</p>


  <p>また、360 万を超えるホスト型 Java リポジトリGitHub、オープン ソース Java プロジェクトのホームとして機能しているのも驚きではありません。 GitHub リポジトリで CI/CD とコード スキャン機能をサポートする無料のクラウド コンピューティング サイクルを提供するなど、Java 開発者が利用できるサポートとリソースのさらなる改善に取り組んでいます。これは、Adoptium、Apache、Eclipse Foundation、Red Hat、VMware などの組織のトップ Java プロジェクトの一部を強化するために役立っています。</p>


  <p style="margin-left: 40px;"><em>"Java、Tomcat、Docker コンテナー、Red Hat Enterprise Linux、SUSE Linux</em>、その他の多くのオープンソース ツールを DevTest Labs に取り込み、すべてがうまく機能します。"— Peter Rothlaender、クラウド ソリューションのマネージャー、<a href="https://customers.microsoft.com/en-us/story/daimler-manufacturing-azuredevtest" target="_blank">Of OfEr AG</a></p>


  <h2>フル マネージド サービスを使用した迅速な発送</h2>


  <p>組織と開発者は、インフラストラクチャの管理と構成ではなく、アプリケーションに集中したいと考えています。 コンテナー化されたアプリを実行する場合、Azure には、Azure Kubernetes Service および Azure Red Hat OpenShift (ARO) で最適な Kubernetes プラットフォームがあります。 また、Azure では、Azure App Service と Azure Spring Cloud の Spring で、Java Standard Edition、Tomcat、Red Hat JBoss EAP (プレビュー) など、主要なクラウド プラットフォームの Java 用のフル マネージドホスティング アプリケーションも提供されています。 イベント駆動型アーキテクチャの場合は、自動化された柔軟なスケーリングAzure Functionsを使用できます。 マネージド サービスは、使いやすさ、生産性の向上、総保有コストの削減を実現します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ac5fdc50-15cb-4685-907d-35b7f3b30bbc.png"><img width="953" height="615" title="Azure では、さまざまなマネージド コンピューティング先上のすべての Java サーバーとフレームワークがサポートされます" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" alt="Azure supports all Java servers and frameworks on a range of managed compute destinations" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3ad0bd6c-fbf5-407c-bf5c-c5cf9c7d6111.png" border="0"></a></p>


  <p style="text-align: center;"><em>Azure では、さまざまなマネージド コンピューティング先上のすべての Java サーバーとフレームワークがサポートされています。</em></p>


  <p><a href="https://azure.microsoft.com/en-us/services/spring-cloud/" target="_blank">Azure Spring Cloud</a> は、ビジネスを実行するアプリの構築と実行に集中できる、Spring Boot アプリのフル マネージド サービスです。 JARs またはコードをデプロイするだけで、Azure Spring Cloud Spring サービス ランタイムにアプリが自動的に接続されます。 デプロイ後は、アプリケーションのパフォーマンスを簡単に監視し、エラーを修正し、アプリケーションを迅速に改善できます。 これは、Azure エコシステムとエンタープライズ対応に統合されています。</p>


  <p><a href="https://azure.microsoft.com/en-us/services/app-service/" target="_blank">Azure App Service</a> 使用すると、Java Web アプリと API を使用して、迅速にビルド、デプロイ、スケーリングできます。 Maven プラグイン、コマンド ライン、または IDE を使用して、TOmcat または Red Hat JBoss EAP (プレビュー) に EAR、WAR、JAR ファイルをデプロイできます。 Azure App Serviceには、組み込みの CI/CD 統合と、デプロイ スロットを使用したダウンタイムなしデプロイが含まれます。 診断を使用してインテリジェントなトラブルシューティングをAzure App Service、診断と診断を使用してパフォーマンスAzure Monitor最適化Azure アプリ インサイト。 セキュリティで保護されたエンタープライズ アプリケーションホスティングは、さまざまなネットワーク機能またはシングルテナント サービスを使用してApp Service Environment。 既存の Tomcat Web アプリがある場合は、App Service Migration Assistant を使用して、それらを評価し、Azure App Service。</p>


  <p style="margin-left: 40px;"><em>"アプリの作成Azure Spring Cloud最小限のオーバーヘッドで</em>実行することを選択しました。"—Jonathan Jones、リード ソリューション アーキテクト、Group Finance IT、 <a href="https://customers.microsoft.com/en-us/story/1358540087031302788-swiss-re-accelerates-java-app-modernization-using-azure-spring-cloud" target="_blank">スイス Re</a></p>


  <h2>Java アプリケーションを簡単に拡張する</h2>


  <p>アプリケーションには、データベース、統合、セキュリティ、監視など、サポート サービスが必要です。 Azure には、Azure Database for PostgreSQL、Azure Database for MySQL、Azure Cosmos DB、Azure SQL Database など、さまざまなマネージド データベース オプションが用意Azure SQL Database。 Azure はハイパースケール PostgreSQL を提供する唯一のクラウドなので、お客様はデータベースをほぼ無限にスケーリングできます。 Connect、Azure Service Bus Java Message Service (JMS) のサポートと統合サービスを使用してアプリケーションをAPI Management。 データ インジェストの場合は、Event Hub または Event Grid。 アプリケーション パフォーマンス監視 (APM) を含む、Azure 上の Java ワークロードのフル マネージドのネイティブ監視機能を、Azure Monitor Application インサイト を通じて取得します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/dfb8e4f0-089a-4d9e-8a8f-55ead690073f.jpg"><img width="1916" height="931" title="Azure Spring Cloud Azure プラットフォーム サービス、セキュリティ、統合を使用した Azure 上の Java のリファレンス アーキテクチャ" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" alt="Azure Spring Cloud and Java on Azure reference architecture with common Azure platform services, security, and integration" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c09edf42-c295-4b44-a0e1-db91fd7940cc.jpg" border="0"></a></p>


  <p style="text-align: center;"><em>Azure Spring Cloud Azure プラットフォーム サービス、セキュリティ、統合を使用した Azure 上の Java リファレンス アーキテクチャ。</em></p>


  <p>企業のお客様と継続的に取り組み、スケーリング、セキュリティ、デプロイ、コストの要件など、お客様のニーズに集中します。 重要なテーマは、セキュリティ モデルのゼロ トラスト、エンドツーエンドの監視と監視、完全な自動化などです。 多くのお客様は、何千もの Java アプリケーションをオンプレミスで実行しています。 これらのアプリケーションをクラウドに移行する場合、IT 部門や規制機関の要件を満たす検証済みアーキテクチャが必要です。 多くのお客様の環境では、オンプレミスのシステム アーキテクチャから業界で定義されたセキュリティ制御とベンチマークへの直接マッピングも示す必要があります。</p>


  <p>azure <a href="https://docs.microsoft.com/en-us/azure/spring-cloud/reference-architecture" target="_blank">上の Azure Spring Cloud</a> と Java 用の最近リリースされた参照アーキテクチャを使用すると、さまざまなサポート サービスを使用してクラウドに Java アプリをデプロイする場合のエンタープライズのベスト プラクティスに簡単に従えるのが可能です。 強力な基盤から始め、ニーズの拡大に応じて機能を簡単に追加できます。</p>


  <p style="margin-left: 40px;"><em>"Azure Spring Cloud 参照<em></em></em>アーキテクチャの可用性により、アーキテクチャ オプションと Spring Cloud 機能セットを調査する内部サイクルが短縮され、グローバルに実装およびスケーリングする方法を迅速に決定できます。"—Devon Yost、Enterpriseアーキテクト、<a href="https://devblogs.microsoft.com/java/deploy-spring-boot-applications-by-leveraging-enterprise-best-practices/" target="_blank">Digital Realty Trust</a></p>


  <h2>強力なパートナー エコシステムの利点を活用する</h2>


  <p>Microsoft には、既存の Java ワークロードを Azure に取り込み、アプリケーションの機能を拡張するためのクラス最高のソリューションを提供する強力なパートナー エコシステムがあります。 共同開発とサポートを備えた独自のマネージド ホスティング オプションから、一般的な Linux ディストリビューション用の Azure Marketplace イメージまで、Java に重点を置くソリューションのポートフォリオを活用できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/758cf496-0086-438d-bf55-1085b20fe6d4.png"><img width="1024" height="206" title="" style="display: inline;" alt="Microsoft has a strong partner ecosystem that provides many options for building and running Java applications" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1d429439-9d07-415a-9905-f815ed2ce58f.png"></a></p>


  <p style="text-align: center;"><em>Microsoft には、Java アプリケーションを構築して実行するための多くのオプションを提供する強力なパートナー エコシステムがあります。</em></p>


  <p>お客様は、オンプレミスで実行されているミッション クリティカルな Java アプリケーションに多大な投資を行い、クラウドでこれらのアプリを実行するには、完全にサポートされている環境が必要です。 <a href="https://aka.ms/jbosseap-blog-build2021" target="_blank">Red Hat jBoss EAP on Red Hat</a> Enterprise Linux (RHEL) と <a href="https://aka.ms/websphere-blog-build2021" target="_blank">IBM WebSphere</a> (どちらも Azure VM 上で実行) に対する Azure Marketplace オファリングについて発表します。 Azure VM 上の Red Hat JBoss EAP には、RHEL に応じ、サブスクリプションの持ち込みや支払いなど、柔軟なライセンス オプションが含まれています。 これらのオファリングは、コンピューティング リソースのプロビジョニング、基本イメージのインストール、および構成オプションを提供するソリューション テンプレートとクイックスタートを提供します。 Red Hat JBoss EAP と IBM WebSphere が追加され、お客様は、最も広く使用されている Java エンタープライズ アプリケーション サーバーを Azure VM (Oracle WebLogic、IBM WebSphere、Red Hat JBoss EAP) にデプロイするための Azure Marketplace オファリングを選択できます。</p>


  <p>多くの Java 開発者は、キャッシュには Redis、ログ分析と監視機能には Elastic、アプリケーション アーキテクチャではイベント ストリーミング用の Kafka のようなサービスも使用しています。 Azure では、Redis Enterprise と Redis Enterprise Flash on Azure マネージド インフラストラクチャ、ELK ベースの監視とトラブルシューティングのための Elastic on Azure Marketplace、Azure と統合された Confluent Cloud と Azure portal および CLI の統合など、これらのサービスに固有のマネージド オファリングが提供されています。 マネージド インフラストラクチャとサポートの利点を追加して、Azure でお気に入りのサービスを使用し続けできます。</p>


  <p style="margin-left: 40px;">"Red Hat と Microsoft は、従来の Java アプリケーションをクラウドに移行する組織の選択肢と柔軟性を拡張する取り<em>組みです。Red Hat JBoss EAP on Azure では、組織がクラウドベースのアーキテクチャの利点を簡単に実現できるよう、完全に構成された共同でサポートされているソリューションが顧客に提供されます。Microsoft との長年の関係を</em>築き続け、共同顧客のサポートを拡大していけることを楽しみにしています。"—Rich Sharples、製品管理のシニア ディレクター – Application Services、<a href="https://azure.microsoft.com/en-us/overview/linux-on-azure/red-hat/" target="_blank">Red Hat</a></p>


  <h2>Azure での Java の概要</h2>


  <p>顧客と開発者は、ワークフローとプロセスを変更する必要のない、クラウドで Java アプリをシームレスに実行したいと考えています。 Azure のオープン プラットフォームには、広範な開発者ツールの統合、フル マネージドのコンピューティング、データベース、プラットフォーム サービス、および広範なパートナー オファリングが用意されています。 お客様が Azure 上の Java ですばらしいことを行っているのを見てきたので、引き続き Java 向けオファリングに投資し、エンタープライズ規模で Azure で Java アプリケーションを実行するサポートを追加します。</p>


  <p>詳細については、以下のリソースを使用して、Azure で Java アプリケーションの構築と実行を開始してください。 Azure エンジニアリング チームからの実践的な移行と最新化のサポートに関する広範なドキュメントと自習トレーニングを含む、あらゆる段階で利用できます。 何を構築するのか、ご覧ください。</p>


  <ul>
      <li>Azure 上の <a href="https://azure.microsoft.com/en-us/develop/java/?ocid=AID3032702" target="_blank">Java の詳細を確認してください</a>。</li>
      <li>自分のペースで進めるラーニング パスを<a href="https://docs.microsoft.com/en-us/learn/paths/java-on-azure/?ocid=AID3032702" target="_blank">Microsoft Learn。</a></li>
      <li>Java 開発者 <a href="https://docs.microsoft.com/en-us/azure/developer/java/?ocid=AID3032702" target="_blank">向けドキュメントを確認します</a>。</li>
      <li>詳細については、以下を <a href="https://azure.microsoft.com/en-us/migration/migration-program/?ocid=AID3032702" target="_blank">Azure 移行プログラム</a>。</li>
  </ul>


  <hr>

  <p><em>Azure。目的を持って発明する。</em></p>
