### YamlMime:Yaml
ms.openlocfilehash: 861cc3ee8e7e7608d621d3411f535162125127a4
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903699"
Slug: azure-monitor-for-containers-with-prometheus-now-in-preview
Title: 現在プレビュー中の Prometheus でのコンテナーの Azure Monitor
Summary: Prometheus は、広く普及しているオープンソースのメトリック監視ソリューションであり、クラウドネイティブコンピューティングファンデーションに含まれています。 多くのお客様は、Prometheus で Kubernetes に提供されている広範なメトリックを利用しています。
Content: >-
  <p><a href="https://prometheus.io/" target="_blank">Prometheus</a> は、広く普及しているオープンソースのメトリック監視ソリューションであり、 <a href="https://www.cncf.io/" target="_blank">クラウドネイティブコンピューティングファンデーション</a>に含まれています。 Kubernetes で提供される広範なメトリックを希望する多くのお客様がいます。 ただし、<a href="https://docs.microsoft.com/en-us/azure/monitoring/monitoring-container-health" target="_blank">コンテナーの Azure Monitor</a>を簡単に使用することもできます。これにより、Azure Kubernetes SERVICE (AKS) クラスターを完全に管理し、すぐに<a href="https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-overview">使用できるよう</a>になります。 ここでは、Prometheus データをじょうごするための要求を Azure Monitor に送信しています。ここでは、コンテナーの Azure Monitor との Prometheus 統合がプレビュー段階にあり、2つの長所を組み合わせています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2e90a2c0-7b52-45a7-b101-1c4815e2273c.png"><img alt="Flowchart illistrating how Promethues endpoints integrate with Azure Monitor for containers" border="0" height="307" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/adc3360f-3bfb-439c-90e8-7f2d6f28098b.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="フローチャート illistrating Promethues エンドポイントをコンテナーの Azure Monitor と統合する方法" width="880"></a></p>


  <p>通常、Prometheus を使用するには、データベースを使用して Prometheus サーバーを設定し、管理する必要があります。 Azure Monitor 統合では、Prometheus サーバーは必要ありません。 また、エクスポーターまたはポッド (アプリケーション) を介して Prometheus エンドポイントを公開する必要があります。コンテナーの Azure Monitor のコンテナー化されたエージェントは、メトリックをスクラップことができます。 Azure Monitor で Prometheus メトリックを収集するためのシームレスなオンボードエクスペリエンスが提供されています。 次の例は、kube の一部である coredns メトリックがログの Azure Monitor に収集される方法を示しています。&nbsp;</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/401e4e7e-d3e5-4bcb-b3b9-3399ab2a0434.png"><img alt="Screenshot example of how the coredns metrics is collected into Azure Monitor for logs" border="0" height="183" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/699f0f61-6b0b-47de-af1d-c3b90021bc43.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="ログの Azure Monitor に coredns メトリックが収集される方法のスクリーンショットの例" width="1355"></a></p>


  <p>Prometheus SDK をアプリケーションにインストルメント化することで、コンテナーからワークロードメトリックを収集することもできます。 次の例は、 <strong>prommetrics_demo_requests_counter</strong>のコレクションを示しています。 URL、エンドポイント、またはポッド注釈を使用して、ワークロードメトリックを収集することもできます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/57d50ef9-c134-4732-b742-9d9540af0985.png"><img alt="Screenshot example showing the collection of the prommetrics_demo_requests_counter" border="0" height="157" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0c191334-07c7-4d64-9c5c-7141302c2f4b.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="Prommetrics_demo_requests_counter のコレクションを示すスクリーンショットの例" width="1390"></a></p>


  <h2>コンテナーの Azure Monitor を使用したフルスタック監視</h2>


  <p>では、以前に追加されたストレージとネットワークパフォーマンスメトリックを含めて、他のメトリックに Prometheus のメトリックがどのように適合しているかを示しています。これには、Azure Monitor が既に提供しています。 メトリックがすべてどのようになっているかを確認できます。 コンテナーの Azure Monitor には、プラットフォーム、コンテナー、orchestrator レベル、およびワークロードレベルの範囲内で、すぐに使用できるテレメトリが用意されています。 Prometheus の追加のワークロードメトリックを使用して、コンテナーの Azure Monitor で Azure Kubernetes Services (AKS) の完全なスタック、エンドツーエンドの監視ビューを取得できるようになりました。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cbbc0570-e10c-425f-ab4c-d46ac1e31d49.png"><img alt="Image of table showing how Prometheus telemetry fits in with other metrics" border="0" height="339" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cfec160a-b003-45b0-87d3-bf54ac26bc5f.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="Prometheus テレメトリが他のメトリックにどのように適合するかを示す表の画像" width="1180"></a></p>


  <h2>Azure ダッシュボードとアラートでの Prometheus メトリックの視覚化</h2>


  <p>メトリックが Azure Monitor ログに格納されたら、Kusto クエリ言語 (KQL) で Log Analytics を使用してメトリックに対してクエリを実行できます。 ここで &rsquo; は、Prometheus SDK をインストルメント化するサンプルクエリについて説明します。 &nbsp; Azure portal のクエリを使用して、結果をすばやくプロットできます。</p>


  <pre>

  &lt;Queries&gt;

  InsightsMetrics

  | where Name == &quot;prommetrics_demo_requests_counter_total&quot;

  | extend dimensions=parse_json(Tags)

  | extend request_status = tostring(dimensions.request_status)

  | where request_status == &quot;bad&quot;

  | where TimeGenerated &gt; todatetime(&#39;2019-07-02T09:40:00.000&#39;)

  | where TimeGenerated &lt; todatetime(&#39;2019-07-02T09:54:00.000&#39;)

  | project request_status, Val, TimeGenerated | render timechart</pre>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7f0c2588-8637-4d11-9fcc-78d580bed27d.png"><img alt="Screenshot example of plotting results in Azure portal for a query that uses the embedded Prometheus library" border="0" height="651" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e6965b89-7451-42c1-abd9-e00b916a543a.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="埋め込み Prometheus ライブラリを使用するクエリの結果を Azure portal にプロットするスクリーンショットの例" width="1307"></a></p>


  <p>Azure ダッシュボードにグラフをピン留めし、カスタマイズした独自のダッシュボードを作成することができます。 <a href="https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-analyze#view-performance-directly-from-an-aks-cluster" target="_blank">コンテナークラスタービューの Azure Monitor</a>から、現在のポッドおよびノードグラフをダッシュボードにピン留めすることもできます。</p>


  <p><img alt="Screenshot example of pinning query result charts to the Azure or customized dashboards" border="0" height="781" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e63bd58f-b746-463b-a9ef-0b58ba53b84a.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="Azure またはカスタマイズされたダッシュボードにクエリ結果グラフをピン留めするスクリーンショットの例" width="1140"></p>


  <p>Prometheus メトリックに対してアラートを生成する場合は、 <a href="https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-alerts" target="_blank">Azure のアラート</a>を使用します。&nbsp;</p>


  <p>これは私たちの画期的な統合で、Kubernetes の監視についてお客様を支援する努力を続けています。 Prometheus データを収集するようにエージェントを構成する方法、コンテナーの Azure Monitor データをクエリして使用する方法の詳細については、microsoft の <a href="https://aka.ms/ci-prom" target="_blank">ドキュメント</a>を参照してください。 Prometheus は、豊富で広範なテレメトリを提供しています。ここで &rsquo; は、取り込まれたログ Azure Monitor に prometheus からのデータを示す <a href="https://aka.ms/ci-prom-usage" target="_blank">クエリ</a> を紹介します。</p>


  <p>Prometheus で利用可能なメトリックについては、 <a href="https://prometheus.io/" target="_blank">Prometheus の web サイト</a>を参照してください。</p>


  <p>フィードバックや提案については、 <a href="https://azure.microsoft.com/en-us/support/community/?product=monitor" target="_blank">テクニカルフォーラム</a> または <a href="https://aka.ms/ci-forums" target="_blank">stackoverflow</a>を通じてご連絡ください。</p>
