### YamlMime:Yaml
ms.openlocfilehash: c8f8cf205df0762f4a42a3969d25917dc9bae5a3
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909070"
Slug: azure-web-application-firewall-waf-generally-available
Title: Azure Web Application Firewall (WAF) の一般提供
Summary: 昨年 9 月の Ignite では、レイヤー 7 のサービスに Web Application Firewallを追加することで、Web アプリケーションのセキュリティを向上Azure Application Gatewayしました。 現在、General...
Content: >-
  <p>昨年 9 月の Ignite では、 <a href="https://azure.microsoft.com/en-us/services/application-gateway/">レイヤー 7 の</a> サービスに Web Application Firewallを追加することで、Web アプリケーションのセキュリティを強化するAzure Application Gatewayしました。 現在、すべての Azure パブリック リージョンでWeb Application Firewallの一般提供を発表します。</p>


  <p>Web アプリケーションは、一般的な既知の脆弱性 (SQL インジェクション攻撃やクロスサイト スクリプティング攻撃など) を悪用する悪意のある攻撃のターゲットとしてますます増加しています。 アプリケーションこのような悪用を防ぐことは困難な場合があり、厳格な保守、パッチの適用、アプリケーション トポロジの複数のレイヤーの監視が必要になることもあります。 一元化された Web アプリケーション ファイアウォール (WAF) は、Web 攻撃から保護し、アプリケーションの変更を必要とせずにセキュリティ管理を簡素化します。 アプリケーション管理者とコンプライアンス管理者は、脅威や侵入に対する保証を強化します。</p>


  <p>Azure Application Gatewayは、SSL ターミネーション、真ラウンド ロビン負荷分散、Cookie ベースのセッション アフィニティ、マルチサイト ホスティング、URL パス ベースのルーティングなど、アプリケーション配信コントローラー (ADC) レイヤー 7 のネットワーク サービス オファリング機能です。 Application Gateway SSL ポリシー制御とエンド エンド SSL 暗号化が提供され、アプリケーションのセキュリティ強化が向上します。 これらの機能を使用すると、バックエンド アプリケーションはコア ビジネス ロジックに集中しながら、コストの高い暗号化/暗号化解除、SSL ポリシー、および負荷分散を Application Gateway。 Web Application Firewall&rsquo; Application Gateway コア オファリングと統合することで、Open Web Application Security Project (OWASP) の上位 <a href="https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project">10</a> 件の脆弱性によって特定される、最も一般的な Web 脆弱性の多くから保護するアプリケーションのセキュリティ ポートフォリオと体制がさらに強化されます。 Application Gateway WAF には、これらの脆弱性の多くに対するベースライン セキュリティを提供する OWASP ModSecurity Core ルール セット (3.0 または 2.2.9) が事前構成されています。 簡単な構成と管理により、WAF Application Gateway豊富なログ機能と選択的ルールの有効化が提供されます。</p>


  <h2>メリット</h2>


  <p>次に示すのは、次のような主な利点Web Application Firewallです。</p>


  <h3>保護</h3>


  <ul>
   <li>バックエンド コードを変更することなく、Web の脆弱性や攻撃からアプリケーションを保護します。 WAF は、次を含むさまざまな攻撃カテゴリに対応します。 <ul>
    <li>SQL インジェクション</li>
    <li>クロス サイト スクリプティング</li>
    <li>コマンド インジェクション、HTTP 要求のスモグリング、HTTP 応答の分割、リモート ファイル インクルード攻撃などの一般的な攻撃</li>
    <li>HTTP プロトコル違反</li>
    <li>HTTP プロトコルの異常</li>
    <li>ボット、クローラー、スキャナー</li>
    <li>一般的なアプリケーションの構成ミス (Apache、IIS など)</li>
    <li>HTTP サービス拒否</li>
   </ul>
   </li>
   <li>複数の Web アプリケーションを同時に保護する。 Application Gatewayは、1 つのゲートウェイの背後で最大 20 の Web サイトをホストできます。これは、すべて Web 攻撃から保護できます。</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fb10e181-7a4d-4ceb-98ab-45ac18906291.png"><img alt="WAF - App Gateway" border="0" height="300" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5e08781c-806a-4b83-b75c-3e59b508ff4f.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="WAF - App Gateway" width="490"></a></p>


  <h3>使いやすさ</h3>


  <ul>
   <li>Application Gateway WAF は、Azure Portal と REST API を使用して簡単に構成、デプロイ、管理できます。 PowerShell と CLI は間もなく使用できる予定です。</li>
   <li>管理者は WAF ルールを一中心に管理できます。</li>
   <li>既存の Application Gateway は、WAF を含む単にアップグレードできます。 WAF では、すべての標準のApplication Gatewayに加えて、すべての標準機能が保持Web Application Firewall。</li>
  </ul>


  <h3>監視</h3>


  <ul>
   <li>Application Gateway WAF には、 <a href="https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-overview">waF</a> アラートを追跡し、傾向を簡単に監視するために Azure Monitor と統合されたリアルタイム WAF ログを使用して、Web アプリケーションを攻撃から監視する機能が備わっています。 JSON 形式のログは、顧客のストレージ アカウントに&rsquo;直接送信されます。 お客様は、これらのログを完全に制御し、独自の保持ポリシーを適用できます。 お客様は、これらのログを独自の分析システムに取り込むすることもできます。 WAF ログは <a href="https://www.microsoft.com/en-us/cloud-platform/operations-management-suite">Operations Management Suite (OMS)</a> と統合されています。そのため、お客様は OMS ログ分析を使用して、高度なきめ細かいクエリを実行できます。</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/aad23373-ed3a-46a1-a36c-982e250e17ee.png"><img alt="WAF - Access Log" border="0" height="310" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1701f816-3793-4ac2-8fbd-0fe84783cd89.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="WAF - アクセス ログ" width="440"></a></p>


  <ul>
   <li>Application Gateway WAF は、すべての Azure リソースの一元的な<a href="https://azure.microsoft.com/en-us/services/security-center/"></a>セキュリティ ビューを提供Azure Security Centerと統合されます。 Azure Security Centerをスキャンして脆弱性を検出し、検出された問題の軽減手順を推奨します。 このような脆弱性の 1 つは、WAF によって保護されていない Web アプリケーションの存在です。</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5d9e369f-c560-4230-95c3-f5913aa53793.png"><img alt="WAF - 1" border="0" height="240" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3a6e5777-1895-4250-905e-16ddf1a365a8.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="WAF - 1" width="569"></a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6c262667-d63b-48c3-b52e-e451c485af1e.png"><img alt="WAF - 2" border="0" height="268" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2f16c1e8-0163-4be5-a834-a1186c2f5dc0.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="WAF - 2" width="569"></a></p>


  <h3>カスタマイズ</h3>


  <ul>
   <li>Application Gateway の WAF は検出モードや保護モードで実行できます。 管理者が検出モードで実行する一般的な用途は、悪意のあるパターンがないかどうかトラフィックを監視することです。 潜在的な悪用が検出されたら、保護モードに切り替えて疑わしい着信トラフィックをブロックします。</li>
   <li>お客様は WAF RuleGroups をカスタマイズして、広範なカテゴリまたはサブカテゴリの攻撃を有効/無効にできます。 そのため、管理者は、挿入またはクロス サイト スクリプティング (XSS) SQL RuleGroups を有効または無効にできます。 お客様は、RuleGroup 内の特定のルールを有効または無効にすることもできます。 たとえば、プロトコル異常ルール グループは、選択的に有効または無効にできる多くのルールのコレクションです。</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7a7795ab-1e4e-41f3-89fb-a59a62f3eee0.png"><img alt="WAF - 3" border="0" height="389" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1db5fa79-b6ea-430c-b4ea-23e3d049090d.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="WAF - 3" width="549"></a></p>


  <h2>オープン ソースの受け入れ</h2>


  <p>Application Gateway WAF では、最も一般的な WAF &ndash;&nbsp; デプロイ <a href="https://www.modsecurity.org/crs/">の OWASP ModSecurity Core ルール</a> セットの 1 つを使用して、最も一般的な Web の脆弱性から保護します。 厳格な標準に準拠するこれらの規則は、オープン ソース コミュニティによって管理および管理されます。 お客様は、ルール セット CRS 2.2.9 と CRS 3.0 を選択できます。 CRS 3.0 では偽陽性が大幅に減少します。CRS 3.0 を使用することをお勧めします。</p>


  <h2>まとめと次のステップ</h2>


  <p>ADC セキュリティ サービスWeb Application Firewallの一般提供は、Application Gateway重要なマイルストーンです。 引き続き、フィードバックに基づいて WAF 機能セットを強化します。 ポータルまたは ARM Application Gateway Web Application Firewallを使用して、今すぐお試しください。 詳細情報と詳細なドキュメント リンクを以下に示します。</p>


  <ul>
   <li><a href="https://azure.microsoft.com/en-us/pricing/details/application-gateway/">Application Gateway WAF の価格</a></li>
   <li>WAF <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-web-application-firewall-overview">の使用に</a> 関するApplication Gateway詳細</li>
   <li><a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-crs-rulegroups-rules">WAF ルール スキーマと RuleGroup/Rules の包括的な一覧</a></li>
   <li>作成とカスタマイズのための <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-web-application-firewall-portal">ステップ バイ ステップ</a> <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-customize-waf-rules-portal">ガイド</a></li>
   <li><a href="https://github.com/Azure/azure-quickstart-templates/tree/master/101-application-gateway-waf/">ARM テンプレートによるデプロイ</a></li>
   <li><a href="https://docs.microsoft.com/en-us/rest/api/applicationgateway/">ARM API</a></li>
   <li>PowerShell と CLI のサポートは間もなく利用可能になる予定です</li>
  </ul>
