### YamlMime:Yaml
ms.openlocfilehash: cd9112e6e816f085715aa8807a6cd6686ccdafce
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889581"
Slug: azure-security-center-and-microsoft-web-application-firewall-integration
Title: Azure Security Centerと Microsoft Web Application Firewall 統合
Summary: Web アプリケーションは、クロスサイト スクリプティング、クロスサイト インジェクション、アプリケーション DDoS などの攻撃SQLターゲットになりつながっています。 Microsoft Web Application Firewall (WAF) と Azure Security Center (ASC) は、このような脆弱性から Web アプリケーションをセキュリティで保護するのに役立ちます。
Content: >-
  <p>Web アプリケーションは、クロスサイト スクリプティング、クロスサイト インジェクション、アプリケーション DDoS などの攻撃SQLターゲットになっています。 OWASP は、このような攻撃に対してより抵抗力のあるアプリケーションを作成する方法に関するガイダンスを提供しますが、アプリケーション トポロジの複数のレイヤーで厳格なメンテナンスと修正プログラムを適用する必要があります。 Microsoft <a href="https://docs.microsoft.com/azure/application-gateway/application-gateway-web-application-firewall-overview" target="_blank">Web Application Firewall (WAF)</a> と <a href="https://azure.microsoft.com/en-us/services/security-center/" target="_blank">Azure Security Center (ASC)</a> は、このような脆弱性から Web アプリケーションをセキュリティで保護するのに役立ちます。</p>


  <p>Microsoft WAF は、OWASP <a href="https://docs.microsoft.com/azure/application-gateway/application-gateway-introduction" target="_blank">コア ルール セット</a> を使用して Web アプリケーションを一般的な Web 悪用から保護する Azure Application Gateway (レイヤー 7 ロード バランサー) の <a href="https://www.owasp.org/index.php/Category:OWASP_ModSecurity_Core_Rule_Set_Project" target="_blank">機能です</a>。 Azure Security Center Azure リソースの脆弱性をスキャンし、それらの問題の軽減手順を推奨します。 このような脆弱性の 1 つは、WAF によって保護されていない Web アプリケーションの存在です。 現在、Azure Security Center受信 Web ポート (80 と 443) が開いているネットワーク セキュリティ グループが関連付けられているパブリック接続の IPs に対して WAF デプロイを推奨しています。 Azure Security Center既存の Azure リソースへの <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-integration-security-center" target="_blank">アプリケーション ゲートウェイ WAF</a> のプロビジョニングと、既存の Web アプリケーション ファイアウォールへの新しいリソースの追加が提供されます。 WAF と統合することで、Azure Security Centerログを分析し、重要なセキュリティ アラートを表示できます。</p>


  <p>場合によっては、セキュリティ管理者に Azure Security Center から WAF をプロビジョニングするためのリソースアクセス許可が付与されていない場合や、アプリケーション所有者がアプリのデプロイの一環として WAF を既に構成している場合があります。 これらのシナリオに対応するために、Security Center では、Security Center を使用してプロビジョニングされていないサブスクリプション内の WA Security Center F インスタンスが間もなく自動的に検出される予定です。 以前にプロビジョニングされた WAF インスタンスは、検出されたソリューションの下の Security Center セキュリティ ソリューション ペインに表示されます。このウィンドウでは、セキュリティ管理者がそれらを Azure Security Center と統合できます。 既存の Microsoft WAF デプロイを接続すると、WAF のプロビジョニング方法に関係なく、Security Center検出を利用できます。 カスタム ファイアウォール規則セットなどの追加の構成設定は、WAF コンソールで使用できます。この設定は、カスタム ファイアウォール規則から直接Security Center。 <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-web-application-firewall-portal">Microsoft WAF の構成に関するこの記事では</a>、プロビジョニング プロセスに関するより多くのガイダンスを提供できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8a165976-3bc4-452d-886d-2b33a3e6624e.png"><img alt="ASC_WAF_Blog_picture" border="0" height="493" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/72d8b75f-b9af-4809-ad51-99aa93267843.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="ASC_WAF_Blog_picture" width="925"></a></p>


  <p>ご意見をお寄せください。 提案や質問がある場合は、投稿の下部にコメントを残するか、 に問い合わせください <a href="mailto:ascpartnerssupport@microsoft.com">ascpartnerssupport@microsoft.com</a>。</p>


  <p>詳細については、次のAzure Security Center。</p>


  <p style="margin-left: 40px;"><a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-intro" target="_blank">次のAzure Security Center</a></p>


  <p style="margin-left: 40px;"><a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-faq" target="_blank">Azure Security Center のよく寄せられる質問 (FAQ)</a>。</p>
