### YamlMime:Yaml
ms.openlocfilehash: 59c71d650bdb86e3b15f11849d6b01152ec34d89
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139896122"
Slug: best-practices-in-migrating-sap-applications-to-azure-part-3
Title: SAP アプリケーションを Azure に移行する場合のベスト プラクティス – パート 3
Summary: これは、SAP を Azure に移行するベスト プラクティスに関する 3 部構成のブログ投稿シリーズの 3 番目のブログです。
Content: >-
  <p><em>これは、SAP を Azure に移行するベスト プラクティスに関する 3 部構成のブログ投稿シリーズの 3 番目のブログです。</em></p>


  <h2>HANA 上の BW と Azure 上の BW/4HANA</h2>


  <p>SAP のお客様&rsquo; の多くは、クラウドへの移行に関する魅力的SAP HANA、次の 2 つの要因によって駆動されています。</p>


  <ul>
   <li>エンド オブ ライフ 第 1 世代SAP HANA、お客様がプラットフォームを再評価する原因となっているアプライアンスです。</li>
   <li>従来のデータベースと後の BW/4HANA に対する柔軟な TDI モデルでの SAP Business Warehouse (BW) on HANA の早期価値提案を利用する希望。</li>
  </ul>


  <p>その結果、SAP HANA から Microsoft Azure への初期移行の多くでは、bw ワークロードに対して SAP HANA&rsquo; のメモリ内機能を利用するために SAP BW に重点が置かれがありました。 つまり、データベースレイヤーで SAP HANA を利用するために BW アプリケーションを移行し、最終的には HANA 上の BW を BW/4HANA に移行する必要があります。</p>


  <p>移行の一環として使用される SUM のシステム移動オプションを使用した SAP <a href="https://vimeo.com/user21884330/review/78267156/e0caac1dde" target="_blank">Database Migration Option (DMO)</a> を使用すると、お客様は、オンプレミスのソース システムから、または Microsoft Azure に存在するターゲット システムへの単一の手順で移行を実行し、全体的なダウンタイムを最小限に抑えることができます。</p>


  <p>S/4HANA の例と同様に、同僚の Marshal &ldquo;は、SAP アプリケーションを Azure &ndash; パート 2 に移行する際のベスト プラクティスで使用しました。つまり、AnyDB 上の従来の BW を顧客のデータセンターから HANA 上の BW に移行すると、最終的には 2&rdquo; つの手順で BW/4HANA が実現されます。 ハイパースケールとグローバルな展開により、Microsoft Azure投資を最小限に抑えながら、移行を柔軟に完了できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b6ae9213-46bb-4c5e-b345-983f0fd0a1a2.png"><img alt="SAP BW on HANA and BW 4HANA migrations" border="0" height="1022" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0a207642-99ce-4e47-8797-0b04c20bfde9.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="SAP BW HANA と BW 4HANA の移行に関するページ" width="1837"></a></p>


  <p align="center"><em>図 1: HANA SAP BW BW/4HANA の移行に関する説明</em></p>


  <h3>手順 1</h3>


  <p>最初の手順は、AnyDB 上の SAP BW を HANA 上SAP BWに移行し、Microsoft Azure。 仕事仲間の Bartosz Jarkowski は、<a href="https://blogs.sap.com/2017/10/05/your-sap-on-azure-part-2-dmo-with-system-move/" target="_blank">SAPs&rsquo; Software Update Manager (SUM)</a> のデータベース移行オプション (DMO) について説明する優れたブログを書いています。</p>


  <p>この移行手順は、SAP HANA を実行するターゲット サーバーとして、認定およびサポートされている <a href="https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/iaas.html#categories=Microsoft%20Azure" target="_blank">SAP HANA &ndash; ハードウェア ディレクトリ IaaS</a> プラットフォームに記載されている HANA 認定 SKU のいずれかを使用して実行できます。</p>


  <p><strong>Microsoft Azure</strong>では、OLTP および OLAP シナリオ全体で 12 の専用ハードウェア オプションを含む、192 GiB から 20 TiB RAM までの、任意のハイパースケール クラウド プロバイダーの HANA 認定 SKU の中で最も多くの選択肢が提供されています。</p>


  <p>お客様が SAP HANA OLAP スケールアウト構成を選択した場合、Azure では、TDIv4 では <a href="https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/iaas.html#categories=Microsoft%20Azure%23OLAP%2FOLTP%23OLAP%23OLTP&amp;recordid=1983" target="_blank">最大 60 TiB</a> 、TDIv5 認定では最大 <a href="https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/iaas.html#categories=Microsoft%20Azure&amp;recordid=1984" target="_blank">120 TB</a> の認定オプションが提供されます。</p>


  <p>Azure の SAP HANAのお客様の多くは、Azure で BW on HANA への DMO 移行を実行することで、BW/4HANA への移行の 1 歩を既に踏み出しています。 これは、仮想マシンや HANA Large Instance 専用ハードウェア上にある場合があるスケールアウト シナリオに似ています。</p>


  <p>この最初の手順により、お客様はネットワーク、仮想マシン、ストレージなどのクラウド インフラストラクチャを準備できました。 また、バックアップ/復元、データの階層化、高可用性、ディザスター リカバリー Microsoft Azureの運用機能とサポート モデルを有効にするのにも役立ちます。</p>


  <h3>手順 2</h3>


  <p>お客様が Azure SAP BW HANA を使用すると、ハイパースケール クラウドの柔軟性の真の利点が実現し始めるのです。 BW/4HANA 移行演習は繰り返しテストできます。必要に応じて並列で実行できます。一方、使用した分だけ支払うのに対して、移行レシピが完全に完了し、実稼働環境に対して実行する準備ができたら、それを捨ててみることができます。</p>


  <h2>最適なSAP HANAを実行Microsoft Azure</h2>


  <p>SAP BW Microsoft Azure で実行される HANA および BW/4HANA のシナリオに関する一般的な機能は、次のような IaaS サービスの組み合わせによって有効になります。</p>


  <ul>
   <li>高パフォーマンスの Azure Virtual Machines</li>
   <li>Azure Premium Storage</li>
   <li>Azure Accelerated Networking</li>
  </ul>


  <p>これらの非常に柔軟でパフォーマンスの高い仮想マシン (VM) は、お客様が SAP HANA ワークロードをすばやく起動し、n+0 スケールアウト構成用のインフラストラクチャをデプロイする機能を提供します。 さらに、Azure では、専用のスケールアウト シナリオを使用して OLAP ワークロードをスケーリングする機能を、専用の専用の SAP HANA を提供しています。</p>


  <p>これらの HANA Large Instance の構成では、お客様は N+1&rdquo; SAP HANA&ldquo;をインストールします。これは通常、次の意味を持っています。</p>


  <ul>
   <li>1 つのマスター ノード</li>
   <li>N ワーカー ノード</li>
   <li>1 スタンバイ ノード (省略可能)</li>
  </ul>


  <p>50 以上のワーカー ノードを含むスケールアウト構成は存在しますが、実質的にスケールアウト構成の大部分は 3 から 15 ノードの範囲になります。</p>


  <h2>この動作は、次のMicrosoft Azure。</h2>


  <p>パフォーマンスと使用可能なインフラストラクチャを確保するために、Microsoft と SAP&rsquo; の両方のガイダンスに従って、vm シナリオで Azure インフラストラクチャを利用して、SAP HANA のコンピューティング、ネットワーク、ストレージを設計することが重要です。</p>


  <ul>
   <li>可用性セット</li>
   <li>高速ネットワーク</li>
   <li>Azure 仮想ネットワーク</li>
  </ul>


  <p>HANA Large Instance シナリオでは、専用の共有 NFS ストレージとスナップショットを使用することで、スタンバイ ノードを使用してスケールアウトできます。 追加のオーバーヘッドを最小限に抑え、BW システムの可用性を確保します。</p>


  <h3>ネットワーク</h3>


  <p>SAP HANAを使用するスケールアウト構成では、SAP HANA クライアント トラフィック、SAP HANA ノード内通信、および SAP HANA ストレージ通信 (NFS) を分離して予測パフォーマンスを確保するために、3 つの異なるネットワーク ゾーンが必要です。 次に示すのは、上記の概念を示すスタンバイ ノード (1+6+1) を備えたサンプル 8 ノード SAP HANA システムの図です。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/17fcf960-18eb-4f72-bd42-faa7df904ce0.png"><img alt="SAP HANA scale-out client, intranode and storage network zones" border="0" height="505" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/dbef23f1-f84a-4812-be3c-59d49b290000.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="SAP HANA、ノード内、およびストレージ ネットワーク ゾーンのスケールアウト" width="2133"></a></p>


  <p align="center"><em>図 2: SAP HANA、ノード内、およびストレージ ネットワーク ゾーンの構成</em></p>


  <p>次の手順に合った設計を行う場合は、SAP で推奨される TDI プラクティスに従SAP HANA。</p>


  <ul>
   <li>割り当てられた RAM に比例した適切でパフォーマンスの高いストレージ。</li>
   <li>HANA Large Instances での n+1 構成の場合に適切なフェールオーバー操作を確保するために、NFS 共有ストレージの構成を修正します。</li>
   <li>ネットワーク トラフィックをクライアントゾーンとノード内ゾーンに分離する個別のネットワーク ゾーン。</li>
  </ul>


  <p>これらの定義済みの HANA Large Instances コンピューティング SKU (SAP Tailored Datacenter Initiative v4 仕様 (TDIv4 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-available-skus" target="_blank">) に</a> 従った適切なストレージ構成を含む) は、事前に設計され、必要に応じて顧客が使用できる状態です。 これらの SKU は、顧客固有のサイズ設定から生じる特定のニーズに適応できます。</p>


  <h3>Storage</h3>


  <p>SAP HANAモデルの Large Instance スケールアウト構成では、高パフォーマンスの NFS 共有ストレージを使用して、スタンバイ ノードが障害が発生したノードを引き継ぐ機能を有効にします。</p>


  <p>Azure HANA Large Instances の TDI スケールアウト構成では、SAP HANA インストール用に少なくとも 4 種類の共有ファイルシステムが設定されます。</p>


  <table border="1" cellpadding="0" cellspacing="0">
   <tbody>
    <tr>
     <td valign="top" width="174">
     <p><b>共有ファイル システム</b></p>
     </td>
     <td valign="top" width="310">
     <p><b>説明</b></p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="174">
     <p>/usr/sap/SID</p>
     </td>
     <td valign="top" width="310">
     <p>IO パフォーマンスの要件が低い</p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="174">
     <p>/hana/shared/SID</p>
     </td>
     <td valign="top" width="310">
     <p>IO パフォーマンスの要件が低い</p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="174">
     <p>/hana/data/SID/mnt0000*</p>
     </td>
     <td valign="top" width="310">
     <p>中/高 IO パフォーマンスの要件</p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="174">
     <p>/hana/log/SID/mnt0000*</p>
     </td>
     <td valign="top" width="310">
     <p>中/高 IO パフォーマンスの要件</p>
     </td>
    </tr>
   </tbody>
  </table>


  <p><em>HANA データファイル システムとログ ファイル システムの数と名前は、使用されているスケールアウト ノードの数と一致します(下図)。</em></p>


  <p>スケールアウト構成で適切な SAP HANA 操作を実行するために必要なファイルシステムは他にありませんが、これらの 4 つのファイルシステムは、高パフォーマンスの IO 特性を提供し、スケールアウト構成内のすべてのノードで共有する機能を提供するために必要です。</p>


  <p>次の例は、HANA&rsquo; スケールアウトの 8 つの Azure HANA Large Instance ユニットを示しています。各ユニットでは、HANA ファイルシステムがプロビジョニングされている他のすべてのユニットを確認できます。最も重要な HANA ボリュームとログ ボリュームは、各ユニットが、NFS v4 ロックによって適用される独自のデータおよびログ ファイルシステムの読み取り/書き込みを制御できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/aca9c501-3087-405e-9208-886f7de2c6d1.png"><img alt="SAP HANA scale-out filesystem on Microsoft Azure HANA Large Instances" border="0" height="776" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ae0c944f-dfff-4ff2-9d88-4372dec64fa0.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="SAP HANA HANA Large Instances でスケールMicrosoft Azureファイル システムを作成する" width="2141"></a></p>


  <p align="center"><em>図 2: SAP HANA HANA Large Instances 上のスケールMicrosoft Azureファイル システム</em></p>


  <p>障害が発生した場合、SAP HANA&rsquo;&rsquo; スタンバイ ノードは、そのノード ストレージの所有権を引き継ぎ、ノードが運用スケールアウト HANA システムに配置されたと想定します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f2cd6b16-fb9d-4833-91eb-9f9b97c1ccde.png"><img alt="SAP HANA standby bode taking ownership of a failed node's storage" border="0" height="773" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b5460226-62a4-4992-84fa-d0e91ade5730.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="SAP HANAノードのストレージの所有権を取得するスタンバイ ノードを作成する" width="2123"></a></p>


  <p align="center"><em>図 3: SAP HANAノード ストレージの所有権を取得するスタンバイ ノードの&rsquo;作成</em></p>


  <p>SAP HANAのスタンバイ ノード機能により、Microsoft Azure を実行するプラットフォームとして Microsoft Azure を選択すると、パフォーマンスと可用性の組み合わせに対するSAP HANA。</p>


  <p>これらのソリューションの詳細を確認し、オファリングのハンズオン デモを見る場合は、 <a href="https://aka.ms/SAPSAPPHIRENOW2019" target="_blank">MICROSOFT の</a> ブース #729 にお立ち寄りください。 お会いしましょう。</p>
