### YamlMime:Yaml
ms.openlocfilehash: 0556f244167ed60deb2af7d74109b2306d43c7d7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890509"
Slug: best-practices-in-migrating-sap-applications-to-azure-part-1
Title: SAP アプリケーションを Azure に移行する際のベストプラクティス–パート1
Summary: 'このブログ投稿では、移行の準備として SAP on Azure アーキテクチャを構築することに関係する、優れた Azure アーキテクチャの柱に記載されている原則について説明します。 '
Content: >-
  <p><em>これは、SAP を Azure に移行するためのベストプラクティスに関する3部構成のブログ投稿シリーズの最初のブログです。</em></p>


  <h2>優れた SAP on Azure アーキテクチャの設計</h2>


  <p>このブログ投稿では、お客様の移行の準備として SAP on Azure アーキテクチャを構築するため<a href="https://docs.microsoft.com/en-us/learn/modules/pillars-of-a-great-azure-architecture/" target="_blank">の優れた Azure アーキテクチャ</a> &rdquo; について説明した原則について説明 &ldquo; します。</p>


  <p>Azure 上の優れた SAP アーキテクチャは、次の4つの柱に構築された堅固な基盤から始まります。</p>


  <ul>
   <li>セキュリティ</li>
   <li>パフォーマンスと拡張性</li>
   <li>可用性と回復性</li>
   <li>効率性と運用</li>
  </ul>


  <h2>セキュリティのための設計 <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a050ecb0-17d7-41a1-9622-42098fa867ef.png"><img align="right" alt="Graph comparing the responsibility of Microsoft and customers" border="0" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ed46ce1f-ce14-49f5-917e-81d1802dc2e1.png" style="margin: 43px 0px 0px; border: 0px currentcolor; border-image: none; float: right; display: inline; background-image: none;" title="Microsoft と顧客の責任を比較 Graph" width="295"></a></h2>


  <p>お客様の SAP データは、お客様の組織が&#39;の技術的フットプリントを使用している可能性があります。 そのため、セキュリティで保護された認証による SAP アーキテクチャへのアクセスのセキュリティ保護、ネットワークの脆弱性からのアプリケーションとデータの保護、暗号化方法によるデータ整合性の維持に重点を置く必要があります。</p>


  <p>SAP on Azure は、サービスとしてのインフラストラクチャ (IaaS) クラウド モデルで提供されます。 つまり、セキュリティ保護は、物理的なデータセンター、物理ネットワーク、物理ホストレベル、およびハイパーバイザーで Microsoft によってサービスに組み込まれています。 そのため、ハイパーバイザー (たとえば、ゲストオペレーティングシステムの SAP) の上にある領域では、選択したサービスとテクノロジを慎重に評価して、アーキテクチャに適したセキュリティ制御を提供する必要があります。</p>


  <p>認証に関しては、 <a href="https://docs.microsoft.com/en-us/azure/active-directory/" target="_blank">Azure Active Directory</a> (Azure AD) を利用して、S/4hana Fiori スタートパッドへのシングルサインオン (SSO) を有効にすることができます。 また、Azure AD を SAP Cloud Platform (scp) と統合して、Azure でも実行できる scp サービスにシングルサインオンを提供することもできます。</p>


  <p><a href="https://docs.microsoft.com/en-us/azure/virtual-network/security-overview" target="_blank">ネットワークセキュリティグループ</a> (nsg) を使用すると、 <a href="https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview" target="_blank">仮想ネットワーク</a>内のリソースとの間でネットワークトラフィックをフィルター処理できます。 NSG ルールは、SAP サービスへのアクセスを許可または拒否するように定義できます。たとえば、オンプレミスの IP アドレス範囲から SAP アプリケーションポートへのアクセスを許可し、パブリックインターネットアクセスを拒否することができます。</p>


  <p>データの整合性に関しては、 <a href="https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-faq" target="_blank">Azure Disk Encryption</a> では、オペレーティングシステムとデータボリュームの両方をストレージに保存して暗号化できる SAP 仮想マシンディスクを暗号化するのに役立ちます。 Azure Disk Encryption は、暗号化キーを制御および管理する <a href="https://docs.microsoft.com/en-us/azure/key-vault/key-vault-whatis" target="_blank">Azure Key Vault</a> と統合されています。 SAP のお客様の多くは、オペレーティング システム ディスクには Azure Disk Encryption を、SAP データベース ファイルには透過的な DBMS データ暗号化を選択しています。 この方法では、オペレーティングシステムの整合性が確保され、データベースのバックアップも暗号化されます。</p>


  <p>セキュリティ領域の関心のあるトピックをさらに掘り下げていくには、 <a href="https://docs.microsoft.com/en-us/azure/security/" target="_blank">Azure のセキュリティに関するドキュメント</a>を参照してください。</p>


  <h2>パフォーマンスとスケーラビリティのための設計</h2>


  <p>パフォーマンスは、ビジネスプロセスをデジタル化するための主要なドライバーであり、高性能の SAP アプリケーションを使用することは、ストレスをかけることなく効率的に作業できるようにするために重要です。 そのため、SAP デプロイの品質のサイズ設定の演習を実行し、Azure コンポーネント &ndash; のコンピューティング、ストレージ、およびネットワークを適切にサイズ設定することが重要です。</p>


  <p>Sap <a href="https://launchpad.support.sap.com/#/notes/1928533" target="_blank">Note #1928533</a> sap アプリケーションを実行するためにサポートされている azure Virtual Machines の<a href="https://www.sap.com/about/benchmark/measuring.html" target="_blank">sap 値の</a>詳細。以下のリンクでは、azure VM の種類ごとにネットワークとストレージのスループットを確認できます。</p>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes?toc=%2fazure%2fvirtual-n..." target="_blank">Azure での Windows Virtual Machines のサイズ</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes?toc=%2fazure%2fvirtual-net..." target="_blank">Azure での Linux Virtual Machines のサイズ</a></li>
  </ul>


  <p>Azure の機敏性により、SAP システムを簡単に拡張できます。たとえば、データベースサーバーのコンピューティング能力を増やしたり、需要が生じたときにアプリケーションサーバーを追加することで水平方向にスケーリングしたりできます。 これには、SAP 移行スループットを加速させ、ダウンタイムを短縮するために、インフラストラクチャを一時的に使用することが含まれます。</p>


  <p>SAP アプリケーションとデータベース層には、仮想マシンアクセラレータを利用することをお勧めします。 ネットワークパフォーマンスを向上させるために、仮想マシンで <a href="https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli" target="_blank">高速ネットワーク</a> を有効にします。 M シリーズの仮想マシンで SAP データベースを実行するシナリオでは、書き込み i/o 待機時間を向上させるために、データベースログボリュームの <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/linux/how-to-enable-write-accelerator" target="_blank">書き込みアクセラレータ</a> 持続性のある書き込みキャッシュを有効にすることを検討してください。 書き込みアクセラレータは、生産的な SAP HANA ワークロードに対しては、/のボリュームに対する書き込み待機時間 (sub ms) を低くするために必須です。</p>


  <p>SAP データベースサーバーの Premium Storage Managed Disks を使用して、高パフォーマンスと短い待機時間の i/o を活用できます。 アプリケーションのニーズに合わせて IOPS とスループットを集計するには、RAID 0 のストライプを構築する必要があることに注意してください。 SAP HANA ワークロードの場合は、 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations" target="_blank">Azure でのインフラストラクチャの構成と操作 SAP HANA</a>のドキュメント &ldquo; 内のストレージのベストプラクティスについて説明します。&rdquo;</p>


  <p><a href="https://azure.microsoft.com/en-us/services/expressroute/" target="_blank">ExpressRoute</a> または VPN は、Azure 内の sap アプリケーションに接続するオンプレミスの sap エンドユーザーとアプリケーションインターフェイスの接続を容易にします。 Azure の運用 SAP アプリケーションでは、信頼性、速度の向上、待機時間の短縮、セキュリティの強化を実現するプライベートな専用接続用に ExpressRoute を使用することをお勧めします。 SAP アプリケーションと SAP 以外のアプリケーションの間の待機時間に依存するインターフェイスに注意する必要がある場合は、SAP アプリケーションのグループと SAP 以外のアプリケーションが Azure に到着する移行 &ldquo; グループ &rdquo; の定義が必要になることがあります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b3157cdc-744d-4491-812c-e1d813b0b725.png"><img alt="ExpressRoute or VPN facilitates connectivity for on-premises SAP end-users and application interfaces connecting to your SAP applications in Azure." border="0" height="200" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/de76cdfb-309e-49e2-b5ca-5b9905e52e23.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="ExpressRoute または VPN は接続を容易に " width="780"></a></p>


  <h2>可用性と回復性のための設計</h2>


  <p>運用の安定性とビジネス継続性は、ミッションクリティカルな tier 1 SAP アプリケーションにとって重要です。 可用性のための設計により、ローカライズされたソフトウェアまたはハードウェアの障害が発生した場合に、SAP アプリケーションの稼働時間が確実にセキュリティで保護されます。 生産性の高い SAP アプリケーションの場合は、計画済みおよび計画外のメンテナンスイベントから保護するために、システムセントラルサービス A (SCS) やデータベースが可用性セットまたは <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-ha-availability-zones" target="_blank">Availability Zones</a>にデプロイされるなど、sap の単一障害点を実行する仮想マシンを使用することをお勧めします。 これは、1つの大きなアプリケーションサーバーではなく、いくつかの小規模なサーバーを推奨する SAP アプリケーションサーバーにも当てはまります。 Windows フェールオーバークラスターや Linux Pacemaker などのオペレーティングシステムクラスターテクノロジは、A (SCS) と DBMS の短いフェールオーバー時間を確保するために、ゲスト OS で構成されます。 DBMS 同期レプリケーションは、データが失われないように構成されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3d7f7719-88c6-4892-a048-82503f1748a1.png"><img alt="Industry-leading high availability SLA" border="0" height="533" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e731a7e6-20d2-41c1-9847-639ec7a3964e.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="業界トップレベルの高可用性 SLA" width="1232"></a></p>


  <p>回復性のための設計とは、SAP データベースの論理エラーや大規模な災害からの復旧、完全な Azure リージョンの損失など、データ損失からの復旧を意味します。 回復性を設計するときは、SAP アプリケーションの目標復旧時点 (RPO) と目標復旧時間 (RTO) を把握しておく必要があります。 <a href="https://docs.microsoft.com/en-us/azure/best-practices-availability-paired-regions" target="_blank">Azure</a> のリージョンペアは、1つのリージョンに影響を与える自然災害または人的災害のリスクに対しては、分離と可用性を提供するディザスターリカバリーにお勧めします。</p>


  <p>DBMS レイヤーでは、非同期レプリケーションを使用して、プライマリリージョンからディザスターリカバリーリージョンに実稼働データをレプリケートできます。 SAP アプリケーション層では、効率的でコスト重視のディザスター リカバリー ソリューションの一部として、<a href="https://docs.microsoft.com/en-us/azure/site-recovery/site-recovery-sap" target="_blank">Azure から Azure への Site Recovery</a> を使用できます。</p>


  <p>SAP デプロイ アーキテクチャの設計では、可用性と回復性の両方を慎重に検討することが不可欠です。 これにより、ダウンタイムやデータ損失につながる財務上の損失からビジネスを保護できます。</p>


  <h2>操作と効率の設計</h2>


  <p>Azure に移行することで、SAP システムの合理化評価を行うこともできます。 すべての SAP システムを移動する必要がありますか、使用されなくなったものを使用停止にすることはできますか? たとえば、Microsoft では、 <a href="https://www.microsoft.com/itshowcase/blog/hello-azure-unpacking-microsoft-moved-sap-workload-cloud/" target="_blank">Azure への SAP 移行</a>の一環として約60の仮想マシンを廃止しています。</p>


  <p>効率を重視して、SAP on Azure のデプロイ内の無駄を排除することに専念します。 [ライブ通知]: サイズ変更を確認します。 使用率に基づいて仮想マシンのサイズを小さくすることはできますか。 使用されていないディスクを削除できますか。&nbsp;&nbsp;</p>


  <p>仮想マシンの割り当てを解除したり &ldquo; 事項 &rdquo; したりすると、コストを大幅に節約できます。 たとえば、SAP Sandbox システムを24時間 x 7 日ではなく10時間 x 5 日で実行すると、従量課金制モデルでは約70% のコストが削減されます。 SAP アプリケーションでは、コストを削減するために、 <a href="https://azure.microsoft.com/en-gb/pricing/reserved-vm-instances/" target="_blank">Azure 予約インスタンス</a> に対して 24 x 7 オプトインを実行する必要があります。</p>


  <p>各 SAP デプロイに対してインフラストラクチャを手動で確立することは、煩雑でエラーが発生しやすく、複数の SAP インストールが必要な場合には時間または日数がかかることがあります。 そのため、効率を向上させるために、SAP インフラストラクチャのデプロイとソフトウェアのインストールを可能な限り自動化するのが理にかなっています。 sap プロジェクトランドスケープなど、必要に応じて新しい sap 環境を構築するために、コードとしてのインフラストラクチャを使用して、DevOps パラダイムを採用します。 次に、の一部のリンクを使用して、automation を開始する方法を紹介します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f1b579b0-39be-4fe3-9f81-e50e4a4fde86.png"><img alt="Manual deployment pairs and automated deployment gains" border="0" height="416" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/011a0bcd-ea2c-4155-a40e-15b6dc9af99b.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="手動デプロイペアと自動展開の利点" width="640"></a></p>


  <ul>
   <li><a href="https://azure.microsoft.com\en-gb\blog\automating-sap-deployments-in-microsoft-azure-using-terraform-and-ansible/" target="_blank">Terraform および Ansible を使用した Microsoft Azure への SAP 自動デプロイ</a></li>
   <li><a href="https://azure.microsoft.com/en-us/blog/accelerate-your-sap-on-azure-hana-project-with-suse-microsoft-solution-templates" target="_blank">SUSE Microsoft ソリューション テンプレートを使用した SAP on Azure HANA プロジェクトの加速化</a></li>
  </ul>


  <p>SAP から Azure への取り組みをコンシューマライゼーションする際には、Azure を使用して SAP ワークロードをホストおよび実行することについて理解を深めていただくために、 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/get-started" target="_blank">公式のドキュメント</a> を参照することをお勧めします。&nbsp;</p>


  <p>Sap の移行プロジェクトのさまざまなフェーズを移動するためのコンパスとして、 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-deployment-checklist" target="_blank">Azure の計画とデプロイのチェックリストで Sap ワークロード</a> を使用します。 このチェックリストは、Azure での品質の高い SAP デプロイのための適切な方向を目指しています。</p>


  <p>また、SAP 資産を Azure に配置するためのさまざまな移行オプションに<a href="https://azure.microsoft.com/en-us/resources/migration-methodologies-for-sap-on-azure/" target="_blank">ついて</a>詳しく説明している SAP on Azure &rdquo; のホワイトペーパー、 &ldquo; 移行方法についてもお勧めします。 SAP アプリケーションに巨大なデータベースフットプリントがあるシナリオでは、もカバーされています。 詳細については、ブログの投稿「 <a href="https://techcommunity.microsoft.com/t5/Running-SAP-Applications-on-the/Very-Large-Database-Migration-to-Azure-8211-Recommendations/ba-p/368146" target="_blank">Azure への非常に大規模なデータベースの移行</a>」 &ldquo; を参照してください。&rdquo;</p>


  <p>このシリーズの次のブログでは、Azure での HANA と S/4HANA への移行に焦点を当てています。</p>
