### YamlMime:Yaml
ms.openlocfilehash: e942c7a9d5c492a01b1b6451fb94b2ebbbc9de24
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890516"
Slug: best-practices-for-process-server-deployment-when-protecting-vmware-and-physical-workloads-with-azure-site-recovery
Title: 仮想マシンを使用して VMware と物理ワークロードを保護する場合のプロセス サーバーのデプロイAzure Site Recovery
Summary: この投稿では、InMage レプリケーション チャネルまたは移行アクセラレータを使用して ASR を実装する場合のプロセス サーバー コンポーネントのサイズ設定と配置に関するガイダンスを提供します。
Content: >-
  2014 年の夏に、 <a href="https://aka.ms/microsoft_acquires_inmage">Microsoft は InMage Systems</a> という会社を買収しました。この会社は、さまざまなプラットフォームとオペレーティング システムをサポートするエンタープライズ クラスのディザスター リカバリー (DR) 製品の構築に特化しています。 買収後間もなく、InMage のサイト間およびサイト間ホスト DR の主要製品は、Microsoft Azure Site Recovery <a href="https://aka.ms/asr_for_vmw_phy_site_to_site">(ASR)</a> の一部になりました。 この後、<a href="https://aka.ms/ma_preview">Microsoft Migration Accelerator</a> のプレビューに従いました。これは、お客様がダウンタイムを最小限に抑え、ワークロードをすばやく簡単に Microsoft Azure に移行できる <a href="https://aka.ms/what_is_microsoft_azure">InMage</a> テクノロジに基づくサービスです。


  &nbsp;


  基本的に、InMage レプリケーション チャネルを利用している現在のすべてのオファリングは、同じ基になるアーキテクチャに基づいて作成されます。 関連するコア コンポーネントは次のとおりです。

  <ul>
   <li><b>構成サーバー</b> – レプリケーション ポリシー、レプリケーションの状態、および正常性レポートの管理を担当するセカンダリ サイトで実行されている VM。</li>
   <li><b>マスター ターゲット</b> – レプリケートされたデータと変更ジャーナルのリポジトリとして機能するセカンダリ サイトで実行されている VM。</li>
   <li><b>モビリティ サービス </b>– レプリケーションを目的として、保護されたワークロードで生成されるデータ変更をリアルタイムで直接メモリからキャプチャする軽量ソフトウェア コンポーネントです。</li>
   <li><b>プロセス サーバー</b> – レプリケーションのすべてのコンピューティングと IO 集中型の側面を処理するプライマリ サイトに存在するゲートウェイ。<b></b></li>
  </ul>

  このブログ記事では、InMage レプリケーション チャネルまたは移行アクセラレータを初めて使用して ASR を実装するユーザー向けプロセス サーバー コンポーネントのサイズ設定と配置に関するガイダンスを提供します。


  &nbsp;

  <h3>プロセス サーバーとは</h3>

  プロセス サーバーは、保護されているプライマリ ワークロードと同じ場所に存在するゲートウェイ アプライアンスです。 R2 を実行している物理マシンまたは仮想マシンWindows Server 2012できます。 DR の目的でセカンダリの場所にレプリケートする前に、プライマリ ワークロードからデータ変更を受信し、圧縮、暗号化、キャッシュ、帯域幅の管理を実行する必要があります。 このアプローチでは、プロセス サーバーへの継続的なレプリケーションに関連するコンピューティングタスクと IO 集中型タスクをすべてオフに読み込むので、保護されたワークロードに対するオーバーヘッドがほぼすべて排除されます。


  &nbsp;


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/01/21/image.png"><img style="padding-top: 0px; padding-left: 0px; padding-right: 0px; border-width: 0px;" title="image" alt="image" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/image_thumb.png" width="614" height="223" border="0" /></a>


  &nbsp;

  <h3>プロセス サーバーの配置</h3>

  経験則として、InMage のホストのオフロード アーキテクチャの最大の利点を得るために、保護<b></b>されているプライマリ ワークロードと同じ場所にプロセス サーバーを常にプロビジョニングします。 これにより、プライマリ ワークロードのコンピューティングと IO のオーバーヘッドがほぼ存在しなくなります。


  &nbsp;

  <h3>プロセス サーバーのサイズ設定</h3>

  一般に、プロセス サーバーのサイズ設定は、保護されているワークロード全体の毎日の変化率に依存します。 インライン圧縮や暗号化などのタスクを実行するには、十分なコンピューティングが必要です。 また、プライマリ サイトとセカンダリ サイトの間でネットワークのボトルネックや停止が発生した場合に、十分なキャッシュ ストレージをプロビジョニングする必要があります。 次の表は、特に InMage レプリケーション チャネルを使用して ASR を実装する場合、または移行アクセラレータを初めて実装する場合に、従うのに最適なガイドラインを示しています。

  <table border="1" cellspacing="0" cellpadding="0">

  <tbody>

  <tr>

  <td valign="top" width="96"><i>データ変更率</i><i></i></td>

  <td valign="top" width="90"><i>CPU</i><i></i></td>

  <td valign="top" width="68"><i>メモリ</i><i></i></td>

  <td valign="top" width="98"><i>ブート ボリュームの容量</i><i></i></td>

  <td valign="top" width="150"><i>キャッシュ ディスク サイズ</i><i></i></td>

  <td valign="top" width="150"><i>必要なディスク スループットの合計</i><i></i></td>

  <td valign="top" width="128"><i>NIC の詳細</i><i></i></td>

  </tr>

  <tr>

  <td valign="top" width="96">最大 300 GB/日</td>

  <td valign="top" width="90">4 コア</td>

  <td valign="top" width="68">8 GB</td>

  <td valign="top" width="98">40 GB</td>

  <td valign="top" width="150">400 GB 以上</td>

  <td valign="top" width="150">15 ~ 20 MB/秒</td>

  <td valign="top" width="128">静的 IP を使用した 2 x 1 GigE</td>

  </tr>

  <tr>

  <td valign="top" width="96">最大 700 GB/日</td>

  <td valign="top" width="90">8 コア</td>

  <td valign="top" width="68">16 GB</td>

  <td valign="top" width="98">40 GB</td>

  <td valign="top" width="150">790 GB 以上</td>

  <td valign="top" width="150">34.9 - 46.6 MB/秒</td>

  <td valign="top" width="128">静的 IP を使用した 2 x 1 GigE</td>

  </tr>

  <tr>

  <td valign="top" width="96">最大 1 TB/日</td>

  <td valign="top" width="90">8 コア</td>

  <td valign="top" width="68">32 GB</td>

  <td valign="top" width="98">40 GB</td>

  <td valign="top" width="150">790 GB 以上</td>

  <td valign="top" width="150">51.2 - 68.27 MB/秒</td>

  <td valign="top" width="128">静的 IP を使用した 2 x 1 GigE</td>

  </tr>

  </tbody>

  </table>

  キャッシュ ディスク上の IO は通常、大きくシーケンシャルです。 必要なスループットを実現するために、キャッシュ ディスクの背後にある主軸数は容量よりも重要になる傾向があります。 プロセス サーバーが物理マシンにプロビジョニングされている場合は、十分な主軸を取得するために、ワイド ストライトライクを使用して FC または iSCSI 記憶域アレイからキャッシュ ディスク/LUN をプロビジョニングをお勧めします。 プロセス サーバーが VM としてプロビジョニングされている場合は、SAN から送信されるブロックまたはファイル ベースのデータストアにキャッシュ用の仮想ディスクが確実に存在する以外に、特別な操作を行う必要はありません。 1 TB/日を超える変更率の場合は、必要に応じて追加のプロセス サーバーをデプロイしてスケールアウトをお勧めします。 これは、プロファイリングと容量計画について詳しく説明する今後のブログ記事で詳しく説明します。


  &nbsp;

  <h3>その他の注意事項</h3>

  レプリケーションは IP ネットワークを使用して行われるので、プロセス サーバーではいくつかの受信ポートと送信ポートを開く必要があります。 受信ポートには、ソースエンティティとターゲット エンティティからのデータ転送用の 9080 または 9443 が含まれます。および送信ポートには、レプリケーションの状態と正常性に関するリアルタイムの更新を提供するために、構成サーバーに対して 80 または 443 が含まれます。 プライマリ サイトとセカンダリ サイトのコンポーネント間の接続には、セキュリティで保護されたサイト間 VPN トンネルまたはプロセス サーバーのいずれかのインターフェイスに NAT IP を使用するパブリック インターネットを使用できます。 移行アクセラレータのデプロイ <a href="https://aka.ms/ma_ports">に必要なポートの完全なビューについては、こちらを参照してください</a>。

  <h4></h4>

  <h4>まとめ</h4>

  要約すると、InMage レプリケーション チャネルを使用した ASR 用プロセス サーバーのプロビジョニングのサイズ設定と配置の側面は、保護されたワークロードの数や日次変化率など、いくつかの要因によって異なっています。 最良の結果を得る場合は、このブログ記事に示されているガイドラインに従うのをお勧めします。 その他の質問やコメントについては、 <a href="https://aka.ms/asr_msdn_forums">MSDN のAzure Site Recoveryフォーラムを参照してください</a>。 <a href="https://aka.ms/asr_for_vmw_phy_site_to_site">VMware ワークロードと物理Azure Site Recovery</a>保護する機能の詳細については、詳細なドキュメントを参照してください。 無料の <a href="https://aka.ms/asr_landing">Azure 試用版に</a>サインアップして、無料の Azure 試用版Azure Site Recovery。
