### YamlMime:Yaml
ms.openlocfilehash: fd1196526998ed60cf05de1a406640cddb4909f4
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890493"
Slug: bring-the-power-of-serverless-to-your-iot-application-and-compete-for-cash-prizes
Title: IoT アプリケーションにサーバーレスの力を持ち込み、現金の賞品を獲得する
Summary: 最近では、何らかの方法でインターネットに接続されている何かを通り過ぎないのは難しです。 デスク、ポケット、時計、壁、キッチン、車両、工場、交通など、あらゆる場所で使用できます。
Content: >-
  <p>最近では、何らかの方法でインターネットに接続されている何かを通り過ぎないのは難しです。 デスク、ポケット、時計、壁&hellip; 、キッチン、車両、工場、交通停止、リストが続く買い物店など、あらゆる場所に用意されています。 これらは便利な操作を実行し、データを収集し、最も重要なのは、組み込みの接続性を備える点です。 これらのデータのデータがクラウドの処理力、可用性、インテリジェンスを使用して安全にキャプチャ、処理、分析された場合に実現できる可能性は無限にあります。 YOU と一緒に、これらの可能性を探りたく思っています。</p>


  <p>このため、サーバーレス ハッカソンの <a href="https://azurehacks.devpost.com/" target="_blank">Azure IoT</a> に参加して、<strong>20,000</strong> ドルの賞品プールの一部 * を獲得する機会を得る必要があります。</p>


  <p><a href="https://azurehacks.devpost.com/" target="_blank"><img alt="Azure IoT on Serverless Hackathon" border="0" height="264" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ed5e4043-a7a2-4331-a0fb-712075544ac6.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure IoTハッカソンで使用する" width="1582"></a></p>


  <p>このオンラインコンペティションは、今後数か月間に実行されます。参加を望むユーザーはだれでも参加できます。 このコンペティションでは、現金の賞品を獲得できるだけでなく、Azure ブログで紹介する機会を提供します。</p>


  <p>すべてのアイデアを歓迎します。そのセンサー駆動型スマート ホーム プロジェクトに取り組む場合、医療施設用のリモート監視ソリューションを構築する場合、生産工場の製造プロセスを効率化するインテリジェントなシステムを作成する場合、またはクールな眼鏡をかけた自己修復型ロボットを作成する場合も、あらゆるアイデアが必要です。 この課題はユーザー向けです。</p>


  <h2>このサーバーレスについてはどうでしょうか。</h2>


  <p>サーバーレス <a href="https://azure.com/serverless" target="_blank"></a> アーキテクチャを使用すると、通常 IoT バックエンドのインフラストラクチャ管理に付属する区別のない負荷の高い処理ではなく、トラフィックの変動に関係なくデータの処理とそこから分析情報の生成に集中できるので、<a href="https://azure.microsoft.com/en-us/product-categories/iot/" target="_blank">モノのインターネット</a> &ndash; &ndash; プロジェクトに最適です。 この統合に、Azure Functions または Logic Apps が他のクラウド サービスと提供する統合を追加します。また、クラウドを利用した IoT アプリケーションを構築するための最も迅速で安価な方法があります。</p>


  <p>お客様のすき落とし <strong>ソリューションに驚</strong> いて、IoT プロジェクトを構築しながらサーバーレス化する可能性を探っいてください。</p>


  <h2>&ldquo;わかりました。参加&rsquo;&hellip;する方法は何ですか?&rdquo;</h2>


  <p>先に進み、 でオンライン ハッカソンに登録できます <a href="https://azurehacks.devpost.com" target="_blank">https://azurehacks.devpost.com</a>。 サブスクリプションをまだ持ってない場合は、<a href="https://aka.ms/iotfunchackfree" target="_blank">無料の Azure</a>&rsquo; アカウントにサインアップし、<strong>IoT Hub と Azure Functions</strong>、および含める可能性があるその他のサービス、デバイス、またはテクノロジを使用してソリューションの構築を開始します。</p>


  <p>Azure を利用するのが初めてであれば、 サーバーレスは新しいですか? 心配しないでください。 デバイスまたはセンサー <a href="https://aka.ms/funciotsample" target="_blank">からデータを</a> キャプチャし、集計、フィルター処理、またはこのデータに対するその他のカスタム処理を実行し、データベースに格納する方法については、このクイック サンプルを参照してください。 このサンプルでは、<strong>IoT Hub と Azure Functions</strong> の統合を設定し、Azure Functions のトリガーとバインドについて少し学習し、Cosmos DB に処理されたデータを削除する<strong>方法を理解</strong>します。</p>


  <h2>お金を見せてください。</h2>


  <p>このハッカソンは<strong></strong>、これらのサービスを一緒に操作するための優れた実践的な学習機会を提供<strong></strong>するほか、上位のプロジェクトに大きな賞品を提供します。</p>


  <ul>
   <li><strong>1 位にランクされたソリューションの $10,000</strong> の現金の景品</li>
   <li>2 <strong>位にランクされたソリューションの $6,000</strong> の現金の景品</li>
   <li><strong>3 位にランクされたソリューションの $3,000</strong> の現金の景品</li>
   <li><strong>人気のある選択ソリューションに対する $1,000</strong> の現金の景品(一般投票で選択)</li>
  </ul>


  <p>審査<strong> 官のパネルは、すべての</strong> 提出をレビューして評価し、勝利したソリューションを選択します。 このパネルは、IoT、クラウド コンピューティング、サーバーレスの Microsoft エキスパートで構成されます。 条件は、アイデアの品質、その実装、および実稼働環境での使用に対する潜在的 <strong>な価値で構成されます</strong>。 関連するすべての詳細は、 <a href="https://azurehacks.devpost.com/" target="_blank">Hackathon の Web サイトで確認できます</a>。</p>


  <p>上記の動機が十分ではない場合は、Azure ブログで、最も高いプロジェクトと開発者も強調します。そのため、構築しているクールなことを世界に知らせる機会があります。</p>


  <h2>次の手順</h2>


  <ul>
   <li>Hackathon Web サイトで <a href="https://azurehacks.devpost.com/" target="_blank">コンペティションに登録します</a>。</li>
   <li>データを使用して <a href="https://aka.ms/funciotsample" target="_blank">データIoT Hub処理する方法Azure Functions</a>。</li>
   <li>IoT のニーズに合ったサーバーレス <a href="https://azure.microsoft.com/en-us/blog/go-serverless-for-your-iot-needs/" target="_blank">の方法の例を確認してください</a>。</li>
  </ul>


  <p>来週の <a href="https://www.microsoft.com/en-us/build" target="_blank">Microsoft Build</a> カンファレンスで発表される予定の発表を見守り、ソリューションの作業を今すぐ始めよう。</p>


  <p>ハッキング ゲームを始めましょう。</p>


  <p>&nbsp;</p>


  <p>*購入は必要ありません。 国の過半数の年齢である新規および既存の Devpost ユーザーにのみ開きます。 ゲームは 2018 年 8 月 2 日午後 5 時 (東部時間) に終了します。 詳細については、「公式ルール <a href="https://azurehacks.devpost.com/rules" target="_blank">」を参照してください</a>。</p>
