### YamlMime:Yaml
ms.openlocfilehash: 72b74c89a8323e8967fd604681631773d96f11aa
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889897"
Slug: bringing-commercial-innovations-in-chip-design-to-national-security
Title: チップデザインにおける商用イノベーションを national security に
Summary: 半導体とマイクロエレクトロニクスは、衛星およびレーダーから車両および通信機器への最先端のセキュリティと防御テクノロジを構築するうえで最も重要なコンポーネントの1つです。
Content: >-
  <p>半導体とマイクロエレクトロニクスは、衛星およびレーダーから車両および通信機器への最先端のセキュリティと防御テクノロジを構築するうえで最も重要なコンポーネントの一部です。 セキュリティに関しては、これらのコンポーネントを確実に開発することは、非常に困難な作業です。 従来は、マイクロエレクトロニクスの開発に関連するセキュリティ要件によって、最新のイノベーションを活用する米国国防総省 &rsquo; (DoD) の機能が制限されていました。</p>


  <p>最新 &nbsp; の DoD に準拠したプロジェクトを通じて、高度な商用機能を使用して、迅速に保証されたマイクロエレクトロニクスのプロトタイプ (ランプ) を利用することを目標として、商用のベストプラクティスを活用して、開発プロセスを加速させ、信頼性の高い、セキュリティで保護された最新のマイクロ電子設計と製造を国家安全 DoD &nbsp; は、 <a href="https://nstxl.org/opportunity/ramp-phase-ii/" target="_blank">このプロジェクトの2番目のフェーズをサポートするために Microsoft を</a>選択したことが最近発表されました。</p>


  <p>このプロジェクトは、米国中のセキュリティコミュニティに対して商用のイノベーションを実現するために、マイクロソフトと米国 DoD の間のコラボレーションの40年の履歴を基に構築されています。 Microsoft では、このイニシアチブの <a href="https://azure.microsoft.com/en-us/blog/innovations-for-a-more-secure-us-microelectronics-supply-chain/" target="_blank">最初のフェーズ</a> で DoD を使用して共同作業を行ってきました。これまで、部門 &rsquo; のミッションの優先順位を達成する設計機能を開発してきました。 この2番目のフェーズでは、Microsoft とパートナーがこれらの成功した設計を構築し、高度な製造プロセスへのアクセスを提供する、セキュリティで保護されたコラボレーション設計フローを使用して、チップ (SoC) 設計のカスタム統合チップとシステムの開発を開始します。 これらの新しい設計により、DoD システムでのアプリケーションの電力消費の削減、パフォーマンスの向上、物理サイズの削減、信頼性の向上が実現されます。</p>


  <p>Microsoft は、商用および防衛産業ベース (DIB) にわたってマイクロエレクトロニクスの業界リーダー &nbsp; を活用して、傾斜プロジェクトのこのフェーズを開発してきました。コラボレーター &nbsp; は、Ansys、適用された資料、INC.、Bae Systems、Battelle Memorial 協会、リズム設計システム、Cliosoft、Inc.、Flex Logix、GlobalFoundries、Intel 連邦、Raytheon 知能 and &nbsp; SPACE、Siemens EDA、Synopsys、Inc.、Tortuga Logic、および 0 ASIC Corporation を含みます。</p>


  <p>このランプソリューションでは、ミッションクリティカルなアプリケーション向けの高度なマイクロエレクトロニクス開発プラットフォームが提供されます。これにより、クラウド、AI、機械学習が有効な自動化、セキュリティ、定量化保証が可能になります。 このソリューションは <a href="https://azure.microsoft.com/en-us/global-infrastructure/government/" target="_blank">Azure Government</a>でホストされ、米国のすべての米国 &nbsp; で利用可能なサービスを使用して、政府向けの幅広い商用イノベーションを提供します。データ分類。</p>


  <p>また、セキュリティで保護されたスケーラブルなマイクロ電子サプライチェーンを DoD &nbsp; が活用できるようにするための重要なイニシアチブでもあります。また、設計と製造が厳格なセキュリティとコンプライアンスの要件を満たしていることを保証します。 クラウドベースのセキュリティで保護された設計機能を利用することにより、ファウンドリは、DoD で利用可能な数の増加を増やし、回復性を高め、国内の半導体サプライチェーンの拡大を促進します。 また、傾斜が成功すると、部門はテクノロジの開発をより迅速に行うことができ、進化するニーズに迅速に適応し、最新の技術機能を採用することができます。 DoD と業界パートナーとの協力を得て、マイクロ電子サプライチェーンをセキュリティで保護する革新的な革新的なソリューションを提供することに注目しています。</p>
