### YamlMime:Yaml
ms.openlocfilehash: 282dedaea5efa0528d1ebbd54180078be1228e16
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903651"
Slug: built-in-security-and-operations-management-for-azure-and-hybrid-environments
Title: Azure およびハイブリッド環境向けの組み込みのセキュリティと操作の管理
Summary: クラウドインフラストラクチャの使用量の増加は、過去数年間に非常に大きくなっています。 お客様との会話で、クラウドのセキュリティとクラウドに役立つテクノロジを探しています...
Content: >-
  <p>クラウドインフラストラクチャの使用量の増加は、過去数年間に非常に大きくなっています。 お客様との会話では、多くのユーザーがクラウドのセキュリティとクラウドの管理に役立つテクノロジを探しています。 多くのお客様は、クラウドをルートとする管理を求めており、新しいクラウドパラダイム向けに設計されています。 Microsoft では、現在および将来の企業向けの信頼されたパートナーであり、クラウドプラットフォームの両方を構築し、管理サービスとセキュリティサービスを提供するための長い歴史を持っています。</p>


  <p>Azure では、組み込みのセキュリティと操作の管理 &ndash; を備え、最大規模の企業ユーザーのニーズを満たすことができるオープンクラウドプラットフォームを提供するため、プラットフォームと管理の従来のカテゴリ間の線があいまいになります。 お客様は、完全なセキュリティと操作の管理ライフサイクルを通じて、より簡単なエクスペリエンスでこのアプローチを利用できます。 また、Azure だけでなく従来のワークロードも管理し、保護するツールを構築することの重要性を理解しています。そのため &rsquo; 、ハイブリッド機能の提供に焦点を合わせています。</p>


  <p>現在、これらの分野でいくつかの新しいサービスと機能を発表しまし &rsquo; た。</p>


  <ul>
      <li><strong>Cloudyn による Azure Cost Management は無料で利用できます。</strong> Azure Cost Management を使用すると、組織は Azure、AWS、Google Cloud Platform 全体のクラウドコストを管理し、最適化することができます。 コスト管理は、お客様 &rsquo; からの最も人気のある要求の1つであり、azure のお客様やパートナーが azure の支出を管理できるようになりました。 Azure Cost Management の詳細については <a href="https://azure.com/costmanagement" target="_blank">、Cloudyn を</a>参照してください。</li>
      <li><strong>ハイブリッドワークロードの保護を Azure Security Center します。</strong> Azure Security Center は、Azure で実行されるワークロードをサイバー脅威から保護し、オンプレミスや他のクラウドで実行されているワークロードを保護するためにも使用できるようになりました。 現在、高度な脅威の検出と防御を強化し、セキュリティワークフローを自動化して調整し、脅威の調査を効率化するために、新機能をリリースしています。 <a href="https://aka.ms/hybrid-asc" target="_blank">Azure Security Center の更新</a>の詳細については、こちらをご覧ください。</li>
      <li><strong>Azure portal の仮想マシンエクスペリエンスへの管理の統合。</strong> この新しいエクスペリエンスにより、バックアップ、site recovery、監視、更新管理などを既存の仮想マシンに追加するプロセスが簡単になります。</li>
      <li><strong>更新管理、構成管理 &amp; の変更の追跡は、azure のお客様には無料で含まれて</strong>います。 azure のお客様は、azure の仮想マシンやハイブリッド環境全体で、不足している更新プログラムを管理したり、構成の変更を Windows 効率的に追跡したりするのに役立ちます。 既存の PowerShell &amp; グラフィカル作成機能に加えて、Windows と Linux の両方の環境を簡単に自動化できるように、Python のサポートが Automation サービスに追加されました。 <a href="https://aka.ms/Vs878t" target="_blank">Azure Automation と構成の更新</a>についての詳細情報を表示します。</li>
      <li><strong>アプリケーションからインフラストラクチャまでのエンドツーエンドの監視。</strong> 新しい Azure monitor のユーザーエクスペリエンスによって、監視サービスが一元化され、インフラストラクチャやアプリケーションの可視性が得られます。 さらに、Azure Log Analytics のエクスペリエンスを大幅に最適化し、メトリックの探索、アプリケーションパフォーマンスの監視、Application Insights での障害診断を使用しています。 また、Azure アラートを IT サービス管理ツールと統合し、コンテナー監視用の新しいソリューションをリリースしました。 詳細については、 <a href="https://aka.ms/AzMonIgnite17" target="_blank">Azure 監視の更新</a>に関するページをご覧ください。</li>
      <li><strong>Azure Policy は、ガバナンスとコンプライアンスを実現するのに役立ちます。</strong> 新しい Azure Policy サービスは現在、制限付きプレビュー段階にあります。標準の設定を行い、コンプライアンスを継続的に監視して、企業全体のガバナンスを実現することができます。 Azure のポリシーは、Azure リソースに対して、1つのサブスクリプションから管理グループに適用して、組織全体で制御することができます。 <a href="https://azure.com/policy" target="_blank">Azure Policy 限定プレビュー</a>にサインアップします。</li>
      <li><strong>Azure Cloud Shell での PowerShell のサポート</strong> は、Azure の管理エクスペリエンスを効率化するために、別の認証済みのブラウザーベースのシェルツールとして Bash を補完します。 PowerShell の詳細について <a href="https://aka.ms/cloudshell/welcomePS" target="_blank">は Azure Cloud Shell を</a>参照してください。</li>
  </ul>


  <h2>クラウドワークロードのセキュリティ保護と管理の重要性</h2>


  <p>この世界では、お客様が24時間365日体制でビジネスを行うことを想定しており、脅威はより洗練されたものであるため、少なくとも仮想マシンのセキュリティ、バックアップ、監視を有効にすることをお勧めします。 Azure platform は、データセンターを構築、保守、およびセキュリティで保護するためのセキュリティと運用管理の負担を軽減するように設計されていますが、お客様は、Azure リソースが適切なセキュリティとコンプライアンスの制御によって安全かつ適切に管理されていることを確認できます。&nbsp;</p>


  <p><a href="https://myignite.microsoft.com/sessions/54789?source=sessions" target="_blank">Microsoft Ignite に参加</a>して、これらの新機能と更新プログラムが動作していることを確認したいと思います。 &rsquo;クラウド内のリソースをどのようにセキュリティで保護して管理し、フィードバックをお送りいただくことをお勧めします。 <a href="https://azure.microsoft.com/free/security-management/" target="_blank">無料アカウントを作成</a>して、今すぐ Azure のセキュリティと運用管理を始めることができます。</p>
