### YamlMime:Yaml
ms.openlocfilehash: 30d9de67f21a509cf0154353222db593dcabd0ff
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910901"
Slug: build-cloudnative-applications-that-run-anywhere
Title: 実行場所を選ばないクラウドネイティブ アプリケーションを構築する
Summary: Microsoft は、将来のアプリケーションの構築を可能にする世界クラスのツールとクラウドサービスを使用して、次世代の開発者を支援します。 これらのアプリケーションは、高度な洞察を提供するために、AI によってインテリジェントで infused されます。 これらには、世界中からオープンソースのテクノロジとライブラリが組み込まれています。これらは、設計上、負荷が高く、セキュリティで保護されます。 また、開発者がアイデアからコードにシームレスに移行できるツールを使用して構築されます。
Content: >-
  <p>開発者のグローバルな人口は2030で7150万になると推定されます。これは、今日<sup>1</sup>からの4450万開発者の増加です。 新しい開発者は、私たちのアイデアとイノベーションを世界中のユーザー &rsquo; と共有したいと考えています。 この次世代の開発者は、将来のアプリケーションの構築を可能にする、世界クラスのツールとクラウドサービスを使用して、このような開発者の生産性を高めることができます。</p>


  <p>これらのアプリケーションは、高度な洞察を提供するために、AI によってインテリジェントで infused されます。 これらには、世界中からオープンソースのテクノロジとライブラリが組み込まれています。 これらは、設計上、負荷が高く、セキュリティで保護されます。 また、開発者がアイデアからコードにシームレスに移行できるツールを使用して構築されます。</p>


  <p>今後、コンテナー、Kubernetes、マイクロサービス、サーバーレス機能、API 中心の設計などの<a href="https://azure.microsoft.com/en-us/overview/cloudnative/" target="_blank">クラウドネイティブテクノロジ</a>を活用して、将来これらのアプリケーションを構築することをお客様に Microsoft Azure します。</p>


  <ul>
      <li>お客様は、ユーザーによるメンテナンスアクセスを必要とせずに、無線で動的にアプリケーションを提供することにより、顧客の車両内での<a href="https://customers.microsoft.com/en-us/story/784791-mercedes-benz-r-and-d-creates-container-driven-cars-powered-by-microsoft-azure" target="_blank">エクスペリエンスを向上させる</a>ことができます。</li>
      <li><a href="https://customers.microsoft.com/en-us/story/811347-pwc-partner-professional-services-azure" target="_blank">PwC</a> は、数週間ではなく数秒でドキュメントを分析できる AI 搭載システムを使用して、クライアントが規制に準拠していることを確認するのに役立ちます。</li>
      <li><a href="https://customers.microsoft.com/en-us/story/765209-bosch-increases-vehicle-safety-using-map-matching-algorithms-and-azure-kubernetes-service" target="_blank">Bosch</a> は、車が幹線道路で間違った方法で、ミリ秒以内に発生した場合に、近くのドライバーにアラートを送信するシステムを使用して保存を支援します。</li>
  </ul>


  <p>お客様は Azure でクラウドネイティブテクノロジを使用してきましたが、多くのユーザーがその成功を他の環境でレプリケートしようとしています。 彼らは、Azure とオンプレミスの環境、エッジの場所、AWS や Google Cloud などの他のクラウドで、クラウドネイティブのワークロードに最高クラスの開発と管理のエクスペリエンスを求めています。</p>


  <h2>Azure アプリケーションサービス: アプリ &nbsp; をどこでも実行できます</h2>


  <p>現時点では、azure、オンプレミス、AWS、Google Cloud <strong>のどこでも Kubernetes で実行できる azure アプリケーションサービスのプレビュー機能</strong> について発表します。 Azure Arc 経由で接続された、Cloud Native Computing Foundation (CNCF) に準拠している Kubernetes クラスターは、Azure アプリケーションサービスに対してサポートされているデプロイターゲットになりました。</p>


  <p>Azure &rsquo; s アプリケーションサービスは連携するように設計されており、開発者の生産性向上のために高度に最適化されています。 次のようなものがあります。</p>


  <ul>
      <li><a href="https://azure.microsoft.com/en-us/services/app-service/" target="_blank">Azure App Service</a> では、自動スケール、デプロイスロット、統合 web 認証など、完全に管理されたプラットフォームと機能を使用して、web アプリケーションと api の構築と管理を簡単に行うことができます。</li>
      <li><a href="https://azure.microsoft.com/en-us/services/functions/" target="_blank">Azure Functions</a> を使用すると、イベントドリブンプログラミングがシンプルになり、最新の自動スケール、トリガー、バインドが他の Azure サービスと統合されます。</li>
      <li><a href="https://azure.microsoft.com/en-us/services/logic-apps/" target="_blank">Azure Logic Apps</a>は、アプリ、データ、サービス、およびバックエンドシステムを、400以上のコネクタを持つライブラリと統合するための自動化されたワークフローを作成します。</li>
      <li><a href="https://azure.microsoft.com/en-us/services/event-grid/" target="_blank">Azure Event Grid</a> は、任意のソースから任意の宛先へのイベントのルーティングを管理するための単一のサービスを使用して、イベントベースのアプリケーションを簡略化します。</li>
      <li><a href="https://azure.microsoft.com/en-us/services/api-management/" target="_blank">Azure API Management</a> は、すべての内部 api と外部 api にわたって、統一された管理エクスペリエンスと完全な可観測性を提供します。</li>
  </ul>


  <p>これらのクラウドネイティブアプリケーションサービスでは、それぞれ<a href="https://aka.ms/build21-devvelocityblog" target="_blank">GitHub および Visual Studio Code</a>と密接に統合されているため、開発者は今日の Azure 上で、高い速度で将来のアプリケーションを構築できます。</p>


  <h2>Kubernetes の制御によるアプリケーションサービスの生産性</h2>


  <p>お客様からのご意見をお待ちしておりますが、Kubernetes の強化されたコントロールとエコシステムの利点にもかかわらず、Kubernetes は開発者が直接使用するのが困難です。 開発者は、生産性を低下させる可能性のある多くの高度な概念と Api を習得する必要があります。</p>


  <p>現在 &rsquo; の発表により、開発者は<strong>Azure アプリケーションサービスの生産性と Kubernetes の制御</strong>のどちらかを選択する必要がなくなりました。</p>


  <p>それはどのように機能しますか? 通常の開発者のワークフローを使用して新しい Azure 関数を作成し、ストレージキュートリガーなどの統合機能を使用して、Azure リージョンではなく Kubernetes クラスターをターゲットにして、他のワークロードと共に Kubernetes monitoring ダッシュボードに Azure Functions ポッドが表示されることを確認します。 Azure での生産性の高い開発者エクスペリエンスは、Azure Arc 経由で接続されている<strong>すべての Kubernetes クラスターで動作するようになりました</strong>。Kubernetes で実行されている<a href="https://aka.ms/ArcEnabledAppServices-Build2021-Blog" target="_blank">アプリケーションサービス</a> &nbsp; の詳細については、こちらをご覧ください。&nbsp;</p>


  <h2>Azure Arc でアプリをどこでも実行</h2>


  <p>開発者は、オンプレミス、エッジ、またはマルチクラウドでより多くの環境を対象としているため、多くの場合、アプリケーションホスティング、データホスティング、監視、セキュリティ、および DevOps の自動化のためのカスタムソリューションを構築する必要があります。 ホスティング環境の変更によってのみ存在するカスタムソリューションを生成する必要があります。</p>


  <p>現在 &rsquo; の発表により、開発者は、 <a href="https://azure.microsoft.com/en-us/services/azure-arc/" target="_blank">Azure Arc</a>で有効になっている<strong>ポータブルアプリケーションサービスを使用して、ハイブリッドアプリケーションの構築にかかる時間を短縮</strong>できます。azure PostgreSQL や azure SQL のような、Arc 対応データサービスの使用と組み合わせることで、アプリケーションとそのデータを、業界初の完全管理型のクラウドサービス &mdash; を使用してどこでも実行できるようになりました。</p>


  <p>Azure または Azure Arc を使用したアプリケーションサービスの試用に関心がある場合は、 <a href="https://aka.ms/apptemplate" target="_blank">GitHub の新しいシナリオベースのアクセラレータ</a>を使用してすぐに開始できます。</p>


  <h2>オンプレミスとクラウドで一貫してアプリを管理</h2>


  <p>お客様が環境全体でワークロードを管理および制御できるようにするため、最近、 <a href="https://techcommunity.microsoft.com/t5/azure-arc/azure-arc-enabled-kubernetes-is-now-generally-available/ba-p/2174859" target="_blank">Azure Arc 対応 Kubernetes の一般提供</a>を発表しました。 <a href="https://customers.microsoft.com/en-us/story/844606-siemens-healthineers-health-providers-azure-arc" target="_blank">Siemens Healthineers</a>は、Azure Arc の GitOps 機能を使用することにより、Kubernetes クラスターを数万の場所にデプロイして管理し、世界中の70の国々にある病院の MRI スキャナー、CT スキャナー、X レイ・マシン、および ultrasound マシンを管理できるようにします。 Azure Arc は、任意の CNCF に準拠した Kubernetes クラスターと連携し、Azure Portal による一元的な可視性と、Azure Policy によるガバナンスとコンプライアンスを備えた <strong>単一のウィンドウを提供</strong> します。</p>


  <p>管理された Kubernetes コントロールプレーンを探しているお客様については、現在、<strong> <a href="https://aka.ms/AKSonHCI" target="_blank">Azure Stack HCI</a>での Azure KUBERNETES Service (AKS) の一般提供</strong>が発表されています。 AKS HCI Azure Stack のを使用すると、お客様は AKS と一貫性のある Kubernetes クラスターを簡単にデプロイできます。クラスターは、Microsoft によって完全にサポートされており、オープンソースエコシステムに準拠している100% に準拠しています。 Azure Stack HCI に AKS を展開するには、数回クリックするだけで済みます。 Azure Stack HCI クラスターは、組み込みのセキュリティ、使い慣れた管理ツール、Azure との高度な統合機能を備えた、すぐに使用できる Azure の弧です。 AKS の詳細については、 <a href="https://aka.ms/AKSonHCI" target="_blank">AZURE STACK HCI を</a>参照してください。</p>


  <p>開発者にとって &rsquo; 、クラウドネイティブテクノロジを使用する絶好の時間です。 Microsoft Build 2021 のテクニカルセッション <a href="https://mybuild.microsoft.com/sessions/2debfc2e-f0b3-4adf-bcec-d126930f806f" target="_blank">ビルドクラウドネイティブアプリケーション</a> に関するページをご覧ください。これらの発表に関する詳細や、クラウドネイティブ領域での革新的な技術をご確認ください。 私たち &nbsp; は、何をビルドしているのかを見ていきます。</p>


  <hr>

  <p><sup>1</sup>データソース: Arnal Dayaratna、PhD、IDC アナリスト</p>


  <p><em>Microsoft.目的を持つ在庫。 </em></p>
