### YamlMime:Yaml
ms.openlocfilehash: ca0d139caac33fb8e62fd2062738d817f12256b0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139896092"
Slug: build-a-windows-azure-application-using-twilio-and-win-a-netbook
Title: Twilio を使用して Windows Azure アプリケーションを構築し、netbook を獲得しましょう。
Summary: 'UPDATE [9/3/2009 @ 10: 14AM]: Twilio は、米国の労働日の週末に対応するために、期限を追加しました。  Windows Azure は、Twilio を使用して強制的に参加し、週を #16 します...'
Content: '<p><strong>更新</strong> [9/3/2009 @ 10:14AM]: Twilio has 米国の労働日の週末に対応するために、<a href="https://blog.twilio.com/2009/09/back-to-school-back-to-coding-with-windows-azure-extended-contest-category.html">期限を追加</a>します。</p>  <p>windows azure では、 <a href="https://twilio.com">Twilio</a>を使用 &#160; して<a href="https://blog.twilio.com/2009/08/announcing-this-weeks-netbook-contest-category-windows-azure-platform.html">、Twilio 開発者コンテストの週 #16</a>を提供しています。お客様が知られていないユーザーのために、Twilio は、単純な HTTP 要求を使用して通話を行うための web サービス API です。 &#160; Windows Azure を使用する開発者は、非常に魅力的です。 今週、この2つを組み合わせたアプリケーションを構築するのは困難です。</p>  <p>コンテストに参加する参加者は、日曜日の午前0時に、9月6日にアプリケーションを送信して、Windows 7、$500 の無料コピー (たとえば、Twilio) を Windows Azure クレジットで利用できるように &#160; なります (たとえば、11月に開始されます)。また、前の週からの申請を確認するには、Twilio コンテストのページにアクセス</p>'
