### YamlMime:Yaml
ms.openlocfilehash: 13ea72e4c609d57f33b88720332db657e9ba9ef0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904917"
Slug: build-resilient-applications-with-kubernetes-on-azure
Title: Azure で Kubernetes を使用して回復性に優れたアプリケーションを構築する
Summary: 本日は、Azure での Kubernetes へのクラウドネイティブな取り組みに役立つ、さらに多くの機能についてご紹介します。
Content: >-
  <p>KubeCon EU 2020 (仮想エディション) へようこそ。 私たちは、今年の KubeCon を通じてお &rsquo; 互いを見ることはできませんでしたが&#39;、この新しい仮想形式の KubeCon によって、カンファレンスはこれまでよりもアクセスしやすくなります。また、すばらしい Kubernetes コミュニティの人々は、自宅を離れることなく、世界中に参加して参加することができます。</p>


  <p>すべて &rsquo; の処理が完了したところで、昨年は稼働経験がありましたが、それによって Azure Kubernetes チームの関心と取り組みが非常に誇りになりました。 お客様のエンタープライズレベルのエクスペリエンスを提供する Azure での Kubernetes の反復処理と改良を続けています。</p>


  <p>Kubernetes on Azure (および実際にどこでも) は、クラウドネイティブ開発用のオープンでポータブルなエコシステムを提供します。 この核となる約束に加えて、お客様のワークロードで必要とされる信頼性とセキュリティを確保すると共に、今日のビジネスで期待される機敏性と効率性を実現する、エンタープライズレベルの独自のエクスペリエンスも提供します。 任意のワークロードを Azure Kubernetes Service (AKS) に安全にデプロイすることにより、ビジネスにおける大規模なコスト削減を実現できます。 本日&#39;、Azure での Kubernetes へのクラウドネイティブな取り組みについて、さらに多くの機能について説明します。</p>


  <h2>待機時間と運用効率の向上</h2>


  <p>クラウド導入の主な推進要因の1つは、待機時間を短縮することです。 これは、物理コンピューターを取得してクラスターに設定するのに数日かかっているということです。 現在、Kubernetes クラスターは、5分未満で Azure にデプロイできます。 これらの改善により、お客様の俊敏性が向上します。 スケールとプロビジョニングをより迅速に行うお客様には、一時的な OS ディスクサポートのプレビューが発表されます。これにより、クラスターでの新しいコンピューティング要求に迅速に対応できます。</p>


  <p>&rsquo;待機時間は、クラスターを作成するための時間の長さだけではありません。 &rsquo;また、運用上の問題を検出して対応できる速度についても説明します。 企業が運用効率を向上させるために、 &rsquo; Azure Resource Health とのプレビュー統合を発表しています。これにより、何らかの理由でクラスターが異常な状態になった場合にアラートを通知することができます。 また、ノードイメージ更新の一般提供が発表されまし &rsquo; た。これにより、基になるオペレーティングシステムをアップグレードして、クラスター内のバグや脆弱性に対応する一方で、安定性を維持するために同じ Kubernetes バージョンを維持することができます。</p>


  <p>最後に、Kubernetes では、コンテナー化によってコストを削減することが常に有効になっていますが、pandemic における世界の新しい経済的な現実は、ビジネスのコスト効率をこれまでよりも重要なものにしています。 &rsquo;<a href="https://docs.microsoft.com/learn/modules/aks-optimize-compute-costs/" target="_blank">コンテナーと Azure Kubernetes サービスを使用してコストを最適化</a>する方法を学習するのに役立つ、すばらしい演習があります。</p>


  <h2>Azure での Kubernetes による設計によるセキュリティ保護</h2>


  <p>エンタープライズコンピューティングプラットフォームの主要な柱の1つはセキュリティです。 ポリシーの統合やポッドや &nbsp; クラウドの Azure Active Directory id などの市場をリードする機能により、Azure Kubernetes サービスの重要な部分が常に重要になってきました。 &rsquo;Kubernetes で実行されているワークロードのセキュリティをさらに強化するために最近追加された新機能についてもご &rsquo; 紹介します。</p>


  <p>Kubernetes にはシークレットのサポートが組み込まれていますが、ほとんどのエンタープライズ環境では、より安全で準拠の実装が必要です。 Azure Kubernetes サービスでは、Azure Key Vault と Azure Kubernetes サービス間の統合を提供するエンタープライズレベルの方法です。 Kubernetes で Key Vault を使用すると、資格情報、証明書、およびその他のシークレットをアートの状態に安全に格納し、準拠しているシークレットストアを Azure Kubernetes クラスター内のアプリケーションで簡単に使用することができます。</p>


  <p>&rsquo;この統合は、Kubernetes コミュニティ全体を対象として構築されオープンなオープン &nbsp; コンテナー Storage インターフェイス &nbsp; (CSI) ドライバーの裏に構築されています。 オープンソースに戻ることは、コミュニティのスチュワードとなることを意味する重要な要素であり、HashiCorp Vault チームが秘密の統合に使用したときに、アプローチが検証されていることがわかります。 オープンソースチームは、セキュリティエコシステムの他の多くの部分を改善するために取り組んでいます。 &nbsp;&rsquo;Windows &nbsp; 用の CSI driver が拡張され、cgroups (v2 とドライブが入っています。 クラウドネイティブワークロードを保護し、企業が Microsoft &rsquo; のベストプラクティスに従っていることを確認する方法の詳細については、 <a href="https://docs.microsoft.com/en-us/azure/aks/best-practices" target="_blank">Kubernetes のベストプラクティスに関するガイドを</a>参照してください。 ファイアウォールやポリシーなどを統合して、クラウドネイティブ開発のセキュリティと俊敏性の両方を確保する方法を説明します。</p>


  <h2>次のステップと KubeCon EU</h2>


  <p>最高の KubeCon EU があることを願っています。 カンファレンスをご覧になり、Kubernetes の詳細については、オンラインのすべての優れた情報と仮想ブースでの <a href="https://azure.microsoft.com/en-us/overview/kubernetes-on-azure/" target="_blank">Kubernetes に関する</a> ページを参照してください。 &rsquo;KubeCon と Kubernetes を初めて使用する場合に、愛好家から enterprise へのワークロードの Kubernetes を導入する方法については、優れた<a href="https://aka.ms/adopt/kubernetes" target="_blank">Kubernetes 導入ガイド</a>をご &rsquo; 用意しています。</p>
