### YamlMime:Yaml
ms.openlocfilehash: ac4fed8fe4ecace71a6b57369799eaf51c9e2c1b
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910894"
Slug: building-cloud-native-applications-with-azure-and-hashicorp
Title: Azure と HashiCorp を使用したクラウドネイティブ アプリケーションの構築
Summary: >
  年を追うごとに、クラウドネイティブ アプリケーションを構築する開発者が増えつながっています。 開発者は、より複雑なアプリケーションを構築する中で、Azure や HashiCorp などのイノベーションを起こして、これらのアプリケーションの構築と運用の複雑さを軽減する必要があります。 HashiCorp と Azure は、無数のイノベーションに取り組み続け、
Content: >-
  <p>年を追うごとに、クラウドネイティブ アプリケーションを構築する開発者が増えつながっています。 開発者は、より複雑なアプリケーションを構築する場合、Microsoft Azure や HashiCorp などのイノベーションを行い、これらのアプリケーションの構築と運用の複雑さを軽減します。 HashiCorp と Azure は、無数のイノベーションに取り組み続け、 このイノベーションの例には、クラウドネイティブ アプリケーションをレガシ インフラストラクチャに接続するツールや、顧客のアプリケーションとインフラストラクチャの継続的なデプロイをセキュリティで保護して自動化するツールが含まれます。 Azure は、HashiCorp のようなオープンソース ソフトウェア開発者が、使いやすい統合された方法で顧客にツールを提供するための最適なプラットフォームに深くコミットしています。 HashiCorps&rsquo; Consul Service on Azure を強化するマネージド アプリケーション プラットフォームのような Azure のイノベーションは、コラボレーションへのこのコミットメントの大きな例であり、オープン ソースのスタートアップ エコシステムに大きな影響を与えています。 また&rsquo;、&rsquo;これらのエコシステムの前進に役立つオープン標準の開発にも取り組み、CNAB (クラウド ネイティブ アプリケーション バンドル) 仕様と SMI (Service Mesh Interface) 仕様の両方で HashiCorp と共同作業できたとうれしく思いました。</p>


  <p>昨年 HashiConf 2018 で、Terraform と Packer を Azure プラットフォームに統合する方法を共有する機会を得ていました。 これらの&rsquo;統合の進行状況を共有し、クラウド ネイティブ ネットワークで新しいコラボレーションを共有するために、今年の復帰の機会を得て、非常に楽しみに思います。 この新しい作業では、お客様が HashiCorp テクノロジを使用して Azure 上でアプリケーションを接続して運用するのに役立つコラボレーションを行いました。</p>


  <h2>&mdash; Connect HashiCorp Consul Service on Azure</h2>


  <p>コンテナーと Kubernetes の後、マイクロサービスにおける最も重要なイノベーションの 1 つは、サービス メッシュの概念の開発です。 今年の初めに、HashiCorp などと提携し、サービス <a href="https://cloudblogs.microsoft.com/opensource/2019/05/21/service-mesh-interface-smi-release/"></a> メッシュ テクノロジの構成とデプロイのための、共同で実装に依存しない API である <a href="https://smi-spec.io" target="_blank">Service Mesh Interface</a> のリリースを発表しました。 HashiCorp と協力して、Consul Connect を使用したトラフィック アクセス制御 (TAC) の制御規則の実装を作成しました。 今日は&rsquo;、Azure のお客様が、Azure 上の <a href="https://www.hashicorp.com/blog/announcing-consul-service-on-azure" target="_blank">HashiCorp Consul Services</a> を利用して、新しいプラットフォームを利用Azure Managed Applicationsしています。 HashiCorp Consul は、サービス ネットワークを簡素化し、セキュリティで保護するソリューションを提供します。この新しいマネージド オファリングにより、共同のお客様は Consul の価値に集中しながら、HashiCorp の専門家がサービスの管理を行っているという確信を持っています。 顧客の複雑さを軽減し、クラウドネイティブイノベーションに集中できます。</p>


  <h2>&nbsp;&mdash; Azure で HashiCorp Terraform をプロビジョニングする</h2>


  <p>HashiCorp Terraform は、Azure への宣言型デプロイを実行する場合に最適なツールです。 お客様&#39;年の初めから 2 倍に増えたので、Azure での HashiCorp Terraform の導入に大きな勢いが見え、お客様は Terraform を使用してさまざまなシナリオで Azure インフラストラクチャのデプロイと運用を自動化しています。&nbsp;</p>


  <p>この勢いは、コントリビューターの前面で素晴らしいものにし、 <a href="https://github.com/terraform-providers/terraform-provider-azurerm" target="_blank">Terraform</a> プロバイダーに対して約 180 人の独自の共同作成者がAzure Resource Manager。 コミュニティからの 3 週間のリリースの増加 (現在バージョン 1.32) との関与により、Terraform による Azure サービスのより多くのカバレッジが保証されます。 さらに、Azure 用の Terraform モジュールの追加の必要性に関するお客様およびコミュニティからのフィードバックの後、&#39;は高品質のモジュールの追加に取り組み、 <a href="https://registry.terraform.io/browse/modules?provider=azurerm" target="_blank">Terraform</a> レジストリ内の Azure モジュールの数を 2 倍にし、120 を超えるモジュールに追加しました。&nbsp;</p>


  <p>これらすべての追加の統合により、お客様はコードとしてのインフラストラクチャを簡単に管理し、クラウド環境の管理を簡素化できると考えています。 Azure 上の <a href="https://azure.microsoft.com/en-us/solutions/devops/terraform/" target="_blank">Terraform の詳細を確認してください</a>。</p>


  <p>Microsoft と HashiCorp は、Azure 上の Terraform の統合サポートを提供するために、一緒に作業しています。 Microsoft&#39;Azure クラウドで Terraform を使用しているお客様は相互のお客様であり、両方の企業が統合してトラブルシューティングとサポート サービスを提供しています。 この共同エンタイトルメント プロセスは、シームレスなカスタマー エクスペリエンスを提供しながら、企業やプラットフォーム間で共同サポートを提供します。 Terraform Provider for Azure を使用しているお客様は、Microsoft サポートにサポート チケットを登録できます。 Azure サポートで Terraform を使用しているお客様は、Microsoft または HashiCorp にサポート チケットを提供できます。</p>


  <h2>Cloud&nbsp;&mdash; Native Application Bundles 仕様でのコラボレーションのデプロイ</h2>


  <p>コンテナーによって解決される重要な問題の 1 つは、世界中で共有およびデプロイが容易なパッケージへのバイナリのパッケージ化です。 しかし、クラウドネイティブ アプリケーションはバイナリ以上のアプリケーションであり、これが Coud Native Application Bundle (CNAB) 仕様の HashiCorp などとの共同開発につながっています。 CNAB&nbsp; を使用すると、Terraform などの構成ツールや他の成果物と共にイメージをパッケージ化して、ユーザーが 1 つのパッケージからアプリケーションをシームレスにデプロイできます。 コミュニティ&rsquo;が一緒に作業して、CNAB&rsquo; が世界中のすべてのデプロイ ニーズに対応できる状態を示す <a href="https://cloudblogs.microsoft.com/opensource/2019/09/10/cloud-native-application-bundle-cnab-1-0-updates" target="_blank">1.0</a> リリースの仕様を構築するのを見て、楽しみに思っています。 作業と素晴らしいパートナーシップに関するチームの皆さん、おめでとうございます。</p>


  <p>Azure と HashiCorp が連携してクラウドネイティブ開発を容易にする方法の詳細については、以下のリンクを参照してください。</p>


  <ul>
      <li><a href="https://www.hashicorp.com/blog/announcing-consul-service-on-azure" target="_blank">Azure での HashiCorp</a> Consul Service オファリングに関する HashiCorp のお知らせ</li>
      <li><a href="https://azure.microsoft.com/en-us/solutions/devops/terraform/" target="_blank">Azure での Terraform</a></li>
      <li><a href="https://aka.ms/cnab2jdf" target="_blank">クラウド ネイティブ アプリケーション バンドル (CNAB)</a></li>
  </ul>
