### YamlMime:Yaml
ms.openlocfilehash: f6562a3bac1dcb78329c5f7f3f392b755ce03868
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139896070"
Slug: build-your-application-development-agenda-at-ignite
Title: Ignite でアプリケーション開発の議題を作成しましょう。
Summary: 新しい開発テクノロジ、接続された新しいデバイス、新しいクラウド指向ビジネスモデルは、アプリケーション開発者がイノベーションを向上させるための大きな機会を生み出します。 ...
Content: >-
  新しい開発テクノロジ、接続された新しいデバイス、新しいクラウド指向ビジネスモデルは、アプリケーション開発者がイノベーションを向上させるための大きな機会を生み出します。 オンプレミスまたはクラウドで実行されているビジネスアプリケーション、高度な web ポータル、またはクライアントユーザーインターフェイスを構築するかどうかにかかわらず、Ignite 今年に参加したときに可能な限り多くのアプリケーション開発の知識が必要になります。 (これを行うことができない場合は、この投稿の下部にあるオンライン表示オプションを確認してください)。Ignite に参加している人やオンラインであるかどうかにかかわらず、実際のキャリア向上が可能です。


  次のサンプルの議題には、アプリケーション開発者にとって最も関連性が高く、役に立つセッションが含まれています。


  <b>月曜日、5月4</b>


  9:00 AM-Satya Nadella とその他の Microsoft 役員との Ignite の基調講演


  1: 5:30-<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=2dfca4c9-00c1-e411-b87f-00155d5066d7#fbid=fQk9eWdVz_x?WT.mc_id=IG15XCSOSC">開発者向けの Microsoft アプリケーションプラットフォームの概要</a>


  3: 15PM —<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=2d5ee1b2-91a1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">実際の開発サイクルにおけるアジャイル開発: ヒントと手法</a>


  <b>火曜日、5月5日</b>


  1: 5:30-<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=e3bb0a18-91a1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">新しいプレミアムの概要 Azure CDN</a>


  3: 15PM-<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=4bdc904a-93a1-e411-b87f-00155d5066d7#fbid=fQk9eWdVz_x?WT.mc_id=IG15XCSOSC">モバイルに移行します。Azure App Service で Enterprise api にログインし、データを同期し、Connect し</a>ます


  5: 00pm —<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=87223433-6f85-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">Office 365 api を使用して Mobile Apps を薄くし</a>ます。


  <b>水曜日、5月6日</b>


  9: 00am —<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=af9f0784-2fa1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">DevOps マインドセットの Release Management の実用的なビュー</a>


  1: 5:30-<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=d34c3f49-eaaf-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">Microsoft Azure Media Services を使用したエンドツーエンドのメディアワークフロー</a>


  <b>木曜日、5月7日</b>


  9:00 am:<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=03629459-b39a-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">Office 365 api を使用したクラウドでの Microsoft OneNote による開発</a>


  10: 45am —<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=f574e3c8-2fa1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">ASP.NET 5 の概要</a>


  5: 00PM —<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=99ed2f92-92a1-e411-b87f-00155d5066d7#fbid=fQk9eWdVz_x?WT.mc_id=IG15XCSOSC">Azure App Service Logic Apps と BizTalk: 明日の統合が今日開始</a>


  <b>金曜日、5月8</b>


  9: 00AM —<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=dca77d19-92a1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">優れたアプリで問題が発生した場合: Azure App Service でのアプリケーションのトラブルシューティング</a>


  12: 5:30:<a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=5a60d65c-91a1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">Azure App Service で Web および Mobile Apps を実行 Enterprise</a>


  このようにすると、口が水になります。 これらのセッションは、Ignite のすべてについてのほんの一部にすぎません。 ニーズに合わせて微調整された <a href="https://myignite.microsoft.com/#/sessions?WT.mc_id=IG15XCSOSC">イベントの名簿を作成</a> できます。 さらに、時間のかかるネットワークアクティビティの中でも、志向の大勢のスタッフをご利用いただけます。


  Ignite に登録しておらず、ユーザーに参加できない場合は、 <a href="https://ignite.microsoft.com/#fbid=MVRDJfn0SnH?WT.mc_id=IG15XCSOSC">5 月4日に基調講演ライブを視聴</a> して、ライブで24時間、オンデマンドセッションにアクセスすることができます。


  Ignite のニュースと更新情報を確認するには、 <a href="https://microsoft.eventcore.com/MicrosoftIgniteMailingList?WT.mc_id=IG15XCSOSC">こちらを購読</a>してください。
