### YamlMime:Yaml
ms.openlocfilehash: 6e69aa01c0884adde4de4683e528773c11c5704c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909030"
Slug: compute-and-stream-iot-insights-with-data-driven-applications
Title: データドリブンアプリケーションを使用した IoT insights の計算とストリーミング
Summary: 世界では、最も信頼性の高い最先端のテクノロジを使用しても、多くのデータがキャプチャされる可能性があります。 エッジコンピューティングとモノのインターネット (IoT) は、有用なデータの量を増やすテクノロジの2つの例にすぎません。
Content: >-
  <p>世界では、最も信頼性の高い最先端のテクノロジを使用しても、多くのデータがキャプチャされる可能性があります。 エッジコンピューティングとモノのインターネット (IoT) は、有用なデータの量を増やすテクノロジの2つの例にすぎません。 多くのデータが作成されています。現在の通信インフラストラクチャは、それを転送するのに苦労し、クラウドが使用さに格納される場合もあります。 通信で5G が登場し、クラウドストレージの急速な成長にもかかわらず、データの増加によって両方のインフラストラクチャの容量が追い越し始めされ続けます。 1つの解決策は、スイムのテクノロジを使用して、データドリブンのステートフルアプリケーションを構築することです <a href="https://www.swim.ai/" target="_blank">。AI</a>。</p>


  <p>Azure platform は、パートナーが業界のソリューションを強化、拡張、構築するための豊富なサービスを提供します。 ここでは、1つの Microsoft パートナーが Azure を使用して一意の問題を解決する方法について説明します。</p>


  <h2>共有の認識とコミュニケーション</h2>


  <p>ボリュームの増加には他にも影響があります。特に、IoT デバイスが相互に認識し、共有情報を通信する必要がある場合です。 IoT 資産間のピアツーピア (P2P) 通信では、ネットワークが過負荷になり、パフォーマンスが低下する可能性があります。 スマートグリッドは、センサーまたは電気メーターが分布グリッドを介してネットワークに接続されていることを示しています。これにより、電力の全体的な信頼性とコストが向上します。 メーターを使用して問題の局所性を判断すると、住居、近所、市町村、セクター、リージョンに対するサービスの品質向上に役立ちます。 共有認識の概念は、車両から車両 (V2V) と車両間 (V2I) の通信に及びます。 ネットワークに接続された AI はより多くの自動車やデバイスに分散しているため、他の資産のパフォーマンスや状態を把握するメリットがあります。 その他のユースケースは次のとおりです。</p>


  <ul>
   <li>1つの地域における車両のフローに反応する信号。</li>
   <li>前のプロセスのステップからの影響を判断できる製造装置を処理します。</li>
   <li>下流の石油/ガスセンサーの検証に反応するアップストリームの石油/ガス機器のパフォーマンス。</li>
  </ul>


  <h2>問題: 超過データはデータの損失を意味する</h2>


  <p>大量のデータを処理する場合、企業は、保持するデータ、保持する量、および保持する必要がある期間を決定することが困難になることがよくあります。 既定では、そのいずれも保持されない可能性があります。 または、サンプルデータが不完全なデータセットを保持している可能性があります。 データが失われた場合、価値の高い洞察が含まれている可能性があります。 たとえば、効率的な車両ルーティング、通勤安全、保険分析、政府によるインフラストラクチャレビューに使用されるトラフィック情報を考えてみます。 ラスベガスの市は1100を超える交通45TB を維持しています。これにより、毎日、より多くのデータが生成される可能性があります。 前に説明したように、IoT データは、これらのボリュームにデータを転送して格納する機能を備えています。</p>


  <p>データが集計されると、 &rsquo; データが過剰になる場合もあります。 たとえば、通信装置とネットワーク機器は、通常、データのスナップショットを作成し、15分ごとに送信します。 このデータを時間の経過に伴う概要に正規化すると、粒度が失われます。 これは、時間の経過と共にデータの性質またはパターンと、一意で直感的なイベントが失われることを意味します。 これは、固定時間のウィンドウ概要データをキャプチャする機器にも当てはまります。 データの損失は、デバイスが認識または通信のためにデータを共有するネットワークに悪影響を及ぼすことがあります。 また、この問題は、数千または数百万のデバイスのネットワーク全体に対してのみスナップショットがキャプチャされ、集計されるため、さらに複雑になります。 リアルタイムは目標です。</p>


  <h2>リアルタイムは目標です。</h2>


  <p>ステートレスなアプリケーションアーキテクチャの現在の標準はほぼリアルタイムですが、 &ldquo; ほぼ &rdquo; リアルタイムでは十分に高速ではありません。 リアルタイム処理またはミリ秒以内の処理は、V2V または V2I 通信の新しい標準であり、より高性能なアーキテクチャを必要とします。 これを実現するには、ステートフル API &rsquo; を活用します。 ステートフル接続では、 &rsquo; ネットワーク内のピア間で迅速な応答を行うことができます。 速度は効率と信頼性に大きな影響を与え、 &rsquo; クラッシュの防止などの安全性が最も重要なシステムにとって重要です。 自律システムは、安全性を確保するためにリアルタイムのパフォーマンスを利用します。</p>


  <h2>インテリジェントエッジデータ戦略</h2>


  <p>スイム.AI は、スケーラブルなストリーミングアプリケーションを構築するためのソリューションを提供します。 サイトの <a href="https://www.swim.ai/opensource/" target="_blank">達成</a>に応じて、次のようになります。</p>


  <p><em>&ldquo;別のメッセージブローカー、アプリサーバー、およびデータベースを構成するのではなく、スイムの永続化、メッセージング、スケジューリング、クラスタリング、レプリケーション、イントロスペクション、およびセキュリティを提供します。すべてが統合されているので、従来のクラウドアプリケーションアーキテクチャのインフラストラクチャと開発コストのごく一部について、エッジ、クラウド、クライアントの間のシームレスなスケーリングを実現します。&rdquo;</em></p>


  <p>次の図は、スイムの IoT アーキテクチャを簡素化する方法を示しています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4a7702c1-0bba-492e-918b-c7d029862e01.png"><img alt="Diagram display of how Swim can simplify architectures" border="0" height="697" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fb010b18-6d5d-41e6-8b34-6b7921ae03f5.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="スイム・フローがどのように簡素化できるかを図で表示" width="1118"></a></p>


  <h2>中間ストリームでのデータの収集</h2>


  <p>スイム.AI は、軽量の <a href="https://www.swim.ai/opensource/" target="_blank">スイム</a> プラットフォームを使用します。これは、IoT insights を計算してストリーミングするために 2 mb のフットプリントを生成するだけで、データ駆動型アプリケーションの呼び出し &ldquo; を構築します。 &rdquo; これらのアプリケーションはデータストリームに配置され、表示される各データソースに対して一意でインテリジェントな web エージェントを生成します。 これらのインテリジェント web エージェントは、データストリームからの状態の変更のみをストリーム配信するときに生データを処理します。 このストリームデータは、他の web エージェントで使用することも、Azure などの data lake に格納することもできます。</p>


  <p>スイム干し草 &rdquo; の中にある針を使用して &ldquo; 、この固有の利点を説明します。 スイムメタル検出機能を適用して、針を検索するための粒子を取得することができます。これにより、針を検索する前に、粒度を設定したり、移動したりする必要はありません。 この利点は継続的にデータを処理することです。インテリジェントな web エージェントは、時間の経過と共に、またはしきい値を設定するドメインの専門家によって影響を受ける可能性があります。</p>


  <p>スイムのステートフルアーキテクチャにより、必要な最小限のデータのみがネットワーク経由で転送されます。 さらに、アプリケーションサービスでは、クラウドがアプリケーションコンテキストを確立するまで待機する必要がありません。 この結果、ステートフルな接続 &rsquo; では、データベースへの読み取りと書き込み、またはポーリング要求に基づく更新の待機時間のコストが発生しないので、待機時間が非常に短くなります。</p>


  <p>をオンにします。AI &rsquo; s web サイトでは、 <a href="https://www.swim.ai/showcase/traffic/" target="_blank">スマート都市アプリケーション</a> は、数千のセンサーを使用して、100の交差部分におけるライトと交通のリアルタイムの状態を示しています。 アプリを使用しているクライアントは、接続されているか自立車に近づいている可能性があります。 これは、共通部分の横にあるハンドヘルドデバイス、または1つのブラウザーが、連続した米国内で1000マイル離れた場所にある可能性があります。 リアルタイムの待機時間は 75 ~ 150 ミリ秒であり、インターネットを介した目の点滅よりも小さくなります。</p>


  <h2>メリット</h2>


  <ul>
   <li>すぐに得られるメリットは、データの転送と保存にかかるコストを節約することです。</li>
   <li>スイム &rsquo; のテクノロジにより、粒度を維持することができます。 たとえば、1000のすべてのトラフィックの交差部分から10秒 (1 日あたり) を生成した場合を考えます。 これで、データは1日あたり100秒にダウンするようになりました。 しかし、収集されたデータセットは元の生データセットを完全に記述します。</li>
   <li>さまざまなデータソース用に、効率的にネットワーク対応のアプリを作成します。 たとえば、インターネット上の車両、デバイス、センサー、およびその他のデータソースなどの資産間で、ピアツーピア認識と通信を実現します。</li>
   <li>75-150 ミリ秒の範囲で、非常に短い待機時間を実現します。 これは、認識と通信のためにデータに依存するアプリを作成するための鍵です。</li>
  </ul>


  <h2>ソリューションで使用される Azure サービス</h2>


  <p>スイムでの DataFabric のデモ。AI は、セキュリティ、プロビジョニング、管理、およびストレージのためにコア Azure サービスに依存しています。 また、datafabric は、 <a href="https://docs.microsoft.com/common-data-model/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Common Data Model</a>を使用して、Azure 内の他のシステム ( <a href="https://powerbi.microsoft.com/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Power BI</a>や<a href="https://powerapps.microsoft.com/?WT.mc_id=ptx-azblog-ditambur" target="_blank">PowerApps</a>など) との情報の共有を簡略化します。 Azure テクノロジを使用すると、顧客 &rsquo; の分析をイベント、ネイティブ ML および認知サービスと統合できます。</p>


  <p>DataFabric は、 <a href="https://aka.ms/iotrefarchitecture" target="_blank">Microsoft IoT 参照アーキテクチャ</a> に基づいており、次の主要なコンポーネントを使用します。</p>


  <ul>
   <li><a href="https://azure.microsoft.com/services/iot-hub/?WT.mc_id=ptx-azblog-ditambur" target="_blank">IoT Hub</a>: デバイスとそのデータを管理するためのクラウドの中心点を提供します。</li>
   <li><a href="https://azure.microsoft.com/services/iot-edge/?WT.mc_id=ptx-azblog-ditambur" target="_blank">IoT Edge フィールドゲートウェイ</a>: クラウドインテリジェンスを配信するためのオンプレミスのソリューションです。</li>
   <li><a href="https://azure.microsoft.com/services/event-hubs/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Azure Event Hubs</a>: 1 秒あたり何百万ものイベントを取り込み。</li>
   <li><a href="https://azure.microsoft.com/services/storage/blobs/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Azure Blob</a>: ホット、ウォーム、アーカイブされたデータのオプションを含む効率的なストレージ。</li>
   <li><a href="https://azure.microsoft.com/services/storage/data-lake-storage/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Azure Data Lake storage</a>: ビッグ Data Analytics に対応した、拡張性とコスト効率に優れたデータレイクソリューションです。</li>
   <li><a href="https://azure.microsoft.com/services/stream-analytics/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Azure Streaming Analytics</a>: データを実用的な洞察や予測にほぼリアルタイムで変換します。</li>
  </ul>


  <h2>次の手順</h2>


  <p>その他の業界ソリューションの詳細については、 <a href="https://azure.microsoft.com/industries/discrete-manufacturing/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Azure for の製造</a> に関するページを参照してください。</p>


  <p>このソリューションの詳細については、「 <a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/swim-ai.swim-ai?tab=Overview" target="_blank">Azure IoT 用の datafabric</a> 」を参照して、[<strong>今すぐ入手</strong>する] を選択してください。</p>
