### YamlMime:Yaml
ms.openlocfilehash: b7c17c5564d59eaccd99938eba1d76cb9a7eeecc
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893540"
Slug: configure-resource-group-control-for-your-azure-devtest-lab
Title: Azure DevTest Lab のリソース グループ制御を構成する
Summary: ラボ所有者として、すべてのラボ仮想マシン (VM) を 1 つのリソース グループに作成するオプションが追加されました。 これにより、サブスクリプションのリソース グループの制限に達Microsoft Azureできます。
Content: >-
  <p>ラボ所有者として、すべてのラボ仮想マシン (VM) を 1 つのリソース グループに作成するオプションが追加されました。 この機能は、次のシナリオで役立ちます。</p>


  <ul>
   <li>サブスクリプション内のリソース グループのうち、ラボによって作成されたものが少ない。</li>
   <li>自分で構成した一連の固定のリソース グループ内でラボを運用する。</li>
   <li>Azure サブスクリプション内でリソース グループを作成するために必要な制限および承認を回避する。</li>
   <li>すべてのラボ リソースを 1 つのリソース グループ内に統合して、それらのリソースを追跡し<a href="https://docs.microsoft.com/en-us/azure/governance/policy/overview" target="_blank"></a>、リソース グループ レベルでリソースを管理するためのポリシーの適用を簡略化します</li>
  </ul>


  <p>この記事では、DevTest Lab を使用してこの機能を使用する方法、または自動化Azure portal方法について説明します。</p>


  <h2>Azure DevTest Lab ポータルの使用</h2>


  <p>ラボ所有者は、仮想マシンの [構成とポリシー]、 [ラボ<strong></strong>の設定]、および <strong></strong>[リソース グループの割り当て] に移動して、ラボに対してこの設定<strong>を構成できます</strong>。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0c6c9170-9580-421c-856c-7fe37ed17ff6.png"><img alt="Screenshot of Resource Group allocation for virtual machines" border="0" height="720" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f2d3f9e4-34b9-4bf5-bef3-d1ab3870c9df.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="仮想マシンのリソース グループ割り当てのスクリーンショット" width="2354"></a></p>


  <p>この設定は既定で既存の動作に設定されます。つまり、リソース グループの割り当てに変更はありません。 既存の動作を続行するか、1 つのリソース グループ内のすべてのマシンを今後作成するオプションを選択できます。 後者を選択した場合は、次の 2 つのオプションがあります。</p>


  <p>1. アクセス権を持つリソース グループの事前設定済みのドロップダウンから既存のリソース グループを選択します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/99235ec2-2fc3-4a64-8cb1-47872483378c.png"><img alt="Screenshot of exsiting resource groups from a pre-populated dropdown menu" border="0" height="782" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fe999b02-14db-4d4e-b451-cc46aa1e54ea.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="事前設定されたドロップダウン メニューからのリソース グループの抜粋のスクリーンショット" width="2354"></a></p>


  <p>2. 今後仮想マシンを作成するためにサービスによって自動的に作成される新しいリソース グループを入力します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e3f8abf5-df25-4bd3-9a00-4b8526aa1323.png"><img alt="Screenshot of entering a new resource group" border="0" height="810" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a306b580-05be-4b77-be2f-5e1853492b79.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="新しいリソース グループの入力のスクリーンショット" width="2354"></a></p>


  <h2>オートメーションの使用</h2>


  <p>スクリプトを使用して、すべてのラボ VM を作成する Azure サブスクリプション内の新規または既存のリソース グループを指定することもできます。 次に、&rsquo;この API の使用中にラボ所有者として持っているオプションについて説明します。</p>


  <ul>
   <li>今後作成される&rsquo;すべての VM のラボ リソース グループを選択できます。</li>
   <li>今後作成されるすべての VM のラボ&#39;リソース グループ以外の既存のリソース グループを選択できます。</li>
   <li>今後作成する VM の新しいリソース グループ名を入力できます。</li>
   <li>既存の動作を続行できます。</li>
  </ul>


  <p>この設定は、ラボで作成された新しい VM に適用されます。 つまり、独自のリソース グループに作成されたラボ内の古い VM は引き続き影響を受けません。 ラボで作成された ARM 環境は、引き続き独自のリソース グループに残り、この機能の操作中に選択したオプションの影響を受け "しません"。</p>


  <p>この機能を使用&ldquo;する方法とサンプル スクリプトの詳細については、ドキュメント「ラボ仮想マシンのリソース グループを Azure DevTest Labs で指定する」を参照<a href="https://aka.ms/RGControl" target="_blank">してください。</a>&rdquo;この機能が役に立ちます。</p>


  <p>よりうまく機能するアイデアを得ましたか? フィードバックやアイデアを送信するか、<a href="https://feedback.azure.com/forums/320373-azure-devtest-labs" target="_blank">UserVoice フォーラムで他Azure DevTest Labs投票してください</a>。 質問はございますか? 回答を確認するか、MSDN フォーラムで新しい回答 <a href="https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureDevTestLabs" target="_blank">を確認してください</a>。</p>
