### YamlMime:Yaml
ms.openlocfilehash: 19e401fd4dfa15d18b9ab9f9d171002e09c9c62c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893539"
Slug: configuring-barracuda-web-application-firewall-for-azure-app-service-environment
Title: Azure App Service Environment の Barracuda Web アプリケーション ファイアウォール (WAF) を構成する
Summary: Barracuda Web Application Firewall を構成App Service Environment
Content: <a href="https://azure.microsoft.com/en-us/documentation/articles/app-service-app-service-environment-intro/">Azure App Service環境では</a> 、アプリケーションの分離とスケーリングの特性が高い環境が提供されます。 App Service Environment のセキュリティを向上させるために、SQL インジェクション、クロスサイト スクリプティング、その他の攻撃からアプリケーションを保護するために、この環境用に <a href="https://azure.microsoft.com/documentation/articles/app-service-app-service-environment-web-application-firewall">Barracuda Web Application Firewall (WAF)</a> を構成する方法に関するドキュメントをリリースしました。 Barracuda WAF の詳細については、Web サイト<a href="https://www.barracuda.com/programs/azure"></a>で確認できます。また、次の手順<a href="https://azure.microsoft.com/marketplace/partners/barracudanetworks/waf-byol/">で構成Azure Marketplace</a>。
