### YamlMime:Yaml
ms.openlocfilehash: d078d185523758f2a6678f9c5360dd894e9b14d0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909932"
Slug: connect-your-applications-to-azure-with-open-service-broker-for-azure
Title: Open Service Broker for azure を使用してアプリケーションを azure に Connect する
Summary: 現在、open Service Broker for Azure (OSBA) のプレビューを発表しています。これは、Open Service Broker API for Azure サービスを実装したものです。 マルチクラウドのマルチプラットフォーム環境で,...
Content: >-
  <p>&rsquo;現在、open <a href="https://github.com/azure/open-service-broker-azure" target="_blank">Service Broker for AZURE (osba)</a>のプレビューを発表しています。これは、azure サービス用の<a href="https://openservicebrokerapi.org/" target="_blank">open Service Broker API</a>の実装です。 マルチクラウドのマルチプラットフォーム環境では、開発者は、marketplace で利用できる豊富なサービスにアプリケーションを接続するための標準的な方法を希望しています。 Open Service Broker API は、その需要を簡単かつ安全に満たすための業界全体の取り組みです。 osba は最も単純で、最も柔軟性の高い方法で、Azure Database for MySQL などの標準的なオファリングから、グローバルに分散されたマルチモデルデータベースである Azure Cosmos DB などの独自の azure ソリューションにアプリケーションを接続できます。 現在、11個の Azure サービスが提供されており、翌年の中でほとんどのサービスをサポートする予定です。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/211b4faa-63d1-4c67-8546-20e106cb277f.png"><img alt="Open Service Broker for Azure" border="0" height="716" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8ad03f4d-1b1a-44ed-92d8-04cb78228d51.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure の Service Broker を開く" width="1430"></a></p>


  <p align="center"><em>Open Service Broker for Azure と Service catalog CLI を使用すると、Kubernetes アプリケーションを Azure サービスに簡単に接続できます。</em></p>


  <p>&nbsp;</p>


  <p><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Shows/Azure-Friday/Open-Service-Broker-for-Azure/player" width="960"></iframe></p>


  <p>Open Service Broker for Azure は、任意の環境で実行されている任意の OSB 互換プラットフォームにデプロイできます。 &rsquo;Azure、Azure Stack、独自のオンプレミス環境 (または他の場所) で Kubernetes、Cloud Foundry、OpenShift のいずれを使用しても、azure が提供するすべての優れたサービスを利用できます。 マイクロソフトは、2016の Cloud Foundry に対する service broker への投資と、それを <a href="https://github.com/azure/meta-azure-service-broker" target="_blank">オープンに</a>するために、この分野におけるイノベーションを長期に記録しています。 OSBA は、この作業に基づいて構築され、新しいプラットフォームとサービスに拡張されます。一方、Open Service Broker API に対するコミットメントも示されています。 現在 &rsquo; 発表されているので、OSBA を優先し、Cloud Foundry のお客様と密接に連携して円滑に移行できるようにすることを計画しています。</p>


  <p>Kubernetes に対する大きな投資の一環として、Microsoft はサービスカタログのアクティブな共同作成者になっています。これにより、Kubernetes オペレーターは、Azure などのプラットフォームによって提供されるクラウドネイティブサービスを利用できます。 また、 <a href="https://github.com/Azure/service-catalog-cli" target="_blank">Kubernetes service カタログ用の CLI のアルファリリース</a>も発表しています。</p>


  <p>このツールを使用すると、ブローカー、サービスインスタンス、サービスバインドなど、明確に定義されたサービスカタログオブジェクトとの対話が可能になり、サービスカタログとの対話が非常に簡単になります。 サービスカタログ CLI は、サービスカタログがデプロイされている場所に関係なく動作します。また、Kubernetes コミュニティの他の部分と連携することに注目してください。</p>


  <p>以下のデモでは、OSBA を使用して、サポートされている環境の一部に対して Azure サービスをプロビジョニングおよびバインドすることがいかに簡単であるかを示しています。 Kubernetes の場合、これには、ヘルムパッケージマネージャーとの自然な統合と、新しいサービスカタログ CLI の使用が含まれます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3a1e4982-f01b-4369-9f84-6716348dc023.gif"><img alt="OSBdemovideo-Fdraft3" border="0" height="810" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/17b8701e-5f5f-4a63-acc5-f433985c3b1a.gif" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="OSBdemovideo-Fdraft3" width="1296"></a></p>


  <p>現在、OSBA で Azure を利用したアプリケーションの構築を開始できます。 <a href="https://github.com/Azure/helm-charts/tree/master/open-service-broker-azure" target="_blank">Kubernetes</a>と<a href="https://github.com/Azure/open-service-broker-azure/blob/master/contrib/cf/README.md" target="_blank">Cloud Foundry</a>にデプロイする手順について説明します。 openshift と Azure Service Fabric は近日対応予定です。 Kubernetes を対象としている場合は、 <a href="https://github.com/Azure/helm-charts/" target="_blank">ヘルムグラフ</a> を確認してください。これは、osba によってプロビジョニングされた Azure サービスを使用するように強化された WordPress や Concourse などの一般的なヘルムグラフの例を示しています。</p>


  <p>ありがとうございまし &rsquo; た。 GitHub にご協力ください。</p>


  <p>Sean</p>
