### YamlMime:Yaml
ms.openlocfilehash: 46b59b2527720ceb3e7c349ef55921243361d600
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903606"
Slug: creating-iot-applications-with-azure-database-for-postgresql
Title: Azure Database for PostgreSQL を使用した IoT アプリケーションの作成
Summary: さまざまな業界に多くの IoT ユースケースがあります。 IoT のユースケースの最も一般的なカテゴリには、予測メンテナンス、接続車両、異常検出、資産の監視などがあります。
Content: >-
  <p>さまざまな業界に多数の <a href="https://azure.microsoft.com/en-us/overview/iot/industry/">IoT ユースケース</a> があり、 <a href="https://www.azureiotsolutions.com/Accelerators#description/predictive-maintenance">予測メンテナンス</a>、 <a href="https://download.microsoft.com/download/6/9/D/69D92EB1-F1EE-4893-ABE1-C005D7F9FF57/Microsoft_Connected_Vehicle_Platform_Whitepaper_EN_US.pdf">接続車両</a>、異常検出、資産の監視などの一般的なカテゴリがあります。 たとえば、カリフォルニア州の水の治療施設では、IoT デバイスを水ポンプに取り付けて、水ポンプの木馬パワー、フロー速度、および電気的な使用量を測定できます。 これらのデバイスから生成されたイベントは、集計と処理のために30秒ごとに IoT hub に送信されます。 水の設備は、イベントデータが特定のしきい値を超えた場合に、水ポンプを監視するダッシュボードを作成し、メンテナンスチームにアラートを作成することができます。 その後、フローレートが dangerously 低い場合は、メンテナンスチームにアラートを出し、水ポンプを修復することができます。 これは、一般的なプロアクティブメンテナンスの IoT ユースケースです。</p>


  <p><a href="https://docs.microsoft.com/en-us/azure/iot-fundamentals/iot-introduction">Azure IoT</a>は、IoT ソリューションの完全なスタックです。 これ &rsquo; は、数十億の IoT 資産を接続、監視、制御する Microsoft が管理するクラウドサービスのコレクションです。 Azure IoT コアサブシステムのコンポーネントには、次のような共通のセットがあります。</p>


  <ul>
   <li>イベントをストリーミングする<b>IoT デバイス</b></li>
   <li><b>クラウドゲートウェイ</b>。 Azure IoT は、デバイスとエッジデバイスとの間の通信を可能にするために最もよく使用されます。</li>
   <li><b>ストリーム処理</b> 。デバイスからイベントを取り込みし、分析の出力に基づいてアクションをトリガーします。 一般的なワークフローは、Avro でエンコードされた入力テレメトリで、ストレージの JSON でエンコードされた出力テレメトリを返すことができます。</li>
   <li><b>Storage </b>。<b> </b>これは通常、レポートと視覚化の目的で IoT イベントデータを格納するために使用されるデータベースです &rsquo; 。</li>
  </ul>


  <p>ここでは、エンドツーエンドの Azure IoT ソリューションを実装する方法と、 <a href="https://docs.microsoft.com/en-us/azure/postgresql/">Azure Database for PostgreSQL</a>を使用して、IoT イベントデータを jsonb 形式で格納する方法について説明 &rsquo; します。 PostgreSQL を NoSQL データストアとして使用すると、強力なネイティブ JSON 処理、インデックス作成機能、および<a href="https://azure.microsoft.com/en-us/blog/run-your-lob-applications-with-postgresql-powered-by-the-plv8-extension/">plv8 拡張</a>によって独自の利点が得られるため、JavaScript v8 engine と SQL を統合することによってさらに拡張することができます。 管理されたサービスの機能とコストの削減に加えて、Azure Database for PostgreSQL を使用する主な利点の1つは、最新のアプリケーションが開発者の生産性を向上できるようにする Azure エコシステムとのネイティブ統合です。</p>


  <p>この実装では、plv8 拡張機能を使用して、ストレージ、分析、レポートのための IoT テレメトリストリームの永続レイヤーとして、Azure Database for PostgreSQL を使用します。 高速ストリーミングデータは、最初に、永続レイヤーとして PostgreSQL データベース (マスターサーバー) に読み込まれます。 マスターサーバーは、高速なデータインジェストのために使用されます。 <a href="https://docs.microsoft.com/en-us/azure/postgresql/concepts-read-replicas">読み取りレプリカ</a> は、レポートおよび下流のデータ処理でデータドリブンのアクションを実行するために活用されます。 イベント処理ハブと Azure 関数として Azure IoT ハブを利用して処理手順をトリガーし、出力されたイベントから必要なもの &rsquo; を抽出して Azure Database for PostgreSQL に格納することができます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d83daf7a-9ac9-4afe-b40d-7caf67f29038.png"><img alt="139 - Azure" border="0" height="199" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6dd84e2c-5f52-4709-b6f3-4c02b92789ac.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="139-Azure" width="576"></a><br>

  &nbsp;</p>


  <p>この投稿では、概要を理解するための高度な実装について説明 &rsquo; します。 <a href="https://github.com/Azure/azure-postgresql/tree/master/samples/IoT%20Demo">GitHub リポジトリ</a>には、サンプルアプリケーションと、以下のソリューションを実装するための詳細な手順を示すクイックスタートチュートリアルがあります。 クイックスタートでは Node.js アプリケーションを使用して、IoT Hub にテレメトリを送信します。</p>


  <h3>手順 1: Azure IoT ハブを作成し、ハブにデバイスを登録する</h3>


  <p>この実装では、IoT センサーシミュレーターは、温度と湿度のデータを常にクラウドに送り返します。 最初の手順では、<a href="https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-create-through-portal">次の手順</a>に従って、Azure portal に Azure IoT ハブを作成します。 次に &rsquo; 、デバイス名を IoT Hub に登録して、IoT Hub が登録済みデバイスからテレメトリを受信して処理できるようにします。</p>


  <p>GitHub では、CLI を使用してデバイスを登録し、IoT Hub サービス接続文字列をエクスポートするサンプルスクリプトが表示されます。</p>


  <h3>手順 2: テレメトリデータストリームを格納するための Azure Database for PostgreSQL サーバーとデータベース IoT デモを作成する</h3>


  <p>適切なサイズの Azure Database for PostgreSQL をプロビジョニングします。 <a href="https://docs.microsoft.com/en-us/azure/postgresql/quickstart-create-server-database-portal">Azure portal</a>または<a href="https://docs.microsoft.com/en-us/azure/postgresql/quickstart-create-server-database-azure-cli">Azure CLI</a>を使用して、Azure Database for PostgreSQL をプロビジョニングできます。</p>


  <p>データベースでは、plv8 拡張機能を有効にし、JSON ドキュメントから気温列を抽出するためにクエリに役立つサンプル plv8 関数 &rsquo; を作成します。 JSON テーブルを使用して、IoT テレメトリデータを格納できます。 スクリプトを検索してデータベースとテーブルを作成し、GitHub で plv8 拡張機能を有効にすることができます。</p>


  <h3>手順 3: Azure 関数イベントハブを作成し、メッセージを抽出して PostgreSQL に格納する</h3>


  <p>次に、手順1で作成した Azure IoT hub へのイベントハブトリガーバインドを含む JavaScript Azure 関数を作成します。 この関数を作成するには、JavaScript &nbsp; <a href="https://github.com/Azure/azure-postgresql/blob/master/samples/IoT%20Demo/azure%20function/index.js">index.js</a>サンプルを使用します。 関数は、IoT Hub 内の受信メッセージストリームごとにトリガーされます。 JSON メッセージストリームを抽出し、手順2で作成した PostgreSQL データベースにデータを挿入します。</p>


  <h2>IoT ソリューションをエンドツーエンドで実行して作業を開始する</h2>


  <p><a href="https://github.com/Azure/azure-postgresql/tree/master/samples/IoT%20Demo">GitHub リポジトリ</a>のサンプルアプリケーションを使用して、このソリューションを実装することをお勧めします。 GitHub では、node.js アプリケーションを実行してイベントデータの生成をシミュレートする手順、デバイス登録を使用して IoT Hub を作成する方法、イベントデータを IoT Hub に送信する方法、JSON メッセージからデータを抽出して Azure Database for PostgreSQL に挿入する Azure 関数のデプロイ方法について説明します。</p>


  <p>GitHub のすべての手順の実装が終了したら、次に示すように、リアルタイムダッシュボードを作成するための Power BI のようなレポートツールを使用して、データのクエリと分析を行うことができます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0aa0cf61-6d04-4fcc-9738-7e617a5fdf71.png"><img alt="139 - Azure 2" border="0" height="326" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/deb6a49b-6364-4848-980b-6fc28866b267.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="139-Azure 2" width="566"></a></p>


  <p>Azure Database Service for PostgreSQL に用意されている最新の機能をご利用いただけます。 お客様のフィードバックは、必ず <a href="https://feedback.azure.com/forums/597976-azure-database-for-postgresql">ユーザー Voice For PostgreSQL</a>を使用してご連絡ください。</p>


  <p>ヘルプが必要な場合、または質問がある場合は、 <a href="https://docs.microsoft.com/en-us/azure/postgresql/">Azure Database for PostgreSQL のドキュメント</a>を参照してください。</p>


  <h3>謝辞</h3>


  <p>この投稿への投稿については、Qingqing 人民、Bassu Hiremath、Parikshit Savjani、 &nbsp; anitah Cantele、および Rachel Agyemang &nbsp; に感謝します。</p>
