### YamlMime:Yaml
ms.openlocfilehash: d2e17720da832dc9b6d29b982302f3432be13091
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903609"
Slug: creating-cloud-ready-environments-with-azure-landing-zones
Title: Azure ランディング ゾーンを使用したクラウド対応環境の作成
Summary: Microsoft クラウド導入フレームワーク for Azure の Azure ランディング ゾーンは、運用モデルをマップ、最新化、または再設計するための取り組みを加速するように設計されています。 Azure ランディング ゾーンは、クラウド内のニーズに固有の最適なテクノロジ運用に合わせてクラウド環境を構築するのに役立ちます。
Content: >-
  <p>クラウドに移行すると、IT 環境の運用方法を一時停止して考える機会が生み出されます。 世界中のほとんどの組織は、既存の IT 環境を管理するルールと運用モデルによって遅くなるクラウド テクノロジをイノベーションして採用する能力を見てきた。 組織には、これらの環境がビジネス ニーズを継続的にサポートできるよう、独自のプロセス、ツール、および専用スタッフのセットがあります。</p>


  <p>クラウド環境への移行により、IT は IT 運用のブロックを解除する新しいツールやプロセスにアクセスできます。 運用モデルを見直して、テクノロジに重点を置くチームと Azure パートナーは、組織が機敏性、コスト、スケールを向上させるのに役立ちます。</p>


  <p><a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/migrate-landing-zone" target="_blank">Microsoft クラウド導入フレームワーク</a> <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/" target="_blank">for Azure の Azure ランディング ゾーン</a> は、運用モデルをマップ、最新化、または再設計するための取り組みを加速するように設計されています。 Azure ランディング ゾーンは、クラウド内のニーズに固有の最適なテクノロジ運用に合わせてクラウド環境を構築するのに役立ちます。</p>


  <p>次の例に示すように&rsquo;、標準化された基盤は、組織や運用モデルで見られるさまざまなニーズに適合する可能性があります。 オプションとカスタマイズの必要性を尊重し、さまざまなランディング ゾーン アーキテクチャと実装オプションを提供します。 組織は、現在のクラウド戦略に最も明確に一致する実装オプションを使用できます。 クラウド プラットフォームの管理、運用、管理のアプローチが成熟するに従って、顧客をサポートし、Azure ランディング ゾーンの実装をリファクタリングして、運用モデルの変更を反映することができます。</p>


  <h2>ランディング ゾーンの例え</h2>


  <p>クラウド環境は、任意の建設プロジェクトに基盤を構築するのと似ています。 すべてのアーキテクトは、すべての建物の基礎を設計および構築する際に、一般的な決定を考慮する必要があります。 それらはすべて、プラムや電気など、必要なユーティリティを取り込む、具体的な、リバー、パイプのようなものを共有します。 基礎には同様の要素と考慮事項が含まれていますが、一意で大別する他の考慮事項がある場合があります。 家の基礎は簡潔で、十分に含まれている。 球場の基礎は、より大きく、より複雑です。 ブリッジの基礎はさらに複雑であり、より厳密なガバナンスとパフォーマンス標準が必要な場合があります。 適切な基盤を設計するには、その基盤が何をサポートするのかを理解する必要があります。</p>


  <p>Azure ランディング ゾーンによって作成されるクラウド環境は、すべて同じ一般的な設計要素から構築されるのとよく似ています。 すべての環境に共通点は存在しますが、各ランディング ゾーンの実装は、特定の種類の構造またはクラウド運用モデルをサポートするためにカスタマイズされます。 従来の基盤と同様&rsquo;に、クラウド環境では、組織の長期的なニーズを確実にサポートするために、経験豊富なアーキテクトによるレビュー、変更、イテレーションが必要になります。</p>


  <p>運用を開始または再考する場合、Azure ランディング ゾーンは、クラウド環境の設計、レビュー、実装を加速するのに役立ちます。 顧客と連携して取り組む際に、Azure ランディング ゾーンは、Azure ランディング ゾーンを検証、カスタマイズ、拡張してデジタル変革の基盤を構築する際に、コラボレーションをガイドできます。</p>


  <h2>Azure ランディング ゾーン</h2>


  <p>Azure ランディング ゾーンは、初期クラウド環境を作成する明確なアーキテクチャ、参照実装、コード サンプルを提供します。 この環境では、一連の一般的な設計領域を一貫して適用することで、他のすべての導入 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas" target="_blank">作業がサポートされます</a>。 これらの設計領域は、クラウドでの運用モデルのサポート方法を表します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/11168e94-35aa-4db0-a35d-c36589720c40.png"><img alt="Design areas of a well-architected landing zone." border="0" height="423" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9d315b5b-2839-47e1-a647-958e6137eead.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="十分に設計されたランディング ゾーンの設計領域。" width="1024"></a></p>


  <p>Azure ランディング ゾーンの実装オプションは、ネットワーク、ID、リソース編成、ガバナンス、運用、および環境に影響を与えるその他の設計領域に関する決定を行うのに役立つ参照実装またはアプローチを提供します。 このオプションは、最小限の設計上の考慮事項が行われたり、決定がクラウド環境全体に一貫して反映されるのを保証するために、組織が従える構造を提供します。</p>


  <h2>Azure ランディング ゾーンの実装オプション</h2>


  <p>Azure ランディング ゾーンは、&rsquo;今日の要件に基づいてお客様の個別のニーズを満たした後、パーソナライズされたランディング ゾーンの実装をカスタマイズして成熟するための明確なパスを提供するように設計されています。 まず、ランディング ゾーンの実装 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/implementation-options" target="_blank">オプション</a>を選択します。これにより、クラウド環境の開始点をすばやくデプロイできます。</p>


  <p>一部の Azure ランディング ゾーンは、スキルの開発とカスタマイズを促進するために設計上小さめです。 小規模 &ldquo;な実装オプション&rdquo; を開始すると、コードとしてのインフラストラクチャ アプローチが確立され、IT チームに一連の意思決定ガイドが提供されます。 このアプローチは、発生する必要がある考えや決定を導く上で役立ちます。 この反復的なアプローチでは、クラウド導入計画と並行して基盤を構築し、クラウド エクスペリエンスの成熟に合った具体的な決定をチームが行うのに役立ちます。</p>


  <p>運用モデルが十分に定義されている組織の場合、エンタープライズ&ldquo;&rdquo;規模の実装オプションによってこれらの決定が満たされます。 このオプションには、セキュリティ、ガバナンス、運用に関する非常に詳細なソリューションが含まれています。 これらのソリューションは、参照実装の Azure Policyその他のガバナンス ツールによって自動化され、適用されます。 エンタープライズ規模から始める場合、組織は意思決定ポイントの数を減らし、実証済みのクラウド運用モデルをより迅速に実装できます。</p>


  <h2>Azure ランディング ゾーンの開発</h2>


  <p>選択したランディング ゾーンに関係なく、Azure 向け <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/" target="_blank">クラウド導入フレームワーク (CAF)</a> の準備手法は、クラウド環境を作成してサポートするために必要なスキルを開発しながら、組織をガイドするのに役立ちます。 Azure ランディング ゾーンの背後にある理論により、インフラストラクチャ管理機能に十分に確立された開発プラクティスが提供されます。</p>


  <p>Azure ランディング ゾーンが実装およびカスタマイズされるに応じて、チームは一般的な Azure アーキテクチャのスキルを開発します。 また、ランディング ゾーンをリファクタリング<a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/refactor" target="_blank"></a>して新しいビジネス要件と技術要件を満たす方法と、<a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/azure-test-driven-development" target="_blank"></a>テスト駆動開発によって高品質の変更がクラウド環境に価値を追加する方法を学習することが重要です。 また&rsquo;、Azure のガバナンス ツールを使用して環境ファクトリを作成し、お客様にセキュリティの迅速なデプロイを提供し、十分に管理された、十分に管理された Azure ランディング ゾーンを顧客に提供する方法も経験します。</p>


  <p>顧客のクラウド導入&rsquo;作業が進むに従って、ガバナンスと管理の手法に<a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/"></a>関する<a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/"></a>ページにあるガイダンスを使用して、ガバナンスと運用管理の体制をさらに成熟するのに役立ちます。 これらのプロセスと分野が成熟するに従って、Azure ランディング ゾーンと Azure のガバナンス ツールのスイートは、既存の環境に変更を適用するための便利なアプローチを提供します。 これにより、集合的なテクノロジ&rsquo; チームは、ガバナンスと管理を適切なペースで成熟できる一方で、技術的な互換性の課題によってそのような進行状況が失速し続けずにいます。</p>


  <h2>詳細情報</h2>


  <p>Azure ランディング ゾーンの詳細については、以下を含む、クラウド導入フレームワーク <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/overview">(CAF) の [</a> 準備完了] セクションを参照してください。</p>


  <ul>
      <li>定義されている <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/refactor" target="_blank">Azure ランディング ゾーンを読み取る</a>。</li>
      <li>Azure ランディング <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas" target="_blank">ゾーンの設計領域を確認し</a> 、ランディング ゾーンの要件について考え始める。</li>
      <li>Azure ランディング <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/implementation-options" target="_blank">ゾーンの実装オプションを評価</a> して、ニーズに最も合ったデプロイ アプローチを見つける。</li>
  </ul>


  <p>顧客が Azure ランディング ゾーンをデプロイする準備ができている場合は、次のリソースを使用して開始できます。</p>


  <ul>
      <li><b>小規模から始め、展開します。</b><a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/migrate-landing-zone" target="_blank">CAF 移行ランディング ゾーンブループリントをデプロイ</a>して、移行準備環境の構築を開始します。 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/foundation-blueprint">CAF ブループリントを追加して</a>、任意の環境へのガバナンス ツールの追加を開始します。</li>
      <li><b>エンタープライズ規模から始める:</b> より堅牢な実装を実現するには、参照実装を利用して <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/" target="_blank">CAF エンタープライズ規模の</a> ランディング ゾーンを <a href="https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md" target="_blank">デプロイします</a>。</li>
      <li><b>サード パーティのマルチクラウド オプション:</b><a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/terraform-landing-zone#customize-and-deploy-your-first-landing-zone" target="_blank">CAF Terraform モジュールを使用してランディング</a> ゾーンをデプロイします。</li>
  </ul>


  <p>Azure にワークロードが既に存在し、ベスト プラクティスに対してそれらを評価する必要がありますか? <a href="https://docs.microsoft.com/en-us/azure/architecture/framework/" target="_blank">Microsoft Azure Well-Architected Framework と</a> Microsoft Azure Well-Architected <a href="https://docs.microsoft.com/en-us/assessments/?id=azure-architecture-review&amp;mode=pre-assessment" target="_blank">確認してください</a>。</p>


  <p>Azure&rsquo; ランディング ゾーンを活用して顧客のクラウド導入ニーズをサポートする適切なクラウド環境を作成することで、ビジネスを拡大し、信頼できるクラウド アドバイザーとしての立場を強化します。 適切な環境を構築することで、お&rsquo; 客様と顧客の最新の運用で、組織のイノベーションと移行のニーズを確実にサポートできます。 Azure&rsquo; ランディング ゾーンの上にクラウドを導入する方法は、顧客の IT ポートフォリオ全体でクラウドの機敏性、スケール、コストのメリットを引き出す最初のステップです。</p>
