### YamlMime:Yaml
ms.openlocfilehash: 95497fae919eb86fd505e6087f329030511312fb
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904883"
Slug: cross-post-applications-are-now-open-for-the-microsoft-accelerator-for-windows-azure-2013
Title: 'クロスポスト: Microsoft Accelerator for Windows Azure - 2013 に対してアプリケーションが開く'
Summary: 過去数か月間、Microsoft Accelerator for Windows Azure&nbsp; のスタートアップ企業は、企業およびテクノロジのリーダーから指導を受け、投資者と会い、互いに学び合いました,...
Content: <p>この数か月の間に、Microsoft Accelerator for Windows Azure&nbsp; のスタートアップ企業は、ビジネスおよびテクノロジのリーダーから指導を受け、投資者と会い、互いに学び合い、最も重要なのは、最適な製品を構築することでした。 最初のクラスのスタートアップ企業の&rsquo;詳細と、Azurehere でのスタートアップの使用Windowsできます&nbsp;。</p>  <p>最初のクラスが <sup>1 月</sup> 17 日のデモの日に近づくにつれて、Microsoft Accelerator for Windows Azure の 2 番目のクラスのアプリケーションを開く予定です。 これは 2013 年 4 月 1<sup>&nbsp;</sup> 日に開始され、2013 年 6 月 26 日のデモの日で終了します。</p>  <p>現在スタートアップ企業で働いている場合、または自分の会社の設立を検討している場合は、適用をお&nbsp;勧めしています。 &rsquo;<sup>2013</sup> 年 2 月 1 日まで、アプリケーションを受け入れる予定です。 アクセラレータとアプリケーション プロセスの詳細については、こちらを参照&nbsp;<a href="https://www.microsoft.com/bizspark/accelerator/" target="_blank">してください</a>。</p>  <p>元の投稿はこちらで<a href="https://weblogs.asp.net/scottgu/archive/2012/12/19/applications-are-now-open-for-the-microsoft-accelerator-for-windows-azure-2013.aspx" target="_blank">読む。</a></p>
