### YamlMime:Yaml
ms.openlocfilehash: 03393ff648305976f131e6c88857afeb506d5054
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893100"
Slug: customer-success-stories-with-application-insights-analytics-2
Title: Application Insights Analytics を使用したお客様の成功事例
Summary: ビルド2016で発表された Visual Studio の Application insights の新しい診断および分析機能について、優れたフィードバックを受け取りました。
Content: >-
  <p>ビルド2016で発表された<a href="https://azure.microsoft.com/services/application-insights/">Visual Studio の Application</a> insights の<a href="https://azure.microsoft.com/en-us/blog/new-diagnostics-and-analytics-capabilities-in-application-insights/">新しい診断および分析機能</a> &nbsp; について、優れたフィードバックを受け取りました。</p>


  <p>ここでは、お客様の成功事例をいくつかご紹介します。</p>


  <h2>Quorum</h2>


  <blockquote>

  <p><a href="https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.qbsol.com%2f&amp;data=01%7c01%7ckghelani%40exchange.microsoft.com%7ce154670939ef44a19c1208d352866925%7c72f988bf86f141af91ab2d7cd011db47%7c1&amp;sdata=zSBqwwy6MeqY%2f7YzTxPYFlu1z8Da7XaeIN%2fK7sxTfT0%3d">クォーラム</a> (<a href="https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.qbsol.com&amp;data=01%7c01%7ckghelani%40exchange.microsoft.com%7ce154670939ef44a19c1208d352866925%7c72f988bf86f141af91ab2d7cd011db47%7c1&amp;sdata=y5RhIhg2Zx72pjedrkP7xbL7B9O07WQ8HyZe1mXjQ%2bs%3d">qbsol.com</a>) は、hydrocarbon およびエネルギービジネス管理向けの革新的なソフトウェアです。 &rsquo;エネルギー価値チェーン全体でお客様の利益を促進することが実証された統合ソリューションのプラットフォームで業界を推進しています。 <a href="https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.qbsol.com%2ffield-operations%2f&amp;data=01%7c01%7ckghelani%40exchange.microsoft.com%7ce154670939ef44a19c1208d352866925%7c72f988bf86f141af91ab2d7cd011db47%7c1&amp;sdata=bq6FO3PIbXTmYHmDQgniyzsZWize5%2f%2bE834RrwICRs0%3d">運用操作およびフィールド操作用の</a>クォーラム &rsquo; s クラウドベースのソフトウェアは Microsoft Azure で実行されます。 これは、石油およびガス企業が比類のない速度とパフォーマンスを重視することを意味します。</p>


  <p>アプリインサイトに追加された新しい分析機能により、重要なアプリケーションとサービスの正常性テレメトリにすぐにアクセスできるようになります。 これは、過去、5、30、または90分の問題について質問に回答しようとしているときに、アプリデータに対して SQL に似たクエリを記述してすぐに応答を取得することによって、"移動ツール" として表示されています。 今後、データの傾向を時系列で表示し、プラットフォームとそのサービスを改善するための変更を積極的に行う場合は、Power BI のようなものが必要です。</p>


  <p>任意のツールが役に立つようにするには、それを使用するかどうかの決定とそれによって提供される値の間に、障壁をできるだけ少なくする必要があります。 データの収集と格納に使用するマネージプラットフォームが1つであっても、データを分析して使用できる情報に変換するまで、実際の値は達成されません。 Intellisense のようなものは、アプリインサイトと市場におけるその他の競争力のあるサービスとの間には違いがあると考えています。</p>


  <p>最終的には、管理する別のクラスターではなく、利用するサービスを探していました。 最初に、オープンソースの検索と分析エンジンを使用して、すべてのテレメトリをこのエンジンに移行しようとしていました。 クラスターを利用できなくなった場合は、方向を変更し、オーバーヘッドを少なくする必要がある代替手段を見つける必要があります。 ソリューションのアプリインサイト analytics を選択しました。</p>


  <p>アプリインサイトの新しい分析機能について長期的に考えられるのは、クラウドとオンプレミスの両方のデバイス、デスクトップとスマートデバイス、サービスの正常性とパフォーマンス、および石油とガスの風景全体にわたるデバイスとセンサーのデータです。 - <strong>Shawn カッター、副社長、クォーラムビジネスソリューション</strong></p>

  </blockquote>


  <h2>OSIsoft</h2>


  <blockquote>

  <p>サンフランシスコベイ領域に基づく30年前のソフトウェア会社である<a href="https://www.osisoft.com/Default.aspx">OSIsoft</a>は、工業プロセスデータと運用インテリジェンスのグローバルリーダーです。 OSIsoft &rsquo; s <a href="https://www.osisoft.com/software-support/what-is-pi/What_Is_PI.aspx">PI システム</a> は、fortune 500 工業企業の65% を通じて、リアルタイムの意思決定支援および高度な分析のために、多数のセンサーベースの操作データを収集、格納、処理、および提示するために使用されています。</p>


  <p>OSIsoft では、センサーベースのデータインフラストラクチャテクノロジのクラウドネイティブの拡張機能の開発を開始しましたが、間もなく、分散型の大規模なシステムで動作するテレメトリソリューションについて見てきました。 2倍の要件を満たすものが必要でした。</p>


  <ul>
      <li>大量のログデータとメトリックデータを大規模に格納する機能</li>
      <li>このデータを確実にクエリする機能</li>
  </ul>


  <p>1つまたは他の要件を満たしていない複数のテクノロジを探索したので、Microsoft との密接な関係があるため、最終的には、その時点での内部の Microsoft テクノロジである Kusto が使用されました。 Kusto をテレメトリフレームワークに統合することを開始した後は、データ消費率に非常に感銘を加えました。 Kusto では、分散フレームワークで実行されている複数のマイクロサービスからテレメトリデータをログに記録できるようになりました。一方、スキーマとスキーマのないストレージの両方を使用して、将来の変更に適切に対応するメカニズムを確保します。 &ldquo;拡張性の高いマイクロサービスアーキテクチャを持つことで、テレメトリに関する困難な課題が生じます。 Kusto では、スケール、堅牢性、柔軟性の理想的な組み合わせを使用して、 &rdquo; OSIsoft のソフトウェア開発者である Sai Roop Tetali と言いました。</p>


  <p>kusto の SQL に似たクエリ機能は、ストレージ機能として優れています。 膨大な量のデータを処理し、必要な情報をすばやく提供する豊富なクエリを作成できます。 Kusto に移行したので、迅速なターンアラウンドによって問題の診断が改善されたことを確認しました。 &ldquo;Kusto では、非常に優れたクエリ機能を提供しています。 クエリ構文のような SQL を使用すると、チームが迅速に作業を開始し、サービスが大規模 &rdquo; に運用されていることをすぐに理解できるようになります。これは Tetali と言います。</p>


  <p>また、Kusto に格納されている未加工のテレメトリデータに対してクエリを実行することで、複数のテナントにわたる分散アプリケーションの使用状況を追跡することもできます。 &quot;これまで &rsquo; 、静的データを表示できるようになりました。 私たちは役に &rsquo; 立ちましたが、私たちの話 &rdquo; は、OSIsoft で Allison Muraski、サービス操作製品マネージャーと言います。 &ldquo;Kusto どんなは、静的なメトリックを返すだけでなく、集計と計算も提供しますが、データを手動で操作することなく、すばやく質問に回答できる方法でレンダリングします。&quot;</p>


  <p>&quot;kusto は Application Insights からの大きな飛躍です。 Kusto Explorer は、特に使用することができます。 簡単に使用できるようになったので、アプリケーション &quot; に関するより多くのデータを記録することを計画できます。これは、OSIsoft で cloud services イニシアチブリーダーであるチャド Chisholm と呼ばれています。 Kusto では、大量の高頻度テレメトリデータを格納できるだけでなく、さまざまな状況下でアプリケーションがどのように機能しているかについての洞察を得ることができる豊富なクエリ機能も用意されています。 Kusto を使用しているチームからのフィードバックは、OSIsoft にある他の複数のチームにロールアウトされています。 - <strong>Manas Talukdar、ソフトウェアエンジニアリングチームリーダー、OSIsoft、</strong></p>

  </blockquote>


  <p>注: OSIsoft は、 <a href="https://blogs.msdn.microsoft.com/bharry/2016/03/28/introducing-application-analytics/">Brian Harry &rsquo; s ブログ</a>で言及されている Application Insights 分析機能の内部コード名 &ldquo; kusto &rdquo; を示しています。</p>


  <p>詳細については、Channel 9 のビデオを参照してください Application Insights 分析機能の詳細については、こちらをご覧ください。</p>


  <p><iframe allowfullscreen="" frameborder="0" height="315" src="https://channel9.msdn.com/Events/Build/2016/T666/player" width="560"></iframe></p>


  <p>&nbsp;</p>


  <p><iframe allowfullscreen="" frameborder="0" height="315" src="https://channel9.msdn.com/Events/Build/2016/P591/player" width="560"></iframe></p>
