### YamlMime:Yaml
ms.openlocfilehash: 3948e103808c80aad9796850eb18098818b7f3e7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890453"
Slug: deep-diagnostics-for-web-apps-with-application-insights
Title: Application Insights を使用した Web Apps の詳細な診断
Summary: 現在、ニューヨークの Connect () 2015 では、アプリケーションの分析と診断のためのいくつかの発表を行っています。
Content: >-
  <p>現在、ニューヨークの Connect () 2015 では、次の製品で構成されるアプリケーション分析と診断に関して、マイクロソフトのオファリングについていくつかの発表を行っています。</p>


  <ul>
   <li><strong>Web apps および services</strong>: <a href="https://azure.microsoft.com/en-us/services/application-insights/">Visual Studio Application Insights</a></li>
   <li><strong>Mobile apps</strong>: <a href="https://hockeyapp.net/features/">HockeyApp</a></li>
  </ul>


  <p>ここでは、これらの各製品を強化し、Visual Studio や Visual Studio Team Services を含む ALM ツールとサービスへの統合を拡張することに焦点を合わせています。</p>


  <p><strong>HockeyApp</strong>は、iOS、OS X、Android、Windows デバイスアプリを構築するためのモバイル DevOps ソリューションであり、Xamarin、Cordova、Unity に基づくクロスプラットフォームアプリも提供します。 これを使用すると、ベータ テスト担当者にビルドを配布し、クラッシュ データを収集して、ユーザーからのフィードバックを得ることができます。 これは、簡単なビルド配置と作業項目の統合を可能にする Visual Studio Team Services と統合されて &rsquo; います。 詳細については、 <a href="https://support.hockeyapp.net/kb">HockeyApp サポート技術情報</a> を参照してください。 <a href="https://hockeyapp.net/blog/">HockeyApp のブログ</a>をご覧ください。</p>


  <p>この記事では、web アプリとサービスの<strong>Application Insights</strong>について説明します。</p>


  <h1>Visual Studio の統合環境</h1>


  <p>より広範な<a href="https://www.visualstudio.com/features/alm-devops-vs">Microsoft ALM/DevOps スタック</a>内の Application Insights の役割は、開発者がライブ web アプリの問題を検出して診断し、その影響に基づいて問題の優先順位を設定できるようにすることです。 開発チームは継続的デリバリーを採用している &rsquo; ので、急速に変化するアプリで発生していることについて、彼らにとって重要なことです。</p>


  <p>&rsquo;このため、開発プロセスの不可欠な部分を Application Insights しています。 既に、 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-start-monitoring-app-health-usage/#ide">Visual Studio 2013 と 2015</a>の一部として提供されているため、新規または既存のアプリを最小限の労力ですばやくオンボードできます。</p>


  <p><img alt="New Project" border="0" height="445" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/66d40ca0-0758-46b2-96de-10d536c4413c.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="[新しいプロジェクト]" width="640"></p>


  <p>Visual Studio 2015 Update 1 では、間もなくリリースされるようになりました。 IDE を離れることなく、Azure プレビューポータルで使用した &rsquo; のと同じ Application Insights 検索エクスペリエンスを開始できます。 つまり、問題を調査しているとき、またはバグをトリアージしている間に、運用環境のテレメトリを検索し、その結果を確認し、ブラウザーを起動しなくてもそのイベントの詳細を詳しく調べることができます。 これにより、Application Insights を開発ツールとして使用できるようになります。また、運用環境にプッシュする前にカスタムテレメトリを簡単にテストすることもできます。</p>


  <p><img alt="Application Insights Search experience" border="0" height="433" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1aa2b653-8075-4322-bd75-787afc4887a2.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="Application Insights 検索エクスペリエンス" width="640"></p>


  <p>また、Update 1 以降では、Application Insights が<a href="https://blogs.msdn.com/b/visualstudioalm/archive/2015/07/20/performance-and-diagnostic-tools-in-visual-studio-2015.aspx">Visual Studio 診断ハブ</a>と統合され、Application Insights SDK によって生成されるデータと F5 のデバッグエクスペリエンスがまとめられます。 SDK をプロジェクトにインストールするだけで、他の F5 診断調査に使用するのと同じイベントタイムラインに Application Insights テレメトリイベントが表示されるようになりました。</p>


  <p><img alt="Diagnostic Tools" border="0" height="470" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/308b81d6-7164-4a13-a7f7-5360d00f4da4.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="診断ツール" width="640"></p>


  <p>さらに、Visual Studio Team Services (VSTS) との統合がさらに表示されるようになり、運用前と運用後の間でブリッジを作成でき &rsquo; ます。 &rsquo; <a href="https://www.visualstudio.com/features/release-management-vs">VSTS Release Management</a>の配置注釈を Application Insights のチャートやグラフに表示できるので、パフォーマンスの変化をビルドと簡単に相互に関連付けることができます。</p>


  <h1>プロアクティブな問題の検出</h1>


  <p>Application Insights は、開発者向けに設計されています。 開発チームは、ops チームの壁を超えてアプリケーションをスローしなくなりました。開発サイクルは厳重であり、開発者はアプリが生きて &rsquo; いる間に何 &rsquo; が起こっているかを把握しておく必要があります。 しかし、ライブ環境とデバッグ環境またはテスト環境の大きな違いは、その中での条件の変動です。 ボード全体で応答時間が悪くなると、そのよう &rsquo; に見えやすくなりますが、一部のユーザーにのみ影響を与えるバリエーションを特定するのは困難な場合があります。</p>


  <p>ここでは、異常なセグメントとサービスの低下を識別する機械学習ベースのエクスペリエンスを導入しています。 これにより、問題の特性について深い洞察を得ることができるため、運用上の問題を軽減する時間が短縮されます。 たとえば、web アプリが特定の時間帯に特定のサーバーから応答を遅くした場合、問題の詳細を警告するメッセージが表示されます。 試してみる場合は、にお問い合わせ <a href="mailto:AppInsightsML@microsoft.com">AppInsightsML@microsoft.com</a> ください。お客様と協力してセットアップします。</p>


  <h1>診断ハブの Azure アプリケーション</h1>


  <p>microsoft は、Azure アプリ開発者が直面する主な問題点に対処しています。具体的に<a href="https://azure.microsoft.com/en-us/blog/tag/application-insights/">は</a>、パフォーマンスの低下の診断、アプリのデプロイとアップグレードの失敗、Azure アプリケーション診断のためのハブ Application Insights します。</p>


  <p><a href="https://azure.microsoft.com/en-us/blog/announcing-the-azure-sdk-2-8-for-net/">Azure SDK 2.8</a>以降では、Application Insights を使用して、Web ロール、Worker ロール、Windows vm から<a href="https://azure.microsoft.com/en-us/documentation/articles/cloud-services-dotnet-diagnostics/">Azure 診断</a>テレメトリにアクセスできるようになりました。 アプリケーション内から送信された応答時間、依存関係、およびカスタムイベントを使用して、これらのパフォーマンスカウンター Windows、Application Insights のイベントログとアプリトレースを関連付けることができるようになりました。 これで、問題を検出、トリアージ、診断するために必要なすべての情報を1か所で確認できます。</p>


  <h1>拡張可能でオープンで柔軟</h1>


  <p>Application Insights は、すぐに使用できるテレメトリを使用して値の大きなまとまりを提供しますが、アプリケーションからトレース、例外、ページビュー、依存関係などをキャプチャする<a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/">カスタムインストルメンテーション</a>を提供することもできます。 データ収集をより細かく制御できるように、最近、 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-sampling/">サンプリング</a>の概念を紹介しました。 基本的には、ポータルでアプリケーションデータの統計的に正しい分析を維持しながら、限定されたテレメトリのセットを収集して保存することができます。</p>


  <p>すべての sdk が<a href="https://github.com/Microsoft/ApplicationInsights-Home">オープンソースで</a>あり、コミュニティへの投稿をサポートしており GitHub 現在、多数の sdk が用意されており、ASP.NET、J2EE、Ruby、PHP、JavaScript、Node.JS、Python など、さまざまなプラットフォームをサポートしています。</p>


  <p>データを他のデータソースでマッシュアップする場合は、<a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-export-telemetry/">連続エクスポート</a>を設定して、SQL、Excel、Power BI などのツールでデータを分析することができます。 Power BI 用に最近発表された<a href="https://azure.microsoft.com/en-us/blog/application-insights-content-pack-for-power-bi/">Application Insights コンテンツパック</a>を使用すると、たとえば、売上データや web サイトの使用状況を同じリアルタイムの Power BI ダッシュボードにプルできます。</p>


  <p><img alt="Application Insights - Power BI" border="0" height="310" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e020ef0e-4c0d-4a22-a10b-dcdb74aa745f.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="Application Insights-Power BI" width="640"></p>


  <h1>まとめ</h1>


  <p>Application Insights は、お探しの強力なアプリケーション分析ソリューションとして拡大しています。 これには、パフォーマンスと例外の診断機能が用意されており、強力なログとメトリックの分析により、サービスの問題を効率的に検出、トリアージ、調査できます。</p>


  <p>私は、お客様の1人が Application Insights の経験を得ています。</p>


  <blockquote>

  <p>&quot;数日前に、&#39;マイナー&#39; 修正プログラムを展開しました。 広範なテストパスを実行する&#39;ませんでしたが、残念ながらいくつかの予期しない変更がペイロードにマージされたため、フロントエンドとバックエンドの間で非互換性が発生しました。 すぐにサーバーの例外が急増し、アラートが発行され、私たちは状況に気付きました。 Application Insights ポータルで数回クリックすると、問題を絞り込むために、例外呼び出しスタックから十分な情報が得られます。 私たちは直ちにロールバックし、損害を抑えることができました。 Application Insights は、DevOps サイクルのこの部分を非常に簡単で実用的なものにしました。&quot;</p>

  </blockquote>


  <p>新しい機能や改善された機能については、Application Insights ユーザーの声のページでお客様のアイデアを共有してください。質問がある場合は、 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights">Application Insights フォーラム</a>にアクセスしてください。</p>
