### YamlMime:Yaml
ms.openlocfilehash: a84f1f3924aacb81213782b778981b5d48d87edc
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891098"
Slug: deliver-ai-powered-application-search-with-azure-cognitive-search-and-ba-insight
Title: AI を利用したアプリケーション検索を Azure Cognitive Search BA Insight で提供する
Summary: データは指数関数的に増加し、データの 80% を超えるデータは構造化されていないので、組織は顧客に適切な情報を見つけて表示する課題を生み出しています。 組織に必要なのは、関連する情報と意味のあるパターンをすばやく特定することで、すべてのコンテンツから潜在的な分析情報を明らかにできるソリューションです。
Content: >-
  <p>データは指数関数的に増加し、データの 80% を超えるデータは構造化されていない <sup>1</sup> であり、組織が顧客に適切な情報を見つけて表示する課題を生み出しています。 組織に必要なのは、関連する情報と意味のあるパターンをすばやく特定することで、すべてのコンテンツから潜在的な分析情報を明らかにできるソリューションです。</p>


  <p><a href="https://azure.microsoft.com/en-us/solutions/knowledge-mining/" target="_blank">ナレッジ マイニングは</a> 、複数の AI 機能をまとめる AI のカテゴリです。開発者は、より迅速に分析情報を得ることができます。 Azure Cognitive Searchナレッジ マイニング ソリューションを使用すると、関連するコンテンツを大規模に簡単に識別して探索できます。</p>


  <p>クラウド <a href="https://azure.microsoft.com/en-us/services/search/" target="_blank">Azure Cognitive Search</a>、構造化されたコンテンツと非構造化コンテンツの取り込み、エンリッチメント、探索の間で AI 機能が含まれるまで進化しました。 開発者は API とツールを使用して、Web、モバイル、エンタープライズ アプリケーションのさまざまなコンテンツに対する豊富な検索エクスペリエンスを提供するソリューションを構築できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1c5f0527-800e-489b-b0aa-357805ff1a04.jpg"><img alt="Three phrases to Knowledge Minig with Cognitive Search: Ingest, Enrich, and Explore" border="0" height="380" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3825d129-7b61-4af7-9e9e-6ea06c242b9c.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="" width="1024"></a></p>


  <p>複数の業界のお客様は、アプリ検索Azure Cognitive Searchを提供するために、この機能を利用してきました。 <a href="https://channel9.msdn.com/Shows/AI-Show/Learn-how-Amway-is-using-Azure-Cognitive-Search-to-serve-better-and-faster-search-results-to-million" target="_blank">Amway は</a> 、アプリケーションをAzure Cognitive Searchし、販売者が製品情報をよりよく探索して理解するのに役立ちます。 その結果、販売者の検索時間が大幅に短縮され、毎日 4 倍の顧客を支援できます。 <a href="https://azure.microsoft.com/en-us/resources/videos/how-the-atlantic-is-preserving-published-history-with-azure-ai/" target="_blank">The Transition</a> は、Azure Cognitive Searchデジタル システムに移行するために使用されました。 これは、大きな物語から洞察を導き出し、過去と現在の間のつながりを構築するために、大島のライターを支援しました。</p>


  <p><a href="https://customers.microsoft.com/en-IN/story/811347-pwc-partner-professional-services-azure" target="_blank">PwC</a>、<a href="https://customers.microsoft.com/en-us/story/archive360-partner-professional-services-azure-search" target="_blank">Archive360</a>、<a href="https://customers.microsoft.com/en-us/story/764974-wix-partner-professional-services-azure-cognitive-search" target="_blank">Wix</a>、<a href="https://customers.microsoft.com/en-IN/story/762687-royal-ihc-manufacturing-azure-cognitive-search" target="_blank">OrangeNXT</a> などの多くのパートナーは、金融、小売、製造、その他の業界全体で顧客をサポートする Azure Cognitive Search を利用した検索ソリューションも構築されています。</p>


  <p>BA Insight では、新しいサービスや他のサービスを利用Azure Cognitive Searchされた Search for <a href="https://www.bainsight.com/azure-search/" target="_blank">Workplace</a> ソリューションAzure AIしました。 これにより、エンタープライズ ユーザーはストア別の情報の検索を停止し、情報の場所に関係なく、すべてのコンテンツにわたってユーザーにナレッジを提供できます。 ユーザーは、パーソナライズされた情報に関する推奨事項を取得し、コンテンツ リポジトリ、アプリケーション、データベースに、既存のコネクタを介して接続したり、SDK を使用してカスタム コネクタを作成したりすることができます。 自動分類子を使用すると、新しいコンテンツと既存のコンテンツを正確かつ一貫してタグ付けするときに、ユーザーからのタグ付けの負担が軽減されます。 アプリ内検索エクスペリエンスを使用すると、ユーザーは毎日使用するアプリケーション内から検索を実行し、既存の作業プラクティスにシームレスに統合できます。</p>


  <p>このソリューションは、BA Insights&rsquo; Enterprise Search を使用してクラウド サービスとして、または顧客環境内に&rsquo;デプロイできます。 Enterprise Search&mdash; をクラウド サービスとして使用すると、組織は、高度にパーソナライズされたインテリジェントで関連性の高いユーザー エクスペリエンスを提供するフル マネージドのエンタープライズ検索デプロイの恩恵を受け、カスタム開発の負担を軽減できます。 これは、Microsoft Teams、Microsoft Dynamics、Microsoft Exchange、Microsoft Outlook、Salesforce、Microsoft Edge、ServiceNow のようなアプリケーションと統合されています。</p>


  <p>最近、BA Insight Workplace と CEO、Massood Zarrabian、および Azure Cognitive Search のプリンシパル プログラム マネージャーである Liam Workplaceanagh は、Search for Workplace ソリューションに関するチャットに座っています。 <a href="https://azure.microsoft.com/en-us/resources/videos/azure-cognitive-search-x-ba-insight-joint-podcast" target="_blank">詳細については、このポッドキャストをご覧ください</a>。</p>


  <p>BA Insight&mdash; には特別なオファーも用意されています。BA Insight &ldquo;&rdquo; による Art <a href="https://www.bainsight.com/whats-possible/" target="_blank">of Possible</a> オファーを利用して、ソリューションがコンテンツとどのように動作するのかについての実際のビューを取得し、検索戦略セッションに参加して現在の環境と課題について話し合い、ユーザーの選択したチームのテストを手に入れすることができます。</p>


  <h2>その他の技術情報</h2>


  <ul>
      <li><a href="https://www.bainsight.com/azure-search/" target="_blank">BA Insight Search for Workplace</a>。&nbsp;</li>
      <li><a href="https://azure.microsoft.com/en-us/free/cognitive-search/">無料試用版Azure Cognitive Searchサインアップします</a>。</li>
      <li><a href="https://www.bainsight.com/resources/">BA Insight リソース</a>。</li>
  </ul>


  <p>&nbsp;</p>


  <p><sup>1</sup> <a href="https://azure.microsoft.com/en-us/resources/knowledge-mining-the-next-wave-of-artificial-intelligence-led-transformation/">つのナレッジ マイニング: 人工的</a>なデータ変換Intelligence-Led波</p>


  <ul>

  </ul>
