### YamlMime:Yaml
ms.openlocfilehash: 3dc45763484cf28029b43567a32fa733da3310d0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895140"
Slug: dev-test-starts-with-it-set-up-a-lob-application-in-a-hybrid-cloud-for-testing
Title: 'Dev-Test IT の使用開始: テスト用にハイブリッド クラウドに LOB アプリケーションを設定する'
Summary: 階層化された Web ベースのビジネス ライン オブ ビジネス アプリケーション (LOB アプリ) をデプロイしてテストするために必要なインフラストラクチャを作成するには、はるかに高速な方法があります。 Azure を使用すると、インターネット上の場所から LOB アプリの実稼働環境を簡単にシミュレートできます。
Content: >-
  <p><em>開発者の 65%&rsquo; は、開発テスト リソースを取得するには複雑すぎて時間がかかると言っています。*&rsquo; 必要はありません。</em></p>


  <p><em>このブログ シリーズでは、Microsoft&mdash; クラウドを利用して開発テスト環境を設定する方法に関するガイダンスを提供します。これにより、開発テストを数時間または数日で数分で利用できます。</em></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/32b2d55e-59a8-47d6-9d5e-df0b87bf9797.jpg"><img alt="IaaS_BlogThumb_250x143" border="0" height="137" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bd91e93e-4687-4e79-9b3f-5e493f2df651.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="IaaS_BlogThumb_250x143" width="240"></a></p>


  <p>階層&#39;された Web ベースのビジネス ライン オブ ビジネス アプリケーション (LOB アプリ) をデプロイしてテストするために必要なインフラストラクチャを作成するには、はるかに高速な方法があります。 Azure を使用すると、インターネット上の場所から LOB アプリの実稼働環境を簡単にシミュレートできます。</p>


  <p>Azure インフラストラクチャ サービスを使用して仮想マシン (VM) を起動し、仮想ネットワーク (VNet) を作成することで (<a href="https://azure.microsoft.com/en-us/blog/dev-test-starts-with-it-how-to-resource-vms-for-your-dev-test-environment/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure</a> VM と <a href="https://azure.microsoft.com/en-us/blog/dev-test-starts-with-it-how-to-create-a-dev-test-environment-in-azure/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">VNet</a> 上の他のリソースについては、前のブログ記事を参照)<a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-hybrid-cloud-environment-testing/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE"></a>、LOB アプリをデプロイして実行するハイブリッド クラウド テスト環境をすばやく作成できます。</p>


  <p>これらの詳細な手順に従って、ハイブリッド クラウド テスト環境で階層化された Web ベースの LOB アプリをデプロイしてテストするインフラストラクチャを <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-lobapp-hybrid-cloud-testing/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">作成します</a>。 ハイブリッド クラウド テスト環境における Web ベースの LOB アプリケーション では、SQL Server 2014 サーバーとインターネット インフォメーション サービス (IIS) サーバーをハイブリッド クラウドの基本構成に追加します。</p>


  <p>これは、Azure の SQL Server 2014 データベース バックエンドを使用して IIS でホストされている LOB アプリを開発してテストし、ハイブリッド クラウドベースの IT ワークロードのテストを実行するための最適な開始点です。</p>


  <p>Web 層またはデータベース層に新しい Azure VM を追加して、LOB アプリのテスト環境の容量を拡張します。 複数の IIS <a href="https://azure.microsoft.com/en-us/documentation/articles/load-balancer-internal-overview/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">サーバーにトラフィックを</a> 分散する内部ロード バランサーを追加します。</p>


  <p>開発とテストの後、Azure に高可用性 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-workload-high-availability-lob-application-overview/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">LOB</a> アプリをデプロイする手順に従って、実稼働環境を作成します。 Azure VNet はオンプレミス ネットワークの拡張機能なので、ユーザーは引き続き、アプリがオンプレミスのデータセンターにある場合と同様に、実稼働 LOB アプリ サーバーにアクセスします。</p>


  <p><a href="https://azure.microsoft.com/en-us/campaigns/dev-test-starts-with-it-webinar-series/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">IT ウェビナーを使用して、今後の開発テストに参加します</a>。<br>

  <a href="https://azure.microsoft.com/en-us/solutions/dev-test/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure での開発テストの詳細を確認します</a>。</p>


  <p>&nbsp;</p>


  <p>*ソース: テスト環境管理のビジネス ケースホワイトペーパー、Cognizant</p>
