### YamlMime:Yaml
ms.openlocfilehash: 0d46ca548d194829bb923313d289e2d3e45991c0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895558"
Slug: dev-test-starts-with-it-cloud-development-and-test-environments
Title: 'Dev-Test IT の使用: クラウドの開発およびテスト環境'
Summary: Azure での開発テストは、コラボレーション チームに最適であり、環境に対するアジャイル管理を提供します。
Content: >-
  <p><em>開発者の 65%&rsquo; は、開発テスト リソースを取得するには複雑すぎて時間がかかると言っています。*&rsquo; 必要はありません。</em></p>


  <p><em>このブログ シリーズでは、Microsoft &mdash; クラウドを利用して開発テスト環境を設定する方法に関するガイダンスを提供します。これにより、数時間または数日ではなく数分で開発テストを活用できます。</em></p>


  <p><br>

  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a7528a29-2455-46fc-be5a-35313845c861.jpg"><img alt="IaaS_BlogSeries" border="0" height="143" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b3676513-5962-4543-ac45-668f854fa24a.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="IaaS_BlogSeries" width="250"></a></p>


  <p>クラウドで一貫した開発テスト環境を作成するペースと経済力は、物理環境の従来のコストと課題と急激に対照的です。</p>


  <p>クラウド リソースには、探索が容易な、迅速でコスト効率の高いオプションが用意されています。 たとえば、Microsoft Azure、完全な開発テスト環境を独自の条件でプロビジョニングおよび管理するために必要なすべてが含めます。 仮想マシンは数分でプロビジョニングできます。数日または数週間も節約できます。 必要な数の仮想マシンをスピンアップし、ネットワークを作成し、開発者に割り当てる。 実際の使用シナリオをレプリケートし &mdash; 、実稼働規模でテストして、推測を解放する前に問題を特定して解決することができます。</p>


  <p>Azure での開発テストは、コラボレーション チームにも最適であり、環境に対するアジャイル管理を提供します。 リアルタイム使用率データを使用すると、コンピューティング リソースと使用状況を可視化し、制御できます。 無駄をなくし、簡単に変更を加え、制限を設定し、コストを制御します。 Azures&rsquo; の移動有料サービスを使用すると、需要に合わせてスケールアップまたはスケールダウンして、使用した分の料金のみを支払います。</p>


  <p>Microsoft とオープンソースの両方のアプリケーションとオペレーティング システムの広範なサポートにより、既存のアプリ、スキル、専門知識を活用できます。 System Center や PowerShell スクリプトなどの好みのツールを使用して、Azure での開発テスト環境のプロビジョニング、デプロイ、管理をより簡単にします。</p>


  <p>開発とテストのための VM のリソーシングに関する IT シリーズの <em>Dev-Test</em> の開始に関する次の投稿を探します。</p>


  <p><a href="https://azure.microsoft.com/en-us/pricing/free-trial?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE/">無料の Azure 試用版を開始します。</a></p>


  <p><a href="https://azure.microsoft.com/en-us/solutions/dev-test/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure での開発テストの詳細を確認します。</a></p>


  <p>&nbsp;</p>


  <p>*ソース: テスト環境管理のビジネス ケースホワイトペーパー、Cognizant</p>
