### YamlMime:Yaml
ms.openlocfilehash: 7405e92d0213fe96764d35d606f4d2a4f01d7b5c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910818"
Slug: dev-test-starts-with-it-set-up-a-hybrid-cloud-environment-for-testing
Title: 'Dev-Test 開始: テスト用のハイブリッドクラウド環境を設定する'
Summary: 実稼働を模倣した開発/テスト環境を作成すると、スケーラビリティと複雑さ (特にハイブリッドアプリケーションとワークロード) による課題が発生することがよくあります。 Azure を使用すると、オンプレミスネットワークに接続して拡張するクロスプレミス仮想ネットワークを簡単に作成できます。
Content: >-
  <p><em>開発者の65% は、開発/テストリソースを取得するのに時間がかかりすぎると言っ &rsquo; ています。 * これ &rsquo; は必要ありません。 </em></p>


  <p><em>このブログシリーズでは、Microsoft cloud を使用して開発/テスト環境をセットアップする方法について説明します。これにより、数時間または数日ではなく数分 &mdash; で開発/テストを最大限に活用できます。</em></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d7ed6200-a490-4f8e-a7bf-b43d685c4926.jpg"><img alt="IaaS_BlogSeries" border="0" height="143" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/694f926d-a3a1-42da-bcd4-4e42c5bb46b0.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="IaaS_BlogSeries" width="250"></a></p>


  <p>実稼働を模倣した開発/テスト環境を作成すると、スケーラビリティと複雑さ (特にハイブリッドアプリケーションとワークロード) による課題が発生することがよくあります。&nbsp;</p>


  <p>Azure を使用すると、オンプレミスネットワークに接続して拡張するクロスプレミス仮想ネットワークを簡単に作成できます ( <a href="https://azure.microsoft.com/en-us/blog/dev-test-starts-with-it-how-to-create-a-dev-test-environment-in-azure?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">クラウド専用仮想ネットワークの作成に役立つリソース</a>については、前述のブログエントリを参照してください)。</p>


  <p>Azure には、作成できる <a href="https://azure.microsoft.com/en-us/blog/new-set-of-hybrid-cloud-test-environments/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">ハイブリッドクラウドテスト環境の新しいセット</a> が用意されています。 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-hybrid-cloud-environment-testing/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">テスト用のハイブリッドクラウド環境を設定</a>するための手順に従って、Azure で開発テスト用の実際のハイブリッド運用環境をシミュレートできます。 ハイブリッド環境では、ローカルのインターネット接続とパブリック IP アドレスの1つを使用して、機能するクロスプレミス Azure 仮想ネットワークを設定します。 分離サブネット上の3台のコンピューターを使用して、この構成の簡略化されたイントラネットの部分を作成します。これは、1つの Hyper-v または他の仮想化サーバーでホストできます。</p>


  <p>この基本構成を拡張または調整して、クラウドベースのハイブリッド IT ワークロード用の開発/テスト環境または概念実証の構成を作成できます。 これは、Azure の機能を試して、アプリケーションの開発とテストを実行し、簡素化された IT ワークロードを試して実験し、インターネット上の場所を基準としたサイト間 VPN 接続のパフォーマンスを測定するための優れた方法です。</p>


  <p>インターネットに直接接続していない場合、または使用可能なパブリック IP アドレスがない場合は、シミュレートされた <a href="https://azure.microsoft.com/en-us/blog/simulated-hybrid-cloud-test-environment/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">ハイブリッドクラウドを</a>作成することもできます。 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-simulated-hybrid-cloud-environment-testing/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">テスト用にシミュレートされたハイブリッドクラウド環境を設定</a>するには、次の手順に従います。 この構成では、Azure インフラストラクチャコンポーネントのみを使用して、追加の Azure 仮想ネットワーク (VNet) に簡略化されたイントラネットを作成し、その2つを vnet 間接続にリンクします。 この構成は、真のクロスプレミス仮想ネットワークのエクスペリエンスを提供するものではありませんが、開発/テスト機能を実行し、簡素化された IT ワークロードを実行するために引き続き使用することができます。</p>


  <p>テスト用のハイブリッドクラウドでの SharePoint ファームの設定については、「<em>開発/テスト</em>での次の投稿」を参照してください。</p>


  <p><a href="https://azure.microsoft.com/en-us/pricing/free-trial/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">無料の Azure 試用版を開始</a>します。<br>詳細につい

  <a href="https://azure.microsoft.com/en-us/solutions/dev-test/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">ては、Azure での開発/テストに関するページを参照して</a>ください。</p>


  <p><br>

  <br>

  * ソース: テスト環境管理のビジネスケース、Cognizant</p>
