### YamlMime:Yaml
ms.openlocfilehash: 6713c172e51ac0c5d946239152c3cd1e3319125d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910809"
Slug: developing-applications-for-the-cloud-on-azure
Title: Azure でクラウド用のアプリケーションを開発する
Summary: '[この記事は SQL Azure チームによって提供されました。]Microsoft Patterns &amp; プラクティスグループは、クラウド用のアプリケーションの開発に関して、次のオンラインブックの2番目のボリュームを公開しました。'
Content: <p>[この記事は SQL Azure チームによって提供されました。]</p><p>microsoft Patterns &amp; プラクティスグループは、 <a href="https://msdn.microsoft.com/en-us/library/ff966499.aspx">microsoft Windows Azure Platform でクラウド用のアプリケーションを開発するため</a>の2番目の<b>オンライン</b>ブックボリュームを公開しました。 この本では、Windows Azure platform を使用して、クラウドで実行するマルチテナントサービスとしてのソフトウェア (SaaS) アプリケーションを作成する方法について説明します。 本書は、クラウドとの間で実行されるアプリケーションやサービスを設計、構築、または運用する、設計者、開発者、または情報技術 (IT) プロフェッショナルを対象としています。</p>  <p>アンケートアプリケーションでのデータの処理は、SQL Azure に関連する場合に特に重要です。 質問、懸念事項、コメントがありますか。 これらを下に投稿してください。</p>
