### YamlMime:Yaml
ms.openlocfilehash: 04ed39cbc6a8f17a0da5a5cf9c8b003502197d7d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139894421"
Slug: dont-sweat-it-move-your-applications-to-the-public-cloud-the-right-way
Title: 汗しないでください。アプリケーションをパブリッククラウドに適切な方法で移行してください
Summary: 'エディター &rsquo; のメモ: 今日 &rsquo; の投稿は、より大規模なソリューションアーキテクトである、パトリック mcclory います。 右スケール &reg; Inc. クラウド管理を使用すると、組織はビジネス-... を簡単に展開および管理できます'
Content: >-
  <p><b><img alt="Patrick McClory" height="153" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6521.PMcClory_5F00_headshot_2D00_200px.jpeg" style="float: right;" title="パトリック mcclory " width="144"> </b> <strong>Editor &rsquo; ) のメモ:</strong>今日 &rsquo; の投稿は、より大規模なソリューションアーキテクトである、<b>パトリック mcclory</b>います。 &reg;また、クラウド管理を使用すると、組織はパブリッククラウド、プライベートクラウド、およびハイブリッドクラウド全体でビジネスクリティカルなアプリケーション &nbsp; を簡単にデプロイおよび管理できます。 優れたスケールでは、クラウドコンピューティングのインフラストラクチャとアプリケーションの構成、監視、自動化、ガバナンスを効率的に行うことができます。</p>


  <p>&nbsp;</p>


  <p>&nbsp;</p>


  <p>&nbsp;</p>


  <p>&nbsp;</p>


  <p>分離 anxiety は、 <a href="https://azure.microsoft.com/en-us/overview/choosing-a-cloud-service-provider">クラウドコンピューティングへの移行</a>を行うときによく見られます。 しかし、it 業界は、長年のクラウドデプロイを成功させるために必要な基礎要素である、冗長性、スケーラビリティ、および自動化を実践しているとは考え &rsquo; られません。 これらのアイデアは必ずしも新しいものではありませんが、新しい Windows Azure Virtual Machines (サービスとしてのインフラストラクチャ) にまとめて適用することで、従来のデータセンターアプローチよりも大幅に時間がかからずに地理的に分散された高冗長性アーキテクチャを実現できます。 これは、すべての規模の企業にとって魅力的な提案です。ここでは、企業の規模を拡大 &rsquo; し、2006以来、アプリケーションをクラウドにデプロイしています。 クラウド管理のカテゴリを開拓、組織がクラウド環境でアプリケーションをデプロイして管理するためのプラットフォームを提供し、お客様がクラウドで数百万のサーバーを起動しました。 &nbsp;</p>


  <p>優れたスケールは azure の戦略的パートナー Windows であり、azure コミュニティ Windows に導入する方法として、世界中の最大のクラウドデプロイを実現するための独自のエクスペリエンスから開発したベストプラクティスの一部を共有したいと考えています。 では、始めましょう &rsquo; 。</p>


  <h4><b>冗長性はキングです</b>&nbsp;</h4>


  <p>負荷分散された web アプリケーション層とミラー化されたデータベースは、しばらくの間、システム展開の障害を管理するための一般的な構成です。クラウドの利点は、地理的に分散した展開を使用して、クライアントに近い場所にコンテンツを提供するだけでなく、データセンターの境界を越えて災害復旧機能を提供することです システムの冗長性を設計する際には、次の点を考慮する必要があります。</p>


  <ul>
   <li>Don&#39;サーバーの冗長性を計画するだけでは、サーバーの稼働時間が非常に役に立たないので、サーバーの稼働時間を&#39;ことができます。パブリック DNS インフラストラクチャも重要であることに注意してください。</li>
   <li>障害を計画し、プランを頻繁に実行します。 ディザスターリカバリーとフェールオーバーのテストは、長期的なアップタイムを保証するうえで重要です。 &nbsp;</li>
   <li>自動的にフェールオーバーするという意味について考えてみましょう。 一部のシステムでは、自動フェールオーバーによってデータが破損する可能性があります--サーバーの稼働時間だけでなく、 <i>サービス</i> の稼働時間とデータの整合性についても、フェールオーバー計画をテストして評価します。</li>
  </ul>


  <h4><b>スケーラビリティによって新しいドアが開かれます</b></h4>


  <p>需要に応じてスケールアップおよびスケールダウンできるため、長期的な総所有コストを最適化することができます。 &nbsp;&rsquo;少数のサーバーから、クラウド内の数百台のサーバーに数時間、またはアプリケーションがより多くのリソースを必要とする場合は、数分かかることがあります。 必要に応じて、アイドル状態のリソースに対して料金がかかることがないように、簡単にスケールダウンすることができます。 スケールを設計するときは、次のようにします。</p>


  <ul>
   <li>障害を計画するには、必ずデプロイを配布してください。</li>
   <li>リージョン間またはゾーン間のデータ転送のコストを評価します。</li>
   <li>パフォーマンスメトリックとシステムトリガーについて考えてみましょう。スケールアップのタイミングやスケールダウンが必要なタイミングが示されます。</li>
  </ul>


  <h4><b>すべて自動化 &hellip; &nbsp;&nbsp;</b>&nbsp;</h4>


  <p>自分で管理している menial タスクはすべて、それによって&#39;になります。 プロセスを自動化された方法で構築することで、テクノロジチームは、お客様の会社を前進させる更新プログラム、製品、機能、ソリューションについて、運用環境のサポート項目やその他の項目に専念することができます。 迅速かつオンデマンドでスケールアップとスケールダウンを利用する&#39;、サーバーを起動し、サーバーが完全に動作しているときに起動するまでの時間を最小限に抑えるために、自動化が重要です。 Web サーバーの場合、負荷分散のセットアップに接続するために、web サイト&#39;s コードのインストールの管理からすべてを行うことができます。 ミラー化されたデータベースサーバーの場合、インスタンスサイズのスケールアップとスケールダウンを非常に簡単に行うことができますが、ミラーリングセッションを再初期化するプロセスを自動化し、新しいセカンダリノードを導入することで、データ層の馬力 (およびコスト) を大幅に増減することができます。 次の点を考慮してください。</p>


  <ul>
   <li>プロビジョニング <i>と</i> 使用停止のプロセスを自動化する-両方のタスクセットは詳細なので、アプリケーションの可用性とアップタイムを確保するために100% の精度が必要です。</li>
   <li>PowerShell について学習し、使用する製品で使用できるコマンドレットについて説明します。 Msdeploy.exe と MSBuild について説明します。 作業を最小限にするために、再デプロイ&#39;テクノロジ用に既に作成されているツールを活用してください。</li>
   <li>これは、プロセスを改善するための時間として使用します。 使用している製品のベストプラクティスを確認し、新しく自動化されたプロセスに実装するための作業を行います。</li>
  </ul>


  <p>これらのアイデアを個別に作成することは、&#39;新しいものではありません。 しかし、これらを正しく実装することで、物理ハードウェアに専念する必要がなくなり、システム (またはチーム) が小さくなっている場合でも、高可用性ソリューションのベストプラクティスに集中できます。 大規模で小規模なデプロイは、冗長性、拡張性、自動化によってメリットがあります。 プロセスを改良するほど、短期間と長期間の成長を管理するチームの能力が向上します。 Azure Windows でこれらの基本的な手法を試したい場合は、高速で<a href="https://www.rightscale.com/s/azure.php?sd=Partner_Azure_Blog&amp;campaign=70170000000hPsp" target="_blank">無料のエディション</a>を使用して簡単に始めることができます。</p>
