### YamlMime:Yaml
ms.openlocfilehash: 3c0baff4c9becf3ca791f23586477a56eac8a13d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889502"
Slug: e-on-and-azure-sphere-building-smart-home-experiences-on-a-foundation-of-security
Title: 'E.ON と Azure Sphere: セキュリティを基盤にスマート ホーム エクスペリエンスを構築する'
Summary: IoT は、私たちの周りの世界との対話方法を再設定しています。
Content: >-
  <p><em>この投稿は、プリンシパル プログラム マネージャー の Lead である Danielle Damasius&nbsp; 氏によって共同Azure Sphere。</em></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4bb7f25d-fce9-4a0b-8d9f-65969814ba74.jpg"><img alt="IoT header" border="0" height="683" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b979b7fd-67a6-49c1-bb31-8417dc017145.jpg" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="IoT ヘッダー" width="1024"></a></p>


  <p>IoT は、私たちの周りの世界との対話方法を再設定しています。&nbsp;&mdash;&mdash;たとえば、私たちは、責任と競合する優先順位が常に私たちの時間に対して競合する文化に住んでいるスマート ホームの美しさは、人々が個人的なコレクション、創造性、達成、友人、家族を優先してバランスを取れるという点です。 コンシューマー スマート デバイスは、リモート コントロール機能と音声コマンドを使用して基本的なタスクを実行することで、時間を最大化するのに役立ちます。 これはほんの始めです。 &rsquo;より多くの接続されたデバイスが画像に入るに応じて、豊富なエクスペリエンスのファブリックの進化が見え、インテリジェント システムのレイヤーが組み合わせてニーズを予測し、アクションを自動化してから To Do リストにヒットします。 アプライアンスは、壊れる前にサービスが提供され、供給と食品は、ニーズを予測して提供されます。 これらのスマート エクスペリエンスの直感的な機能は、摩擦を取り除き、環境を流動的に制御し、毎日の生活のあらゆる側面を最適化します。 このインテリジェントエッジにより、人のコストと&mdash;時間を節約し、環境フットプリントを下げ、人々がさらに多くの成果を上げるのに大きな力を与えます。</p>


  <p>これは、スマート エクスペリエンスを開発する企業にとってゴールデン タイムです。イノベーションの機会は、想像の範囲に限定されます。 永続的な課題はセキュリティです。この新しい世界のリスクランドスケープはまだマップされています。&nbsp; この新しい領域に進むには、アジャイルで応答性が高く、常に学習するインテリジェントなセキュリティのプラットフォーム上にエクスペリエンスを構築する必要があります。 現在、セキュリティの責任を担う企業は、将来を推進する信頼できるブランドとして、大きな利点を持つでしょう。</p>


  <h2>E.ON: ホーム エネルギー管理のための新しいパラダイムの作成</h2>


  <p>ヨーロッパをリードする&rsquo;エネルギー企業の 1 つである E.ON は、自宅に存在するより複雑な関係の 1 つ、つまりエネルギーがホーム環境を維持する方法に取り組んでいます。 エネルギー消費&rsquo;に対する会社の前向き思考アプローチにより、人々は自分の生活の質をキュレーションする力を得て、自分の生活の望み方の詳細を定義できます。</p>


  <p>E.ON Home Energy Management は、パーソナライズされたソリューションにホーム エネルギー リソースをまとめ、顧客の手に 1 つの応答性の高いエネルギー管理ソリューションを提供します。 ソーラー パネル、バッテリ、電気自動車のホーム充電ポイントなど、暖房、照明、エネルギー源はすべて協力して、人々が自宅のエネルギー プロファイルを定義して管理するのに役立ちます。 ユーザーは、リソースと家の&mdash;目標のバランスを取る統一されたアプローチを通じて、利便性、快適さ、コスト削減、または省エネルギーを優先することができます。 E.ON はエネルギーの独立の支持者として、持続可能なエネルギーを自宅に組み込み、それを物理的にバッテリに格納したり、事実上 E.ON Solar Cloud に格納したりするために、顧客にソーラー ソリューションを提供します。</p>


  <p>エネルギーは重要なリソースです。 すべての利便性、私たちが持っているすべての基本的な必要性は、エネルギーへのアクセスに依存します。多くの場合、エネルギーへのアクセスは、生き生きまたは死亡の問題になる場合があります。 E.ON は、非常に多くの利害を受け、セキュリティがビジョンの基礎コンポーネントでなければならないと認識しています。 彼らは、脅威の&mdash;状況が変化してもデバイスを保護し続ける高度なセキュリティセキュリティと、提供する高度なエクスペリエンスを一致させる必要がある、と理解しています。 選択&rsquo;したAzure Sphere。</p>


  <p>E.ON は、ヨーロッパ全体で 3,200&rsquo;&rsquo; 万を超える顧客のニーズに対応し、今日の現代の住宅や企業のニーズを満たす信頼できるエネルギー ソリューションを一貫して提供することでブランドを構築しました。 Azure Sphere を使用してデバイスからクラウドにエクスペリエンスがセキュリティで保護されているのを知ることにより、E.ON は、顧客、要するに、ブランドが時間のと一緒に保護されるという自信を持ってイノベーションを起こします。</p>


  <p>E.ON は、2019&rsquo; 年に E.ON Home ソリューションの広範な可用性を準備する中で、Microsoft のチームと提携して、Azure Sphere を使用してエコシステム全体でデバイスの電源を供給し、セキュリティ保護する必要があります。 私たちは、ビジョンを実現する多様なデバイス (暖房要素から電気自動車のヒーター、ソーラー パネル、照明ソリューション、バッテリまで) が、すべて利用可能な最高基準のセキュリティを満たします。 E.ON と Microsoft は、将来性の高いテクノロジ システムを設計し、今日の将来の想像されるテクノロジをお客様に提供します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c099c445-ba22-4c39-ad70-950599d15a8b.png"><img alt="E.ON smart home energy consumption graph." border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e27349c1-d673-428e-8912-974a3c7a1430.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="Iot" width="1024"></a></p>


  <blockquote>

  <p style="margin-left: 40px;">E.ON の私たちは、ますます化され、つながっている家を信じ、お客様の自宅での快適さと生活の質<em>を向上しています。&ldquo;E.ON Home Energy Management を使用すると、ホーム内のエネルギー インフラストラクチャをシームレスかつ安全な方法でまとめます。これは、自己生成、ストレージ、暖房と冷却、電気自動車の充電、またはホーム オートメーションなどです。お客様は、エネルギーの独立を可能にしながら、コストや持続可能性を損なうことなく快適な環境を楽しめばよいでしょう。Microsoft とチームを組み、Azure Sphereを活用することで、IoT と AI の機会と力を、安全性が高く、信頼され、スケーラブルな方法で活用できます。&rdquo; - </em>Alex Cirlan、E.ON、Global DomainHEM &ndash; &amp; Software のヘッド</p>

  </blockquote>


  <h2>セキュリティの責任を受け入Azure Sphere</h2>


  <p>家族を<a href="https://www.cnet.com/news/fridge-caught-sending-spam-emails-in-botnet-attack/">監視するために使用</a>されているスパムモニターと赤<a href="https://www.marketwatch.com/story/woman-claims-hacker-used-baby-monitor-to-spy-on-her-in-her-bedroom-2018-06-07"></a>ん子モニターを送信する冷却装置に関する見出しは、遠く未来的に見えるかもしれませんが、その結果は非常に現実的です。 デバイスが侵害された場合、プライバシー、データ、インフラストラクチャ、物理的なセキュリティに影響を与える可能性があります。 スマート エクスペリエンスが可能性と想像によって進化し続けるにつれて、脅威のランドスケープも進化し、セキュリティの問題はますます深刻になります。</p>


  <p>ユーザーがスマート エクスペリエンス&rsquo;と最先端のテクノロジに対して個人的な生活と空間を開く場合、ユーザーがこれらのエクスペリエンスを信頼できる必要があります。 それ以上に、それは&rsquo;私たちの責任です。 スマートを再定義する必要があります。 はい。スマート エクスペリエンスは直感的で、洞察力が高く、使いやすいです。 ただし、もう 1 つ追加する必要があります。 スマート製品は安全である必要があります。 このため、デバイスの製造元が、Azure Sphereでセキュリティで保護されたスマート製品を簡単に作成するために、この機能を構築しました。 セキュリティに対する詳細な防御アプローチの詳細については、こちらを <a href="https://azure.microsoft.com/en-us/blog/azure-sphere-is-here-public-preview-and-dev-kits-now-available/">参照してください</a>。</p>


  <p>デバイスの製造元と話し合って、Azure Sphere、次の 3 つのことを常に耳にします。</p>


  <ul>
      <li>彼らは、ユーザーがAzure Sphereすのが好きです。 弊社のVisual Studio環境は、製品をより迅速に市場に出すのに役立ちます。</li>
      <li>彼らは、自分Azure Sphere &ndash; ブランドと顧客を保護するセキュリティで保護されているという自信を与えるのが好きです。</li>
      <li>彼らは価値Azure Sphere&rsquo;好きです。 MediaTeks&rsquo; MT3620 Azure Sphereソリューションの価格は 8.65 ドル以下です。 この 1 回の前払い料金には、次が含まれます。</li>
      <li>MT3620 は、最初に認定Azure Sphere MCU です</li>
      <li>継続的Azure Sphere OS サービス更新プログラムを含む、新しい OS ライセンス</li>
      <li>Azure Sphere Security Service のデバイス ライセンス。これには、継続的な監視と更新プログラムが含まれます</li>
  </ul>


  <p><em>正確な価格は、ボリュームなどの要因によって異なります。新しい認定された MCUs を追加すると、価格は、その機能と製造元の要件によって異なると予想されます。 </em><a href="https://azure.microsoft.com/en-us/pricing/details/azure-sphere"><em>詳細については、Web サイトを参照してください。</em></a></p>


  <h2>概要開発キットAzure Sphereパブリック プレビュー エクスペリエンスについて</h2>


  <p>&rsquo;本日は、<a href="https://azure.microsoft.com/en-us/services/azure-sphere/">Azure Sphere</a> 開発キットの広範な可用性と、Azure Sphere OS、Azure Sphere Security Service、Azure Sphere 用の Visual Studio ツールのパブリック プレビューをお知らせします。 これらのツールを組み合わせて使用すると、新しい製品やエクスペリエンスのプロトタイプ作成を開始するために必要Azure Sphere。</p>


  <p>より多くのユーザーに、何十&rsquo;億もの接続されたデバイスを自分の生活に招待する必要がある場合は、保護されていることを確認する必要があります。&nbsp; デバイスをセキュリティで保護すると、将来をセキュリティで保護できます。</p>


  <p>IoT の詳細<a href="https://azure.microsoft.com/en-us/overview/iot/">Microsoft Azureする</a></p>
