### YamlMime:Yaml
ms.openlocfilehash: 6f890942d944b081961500d88bbb5442e0a10fa6
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893974"
Slug: empower-an-adaptive-it-environment-for-people-processes-and-culture-with-inside-azure-for-it
Title: Inside Azure for IT を使用してアダプティブ IT 環境を強化する
Summary: 7 月に、クラウドプロフェッショナルが Azure のベスト プラクティスと分析情報を使用して IT 運用を変革するように設計されたオンライン技術スキル リソースである Inside Azure for IT を発表しました。 このチームは、It 向け Inside Azure を使用して、事実上あらゆる場所から接続および共同作業を行ったユーザーの数に非常に感激しています。
Content: >-
  <p>7 月に、クラウドプロフェッショナルが Azure のベスト プラクティスと分析情報を使用して IT 運用を変革するように設計されたオンライン技術スキル リソースである Inside <a href="https://azure.microsoft.com/en-us/blog/enhance-your-cloud-skills-and-accelerate-digital-transformation-with-inside-azure-for-it/" target="_blank">Azure for IT</a> を発表しました。 このチームは、It 向け <a href="https://azure.microsoft.com/en-us/overview/what-is-azure/iaas/it-resources/?wt.mc_id=IAFITc" target="_blank">Inside Azure</a> を使用して、事実上あらゆる場所から接続および共同作業を行ったユーザーの数に非常に感激しています。 毎月、ライブの <a href="https://techcommunity.microsoft.com/t5/azure-infrastructure/inside-azure-for-it-ask-the-product-experts-live-save-the-date/ba-p/2461257" target="_blank">ask-the-product-experts</a>&nbsp;&nbsp; セッションに参加した場合でも、私がホストする新しいビデオ シリーズの学びや、Azure チームと私は参加、フィードバック、パートナーシップに感謝しています。&nbsp;</p>


  <p>IT ジョブが難しくなってきるのがわかっています。 あなたは&rsquo;、従業員がローカルか世界中に&mdash;分散している場合でも、ハイブリッド作業を可能にする必要があります。 これは、クラウドを&rsquo;迅速に導入することを意味し、これを行う一方で、セキュリティ、可用性、一貫性のある管理を確保するために、内部チームや開発者とより良く取り組む必要がありました。</p>


  <p>私は最近、IT ディレクターと話をしました。従業員が自宅やオフィスから仕事を行えるという大きな仕事をしたにもかかわらず、従業員はこれを急いで、古い IT&rsquo; プロセスを残しました。 IT 管理とガバナンスを&nbsp;改善して、より適応性と柔軟性を高める上で、シンプルで影響の大きな手順について説明しました。 今日は&rsquo;、業界や規模に関係なく、現在使用できるヒントを提供するためのアドバイスの一部を紹介する、IT&rsquo; 向け Inside Azure の第 2 回の第 2 回を紹介します。</p>


  <h2>技術とクラウド&nbsp;スキルのリソースを活用する</h2>


  <p>この&rsquo;エピソードを 3 つの &ldquo;説明可能な&rdquo; セグメントに分割しました。そのため、現時点で必要なアドバイスに基づいてトピック間を移動できます。</p>


  <h3>セグメント 1: Connectと Azure を使用して従業員Microsoft 365を作成する</h3>


  <p>カスタマー サク成功エンジニアリングの副社長である Tara Roth が、私と一緒に、ユーザーがどこからでも、任意のデバイスで仮想的に作業できる安全な方法について <a href="https://aka.ms/Episode2-pt1" target="_blank">説明します</a>。 新しい従業員が初めて設定されるのを確認する以外に、ユーザーの実行を続けるために必要なツールを使用して回復性と機敏性を構築する方法について説明します。</p>


  <h3>セグメント 2: ハイブリッドおよび分散 IT 環境を大規模に管理する</h3>


  <p>Windows Server のプリンシパル プログラム マネージャーである Jeff Windows と、クラウドを使用したビジネス プロセスとレガシ システムの最新化について説明し、運用方法を<a href="https://aka.ms/Episode2-pt2" target="_blank">改善します</a>。 Jeff は、&mdash;&mdash;リソースの管理、監視、セキュリティ保護の方法を自動化するための実際の例も共有しています。リソースがどこにあるかは無視して、操作を簡素化し、時間を節約できます。</p>


  <h3>セグメント 3: DevOpsを使用して、任意の場所でクラウドネイティブ アプリを構築する</h3>


  <p>最後に、VS および .NET のパートナー プログラム マネージャーである Scott Hanselman 氏が参加し、開発チームとの<a href="https://aka.ms/Episode2-pt3" target="_blank"></a>共同作業や、DevOps カルチャでデジタル変革を推進するクラウドネイティブ アプリケーションの構築に関するベスト プラクティスを共有しました。&rsquo; Scott と私は、リモート エンジニアリングのさまざまな段階で課題を克服する方法について説明します。</p>


  <p>これらの会話&rsquo;を通して観察すると、人、インフラストラクチャ プロセス、投資を強化する場合、小さな手順によって大きな結果が得られます。 これらの学習を適用すると、リモート ソフトウェア開発と IT 管理のすべてのステップで課題を克服するのに役立ちます。</p>


  <h2>It 向け Inside Azure を最新の状態に</h2>


  <p>It 向けInside&nbsp; Azure を通じて、さらに多くの技術的およびクラウド スキルのリソースを利用できます。 生産性、デジタル変革、イノベーションを可能にするように設計されたベスト プラクティスとリソースを使用して、アダプティブ IT 環境を強化する方法について学習します。 テクニカル トレーニング ビデオを活用し、It 向け Inside Azure を使用してこれらのシナリオ <a href="https://azure.microsoft.com/en-us/overview/what-is-azure/iaas/it-resources/?wt.mc_id=IAFITc" target="_blank">を実装する方法について説明します</a>。</p>


  <ul>
      <li>概要ガイド: <a href="https://azure.microsoft.com/en-us/resources/azure-strategy-and-implementation-guide-fourth-edition/?wt.mc_id=IAFITc" target="_blank">Azure の戦略と実装ガイドに関するページを参照してください</a>。</li>
      <li>スケジュールを参照してください。 <a href="https://techcommunity.microsoft.com/t5/azure-infrastructure/inside-azure-for-it-ask-the-product-experts-live-save-the-date/ba-p/2461257" target="_blank">製品の専門家にライブで質問してください</a>。</li>
      <li>クラウドと Azure を使用Connect&nbsp;<a href="https://aka.ms/Episode2-pt1" target="_blank">従業員のセグメントをMicrosoft 365見る</a>。</li>
      <li>セグメント 2 を見る:&nbsp;<a href="https://aka.ms/Episode2-pt2" target="_blank">ハイブリッドおよび分散 IT 環境を大規模に管理する</a>。</li>
      <li>セグメント 3 を見る:&nbsp;<a href="https://aka.ms/Episode2-pt3" target="_blank">DevOpsを使用して、任意の場所でクラウドネイティブ アプリを構築します</a>。</li>
  </ul>
