### YamlMime:Yaml
ms.openlocfilehash: 22fb7e26bd8efcbcec47eff5f6ecea21c11ce904
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889825"
Slug: enable-client-side-monitoring-in-azure-with-application-insights
Title: Application インサイト を使用して Azure でクライアント側の監視を有効にする
Summary: Application インサイト JavaScript SDK を使用すると、Web ページまたはアプリのパフォーマンスと使用状況を収集して調査できます。 これまでは、 を手動で追加することでオンボードを提供しました。
Content: >-
  <p>Application インサイト JavaScript SDK を使用すると、Web ページまたはアプリのパフォーマンスと使用状況を収集して調査できます。 これまで、アプリケーションにスクリプトを手動で追加して再デプロイすることで、オンボードを提供しました。 スクリプトの手動追加は引き続きサポートされますが、最近、数回のクリックで Azure portal からクライアント側の監視を追加する機能も追加されました。</p>


  <h1>有効化</h1>


  <p>Azure で Application Insights を有効にしている場合は、ページ ビューとユーザー テレメトリを追加できます。 サーバー側の監視をオンに切り替える方法については、ドキュメントを参照 <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-monitor-performance-live-website-now">してください</a>。</p>


  <p>&nbsp;&nbsp;&nbsp;&nbsp; 1. [設定 -&gt;&nbsp;Application 設定</p>


  <p><img alt="step one" border="0" height="529" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/debb70c9-16fe-49f3-9856-31e6c10815ed.png" style="margin: 0px auto; border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="手順 1" width="661"></p>


  <p>&nbsp;&nbsp;&nbsp;&nbsp; 2. [アプリ設定] で、新しいキー値ペアを追加します。</p>


  <blockquote>

  <p style="margin-left: 40px;">キー: APPINSIGHTS_JAVASCRIPT_ENABLED</p>

  </blockquote>


  <blockquote>

  <p style="margin-left: 40px;">値: true</p>


  <p><img alt="step two" border="0" height="141" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/97761839-1c18-42cb-9c43-a15eb3b05ab0.png" style="margin: 0px auto; border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="手順 2" width="697"></p>


  <p>&nbsp;</p>

  </blockquote>


  <p>&nbsp;&nbsp;&nbsp;&nbsp; 3. 設定を保存し、[概要] タブでアプリを再起動します。</p>


  <p>&nbsp;</p>


  <p>Application Insights JavaScript SDK が各 Web ページに挿入されるようになりました。</p>


  <h1>フィードバック</h1>


  <p>JavaScript SDK に関して質問がある場合、または問題が発生した場合は、次のページで問題を<a href="https://github.com/Microsoft/ApplicationInsights-JS">GitHub。</a></p>
