### YamlMime:Yaml
ms.openlocfilehash: cfaa0ff752588315023b603f497ddef1862e4e0a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890807"
Slug: enhancements-in-application-insights-profiler-and-snapshot-debugger
Title: Application インサイト Profiler と スナップショット デバッガー の機能強化
Summary: Application インサイト Profiler と スナップショット デバッガー に関する一連の機能強化をお知らせします。
Content: >-
  <p>Application インサイト Profiler と スナップショット デバッガー に関する一連の機能強化をお知らせします。 プロファイラーは、読み込み中に Web アプリのパフォーマンスを低下させるコード行を識別します。 スナップショット デバッガーランタイム例外呼び出し履歴とローカル変数をキャプチャして、コード内の問題を特定します。 ユーザーがツールを簡単かつ便利に使用できるよう、Profiler と スナップショット デバッガー 用の次の新機能が提供されました。</p>


  <h2>Profiler と インサイトを使用したアプリケーション の有効化スナップショット デバッガー</h2>


  <p>新しく強化された Application インサイト有効化エクスペリエンスにより、Profiler と スナップショット デバッガー は、Application インサイト で有効にする既定のオプションです。</p>


  <ul>
   <li><strong>Web スナップショット デバッガー</strong>を再デプロイせずに有効にする: ASP.NET コア Web アプリの場合、スナップショット デバッガーは App インサイト を有効にする際の単純な既定のオプションです。 以前は、アプリケーションをインストールして例外追跡コードを追加NuGetを変更する必要があります。 これで、&rsquo;アプリ設定を通 ASP.NET ホストしているコア を介して行われるので、再デプロイは必要ありません。 ASP.NET サポートは間もなく提供される予定です。</li>
   <li>
   <p><strong>Application インサイトで Profiler</strong> を有効にする: 以前は別の Profiler 構成ウィンドウで Profiler を有効にします。追加の手順が必要です。 これは不要です。</p>
   </li>
  </ul>


  <h3>プロファイラー</h3>


  <ul>
   <li>
   <p><strong>オンデマンド プロファイラー</strong>: 必要に応じて、いつでも Web アプリでプロファイラーの実行セッションをトリガーします。 以前は、Profiler はランダムに 5% の時間実行され、重要なトレースのキャプチャが欠落する可能性があります。 新しいオンデマンド プロファイラー機能では、ユーザーが必要に応じていつでもトレースをキャプチャできるので、この問題は解決されます。</p>
   </li>
   <li>
   <p><strong>Linux 上の ASP.NET コア</strong>のプロファイラー: Profiler は、Linux App Servicesコア 2.0 docker ASP.NET で動作します。 今後、より多くのプラットフォームがサポートされる予定です。</p>
   </li>
  </ul>


  <h3>スナップショット デバッガー</h3>


  <ul>
   <li>
   <p><strong>スナップショットの正常なチェック</strong>: Web アプリランタイムの例外にスナップショットが関連付けされていない理由をスマートに診断します。 より多くの分析情報と可視性を備え、スナップショット デバッガーの簡単かつ迅速なトラブルシューティングを行います。</p>
   </li>
  </ul>


  <h2>Profiler を有効にしてスナップショット デバッガーを今まで以上に簡単に実行する</h2>


  <p>アプリの有効化インサイトエクスペリエンスを強化App Services。 Web アプリケーションを新しいリソースにデプロイApp Servicesします。 後で、Web アプリの速度が遅い、または例外がスローされているのに気付きます。 Web アプリで App インサイトを有効&rsquo;にして、何が起こっているのかを監視および診断する必要があります。 もちろん、監視サービスを&rsquo;有効にするために Web アプリを再デプロイしたくはないと思います。</p>


  <p>新しい有効化エクスペリエンスを使用すると、エントリ ポイントを簡単に見つけて、[アプリ] を [インサイト有効<strong>設定 |アプリケーション インサイト</strong>。 プロファイラー <strong>を有効に</strong> し、アプリのパフォーマンスが低下し、ランタイム例外を診断スナップショット デバッガーするために、コード レベルの診断が既定でオンになっています。</p>


  <p>Profiler エージェントは新しい App インサイト サイト拡張機能にインストールされ、アプリ設定によって有効になっているため、このようなプロファイラーを簡単に有効にできます。 スナップショット デバッガーホスティング ASP.NET を使用して有効にすると、環境変数が設定されている場合、ランタイムにはアセンブリが含まれます。</p>


  <p>新しい有効化エクスペリエンスの UI を使用すると、すべてを 1 つの手順で構成できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/41666712-3cd4-4986-b372-4ee59b1ef39d.png"><img alt="Enablement_UI" border="0" height="1140" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/be4833d3-d95d-4ec2-bfd3-2a16bb5e7818.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Enablement_UI" width="1509"></a></p>


  <p>プロファイラーと設定を有効App Services次の App スナップショット デバッガー。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/64944680-41f5-4e38-a53f-a499ab280e99.png"><img alt="Enablement_AppSettings" border="0" height="264" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7e9766e5-d177-4eef-b4de-24ea63b328c3.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Enablement_AppSettings" width="992"></a></p>


  <h2>オンデマンドで興味深いプロファイラー トレースをキャプチャする</h2>


  <p>新しいオンデマンド トリガー プロファイラー機能を導入して、楽しみに思います。 重要なトレースが見つからない場合は、[プロファイラーの構成] ウィンドウに移動し、[今すぐ<strong></strong>プロファイル] ボタンをクリックして、必要に応じてプロファイラーを起動します。 次のような状況の場合は、プロファイラーの実行をトリガーできます。</p>


  <ul>
   <li>
   <p>プロファイラーの使用を開始するには、最初のトレースをキャプチャして、すべてが動作しているテストを行います。</p>
   </li>
   <li>
   <p>ロード テストの実行時にトレースを効率的かつ確実にキャプチャする必要があります。</p>
   </li>
   <li>
   <p>現在発生しているパフォーマンスの問題のトレースを迅速にキャプチャする必要があります。</p>
   </li>
  </ul>


  <p>さらに、プロファイラーの実行履歴の一覧からプロファイラーの実行状況を確認できます。</p>


  <p>詳細については、「 <a href="https://go.microsoft.com/fwlink/?linkid=873212" target="_blank">Profiler を手動でトリガーする」を参照してください。</a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7f58b5df-fa71-4956-b3c9-85da6668048f.png"><img alt="OnDemand-Profiler" border="0" height="1003" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/95831846-bb56-490e-8087-856a0ed199a7.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="OnDemand-Profiler" width="2423"></a></p>


  <h2>Profiler を使用して Linux ASP.NET Coreのパフォーマンスを調査する</h2>


  <p>Event Pipe テクノロジを利用して、ASP.NET でホストされている Linux コンテナー内で実行されているコア Web アプリのトレースをキャプチャApp Services。 プロファイラーは、トレースをキャプチャするために ASP.NET インプロックで実行され、オーバーヘッドが少なくなります。 現在のプレビュー リリースは、評価のみを目的とします。 Application インサイト <a href="https://docs.microsoft.com/azure/application-insights/app-insights-profiler-aspnetcore-linux">Profiler ASP.NET Core を使用した Azure Linux Web アプリのプロファイルに関するページインサイトしてみてください</a>。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/34e779e4-136f-4401-956a-56bc4286b62e.png"><img alt="Linux_profiler" border="0" height="482" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6957a22d-cf9f-4aac-a807-e3be7e971d4b.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Linux_profiler" width="1467"></a></p>


  <h2>スナップショットの正常性チェックで問題をすばやく把握して解決する</h2>


  <p>お客様から寄せられたフィードバックの 1 つで、例外のスナップショットが表示できない場合がある場合に対処するために、ユーザーがスナップショットが見つからない理由をスマートに診断するのに役立つ新しい機能を構築しました。 サービスは、ユーザー入力に基づいてスナップショット デバッガー正常性チェックを実行します。 スナップショットが見つからない&rsquo;場合は、[エンドツーエンドのトレース ビューアー] ブレードに何も表示されない代わりに、ユーザーが何が起こっているのかをトラブルシューティングするためのリンクが表示されます。 これが、お客様が根本原因を特定し、問題を解決するのにすぐに役立つ可能性があります。 お客様の成功を可能にするために常に努&rsquo; めています。</p>


  <p>詳細については、「スナップショット デバッガー <a href="https://go.microsoft.com/fwlink/?linkid=873213">のトラブルシューティング」を参照してください</a>。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b857ee85-9c4d-4c18-83e3-24c08ae29e65.png"><img alt="healthcheck2" border="0" height="1147" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/34e3ba3b-946b-4309-a640-7f5d2e4a3d7f.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="healthcheck2" width="2303"></a></p>


  <h2><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/af253ae0-5a1f-47e4-95c9-9734ff89d086.png"><img alt="SnapshotHealthCheck" border="0" height="1233" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7788e55d-7567-4018-abb2-009b7e1313aa.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="SnapshotHealthCheck" width="2309"></a></h2>


  <h2>次の手順</h2>


  <p>今すぐ Web アプリスナップショット デバッガープロファイラーとアプリを有効にしてください。 または でフィードバックを送信<a href="mailto:  serviceprofilerhelp@microsoft.com">serviceprofilerhelp@microsoft.com</a>します<a href="mailto:snapshothelp@microsoft.com">snapshothelp@microsoft.com</a>。 この投稿に直接返信することもできます。</p>
