### YamlMime:Yaml
ms.openlocfilehash: 7f5c3ca460a631e9435f9cef96df4e6b553faf97
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909860"
Slug: enhanced-app-usage-monitoring-and-investigative-features-in-azure-application-insights
Title: Azure アプリケーションインサイトのアプリの使用状況の監視機能と調査機能が強化されました
Summary: "アプリケーションのパフォーマンスの問題を調査するときに、情報にスクランブルをかけることができますか。 アプリケーションの使用状況とインシデントを利害関係者に対して収集してレポートするのに、数時間 (場合によっては数日) かかりますか。 \n"
Content: >-
  <p>アプリケーションのパフォーマンスの問題を調査するときに、情報にスクランブルをかけることができますか。 アプリケーションの使用状況とインシデントを利害関係者に対して収集してレポートするのに、数時間 (場合によっては数日) かかりますか。</p>


  <p><a href="https://azure.microsoft.com/services/application-insights/">Azure アプリケーションインサイト</a>を使用すると、機械学習やアドホック分析に基づいてリアルタイムの洞察を提供することで、アプリとサービスのパフォーマンスと使いやすさを学習、反復、向上させることができます。 これは、ユーザーに影響を与える前に、アプリケーションのパフォーマンスの問題を検出、調査、軽減するのに役立ちます。</p>


  <p>現在パブリックプレビューで提供されている Azure アプリケーションインサイトの新機能を使用すると、関連するすべての情報を簡単に照合してレポートすることができます。 アプリケーションのパフォーマンスの問題を調査している場合でも、アプリケーションの使用状況を調べている場合でも、結果をジャーナル処理し、アプリの全体像を語ることができます。</p>


  <h3>アプリケーションの使用状況を監視するためのブック</h3>


  <p>Application Insights の新機能であるブックを使用すると、使用状況データ、分析クエリ、テキストの視覚エフェクトをインタラクティブなドキュメントにまとめることができます。 製品所有者は、複数の視覚化ツール (ユーザー、セッション、イベント、リテンション、分析) にわたるアプリの使用状況に関する質問に答えることができます。その後、結果を読みやすい形式にプルし、チームと共有することができます。 ブックをチーム内の他のユーザーに送信すると、ブックを編集できるようにするために使用したコントロールとクエリが編集可能な状態のままになります。 これにより、ブックの探索、拡張、および誤りの確認が容易になります。 ブックは、現在 Application Insights の [使用状況] セクションにあります。</p>


  <p>詳細については、「 <a href="https://go.microsoft.com/fwlink/?linkid=851491">使用状況データを調査して共有</a>する方法」のドキュメントページを参照してください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7edd6a9a-39c7-4791-ba04-ac6d754c4769.png"><img alt="Workbooks in Insights" border="0" height="518" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3c14f5ae-cea7-4d18-b707-98d877d90cad.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="インサイト内のブック" width="924"></a></p>


  <p align="center"><em>Azure アプリケーションインサイトのブックのスクリーンショット</em></p>


  <h3>ユーザーとセッションのタイムラインの視覚化</h3>


  <p>個々のユーザーの動作を分析することができます。 たとえば、顧客が自分の製品を使用していることを観察することにより、使いやすさが向上している場所を知ることができます。 そのため、Application Insights で個々のユーザーとセッションに簡単にフィルターを適用できるようにしまし &rsquo; た &rsquo; 。 ユーザー、セッション、およびイベントの各ツール &rsquo; では、クエリに基づいて、それぞれ5つのサンプルユーザー、セッション、またはイベントを提供するセクションが見つかります。 セッションツールで [サンプルセッション] をクリックすると、新しいタイムラインビューでこの手順をさらに進めていき &rsquo; ます。 このタイムラインを使用すると、セッションの詳細、ページビュー、およびカスタムイベントをストーリーのように簡単に参照できます。 この方法でユーザー &rsquo; エクスペリエンスをステップ実行することにより、製品の使用中に発生した問題や目標を推測し、サイトの今後のリリースでそれらに対処することができます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/72ef3756-eb32-459e-a07f-abd584525452.png"><img alt="Screenshot highlighting Session Timeline in Azure Application Insights" border="0" height="517" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4ffb85df-1a96-4360-854c-1e4c9c344c93.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure アプリケーションインサイトのセッションタイムラインを強調表示したスクリーンショット" width="929"></a></p>


  <p align="center"><em>Azure アプリケーションインサイトのセッションタイムラインを強調表示したスクリーンショット</em></p>


  <h3>User Flows を理解するためのじょうご</h3>


  <p>じょうごを使用すると、複雑なクエリを記述しなくても、視覚的表現を使用してイベントシーケンスの変換を簡単に測定できます。 じょうごを使用して、ユーザーが何を削除しているかを把握し、顧客の問題の原因となっているイベントまたはページを特定します。 詳細については、 <a href="https://go.microsoft.com/fwlink/?linkid=846142">web アプリケーションの使用状況の分析</a>に関するドキュメントのページを参照してください。&nbsp;</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/60ef3009-7cff-498b-9f72-749a23a34401.png"><img alt="Funnels in Azure Application Insights." border="0" height="415" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4e57ecd2-5c41-4a70-acfb-6b0ce8515ca4.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure アプリケーションインサイトでじょうご。" width="924"></a></p>


  <p align="center"><em>Azure アプリケーションインサイトのじょうごのスクリーンショット</em></p>


  <h3>Curated のパフォーマンス調査の改善</h3>


  <p>お客様からのフィードバックをお待ちしており、アプリケーションのパフォーマンス調査エクスペリエンスを改善しました。 [パフォーマンス] ブレードに、各グラフとグリッドのタイトルが表示されるようになりました。 また、操作の応答性の傾向を示し、特定の低速な操作について詳細を掘り下げることができます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/67345940-9307-434f-9a41-b744b0260778.jpg"><img alt="Screenshot of performance investigation in Azure Application Insights" border="0" height="594" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/86a4575f-5475-44af-a0c9-3d9823135a4a.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure アプリケーションインサイトでのパフォーマンス調査のスクリーンショット" width="929"></a></p>


  <p>&nbsp;</p>


  <p align="center"><em>Azure アプリケーションインサイトでのパフォーマンス調査のスクリーンショット</em></p>


  <h3>パブリックプレビューの管理</h3>


  <p>Application Insights の新機能を革新し、リリースし続けるにつれて、新しい機能を活用するために必要な柔軟性と制御を提供する必要があります。 この点を考慮して、パブリックプレビュー管理を有効にして、ビジネス操作の中断を最小限に抑えて新しいエクスペリエンスを実現しました。 ここでは、運用環境に移行する前に、独自のスケジュールに基づいて Application Insights の新しい機能強化を試し、運用前の環境でテストすることができます。</p>


  <p>プレビューの構成方法の詳細については、 <a href="https://docs.microsoft.com/azure/application-insights/app-insights-previews">今後の変更をプレビュー</a>する方法に関するドキュメントリンクを参照してください。</p>


  <p>これらの機能を今すぐ試して、 <a href="https://feedback.azure.com/forums/357324-application-insights">Application Insights UserVoice</a>でご意見をお聞かせください。</p>
