### YamlMime:Yaml
ms.openlocfilehash: 09e78e73ebc87c8170edc06c0214b09f283be841
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893967"
Slug: ensuring-high-availability-of-web-applications-in-windows-azure
Title: Windows Azure で Web アプリケーションの高可用性を確保する
Summary: プラットフォームのアップグレード中に Windows Azure アプリケーションの可用性が失われる可能性を回避するために、web に接続されたロールのインスタンスを複数デプロイすることをお勧めします。 やってる。。。
Content: '<p>プラットフォームのアップグレード中に<a target="_blank" href="https://windowsazure.com/">Windows Azure</a>アプリケーションの可用性が失われる可能性を回避するために、web に接続されたロールのインスタンスを複数デプロイすることをお勧めします。 これにより、特定のアプリケーションに2つ以上のロールインスタンスがデプロイされている場合に、インターネットに接続されたロールの99.95% の外部接続を保証する Windows Azure Compute サービスレベルアグリーメント (SLA) も適用されます。 &nbsp;完全な Windows Azure コンピューティング SLA をダウンロードするには、ここをクリックしてください。</p>  <p><iframe scrolling="no" frameborder="0" src="https://www.facebook.com/plugins/like.php?href=;layout=box_count&amp;show_faces=false&amp;width=300&amp;action=like&amp;font=segoe+ui&amp;colorscheme=light&amp;height=50" style="width: 300px; height: 50px; overflow: hidden;"></iframe><br><a data-url="" data-count="horizontal" data-via="Windowsazure" href="https://twitter.com/share" class="twitter-share-button">ツイート</a>  <script src="https://platform.twitter.com/widgets.js" type="text/javascript"></script>  </p>'
