### YamlMime:Yaml
ms.openlocfilehash: 642f410d038aa46d6961700f3d3a04990ab059d6
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891649"
Slug: estimate-throughput-requirements-for-documentdb-applications
Title: DocumentDB のスループット要件を見積もる必要がありますか。 使用可能な新しい電卓
Summary: Azure DocumentDB は、標準的なアプリケーション操作の要求ユニット (スループット) の要件を見積もるための新しい web ベースのツールを起動しました。
Content: >-
  <p><a href="https://azure.microsoft.com/services/documentdb/">DocumentDB</a> は、世界規模で分散した高可用性アプリを対象とした、非常に高速な地球規模の NoSQL データベースサービスです。 <a href="https://azure.microsoft.com/en-us/blog/documentdb-goes-planet-scale-with-global-databases-new-pricing-and-more-developer-choices/">ビルド 2016</a>で発表された DocumentDB の価格変更とスケーリングオプションを使用して、多くのお客様には、ストレージから独立して、予約済みのスループットを購入してスケーリングする機能を利用することが&#39;ます。 これにより、お客様は必要な分だけ料金を支払うことができ、必要に応じてストレージとスループットを拡張できます。 お客様がスループット見積もりを微調整できるようにするために、次のような一般的な操作の要求ユニット要件を見積もるための新しい <a href="https://www.documentdb.com/capacityplanner">web ベースのツール</a> を&#39;しました。</p>


  <ul style="margin-left: 40px;">
   <li>ドキュメントの作成 (書き込み)</li>
   <li>ドキュメントの読み取り</li>
   <li>ドキュメントの削除</li>
  </ul>


  <p>このツールでは、サンプルドキュメントとスループットの要件を使用して、アプリケーション&#39;のニーズを満たすために必要な要求ユニットの数の見積もりを計算します。 要求の料金は、JSON ドキュメントのサイズと形 (インデックス付きプロパティの数) によって異なります。このツールでは、複数のサンプルドキュメントがサポートされています。</p>


  <p><img alt="" height="437" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/RUEstimatorResults.png" width="610"></p>


  <p>ツールの使用方法の詳細については、「 <a href="https://azure.microsoft.com/documentation/articles/documentdb-request-units/#estimating-throughput-needs">DocumentDB の要求ユニット</a> 」を参照してください。 さらに、アプリケーション&#39;プロビジョニングされたリソースのニーズを正確かつ効果的に見積もるために、このツールの改善を続ける&#39;ます。</p>


  <p>DocumentDB の詳細については、 <a href="https://azure.microsoft.com/services/documentdb/">documentdb の製品ページ</a>を参照してください。 ヘルプが必要な場合、または質問やフィードバックがある場合は、 <a href="https://stackoverflow.com/questions/tagged/azure-documentdb">Stack Overflow の開発者フォーラム</a>でご連絡ください。</p>


  <p>最新の DocumentDB のニュースと機能については、Twitter <a href="https://twitter.com/DocumentDB">@DocumentDB</a> でフォローして最新情報を入手してください。</p>
