### YamlMime:Yaml
ms.openlocfilehash: db0e755c6688b8a49491b34d58e9bdad17141a92
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893064"
Slug: expanding-the-azure-stack-portfolio-to-run-hybrid-applications-across-the-cloud-datacenter-and-the-edge
Title: Azure Stack ポートフォリオを拡張して、クラウド、データセンター、およびエッジ全体でハイブリッドアプリケーションを実行
Summary: 2017での Azure Stack が発表されたため、クラウドを顧客のデータセンターに拡張するためのステージが設定されました。 ハイブリッドクラウドは、最初から Azure の設計原則の1つでした。
Content: >-
  <p>2017での Azure Stack が発表されたため、クラウドを顧客 &rsquo; のデータセンターに拡張するための段階を設定しまし &rsquo; た。 ハイブリッドクラウドは、最初から Azure の設計原則の1つでした。 現時点では、<a href="https://www.youtube.com/watch?v=eexMnJyFj28" target="_blank">香港、香港、中、および</a>マルタ型の各<a href="https://www.youtube.com/watch?v=Z64yEqbRbOk" target="_blank">テクノロジ機関</a>のお客様には、パブリッククラウドとの<a href="https://www.youtube.com/watch?v=nhbuox9eWdA&amp;t=2s" target="_blank">間で接続</a>または切断できるハイブリッドソリューションを構築しています。これに Azure Stack より、IT アジリティを向上させ、効率性を最大化し、新しいビジネスシナリオを実現することができます。&nbsp;&nbsp; <img align="right" alt="Image of Editor's choice 2019 StorageReview award" border="0" height="295" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c694eb19-ba15-4010-97a6-e828b4bb19f8.jpg" style="margin: 0px 0px 0px 7px; border: 0px currentcolor; border-image: none; float: right; display: inline; background-image: none;" title="エディターの選択肢 2019 StorageReview アワードの画像" width="452"></p>


  <p>6か月前に、Azure Stack HCI を使用して Azure Stack ファミリへの追加を発表しました。 その後、企業は Azure Stack HCI を使用してデータセンターを最新化し、ハードウェアとストレージを更新して統合し、Windows 管理センターを使用して Azure Site Recovery や Azure Backup などの Azure サービスを活用しています。 企業は、 <a href="https://www.storagereview.com/node/7484" target="_blank">カテゴリ</a>内の最適なシステムの1つでミッションクリティカルなアプリケーションを実行しています。 StorageReview.com によれば &rsquo; 、 &ldquo; この数値に示すように、テストされていた dataon クラスター (Azure Stack HCI) は膨大な数の値を投稿しました。これは、ミッドマーケットの4ノードの HCI クラスターで最も高速 &rsquo; になっています。 &rdquo;HCI カタログ Azure Stack の20社の相手先ブランド供給メーカー (Oem) の150を超えるソリューションが提供されるようになりました。</p>


  <p>今年の前半では、市販、製造、政府、およびその他の業界でよく見られる革新的なエッジコンピューティングシナリオに対応するために、Intel Arria 10 FPGA を使用した <a href="https://www.cnbc.com/2018/09/24/microsoft-designs-ai-hardware-boxes-for-use-outside-of-data-centers.html" target="_blank">AI 対応のエッジコンピューティングアプライアンス</a> である Azure Data Box Edge の一般提供を発表しました。 たとえば、小売店では、 <a href="https://venturebeat.com/2019/05/10/microsoft-is-addressing-tough-paradigms-on-the-intelligent-edge-with-azure-data-boxes/" target="_blank">Data Box Edge の Azure Machine Learning 機能を使用</a>して、インベントリを追跡し、消費 &rsquo; 者の製品を最新化することができます。</p>


  <p>お客様とのエンゲージメントをさらに深めていくと、デプロイパターン (クラウドネイティブ、コンテナー、仮想マシン (Vm)、管理されたサービス) から環境条件、規制環境、レガシアプリ、最新のアプリ、容量ニーズ、導入曲線まで、さまざまな要件を満たす必要があることがわかります。</p>


  <p>現在、microsoft では、お客様 &rsquo; のソリューションにエッジインフラストラクチャがシームレスに適合するように、Azure Stack ポートフォリオの新しい投資、機能、およびフォームファクターを共有したいと考え &rsquo; ています。 本日のニュースでは、Azure Stack が拡張され、Azure Stack HCI、Azure Stack Hub (以前は Azure Stack)、Azure Stack Edge (以前は Azure Data Box Edge) で構成される製品のポートフォリオが含まれるようになります。</p>


  <h2>Azure Stack ポートフォリオ</h2>


  <p>Azure Stack ポートフォリオは、データセンター、エッジロケーション、リモートオフィス、クラウドでハイブリッドアプリケーションを一貫して構築および実行するための Azure の拡張機能です。 Azure Stack は、オンプレミスの一貫性のあるハイブリッドクラウドと Azure Stack ハブを使用したオンプレミスの一貫したハイブリッドクラウドのニーズに基づいて、お客様の選択肢と柔軟性を提供します。これは Azure Stack HCI を使用したオンプレミスの高パフォーマンス仮想化、または Azure Stack エッジを持つエッジでインテリジェントなコンピューティングと AI を提供する Azure</p>


  <p><img alt="Azure Stack portfolio including of Azure Stack Edge, Azure Stack HCI, and Azure Stack Hub" border="0" height="1081" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/27413067-c64e-4627-a47c-2025a662704a.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Azure Stack Edge、Azure Stack HCI、Azure Stack Hub などのポートフォリオを Azure Stack" width="1902"></p>


  <h3>Azure Stack Edge</h3>


  <p>Azure Stack Edge は Azure で管理されているアプライアンスで、Azure のコンピューティング、ストレージ、インテリジェンスをエッジにもたらします。 これは、お客様 &rsquo; のサイトに配信されるファーストパーティの Microsoft アプライアンスであり、初期コストなしで azure サービスを実行します (azure の請求書で月額料金が発生します)。 顧客は、Azure portal を使用して Azure Stack のエッジを注文およびプロビジョニングできます。Azure 管理ツールは、更新プログラムの監視と実行に使用されます。 Azure Stack Edge を使用すると、開発者ツールから access control、ワークロード管理まで、すべてのクラウドとエッジで一貫したエクスペリエンスを得ることができます。<img align="right" alt="Azure Stack Edge Ruggedized backpack" border="0" height="323" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1d25f9d1-a0f5-4308-8ce8-2e673a7efce1.jpg" style="margin: 0px 0px 0px 10px; border: 0px currentcolor; border-image: none; float: right; display: inline; background-image: none;" title="Azure Stack Edge 耐久性 backpack" width="485"></p>


  <p>Azure Stack Edge では、仮想マシン、Kubernetes クラスター、NVIDIA GPU のサポート、高可用性のサポートなど、新しいコンピューティングと AI の機能が間もなくサポートされることをご紹介します。 これらの機能により、Azure Stack エッジは、市場における最先端のコンピューティングに急速に進化しています。 また、Azure Stack エッジにマルチアクセスエッジコンピューティング (MEC) の tech preview を追加することによって、プライベート携帯ネットワークをサービスとして有効にすることもできます。</p>


  <p>現在 Azure Stack Edge には、エンタープライズデータセンターまたはエッジの場所に関するコマーシャルシリーズが含まれています。 過酷な環境を備えたサイト向けの頑丈なシリーズは、 <a href="https://blogs.microsoft.com/bayarea/2019/10/31/dean-paron-shows-the-impact-of-azure-data-box-edge/" target="_blank">お客様が backpack で実行できるバッテリ駆動のフォームファクター</a>を含む、間もなくリリースされる予定です。 これらの Azure Stack エッジフォームファクターとクラウドで管理された機能によって、クラウドインテリジェンスが提供され、小売店、工場のフロア、病院、フィールド操作、災害ゾーン、および復旧操作が可能になります。</p>


  <p><iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/2K-DOWjV_vU?rel=0" width="560"></iframe></p>


  <h3>Azure Stack HCI</h3>


  <p>お客様が HCI アーキテクチャを最も効率的に選択できるようにするために、Microsoft Ignite には、Azure Stack HCI プログラムの拡張機能が導入されています。 この Azure Stack HCI 検証プログラムに加えて、ソリューションは HCI アーキテクチャにとって最も一般的なワークロードの多くに合わせて最適化されています。ブランチオフィスとエッジは、2ノード、回復力のある仮想およびコンテナー化されたアプリケーションに重点を置いています。また、企業データを保護し Microsoft SQL Server、企業データを保護します。 仮想環境で最適化されたデータベース操作を実現するために、信頼されたエンタープライズ仮想化を使用して、ハードウェアから OS へのセキュリティで保護された実装ガイダンスを活用し、スケールアウトストレージを使用してリモートストレージ実装用の高可用性ストレージを拡張します。</p>


  <p>これらのワークロード用に最適化された Azure Stack HCI カタログのソリューションは、カタログに特別な表記で表示されるようになり、潜在的な顧客がワークロードに最適な選択肢を特定するのが容易になりました。 これらの各ワークロードは、Windows 管理センターを利用して Azure の付加価値サービスと組み合わせることができます。これにより、Azure Stack HCI を使用して接続されたハイブリッドソリューションを簡単にデプロイできます。</p>


  <p>顧客の要求に対応するために、汎用 Kubernetes を含む追加のワークロードが開発中です。</p>


  <h3>Azure Stack Hub</h3>


  <p>Azure Stack Hub は、エンタープライズおよび公的機関のお客様を対象としたクラウドネイティブオファリングです。特に、公共のインターネットから切断されたクラウド環境を運用する場合や、規制やコンプライアンスの要件を満たしている場合などです。 &rsquo;NVIDIA V100 gpu によって有効になっている N シリーズの仮想マシンを含む、Azure Stack ハブのロードマップ向けに、いくつかの新しい更新プログラムを共有しています。 また、Azure Stack Hub で Kubernetes の一般提供が発表されることも&#39;ます。 Azure Kubernetes Service (AKS) エンジンを使用して Azure Stack Hub で Kubernetes クラスターを簡単にプロビジョニングし、Kubernetes クラスターの作成、更新、およびスケーリングを自動化できるようになりました。 2020の前半では、Event Hubs と Azure Stream Analytics もパブリックプレビューで使用できます。</p>


  <h3>Azure Arc と Azure Stack ポートフォリオ</h3>


  <p>Microsoft Ignite では、azure のサービスと管理を任意のインフラストラクチャに導入するために、 <a href="https://azure.microsoft.com/services/azure-arc/" target="_blank">Azure Arc</a> のプレビューを発表しました。 azure Arc を使用すると、任意の Kubernetes クラスターに azure SQL データベースをデプロイできます。 Azure Arc と Azure Stack ポートフォリオは補完的です。 Azure arc の利点と Azure Stack ポートフォリオを組み合わせることができます。 azure Arc では、仮想マシンとコンテナーを管理し、Azure Stack のコンピューティングとクラウドの機能を活用しながら、検証された統合システムの Azure Stack ポートフォリオで Azure Data Services を実行できます。</p>


  <p>Azure Stack ポートフォリオ、いくつかのエキスポブース、パートナーの展示に特化した12セッションを含む、Ignite のビジー状態になっています。 また Intel と提携して、Ignite 2019 エキスポフロアでインテリジェントな小売エクスペリエンスを実証しています。</p>


  <hr>

  <p><em>Microsoft.目的を持つ在庫。</em></p>
