### YamlMime:Yaml
ms.openlocfilehash: d299c985ca2bc1fd2db6451ad73fa02ba8f1240c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139894392"
Slug: experts-tips-on-hardening-security-with-azure-security
Title: Azure セキュリティによるセキュリティ強化に関する専門家のヒント
Summary: Microsoft Azureは、お客様がインフラストラクチャとアプリケーションをホストするためのセキュリティで保護された基盤を提供します。 Microsoft の...
Content: >-
  <p><em>注: このブログは、Microsoft Threat Intelligence Center によって作成されました。</em></p>


  <p>Microsoft Azureは、お客様がインフラストラクチャとアプリケーションをホストするためのセキュリティで保護された基盤を提供します。 Microsoft は&rsquo;、物理的、インフラストラクチャ、運用上のセキュリティにまたがって基盤をセキュリティで保護します。 運用セキュリティの一部には、セキュリティの研究と開発に特化したさまざまなチームにわたる 3,500 を超えるサイバーセキュリティの専門家が含まれています。 Microsoft Threat Intelligence Center は、Microsoft のセキュリティ チームの 1 つであり、セキュリティ環境全体の脅威に対して遭遇して軽減します。</p>


  <p>&rsquo;Microsoft Mechanics&rsquo; の今日のエピソードでは、Microsoft Threat Intelligence Center の作業が Azure とグローバル セキュリティランドスケープをセキュリティで保護する方法を確認します。 このチームは、ピア ツー ピア ネットワーク ソフトウェア、標準的なボットネットとランサムウェア攻撃、ハッカーや国の支援を受けたグループからの敵対的な脅威などの問題を特定するために取り組む。</p>


  <p>また、チームは、多くの地域にわたる広範なビューと、Azure で実行されるサービスのビューも持っています。 この分析情報を使用すると、チームは一般的な攻撃パターンを確認できます。 これらのパターンは、ネットワーク レベル、サービス レベル、アプリ レベル、または OS レベルで指定できます。 悪用が検出されるとすぐに、Microsoft Threat Intelligence Center は Microsoft の他のチームと組み合って、Microsoft の製品とサービスに軽減策を組み込む予定です。 さらに、チームは、攻撃の発生場所、影響を受けた環境、攻撃を修復するために必要な手順など、詳細な情報を提供する脅威インテリジェンス レポートを作成します。&nbsp;</p>


  <p>Microsoft Threat Intelligence Center が Azure&rsquo; プラットフォームをターゲットとする攻撃を軽減する方法を確認できるだけでなく、そのインテリジェンスが Microsoft のサービスに戻される方法と、これらのツールを使用して組織のセキュリティを強化する方法について学習します。 たとえば、 <a href="https://azure.microsoft.com/en-us/services/security-center/">Azure Security Center</a> を使用して、ハイブリッド クラウド リソースのセキュリティ状態を一元化したリアルタイム監視ビューを取得し、問題に対して迅速に対処できます。 Security Center の Just-In-Time&rsquo; VM アクセスを使用して、必要な場合にのみ仮想マシン管理ポートへのアクセスを減らすことで、ブルート フォース攻撃などの脅威から保護することができます。 &rsquo;Security Center調査パスは、SQL インジェクションなど、攻撃に関係しているすべてのエンティティを探索し、攻撃に対して迅速に修復するのに役立ちます。</p>


  <p>今日の概要が役に立つ場合&rsquo;があります。 ご自分の考えをお知らせください。質問は自由に投稿してください。</p>


  <p style="text-align: center;"><iframe allow="autoplay; encrypted-media" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/n58eHSLoU9w" width="560"></iframe></p>
