### YamlMime:Yaml
ms.openlocfilehash: ef429e0ac7336a064bfc12e7ab3d6dd9e58250b0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910789"
Slug: finish-your-application-faster-with-an-open-and-flexible-cloud-solution
Title: オープンで柔軟なクラウド ソリューションを使用してアプリケーションをより迅速に完了する
Summary: 開発者は、アプリの違いを変え、独自性を高め、プラムとインフラストラクチャに費やす時間を減らすために、どのように時間を費やしますか?
Content: >-
  <p>開発コミュニティ <a href="https://www.informit.com/articles/article.aspx?p=2235828&amp;seqNum=13" target="_blank">の</a> 古い問題は次のように行きます。プロジェクトの最初の 90% は時間の 90% を取り、残りの 10% は残りの 90% の時間を要します。 もちろん&#39;、アジャイル開発とクラウド コンピューティング パターンの台頭により、過去 10% の考え方は過去のものになる可能性があります。 しかし、それでも問題は残ります。開発者は、アプリを異なる一意にし、プラムとインフラストラクチャに費やす時間を減らすために、より多くの時間を費やす方法を示しています。<br>

  &nbsp;<br>

  適切なクラウド ソリューションを利用すると、正しい方向への大きなステップになる可能性があります。 適切なソリューションは、開発の待機時間と統合時間を削減するのに役立ちます。 柔軟なインフラストラクチャを使用すると、開発者はリソースをすばやくスピンアップし、クラウド レベルの機敏性で最も一般的なソリューションを実行し、事前構築済みの API とコネクタを使用して、開発プロセスを効率化し、プロジェクトをオフにできます。</p>


  <p><a href="https://azure.microsoft.com/en-us/overview/open-source/azure-stories/?wt.mc_id=WW_CE_AP_OO_BLOG_NONE" target="_blank">開発者がアプリをアプリにデプロイする速Microsoft Azure</a>。</p>


  <p><img alt="Finish applications faster with an open cloud" border="0" height="323" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e7bd3bbe-06ca-4e38-9538-a2e1340d189d.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="オープン クラウドを使用してアプリケーションをより迅速に完了する" width="610"></p>


  <h2>相互運用性が重要</h2>


  <p>明日&#39;のアプリは、柔軟なツールとインフラストラクチャを必要とする根本的に異なる方法で構築されます。 この進化の一環として、Linux 仮想マシンまたは Docker コンテナーでアプリをすばやく起動し、複数のデータ型をブレンドすることが重要になります。 さらに、システムがさまざまな&rsquo;ストレージの種類とビッグ データを組み込む機能をサポートする必要があります。 適切なクラウド ソリューションとは、必要に応じて、&#39;いつでも、どこでも利用できる、開発者のニーズを満たすのに十分な柔軟性を備えるインフラストラクチャを意味します。 その柔軟性により、開発者は開発作業に集中し、使用するツールを使用できます。また、限られたツール セットに入れられるのではありません。</p>


  <h2>ジョブに最適なツール</h2>


  <p>開発時間を削減するには、エンドツーエンド ソリューションの豊富なエコシステムを提供するクラウド プロバイダーを見つける必要があります。 オープンソース テクノロジを利用する開発者は、好きなツールを使用できる必要があります。 クラウド サービスは、Cassandra、MongoDB、MySQL、Hadoop などのスタックをサポートする必要があります。 しかし、&#39;はほんの始まりにすぎない。 また、既存の&rsquo;アプリやデータ ストレージ ソリューションとシームレスに統合する必要があります。そのため、開発者は、既に連携しているはずの作業を連携させようとする貴重な開発時間を無駄にしません。</p>


  <p>開発者は、自分の望む方法で何を望むかをプログラムするために、クラウド ソリューションによって強化されたと感じる必要があります。 iOS、Android、Node.js デバイスでの PHP、Java、Python、Windows のサポートは必要です。 プラットフォームやツールが何であれ、開発者&#39;、IT 環境によって妨げられるのではなく、IT 環境によって生産性を向上させる必要があります。</p>


  <h2>操作ではなくコード</h2>


  <p>最後の考慮事項は、開発プロセスを合理化する機能です。そのため、コード作成者は、API、データベース、コネクタの構築のような運用タスクではなく、コーディングに集中できます。 アプリケーションの迅速な &ldquo;構築、デプロイ、管理は、開発プロセスを通じて、以前は過去 10%&rdquo; だったことを開発プロセス全体で継続的に行えるという意味です。 堅牢なクラウド ソリューションは、プロセスを自動化するための事前構築済みの API とコネクタを提供し、開発プロセスをサポートするために、開発者が選択したツール (Git、Jenkins、Puppet、Chef など) と一緒に動作します。 そうすることで、開発者は、作業に時間を費やすのではなく、イノベーションと創造性の第一線に留まれます。</p>


  <h2>開発者を解放する</h2>


  <p>オープンソースの&mdash;&mdash;コラボレーション ロック スターをサポートする適切なクラウド ソリューションを選択すると、開発者は最善を行うことができます。つまり、より速く完成ラインに入り、クリエイティブになります。 柔軟なツールとインフラストラクチャを提供し、エンドツーエンド ソリューションの豊富なエコシステムを提供し、運用タスクを自動化することで開発プロセスを効率化します。 可能な限り少ないバンプで 100% すべての問題を乗り切り、開発者を可能な限り自由に設定するクラウド ソリューションを使用します。</p>


  <p><a href="https://azure.microsoft.com/en-us/overview/open-source/azure-stories/?wt.mc_id=WW_CE_AP_OO_BLOG_NONE" target="_blank">開発チームがワークロードの負荷分散を処理する方法Microsoft Azure</a>。</p>
