### YamlMime:Yaml
ms.openlocfilehash: 093072cfaaacf143ca52f932e003c05208eeb97c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909009"
Slug: gain-application-insights-for-big-data-solutions-using-unravel-on-azure-hdinsight
Title: ビッグ データ ソリューションに関するアプリケーションの分析情報を取得するには、データの分析情報をAzure HDInsight
Summary: HDInsight を理解すると、開発者や IT 管理者は、パフォーマンスを管理し、自動スケーリングを行&コストの最適化をこれまでよりも優れた方法で行えます。 アプリケーション プラットフォームでの Unravel のお知らせAzure HDInsightです。
Content: >-
  <p>HDInsight を理解すると、開発者や IT &amp; 管理者は、パフォーマンスを管理し、自動スケーリングコストの最適化をこれまでよりも優れた方法で管理できます。</p>


  <p>アプリケーション プラットフォームでの <a href="https://unraveldata.com/" target="_blank">Unravel</a> のお知らせAzure HDInsight <a href="https://azure.microsoft.com/en-us/services/hdinsight/partner-ecosystem/" target="_blank">です</a>。 <a href="https://azure.microsoft.com/en-us/services/hdinsight/" target="_blank">Azure HDInsight</a> は、企業向けフル マネージドのオープン ソースビッグ データ分析サービスです。 一般的なオープンソース フレームワーク (<a href="https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/apache-hadoop-introduction" target="_blank">Hadoop</a>、<a href="https://docs.microsoft.com/en-us/azure/hdinsight/spark/apache-spark-overview" target="_blank">Spark</a>、<a href="https://docs.microsoft.com/en-us/azure/hdinsight/interactive-query/apache-interactive-query-get-started" target="_blank">LLAP</a>、<a href="https://docs.microsoft.com/en-us/azure/hdinsight/kafka/apache-kafka-introduction" target="_blank">Kafka</a>、<a href="https://docs.microsoft.com/en-us/azure/hdinsight/hbase/apache-hbase-overview" target="_blank">HBase</a> など) を使用して、ETL、データ ウェアハウス、Machine Learning、IoT などの幅広いシナリオに対応できます。 Unravel では、これらのシナリオなどのための包括的なアプリケーション パフォーマンス管理 (APM) が提供されます。 このアプリケーションは、お客様がアプリケーションのパフォーマンスの問題を分析、最適化、トラブルシューティングし、シームレスで使いやすく、摩擦のない方法で SLA を満たすのに役立ちます。 一部のお客様は、HDInsight の Unravels&rsquo; チューニング機能を使用して、最大 200% のジョブを 50% 低コストで報告しています。</p>


  <p>詳細については、Azure でクラウドの費用を予算内に維持しながら高速で信頼性の高いビッグ データ アプリを構築する方法について、6 月 13 日のウェビナーで、Microsoft Azure Big Data の <a href="https://info.unraveldata.com/webinar-lp-big-data-apps-microsoft-azure-hdinsight.html?utm_source=msft&amp;utm_medium=msft&amp;utm_campaign=180613_webinar&amp;utm_content=msft" target="_blank"></a> Program Manager、<a href="https://www.linkedin.com/in/rastogipranav/" target="_blank">および</a> <a href="https://www.linkedin.com/in/shivnath-babu-82607550/" target="_blank">Unravel の Shivnath Babu</a>(CTO) に参加してください。</p>


  <h2>ビッグ データ ソリューションの SLA を保証する複雑さ</h2>


  <p>ビッグ データ システムの固有の複雑さ、監視のためのさまざまなツール セット、およびこれらのオープン ソース フレームワークの最適化に関する専門知識の欠如により、SLA の保証を担当するエンドユーザーにとって大きな課題が生じます。 現在のユーザーは、クラスターの正常性、パフォーマンス、使用率を管理するインフラストラクチャ メトリックのみを提供する <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-troubleshoot-failed-cluster" target="_blank">Ambari</a> を使用してアプリケーションを監視する必要があります。 ビッグ データ ソリューションでは、さまざまなオープン ソース フレームワークが使用されます。 これらのすべてのフレームワークで実行されているアプリケーションの監視は、困難な作業です。 ユーザーは、 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-hadoop-access-yarn-app-logs-linux" target="_blank">YARN</a>、Hive、Tez、LLAP、Pig、Spark、Kafka などのログを分析して、問題を手動でトラブルシューティングする必要があります。パフォーマンスを向上するには、 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/spark/apache-spark-perf" target="_blank">Spark Executors</a>、YARN キュー、Kafka トピック構成、HBase のリージョン サーバー、ストレージの調整、コンピューティングのサイズ設定など、ユーザーが設定を変更する必要がある場合があります。 この複雑さを解き明かすのは、アートとサイエンスです。</p>


  <h2>Unravel を使用してビッグ データ アプリケーションを簡単に監視する</h2>


  <p>HDInsight を使って解き明かすと、ビッグ データのインテリジェントなアプリケーションと運用管理が簡単になります。 Application Performance Management は、フルスタック のパフォーマンスを関連付け、分析情報と推奨事項を自動化します。 ユーザーはトラブルシューティングを分析し、パフォーマンスを簡単に最適化できます。 HDInsight での Unravel の主な価値提案を次に示します。</p>


  <h3>プロアクティブなアラートと自動アクション</h3>


  <ul>
   <li>SLA が欠落しているアプリケーション、使用状況ポリシーに違反している、またはクラスターで実行されている他のアプリケーションに影響を与えるアプリケーションに対するプロアクティブ アラート。</li>
   <li>動的なしきい値を使用して上記の問題を解決するための自動アクションと、悪いアプリケーションの削除、優先度レベルに基づくアプリの再指示など、会社が定義したポリシー。</li>
  </ul>


  <h3>アプリのパフォーマンスの分析</h3>


  <ul>
   <li>ボトルネック、問題領域、エラーへのドリルダウン機能を備え、アプリケーションのパフォーマンスを直感的にエンドツーエンドで表示します。</li>
   <li>リソースの割り当て、コンテナーの使用率、構成設定の不備、タスク実行パターン、データ レイアウト、リソースの不一致など、アプリのパフォーマンスに影響を与えるすべての要因に関する分析情報を関連付けた。</li>
   <li>アプリケーションによって発生するパフォーマンスとコストの問題を迅速に検出します。</li>
  </ul>


  <p>次に示すのは、Unravel が Tez アプリケーション上の Hive によって引き起こされたリソースの使用率が低く、コストが高いという診断方法の例です。 Unravel によって提供される推奨事項を使用してアプリケーションをチューニングすると、このアプリケーションを実行するコストが 10 倍削減されました。</p>


  <p><img alt="cost_wastage" border="0" height="408" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/67056bf9-d884-40fc-a6f9-cdcbf437f1b6.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="cost_wastage" width="610"></p>


  <p>Unravel を使用した後のクラスター使用率の例を次に示します。 Unravel を使用すると、リソースを効率的に利用し、 <a href="https://unraveldata.atlassian.net/wiki/spaces/UN42/pages/486539455/Autoscaling+HDInsight+Spark+Cluster+using+Unravel+API" target="_blank">SLA</a> のニーズに基づいてクラスターを自動スケーリングできます。これにより、コストが削減されます。</p>


  <p><img alt="auto_scaling" border="0" height="278" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6a2a826e-7410-47c5-8d79-57a771f4cfd5.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="auto_scaling" width="610"></p>


  <h3>AI 駆動型インテリジェントレコメンド エンジン</h3>


  <ul>
   <li>データの並列処理、最適なコンテナー サイズ、タスクの数など、最も高速な実行や最小リソース使用率に最適な値を推奨します。</li>
  </ul>


  <p>次の例は、Unravels&rsquo; AI 駆動エンジンが Hive クエリの最適なパフォーマンスに関するアクション可能な推奨事項を提供する方法を示しています。</p>


  <p><img alt="tez_recommendations" border="0" height="263" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/659370ab-159b-4607-ae77-6b97f34b66c0.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="tez_recommendations" width="610"></p>


  <ul>
   <li>実行の不十分さ、スキュー、負荷の高い結合、マッパー/レクサーの数が多すぎる、キャッシュなどに関連する問題を特定して自動的に修正します。</li>
  </ul>


  <p>次に示すのは、<a href="https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-apache-kafka-spark-structured-streaming?toc=%2Fen-us%2Fazure%2Fhdinsight%2Fkafka%2FTOC.json&amp;bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json" target="_blank">Spark Streaming &amp; Kafka</a> を使用してリアルタイム IoT アプリケーションでラグを自動的に検出し、ソリューションを推奨する Unravel<u> </u>の例です。</p>


  <p><img alt="Streaming recommendations" border="0" height="221" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ad608360-3e2e-4ee0-a87e-dead579480db.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="ストリーミングに関する推奨事項" width="610"></p>


  <h2>概要HDInsight での Unravel の使用</h2>


  <p>お客様は、HDInsight で 1 回のクリックで Unravel を簡単にインストールAzure portal。 Unravel を使用すると、Hadoop、Hive、Spark、Kafka、LLAP などのオープン ソース フレームワークを使用して、ビッグ データ アプリケーションの動作をライブ ビューでAzure HDInsight。</p>


  <p><img alt="Installing unravel" border="0" height="312" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/01f58206-5c25-4918-95b5-469a7f2efa2d.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Unravel のインストール" width="610"></p>


  <p>インストール後、次に示すように、クラスターの [アプリケーション] ブレードから Unravel アプリケーションを起動できます。</p>


  <p><img alt="Launching unravel data" border="0" height="295" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/917b72da-5484-41c5-a2cf-330c684ec6e0.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Unravel データの起動" width="610"></p>


  <h2>HDInsight で今すぐ Unravel を試してみてください。</h2>


  <ul>
   <li><a href="https://azure.microsoft.com/en-us/services/hdinsight/" target="_blank">詳細については、次を参照Azure HDInsight</a></li>
   <li><a href="https://unraveldata.com/unravel-data-collaborates-microsoft-azure-boost-performance-reliability-big-data-workloads-cloud/" target="_blank">Unravel からのリリース</a></li>
   <li><a href="https://unraveldata.atlassian.net/wiki/spaces/UN42/pages/423264310/Install+Unravel+HDInsight+app" target="_blank">HDInsight での Unravel の使用開始ガイド</a></li>
   <li><a href="https://www.youtube.com/watch?v=kEZnsfsC-eE" target="_blank">HDInsight での Unravel の使用に関するビデオ</a></li>
   <li><a href="https://unraveldata.atlassian.net/wiki/spaces/UN42/pages/486539455/Autoscaling+HDInsight+Spark+Cluster+using+Unravel+API" target="_blank">ビジネス SLA に基づく Unravel を使用した HDInsight クラスターの自動スケーリング</a></li>
   <li><a href="https://unraveldata.com/" target="_blank">Unravel Web サイト</a></li>
   <li><a href="https://azure.microsoft.com/en-us/services/hdinsight/partner-ecosystem/" target="_blank">HDInsight アプリケーション プラットフォームのアプリケーションの詳細を学習する</a></li>
  </ul>


  <h2>ウェビナーに参加してください。</h2>


  <p>詳細については、Azure でクラウドの経費を予算内に維持しながら高速で信頼性の高いビッグ データ アプリを構築する方法に関するウェビナーで、Microsoft Azure ビッグ データの Program Manager である<a href="https://www.linkedin.com/in/rastogipranav/" target="_blank">、および</a> Unravel の CTO である <a href="https://www.linkedin.com/in/shivnath-babu-82607550/" target="_blank">Shivnath Babu</a> に参加してください。<a href="https://info.unraveldata.com/webinar-lp-big-data-apps-microsoft-azure-hdinsight.html?utm_source=msft&amp;utm_medium=msft&amp;utm_campaign=180613_webinar&amp;utm_content=msft" target="_blank"></a></p>


  <h2>まとめ</h2>


  <p>Azure HDInsightは、 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/apache-hadoop-introduction" target="_blank">Hadoop</a>、 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/spark/apache-spark-overview" target="_blank">Spark</a>、 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/apache-hadoop-linux-create-cluster-get-started-portal" target="_blank">Hive</a>、 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/interactive-query/apache-interactive-query-get-started" target="_blank">LLAP</a>、 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/kafka/apache-kafka-introduction" target="_blank">Kafka</a>、 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hbase/apache-hbase-overview" target="_blank">HBase</a>、 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/storm/apache-storm-overview" target="_blank">Storm</a> など、幅広いフル マネージド フレームワークを提供する最も包括的なプラットフォームです。 Unravel を含む <a href="https://azure.microsoft.com/en-us/blog/azure-hdinsight-application-platform-install-solutions-built-for-the-apache-hadoop-ecosystem/" target="_blank">HDInsight アプリケーション</a> プラットフォームの拡張をお知らせ <a href="https://unraveldata.com/" target="_blank">します</a>。 Unravel は、さまざまなオープン ソース分析フレームワーク全体で包括的なアプリケーション パフォーマンス管理 (APM) を提供し、お客様がアプリケーションのパフォーマンスの問題を分析、最適化、トラブルシューティングし、シームレスで使いやすく、摩擦のない方法で SLA を満たすのに役立ちます。<a name="_GoBack"></a></p>


  <p>Twitter HDInsight と でフォローすることで、最新Azure HDInsight最新のニュースと機能<a href="https://twitter.com/search?q=%23HDInsight&amp;src=typd" target="_blank">に関する最新情報を確認してください。#</a> <a href="https://twitter.com/AzureHDInsight" target="_blank">@AzureHDInsight</a> 質問とフィードバックについては、 にお問い合わせください <a href="mailto:AskHDInsight@microsoft.com">AskHDInsight@microsoft.com</a>。</p>
