### YamlMime:Yaml
ms.openlocfilehash: 74679d776337fdd35fad799364ef05e482300281
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889488"
Slug: gartner-recognizes-microsoft-as-an-application-platform-as-a-service-leader
Title: Gartner が Microsoft をサービス リーダーとしてアプリケーション プラットフォームとして認識
Summary: 2013 年は、Azure のWindows年でした。毎月、顧客の使用状況に関する新しい記録が見られたので、4 月には、Azure Infrastructure Service を受け取った azure Infrastructure Service の GA Windows大きなマイルストーンに到達しました。
Content: >-
  2013 年は、Azure のWindows年でした。毎月、顧客の使用状況に関する新しい記録が見られたので、4 月には、前例のない導入を受けた Windows Azure Infrastructure Service の GA で大きなマイルストーンに到達しました。 2014 年は、2014 年 1 月 7 日に公開された 2014 年 1 月 7 日に公開された Enterprise <a href="https://www.gartner.com/technology/reprints.do?id=1-1P502BX&amp;ct=140108&amp;st=sb">aPaaS マジック</a> クアドラントに基付き、Enterprise Application Platform as a Service (aPaaS) 市場のリーダーとして Microsoft を認識し、もう 1 つの画期的な瞬間に到達しました。


  企業のお客様から、既存のアプリケーションの開発、テスト、ホスティングのためのインフラストラクチャ サービスを提供するのと同様に、新しいアプリケーションを開発するためのクラウド サービス プラットフォームが必要だとお伝えしています。 Windowsリーダーとしての aPaaS マジック クアドラントと、2013 年 8 月 19 日の Visionary としてのクラウド <a href="/b/windowsazure/archive/2013/08/28/gartner-recognizes-microsoft-as-a-cloud-infrastructure-as-a-service-visionary.aspx">IaaS</a> マジック クアドラントの両方に Azure が配置されている場合、これらのシナリオ全体でのビジョンの完全性と、(はるかに重要なことに)、企業のお客様の短期的および長期的なニーズを満たすために正常に実行する能力について説明します。 この関心は、新しい顧客のサインアップからプラットフォーム内に格納されるデータの量まで、過去 6 か月間に Azure にとって大きな成長を意味しています。

  <ul>
   <li>週平均 8,000 人の新規顧客</li>
   <li>Windows Azure では、2000 年に使用された地球全体よりも多くのサーバー コンピューティングが使用されます</li>
   <li>コンピューティングの需要は引き続き 6 ~ 9 か月ごとに 2 倍</li>
   <li>詳細は、履歴に出力Windows Azure に格納されます</li>
  </ul>

  <strong>Azure でのWindows目標</strong>


  クラウドファーストアプローチにより、商用クラウド ビジネスの FY14 の第 1 四半期に <a href="https://www.microsoft.com/en-us/news/press/2013/oct13/10-24fy14q1earningspr.aspx">103%</a> の収益が増加しました。 開発者や IT のニーズ<a href="https://www.microsoft.com/en-us/server-cloud/cloud-os/default.aspx#fbid=C0ru7F9sYu8">を満たすために、ツール、管理製品、サーバー プラットフォームを</a> Azure と統合することで、引き続き クラウド OS ビジョンを実現しています。


  開発者はシームレスなクラウド開発エクスペリエンスを求め、先月開始された Visual Studio 2013 (VS) は、開発者が Azure 管理ポータル にアクセスすることなく、コードの記述、Azure への直接デプロイ、環境の管理を行う機能を提供します。


  また、クラウドネイティブ アプリケーションを通じて新しいビジネス価値を推進しているお客様のために、Mobile Services、Media Services、Web サイトなど、Windows Azure に過去 200 を超える新しいサービスを追加しました。 また、昨年は、中国と日本での打ち上げとオーストラリアとブラジルでの打ち上げを意図して、世界中のデータセンターのフットプリントを拡大  <a href="https://blogs.technet.com/b/microsoft_blog/archive/2013/05/22/microsoft-announces-major-expansion-of-windows-azure-services-in-asia.aspx">し続</a><a href="/b/windowsazure/archive/2013/12/04/expanding-windows-azure-capacity-brazil.aspx">け、</a>


  <strong>Open and Flexible Windows Azure</strong>


  Windows Microsoft の独自のテクノロジではないサポート テクノロジが採用され、開始されたので、Azure も Microsoft の変更の推進力にもなっています。 これには、node.js、Java、PHP、Python などの新しいフレームワークと言語、および SUSE、CentOS、Ubuntu などの Windows 以外のオペレーティング システムが含まれます。 お客様は、Microsoft 以外のデバイスや iOS や Android のようなオペレーティング システムのモバイル開発に Azure を使用できます。Oracle との最近のパートナーシップにより、Windows Azure は、Oracle Databaseおよび <a href="https://azure.microsoft.com/en-us/campaigns/oracle/">WebLogic Server</a> 向けで最も包括的で完全にサポートされているクラウド プラットフォームになります。 これはすべて、Azure Windows誰でもクラウド プラットフォームになりつながっているという意味です。


  <strong>お客様がストーリーを伝える</strong>


  多くのピアが Azure を採用し、成功を収めています。 以下のケース スタディでは、一部のお客様がクラウドで何を行っているのかについて説明します。

  <ul>
   <li><a href="https://www.microsoft.com/en-us/news/press/2013/apr13/04-09nab13pr.aspx">Microsoft Teamsを使用してデジタル プラットフォーム全体に魅力的なスポーツ プログラミングを提供するために NBC スポーツ グループWindowsする</a></li>
   <li><a href="https://www.microsoft.com/casestudies/Microsoft-Visual-Studio-Team-Foundation-Server-2010/easyJet/Airline-Aims-to-Save-Millions-Shorten-Airport-Waits-with-Cloud-Based-Mobile-Services/4000010767">easyJet ヨーロッパ航空ハイブリッド クラウド ソリューションを使用してサービスとスケーラビリティを向上させる</a></li>
   <li><a href="https://www.microsoft.com/casestudies/Windows-Azure/NBC-News-Digital/NBC-News-Picks-Windows-Azure-over-Amazon-to-Host-Push-Notifications-to-Mobile-Apps/710000003210">NBC News は、Windowsプッシュ通知をホストするために Azure over Amazon を選択Mobile Apps</a></li>
   <li><a href="https://channel9.msdn.com/Blogs/Windows-Azure/Windows-Azure-Case-Study-Talk-Talk/">Mando Group:Azure を利用した TalkTalk Business 向けクロスプラットフォーム モバイル ソリューションWindows提供</a></li>
   <li><a href="https://www.microsoft.com/casestudies/Windows-Server-2012-R2/Lufthansa-Systems-AG/Lufthansa-Systems-Uses-Hybrid-Cloud-to-Trim-IT-Delivery-to-Hours-and-Reduce-Costs/710000003533">Lufthansa システムでは、ハイブリッド クラウドを使用して IT 配信を数時間に削減し、コストを削減します</a></li>
   <li><a href="https://www.microsoft.com/casestudies/Windows-Azure/3M-Informatics/3M-Unit-Boosts-Revenue-by-50-Percent-with-Choice-of-Cloud-Service/710000002636">クラウド サービスの選択により、3M ユニットで収益を 50% 増やします</a></li>
   <li><a href="https://www.microsoft.com/casestudies/Windows-Azure/Radio-Shack/Electronics-Retailer-Enhances-Partnerships-Drives-Traffic-with-Cloud-Technology/710000002677">電子小売業者がパートナーシップを強化し、クラウド テクノロジを使用してトラフィックを推進する</a></li>
  </ul>

  Gartner が、APaaS 市場で実行する能力とビジョンの完全性の両方を認識し、2014 年に新しい Azure サービスを導入し、お客様がクラウドを簡単に利用できるのを楽しみにしています。 完全なレポート 「Gartner: サービスとしてのアプリケーション プラットフォームのマジック クアドラント」を読む場合は、こちらを参照 <a href="https://www.gartner.com/technology/reprints.do?id=1-1P502BX&amp;ct=140108&amp;st=sb">してください</a>。


  <em>*Gartner は、その研究出版物に示されているベンダー、製品、またはサービスを支持するのではなく、評価が最も高いベンダーのみを選択する技術ユーザーには助言されません。Gartner の研究出版物は、Gartner の研究組織の意見で構成され、事実に関する記述として解釈すべきではありません。Gartner は、商品性または特定の目的への適性に関する保証を含め、この調査に関して、明示または黙示を問わず、すべての保証を一切負いません。</em>
