### YamlMime:Yaml
ms.openlocfilehash: 182310525bec08de413748abab7543eca654c2d2
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889181"
Slug: general-availability-of-user-behavior-analytics-tools-in-azure-application-insights
Title: Azure アプリケーションインサイトでのユーザー動作分析ツールの一般提供
Summary: Microsoft ビルド2017では、プレビューとして Application Insights 用の一連のユーザー動作分析ツールを導入しました。 そのため、お客様からのフィードバックをお待ちしており、さらに機能を追加しています...
Content: >-
  <p>Microsoft ビルド2017では、プレビューとして<a href="https://azure.microsoft.com/blog/new-tools-for-understanding-user-behavior-with-application-insights/" target="_blank">Application Insights 用の一連のユーザー動作分析ツール</a>を導入しました。 その後、フィードバックをお待ちしており、機能を追加し、バグをスカッシュしまし &rsquo; た。 &rsquo;また、これらのユーザー動作分析ツールを単独で使用して、経験を必要とせずにエクスペリエンスを向上させる機会を見つけることもできました。</p>


  <p>この追加のポーランド語では、現在 &rsquo; 、これらのツールをプレビューから一般公開に卒業しています。 これらのツール &ndash; のユーザー、セッション、イベント、User Flows、じょうご、リテンション期間、コーホート、影響 &ndash; は、今後の Application Insights の安定してサポートされている部分です。&nbsp;</p>


  <h2>これらのツールを試すにはどうすればよいですか。</h2>


  <p>ユーザー、セッション、イベント、およびその他のユーザー動作分析ツールは、Azure portal の各 Application Insights リソースの一部です。 Application Insights の使用を開始するには、<a href="https://docs.microsoft.com/azure/application-insights/" target="_blank">アプリ &rsquo; のスタックに基づくいずれかのクイックスタートに従っ</a>てください。 Application Insights リソースを取得すると、[使用状況] の左側のメニューに [ &ldquo; ユーザー動作分析ツール] が表示 &rsquo; されます。&rdquo;</p>


  <h2>昨年からの新機能 &rsquo;</h2>


  <p><em>たくさん！</em> ユーザー、セッション、およびイベントは、応答性を向上させるために一から再構築され、より迅速に読み込まれ、より多くの洞察を自動的に提供します。 <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-usage-segmentation" target="_blank">ユーザー、セッション、イベント</a>の詳細については、こちらを参照してください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bed7cd85-8d89-4d20-9ec8-05815c25f2fb.png"><img alt="User, sessions, and events" border="0" height="799" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/15a7569a-69cc-4274-aa72-54e7b3d65c99.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="ユーザー、セッション、およびイベント" width="1429"></a></p>


  <p>また、User Flows、じょうご、影響、ユーザーとセッションのタイムライン、Visual Studio App Center 統合、コーホートなどの6つの主要な新しいツールと統合も追加しました。</p>


  <p><strong>User Flows</strong> には、ユーザーがアプリのページと機能をどのように移動するかを一目で確認できるビューが用意されています。これにより、ユーザーが体験をどこで開始して終了している &rsquo; か、およびそれらの間で何が行われているかを特定できます。 詳細については、 <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-usage-flows" target="_blank">User Flows</a>を参照してください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/df7fc0e3-c41b-4732-9164-c384bfab162c.png"><img alt="User flows" border="0" height="801" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1e275098-626e-44ea-9987-44e25b560128.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="ユーザーフロー" width="1429"></a></p>


  <p><strong>じょうご</strong> を使用すると、チームは、web アプリのキー体験の変換レートを詳細に追跡できます。 各ステップで完了し、削除したユーザーを分析して、チームが製品 &rsquo; の換算率を向上させるのに役立ちます。 <a href="https://docs.microsoft.com/en-us/azure/application-insights/usage-funnels" target="_blank">じょうご</a>の詳細については、こちらを参照してください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/72c69d83-dbf8-4f28-b35d-944933ca8e5d.png"><img alt="Funnels" border="0" height="784" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8f37076a-302d-4a4e-b97b-7b2fc89ef38b.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="じょうご" width="1429"></a></p>


  <p>ページの読み込みに時間がかかるため、お客様のビジネスはテーブルに資金を残していますか? <strong>影響</strong>ツールは、ページの読み込み時間、その他のメトリック、および対応するページの操作への変換率の関係を分析します。 これにより、開発チームはデータ主導型の方法でパフォーマンスの向上に投資することができます。 <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-usage-impact" target="_blank">影響</a>の詳細についてはこちらをご覧ください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1ca09c97-f56f-47ef-b26a-16027b146413.png"><img alt="Impact" border="0" height="804" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8e58a401-3c3d-42e7-b43b-a43f08410f26.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="よる" width="1429"></a></p>


  <p><strong>ユーザーとセッションのタイムライン</strong> のヘルプでは、ユーザーの操作、例外、およびその他のログを contextualize、ユーザーがログの送信時に行っていたことに関する情報を提供します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1e00e917-673c-4ff4-9fdb-5d7ed76dfff1.png"><img alt="User and session timelines" border="0" height="809" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7c7ac79e-521d-4201-9381-b6ac76661340.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="ユーザーとセッションのタイムライン" width="1432"></a></p>


  <p><strong>コーホート</strong> を使用すると、ユーザー、セッション、イベント、または操作の正確なグループを定義し、他のユーザー動作分析ツールでより簡単に分析できるようになります。 <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-usage-cohorts" target="_blank">コーホート</a>の詳細については、こちらを参照してください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/245d26b6-907d-4c08-b52c-61b1100df150.png"><img alt="Cohorts" border="0" height="702" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cd09d3e4-0078-4ea6-945a-756cd79e68a1.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="コーホート" width="1280"></a></p>


  <p>最後に、これらのユーザー動作分析ツールは web apps を超えています。 <strong>Visual Studio App Center 統合</strong>を使用すると、お客様 &rsquo; の Android、iOS、Windows デバイスから送信された App Center テレメトリのコピーを Application Insights &rsquo; に送信できます。 その後、モバイルアプリのテレメトリで、これらすべての分析ツールを Application Insights で使用できるようになります。 <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-mobile-center-quickstart" target="_blank">Application Insights との App Center 統合の</a>詳細については、こちらを参照してください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/831fdfe2-1246-4743-92dd-7f16e0fe8aca.png"><img alt="Visual Studio App Center integration" border="0" height="825" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9bfd87b5-d8fe-460d-a711-6c43a724a321.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Visual Studio App Center 統合" width="1429"></a></p>


  <p>もっと詳しい説明が必要でしょうか。 詳細については、 <a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-overview" target="_blank">Application Insights ユーザー動作分析ツール</a>のドキュメントページを参照してください。</p>
