### YamlMime:Yaml
ms.openlocfilehash: 63b50c7ef443bfa09c4d5f21396c46b075a85b1a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895952"
Slug: general-availability-of-azure-application-insights
Title: サービスの一Azure アプリケーション インサイト
Summary: 'アプリケーションの一般提供 (以前Azure アプリケーション インサイト Visual Studio Application インサイト) を発表し、新しい価格体系を立ち上げしました。 '
Content: >-
  <p>本日、<a href="https://connectevent.microsoft.com/">ニューヨークの Connect() 2016</a> イベントで、Azure アプリケーション インサイト (以前の <a href="https://azure.microsoft.com/services/application-insights/">Visual Studio</a> Application インサイト) の一般提供を発表し、新しい価格体系を開始しました。<a href="https://azure.microsoft.com/pricing/details/application-insights/"></a> この発表により、Application インサイトでは、99.9% の可用性を提供する財務的な SLA が提供されます。</p>


  <p>Application インサイトは、統合されたアプリケーション パフォーマンス管理 (APM) とアプリケーション分析ソリューションです。 これにより、開発チームは、アプリケーションのパフォーマンスとユーザー エクスペリエンスとの関係、およびこれらの影響がビジネス成果に与える影響を理解できます。</p>


  <p>Application インサイト を使用する場合は、簡単な概要とデモを次に示します。</p>


  <p><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Events/Connect/2016/100/player" width="960"></iframe></p>


  <p>&nbsp;</p>


  <p>Application インサイトの主な領域は次のとおりです。</p>


  <ul>
      <li><b>インテリジェント APM</b>: 高度なツールを使用して&rsquo;開発するアプリケーションのパフォーマンスを事前に監視し、改善します。 ビジュアル <a href="https://azure.microsoft.com/documentation/articles/app-insights-app-map/">アプリケーションは、パフォーマンス</a> の問題を特定してマップします。 <a href="https://azure.microsoft.com/documentation/articles/app-insights-proactive-diagnostics/">機械学習に基</a> づくスマート検出では、埋め込み診断を使用してアラートが送信されます。 この <a href="https://azure.microsoft.com/blog/live-metrics-stream/">Live Metrics Stream</a> 、変更を&rsquo;デプロイしている間に、アプリケーションの正常性メトリックをリアルタイムで監視できます。</li>
      <li><b>分析:</b> 豊富な <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-analytics/">クエリ言語</a>により、Analytics&rsquo; では、アプリケーションのパフォーマンスと使用状況に関する複雑な質問に対する回答がほぼ瞬時に提供されます。 対話型クエリを使用して柔軟な方法でアプリのパフォーマンスと動作に関するクリエイティブな質問をし、望ましいビジネス成果を妨める問題を特定するまでそれらを絞り込む。 アドホック クエリから分析情報を導き出したら、カスタマイズ可能なダッシュボードまたは Power BI との統合を通じて、組織全体でビジュアル<a href="https://azure.microsoft.com/documentation/articles/app-insights-export-power-bi/">の形式で共有できます</a>。</li>
      <li><b>DevOps統合&amp;機能</b>拡張: 製品ファミリに緊密Visual Studio統合されます。 IDE でアプリのコード内のパフォーマンス データをVisual Studioします。 Visual Studio Team Services<a href="https://azure.microsoft.com/blog/application-insights-work-item-integration-with-visual-studio-team-services/">、Team Foundation Server</a>、GitHub との統合により、ワークフローの初期段階で<a href="https://azure.microsoft.com/blog/application-insights-work-item-integration-with-github/"></a>品質の問題を見つけて修正DevOpsできます。 System Center および Operations Management Suite との統合により、チームの境界を越えてアプリケーションのパフォーマンスとシステム パフォーマンスのメトリックを共有し、問題の根本原因を特定する時間を短縮できます。</li>
  </ul>


  <p>一般提供の一環として、新しい価格体系が導入されました。 Application インサイト を使用して無料で開始できます。また、コストなしで完全な機能セットを取得する APM ツールと Analytics &ndash; ツールに制限はありません。 支払いは、アプリの拡大と、Application インサイト へのより多くのアプリケーション テレメトリの送信時にのみ行いますが、支払い量を制御できます。</p>


  <p>さらに、これらの新機能と Application インサイト の機能強化を発表します。現在、お客様と共有できると思います。</p>


  <ol>
      <li>分析クエリの生データリテンション期間を 90 <a href="https://azure.microsoft.com/documentation/articles/app-insights-analytics/">日に増やしました</a></li>
      <li>アプリケーション とデータを格納するためのヨーロッパインサイトオプション</li>
      <li>アプリケーション パフォーマンス管理の機能強化: <ul>
          <li><a href="https://azure.microsoft.com/documentation/articles/app-insights-proactive-diagnostics/">要求パフォーマンスの</a> 低下のスマート検出</li>
          <li><a href="https://azure.microsoft.com/documentation/articles/app-insights-monitor-web-app-availability/#failures">可用性監視の結果</a> とサーバー側のテレメトリを関連付ける。このテレメトリを使用すると、合成テストの失敗を診断できます</li>
          <li><a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/#live-metrics-stream-instant-metrics-for-close-monitoring">失敗した要求Live Metrics Stream</a> の詳細、依存関係の呼び出し、および例外の詳細をリアルタイムで把握できる、Live Metrics Streamのエラー サンプル</li>
          <li>Azure ダッシュボードの <a href="https://azure.microsoft.com/documentation/articles/app-insights-dashboards/">グリッド コントロール</a> と、パーセンテージ グラフなどのメトリック オプションの追加のグラフ作成オプション</li>
      </ul>
      </li>
      <li>Visual Studio 内の <a href="https://azure.microsoft.com/en-us/blog/application-insights-three-latest-visual-studio-features/">Codelens およびアプリケーション</a>検索機能の機能強化により、より早く問題を特定して修正するためのコンテキストの詳細が提供されます</li>
      <li>すべてのクエリ<a href="https://dev.applicationinsights.io/">、イベントインサイトメトリック</a> データにアクセスするために REST API を使用する Application インサイトのプレビュー</li>
  </ol>


  <p>お客様のニーズにより適切に対応するために、Application インサイトに新しい機能を継続的に追加し、お客様から学習しています。 データを安全に保つには<a href="https://azure.microsoft.com/support/trust-center/">、Azure の&amp;</a>プライバシー標準とセキュリティ コンプライアンス ポリシーに完全にコミットしています。</p>


  <p>最後に、私たちが最近ケース スタディを公開した、グローバルな塗り絵具会社 AkzoNobel という顧客の 1 人からの感動的な言葉で <a href="https://customers.microsoft.com/en-US/story/blobal-paint-firm-transforms-customer-service-worldwide-with-microsoft-cloud-technologies">終了します</a>。</p>


  <p><i>&ldquo;Application インサイトでは、検出に時間がかかる問題に何度も注意が向けらなくなりました。その結果、アプリケーション&rsquo;に必要なサービス レベルを維持できます。&rdquo;</i></p>


  <p><i>--Rob Rejers、マネージャー ColorApps Development、AkzoNobel</i></p>


  <p>&nbsp;</p>


  <p>新機能や改善された機能については、<a href="https://visualstudio.uservoice.com/forums/357324-application-insights">Application インサイト User Voice</a> でアイデアを共有してください。質問がある場合は、Application インサイト <a href="https://social.msdn.microsoft.com/Forums/en-US/ApplicationInsights/">フォーラムを参照してください</a><u>。</u></p>
