### YamlMime:Yaml
ms.openlocfilehash: b34a5b9ca55f16d49b6e8e65ca21526ff4fbdb14
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895064"
Slug: getting-started-with-iot-driving-business-action-through-analytics-and-automation
Title: 'IoT の使用を開始する: 分析と自動化を通じてビジネス アクションを推進する'
Summary: 現時点での分析情報や長期的な傾向を探している場合でも、情報の価値はビジネスにとっての有益性と同じだけになります。 一部の情報は直ちに実行する必要がありますが、時間の流れによる傾向の長期的な大きな分析のためにも格納できます。 それぞれのケースに対して、使用するツールが異なAzure IoT説明しました。
Content: >-
  <p>現時点での&rsquo;分析情報や長期的な傾向を探している場合でも、情報の価値はビジネスにとっての有益性と同じに過言ではありません。 一部の情報は直ちに実行する必要がありますが、時間の流れによる傾向の長期的な大きな分析のためにも格納できます。 それぞれのケースに対して、使用するツールが異なAzure IoT説明しました。</p>


  <h2>ほぼリアルタイムのデータ分析</h2>


  <p><strong>Azure Stream Analytics</strong> は、さまざまなソースからデータを取り込む、移動可能な有料サービスです。 IoT Hub からのリアルタイム データに加えて、Azure Blob Storage の履歴データを取り込み、Event Hub データを他のソースと組み合わせて相関関係を強調したり、比較分析を実行したりすることができます。</p>


  <p>Azure Portal を使用すると、Azure Stream Analytics ジョブを開始し、適切なデータ セットに転送し、特定のデータ、パターン、またはリレーションシップを検索する方法について説明できます。</p>


  <p>ジョブStream Analytics完了したら、結果を BLOB Storage、SQL Server、Data Lake、または Cosmos DB などのサービスとしてのデータベース オファリングに転送できます。 また、追加の分析と視覚化のために、HD インサイトまたは Power BIにデータを送信することもできます。</p>


  <p>その名前が示すように、<strong>Azure Time Series インサイト</strong> は、時系列またはシーケンシャルなデータを格納、インデックス作成、クエリ、視覚化するように設計されています。 また、テラバイト単位のデータや数十億のイベントを処理する場合でも、大規模に実行できます。</p>


  <p>Time Series の最も一般的なアプリケーションの一部はインサイトです。</p>


  <ul>
      <li>根本原因分析の実施</li>
      <li>時系列データを分析または視覚化するカスタム アプリの構築</li>
      <li>さまざまな場所のデータをビジネス リードと共有してコラボレーションを強化する</li>
  </ul>


  <p>大規模な&rsquo;データ セットを扱う場合は、 <strong>Apache Sparkが選択</strong> できる場合があります。 並列処理を使用し、長期的な分析ジョブに最適なソリューションです。 分析の効率を向上させるために、処理前にデータを小さなチャンクに分割します。そのため、待機時間の問題が発生する可能性は高く、わずか数秒です。</p>


  <h2>履歴データ分析</h2>


  <p>長期的な傾向を探すのは、お花の花を読むのと少し似ている場合があります。 データ サイエンスと<strong>高度なAzure Machine Learning</strong> (AMLソリューション) を使用する場合があります。 既存のデータ セットを使用すると、将来の結果と傾向を予測できます。 時間のAzure Machine Learning領域について理解を深め、より効果的な実験を開発し、より良い結果を得る基盤を提供します。</p>


  <p>AMLには、コンピューター ビジョン、財務および需要予測、テキスト分析など、特定の領域での機械学習モデルの開発を加速させるのに役立つ Python コードの特殊なライブラリも用意されています。</p>


  <p>ビッグ データ分析用の元のオープン ソース ソリューション <strong>である Azure HD Insight</strong> は、Hadoop に基づくフル マネージド サービスです。 HD Insight では、いくつかのオープン ソース フレームワークがサポートされ、柔軟性が高く、高速でコスト効率の高いソリューションになります。 また、Kafka for HD Insight がサポートされているため、大量のデータを処理するためにスケーリングできる、管理されたコスト効率の高いストリーミング分析ソリューションを作成できます。</p>


  <p>HD サービスの主な利点インサイト次のとおりです。</p>


  <ul>
      <li>Azure Log Analytics との統合により、クラスターのパフォーマンスを監視する単一のポータルが提供されます</li>
      <li>さまざまな開発者環境との互換性により、選択したツールを確実に使用できます</li>
      <li>履歴、リアルタイム、構造化、非構造化、ビッグ データなど、さまざまなデータ セットの分析に優</li>
  </ul>


  <p>データ分析によるアクションの推進に加えて、データ分析の特定のイベントに基づいてアクションをトリガーするサーバーレス コンピューティング モデルをIoT Hub。<strong> </strong>以前のブログ記事では、アクション <a href="https://azure.microsoft.com/en-us/blog/getting-started-with-iot-what-do-you-do-with-all-that-data/">をトリガーする方法について説明しました Event Grid</a>。 新しいファイルのアップロードAzure Functions、イベントに応答してコードのスニペットを実行することもできます。</p>


  <p>Azure Functionsアプリ全体とサポート インフラストラクチャを作成する手間を省きます。 代わりに、必要なのは、現在の問題に焦点を当てた短いコード スニペット (選択した言語を使用) を記述する必要があります。 この合理化されたアプローチにより、Functions は、注文の処理、ファイルの管理、または定期的に操作する必要があるその他のほとんどのタスクに最適です。</p>


  <p>リアルタイムデータ&#39;履歴データを扱う場合でも、関数を自動化する必要がある場合でも、Azure IoT にはニーズを満たすツールがあります。 IoT の操作の詳細と、最初のデプロイを開始する簡単な方法については、 <a href="https://content.microsoft.com/iot/developerguide"><strong>IoT 開発者ガイドをダウンロードしてください</strong></a>。</p>
