### YamlMime:Yaml
ms.openlocfilehash: 3e722737adfb0f1947e84bc9bbfe4cae6f297253
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890789"
Slug: getting-started-with-the-new-azure-iot-suite-remote-monitoring-preconfigured-solution
Title: 新しい Azure IoT Suite リモート監視構成済みソリューションの使用を開始する
Summary: 先月、次世代の Azure IoT Suite 構成済みソリューションを作成するために行っている作業を発表しました。 更新された をデプロイできると発表します。
Content: >-
  <p>先月、<a href="https://azure.microsoft.com/en-us/blog/the-next-generation-of-azure-iot-suite-accelerates-iot-solutions/" target="_blank">次世代</a>の Azure IoT Suite 構成済みソリューションを作成するために行っている作業を発表しました。 新しいバージョンのリモート監視ソリューションを AzureIoTSuite.com および開発 <a href="https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Developer-Reference-Guide" target="_blank">CLI</a> からデプロイ<a href="https://www.azureiotsuite.com/" target="_blank">できる</a>と発表します。 これは、新しく有効にされたシナリオと機能が多く含まれる大規模な更新プログラムです。そのため、開始方法に関するガイダンスを提供したいと考えたのです。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d34c85d3-b01b-4702-864b-24a8043edb00.png"><img alt="PCSScreenShot" border="0" height="558" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3f1359ab-5bd2-4efb-82a1-be74ce067ea8.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="PCSScreenShot" width="997"></a></p>


  <h2>ソリューション コードを確認する</h2>


  <p>どちらのバージョンのソリューションもオープン ソースであり、現在から完全なカスタマイズを行う準備ができています。 ユーザー設定に基づいて探索を開始してください。</p>


  <ul>
   <li><a href="https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet" target="_blank">.NET バージョン リポジトリ</a></li>
   <li><a href="https://github.com/Azure/azure-iot-pcs-remote-monitoring-java" target="_blank">Java バージョン リポジトリ</a></li>
  </ul>


  <h2>ソリューション機能の詳細を確認する</h2>


  <p>すべてのドキュメントに対する大規模な更新が行われ、docs.microsoft.com と GitHub。 新しいドキュメントについては、こちらを参照してください。</p>


  <ul>
   <li><strong>構成</strong>済みのソリューション<a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-what-is-azure-iot" target="_blank"></a>の&nbsp;概要とアーキテクチャに関する概要<a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-what-are-preconfigured-solutions" target="_blank"></a>ドキュメントと、他のテクノロジの選択肢<a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-options" target="_blank">Azure IoT比較します</a>。</li>
   <li><strong>概要</strong>をデプロイして操作する方法を<a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-remote-monitoring-deploy" target="_blank">説明するチュートリアル</a><a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-remote-monitoring-explore" target="_blank">を参照してください</a>。</li>
   <li><strong>次のような</strong> さまざまなトピックについて深く掘り下げ、チュートリアルを行う方法: <ul>
    <li><a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-remote-monitoring-monitor" target="_blank">高度な監視を実行する</a>&nbsp;</li>
    <li><a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-remote-monitoring-automate" target="_blank">ルールを使用した問題の検出</a></li>
    <li><a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-remote-monitoring-manage" target="_blank">デバイスの管理</a></li>
    <li><a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-remote-monitoring-maintain" target="_blank">デバイスの問題のトラブルシューティング</a></li>
    <li><a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-remote-monitoring-test" target="_blank">シミュレートされたデバイスを使用する</a>&nbsp;</li>
    <li><a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-remote-monitoring-customize" target="_blank">ソリューションをカスタマイズする</a></li>
    <li>Connect Linux で物理デバイス<a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-connecting-devices" target="_blank">をWindows</a><a href="https://docs.microsoft.com/en-us/azure/iot-suite/iot-suite-connecting-devices-linux" target="_blank">する</a></li>
    <li><a href="https://docs.microsoft.com/en-us/azure/iot-suite/iot-suite-remote-monitoring-deploy-cli">デプロイを変更する</a></li>
    <li><a href="https://docs.microsoft.com/azure/iot-suite/iot-suite-remote-monitoring-sample-walkthrough" target="_blank">リモート監視のアーキテクチャ</a></li>
   </ul>
   </li>
  </ul>


  <p>また、Ignite プレゼンテーション「Building <a href="https://techcommunity.microsoft.com/t5/Microsoft-Ignite-Content-2017/Building-Reliable-IoT-Solutions-in-the-Cloud-Fast/td-p/109114" target="_blank"><em>Reliable IoT Solutions in the Cloud, Fast</em></a>(クラウドでの信頼性の高い IoT ソリューションの構築、高速)」をリッスンできます。このプレゼンテーションには、リモート監視ソリューションの更新で行われた&#39;の変更と、それを活用してカスタム IoT ソリューションをすばやく構築する方法が詳しく説明されています。</p>


  <h2>今後のトレーニングに登録する</h2>


  <p>新しいリモート監視に関するウェビナーが 2 つ予定されています。 すべてのユーザーが参加できます。サインアップするには、リンクに従います。</p>


  <ul>
   <li>2017 年 11 月 6 日午前 8 時 PT &amp; 5 PM PT - IoT Online: クラウドでの信頼性の高い <em><a href="https://learningportal.microsoft.com/learning-path?learningpathid=5145" target="_blank">IoT</a> ソリューションの構築、高速での C+E University ウェビナー</em></li>
   <li>2017 年 11 月 8 日午前 10 時 PT の Azure ウェビナー シリーズ - <em><a href="https://info.microsoft.com/en-us-landing-azure-iot-suite-remote-monitoring-live-webinar.html" target="_blank">次世代の Azure IoT Suite</a> リモート監視による IoT ソリューションの高速化</em></li>
  </ul>


  <h2>フィードバックを提供し、質問する</h2>


  <ul>
   <li>お客様&rsquo;のフィードバックをお寄せください。 機能と <a href="https://feedback.azure.com/forums/321918-azure-iot" target="_blank">今後サポートされる</a> シナリオに関する提案を受け取るユーザーの音声チャネルがあります。 他のユーザーが提案している情報を参照し、お気に入りに投票して、自分の提案を入力する方法も推奨されます。</li>
   <li>ソリューションで問題が発生した場合は、GitHub リポジトリ (.NET と Java) で問題<a href="https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/issues" target="_blank">を開</a><a href="https://github.com/Azure/azure-iot-pcs-remote-monitoring-java/issues" target="_blank">きます</a>。</li>
   <li>最も頻繁に寄せられる <a href="https://docs.microsoft.com/en-us/azure/iot-suite/iot-suite-faq" target="_blank">質問に</a> 対する回答については、パブリック FAQ を参照してください。</li>
  </ul>


  <h2>ソリューションをお試しください</h2>


  <p>開始するには、<a href="https://www.azureiotsuite.com/" target="_blank">AzureIoTSuite.com</a> からリモート監視ソリューションの更新バージョンをデプロイするか、新しい対話型デモを確認して、ソリューションの動作を確認<a href="https://www.microsoft.com/en-us/internet-of-things/remote-monitoring" target="_blank"></a>します。</p>


  <p>フィードバックをお待ちしております。</p>
