### YamlMime:Yaml
ms.openlocfilehash: f87ecc5cdf215e0516bf48a77f9cb9aeb4089297
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909213"
Slug: glimpse-application-insights
Title: Application インサイト Telemetry を見る
Summary: Application インサイト を気に入っている人がいて、知らない人もいて、これらの素晴らしいツールを聞いていない人もいます。 詳細については、少しお待ちください。
Content: >-
  <p>Application インサイトを好む人がいて、知&rsquo;り合いを気に入っている人がいて、これらの素晴らしいツールを聞いていない人もいます。</p>


  <p>開発中に Web アプリのプロファイリングとデバッグを行うのに便利ですが、Application インサイト は、ライブ実稼働環境での問題の診断とパフォーマンスの監視のためのツールです。 両方が必要なので、これらの製品を統合することを決定しました。</p>


  <h1>Application Insights とは何か?</h1>


  <p><a href="https://www.visualstudio.com/features/application-insights-vs">アプリケーション インサイト</a>、パフォーマンス、可用性、使用状況について、実稼働環境の Web アプリケーションを監視します。 これは、ユーザーがアプリで何を行うのかを理解し、失敗した要求と例外を診断し、ブラウザー、Web サーバー、またはバックエンド サービスでパフォーマンスの問題を見つけるのに役立ちます。</p>


  <p><img alt="appinsights" border="0" height="123" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ede00e7f-3376-46d9-b9a1-a93641780a4b.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="appinsights" width="610"></p>


  <h1>一見とは</h1>


  <p>Web 用の診断プラットフォームが簡単です。 Web アプリをデバッグしている間に、Inspect は Web 要求が発生した場合に検査し、デバッグ時間を短縮し、すべての開発者が Web アプリケーションを向上させる分析情報とツールを提供します。</p>


  <p><img alt="glimpse2" border="0" height="189" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/622c0212-d91c-4b28-bcc6-1551f1d47992.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="と見なす 2" width="610"></p>


  <h1>統合では何が提供されますか?</h1>


  <p>Application インサイトでは、要求に関するクライアントとサーバー側のテレメトリ、および依存関係の送信呼び出し、およびビジネス メトリックが自動的に収集されます。 これらの項目には、見た目で収集された他のデータと共に、[タイムライン] タブを使用してアクセスできます。ここで、Application インサイト は新しいカテゴリです。 今日の概要では、送信 HTTP 呼び出しに関する情報は提供しませんが、Application インサイトでは、それらを確認できます。</p>


  <p><img alt="glimpse-trace" border="0" height="183" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ba1a2ed5-bcbd-402c-a7d8-7b54579cf54d.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="と見なされます。" width="610"></p>


  <p>アプリケーション インサイトログ トレースと例外レポートも収集します。 これらは、[見た目のトレース] タブに表示されます。</p>


  <p><img alt="glimpse-trace2" border="0" height="121" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/49818b42-17f6-41fd-8f56-854a9da55bac.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="と見なす trace2" width="610"></p>


  <p>新しい [アプリケーション インサイト] タブには、アプリケーションが実稼働環境にデプロイされた後に収集するクライアントとサーバーからのすべての Application インサイト テレメトリが表示されます。</p>


  <p><img alt="glimpse-ai" border="0" height="183" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9dd6f747-f600-4334-9d55-edc754d463d1.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="は、次の方法で" width="610"></p>


  <h1>開発サイクル</h1>


  <p>この組み合わせのツールを使用すると、Diagnostics ハブVisual Studioと診断ハブを使用して、各 Web 要求への応答をトレースできます。 これらのツールを使用すると、要求パラメーター、セッション状態、クエリと構成設定SQLすぐにアクセスできます。 これにより、開発プロセスが簡素化され、デバッグが迅速になります。</p>


  <p><img alt="developmentcycle2" border="0" height="230" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/809f6161-5a13-4e64-995b-390aed0ee597.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="developmentcycle2" width="303"></p>


  <p>アプリが実稼働環境で実行されている場合、診断プロセスは異なります。 すべての要求が発生する様子を監視する代わりに、たとえば &ndash; 、負荷によって応答時間がどのように変化し、そのバリエーションの多くが依存関係 REST サービスやデータベースなどから発生したのかなど、統計情報を収集する必要があります。 失敗した要求&rsquo;&rsquo;がある場合は、影響を受けるユーザーの数を評価し、エラーの一部を選択してトレースを詳細に調べる必要があります。 これらは Application インサイト の長所です。</p>


  <p>多くの場合、Application インサイト を有効にするだけで、ライブ アプリに関して必要なすべての診断情報と使用状況情報を得るのに十分です。 ただし、テレメトリをカスタマイズして、使用状況とパフォーマンスに関するより詳細なフィードバックを取得できます。 Telemetr と Application インサイト の統合により、Application インサイトから取得したテレメトリを実稼働環境で微調整できます。</p>


  <p>[Application インサイト] タブを見て、アプリケーションを参照すると、特定のページに対して収集されるデータを正確に確認できます。 開発中にこれを行って、テレメトリコレクションを意図した方法で実装することができます。 チェックアウト価格またはキューの長さを正しく送信しましたか? 成功したトランザクションは、ビジネス テレメトリ イベントとして報告されましたか? アプリケーションをリリースすると、このテレメトリがビジネスおよび診断の分析情報のソースです。</p>


  <p>この統合は、開発で収集されたデータから実稼働環境で収集されたデータへの移行に役立ちますが、統合を改善してさらに価値を高める予定です。 新しいバージョンのアプリケーションを開発する場合は、インサイト NuGet の新しいバージョンを開発する前に、新しいバージョンのアプリケーションの実稼働データを、新しいバージョンのアプリケーション UI に表示する予定です。</p>


  <h1>今すぐ試す</h1>


  <p>この統合の実際の動作を確認し、独自のアプリケーションで試してみるには、NuGet パッケージのいずれかをインストールします。 現時点では、2 つのNuGetパッケージを使用できます。</p>


  <p>インサイト <a href="https://www.nuget.org/packages/Glimpse.ApplicationInsights.Web/1.0.0">Application インサイト Web</a> パッケージをインストールすると、アプリケーションの Application インサイト が有効にされ、基本的な一連の Packages が有効になります。 このパッケージには、Web アプリケーションに必要な他のパッケージへの依存関係が含まれています。これにより、これはすべてのユーザーに対する単純なソリューションになります。 Application インサイトにオンボードしていない場合は、このパッケージを使用する必要があります。 Application インサイト Web では、追加の作業を行わずに .NET Web アプリケーションがサポートされます。</p>


  <p><img alt="package_glimpse" border="0" height="125" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a54c5696-0b7c-466f-acd7-65826c1236b2.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="package_glimpse" width="610"></p>


  <p><strong>メモ：</strong>Application インサイト となびきを既にオンボードしている場合は、一時アプリケーション と インサイト NuGet<a href="https://www.nuget.org/packages/Glimpse.ApplicationInsights/1.0.0">できます</a>。 追加の機能が必要な場合は、ADO.NET、enityFramework、ASP.NET その他の拡張機能を手動でインストールできます。</p>


  <h1>特別な感謝</h1>


  <p>一見とアプリケーションインサイト統合は、複数の共同作成者を通じて可能なオープン ソース プロジェクトです。 <a href="https://github.com/oscargarciacolon">Oscar Garcia Colon</a> (MVP) の ALM Latam OOS チーム のリードに、Guillermo Zepeda の支援を受け、特別な感謝をいたします。 <a href="https://github.com/JoseCarlosMM">Carlos Carlos Mendez</a>、Aleiandro Damian、Carlos Carlos、Jorge Rodriguez、Jorge Rodriguez、<a href="https://github.com/SusanaL">Claudia Susana Lopez</a>、および、Microsoft Application インサイト の <a href="https://github.com/SergeyKanzhelev">Sergey Kanzhelev</a>、およびビガニ ム チーム: <a href="https://github.com/avanderhoorn">Anthony van der Hoorn</a>、<a href="https://github.com/nikmd23">Nik Molnar</a>。 3 つの異なるチームが一緒に統合を行い、皆さんも楽しんだと思います。</p>


  <h1>お知らせください&hellip;</h1>


  <p>一見とアプリケーションインサイト統合は進行中の作業です。 問題や機能の要求については、リポジトリにアクセス <a href="https://github.com/glimpse/glimpse.applicationInsights/issues">してください</a>。</p>


  <p>Application インサイトチームは、開発者に高品質のツールを提供する取り組みです。 フィードバックや新機能に関する推奨事項を大いに感謝します。</p>
