### YamlMime:Yaml
ms.openlocfilehash: 063a67afc16dd0a031ff4c450f81b48a62638511
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893023"
Slug: guidance-for-identity-management-in-multitenant-applications
Title: マルチテナントアプリケーションでの Id 管理のガイダンス
Summary: Microsoft Patterns & プラクティスグループは、Azure でのマルチテナントアプリケーションの Id 管理に関する新しいガイダンスを公開しました。
Content: >-
  <p>Microsoft <strong>Patterns &amp; プラクティス</strong> グループは、 <strong><a href="https://azure.microsoft.com/documentation/articles/guidance-multitenant-identity/">Azure でのマルチテナントアプリケーションの id 管理</a></strong>に関する新しいガイダンスを公開しました。</p>


  <p>マルチテナントアプリの構築を&#39;する場合、最初の課題の1つは、ユーザー id の管理です。これは、すべてのユーザーがテナントに属しているためです。 &nbsp; たとえば、ユーザーは自分の組織の資格情報でサインインできる必要があります。 Contoso で働く Alice は、として alice@contoso.com サインインします。</p>


  <p>Alice がサインインした後、Contoso のデータ &mdash; にアクセスし、他の組織に属するデータにアクセスすることはできません。 そのため、マルチテナント機能は承認ポリシーにも影響します。</p>


  <p>その他の考慮事項</p>


  <ul>
   <li>どの組織からでもアプリにサインインできますか。 または、組織が最初にサインアップする必要がありますか。</li>
   <li>すべてのユーザーが同じ特権を持っていますか。 または、ユーザーは、管理者、 &quot; &quot; 発行者、 &quot; &quot; 閲覧 &quot; 者など、アプリ &quot; 内で割り当てられたロールを取得します。</li>
  </ul>


  <p><a href="https://azure.microsoft.com/services/active-directory/">Azure Active Directory</a> (Azure AD) には、これらすべてのシナリオをサポートする優れた機能があります。 (現在、このガイダンスでは Azure AD のテナントのみがサポートされています)。</p>


  <p>このプロジェクトには、マルチテナントアプリケーションの実装と、 <a href="https://azure.microsoft.com/documentation/articles/guidance-multitenant-identity/">記述</a>されたガイダンスのサポートが含まれています。 <a href="https://github.com/Azure-Samples/guidance-identity-management-for-multitenant-apps">アプリケーション</a>は Tailspin という架空の会社に基づいているので、ユーザーはオンラインアンケートを作成できます。 このアプリは<a href="https://docs.asp.net/">ASP.NET Core 1.0</a> (旧称 &quot; ASP.NET 5 &quot; ) 上に構築されているため、ASP.NET の最新の認証および承認機能を使用します。</p>


  <blockquote>

  <p>注: このプロジェクトは、特に id 管理に焦点を合わせています。 データのパーティション分割など、他の問題については&#39;いません。</p>

  </blockquote>


  <p>アンケートアプリケーションは、web アプリとバックエンド web API で構成されています。 ここ &rsquo; には、認証プロセスの概要が表示されています。</p>


  <p><img alt="Azure AD" border="0" height="329" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5b483fa1-fb53-40a6-8e5e-d0f9bf52afbd.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="Azure AD" width="360"></p>


  <p>アプリケーションは Tailspin &rsquo; s Azure AD directory に登録されています。 これにより、Azure AD がアプリケーションの代わりにユーザーを認証できるようになります。 Contoso の alice が web アプリにサインインすると、Azure AD にリダイレクトされます。ここで、組織の資格情報を入力すると、web アプリは Alice (名前、電子メール) に関する一連の要求を受け取ります。 また、web アプリはアクセストークンを取得します。これにより、バックエンド web API を呼び出すことができます。</p>


  <p>また、この実装には、セキュリティやパフォーマンスなどの横断的な懸念に対処するいくつかの興味深い機能もあります。&nbsp;&nbsp;</p>


  <ul>
   <li>OAuth クライアントシークレットに代わる、より安全なクライアントアサーションの使用</li>
   <li><a href="https://azure.microsoft.com/services/key-vault/">Azure Key Vault</a>からアプリ設定を読み取り、接続文字列などの機密データを保護する</li>
   <li>分散キャッシュでの OAuth トークンのキャッシュ (web サーバー間で共有可能)</li>
  </ul>


  <p>この <a href="https://azure.microsoft.com/documentation/articles/guidance-multitenant-identity/">ガイダンス</a> では、認証、アプリケーションロール、ロールベースおよびリソースベースの承認、バックエンド Web API の認証など、さまざまなトピックについて説明します。</p>
