### YamlMime:Yaml
ms.openlocfilehash: 46b9383f34e5aeda00999afce52191987c9aeca7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893027"
Slug: guidance-for-enterprises-looking-to-take-their-application-portfolio-to-the-cloud
Title: アプリケーション ポートフォリオをクラウドに移行する企業向けガイダンス
Summary: 'アプリケーション カタログを備えるエンタープライズ環境をクラウドに移行する意味について、広範な調査を行いました。 詳細については、最近公開された電子書籍を参照してください。 '
Content: >-
  <p>ポートフォリオ全体のすべてのビジネス ドメインとアプリケーションで効率性とイノベーションの両方を達成できたとします。 クラウドとそのすべてのリソース &ldquo;と機能を利用して全体を取得できると、そのパーツ効果の合計を超える場合は、どうなる&rdquo; でしょうか。 優れたロード マップと実証済みの戦略を使用して、その道をリードすることができます。 アプリケーション カタログを備えるエンタープライズ環境をクラウドに移行する意味について、広範な調査を行いました。 &ldquo;最近公開された電子書籍「Enterprise Cloud Strategy&rdquo; by Barry Recentlygs」と私自身では、Microsoft&rsquo; 独自の体験や顧客からの例と学習エクスペリエンスを提供しています。</p>


  <p><a href="https://info.microsoft.com/enterprise-cloud-strategy-ebook.html?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">独自の道路マップを構築するのに役立つ戦略を提供する eBook を参照してください。</a></p>


  <p><img alt="Enterprise Cloud Strategy" border="0" height="360" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/91e9bef9-1c31-4939-aa6b-e5f6647f69a8.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Enterpriseクラウド戦略" width="295"></p>


  <p>さまざまな移行アプローチを強調し、その利点と複雑さを詳しく説明します。</p>


  <ul>
   <li><strong>再ホストします。</strong> VM またはオペレーティング環境をオンプレミスのデータセンターからホストまたはクラウドに移動します。 このモデルは、"コロケーション" とも呼ばれる。</li>
   <li><strong>再プラットフォーム。</strong> レガシ環境は、コストまたは運用上の要件に基づいて持続不可能になります。解決策は、コード &ldquo;を変更&rdquo; せずにアプリケーションを保持してラップし、操作の整合性とセキュリティを損なう可能性があります。</li>
   <li><strong>廃止と書き換え (または再構想)。</strong> 古い環境では満たできない十分な新しい要件がある場合は、より新しい、より適した環境でアプリケーションを書き換えるのが最善の方法です。 多くの場合、これはアプリケーションのポートフォリオを調べて、同様の機能を持つ複数のアプリケーションを統合するときに発生します。</li>
   <li><strong>バーストアウト。</strong> クラウド環境で提供される新しいコンピューティング、データ、およびサービス モデルはすべて、それぞれ IT 環境からアクセスできる機能と容量を提供し、多くのアプリケーションがクラウドにバーストしています。 これらのアプリケーションでは、革新的な種類の分析、レポート、ハイ パフォーマンス コンピューティング、視覚化などについて行っています。 頻繁に使用される (&ldquo;&rdquo;ホット) データをローカルに維持しながら、アクセス頻度の低い (&ldquo;&rdquo;コールド) データをはるかに低コストのクラウド ストレージに保存する方法も一般的です。</li>
   <li><strong>展開。</strong> 企業は、以前のアプリケーションを拡張する方法と、以前はコンピューター画面に制限されたのと同じ機能を使用してモバイル デバイスと Web フロントエンドに提供する機能を追加する方法を探っています。 たとえば、検索サービスやビデオ サービスを使用してアプリケーションを強化する動きもあります。</li>
   <li><strong>クラウドネイティブ アプリケーション。</strong> 企業がクラウドの調査を開始すると、ビッグ データ、新しい種類の分析、機械学習などの完全に新しい機能、クラウドに一意に適合する モノのインターネット (IoT) のアプリケーションなどの新しい形式のアプリケーションが頻繁に認識されます。</li>
  </ul>


  <p>たとえば、推奨されるクラウド移行計画は静的な計画ドキュメントよりもプロセスであり、各移行の詳細は通常、次のパターンに従います。</p>


  <ol>
   <li><strong>分析。</strong> これは、現在の状態を目的の状態にマッピングするプロセスです。 このプロセスは、現在持っているものと、そのワークロードをクラウドに移行するために必要なギャップを特定するのに役立ちます。 これらのギャップには、ワークロードのアーキテクチャの変更が含まれる場合や、プログラムの完全な書き換えが必要になる場合があります。</li>
   <li><strong>アプリケーションの移行。</strong> 特定のワークロードをクラウドに移動する必要がある場合、ベスト プラクティスは、最小限のデータを使用してワークロードのバージョンを作成して、アプリケーションをクラウドで動作するか、そこで新しいバージョンのアプリケーションを構築することです。 アプリケーションが既に VM 上で実行されている場合は、VM をクラウドに移行するだけで、それ以上変更を加えなくても済む可能性があります。 一般に、多くのオンプレミス アプリケーションは、最小限の変更または変更を必要としない Microsoft Azure で実行できますが、これは、アプリケーションがパフォーマンス、スケーラビリティ、セキュリティのために最適化されるという意味ではありません。 最新のサービス指向の原則を使用して、アプリケーションをある程度再設計して再構築する必要がある場合があります。</li>
   <li><strong>データ移行。</strong> これは、データ構造をクラウド上のリレーショナル (azure VM の Azure SQL Database、SQL Server) または非リレーショナル (BLOB、テーブル、キュー、Azure DocumentDB など) に、データ構造を移動できる点で、アプリケーションの移行とやや似ています。 これらの種類の移行のいくつかは非常に簡単であり、Azure 移行ウィザードなどのウィザードを使用SQL Server実行できます。 ただし、パフォーマンス、スケーラビリティ、回復性、およびセキュリティの向上を実現するために、データ モデルAzure SQL Database新しいデータ モデルとして再構築を検討してください。 オンプレミスと SQL Database 間、または異なる SQL Database サーバー間でデータを同期する必要がある場合は、SQL データ同期 サービスを設定して構成します。 また、ユーザー エラーや自然災害が発生した場合に備えて、データ復旧計画を設定して構成するのもベスト プラクティスです。</li>
   <li><strong>最適化とテスト。</strong> アプリケーションとデータを Azure に移行した後、機能とパフォーマンスのテストを実行します。 このフェーズでは、クラウド内のアプリケーションをテストし、正しく機能することを確認します。 次に、オンプレミスと Azure のパフォーマンス結果を比較します。 その後で、クラウド内のアプリケーションについて、機能、パフォーマンス、スケーラビリティの問題を解決します。</li>
   <li><strong>操作と管理。</strong> テストと最適化フェーズの後、Azure アプリケーション インサイト を使用してアプリケーションの監視とトレースを設定して実装します。これにより、アプリケーションからテレメトリを収集して分析できます。 このデータは、デバッグとトラブルシューティング、パフォーマンスの測定、リソース使用状況の監視、トラフィック分析と容量計画、監査に使用できます。</li>
  </ol>


  <p>クラウド戦略Enterprise&ldquo;&rdquo;、Eduグループ・カズナーと Barry By Barry の Edry を使用して調整されています。 カズナーは、Microsoft のワールドワイド Enterpriseパートナー グループのクラウド ソリューション アーキテクチャのディレクターです。 ソフトウェアおよびエンタープライズ コンピューティングの長い歴史を持つ独立したコンサルタントです。</p>


  <p><a href="https://info.microsoft.com/enterprise-cloud-strategy-ebook.html?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">電子書籍を今すぐダウンロードします。</a></p>
