### YamlMime:Yaml
ms.openlocfilehash: dbb89b29bb23c4e981c847062be8e449456dab63
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895936"
Slug: harness-the-power-of-data-and-ai-in-your-applications-with-azure
Title: Azure でアプリケーションのデータと AI の機能を活用する
Summary: 開発者にとってのコミットメントは、データと AI の機能を活用するインテリジェントなアプリケーションを開発するための最適なクラウドとして Azure を構築することです。 Microsoft のビルドでは、開発者が Azure データと AI サービスを簡単かつ低コストで利用できるようにする、いくつかの優れた新機能とプランが発表されています。
Content: >-
  <p>過去1年にわたって、これまでにない時間を移動する企業が新しいレベルの機敏性を必要としていることが明らかになって &rsquo; います。 この機敏性の中核となるのは、1回考えられてきたソフトウェア開発のレベルを絶するにすることです。 無制限のスケール、選択肢、および可能性を持つすべての開発者を支援するために、Microsoft Azure には戻ってきました。</p>


  <p>開発者にとってのコミットメントは、データと AI の機能を活用するインテリジェントなアプリケーションを開発するための最適なクラウド &nbsp; として Azure を構築することです。 Microsoft のビルドでは、開発者が Azure データと AI サービスを簡単かつ低コストで利用できるようにする、いくつかの優れた新機能とプランが発表されています。</p>


  <h2>Azure database services を使用したイノベーション</h2>


  <p>Microsoft は、開発者が Azure &rsquo; のデータベースサービスをイノベーションするのに役立ついくつかの新機能を発表します。 <a href="https://aka.ms/sql-ledger-blog" target="_blank">Azure SQL Database &rsquo; s 台帳機能</a>は、プレビュー段階で、機密性の高いレコードの暗号化の検証を提供します。 イギリスの石油をご利用のお客様にとっては、この魅力的な機能の恩恵を受けています。 microsoft <a href="https://azure.microsoft.com/en-us/services/synapse-analytics/" target="_blank">dataverse の Azure Link</a>は、microsoft Dynamics 365 と microsoft Power Platform アプリケーションからの洞察を即座に提供します。一方、 <a href="https://aka.ms/2021BuildPowerBI" target="_blank">microsoft Power BI streaming データフロー</a>は、信号から洞察までのボトルネックを取り除き &nbsp; ます。 また、Azure Cosmos DB にはいくつかの更新プログラムがあり、開発者が任意の規模で高パフォーマンスアプリケーションを構築および最新化するのに役立ちます。</p>


  <ul>
      <li><a href="https://aka.ms/cosmos-devblog-build-1" target="_blank">Azure Cosmos DB サーバーレス</a> &nbsp; がすべての api で一般公開されました。 サーバーレス料金は、消費されたリソースのみを対象としており、激しいトラフィックパターンを使用したアプリケーションのための優れたデプロイオプションです。 Albertsons やスイスなどのお客様は、現在この機能を活用しています。</li>
      <li><a href="https://aka.ms/cosmos-devblog-build-2" target="_blank">Azure Cosmos DB 統合キャッシュ</a> &nbsp; がプレビュー段階になりました。 統合キャッシュを使用すると、コストが最適化され、読み取り負荷の高いワークロードのパフォーマンスが、それぞれ最大96% と300% まで向上します。 ASOS などのお客様には、この魅力的な機能が既に利用されています。</li>
      <li><a href="https://aka.ms/cosmos-devblog-build-2" target="_blank">Azure Cosmos DB</a> &nbsp; の Always Encrypted がプレビュー段階になりました。 Always Encrypted を使用すると、開発者は、データベースに格納される前に、クライアントアプリケーション内の機密データを暗号化できます。</li>
      <li><a href="https://aka.ms/cosmos-devblog-build-2" target="_blank">Azure Cosmos DB ロールベースのアクセス制御</a>(RBAC) &nbsp; の一般提供が開始されました。 RBAC を使用すると、管理者は特定のルールを持つロールを定義し、ロールを Azure Active Directory (Azure AD) プロファイルに適用してアクセスレベルを決定することができます。</li>
  </ul>


  <p>Azure Cosmos DB は、世界 &rsquo; で最も要求の厳しいミッションクリティカルなアプリケーションを活用するために、データベースにアクセスすることになりました。 たとえば、Walmart の電子商取引プラットフォームを休日シーズン用に準備したときに、高可用性、10ミリ秒の待機時間をペタバイト規模で Azure Cosmos DB し、数十億の日々の要求を処理できるようになりました。&nbsp;&nbsp;</p>


  <p>&rsquo;また、Azure Cosmos DB、Azure Database for PostgreSQL、Azure Database for MySQL について、追加の低コストで無料のオプションも発表します。 現在、 <a href="https://aka.ms/cosmos-devblog-build-1" target="_blank">Azure Cosmos DB &rsquo; の拡張</a>された free レベルが一般公開されており、開発者は 1000 RU/秒 &nbsp; のプロビジョニング済みスループットと 25 GB のストレージを毎月無料でイノベーションする柔軟性を高めることができます。 <a href="https://aka.ms/cosmos-devblog-build-1" target="_blank">Azure Cosmos DB &rsquo; </a>の無料の linux エミュレーターであるプレビューでは、linux 開発者は linux および macOS コンピューターでローカルに Azure Cosmos DB をビルド、テスト、および学習できます。 <a href="https://aka.ms/postgresqlbuild21" target="_blank">Azure Database for PostgreSQL</a>と<a href="https://aka.ms/SunilBuild2021MySQL" target="_blank">Azure Database for MySQL</a>の柔軟なサーバーを6月に利用できる無料の12か月プランでは、開発者は、Azure 無料アカウントを使用して最初の12か月間無料で750時間まで無料でご利用いただけます。 さらに、プレビュー段階では、Azure Database for PostgreSQL ハイパースケール (Citus) の <a href="https://docs.microsoft.com/en-us/azure/postgresql/concepts-hyperscale-tiers" target="_blank">basic レベル</a>では、1つのノードでハイパースケール (Citus) を開始するためのコスト効率に優れたオプションが用意されています。これにより、実質的に無制限のスケールを実現するためのワーカーノードの追加が容易になります。</p>


  <h2>Azure AI でインテリジェントなアプリケーションを構築する</h2>


  <p>Azure &rsquo; s AI サービスは、すべてのスキルレベルの開発者に、選択したツールと言語を使用したインテリジェントなアプリケーションの構築を支援します。 機械学習の経験がない開発者は、単純な API 呼び出しによって、高品質の視覚、音声、言語、および意思決定 AI モデルにアクセスできます。 独自の機械学習モデルを構築している開発者は、jupyter notebook、Visual Studio &nbsp; コード、オープンソースフレームワークなどのツールを使用できます。これには、PyTorch や移行フローなどがあります。</p>


  <p>開発者が AI ソリューションをより迅速に構築できるように、Azure によって <a href="https://aka.ms/AppliedAITC" target="_blank">適用される Ai サービス</a>と呼ばれる追加のカテゴリのサービスが発表されます。 これらのサービスでは、 <a href="https://azure.microsoft.com/en-us/services/cognitive-services/" target="_blank">Azure Cognitive Services</a> とタスク固有の ai およびビジネスロジックを組み合わせることにより、ドキュメント処理、カスタマーサービス、コンテンツからの洞察の抽出など、一般的なシナリオ用の ai ソリューションの構築を迅速に行うことができます。 適用される AI サービスには、 <strong>azure Bot services、azure Cognitive Search、azure フォームレコグナイザー、azure Metrics Advisor、azure イマーシブリーダー</strong>が含まれており、多くの開発者が既に理解しています。 現在、 <a href="https://azure.microsoft.com/en-us/services/bot-service/" target="_blank">Azure Bot Services</a> を使用すると、統合された開発環境を通じて、テキスト、音声、またはテレフォニーベースのボットを簡単に構築、テスト、発行できます。 &nbsp;<a href="https://azure.microsoft.com/en-us/services/metrics-advisor/" target="_blank">Azure Metrics Advisor</a>は一般公開され、ダウンタイムを最小化するために自動的に問題を検出して診断します。 <a href="https://aka.ms/AppliedAISamsung" target="_blank">Samsung は、Azure Metrics Advisor を使用</a> して、smarttv サービスを強化しています。 現在プレビュー中の<a href="https://azure.microsoft.com/en-us/products/video-analyzer" target="_blank">Azure Video Analyzer</a>では、ライブビデオ分析と Video Indexer が提供されるため、開発者は AI を利用したビデオ分析ソリューションをすばやく作成できます。 Lufthansa は、 <a href="https://aka.ms/AppliedAIDow" target="_blank">Azure Video Analyzer</a>を利用して職場の安全性を向上させ、<a href="https://aka.ms/AppliedAILufthansa" target="_blank">運用効率を向上</a>させ、航空機のターンアラウンドをより安全にします。</p>


  <p>開発者は、Azure Machine Learning から独自のカスタムモデルを導入することで、適用された AI サービスを拡張できます。 <a href="https://aka.ms/AzureMLbuild2021" target="_blank">Azure Machine Learning のマネージエンドポイント</a>を使用すると、開発者は、モデルをアプリケーションに提供するために使用されるインフラストラクチャの作成と管理を自動化できます。 機械学習で PyTorch を使用している開発者にとっては、より信頼性の高い運用環境で<a href="https://aka.ms/PyTorchEnterpriseHeroBlog" target="_blank">PyTorch Enterprise</a>を使用できるようになり、優先度の高い要求やハンズオンサポートなどのメリットが得られるようになりました。</p>


  <p>低レベルの環境での構築を希望する開発者にとっては、Microsoft Power Apps が引き続き提供されます。 これで、すべての開発者は、AI による <a href="https://aka.ms/2021BuildPowerApps" target="_blank">アプリ開発アプローチ</a>を使用して、自然言語をコードやプログラムに変えることができます。 このエクスペリエンスは、世界中の最大の自然言語モデルの1つである OpenAI GPT-3 モデルを備えています。 Power Apps のこの追加機能は、Azure Machine Learning &rsquo; s マネージエンドポイントによって可能になります。</p>


  <h2>今すぐ始めましょう</h2>


  <p>これらの発表は、すべてのスキルレベルの開発者がデータと AI の力を活用するインテリジェントアプリケーションを構築できるクラウドとして、さらに <em>Azure のインテリジェンス</em> を受けています。 &nbsp;これにより、開発者はこれまでよりも簡単かつコスト効率の高い方法で Azure のイノベーションを&#39;&nbsp; できます。</p>


  <ul>
      <li>この今週のデジタル Microsoft ビルド &nbsp; で、次のセッションをライブまたはオンデマンドでキャッチし、詳細情報を取得します。&nbsp; <ul>
          <li><a href="https://mybuild.microsoft.com/sessions/46f12ac0-4d74-4a53-95b1-22e406edd72c" target="_blank">Azure でアプリケーションのデータの機能を活用する</a>&nbsp;</li>
          <li><a href="https://mybuild.microsoft.com/sessions/2ba55238-d398-46f9-9ff2-eafcd9d69df3" target="_blank">世界クラスの AI で infused インテリジェントなアプリケーションを構築</a>&nbsp;</li>
      </ul>
      </li>
      <li>Azure&#39;s マネージデータベースと AI サービスの詳細については、次を参照してください。 <ul>
          <li><a href="https://azure.microsoft.com/en-us/solutions/databases/" target="_blank">完全に管理されたデータベースを使用したアプリケーション開発の簡素化</a></li>
          <li><a href="https://azure.microsoft.com/en-us/overview/ai-platform/" target="_blank">Azure AI で、実績のある、セキュリティで保護された、責任を負う AI 機能をご利用いただけます</a></li>
      </ul>
      </li>
  </ul>


  <p><a href="https://azure.microsoft.com/en-us/free/" target="_blank">今すぐ始めましょう</a>。 &rsquo;次に何をビルドするかをお待ちしています。</p>


  <hr>

  <p><em>Microsoft.目的を持つ在庫。</em></p>
