### YamlMime:Yaml
ms.openlocfilehash: f858ea19c48e3d5dd8149ea0feff6c652acf08bf
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904781"
Slug: hdinsight-tools-for-vscode-simplifying-cluster-spark-job-configuration-management
Title: 'Visual Studio Code 用の HDInsight ツール: クラスターと Spark のジョブ構成管理の簡素化'
Summary: HDInsight Tools for Visual Studio Code (VS Code) が、HDInsight クラスターと Spark ジョブの送信を管理するための組み込みのユーザー設定とワークスペース設定を VS Code 利用できるようになったことをお知らせします。
Content: >-
  <p>HDInsight Tools for Visual Studio Code (VS Code) が、HDInsight クラスターと Spark ジョブの送信を管理するための組み込みのユーザー設定とワークスペース設定を VS Code 利用できるようになったことをお知らせします。 この機能を使用すると、リンクされたクラスターを管理し、VS Code のユーザー設定で優先する Azure 環境を設定することができます。 また、既定のクラスターを設定し、VS Code ワークスペースの設定を使用してジョブ送信の構成を管理することもできます。</p>


  <p>VS Code 用の hdinsight ツールは、世界中の Azure リージョンの hdinsight クラスターにアクセスできます。 hdinsight クラスター &nbsp; へのより柔軟なアクセス権を付与するには、Azure サブスクリプションを使用してクラスターにアクセスします。そのためには、Ambari のユーザー名とパスワードを使用して hdinsight クラスターにリンクするか、ドメイン名とパスワードを使用して hdinsight Enterprise セキュリティパッケージクラスターに接続します。 すべての Azure 設定とリンクされた HDInsight クラスターは、将来使用するために VS Code ユーザー設定に保持されます。 Spark ジョブの送信では、最大100個のパラメーターをサポートしているため、クラスターコンピューティングリソースの使用率を最大限に高めることができ、Spark ジョブのパフォーマンスを最適化するための適切なパラメーターを指定することもできます。 VS Code ワークスペースの設定を利用することで、JSON 形式のパラメーターを柔軟に指定できます。</p>


  <h2>新機能の概要</h2>


  <ul>
   <li>VS Code ユーザー設定を活用して、クラスターと環境を管理します。
   <ul>
    <li><strong>Azure 環境の設定:</strong> [コマンド] [ <strong>HDInsight: Set Azure Environment</strong>] の順に選択します。 指定された Azure 環境は、クラスターナビゲーション、データクエリ、およびジョブ送信用の既定の Azure 環境になります。</li>
    <li><strong>クラスターをリンクします。</strong> [コマンド] [ <strong>HDInsight: リンククラスター] の順に</strong>選択します。 リンクされたクラスターの情報は、[ユーザー設定] に &nbsp; 保存されます。</li>
   </ul>
   </li>
   <li>PySpark ジョブの送信を管理するには、[VS Code] ワークスペース設定を使用します。
   <ul>
    <li><strong>既定のクラスターの設定:</strong> &nbsp;[コマンド] [ <strong>HDInsight: 既定のクラスターの設定</strong>] の順に選択します。 指定されたクラスターは、PySpark または Hive データクエリとジョブ送信の既定のクラスターになります。</li>
    <li><strong>構成の設定:</strong> &nbsp;[コマンド] [ <strong>HDInsight: 構成の設定</strong>] を選択して、Spark ジョブ Livy の構成のパラメーター値を指定します。</li>
   </ul>
   </li>
  </ul>


  <h2>インストールまたは更新する方法</h2>


  <p>まず、Visual Studio Code をインストールし、Mono 4.2. x (Linux および Mac 用) をダウンロードします。 次に、VSCode 拡張機能リポジトリまたは VSCode Marketplace に移動して、 <strong>Hdinsight tools For VSCode</strong>を検索して、最新の hdinsight ツールを取得します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/de06da16-d4c2-4f2f-a8cf-5ab29ef2278e.png"><img alt="image" border="0" height="210" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3bf4b3a1-2dfb-4d8f-93bd-4e6a975116c6.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="画像 " width="420"> </a> vscode 用の HDInsight ツールの詳細については、次のリソースを参照してください。</p>


  <ul>
   <li>ユーザーマニュアル: <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-for-vscode">VSCode 用 HDInsight ツール</a></li>
   <li>ユーザーマニュアル: <a href="https://docs.microsoft.com/en-us/azure/hdinsight/set-up-pyspark-interactive-environment?branch=pr-en-us-26060">PySpark 対話型環境のセットアップ</a></li>
   <li>デモビデオ: <a href="https://youtu.be/RLjVNP8ufuw">VSCode 用 HDInsight ビデオ</a></li>
   <li>Hive LLAP: <a href="https://docs.microsoft.com/en-us/azure/hdinsight/interactive-query/apache-interactive-query-get-started">HDInsight で対話型クエリを使用する</a></li>
  </ul>


  <p>今日 &rsquo; の発表の詳細については、 <a href="https://blogs.msdn.microsoft.com/azuredatalake">ビッグデータブログ</a>を参照してください。 詳細については、 <a href="https://azure.microsoft.com/en-us/updates/">Azure サービスの更新</a> に関するページを参照してください。</p>


  <p>質問、フィードバック、コメント、またはバグレポートがある場合は、以下のコメントを使用するか、に <a href="mailto:hdivstool@microsoft.com">hdivstool@microsoft.com</a> メモをお送りください。</p>
