### YamlMime:Yaml
ms.openlocfilehash: 3aaa53c2c11f142f810fae206b602b1bcdb4fb17
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908971"
Slug: hdinsight-tools-for-vscode-supports-azure-environments-worldwide
Title: HDInsight Tools for VSCode では、世界中の Azure 環境がサポートされます
Summary: 世界中の HDInsight のお客様により良いサービスを提供するために、HDInsight Tools for VSCode は、HDInsight サービスをホストしているすべての Azure 環境に接続できます。
Content: >-
  <p align="left">世界中の HDInsight のお客様により良いサービスを提供するために、HDInsight Tools for VSCode は、HDInsight サービスをホストしているすべての Azure 環境に接続できます。 これには、特定のコンプライアンスとデータ主権の要件を持つお客様によって使用される Azure Government クラウドとリージョン クラウドが含まれます。 開発者は、VSCode コマンド パレットの [ <b>Azure 環境</b> の設定] コマンドを使用して、さまざまな Azure 環境を簡単に切り替えます。 この機能は、Azure 政府機関や地域の環境向けのデータ クエリやジョブの送信が簡単なエディターを作成する必要があるが、難しいと感じ、Hive および Spark の開発者にとって特に便利です。 この新しい機能を使用すると、HDInsight Tools for VSCode への高速でシンプルなアクセスを提供し、クリックだけで Azure 環境に接続することで、お客様を支援します。</p>


  <h2><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/66b04a50-7e5d-4955-b31e-17a877ca37f6.png"><img alt="Azure Command" border="0" height="60" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a4f5855d-b9be-4832-888b-f6a2c1377af4.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure コマンド" width="600"></a></h2>


  <h2><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/69cf1678-055b-4fde-ad2e-049e335d843f.png"><img alt="Azure Environment" border="0" height="130" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8edc054c-e7b4-4a22-9f9d-438d2ba12b5d.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure 環境" width="600"></a></h2>


  <p align="left">前の通信で説明した通り、HDInsight Tools for VSCode では、Hive Interactive Query、Hive Batch、PySpark Interactive、PySpark Batch がサポートされています。 軽量でクロスプラットフォームであり、HDInsight での開発エクスペリエンスが大幅に向上します。 最近のお知らせについては、以下のブログを参照してください。</p>


  <ul>
   <li><a href="https://azure.microsoft.com/en-us/blog/run-you-hive-llap-pyspark-job-in-visual-studio-code-vscode/">Hive LLAP &amp; Batch ジョブを実行する方法Visual Studio Code</a></li>
   <li><a href="https://azure.microsoft.com/en-us/blog/run-your-pyspark-interactive-query-and-batch-job-in-visual-studio-code/">PySpark のジョブInteractive Queryバッチ ジョブを次のコマンドで実行Visual Studio Code</a></li>
  </ul>


  <h2>インストールまたは更新する方法</h2>


  <p align="left">最初に、Visual Studio Codeインストールし、Mono 4.2.x (Linux および Mac の場合) をダウンロードします。 次に、VSCode 拡張機能リポジトリまたは VSCode Marketplace &ldquo; にアクセスし、<strong>HDInsight Tools for VSCode を検索して、最新の HDInsight ツールを取得します</strong>&rdquo;。</p>


  <p align="center"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/afcf4676-91c3-4fe0-a8c5-a6fb0fc3d93e.png"><img alt="a4991f2e-c132-4794-8a4c-08b3cf68b328" border="0" height="300" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b9c84107-ffd7-44c0-91f5-20a4ebf6b0e2.png" style="border-image: none; display: inline; background-image: none;" title="a4991f2e-c132-4794-8a4c-08b3cf68b328" width="600"></a></p>


  <p align="left">HDInsight Tools for VSCode の詳細については、次のリソースを使用してください。</p>


  <ul>
   <li>ユーザー マニュアル: <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-for-vscode">HDInsight Tools for VSCode</a></li>
   <li>ユーザー マニュアル: <a href="https://docs.microsoft.com/en-us/azure/hdinsight/set-up-pyspark-interactive-environment?branch=pr-en-us-26060">PySpark Interactive Environment を設定する</a></li>
   <li>デモ ビデオ: <a href="https://youtu.be/RLjVNP8ufuw">HDInsight for VSCode ビデオ</a></li>
   <li>Hive LLAP: <a href="https://docs.microsoft.com/en-us/azure/hdinsight/interactive-query/apache-interactive-query-get-started">HDInsight Interactive Queryを使用する</a></li>
  </ul>


  <p>今日のお知らせの&rsquo;詳細については <a href="https://azure.microsoft.com/en-us/blog/">、Azure</a> ブログとビッグ データブログ <a href="https://blogs.msdn.microsoft.com/azuredatalake">を参照してください</a>。 詳細については、Azure サービスの <a href="https://azure.microsoft.com/en-us/updates/">更新に関するページを</a> 参照してください。</p>


  <p>質問、フィードバック、コメント、またはバグ レポートがある場合は、以下のコメントを使用するか、 にメモを送信してください <a href="mailto:hdivstool@microsoft.com">hdivstool@microsoft.com</a>。</p>
