### YamlMime:Yaml
ms.openlocfilehash: f41001109a02f34d7c1b12bd424f3475a37a8572
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904156"
Slug: hololens-2-industrial-edition-brings-mixed-reality-to-regulated-environments
Title: HoloLens 2 工業 Edition では、規制される環境に mixed reality がもたらされる
Summary: HoloLens 2 については、energizing の最初の年であり、市場でもあります。 私たちは、お客様が業界全体にわたって顧客を強化し、生産性を向上させ、目的をイノベーションする方法を HoloLens 2 しています。
Content: >-
  <p><a href="https://www.microsoft.com/en-us/hololens/buy" target="_blank">HoloLens 2</a>については、energizing の最初の年であり、市場でも &rsquo; ありました。 私たちは、お客様が業界全体にわたって顧客を強化し、生産性を向上させ、目的をイノベーションする方法を HoloLens 2 しています。</p>


  <ul>
      <li><a href="https://www.youtube.com/watch?v=GRLyP7_cqNc" target="_blank">Lockheed Martin</a>は、HoloLens 2 を使用して Orion を構築し、8時間のシフトを要求するために使用されるタッチ &mdash; 操作を45分で完了できるようになりました。</li>
      <li><a href="https://customers.microsoft.com/en-ca/story/825289-imperial-nhs" target="_blank">英国大学の医療 nhs 信頼</a>は、HoloLens 2 を使用して、医療従業員&#39;の露出を covid-19 で患者に限定しています。これにより、スタッフが病気に公開される時間が83% に短縮されます。</li>
      <li><a href="https://customers.microsoft.com/en-ca/story/839709-mercedes-benz-automotive-holoLens-en-usa" target="_blank">Benz USA</a>は、サービス技術者の効率を向上させ、問題解決までの時間を短縮するために HoloLens 2 を使用して、サービス技術者の移動を35から40% 削減します。</li>
  </ul>


  <p>リスニングの一部として、常に学習するために、厳格な要件を持つ環境や業界の認定によって規制されている環境で、HoloLens 2 が運用することを強く求めています。 半導体および製薬業界では、パートナーは、高度に制御されたクリーンルーム環境に入るために、パーティクル排出基準を満たすデバイスを必要としています。 エネルギー部門のパートナーには、危険な環境で安全に機能できるデバイスが必要です。</p>


  <h2>ワーカーの生産性を高め、イノベーションを促進</h2>


  <p>HoloLens 2 工業 Edition が発表されました。これは、規制されている工業環境をサポートするために設計、構築、テストされたならでは混合現実デバイスです。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/18ff41b8-5c63-4fa5-9b8b-0d059635e0d5.png"><img alt="Medical worker in protective gear using Microsoft HoloLens 2" height="574" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b3c47754-4d4b-4ec9-b1bf-aa8a15dc90b8.png" style="margin-right: auto; margin-left: auto; display: block;" title="hololens 1" width="1024"></a></p>


  <p>HoloLens 2 工業エディションは、次の工業規格と認定を満たしています。</p>


  <table class="MsoTableGrid" style="border-collapse:collapse; border:none">
      <tbody>
          <tr>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:2px solid black; border-right:2px solid black; border-left:2px solid black" valign="top">
              <p><strong>HoloLens 2 工業 Edition 標準</strong></p>
              </td>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:2px solid black; border-right:2px solid black; border-left:none" valign="top">
              <p><strong>Rating</strong></p>
              </td>
          </tr>
          <tr>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:none; border-right:2px solid black; border-left:2px solid black" valign="top">
              <p>クリーンルームとの互換性</p>
              </td>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:none; border-right:2px solid black; border-left:none" valign="top">
              <p>ISO 14644-1 クラス5-8</p>
              </td>
          </tr>
          <tr>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:none; border-right:2px solid black; border-left:2px solid black" valign="top">
              <p>組み込みの安全性</p>
              </td>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:none; border-right:2px solid black; border-left:none" valign="top">
              <p>UL クラス I、除算 &nbsp; 2</p>
              </td>
          </tr>
      </tbody>
  </table>


  <p>工業規格の評価に加えて、HoloLens 2 工業 Edition は2年間の保証と高速な代替プログラムでサポートされています。 迅速な置換プログラムを使用すると、事前の exchange と優先配送によってダウンタイムが最小限に抑えられます。</p>


  <p>HoloLens 2 工業 Edition では、お客様はスペース、プロトコル、ワークフローを変更することなく、HoloLens 2 を制限付き環境で使用できるようになりました。 Azure の信頼性、セキュリティ、およびスケールによって支えられている、ファーストパーティとサードパーティの混合現実アプリケーションの信頼性の高いエコシステムでサポートされています。 HoloLens 2 工業 Edition では、規制された環境で運用している企業が次のことを支援します。</p>


  <ul>
      <li>必要なときはいつでもリモートのエキスパートにアクセスできるようにします。</li>
      <li>対話型の3D ガイドでは、これまでよりも迅速かつ正確にタスクを完了できます。</li>
      <li>アプローチを採用することで、 &ldquo; 新しい従業員のトレーニングと配布を迅速に行う &rdquo; ことができます。</li>
  </ul>


  <p>HoloLens 2 工業 Edition は、HoloLens 2 が利用可能な市場を選択し、出荷が Spring 2021 で開始されます。 詳細につい<a href="https://www.microsoft.com/en-us/hololens/buy" target="_blank">ては、詳細を</a>確認するか、Microsoft channel supplier にお問い合わせください。</p>
