### YamlMime:Yaml
ms.openlocfilehash: cd190929353071c29c29738a914bba6c8b2ffc05
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909810"
Slug: how-azure-security-center-aids-in-detecting-good-applications-being-used-maliciously
Title: 適切なアプリケーションが悪意のあるものであることを検出するために役立つ Azure Security Center 方法
Summary: この記事では、Azure Security Center によって侵害された Vm 上の悪意のあるアクティビティを検出する方法について説明しました。これには、Bitcoin マイニング攻撃の詳細と、送信 DDoS 攻撃に関する情報が含まれます。 多くの場合、攻撃者は悪意のあるツールのセットを使用して、侵害されたコンピューター上でこれらの操作や他のアクションを実行します。
Content: >-
  <p>これまでは、Azure Security Center によって侵害された Vm 上の悪意のあるアクティビティを検出する方法について説明しまし &rsquo; た。これには、 <a href="https://azure.microsoft.com/en-us/blog/how-azure-security-center-detects-a-bitcoin-mining-attack/">bitcoin マイニング攻撃</a> の詳細と、 <a href="https://azure.microsoft.com/en-us/blog/how-azure-security-center-detects-ddos-attack-using-cyber-threat-intelligence/">送信 DDoS 攻撃</a>に関する記事が含まれます。 多くの場合、攻撃者は悪意のあるツールのセットを使用して、侵害されたコンピューター上でこれらの操作や他のアクションを実行します。 しかし、セキュリティ研究者のチームは、攻撃者が適切なアプリケーションを使用して悪意のあるアクションを実行している新しい傾向を特定しました。 このブログでは、既知のハッカーツールとその性質に不正ないツールの使用について説明しますが、悪意を持って使用されていること、およびそれらの使用を検出するために役立つ Azure Security Center 方法について説明します。</p>


  <h2>ハッカーツールは悪用に役立ちます。</h2>


  <p>一般に、ブルートフォース攻撃の後に見られるツールの最初のカテゴリは、ポートと IP アドレスのスキャンツールです。 これらのツールのほとんどは悪意のあるものではありませんでしたが、攻撃者は IP 範囲とポートをスキャンして、標的にできる脆弱なコンピューターを見つけることができます。</p>


  <p>より頻繁に使用されるポートスキャンツールの1つは、KportScan 3.1 です。これには、開いているポートとローカルポートをスキャンする機能があります。 これにはさまざまな用途があります。これには、任意のポートや個々のアドレスと IP 範囲の操作が含まれます。 &nbsp;これはマルチスレッド (1200 フロー) であり、侵害されたコンピューター上でほとんどのリソースを消費します。最適なのは、ツールが無料であることです。 &nbsp;スキャンを実行すると、既定ではresults.txt&rdquo; という名前 &ldquo; のファイルに結果が保存されます。 次の例では、KportScan は、ポート3389がインターネットに対して開いている指定された範囲の IP &rsquo; をすべて返すように構成されています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/131be5f2-9015-4678-af4a-366c1e5a4279.png"><img alt="image" border="0" height="386" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b8598017-f98d-48d3-a035-65d953b3a367.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="500"></a></p>


  <p>侵害された後にコンピューターにドロップした他のスキャナーには、Masscan、xDedicIPScanner、D3vSpider などがあります。 &nbsp; これらはあまり頻繁ではなく、注目に値する傾向があります。</p>


  <p>Masscan は、最速のインターネットポートスキャナーの1つであることを要求します。 インターネット全体を6分以内でスキャンし、独自のネットワーク帯域幅が唯一の影響要因であることを確認します。 &nbsp;Linux は主要なプラットフォームですが、Windows や Mac OS X など、他の多くのオペレーティングシステムで実行されます。 &nbsp;次のコマンドは、3389上の開いているポートをスキャンします。この場合、サブネットの範囲は 104.208.0.0 104.215.255.255 になります。これは、アドレスが 512 kb です。 &nbsp;結果は、good.xml という名前の XML ファイルに格納されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/84c4f84c-4bae-49fd-adfb-71fc4a0db14d.png"><img alt="image" border="0" height="51" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/38ad4743-6936-4669-a497-688a3f488f0d.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="絵" width="460"></a></p>


  <p>xDedicIPScanner は、Masscan に基づく別のポートスキャナーです。 Masscan と同じ機能の多くが用意されていますが、GUI ベースで Linux を学習する必要はありません。 &nbsp; 一部の機能には、CIDR ブロックのスキャン、国範囲の自動読み込み、小型フットプリント、複数のポートまたはポートの範囲のスキャン機能などがあります。 また、実行するアプリケーションの依存関係もいくつかあります。これには winpcap と Microsoft Visual C++ 2010 が含まれます。 また Windows 7 以降も必要です。 私たちの所見から、xDedicIPScanner は、主に悪意を持って使用されているように見えます。 次の例は、スキャンのためにツールに読み込まれる国の範囲を示しています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7380b4a9-9f45-41b1-956a-38623e740e45.png"><img alt="image" border="0" height="362" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bd1ffe8e-702f-40d6-9428-9488867e6af4.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="320"></a></p>


  <p>最後に、Pastebin D3vSpider も頻繁に見てきたスキャナー &rsquo; です。 D3vSpider はポートスキャナーではなく、テキストの保存と共有 (盗まれたパスワード、ユーザー名、ネットワークデータを含む) のためによく使用される Pastebin リポジトリをスキャンします。 ツール &rsquo; の出力はユーザー &rsquo; の入力検索条件に基づいており、ユーザー名やパスワードなどの情報を提供します。 次の例では、1か月に745のユーザー名とパスワードが生成されたスキャンを示しています。これは、今後使用するために txt ファイルにエクスポートでき、他のツールでも使用できます。 たとえば、これは、既知の RDP ブルートフォースツールである、NLBrute で使用できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/af04f66e-c441-45b0-ac97-9f609ba69742.png"><img alt="image" border="0" height="334" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b9391e35-b6d7-4f7d-bd47-4f24eeaca561.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="338"></a></p>


  <p>&nbsp;</p>


  <p>最近では、悪意のあるその他の悪意のあるツールを削除するために使用されているメッセージングアプリケーションの使用について説明しました。 メッセージングアプリケーションは広く使用されており、悪意のあるものではありません。 クラウドベースのメッセージングサービスであり、デスクトップシステムとモバイルデバイスの両方を含む広範なデバイスがサポートされている傾向があります。 製品のユーザーは、エンドツーエンド暗号化の有無にかかわらず、メッセージ、あらゆる種類のファイルを交換できます。また、すべてのユーザー &rsquo; のデバイス間でメッセージを同期させることもできます。 &nbsp; これらのメッセージングサービスの一部では、配信後もメッセージを &ldquo; 自己破棄され &rdquo; にすることができるため、どのデバイスにも表示されなくなりました。 これらのメッセージングアプリケーションの機能の1つに、シークレット &rdquo; チャットと &ldquo; 呼ばれるものがあります。 ユーザーは、暗号化キーを交換した後、exchange の後に確認され、追跡される可能性がなくても自由に通信できます。 これらの機能やその他の機能により、これらのメッセージングサービスは、一部の攻撃者 &rsquo; ツールボックスに追加されました。&nbsp;</p>


  <p>他のコンピューターにファイルを簡単にドロップできるのは、攻撃者がこのプログラムを使用する主な理由の1つです。 実際には、2016年12月より早い段階で、構成されたマシン上でこれらのツールの存在が見られるようになりました。 &nbsp; まず、これは偶然として破棄されましたが、さらに調査を開始した後は、これらのメッセージングアプリケーションのインストール後に感染したコンピューターに既知のハッカーツール (NLBrute、Dubrute、D3vSpider) が表示されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6aa491c8-780e-429f-8ff9-29e39e76d3ed.png"><img alt="image" border="0" height="280" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/07834e10-5609-44ba-946d-8be3c6710cce.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="373"></a></p>


  <p>これらのツールは、すべてのユーザーのデバイス間でメッセージを同期できるため、メッセージ交換の一部であるすべてのユーザー &rsquo; は、後でメッセージを再表示して、ファイルまたは画像をダウンロードすることができます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5bf0c51c-3d63-40b6-b196-ec036f9d3132.png"><img alt="image" border="0" height="274" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/67eed22d-7c93-492c-8d83-ca8d6399553c.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="365"></a></p>


  <p>&nbsp;</p>


  <p>もう1つの方法として、メッセージを配信するための主要な目的として、メッセージチャネルが作成されています。これは、無制限の数のサブスクライバーに対して行われます。 チャネルは、一般公開されている場合もプライベートである場合もあります。 パブリックチャネルを任意のユーザーが参加させることができます。 ただし、プライベートチャネルの場合は、参加する招待を追加または受信する必要があります。 これらのアプリケーションは暗号化されているため、チャットチャネルに参加しているコンピューター以外のアクティビティはほとんどありません。次に例を示します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3a0cfe9b-78e8-4a9e-915c-e4ba4f59c992.png"><img alt="image" border="0" height="33" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/415c31da-678d-4ea4-9b3d-c6820bfd46c7.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="1024"></a></p>


  <p>チャネルへの参加は重要ですが、この後にコンピューターに表示されるファイルは最も興味深いものです。 &nbsp; これらのツールは、攻撃者がトラフィックを隠し、アクティビティの発信元 IP アドレスを隠すことを可能にする、クラックツール、RDP ブルートフォースツール、暗号化ツールの範囲です。 次に示すのは、プライベートチャネルに接続した後にホストで直接見られたものの例です。&nbsp;</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/119bb607-94f6-4dc0-afb0-0307867311a8.png"><img alt="image" border="0" height="222" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/402495a4-2924-423b-a146-98783d45c4c3.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="絵" width="800"></a></p>


  <h3>次のよう &rsquo; になります。</h3>


  <p>&rsquo;攻撃者が優先する、より頻繁に見られるツールをいくつか紹介し、Azure の仮想マシンで使用しています。 これらのツールは、ほとんどの場合、悪意のある目的ではなく正当な用途のために作成されていました。</p>


  <p>これらのツールのいずれかの存在はアラームの理由ではありませんが、他の要因を詳しく調べることは、悪意のあるものかどうかを判断するのに役立ちます。 たとえば、Azure の仮想マシンに複数の項目が表示されている場合、コンピューターが侵害される可能性ははるかに高く、さらに調査が必要になる可能性があります。 Azure コンピューター上の他のアクティビティのコンテキストでツール &rsquo; の使用状況を確認することは、これらのツールが悪意を持って使用されているかどうかを判断する上でも非常に重要です。 &rsquo; <a href="https://azure.microsoft.com/en-us/blog/azure-security-center-adds-context-alerts-to-aid-threat-investigation/">Azure Security Center コンテキストアラート</a>についてのセキュリティに関する注意事項については、Security Center によって自動化される面倒なセキュリティ調査の量、および関連するコンテキストについて説明しています。 KportScan、Masscan、XDedicIPScanner、D3vSpider、悪意のあるメッセージングサービスなどのツールは、Azure Security Center のコンテキストアラートによって検出され、アラートが生成されます。</p>


  <p>調査されたインシデントの数から、悪意のある目的に対する正当なツールの使用は、上昇傾向にあるように見えます。 回答として、アナリスト、調査担当者、および開発者の Azure Security Center &rsquo; s チームは、これらの種類の侵害の兆候を積極的に調査し、監視しています (その多くは、一部の AV 署名では検出されません)。 現在、このブログで説明されているすべてのツールを検出しています。さらに、これらのツールを Azure Security Center 検出に追加しています。</p>


  <h2>推奨される修復手順と軽減策</h2>


  <p>Microsoft では、使用可能なログソース、ホストベースの分析、および必要に応じて、侵害の画像を構築するために必要な場合は、攻撃キャンペーンを調査することをお勧めします。 Azure &lsquo; Infrastructure as a Service &rsquo; (IaaS) 仮想マシン (vm) の場合は、実行中のコンピューターおよびディスクイメージング機能にデータドライブを接続する機能など、データの収集を容易にするためにいくつかの機能が用意されています。</p>


  <p>対象となるコンピューターがクリーンであることを確認できない場合、または侵害の根本原因を特定できない場合は、重要なデータをバックアップして新しい仮想マシンに移行することをお勧めします。 また、セキュリティ侵害や再感染を防ぐために、仮想マシンをオンラインにする前にセキュリティを強化することをお勧めします。 ただし、これはすぐには実行できないことを理解しているため、次の修復手順を実装することをお勧めします。</p>


  <ul>
   <li><strong>アプリケーションの確認</strong>: 悪意のあるプログラムが悪用されたり、使用されない可能性がある場合は、ホスト上にある管理者とユーザーのアプリケーションを確認することをお勧めします。 既知のユーザーによってインストールされていないアプリケーションがあると判断された場合は、管理者によって決定される適切な操作を行うことをお勧めします。</li>
   <li><strong>Azure Security Center の推奨事項を確認</strong>します。 Security Center によって特定されたセキュリティの脆弱性を確認して対処します (たとえば、パスワードの保存を許可しない)。 os の構成に、セキュリティ更新プログラムが適用されていない、またはマルウェア対策による保護が適用されていないコンピューターなどがあります。</li>
   <li><strong>Defender scan</strong>: Microsoft Antimalware または別のソリューションを使用して、マルウェア対策スキャンを実行します。これにより、潜在的なマルウェアにフラグを付けることができます。</li>
   <li>クラックされた<strong>ソフトウェアの使用を避ける</strong>: 悪意のあるソフトウェアを使用すると、マルウェアや海賊版ソフトウェアに関連するその他の脅威に対する望ましくないリスクが生じます。 マイクロソフトは、お客様の組織によって推奨されているように、ひび割れのあるソフトウェアを使用しないことを強くお勧めします。</li>
  </ul>


  <p>Azure Security Center の詳細については、次を参照してください。</p>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-detection-capabilities">Azure Security Center の検出機能</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-managing-and-responding-alerts">Azure セキュリティ センターでのセキュリティの警告の管理と対応</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-recommendations">Azure Security Center でのセキュリティに関する推奨事項の管理</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-monitoring">Azure Security Center でのセキュリティ ヘルスの監視</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-partner-solutions">Azure Security Center を使用したパートナーソリューションの監視</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-faq">Azure Security Center のよく寄せられる質問 (FAQ)</a>。</li>
  </ul>


  <p>Azure security の <a href="https://blogs.msdn.com/b/azuresecurity/">ブログ</a>を参照して、azure のセキュリティに関する最新のニュースと情報を入手してください。</p>
