### YamlMime:Yaml
ms.openlocfilehash: 2b34f0a7d1eb7cbe09507ad5fbfdaa8a96e6f63d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893485"
Slug: how-developers-can-get-started-with-building-ai-applications
Title: 開発者が AI アプリケーションの構築を開始する方法
Summary: 最近では、膨大な量のデータ、クラウド、アルゴリズムやハードウェアのイノベーションなどによって、実際の AI イノベーションが加速しています。 では、開発者はどのようにして、顧客を引き付け、楽しませ、運用を最適化し、従業員を支援し、製品を変革する AI アプリケーションを設計し始めるのでしょうか。
Content: >-
  <p><em>このブログは、CTO AI のプリンシパル マネージャーである <a href="https://azure.microsoft.com/en-us/blog/author/weetok/" target="_blank">Wee Hyong Tok</a> データ科学者共同Office執筆しています。</em></p>


  <p>最近では、膨大な量のデータ、クラウド、アルゴリズムやハードウェアのイノベーションなどによって、実際の AI イノベーションが加速しています。 では、開発者はどのようにして、顧客を引き付け、楽しませ、運用を最適化し、従業員を支援し、製品を変革する AI アプリケーションを設計し始めるのでしょうか。</p>


  <p>アプリケーション <a href="https://azure.microsoft.com/en-us/services/cognitive-services/">Azure Cognitive Services</a> 、Web サイト、ボットにインテリジェントな機能を組み込む機能を利用できます。 これらの機能は、視覚、音声、知識、検索、言語に関して行われた何年もの研究を基に構築されています。 開発者は、さまざまなコグニティブ サービスを使用して、機械学習モデルを最初からトレーニングすることなく、AI 機能を簡単に追加できます。</p>


  <p>OReilly&rsquo; と Microsoft は、AI <a href="https://info.microsoft.com/ww-landing-ai-developers-bot-ebook.html">&rsquo;</a>アプリケーションの構築に関する開発者ガイドというタイトルの無料の電子書籍を提供しています。 この電子書籍では、Microsoft の Anand Raman と Wee Hyong Tok が、インテリジェントな AI アプリケーションを構築するために Azure AI を使用する簡単な概要を提供しています。 会議参加者が使用する <em>&ldquo;Conference Buddy&rdquo;</em> と呼ばれるボットの実用的な例を提供します。 この電子書籍では、使用事例、アーキテクチャ、およびボットを AI に取り込みながらボットを作成する方法について確認します。 このコードは、次のコードで<a href="https://github.com/Azure/ConferenceBuddy" target="_blank">GitHub</a>。 具体的には、この電子書籍は次の場合に役立ちます。</p>


  <ul>
   <li>アプリケーション プラットフォームで使用できるツール、インフラストラクチャ、およびサービスについて詳細にAzure AIします。</li>
   <li>概要、魅力的なエクスペリエンスをサポートするためにボットを強化するプラグ アンド プレイ インテリジェンスを備え、インテリジェント チャットボットの開発に取り組む必要があります。</li>
   <li>AI で使用できるリソースについて学習します。</li>
  </ul>


  <p><a href="https://info.microsoft.com/ww-landing-ai-developers-bot-ebook.html" target="_blank"><img alt="Developer ebook" border="0" height="480" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3d2728e8-c094-4410-9787-5cda699797a4.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="開発者向け電子ブック" width="325"></a></p>


  <h2>概要今日!</h2>


  <ul>
   <li><a href="https://info.microsoft.com/ww-landing-ai-developers-bot-ebook.html">AI アプリケーションの&rsquo;構築に関する開発者ガイドをダウンロードします</a>。</li>
   <li>詳細については<a href="https://azure.microsoft.com/en-us/overview/ai-platform/">、Azure AI。</a></li>
   <li><a href="https://azure.microsoft.com/en-us/try/cognitive-services/my-apis/">試Cognitive Services</a> API は無料です。</li>
   <li>Azure 無料 <a href="https://azure.microsoft.com/en-us/free/ai/">アカウントを作成します</a>。</li>
   <li><a href="https://myignite.techcommunity.microsoft.com/sessions?q=artificial%2520intelligence&amp;t=%257B%2522from%2522%253A%25222018-09-23T08%253A00%253A00-04%253A00%2522%252C%2522to%2522%253A%25222018-09-28T19%253A00%253A00-04%253A00%2522%257D">Ignite 2018 AI セッションを見る</a>。</li>
  </ul>
