### YamlMime:Yaml
ms.openlocfilehash: 704bdce5176dc0dc2552004962337ac127009fca
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910765"
Slug: how-to-optimize-your-azure-environment
Title: Azure 環境を最適化する方法
Summary: 適切なツールとアプローチがなければ、クラウドの最適化には時間と労力がかかることがあります。 これまでに進めていくベストプラクティスのリストが増えており、クラウドワークロードの進化に伴って絶えず流が発生しています。
Content: >-
  <p>適切なツールとアプローチがなければ、クラウドの最適化には時間と労力がかかることがあります。 これまでに進めていくベストプラクティスのリストが増えており &rsquo; 、クラウドワークロードの進化に伴って絶えず流が発生しています。 直面している課題や緊急事態を日常的に追加することで、 &rsquo; クラウドリソースが最適に実行されているかどうかを事前に確認することが困難である理由 &rsquo; を簡単に把握できます。</p>


  <p>Azure には、ワークロードを最適に実行し、投資を最大限に活用できるようにするためのさまざまな &rsquo; 方法が用意されています。</p>


  <h2>3種類の最適化: 組織、アーキテクチャ、戦術</h2>


  <p>これらの方法の1つとして、組織、アーキテクチャ、または戦術の高度なアドバイスと最適化が挙げられます。<br>

  戦術的またはリソースレベルでは、Azure リソースの高可用性、セキュリティ、パフォーマンス、およびコストを最適化するのに役立つ無料の Azure サービスである <a href="https://aka.ms/advisor-acom" target="_blank">Azure Advisor</a>があります。 Advisor は、リソースの使用状況と構成をスキャンし、100を超えるパーソナライズされた推奨事項を提供します。 各推奨事項には、クラウドリソースの最適化を迅速かつ簡単に修復するためのインラインアクションが含まれています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a3f087a2-f6c0-4a4e-b33d-35cfd5279f6d.png"><img alt="Software as a Service plan creation in Partner Center showing seat based billing." border="0" height="606" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d89d53e3-064b-44ea-bb61-5197e37b1994.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="パートナーセンターでのサービスプラン作成としてのソフトウェアで、座席ベースの課金が示されています。" width="1024"></a></p>


  <p>その一方で、Azure の専門家によって作成された無料ガイドのコレクションで <a href="https://docs.microsoft.com/en-us/azure/architecture/" target="_blank">Azure アーキテクチャセンター</a>あり、組織およびアーキテクチャのベストプラクティスを理解し、ワークロードを最適化するのに役立ちます。 このガイダンスは、クラウドの新しいワークロードを設計する場合や、既存のワークロードをオンプレミスからクラウドに移行する &rsquo; 場合に特に役立ちます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d1e61232-da2c-43fe-ba1a-2e2be585f494.png"><img alt="Azure Architechture Center main page." border="0" height="607" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/78aa57a7-d568-45a9-8a05-31dca3551b8b.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure アーキテクチャ Center のメインページ。" width="1024"></a></p>


  <p>Azure アーキテクチャセンターのガイドは、 <a href="https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/" target="_blank">azure の Microsoft Cloud 導入フレームワーク</a>の範囲を示しています。これは、クラウドの導入と戦略に対する組織 &rsquo; のアプローチを <a href="https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/" target="_blank">azure 参照アーキテクチャ</a>に提供するのに役立ちます。これは、AI、IoT、マイクロサービス、サーバーレス、SAP、web apps などの一般的なシナリオに推奨されるアーキテクチャとプラクティスを提供します。</p>


  <h2>小規模の開始、勢いの獲得</h2>


  <p>Azure 環境の最適化を開始するには、さまざまな方法があります。 クラウド導入戦略に合わせて組織として配置することができます。また、提供されている参照アーキテクチャに対してワークロードアーキテクチャを確認することも、Advisor を開いてベストプラクティス推奨事項があるリソースを確認することもできます。 これらはほんの一例にすぎません。最終的 &rsquo; には、お客様の組織だけが選択できます。</p>


  <p>組織が大規模な場合は、小規模に開始して勢いを上げることができます。 &rsquo;多くのお客様が、戦術またはリソースレベルでの最適化の開始を成功させ、ワークロードレベルまで最終的に作業してきました。最終的には、学習した &rsquo; 内容を統合し、ポリシーを実装することができます。</p>


  <h2>Azure Advisor の使用を開始する</h2>


  <p>Advisor にアクセスすると、 &rsquo; 環境を最適化するために実行できる多くの推奨されるアクションが見つかる可能性があります。 アドバイスはありますか? 気 &rsquo; にならないようにしてください。 始めましょう。 お客様と組織にとって最も意味のある営業案件について、推奨事項をスキャンします。 Vm のバックアップなどの高可用性に関する考慮事項は、特に開発/テストから運用に移行する場合の VM の作成での一般的な監視です。 それ以外の場合は、過小使用されている Vm を確認することでコストを削減できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/67294587-2ab5-480e-bd9f-68d551c9dc09.png"><img alt="Azure Advisor recommendation details screen." border="0" height="608" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4f753c06-3c79-4819-9704-47743b2c9430.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure Advisor 推奨事項の詳細画面。" width="1024"></a></p>


  <p>&rsquo;適切な推奨事項を見つけたら、こちらの<a href="https://www.youtube.com/watch?v=xO3V3FZWXwc" target="_blank">ビデオに示されているように修復</a>してください。 最適化は継続的なプロセスであり、実際には完了していませんが、実行するすべての手順は正しい方向の手順です。</p>


  <p><a href="https://aka.ms/azureadvisor" target="_blank">Azure portal の Advisor にアクセス</a> して、推奨事項の確認と修復を開始してください。 詳細なガイダンスについては、 <a href="https://aka.ms/azureadvisordocs" target="_blank">Azure Advisor のドキュメント</a>を参照してください。 <a href="https://aka.ms/advisorfeedback" target="_blank">こちらのフィードバックツールで</a>アイデアを提出していただき、Advisor にご提案をお寄せください。</p>
