### YamlMime:Yaml
ms.openlocfilehash: 9291a2996b73703898cc6b0d152fe60916bbfdc1
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890412"
Slug: how-to-configure-azure-sql-database-geo-dr-with-azure-key-vault
Title: Geo-DR をAzure SQL Database構成する方法Azure Key Vault
Summary: 高可用性を維持するために geo レプリケートされたデータベースに対して BYOK を使用して TDE を利用するには、シナリオを慎重に構成してテストする必要があります。 この投稿では、最も一般的な構成オプションについて説明します。
Content: >-
  <p>Azure SQL Databaseおよび Data Warehouseでは、データベース、ログ ファイル、バックアップなど、ディスクに書き込まれるすべてのデータに Transparent Data Encryption (TDE) を提供することで、保存時の暗号化が提供されます。 これにより、ハードウェアへの不正アクセスの場合にデータが保護されます。 TDE には、データの暗号化に使用されるデータベース暗号化キー (DEK) の暗号化に使用される TDE 保護機能が用意されています。 TDE と Bring Your Own Key (BYOK) オファリングは現在プレビュー中であり、お客様は TDE 保護機能を Azure Key Vault。</p>


  <p>高可用性を維持するために geo レプリケートされたデータベースに対して BYOK を使用して TDE を利用するには、シナリオを慎重に構成してテストする必要があります。 この投稿では、最も一般的な構成オプションについて説明します。</p>


  <p>アクティブ geo レプリケート インスタンスまたは SQL フェールオーバー グループで単一障害点を作成しないようにするには、冗長な Azure Key Vault を構成する必要があります。 geo レプリケートされたサーバーごとに個別のキー コンテナーが必要であり、同じ Azure リージョンにサーバーと併置する必要があります。 1 つのリージョンの停止によってプライマリ データベースにアクセスできなくなり、フェールオーバーがトリガーされた場合は、セカンダリ データベースがセカンダリ キー コンテナーを使用して引き継ぐことができます。</p>


  <p>geo レプリケートされた Azure SQL データベースの場合、Azure Key Vault の次の構成が必要です。</p>


  <ul>
   <li>リージョン内にキー コンテナーがあるプライマリ データベースが 1 つと、リージョン内にキー コンテナーがあるセカンダリ データベースが 1 つ。</li>
   <li>少なくとも 1 つのセカンダリが必要です。最大 4 つのセカンダリがサポートされています。</li>
   <li>セカンダリのセカンダリ (チェーン)&nbsp; はサポートされていません。</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/21d2541b-d8c9-40b6-8f39-02c88bdb368c.png"><img alt="Geo-DR config" border="0" height="454" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6f81f172-b829-4ad1-919e-271ccac11284.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="geo-DR 構成" width="826"></a></p>


  <p>新しい Geo-DR 構成から始める場合は、データベース間の geo リンクの確立に進む前に、両方のキー コンテナーに同じ TDE 保護機能が存在することが重要です。</p>


  <p>既存の Geo-DR デプロイを操作する場合は、最初にセカンダリ サーバーにキー コンテナーを割り当てる必要があります。 セカンダリ サーバーが構成された後Azure Key Vaultプライマリ サーバーに対してこの手順を完了し、その TDE 保護機能を更新できます。 既存の Geo-DR リンクは引き続き機能します。この時点で、レプリケートされたデータベースで使用される TDE 保護機能は両方のサーバーで使用できます。</p>


  <p><a href="https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption-byok-azure-sql#how-to-configure-geo-dr-with-azure-key-vault" target="_blank">詳細な詳細な構成ガイダンスについては、ドキュメントを参照してください。</a></p>


  <h2>まとめ</h2>


  <p>SQL Database Geo-DR シナリオで、Azure Key Vault のユーザー管理のキーを使用して TDE を有効にする前に、SQL Database の geo レプリケーションに使用されるリージョンに、同じ内容の 2 つの Azure Key Vault を作成して管理することが重要です。 &ldquo;同一の&rdquo; 内容は、特に、両方のサーバーがすべてのデータベースで使用される TDE 保護機能にアクセスするために、両方のキー コンテナーに同じ TDE 保護機能のコピーを含めなければならないことを意味します。 今後は、両方のキー コンテナーの同期を維持する必要があります。&nbsp; つまり、両方のキー コンテナーには、キーのローテーション後に TDE 保護機能の同じコピーを含め、ログ ファイルまたはバックアップに使用される古いバージョンのキーを保持する必要があります。 さらに、TDE 保護機能は同じキー プロパティを保持する必要があります。また、キー コンテナーは、キー コンテナーに対して同じアクセス許可を保持SQL。 ベスト プラクティスは、シナリオが引き続き機能するために、定期的にフェールオーバーをテストしてトリガーする方法です。 フェールオーバーを管理およびトリガーする方法の詳細については、フェールオーバー グループのドキュメント <a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-geo-replication-overview#programmatically-managing-failover-groups-and-active-geo-replication" target="_blank">ページを参照してください</a>。</p>
