### YamlMime:Yaml
ms.openlocfilehash: 5bfc1b328e58559fd0581840411177cb3c85dd54
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139896741"
Slug: how-to-using-visual-studio-to-build-applications-that-integrate-with-hdinsighthadoop
Title: "\"方法\": HDInsight/Hadoop とVisual Studioするアプリケーションをビルドする方法"
Summary: Visual Studio の開発者がカスタム アプリケーションの "ビッグ データ" を使用して生産性を向上するために、Azure SDK の最近の更新プログラムに Visual Studio の HDInsight 用のより深いツール エクスペリエンスを追加しました。
Content: >-
  Visual Studio の開発者がカスタム アプリケーションで "ビッグ データ" を使用して生産性を向上するために、<a href="https://azure.microsoft.com/blog/2014/11/12/announcing-azure-sdk-2-5-for-net-and-visual-studio-2015-preview/">Azure SDK</a> の最新の更新プログラムに Visual Studio の HDInsight 用のより深いツール エクスペリエンスを追加しました。 この拡張機能を使用Visual Studio、開発者は、使い慣れた強力なツールで Hadoop クラスター、テーブル、および関連するストレージを視覚化できます。 開発者は、Visual Studio 内からクラスターに対して HDInsight のアドホック Hive クエリを直接作成して送信したり、他の Visual Studio プロジェクトと同様に管理される Hive アプリケーションを構築したりできます。


  <a href="https://www.microsoft.com/web/handlers/webpi.ashx/getinstaller/VWDOrVs2013AzurePack.appids">VS 2013VS</a>| <a href="https://www.microsoft.com/web/handlers/webpi.ashx/getinstaller/VWDOrVs11AzurePack.appids">2012VS</a>| <a href="https://www.microsoft.com/web/handlers/webpi.ashx/getinstaller/VWDOrVs2015AzurePack.appids">2015 Preview 向け Azure SDK を今すぐダウンロードします</a>。


  HDInsight オブジェクトを "サーバー エクスプローラー" に統合すると、ビッグ データ資産が Azure の他のクラウド サービスと同じページに表示されます。 これにより、テーブルの最初の 100 行のクエリまで、クラスター、Hive テーブル、およびそれらのスキーマを迅速かつ簡単に探索できます。これにより、アプリケーションで使用しているデータの形状をすばやく理解Visual Studio。


  また、Hive クエリを作成してジョブとして送信するツールも用意されています。 Hadoop クラスターに対してコンテキスト メニューを使用して、Hive クエリ スクリプトの記述をすぐに開始します。 次の例では、地理的情報を含む Hive テーブルに対する単純なクエリを作成して、すべての国の数を検索し、国別に並べ替えます。 ジョブ ブラウザー ツールを使用すると、ジョブの送信と状態を視覚化できます。任意のジョブをダブルクリックして、[Hive ジョブの概要] ウィンドウで概要と詳細を取得します。


  任意の Azure BLOB コンテナーに移動し、それを開いてそこに含まれているファイルを操作することもできます。 バッキング ストアは、Azure ダッシュボードでのクラスターの作成中に Hadoop クラスターに関連付けされます。 Hadoop クラスターの管理は、同じ Azure ダッシュボードで引き続き実行されます。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/11/27/clip_image002.jpg"><img style="padding-top: 0px; padding-left: 0px; padding-right: 0px; border: 0px;" title="clip_image002" alt="clip_image002" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/clip_image002_thumb.jpg" width="539" height="325" border="0" /></a>


  より複雑なスクリプトの開発とライフサイクル管理を行う場合は、Hive プロジェクトを Visual Studio。 新しいプロジェクト ダイアログ (下記参照) に、新しい HDInsight テンプレート カテゴリが表示されます。 便利な開始点は、Hive サンプル プロジェクトの種類です。 このプロジェクトには、Web サーバー ログを処理する場合の、より複雑な Hive クエリとサンプル データが事前に設定されています。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/11/27/clip_image004.png"><img style="padding-top: 0px; padding-left: 0px; padding-right: 0px; border: 0px;" title="clip_image004" alt="clip_image004" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/clip_image004_thumb.png" width="538" height="374" border="0" /></a>


  開始するには、次のリソースを利用してください。

  <ul>
   <li><a href="https://channel9.msdn.com/Events/Visual-Studio/Connect-event-2014/410">Channel 9 のビデオ デモ</a></li>
   <li><a href="https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-visual-studio-tools-get-started/">はじめに ドキュメント</a></li>
  </ul>
