### YamlMime:Yaml
ms.openlocfilehash: 530cb689e574495081485556e77c7802cd7e0206
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890771"
Slug: hybrid-management-in-azure-automation
Title: Azure Automation でのハイブリッド管理
Summary: 'この投稿では、新しい機能の基本といくつかの重要な機能Hybrid Runbook Workerします。 '
Content: >-
  最新リリース <a href="https://azure.microsoft.com/en-us/services/automation/">の Azure Automation Hybrid</a> Runbook Worker を使用してオンプレミス システムに接続する機能が導入されました。 新しい Hybrid Runbook Worker機能を使用すると、送信ポートを開く必要なく、クラウドとデータセンターにまたがるリソースを管理できます。


  この投稿では、新しい機能の基本といくつかの重要な機能Hybrid Runbook Workerします。 最初に、データの概要をAzure Automation

  <h2>Azure Automation とは</h2>

  まだお使い慣れしていない場合、Azure Automation は、リソースを任意の場所 (パブリック、ホスト、またはプライベート クラウド) で管理するための IT プロセス自動化サービスです。 この機能を使用すると、Azure 環境でリソースの作成、監視、配置、およびメンテナンスを自動化できます。 Dev/Ops では、Automation を使用して Runbook を構築、実行、管理し、IT プロセスを統合、調整、自動化できます。 Automation Runbook は、Windows PowerShell ワークフロー エンジンで実行されます


  詳細については、「」を参照してください <a href="https://azure.microsoft.com/en-us/services/automation/">https://azure.microsoft.com/en-us/services/automation/</a>。


  次に、 <b>Hybrid Runbook Worker</b> 機能について説明し、基本的な質問から始め、ハイブリッド ワーカーとは何か、必要な理由、それを使用する方法について説明します。

  <h2>データ のHybrid Runbook Worker?</h2>

  Hybrid Runbook WorkerのAzure Automation<s></s>機能を使用すると、ローカル リソースを管理するために、データセンターにあるマシンで Runbook を実行できます。 Runbook は Azure Automation に格納および管理され、実行されている 1 つ以上のオンプレミス マシンに配信されます。

  <h2>ハイブリッドオートメーションの概要</h2>

  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/23/Hybrid-Automation-Overview.png"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-width: 0px;" title="ハイブリッドオートメーションの概要" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Hybrid-Automation-Overview_thumb.png" alt="Hybrid Automation Overview" width="1318" height="732" border="0" /></a>


  ハイブリッド機能が使用可能になるまで、Azure Automationは主にクラウド内のリソースを管理するために使用されています。これらの Runbook はクラウドで実行されます。 Hybrid Runbook Worker を使用すると、ローカル データセンターにある Hybrid Runbook Worker で Runbook を実行することで、オンプレミスのリソースを管理できます。


  Runbook と参照先の資産はすべて Azure Automation に格納され、実行時に実行される 1 つ以上のオンプレミス マシン (Hybrid Runbook Worker として指定) に配信されます。 Runbook は、管理しているリソースに関係なく、1 つの場所に関係なく、すべてのジョブ出力を監視できるよう、トラブルシューティングのために詳細なジョブ情報を Azure Automation に送信します。 Hybrid <a href="file:///C:/Users/v-katisc/Desktop/#creating-runbooks-for-hybrid-runbook-wor">Runbook worker として</a> 指定されたマシンでアセットとモジュールを使用する方法の詳細については、以下を参照してください。 ファイアウォール規則を開く必要はありません。この指定されたサービスがインターネットHybrid Runbook Worker持っている必要があります

  <h2>Hybrid Runbook Worker を使用する理由</h2>

  <ul>
   <li>ハイブリッド worker を使用すると、リソースを管理するための単一のソリューションとして Azure Automation を使用できます。リソースは、Azure、AWS、その他のサービス プロバイダーなどのパブリック クラウド内にあるか、Microsoft や他の Microsoft 以外のスタック (VMWare や OpenStack など) などのオンプレミス ソリューションに含まれます。</li>
   <li>ハイブリッド Azure Automationを使用すると、Service Management Automation、Orchestrator などのオンプレミスのオートメーション製品をデプロイ、保守、アップグレードする必要がなされます。</li>
  </ul>

  <h2>操作方法 Hybrid Runbook Worker を使用しますか?</h2>

  <h3>手順 1: オンプレミスのマシンを識別する</h3>

  オンプレミス のマシンを選択するときに考慮する必要がある推奨事項を次に示します。

  <ol>
   <li>Hybrid Runbook Worker は、Windows Server 2012上で実行されます。</li>
   <li>Service Management Automation (SMA) Runbook worker または System Center Orchestrator (SCO) Runbook Server マシンと同様に、環境内の高可用性マシンを Hybrid Runbook Worker として指定することを推奨します。 ハイブリッド ワーカーは、SMA または SCO 環境と共に存在できます。</li>
   <li>Runbook が完了すると、ジョブ データ全体が Azure Automation に返されるので、 <a href="https://azure.microsoft.com/en-us/regions/#services">Azure Automation</a> リージョンに近い場所にあるマシンを使用Azure Automation。</li>
  </ol>

  <h3>手順 2: アプリケーションのインストールと構成Hybrid Runbook Worker</h3>

  <a href="https://www.microsoft.com/en-us/server-cloud/operations-management-suite/overview.aspx">Operations Management Suite</a> (OMS) Microsoft Management Agent (MMA) チャネルとインテリジェンス パック/ソリューション チャネルを使用して、Hybrid Runbook Worker として指定したオンプレミスのマシンに Hybrid Runbook Worker ビットを配信します。


  アプリケーションのインストールと構成の詳細については、Hybrid Runbook Workerを参照してください。 <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-hybrid-runbook-worker/">https://azure.microsoft.com/en-us/documentation/articles/automation-hybrid-runbook-worker/</a>

  <h3>手順 3: アプリケーションで Runbook を開始Hybrid Runbook Worker</h3>

  <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-starting-a-runbook">Runbook の開始方法Azure Automation Runbook</a> を開始するさまざまな方法について説明します。 Hybrid Runbook Workerグループの名前を指定できる Run <strong>On</strong> オプションをHybrid Runbook Workerします。 グループが指定されている場合は、Runbook が取得され、そのグループ内のいずれかの worker によって実行されます。 このオプションを指定しない場合、Runbook は通常通り Azure クラウドで実行されます。


  Azure プレビュー ポータルで Runbook を開始すると、<strong>Azure</strong> またはハイブリッド Worker を選択できる [Run <strong>on</strong>] オプションが<strong>表示されます</strong>。 [Hybrid <strong>Worker] を選択</strong>した場合は、ドロップダウンからHybrid Runbook Workerグループを選択できます。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/23/Runbook-Migration-Demo1.png"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-width: 0px;" title="Runbook Migration Demo1" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Runbook-Migration-Demo1_thumb.png" alt="Runbook Migration Demo1" width="1097" height="420" border="0" /></a>

  <h2>Hybrid Runbook Worker グループ</h2>

  各Hybrid Runbook Workerは、エージェントをインストールするときにHybrid Runbook Workerグループのメンバーです。 グループには 1 つの Worker を含めできますが、高可用性を実現するには、1 つのグループに複数の Worker をインストールできます。


  Hybrid Runbook Worker で Runbook を開始するときに、実行するグループを指定します。ジョブは、グループ内の任意のワーカーによって実行できます。 現在、特定のワーカーを指定することはできません。

  <h2>Hybrid Runbook Worker の Runbook の作成</h2>

  Runbook で実行される Runbook と、Azure Automationで実行される Runbook に違いHybrid Runbook Worker。 ただし、ハイブリッド用に作成された Runbook は、Hybrid Runbook Worker で使用される Runbook は通常、データ センター内のローカル リソースを管理し、Azure Automation の Runbook は通常、Azure または他のクラウド内のリソースを管理するので、他の Runbook とは異なる可能性があります。 たとえば、Hybrid Runbook Worker を使用して Hyper-V 上の VM を管理したり、Orchestrator から移行された Runbook System Centerできます。 もう 1 つの良い使い方は、アプリケーションにインストールできないモジュールAzure Automation。 これらのモジュールはハイブリッド worker にインストールし、Runbook で使用できます。 その良い例は、VMware PowerCLI コマンドレットを使用して VMware を管理できる場合です。


  Orchestrator Runbook を Azure Automationする方法の詳細については、「」を参照してください <a href="https://www.microsoft.com/en-us/download/details.aspx?id=47323">https://www.microsoft.com/en-us/download/details.aspx?id=47323</a>。

  <h2>デバッグとトラブルシューティング:</h2>

  Hybrid worker で Runbook ジョブが完了すると、詳細な状態が Azure Automation に返され、Azure で実行されるジョブのトラブルシューティングと同じ方法でジョブを表示およびトラブルシューティングできます。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/23/RBMigration.png"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-width: 0px;" title="RBMigration" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/RBMigration_thumb.png" alt="RBMigration" width="1471" height="757" border="0" /></a>

  <h2>Azure Automation からのアセットのAzure Automation</h2>

  変数、資格情報、接続、証明書などの Automation アセットは、ハイブリッド ワーカーで実行される Runbook で使用できます。 アセットは Azure Automationに格納され、それらを参照する Runbook で使用するためにワーカーに自動的に配信されます。


  現時点では、ハイブリッド worker で Runbook をスケジュールすることはできません。 別の方法として、Azure クラウドで実行され、Start-AzureAutomationRunbook コマンドレットを使用して worker で Runbook を開始する別の Runbook をスケジュールします。

  <h2>PowerShell モジュール</h2>

  この機能の主なHybrid Runbook Workerはローカル リソースの管理のため、これらのリソースをサポートするモジュールをインストールする必要があります。 これらのモジュールはハイブリッド ワーカーに自動的にデプロイされないので、現在は各ワーカーに手動でインストールする必要があります。 ただし、近い将来、これらのモジュールをワーカーに自動的にデプロイする作業を行っています。

  <h2>Runbook のアクセス許可</h2>

  Runbook は、Hybrid Runbook Worker のローカル システム アカウントのコンテキストで実行されます。そのため、アクセスするリソースに対して独自の認証を提供する必要があります。 Azure の外部のリソースにアクセスする <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-hybrid-runbook-worker/automation-configuring.md/#configuring-authentication-to-azure-resources">Runbook が Azure</a> リソースに対して認証するために通常使用されるのと同じ方法を使用することはできません。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/23/Services.png"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-width: 0px;" title="サービス" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Services_thumb.png" alt="Services" width="1118" height="490" border="0" /></a>


  さまざまなリソース<a href="https://msdn.microsoft.com/library/dn940015.aspx">に対</a><a href="https://msdn.microsoft.com/library/dn940013.aspx">して認証</a>するために資格情報を指定できるコマンドレットを使用して、Runbook で資格情報と証明書資産を使用できます。 次の例は、コンピューターを再起動する Runbook の一部を示しています。 資格情報資産から資格情報を取得し、変数資産からはコンピューター名を取得して、Restart-Computer コマンドレットでこれらの値を使用します。

  <pre class="prettyprint">$Cred = Get-AutomationCredential "MyCredential"

  $Computer = Get-AutomationVariable "ComputerName"


  Restart-Computer -ComputerName $Computer -Credential $Cred

  </pre>

  <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-hybrid-runbook-worker/automation-runbook-concepts.md/#inline-script">InlineScript</a> アクティビティを使用することもできます。このアクティビティを使用すると、<a href="https://technet.microsoft.com/library/jj129719.aspx">PSCredential</a> 共通パラメーターで指定された資格情報を使用して、別のコンピューターでコードブロックを実行できます。

  <h2>まとめ</h2>

  Hybrid Runbook Worker を使用した Azure Automation のハイブリッド接続は、Azure Automation を任意の場所 (データセンター、プライベート、パブリック、ホスト型クラウド) で管理するためのプラットフォームを実現する強力な機能です。


  最近リリースされたその他の新機能を確認してください。

  <ul>
   <li>グラフィカル作成: <a href="https://azure.microsoft.com/blog/2015/05/07/azure-automation-new-graphical-and-textual-authoring-features/">https://azure.microsoft.com/blog/2015/05/07/azure-automation-new-graphical-and-textual-authoring-features/</a></li>
   <li>Web フック: <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-webhooks/">https://azure.microsoft.com/en-us/documentation/articles/automation-webhooks/</a></li>
   <li>Azure Automation DSC: <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-dsc-overview/">https://azure.microsoft.com/en-us/documentation/articles/automation-dsc-overview/</a></li>
  </ul>

  今後の投稿では、新しい機能とシナリオの例Hybrid Runbook Worker説明します。 それまでは、幸せな自動化です。


  次のAzure Automation? このサービスについては、こちらを <a href="https://aka.ms/Q2p1ap">参照し</a>、Twitter <a href="https://twitter.com/AzureAutomation">Azure Automation</a> に従ってください。
