### YamlMime:Yaml
ms.openlocfilehash: e382fadbf30ca78b9f85255edc6dd7aeea8288d7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891620"
Slug: hybrid-application-innovation-with-azure-and-azure-stack
Title: Azure Stack TP3 は、ハイブリッドアプリケーションイノベーションを実現し、従量課金制の価格モデルを導入しています。
Summary: 速度と実験の精神で革新的なアプリケーションを構築することは、クラウド革命の中核です。 世界中の企業がデジタル変革を受け入れようとしています。これは、アプリが delighting の顧客のためにエンジンになる方法と、新しい基幹業務を促進することです。 私たちは、Azure の拡張機能である Azure Stack での作業に加えられた進行状況を共有し、クラウドコンピューティングの機敏性と迅速なイノベーションをオンプレミス環境にもたらしています。
Content: >-
  <p>クラウドテクノロジで革新的なアプリケーションを構築することは、組織が成長を促進し、差別化されたカスタマーエクスペリエンスを作成するうえで非常に重要です。 従量課金制の料金でクラウドテクノロジを利用するアプリケーションは、標準になりました。 私たちの目標は、ハイブリッドクラウド環境を選択する組織が、ビジネス目標とアプリケーション設計に合わせて同じ柔軟性とイノベーション機能を持つことを保証することです。 このため、Azure Stack と現在のオンプレミスで Azure テクノロジを拡張するのは、Azure Stack に関していくつかの更新が発表されているためです。</p>


  <ul>
      <li><strong>ダウンロード可能な TP3:</strong> <a href="https://azure.microsoft.com/en-us/overview/azure-stack/">Technical PREVIEW 3 (TP3) は現在ダウンロードでき</a> ます。また、最新のアプリケーション機能を利用できる新機能が用意されています。Azure に接続していない場所で実行しています。インフラストラクチャとセキュリティの強化についても同様です。</li>
      <li><strong>パッケージ化と価格モデル: </strong>Azure Stack は、従量課金制の料金でクラウドの経済的なモデルをオンプレミスで利用できます。</li>
      <li><strong>ロードマップの更新: </strong>TP3 のすぐ後に <a href="https://azure.microsoft.com/en-us/services/functions/??WT.srch=1&amp;WT.mc_id=AID559320__SEM_T2EIoLH6&amp;">Azure Functions</a> 、が TP3 で実行できるようになります。その後、 <a href="https://github.com/Azure/azure-quickstart-templates/tree/master/ethereum-consortium-blockchain-network">ブロックチェーン</a>、 <a href="https://github.com/Azure/azure-quickstart-templates/tree/master/bosh-setup">Cloud Foundry</a>、およびお持ちの <a href="https://github.com/Azure/AzureStack-QuickStart-Templates/blob/master/mesos-windows-jumpbox/README.md">os</a> テンプレートが表示されます。 継続的なイノベーションは、一般提供が開始されるまで Azure Stack に配信されます。 TP3 は、Azure Stack 統合システムを CY17 での注文に使用できるようになる前に、計画された最終的な主要 Technical Preview です。</li>
  </ul>


  <h2>オンプレミスの Azure の拡張</h2>


  <p>Azure Stack では、クラウド環境とオンプレミス環境で新しいアプリを構築したり、既存のアプリを renovate したりする組織で、3つの一意のハイブリッドクラウドシナリオを実現できます。</p>


  <ul>
      <li>一貫性のある<strong>ハイブリッドアプリケーション開発:</strong>人、プロセス、アプリケーションに投資している組織は、Azure と Azure Stack 間で転送できることを把握できます。 スキルを開発しようとしているユーザーは、Azure を使用している組織にこれらのスキルを講じることができます。 Azure と Azure Stack の間の一貫性を確保することで、組織は、1日に生産性を向上させることができ、1つのプロジェクトから別のプロジェクトに簡単に移行できる、世界中の企業のプールからを作成できます。 &nbsp;Azure のスキルを持つ個人は、プロジェクト、チーム、DevOps プロセスまたは組織を簡単に移動できます。 api、ポータル、PowerShell コマンドレット、Visual Studio エクスペリエンス<a href="https://aka.ms/consistentappdev">はすべて同じ</a>です。</li>
      <li><strong>オンプレミスで使用可能な Azure サービス:</strong> インフラストラクチャサービスとプラットフォームサービスは、次世代のアプリケーションイノベーションに燃料を供給します。 <a href="https://aka.ms/servicesonprem">Azure IaaS および PaaS サービスをオンプレミスで</a>提供することにより、組織は、ビジネス要件と技術的な要件に基づいて、ハイブリッドクラウドコンピューティングを導入することができます。 パブリック、サービスプロバイダー、オンプレミスのデプロイモデルの適切な組み合わせを柔軟に選択できます。 アプリを別の場所に配置する必要があると判断した場合は、変更せずに簡単に移動できます。</li>
      <li><strong>優れた運用のために構築</strong> されたシステム:組織がビジネスを推進する作業に集中できるように、Azure Stack は、予測可能で非破壊的な方法で <a href="https://aka.ms/purposebuiltsystems">Azure イノベーションを継続的に組み込む</a> ように設計された統合システムを通じて提供されます。</li>
  </ul>


  <h2>Azure と Azure Stack のハイブリッドユースケース</h2>


  <p>クラウド戦略についてお客様に説明すると、ハイブリッドは安定した状態の運用モデルであり、いくつかの主要なシナリオで Azure Stack を使用してクラウド戦略を強化することを検討しています。</p>


  <ol>
      <li><strong>エッジおよび切断</strong> されたソリューション:両方の共通アプリケーションロジックを使用して、Azure Stack でローカルにデータを処理し、さらに分析するために Azure で集計することにより、待機時間と接続性の要件に対処します。&nbsp;</li>
      <li><strong>クラウドとオンプレミスでの最新のアプリケーション:</strong>オンプレミスとクラウドで一貫性のある DevOps プロセスを使用しながら、Azure web &amp; mobile サービス、コンテナー、サーバーレス、およびマイクロサービスアーキテクチャを適用して、Azure Stack でレガシアプリケーションを更新および拡張します。</li>
      <li><strong>すべての規則に適合するクラウドアプリケーション:</strong> Azure でアプリケーションを開発してデプロイします。オンプレミスでデプロイできる柔軟性は、規制やポリシーの要件を満たすために、コードを変更する必要はありませんが、Azure Stack を備えています。</li>
  </ol>


  <p>工場フロアの自動化、リモートでの使用は、巡航船や地雷のように求められます。また、政府システムなどの分離の要件によって、最新の設計を採用し、クラウドで開発し、その場所にデプロイすることができます。&nbsp;</p>


  <h2>Azure Stack TP3 の新機能 &rsquo;</h2>


  <p>Azure Stack TP3 では、TP2 による多くのバグ修正、更新、展開の信頼性 &amp; の向上により、お客様と協力して製品を改善しまし &rsquo; た。 Azure Stack TP3 のお客様は次のことができます。</p>


  <ul>
      <li>切断されたシナリオ用の ADFS を使用したデプロイ</li>
      <li>Scale out ワークロードに Azure Virtual Machine Scale Sets の使用を開始する</li>
      <li>Azure Stack で利用できるように、Azure Marketplace のコンテンツをシンジケートします</li>
      <li>Azure D シリーズの VM サイズを使用する</li>
      <li>Azure と一貫性のある一時ディスクでテンプレートをデプロイして作成する</li>
      <li>分離された管理者ポータルの強化されたセキュリティを安心して活用</li>
      <li>IaaS と PaaS の機能強化を活用する</li>
      <li>強化されたアラートなどの強化されたインフラストラクチャ管理機能を使用する</li>
  </ul>


  <h2>ロードマップの更新</h2>


  <p>継続的なイノベーションモデルの一部として、TP3 の直後に、VM 拡張機能の配信とマルチテナントの Azure Functions を追加する予定です。 この後には、ブロックチェーン、Cloud Foundry、および他の Os テンプレートなど、新しいワークロードが続きます。 &nbsp; TP3 は、CY17 の GA まで引き続き更新されます。</p>


  <p>CY17 では、概念実証 (POC) デプロイは、Microsoft Azure Stack Development Kit に名前が変更されます。 この単一サーバーの開発/テストツールを使用すると、ハイブリッドアプリケーションをプロトタイプおよび検証することができます。 これは、Azure の新機能を顧客に迅速に導入するために使用される継続的なイノベーションモデルの重要な部分です。 Azure Stack。 これにより、新しい更新プログラムを顧客に事前に配布する方法が提供されるため、ユーザーは実験、学習、フィードバックを行うことができます。&nbsp;&nbsp;</p>


  <p>TP3 は、GA 前に予定されている最終的な主要 Technical Preview です。 &nbsp; Azure Stack Development Kit は GA としてリリースされますが、同時に、複数のサーバー Azure Stack 統合システム (CY17) を提供するために必要な共同エンジニアリング作業の最終段階を完了できるように、ハードウェアパートナーにソフトウェアをリリースします。</p>


  <p>GA 後、頻繁に更新されるように、継続的に追加の機能を提供します。 GA 後の更新の最初のラウンドは、1) アプリケーションの最新化のシナリオと 2) 強化されたシステム管理とスケールの2つの領域に焦点を合わせています。 これらの更新は、アプリケーションの開発時に、お客様が選択した IaaS および PaaS テクノロジを継続的に拡張し、アプリケーションのポートフォリオ拡大に対応するために Azure Stack のフットプリントを向上させます。</p>


  <h2>従量課金制の価格でクラウドの経済性をオンプレミスに拡張</h2>


  <p>Azure Stack は、従量課金制の料金で、 <a href="https://aka.ms/maspayasyougo">オンプレミスのクラウドの経済モデル</a>を実現します。 Azure と同様に、Azure Stack で Azure サービスを使用するための先行ライセンス料金はありません。お客様は、本サービスを使用した場合にのみお支払いいただけます。 サービスは、Azure と同じように、同じ請求書とサブスクリプションを使用してトランザクション処理されます。 通常、サービスは Azure と同じ単位で課金されますが、お客様が独自のハードウェアと設備を運用するため、料金は低くなります。 顧客が使用状況測定情報を Azure に送信できないシナリオでは、システムのコア数に基づいて固定価格 &ldquo; の容量モデル &rdquo; も提供します。</p>


  <p>お客様は、ハードウェアパートナー、Dell EMC、HPE、Lenovo および (今年の後半) から Cisco のハードウェアを Azure Stack 獲得します。 お客様のハードウェアパートナーと協力して、統合システムを使用しているハードウェアに対して、従量課金制などの柔軟な購入オプションを提供します。</p>


  <p>お客様は、Microsoft とハードウェアパートナーのアカウント担当者に連絡して、詳細な価格情報を確認することができます。</p>


  <h2>最後の考えと次の手順</h2>


  <p>世界中のすべての業界のすべての企業が、デジタルテクノロジを使用している組織からデジタル組織に変革しています。 お客様に継続的に進化する製品を作成することにより、組織の成長を支援することを専門としています。</p>


  <p>Azure と Azure Stack 統合システムにより、企業は、自社のアプリケーションポートフォリオをビジネスにとっての戦略的な差別化要因として活用することによって、エネルギーと人材の投資に注力することができます。 この方法では、お客様がビジネスニーズに最も適合するアプリケーションを展開し、運用することができます。 セルフサービスプロビジョニングとクラウドサービスを使用して開発チームを強化し、ビジネスポリシーと要件を満たす DevOps ワークフローを確立することで、はるかに大きな価値を提供できます。</p>


  <p><a href="https://azure.microsoft.com/en-us/overview/azure-stack/">Azure Stack とダウンロード Azure Stack TP3 の詳細については、こちらを参照してください。</a></p>


  <p>Jeffrey Snover<br>

  Azure インフラストラクチャと管理の技術関連<br>

  Twitter でフォローする <a href="https://twitter.com/jsnover">@jsnover</a></p>
