### YamlMime:Yaml
ms.openlocfilehash: abe21f42251147b599279a92158d17dfb50f5c4b
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893001"
Slug: imanis-data-cloud-migration-backup-for-your-big-data-applications-on-azure-hdinsight
Title: Imanis Data-クラウド移行, Azure HDInsight でのビッグデータアプリケーションのバックアップ
Summary: Azure HDInsight での Imanis データの組み合わせと Azure Blob Storage と Data Lake Store との緊密な統合により、お客様はクラウドへの移行を迅速化し、重要なデータ資産をアプリケーションや人的エラーから保護することができます。
Content: >-
  <p>Azure での Imanis データの可用性についてお知らせします。</p>


  <p><a href="https://azure.microsoft.com/en-us/services/hdinsight/" target="_blank">Azure HDInsight</a> は、完全に管理された業界トップレベルのクラウド Apache Hadoop &amp; Spark オファリングであり、お客様は業界最高レベルの SLA で信頼性の高いオープンソース分析を実行できます。 <a href="https://www.imanisdata.com" target="_blank">Imanis data</a> には、ユーザーがデータを移行し、ビッグデータアプリケーションのバックアップと復元の機能を追加できるようにするデータ管理ソフトウェアが用意されています。</p>


  <p>この Imanis データを HDInsight 上で提供し、Azure Blob Storage と Data Lake Store と統合することにより、顧客はクラウドへの移行を迅速化し、重要なデータ資産をアプリケーションや人的エラーから保護できます。</p>


  <h2>Microsoft Azure HDInsight –信頼性の高いオープンソース分析をエンタープライズレベルで、スケール</h2>


  <p>HDInsight は、Spark、Hive、Interactive Hive、MapReduce、HBase、嵐、kafka、R Server 向けに最適化されたオープンソース分析クラスターを提供する、完全に管理された唯一のクラウド Hadoop サービスであり、99.9% の SLA によって支えられています。 これらのビッグデータテクノロジはそれぞれ、エンタープライズレベルのセキュリティと監視機能を備えた管理対象クラスターとして簡単に展開できます。</p>


  <h2>Imanis Data –ビッグデータアプリケーションのクラウド移行、バックアップと復元</h2>


  <p>クラウドコンピューティング全般の爆発的な成長とビッグデータアプリケーションの増加により、オンプレミスで実行されているワークロードを Azure で大規模に実行できることを保証する必要がありました。また、基になる HDInsight データ資産を災害、人的エラー、アプリケーションの破損から保護することもできます。</p>


  <p>そのためには、Azure でソフトウェアソリューションを立ち上げたばかりの Imanis Data (旧称 Talena, Inc.) を強調しておきましょう。 Imanis Data には、HDInsight のお客様に役立つさまざまなユースケースを含むデータ管理ソフトウェアが用意されています。次に例を示します。</p>


  <ul>
   <li>オンプレミスまたはその他のクラウドのビッグデータワークロードを Azure HDInsight に移行する: Imanis Data は、使用している Hadoop ディストリビューションに関係なく、ビッグデータワークロードを HDInsight に移行するための優れた方法を企業に提供します。 これには、データとアプリケーション固有のメタデータも含まれます。</li>
   <li>クラウドのディザスターリカバリー: Imanis データは、Hive、HBase、Spark などのオープンソースワークロードのデータとメタデータをセカンダリリージョンに移動するための基礎として簡単に使用できます。これにより、リージョン間の DR が可能になります。</li>
   <li>スケーラブルなバックアップと迅速な回復: Imanis Data を使用すると、Hive、HBase、Spark などのオープンソースワークロードで使用されるペタバイト規模のデータを、非常に迅速にバックアップおよび特定の時点で復旧できます。</li>
   <li>テストデータ管理: 企業がデータをクラウドに移行するときに、PII を保護することが重要です。 Imanis Data のネイティブデータマスク機能により、企業は、クラウド内の QA、Data Analytics またはその他のクラスターにデータを移行するときに、機密データを保護することができます。</li>
   <li>コンプライアンスと規制の要件に対応したアーカイブ。</li>
   <li>Microsoft Azure Blob Storage と Azure Data Lake Store とのネイティブ統合。<br>&nbsp; </li>
  </ul>


  <p>これらのさまざまなユースケースをサポートするために、Imanis データソフトウェアアーキテクチャには次のものが組み込まれています。</p>


  <ul>
   <li>ペタバイト規模のワークロードをサポートできる、拡張性の高い分散型ファイルシステム。</li>
   <li>直感的なメタデータカタログを使用した迅速な回復機能、さまざまなデータベーストポロジに復旧する柔軟性、並列データ転送のサポート。</li>
   <li>インクリメンタルバックアップ、グローバルなブロックレベルの重複除去、および圧縮に焦点を当てた組み込みのストレージ最適化エンジン。</li>
   <li>エージェントレスのさまざまなデータベースとの統合。</li>
   <li>複数の Azure リージョン間でのデータミラーリングとレプリケーションのサポート。</li>
  </ul>


  <p>Azure での Imanis データオファリングの詳細については、こちらを参照してください。</p>


  <ul>

  </ul>


  <h2>Azure HDInsight での Imanis データの概要</h2>


  <p><a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/talena-inc.talena-solution-template?tab=Overview" target="_blank">Azure marketplace から Imanis データ</a>をインストールできます。 Imanis Data software は、クラスターの外部にある VM にインストールされます。</p>


  <p>Azure HDInsight の Imanis データを構成するには、こちらの詳細な <a href="https://www.imanisdata.com/wp-content/uploads/2017/08/HDITalena-Resources-Deployment-Guide.pdf" target="_blank">ガイド</a>を参照してください。 次に示すのは、HDInsight の Imanis データの構成のスクリーンショットです。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/470518c9-1823-481b-8c9a-278c64b46441.png"><img width="610" height="308" title="2.45.04 PM のスクリーンショット2017-08-15" style="border: 0px currentcolor; border-image: none; margin-right: 0px; margin-left: 0px; display: inline; background-image: none;" alt="Screen Shot 2017-08-15 at 2.45.04 PM" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2480c34c-d644-4b56-a8a8-466689c491c9.png" border="0"></a></p>


  <p><br></p>


  <p>インストールが完了したら、Azure HDInsight クラスターに接続し、次の操作を実行します。</p>


  <ul>
   <li><strong>オンプレミスの hadoop または spark クラスターへの Imanis データの Connect:</strong> Imanis データは、オンプレミスの hadoop、spark、HBase、およびこれらのワークロードに関連付けられているメタデータからクラウドへのデータの移行に役立ちます。 Azure Blob Storage または Azure Data Lake Store にデータを格納できます。 データを移動したら、Hadoop、Spark、または HBase を実行したり、Azure HDInsight で R Server を使用して高度な分析を実行したりすることができます。</li>
   <li><strong>クラウドのディザスターリカバリー:</strong> Imanis データは、Hive、HBase、Spark などのオープンソースワークロードのデータとメタデータをセカンダリリージョンに移動するための基礎として簡単に使用できます。これにより、リージョン間の DR が可能になります。</li>
   <li><strong>拡張性の高いバックアップと迅速な回復:</strong> Imanis Data を使用すると、Hive、HBase、Spark などのオープンソースワークロードで使用されるペタバイト規模のデータを、非常に迅速にバックアップおよび特定の時点で復旧できます。</li>
   <li><strong>テストデータ管理:</strong> 企業がデータをクラウドに移行する際に、PII を保護することが重要です。 Imanis Data のネイティブデータマスク機能により、企業は、クラウド内の QA、Data Analytics またはその他のクラスターにデータを移行するときに、機密データを保護することができます。</li>
   <li><strong>コンプライアンスと規制の要件に対応したアーカイブ</strong>。</li>
  </ul>


  <h2>クラウド移行、バックアップと復元などに関する共同ウェビナー</h2>


  <p>6月27日に共同ウェビナーをホストし、Imanis データを使用して HDInsight 上のビッグデータアプリケーションを管理することによって、企業がどのようにメリットを得られるかを強調しています。 Imanis Data を使用してハイブリッド環境、開発/テスト管理、バックアップと復元、Azure の異なるリージョン間のレプリケーションを設定する方法について、さまざまなパターンについて説明します。 次の図は、対象となるパターンの概要を示しています。 見逃した場合でも、ウェビナーで詳細を <a href="https://go.imanisdata.com/Microsoft-Azure-Optimize-Performance-Reliability.html" target="_blank">ご覧</a> いただけます。 皆様からのご意見をお待ちしております。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6da51be3-50a9-4e86-b339-e2eb5b3adf37.png"><img width="610" height="356" title="10.09.16 PM のスクリーンショット2017-08-16" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" alt="Screen Shot 2017-08-16 at 10.09.16 PM" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c4a86b0f-959a-47c1-8011-6d89ff2e441e.png" border="0"></a></p>


  <h2>リソース</h2>


  <p>この統合の詳細については、次のリソースを参照してください。</p>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/hdinsight/" target="_blank">Azure HDInsight の詳細情報</a></li>
   <li><a href="https://globenewswire.com/news-release/2017/06/22/1027652/0/en/Talena-Enables-Rapid-Migration-of-Modern-Data-Workloads-to-Microsoft-Azure-HDInsight.html" target="_blank">Talena を使用すると、最新のデータワークロードを Microsoft Azure HDInsight に迅速に移行できます</a></li>
   <li><a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/talena-inc.talena-solution-template?tab=Overview" target="_blank">Azure Marketplace から Imanis データを取得する</a></li>
   <li><a href="https://www.imanisdata.com/wp-content/uploads/2017/08/Talena-Deployment-User-Guide.pdf" target="_blank">Azure での Imanis データの概要</a></li>
   <li><a href="https://www.imanisdata.com/wp-content/uploads/2017/08/HDITalena-Resources-Deployment-Guide.pdf" target="_blank">Azure HDInsight での Imanis データの概要</a></li>
   <li><a href="https://www.imanisdata.com/resources-cpt/microsoft-azure-datasheet/" target="_blank">Azure データシートでの Imanis データ管理ソリューション</a></li>
   <li><a href="https://github.com/Talena/public-templates/" target="_blank">クロス geo レプリケーションシナリオのために Azure HDInsight に Imanis データをデプロイする</a></li>
   <li><a href="https://www.imanisdata.com/solutions/microsoft-azure/" target="_blank">Azure での Imanis データについての詳細情報</a></li>
   <li><a href="https://stackoverflow.com/questions/tagged/hdinsight" target="_blank">Stackoverflow で HDInsight に関する質問をする</a></li>
  </ul>


  <h2>まとめ</h2>


  <p>この Imanis データを HDInsight 上で提供し、Azure Blob Storage と Data Lake Store と統合することにより、顧客はクラウドへの移行を迅速化し、重要なデータ資産をアプリケーションや人的エラーから保護できます。 ご意見やご質問がある場合は、に hdiask@microsoft.com 電子メールをお送りください。 皆様のご意見をお待ちしております。</p>
