### YamlMime:Yaml
ms.openlocfilehash: 5144144ab3fc2d2fe355374611de4ec19bb86cb3
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904765"
Slug: insights-and-best-practices-to-run-businesscritical-applications-on-azure
Title: インサイトビジネス クリティカルなアプリケーションを Azure で実行するためのベスト プラクティスとベスト プラクティス
Summary: '2020 年 9 月に、現在のミッション クリティカルなインフラストラクチャを管理する際に IT 組織が直面する主な課題を分析しました。 '
Content: >-
  <p>2020 年 9 月に、現在のミッション クリティカルなインフラストラクチャを管理する際に IT 組織が直面する主な課題 <a href="https://azure.microsoft.com/en-us/blog/run-your-core-applications-on-azure/" target="_blank">を分析しました</a>。 セキュリティの問題、高コスト、環境の更新の困難が最も重要でした。 逆に、クラウドへの移行は、これらのハードルの多くに対処する上で役立ちます。 実際、移行を完了したお客様は、多くの場合、次の利点を示しています。</p>


  <ul>
      <li>セキュリティとコンプライアンスの強化。</li>
      <li>ミッション クリティカルなシステムのパフォーマンスが向上し、待機時間が短縮されます。</li>
      <li>インフラストラクチャの実装時間の短縮。</li>
      <li>機敏性の向上 (新しい機能の開発中に既存のシステムを最新化する機会のため)。</li>
  </ul>


  <p>さらに、組織がコア ビジネス プロセスを実行するためにクラウドに依存している場合は、運用上の大きな利点を活用できます。 これは、不確実な状況では特に当てはっています。 また、組織が引き続きアプリケーションをクラウドに移行する速度が低下しない理由で、ビジネスクリティカルなアプリケーションも含まれます。</p>


  <h2>幅広いビジネス クリティカルなアプリケーション</h2>


  <p>また、ミッションおよびビジネスクリティカルなアプリケーションの範囲が、従来の記録システムを超えて拡大および進化し続けている方法も確認しました。 このパターンは、デジタル変革イニシアチブを進め、事実上すべての業界で見たものとなっています。</p>


  <p>今後のウェビナー のミニシリーズ「インサイト and <a href="https://info.microsoft.com/ww-landing-insights-and-practices-to-run-business-critical-apps-on-azure.html" target="_blank">Practices to Run Business-Critical Apps on Azure」(Azure</a>&nbsp; で Business-Critical Apps を実行するためのプラクティス) の期間中に、Azure をプラットフォームとして受け入れ、コア ビジネスクリティカルなアプリケーションを提供するプラットフォームとして、クラウド体験中に蓄積したエクスペリエンスを共有するように、いくつかのお客様と独立系ソフトウェア ベンダー (ISV) に問い合わせます。 また、お客様の支援を向上するために、このような前例のない時代が、より広範な規模でクラウド移行の優先順位に与えた影響を理解したいと考えています。 その結果、業界の同僚からの本物の視点に加えて、Forrester の市場調査の分析情報を更新します。</p>


  <p>この 3 部構成の Azure ウェビナー ミニシリーズでは、次の機能を利用できます。</p>


  <ul>
      <li>ビジネスクリティカルなアプリケーション向けクラウド移行戦略を構築する際に考慮する必要がある重要な成功要因について、Forrester から聞きます。</li>
      <li>Azure で利用できる最新のイノベーションを使用して、ビジネス クリティカルなアプリケーションの回復性とパフォーマンスを大規模に継続的に向上させる方法について説明します。</li>
      <li>実際の例を確認し、アーキテクチャを参照し、Riversand、Teradata、Unit4 のベスト プラクティスを学習します。</li>
  </ul>


  <h2>パート 1: ビジネスクリティカルなアプリケーションをクラウドに移行する</h2>


  <p>最初のウェビナーでは、ゲストスピーカーである Tracy Woo (Forrester Research のシニア アナリスト、インフラストラクチャと運用) が、過去数か月間に収集された最新の市場の傾向を共有します。 また、Microsoft が最近 Azure で導入した機能の一部を紹介します。これは、お客様がビジネスクリティカルなアプリケーションのクラウドへのデプロイを加速させるのに役立ちます。 このセッションでは、スケーラビリティ、セキュリティ、コンプライアンス、可用性に重点を置きます。 このすべての情報を実際の&nbsp;顧客環境のコンテキストに取り込むには、Riversand の役員とパネルディスカッションを行います。 Azure が提供する機能を使用して、マスター データ管理ソリューションと製品情報管理ソリューションをデプロイする方法について説明します。</p>


  <h2>パート 2: Azure の需要に基づいてデータ分析プラットフォームをスケーリングする</h2>


  <p>多くの場合、ビジネス クリティカルなアプリケーションについてしか話しませんが、データはアプリケーション自体よりも重要ではない場合でも重要です。 2 回目のウェビナーでは、Azure で大規模なデータ ウェアハウス環境のパフォーマンスを管理するのに役立つ実証済みの手法を確認するために、Teradata の分野の専門家を招待します。 Teradata は、クラウドベースのデータ ウェアハウス、ビジネス インテリジェンス、データ分析ソリューションを数年前から企業に提供してきました。 お勧めする講演者は、Teradata Vantage に関連するいくつかの側面を確認します。たとえば、セキュリティ機能、ハイブリッド クラウドデプロイへの取り組み方法、スケーラビリティ要因、クラウドベースのデータ分析プラットフォームに関する追加の推奨事項などです。 また、共有ディスクや、重要なアプリケーションのディスク ストレージのパフォーマンスをダウンタイムなくスケールアップまたはスケールダウンする方法など、新しい Azure Disk Storage 機能を使用して市場に出た最新のイノベーションも示します。</p>


  <h2>パート 3: Azure で ERP ソリューションを実行して、セキュリティ、可用性、コンプライアンスを向上する</h2>


  <p>最後に、ミッション クリティカルなアプリケーションを考える場合、エンタープライズ リソース計画 (ERP) システムが最初に思い付く場合がよくがあります。 過去数年間、Unit4 は、プロフェッショナル サービス、公共部門、非営利団体、教育などの業界で最新の ERP ソフトウェア ソリューションを提供してきました。 Unit4s&rsquo; CTO が参加し、実証済みのベスト プラクティス、ガイダンス、および本物の視点を提供します。 Unit4 が顧客のデプロイ戦略をガイド&rsquo; する方法も重要です。 リフト アンド シフト IaaS ベースの戦略からクラウドネイティブマイクロサービスベースの環境まで、クラウドの取り込みについて説明します。 また、使用中にデータを暗号化する機能など、ビジネスに不可欠なアプリケーションのセキュリティ、コンプライアンス、回復性を継続的に向上させるためにお客様が利用できる最新の Azure 機能も提供します。&nbsp;</p>


  <p>この 3 つのセッションでは、対象ユーザーからオンラインの質問を受け取り、特に関心のある関連領域をカバーします。</p>


  <h2>今すぐ登録</h2>


  <p><a href="https://info.microsoft.com/ww-landing-insights-and-practices-to-run-business-critical-apps-on-azure.html" target="_blank">今すぐ登録してウェビナー</a> シリーズに参加してください。独自の分析情報が豊富で、成長を続ける Azure コミュニティのメンバーとの本物のディスカッションが行います。</p>


  <p>さらに、Microsoft が委託した <a href="https://forrester.co1.qualtrics.com/jfe/form/SV_5bfMfKmQdxOkKfc" target="_blank">専用の Forrester コンサルティング</a>調査に参加し、組織がミッション クリティカルなアプリについてどのように考えているかについて共有してください。 ミニシリーズが完了すると、すべてのアンケート参加者に、集計された匿名化された結果の無料レポートが提供されます。</p>


  <p>ディスカッションに参加します。 これらの今後のセッションを楽しみにしています。</p>
