### YamlMime:Yaml
ms.openlocfilehash: aa2bf616b984f137e014e495834d8b8a0028fac1
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890720"
Slug: integrating-application-insights-into-a-modular-cms-and-a-multi-tenant-public-saas
Title: モジュール型 CMS インサイトマルチテナント パブリック SaaS へのアプリケーション アプリケーションの統合
Summary: Application インサイトをマルチテナント サービスに統合し、各テナントが独自の個別のパフォーマンスと使用状況の監視を取得する方法を提供しています。
Content: >-
  <p><strong>Orchard CMS Application インサイト モジュールと DotNest のケース スタディ</strong></p>


  <p><a href="https://azure.microsoft.com/services/application-insights/">Application インサイト</a>は、オープン ソース <a href="https://docs.microsoft.com/azure/application-insights/app-insights-platforms"></a> SDK とパブリック エンドポイントを使用して統合を開発しているパートナーと、<a href="https://github.com/Microsoft/ApplicationInsights-Home">アクティブなエコシステムを備えています</a>。 最近、Lombiq (パートナーの 1 人) が Application インサイト を Orchard CMS と同じマルチテナントパブリック SaaS バージョンに統合しました。</p>


  <p><i>ここでは、<a href="https://lombiq.com/">Lombiq</a> の共同設立者である Zoltn&aacute; Lehkyky&oacute; 氏による、自身の言葉による経験のケース スタディを示します。Orchard CMS 開発者。</i></p>


  <p>Application インサイトをマルチテナント サービスに統合し、各テナントが独自の個別のパフォーマンスと使用状況の監視を取得する方法を提供しています。 同時に、サービスのプロバイダーである We は、プラットフォーム全体の全体的な監視を取得します。 作成 <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights">したコードは</a> オープンソースです。</p>


  <p>アプリケーション <a href="https://azure.microsoft.com/services/application-insights/">インサイト</a>テレメトリを ASP.NET Web アプリに追加すると、アプリケーションを数回クリックVisual Studio。 しかし、Web アプリが、セルフホステッドまたはサービスとしての CMS として提供できる豊富な機能を備えたマルチテナント コンテンツ管理システム (CMS) である場合、監視のニーズの複雑さは増します。 そのため、アプリケーション ライブラリを拡張して、プラットフォームにネイティブと感じる統合インサイトがあります。 その目的は、CMS プラットフォームに固有の Application インサイト の最適な分析および監視機能をユーザーに提供することで、可能な限り簡単に行うことができます。 このブログ記事では、Orchard CMS Application インサイト モジュールで使用される手法とプラクティスについて説明します。</p>


  <p><a href="https://lombiq.com">Lombiq Technologies は、ハンガリー</a>の .NET ソフトウェア サービス企業です。 Microsoft 自体のような国際的なクライアントがいます。 <a href="https://orchardproject.net/">Microsoft</a> によって開始され、引き続きサポートされているオープン ソース ASP.NET MVC CMS である Orchard は、<a href="https://dotnest.com/">DotNest</a> と呼ばれるパブリック マルチテナントの Orchard as a Service も構築し、主に取り組む機能です。 長年の Azure ユーザーである Application インサイト について学習しました。まだ開発が非常に早く、DotNest で利用できる使いやすい Orchard 統合を構築し始めました。 では、どのようなエクスペリエンスを共有する価値がありますか?</p>


  <p>開発した Application インサイト Orchard モジュールはオープン ソースです。コードを追加する場合は、GitHub <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights"></a> で確認してください。 ここで説明するすべてが実装されています。</p>


  <h1>モジュール型マルチインサイト CMS での Application インサイトの使用</h1>


  <p>アプリケーション インサイト&ldquo;&rdquo;&rsquo;は、一般的に提供されるので、シングルテナント アプリケーションで簡単に動作します。この場合、ルートレベルの XML 構成ファイルが必要な問題はありません。 &rsquo;ただし、コードが、私たちの Orchard CMS などの他のユーザー アプリケーションに統合されるモジュールである場合は、すべての監視拡張機能を含むコードを自己格納型にしたいと考えます。 &rsquo;クライアントをアプリケーション レベルで構成ファイルに公開したくない。 つまり、Application インサイト をコードに統合して、独立して分散可能な 1 つの MVC プロジェクトを作成する必要があります。 分散フォームは、ソース リポジトリまたは zip ファイルである場合があります。</p>


  <p>Application インサイトをコードにパッケージ化するには、次の条件を実行する必要があります。</p>


  <ul>
   <li>アプリケーション構成インサイト&mdash;コードに移動します。つまり、通常は XML 構成ファイルで実行されるのと同じ操作を C# で行います。</li>
   <li>コード内のテレメトリ モジュールの有効期間を管理します。 各モジュールでは、テレメトリ&mdash;の要求、例外、依存関係など、さまざまな種類が処理されます。 通常、これらのモジュールは、.configファイルの読み取り時にインスタンス化され、構成ファイルにパラメーターが設定されます。 (<a href="https://docs.microsoft.com/azure/application-insights/app-insights-configuration-with-applicationinsights-config">詳細については、次を参照してください</a>。 コード<a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/Services/AppWideSetup.cs">)。</a></li>
   <li>静的シングルトンに依存するのではなく<code>TelemetryClient</code><code>TelemetryConfiguration</code>、カスタム方法で オブジェクトと オブジェクトを管理します。 これにより、個別のテナントのテレメトリを個別に保持できます。 (このコードの例を <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/Services/TelemetryConfigurationAccessor.cs">参照してください</a>)</li>
   <li>Orchard では、 <a href="https://logging.apache.org/log4net/">ログ記録に log4net</a> が使用されます。 このデータ<a href="https://docs.microsoft.com/azure/application-insights/app-insights-asp-net-trace-logs">は Application インサイト</a> で収集できますが、構成ファイルに依存するのではなく、ApplicationInsightsAppender を構成するコードを記述する必要があります。 (<a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/Services/LoggerSetup.cs">コード</a>) <p>すべて問題ないので、アプリ レベルの XML 構成を削除しました。 しかし、同じアプリに複数のテナントがある場合は、どうなるでしょうか。 Application インサイトの既定のセットアップでは、シングル テナントのみを念頭に置く必要があります。そのため、もう少し深く掘り下げる必要があります。 (この事後&ldquo;&rdquo;テナントの目的は、サブアプリケーションを意味します。これは、他のテナントに対して高レベルのデータ分離を維持するアプリケーション内のコンポーネント)</p>
   </li>
   <li>&rsquo;<code>HttpModule</code>要求の追跡には Application インサイト に含む を利用できません。グローバル構成ファイル (<code>Web.config</code>)&rsquo; を変更する必要があります。また、テナントごとに要求の追跡を簡単に切り替えることができるようになりました。 Owin ミドルウェア <a>を実装 </a>し、カスタム コードを使用して要求の追跡を <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/Services/RequestTrackingMiddlewareProvider.cs">行う時間</a>です。 このようなミドルウェアは、コードから完全に登録し、テナントごとに有効にできます。</li>
   <li>要求の追跡は独自の方法で行われるので、各要求のコードから操作 ID を追加する必要があります。 Application インサイトでは、<a href="https://docs.microsoft.com/azure/application-insights/app-insights-api-custom-events-metrics#operation-context">操作 ID は</a>、同じ要求の処理の一環として発生するテレメトリを関連付ける場合に使用されます。</li>
   <li>また&rsquo;、テレメトリの発生 <code>ITelemetryInitializer</code> 元となるテナントを追加する を追加します。 (<a href="https://docs.microsoft.com/azure/application-insights/app-insights-api-filtering-sampling#add-properties-itelemetryinitializer">詳細については、次を参照してください</a>。 <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/TelemetryInitializers/ShellNameTelemetryInitializer.cs">コード</a>) <p>すべてが完了すると、&rsquo;最終的には、テナントごとに個別に、インサイト 管理サイトから有効または無効にできる Application インサイト プラグインが使用されます。</p>

   <p>&nbsp;</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5dc3c3a0-2cd9-41fc-a344-131725695e15.png"><img alt="Lombiq Modules" border="0" height="343" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1eec4b56-72a5-49d8-a11d-49718a2d65c5.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Lombiq モジュール" width="580"></a></p>

   <p>&nbsp;</p>

   <h1>一部の果果てを追加する</h1>

   <p>ここまでは良いことですが、結果には、CMS&rsquo; の一部としてさらに多くの作業が必要です。まだ構成する場所はありません。</p>

   <p>Orchard では、 <i>サイト設定</i> を使用できます。 管理者&rsquo;が Web UI から変更できる構成オプションを簡単に追加できます。これらの設定はテナントのレベルです。 次&rsquo;のような設定画面が追加されました。</p>

   <p>&nbsp;</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0529a9dc-a217-4ac3-a146-01e0653989cb.png"><img alt="Enable application wide collection" border="0" height="445" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cd5ee839-bcb7-4f2c-8b78-d3f55645ec2c.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="アプリケーション全体の収集を有効にする" width="663"></a></p>

   <p>&nbsp;</p>

   <p>リモート リソースへのクエリ、ストレージ操作SQL HTTP 要求など、依存関係の呼び出しが追跡されます。 ただし、これにより多くのデータが生成されるので、&rsquo;依存関係の追跡をオフに切り替える可能性があります。</p>

   <p>一部の設定は、テナント レベルで構成できない (したがって、アプリ レベルである必要があります)、またはそうしても意味がない点に注意してください。たとえば、ログ エントリはテナントに関連付けられていません (アプリケーション全体ではなく)、これらはモジュール内のアプリ全体のコレクションでのみ使用できます (&rsquo;ただし、追加のテナント レベルのログ収集が可能になります)。 表示されるのは、メイン テナントでのみ使用&rsquo;できる完全な構成&ldquo;&rdquo;です。</p>

   <p>さらに、開発者がフックする拡張機能ポイントをいくつか追加しました。 &rsquo;そのため、同僚<a href="https://orcharddojo.net/orchard-resources/Library/Wiki/EventHandler">の Orchard</a> 開発者を呼び出した場合は、Application インサイト 構成をオーバーライドするか、テレメトリ データに独自のコンテキストを追加するか、イベント ハンドラー (および、その問題に対応する Orchard スタイルのイベント) を利用できます。</p>

   <p>&nbsp;</p>

   <h1>パブリック SaaS インサイトアプリケーション を使用できる</h1>

   <p>これまで見&rsquo;てきたのは、&rsquo;Application インサイト によって監視される自己格納型コンポーネントに必要なすべての基本的な機能でした。 ただし、<a href="https://dotnest.com/">すべてのユーザーがサインアップできる DotNest</a> では、Application インサイト による 2 つの異なる監視レイヤーが必要です。</p>
   </li>
   <li>独自の用途のために、アプリケーション全体に関する詳細なテレメトリが必要です。</li>
   <li>DotNest テナントのユーザーは、Application インサイト&rsquo; を個別に構成し、テナントに対してだけ表示を許可したテレメトリを収集する必要があります。
   <p>したがって、DotNest&rsquo; のユーザーには、プラットフォーム全体のレベルで管理インサイト元の Application インサイト 構成オプションも表示されます。 ただし、独自のインストルメンテーション キーを構成できる別のサイト設定画面が表示されます。</p>

   <p>&nbsp;</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5c65be51-30d8-40f1-9e7b-0928990526f7.png"><img alt="Azure Applications Telemetry Settings" border="0" height="327" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/23c9a35e-f5a8-4294-ac03-ca9b478887f3.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure Applications Telemetry 設定" width="689"></a></p>

   <p>&nbsp;</p>

   <p>このようなキーを指定すると、別の 2 つ目の Application インサイト 構成がテナント上に作成され、プラットフォーム レベルの構成と共に使用され、サーバー側とクライアント側の要求追跡とエラー報告が提供されます。 そのため、Lombiq では、サービスの所有者は、独自の Application インサイト&rsquo; アカウントのすべてのデータを表示しますが、各ユーザーは、通常どおり Azure Portal で独自のテナント データを表示することもできます。</p>

   <p>このテナント構成は、コードから元のテナントと同じ方法で作成および管理されます。</p>

   <p>&nbsp;</p>

   <h1>結果を表示する</h1>

   <p>このすべてが設定された後、収集したデータの種類を確認する必要があります。これは Azure Portal で通常どおり <a href="https://portal.azure.com">行います</a>。</p>

   <h2>ライブ メトリック ストリーム</h2>

   <p><a href="https://docs.microsoft.com/azure/application-insights/app-insights-live-stream">Live Metrics Stream</a> リアルタイム監視を提供します。 初期化チェーンに <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/TelemetryProcessors/DispatchingQuickPulseTelemetryProcessor.cs">適切なテレメトリ</a> プロセッサを含めしました。 これには、メモリや CPU&rsquo; 使用率などのシステム メトリックも含まれます。最近の状態では、アプリケーション インサイト 拡張機能をインストールして、App Serviceを確認する必要さえあります。</p>

   <p>&nbsp;</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f997fe5b-859d-47b3-96ba-3d2c6fe39821.png"><img alt="Incoming requests outgoing requests" border="0" height="352" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e3d60c73-c8d6-44ab-9f15-f3b80f8e1b60.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="受信要求送信要求" width="608"></a></p>

   <p>&nbsp;</p>

   <h2>トレース エラー</h2>

   <p>しかし、何か問題が起きたらどうでしょうか。 ログ エントリは、Azure Portal でトレース (標準ログ エントリ) または例外 (例外がキャッチおよびログ記録された場合) として表示されます。</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f66514c4-46d4-4a6f-8f6d-8b3ac7b4c948.jpg"><img alt="Something terrible happened" border="0" height="668" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7e1335a8-fc7c-46eb-8a49-b46928c8a52e.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="何か悪事が発生しました" width="445"></a></p>

   <p>しかし、操作 ID を&rsquo;実装したのを思い出してください。 イベント、例外、要求、すべてのデータ ポイントが単独で表示されるだけでなく、コンテキストでは、Application インサイト はテレメトリ データを他のデータ ポイントと関連付け、たとえば例外が発生した要求を伝えるという点が重要です。</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2cf5acab-6662-46cb-a534-7bd234d25352.jpg"><img alt="Hosting Suite Modules" border="0" height="547" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3cb1b0ce-fd3d-453d-a255-a377e9f592cb.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="ホスティング スイート モジュール" width="759"></a></p>

   <p>これにより、実稼働環境で発生した問題を再現する方法を簡単に確認できます。</p>

   <h1>まとめ</h1>

   <p>統合を再配布する必要なく、単一の構成で Application インサイト をアプリケーションに追加するだけの必要がない場合は、Application インサイト ライブラリ API について詳しい説明を&rsquo;行う必要があります。 ライブラリがオープン ソースの場合、これはあまり問題ではなく、C# を記述するだけでそれらを完全に構成して利用できます。 新しい <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights">Azure アプリケーション インサイトでは、それを</a>行う例も文書化されています。</p>

   <p>そのため、お気&rsquo;に入りで、統合に関する優インサイトしてください。 また、Azure Portal でファンシー グラフを使用するだけの場合は、無料の <a href="https://dotnest.com/DotNest.Frontend/UserSiteManagement/EditSite">DotNest</a> サイトをすばやく作成し、すぐにいくつかのデータの収集を開始できます。</p>
   </li>
  </ul>
