### YamlMime:Yaml
ms.openlocfilehash: 4b2b5b83af9435c053b3a4a714e0c7ff53a54f6c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895891"
Slug: introducing-the-app-service-migration-assistant-for-asp-net-applications
Title: ASP.NET アプリケーションの App Service Migration Assistant の概要
Summary: '2018年6月に、App Service 移行評価ツールをリリースしました。 評価ツールは、外部からアクセス可能な (HTTP) エンドポイントをスキャンして、サイトを Azure App Service に移動できるかどうかを迅速かつ簡単に評価できるように設計されています。 '
Content: >-
  <p><em>このブログ投稿は、Nitasha Verma、プリンシパルグループ Enginnering Manager、Azure App Service によって &nbsp; 共同作成されました。</em></p>


  <p>2018年6月に、 <a href="https://appmigration.microsoft.com/" target="_blank">App Service 移行評価ツール</a>をリリースしました。 評価ツールは、外部からアクセス可能な (HTTP) エンドポイントをスキャンして、サイトを Azure App Service に移動できるかどうかを迅速かつ簡単に評価できるように設計されています。 本日、更新されたバージョンのリリースを発表しまし &rsquo; た。 <a href="https://appmigration.microsoft.com/readiness" target="_blank">App Service Migration Assistant</a>。 新しいバージョンは、ASP.Net サイトをすばやく簡単に App Service に移行することによって、評価ツールによって識別されるサイトを顧客およびパートナーが移動するのに役立ちます。&nbsp;</p>


  <p><a href="https://appmigration.microsoft.com/readiness" target="_blank">App Service Migration Assistant</a>は、ASP.Net アプリケーションをオンプレミスからクラウドに移行するための、無料でシンプルで高速なソリューションを使用して、クラウドへの移行を簡略化するように設計されています。 以下を迅速に実行できます。</p>


  <ul>
   <li>パブリック URL のスキャンを実行して、アプリが移行の候補として適しているかどうかを評価します。</li>
   <li>Migration Assistant をダウンロードして、移行を開始します。</li>
   <li>ツールを使用して、アプリ &rsquo; の構成設定の準備チェックと一般的な評価を実行し、ツールを使用して Azure App Service にアプリまたはサイトを移行します。</li>
  </ul>


  <p>このツールの詳細を確認するか、 <a href="https://appmigration.microsoft.com/" style="border-bottom-color: currentColor; border-bottom-style: none; border-bottom-width: 0px; border-image-outset: 0; border-image-repeat: stretch; border-image-slice: 100%; border-image-source: none; border-image-width: 1; border-left-color: currentColor; border-left-style: none; border-left-width: 0px; border-right-color: currentColor; border-right-style: none; border-right-width: 0px; border-top-color: currentColor; border-top-style: none; border-top-width: 0px; color: rgb(95, 151, 175); font-family: inherit; font-size: 100%; font-style: inherit; font-weight: inherit; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; outline-color: invert; outline-style: none; outline-width: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; text-decoration: none; vertical-align: baseline;" target="_blank">今すぐ移行を開始</a>してください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/82ab2c81-c9f5-4f8b-add6-74a52a8958c7.png"><img alt="App Service Migration Tool landing page" border="0" height="608" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ad810c75-f024-4a57-b779-af63fb1ce31a.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="App Service 移行ツールのランディングページ" width="1078"></a></p>


  <h2>作業の開始</h2>


  <p><a href="https://appmigration.microsoft.com/readiness" target="_blank">App Service Migration Assistant をダウンロード</a>します。 このツールは、iiS バージョン7.0 以降で動作し、新規または既存の App Service プランを使用して、サイトのコンテンツと構成を Azure App Service サブスクリプションに移行します。</p>


  <h2>ツールの動作</h2>


  <p>Migration Assistant ツールは、詳細な評価を実行し、移行プロセスの手順を説明するローカルエージェントです。 このツールでは、 <a href="https://appmigration.microsoft.com/readinesschecks" target="_blank">準備チェック</a> に加えて、web アプリ &rsquo; の構成設定の一般的な評価が実行されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d027eb80-934c-483f-8e79-a95c14aacf6d.png"><img alt="Sample Assessment Report for website. " border="0" height="490" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3f8af7f6-462d-4245-af7a-570b1bbe8d10.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="評価レポート" width="703"></a></p>


  <p>アプリケーションで評価が成功すると、ツールによって Azure サブスクリプションでの認証プロセスが実行されます。その後、ターゲットアカウントの詳細を入力するように求められ、新しく移行したサイトのその他の構成の詳細と共にプランを App Service ます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cc15c43a-b79d-4145-a24d-64f4f18bf583.png"><img alt="Azure options" border="0" height="492" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/77bba0bc-3d39-4c04-ae47-3290a5fb2439.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure のオプション" width="701"></a></p>


  <p>このオプションを選択した場合、Migration Assistant ツールはサイトをターゲットの App Service プランに移動し、ハイブリッド接続も構成します。</p>


  <h2>データベースの移行とハイブリッド接続</h2>


  <p>この Migration Assistant は、web アプリケーションとそれに関連する構成を移行するように設計されていますが、データベースを移行することはありません。 データベースには、次の2つのオプションがあります。</p>


  <ol>
   <li><a href="https://azure.microsoft.com/en-us/services/sql-database/" target="_blank">SQL 移行ツール</a>を使用する</li>
   <li>オンプレミスのデータベースをそのままにして、を使用してクラウドから接続 <a href="https://docs.microsoft.com/en-us/azure/app-service/app-service-hybrid-connections" target="_blank">ハイブリッド接続</a></li>
  </ol>


  <p>App Service と共に使用すると、ハイブリッド接続によって、オンプレミスの SQL データベースである他のネットワーク &ndash; のアプリケーションリソースに安全にアクセスできます。 移行ツールを使用するとハイブリッド接続を構成してセットアップすることができます。これにより、オンプレミスのデータベースをいつでも移行することができます。</p>


  <h2>サポートされている構成</h2>


  <p>このツールは最新の ASP.Net アプリケーションを移行する必要がありますが、サポートされていない構成がいくつかあります。 次のようなものがあります。</p>


  <ul>
   <li>IIS のバージョンが7.0 未満</li>
   <li>ISAPI フィルターへの依存</li>
   <li>ISAPI 拡張機能への依存</li>
   <li>HTTP または HTTPS 以外のバインド</li>
   <li>HTTP の場合はポート80以外のエンドポイント、HTTPS の場合はポート443</li>
   <li>匿名以外の認証スキーム</li>
   <li>Location タグを使用した applicationhost.config 設定の依存関係</li>
   <li>複数のアプリケーションプールを使用するアプリケーション</li>
   <li>カスタムアカウントを使用するアプリケーションプールの使用</li>
   <li>グローバル設定に依存する URL 書き換え規則</li>
   <li>Web ファーム &ndash; の具体的に共有する構成</li>
  </ul>


  <p>ツールでサポートされている内容の詳細と、サポートされていない一部のサイトの回避策については、ドキュメントページを参照してください。</p>


  <p>App Service 移行の詳細については、 <a href="https://azure.microsoft.com/en-us/blog/migration-checklist-when-moving-to-azure-app-service/" target="_blank">App Service 移行チェックリスト</a>を参照してください。</p>


  <h2>次の内容 &rsquo;</h2>


  <p>今後数か月の間、ツールに機能を追加することを予定しています。 最も即時の優先順位は、追加の ASP.NET シナリオと、Java や PHP などの追加の web フレームワークのサポートです。</p>


  <p>ツールについてフィードバックがある場合、または改善を提案したい場合は、 <a href="https://github.com/Azure/App-Service-Migration-Tool/issues" target="_blank">GitHub のページ</a>で機能に関するご要望をお送りください。</p>
