### YamlMime:Yaml
ms.openlocfilehash: d6c98964df71e57d90c59d1608b7b90858d9602c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908918"
Slug: irap-protected-compliance-from-infra-to-sap-application-layer-on-azure
Title: AZURE 上のインフラストラクチャから SAP アプリケーションレイヤーへの IRAP で保護されたコンプライアンス
Summary: オーストラリア政府機関は、オーストラリア政府情報セキュリティマニュアル (ASD) によって生成されたオーストラリア政府情報セキュリティ マニュアル (ISM) の目的に準拠した AU-PROTECTED 政府データの処理、保存、および転送に適したサービスとしてのプラットフォーム (PaaS) 環境のデプロイを提供できるクラウドマネージド サービス プロバイダーを探しています。
Content: >-
  <p><em>この投稿は、Cloud4C から、Edvit Kumar Cherriri、Pankaj Badine、Vineet Bulbulefule&nbsp; によって共同作成されました</em></p>


  <p>オーストラリア政府機関は、オーストラリア政府情報セキュリティマニュアル (<a href="https://asd.gov.au/">ASD</a>) によって生成されたオーストラリア政府情報セキュリティ マニュアル (ISM) の目的に準拠した AU-PROTECTED 政府データの処理、保存、および転送に適したサービスとしてのプラットフォーム (PaaS) 環境のデプロイを提供できるクラウド マネージド サービス プロバイダーを探しています。</p>


  <p>&rsquo;州の財務の改善と維持を担当するオーストラリア最大の連邦機関の 1 つは、機密情報を保護し、転送、保存、取得に関するセキュリティ制御を確保するために不可欠な Information Security Registered Assessors Program (IRAP) の実装を探しています。</p>


  <p>Information Security Registered Assessors Program は、政府に高品質の情報通信技術 (政府) セキュリティ評価サービスを提供するオーストラリア信号総局イニシアチブです。</p>


  <p>Australian Signals Directorate は、より広範な業界およびオーストラリア政府の情報と関連するシステムをセキュリティで保護するための関連するセキュリティ サービスを提供するために、適切な資格を持つ情報および通信テクノロジの専門家を保証します。</p>


  <p>Cloud4C は、クラウド配信プラットフォームでこの連邦クライアントを有効にするために、この課題に取りかかっています。 Cloud4C は、Information Security Registered Assessors Program ガイドライン内の厳格なコンプライアンス要件を分析し、評価しました。</p>


  <p>内部ベースベースに従って、Cloud4C &ndash; は評価全体を物理、インフラストラクチャ、およびマネージド サービスの 3 つの異なるカテゴリに分割しました。 Information Security Registered Assessors Program には、これら 3 つの特定の領域に関する厳格なセキュリティ制御があります。</p>


  <p>Cloud4C は、この課題に正常に対応する最善の方法は、あり得ないが成功した価値のある評価を一緒に達成するための責任をパートナーと共有することで実現しました。 2018 年 4 月、Australian Cyber Security Center (ACSC) は、PROTECTED 分類で Azure と Office 365の認定を<a href="https://www.microsoft.com/en-us/trustcenter/compliance/ccsl">発表しました</a>。 Microsoft は、このレベルの認定を達成した最初の唯一のパブリック クラウド プロバイダーになりました。 Cloud4C は Microsoft と提携して SAP アプリケーションと SAP HANA データベースを Azure にデプロイし、Information Security Registered Assessors Program に準拠しているインフラストラクチャのすべての利点を利用して、Azure 上のネイティブツールとマーケットプレースのツールとテクノロジをシームレスに統合しました。</p>


  <p>Cloud4C は、オーストラリア、オーストラリア中部、オーストラリア中部 2 の適切な Azure データ センターを特定しました。これは、物理的なセキュリティと情報通信機器の配置に関して非常に厳格な Information Security Registered Assessors Program 評価を受けています。</p>


  <p>インフラストラクチャとディザスター リカバリーに対する Azure によるこのコンプライアンスにより、Cloud4C は、クラウド サービス プロバイダーのみに重点を置いた残りのコントロールの大部分に対処するために、マネージド サービス プロバイダーとして大きなスタートを行いました。</p>


  <p>Cloud4C の情報セキュリティ登録済み評価プログラムの評価では、Azure ディザスター リカバリーによって対処された制御を取り出した後、22 の主要なカテゴリに分散された 412 の高リスクと最も重要なセキュリティ側面の 19 を対応しました。</p>


  <p><there 22="" a="" amount="" and="" by="" challenge="" cloud4c="" controls="" diligently="" expertise="" maturity="" meeting="" needed="" of="" p="" significant="" staff="" that="" the="" this="" towards="" were="" who="" worked=""> </there></p>


  <h2>ソリューションの概要</h2>


  <p>この取り組みの範囲は、機密情報の処理、保存、取得に関する Information Security Registered Assessors Program の保護された分類標準を維持しながら、SAP ベースレイヤーまでのマネージド サービスを使用して、Azure 上の SAP ランドスケープを構成および管理する方法でした。 エンゲージメント モデルは PaaS であり、責任マトリックスは SAP ベースレイヤーまでであり、アプリケーションマネージド サービスは、このエンゲージメントの定義外でした。</p>


  <h3>単一のサービス レベル アグリーメントと情報セキュリティ登録済み評価プログラムで保護された分類を持つサービスとしてのプラットフォーム</h3>


  <p>提案されたソリューションには、SAP ERP、SAP BW、SAP CRM、SAP GRC、SAP IDM、SAP Portal、SAP Solution Manager、Web Dispatcher、Cloud Connector などのさまざまな SAP ソリューションが含まれており、SAP HANA、SAP MaxDB、および以前の Sybase データベースを含むデータベースが混在しています。 Azure Australiaプライマリ ディザスター リカバリーである Central と、セカンダリ ディザスター リカバリー リージョンであるオーストラリア中部 2 は、Information Security Registered Assessors Program で保護された準拠環境を構築するための物理的なディザスター リカバリーの場所として識別されました。 提案されたアーキテクチャには、SAP ワークロード用の認定仮想マシンの在庫保持ユニット (SKU)、最適化されたストレージとディスクの構成、適切な保護を備えた適切なネットワーク SKU、高可用性、ディザスター リカバリー、バックアップ、監視を実現するメカニズム、ネイティブと外部のセキュリティ ツールの適切な組み合わせ、最も重要なのは、サービス配信に関するプロセスとガイドラインが含まれます。</p>


  <p>次の Azure サービスは、提案されたアーキテクチャの一部と見なされました。</p>


  <ul>
   <li>Azure 可用性セット</li>
   <li>Azure Active Directory</li>
   <li>Azure Privileged Identity Management</li>
   <li>Azure Multi-Factor Authentication</li>
   <li>Azure ExpressRoute ゲートウェイ</li>
   <li>Web アプリケーション ファイアウォールを使用した Azure アプリケーション ゲートウェイ</li>
   <li>Azure Load Balancer</li>
   <li>Azure Monitor</li>
   <li>Azure Resource Manager</li>
   <li>Azure Security Center</li>
   <li>Azure Storage とディスクの暗号化</li>
   <li>Azure DDoS Protection</li>
   <li>Azure Virtual Machines (SAP アプリケーションとデータベース用の認定SAP HANA仮想マシン)</li>
   <li>Azure Virtual Network</li>
   <li>Azure Network Watcher</li>
   <li>ネットワーク セキュリティ グループ</li>
  </ul>


  <h3>情報セキュリティ登録済み評価者プログラムのコンプライアンスと評価プロセス</h3>


  <p>Cloud4C は、Information Security Registered Assessors Program の評価者の支援を受け、認定フレームワーク内を移動しました。このフレームワークは、オーストラリア政府のセキュリティを理解して実装し、SAP アプリケーションと SAP HANA データベースを Azure で保護されたクラウド上の Information Security Registered Assessors Program で保護されたセットアップに移植する技術的な実現可能性を構築するのに役立ちます。</p>


  <p>Information Security Registered Assessors Program の評価者は、システムのセキュリティ制御の実装、適切性、有効性&#39;評価しました。 これは、オーストラリア政府情報セキュリティ マニュアル (ISM) に示されている 2 つのセキュリティ評価 <a href="https://acsc.gov.au/infosec/ism/index.htm">段階で実現されました</a>。</p>


  <ul>
   <li>ステージ<b> </b>1: セキュリティ評価では、システム所有者が修正または軽減するセキュリティの欠陥を特定します</li>
   <li>ステージ 2: セキュリティ評価で残りのコンプライアンスを評価する</li>
  </ul>


  <p>Cloud4C は、適用可能なすべての情報セキュリティ手動制御の下で評価を成功に収め、リスクの低い環境を確保し、Microsoft のサポートを受け、重要な情報システムを保護しています。</p>


  <p>Microsoft チームは、Azure ネイティブ ツールを活用してコンプライアンスを実現する方法に関するベスト プラクティスに関するガイダンスを提供しました。 Microsoft ソリューション アーキテクトおよびエンジニアリング チームは、設計に関するディスカッションに参加し、Azure ネイティブ セキュリティ ツール、サードパーティのセキュリティ ツールの統合シナリオ、およびアーキテクチャで可能な最適化に関する既存のナレッジ ベースを取り入れしました。</p>


  <p>評価中に、Cloud4C と Information Security Registered Assessors Program の評価者は次のアクティビティを実行しました。</p>


  <ul>
   <li>全体的なコミュニケーションに関係するすべてのコンポーネントと利害関係者を組み込んだシステム アーキテクチャを設計しました</li>
   <li>オーストラリア政府のセキュリティ ポリシーに対するマップされたセキュリティ コンプライアンス</li>
   <li>情報セキュリティ登録済み評価者プログラムによって認定されている、特定された物理的な施設である Azure データ センター (オーストラリア中部とオーストラリア中部 2)</li>
   <li>情報セキュリティの手動セキュリティ制御の実装</li>
   <li>コンプライアンス非対応に対して定義された軽減戦略</li>
   <li>システムに対するリスクを特定し、軽減戦略を定義しました</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ad41b64b-767c-4368-a245-c4e9857b66a3.png"><img alt="Placeholder" border="0" height="322" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8e63d431-5515-4fde-b478-7bd3c7bc606f.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="643" width="640"></a></p>


  <h3>自動化とプロセスの改善を確保するための手順</h3>


  <ul>
   <li>ツールと組み合Azure Resource Manager (ARM) テンプレートを使用した迅速なデプロイ。 これは、1 か月未満で 100 を超える仮想マシンと 10 の SAP ソリューションで構成される大規模なランドスケープのデプロイに役立ちます。</li>
   <li>Robotic Process Automation (RPA) ツールを使用したプロセス自動化。 これは、Information Security Registered Assessors Program 環境にデプロイされた SAP 環境内の通常のステージとしてビジネスを識別し、アプリケーションの可用性を確保するインフラストラクチャ レベルを処理する自動化に基いて、実際のビジネス プロセスの中断を最小限に抑えるプロセスを強化するのに役立ちます。<em> </em></li>
  </ul>


  <h3>プロセス中に実装された学習とそれぞれのソリューション</h3>


  <ul>
   <li>Azure Central リージョンと Azure Central 2 リージョンは、ミリ秒未満の待機時間を提供するファイバー リンクを使用して互いに接続されました。SAP アプリケーションと SAP HANA データベース レプリケーションは同期モードで、目標復旧時点 (RPO) はゼロでした。</li>
   <li>Azure Active Directory Domain Services はオーストラリア中部リージョンでは利用できないので、Azure South-East リージョンはシームレスな配信を保証するために利用されました。</li>
   <li>Azure Site Recovery SAP Max DB データベースのレプリケーションに正常に使用されました。</li>
   <li>既定では、Azure ExpressRouteを流れるトラフィックは暗号化されていないので、Microsoft セキュリティ パートナーのネットワーク仮想アプライアンスを使用して暗号化されました。</li>
  </ul>


  <p>Information Security Registered Assessors Program に準拠するには、Australian Signals Directorate が定義した資格を満たし、評価フェーズを通過する必要があります。 Cloud4C には、次の利点がありました。</p>


  <ul>
   <li>市場に出る時間の短縮 - Cloud4C は、約 1 年から 2 年の業界実績と比較して、9 か月で評価プロセスを完了しました。</li>
   <li>Cloud4Cs&rsquo; では、Azure 上の顧客に対して複数のリージョンと業界固有のコンプライアンスを提供する経験と知識が、適切なコントロールを Azure ネイティブおよび外部のセキュリティ ツールにマッピングするのに役立ちます。</li>
  </ul>


  <p>Microsoft とのパートナーシップにより、Cloud4C は別のマイルストーンに到達し、厳しい規制と地理的コンプライアンスを満たすために Azure Hyperscaler が提供する必要があるすべてのセキュリティ機能を活用しました。</p>


  <p>Cloud4C は、Azure Native からすぐに利用できる多くのセキュリティ ソリューションと、市場に出る時間を短縮する Azure Marketplace を使用して成熟しました。 Cloud4C では、お客様の&#39;インフラストラクチャをセキュリティで保護し、クライアントを Azure Expert マネージド サービス プロバイダー (MSP) としてサポートする安全な文化を促進する観点から、Azure ポートフォリオを最大に活用しました。 Azure セキュリティ ポートフォリオは成長を続けています。Cloud4C&#39;ソリューションオファリングの使用もサポートされています。</p>


  <p>Cloud4C と Microsoft は、このパートナーシップを活用して、さまざまな地域や業界全体でマーケットプレース内の顧客に対して、一致しないクラウド エクスペリエンスを提供するという点で、さらに高いレベルを実現する予定です。</p>


  <h3>詳細情報</h3>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/security/fundamentals/services-technologies">Microsoft の Azure セキュリティ ソリューション</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/#pivot=products">Azure ネイティブ製品</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/cloud-solution-provider/migration/migration-from-on-premises-to-azure-csp">ワークロードの Azure への移行</a></li>
   <li><a href="https://www.cloud4c.com/azure-managed-services">Cloud4C Azure マネージド サービス</a></li>
   <li><a href="https://www.cloud4c.com/azure-sap">クラウド向け Cloud4C SAP on Azure</a></li>
  </ul>
