### YamlMime:Yaml
ms.openlocfilehash: 62aaaa62e2bd9055375ed567d285a3b593e69f35
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908913"
Slug: isolate-app-integrations-for-stability-scalability-and-speed-with-an-integration-service-environment
Title: 統合サービス環境を使用して、安定性、スケーラビリティ、および速度のアプリ統合を分離する
Summary: 大規模なイノベーションは、大規模な組織に直面する一般的な課題です。 課題の重要な共同作成者は、アプリと環境の数を調整することの複雑さです。
Content: >-
  <p>大規模なイノベーションは、大規模な組織<a href="https://azure.microsoft.com/en-us/blog/connecting-the-colossal-how-to-scale-innovation-with-serverless-integration/" target="_blank">に</a>直面する一般的な課題です。 課題の重要な共同作成者は、アプリと環境の数を調整することの複雑さです。</p>


  <p><a href="https://azure.microsoft.com/en-us/services/logic-apps/" target="_blank">Azure Logic Apps</a>などの統合ツールを使用すると、オンプレミスまたはクラウドで、必要なだけ迅速にスケールおよびイノベーションを行うことができます。 これは、クラウドに移行するときに必要となる重要な機能であり、クラウドネイティブを再&#39;する場合にも必要です。 多くの場合、統合は、その後の処理として作業されています。 しかし、現代的な企業では、アプリケーションの統合は、アプリケーションの開発とイノベーションと連携して行う必要があります。</p>


  <p>統合サービス環境は、雑音の多い近隣の問題やデータの分離を懸念する組織にとって理想的なソリューションであり、コア Logic Apps サービスのプランよりも柔軟性と柔軟さを必要とします。</p>


  <p>既存の一連の機能に基づいて、次のような統合サービス環境をさらに向上させる、 <a href="https://aka.ms/integrated-service-environment-azure-update" target="_blank">魅力的な新しい変更をいくつ</a> かリリースしています。</p>


  <ul>
      <li>以前のプロビジョニング時間を半分にすることによる展開時間の短縮</li>
      <li>個々のロジックアプリとコネクタのスループット制限の向上</li>
      <li>個々のロジックアプリは、最大1年 (365 日) で実行できるようになりました</li>
  </ul>


  <p>Logic Apps 用の統合サービス環境は、コアアプリケーション開発戦略の一環として統合を進めている組織のための次の手順です。 &rsquo;統合サービス環境では、次のことを実現できます。</p>


  <ul>
      <li><strong>仮想ネットワークリソースへのアクセスを直接、セキュリティで保護</strong>します。 を使用すると、仮想マシン、サーバー、仮想ネットワーク内のその他のサービス (サービスエンドポイントを使用する Azure サービスやオンプレミスのリソースなど) に、 <a href="https://azure.microsoft.com/en-us/services/expressroute/" target="_blank">Azure ExpressRoute</a> またはサイト間 VPN 経由で、セキュリティで保護されたプライベートリソースへの直接アクセスを Logic Apps できます。</li>
      <li>一貫した<strong>信頼性の高いパフォーマンス</strong>。 ノイズ近隣の問題を排除して、Logic Apps のみで実行される専用のランタイムによってビジネスクリティカルなプロセスに影響する可能性がある、断続的なダウンタイムを回避します。</li>
      <li>分離された<strong>プライベートストレージ</strong>。 規制の対象となる機密データは、プライベートで安全で、新しい統合の機会が開かれます。</li>
      <li><strong>予測可能の価格</strong>。 Logic Apps の月額固定コストを提供します。 各統合サービス環境には、1つの standard 統合アカウントと1つのエンタープライズコネクタの無料使用が含まれます。 Logic Apps アクションの実行回数が1か月あたり5000万のアクションを超えた場合、統合サービス環境ではより良い値が得られる可能性があります。</li>
  </ul>


  <p>Logic Apps 用の統合サービス環境を初めて使用する場合は、 詳細については、こちらの <a href="https://www.youtube.com/watch?v=1EnNdpz3UM0&amp;feature=youtu.be" target="_blank">Azure 金曜日の概要ビデオ</a> をご覧ください。</p>


  <p><a href="https://docs.microsoft.com/en-us/azure/logic-apps/connect-virtual-network-vnet-isolated-environment-overview" target="_blank">Azure Logic Apps のための統合サービス環境</a>の概要をご覧ください。</p>
