### YamlMime:Yaml
ms.openlocfilehash: 22cec21f1de3458ef364efb53c687a5bbd55034a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895023"
Slug: july-update-for-web-apps-and-app-service-environments-in-the-azure-preview-portal
Title: Azure プレビュー ポータルでの Web アプリApp Service環境の 7 月の更新
Summary: Azure プレビュー ポータルで、Web アプリとクラウド環境エクスペリエンスにApp Serviceいくつかの機能強化を展開しました。
Content: >-
  数週間、忙しい思いをしました。Azure プレビュー ポータルで、Web アプリとクラウド環境エクスペリエンスに<strong>App Serviceいくつかの機能強化</strong>を展開しました。<strong></strong>

  <h1>Web アプリの新しい作成エクスペリエンス</h1>

  <div id="attachment_323761" align="alignleft" width="1366"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-001.png"><img class="size-full wp-image-323761" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-001.png" alt="New web App Create experience" width="1366" height="768" /></a> 新しい Web アプリの作成エクスペリエンス</div>


  Web アプリの作成エクスペリエンスが効率化され、より高速かつはるかに簡単になります。 この新しいエクスペリエンスでは、Web アプリの作成は名前を指定するのと同じほど簡単です。 App Serviceや価格レベルなどのプラン のプロパティは論理的にグループ化され、重要な場所に表示されます。 場所やインスタンス数など、Web アプリApp Service適切なプランを選択するのに役立つ関連情報がコンテキストで表示されます。

  <h1>Web アプリ リソース ブレードの機能強化</h1>

  次の領域で、[Web アプリ リソース] ブレードが多くの機能強化を行いました。

  <h2>Web アプリ ブレードのパフォーマンス</h2>

  ほとんどのリリースと更新プログラムには、パフォーマンスと信頼性の修正が含まれています。通常は、数秒の改善が追加されます。 ただし、この数週間、Web アプリ ブレードのパフォーマンスの修正を強調しました。 この特定の更新プログラムでは、エクスペリエンスから 1 秒を切り離す方法が管理されたため、パフォーマンスが向上しています。 これらの機能強化により、より迅速なナビゲーション、より信頼性の高いリソース ブレードの読み込み、全体的なエクスペリエンスの向上が実現します。 また、新しいパフォーマンスのボトルネックや回帰を特定し、事前に修正できる場所でテレメトリを改善しました。

  <h2>App Service Plan Lens</h2>

  <div id="attachment_323771" align="alignleft" width="1366"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-002.png"><img class="size-full wp-image-323771" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-002.png" alt="App Service plan lens" width="1366" height="768" /></a> App Serviceレンズ</div>


  プランの概App Serviceの多くが [使用状況のレンズ] の下の [Web アプリ リソース] ブレード<strong></strong>に表示され、混乱を引き起こしました。 Web アプリ ブレードでこのレンズの名前を "App Service<strong>プラン</strong>" に変更しました。これは、そこに含まれる情報をよりよく表します。 またApp Serviceレンズには、プランブレードを開く直接App Serviceも含まれています。

  <h2>[新しいツール] メニュー</h2>

  <div id="attachment_323781" align="alignleft" width="1366"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-003.png"><img class="size-full wp-image-323781" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-003.png" alt="Web App Tools menu" width="1366" height="768" /></a> [Web アプリ ツール] メニュー</div>


  提供されているツールに <strong>すばやくアクセス</strong> する方法として、アクション バーにツール メニューを追加しました。 トラブルシューティングやリソース <strong>エクスプローラーARM</strong><strong></strong> <a title="" href="https://resources.azure.com" target="_blank"> エクスプローラー</a>など、このメニューのツールの多くは、長い間使用していますが、見つけやすくはありませんでした。

  <h2>Web アプリの新しい Java 構成オプション</h2>

  <div id="attachment_323801" align="alignleft" width="1366"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-004.png"><img class="size-full wp-image-323801" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-004.png" alt="Web App Java configuration" width="1366" height="768" /></a> Web アプリ Java の構成</div>


  Java ユーザーは、メジャーバージョンとマイナー バージョン、およびコンテナーを構成できる新しい <strong></strong> <strong>Java</strong> <strong></strong> バージョン セレクターの恩恵を受<strong>けるでしょう</strong>。

  <h1>更新プログラムのApp Service Environment</h1>

  <div id="attachment_323811" align="alignleft" width="1366"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-005.png"><img class="size-full wp-image-323811" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-005.png" alt="App Service Environment metrics" width="1366" height="768" /></a> App Service Environmentメトリック</div>


  [ <strong>App Service Environment</strong> リソース] ブレードにメトリック グラフが表示され、ワーカー プール全体の使用率を監視できます。


  また、多くのお客様の要求に応じて、App Service 環境を小さな <strong>サブネット (8</strong> IP アドレスまたは /29 マスクまで) に作成することもできます。
