### YamlMime:Yaml
ms.openlocfilehash: 9fd305c911e049a2a161c645477531a173933041
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895495"
Slug: keeping-your-environment-secure-with-update-management
Title: アプリケーションを使用して環境をセキュリティで保護Update Management
Summary: Update Managementを使用すると、マシンの更新プログラムとパッチを管理できます。  このUpdate Management、利用可能な更新プログラムの状態をすばやく評価し、必要な更新プログラムのインストールをスケジュールし、展開結果を確認して、更新プログラムが正常に適用されたことを確認できます。 これは、マシンが Azure VM、AWS VM、他のクラウド プロバイダーによってホストされている、またはオンプレミスの場合に可能です。
Content: >-
  <p>Azure Update Managementサービスは <a href="https://azure.microsoft.com/en-us/pricing/details/automation/">、Azure サブスクリプションの一部として含まれています</a>。 更新管理を使用すると、マシンの更新プログラムとパッチを管理できます。 更新管理を使用すると、利用可能な更新プログラムの状態をすばやく評価し、必要な更新プログラムのインストールをスケジュールし、デプロイ結果を確認して、正常に適用される更新プログラムを確認できます。 これは、マシンが Azure VM か、他のクラウド プロバイダーによってホストされている場合でも、オンプレミスでも可能です。</p>


  <p>このUpdate Managementするには、いくつかの前提条件を満たす必要があります。 Azure VM が既に存在する場合、このプロセスは簡単です。</p>


  <ol>

  </ol>


  <p>VM に移動し、左側のメニュー <strong>から</strong> [管理の更新] を選択します。</p>


  <ol>

  </ol>


  <p>次の画面で、[有効にする] ボタン<strong> をクリック</strong> します。 これにより、既定値を使用して、ログ分析ワークスペースと Automation アカウントが作成されます。 既存のワークスペースまたは Automation アカウントがある場合は、それらのアカウントも選択できます。</p>


  <ol>

  </ol>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/26d65595-12c6-4d59-a132-caf71433517e.png"><img alt="2_configure" border="0" height="464" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d9110880-6110-4389-9da5-d9966aff3309.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="2_configure" width="1110"></a></p>


  <p>これが完了すると、新しいビュー Update Managementされます。 データが設定されるには時間が必要ですが、このビューでは 1 つの VM に関する情報が提供されます。 [複数のコンピューターの管理] をクリックしてアクセスできるマルチマシン <strong>ビューも用意されています</strong></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/229786e8-0d98-449b-b274-a13bbf2ad8a2.png"><img alt="3_multi" border="0" height="879" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8c95a597-33a3-424f-90e9-1f1ef2aaab01.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="3_multi" width="1029"></a></p>


  <p>[ <strong>Azure VM</strong> の追加] または [Azure 以外のコンピューターの追加] を選択すると、このビューからマシンを簡単 <strong>に追加できます</strong>。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1ea1207c-bf7e-4a66-b327-c41571dac683.png"><img alt="4_multi (1)" border="0" height="594" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7a191042-1d4c-4cf1-9e23-d5bc63b40982.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="4_multi (1)" width="958"></a></p>


  <h2>データを使用してUpdate ComplianceをUpdate Management</h2>


  <p>マシン <a href="https://aka.ms/winvmupdate">を Update Management</a>すると、マシンの状態をレポートするダッシュボードにアクセスできます。 これは、マシンが Azure VM、AWS VM、その他のクラウド プロバイダー、またはオンプレミスの場合に可能です。</p>


  <h2>セキュリティ更新プログラムの展開</h2>


  <p>マシンにパッチをデプロイするには、マルチ <strong>マシン ビューから [更新プログラムのデプロイ</strong> のスケジュール] を選択します。</p>


  <p><img alt="" border="0" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5_schedule-1.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;"></p>


  <p>&nbsp;</p>


  <p>新しいブレードが表示されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8f3fa92a-394e-47a9-9442-e2e8da044502.png"><img alt="6_deploy" border="0" height="881" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/08f3ca21-a853-4be2-9c05-27f4181ff122.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="6_deploy" width="317"></a></p>


  <p>このブレードでは、更新プログラムを受け取るコンピューターを選択できます。 必要な場合は、更新プログラムの分類 <strong>をフィルター処理して、セキュリティ</strong> 更新プログラムのみを適用できます。 更新プログラムの実行は、1 回または定期的に実行するようにスケジュールできます。 メンテナンス期間は、更新プロセスをマシンで実行できる期間を定義します。</p>


  <p>詳細については、「更新プログラムの展開 <a href="https://docs.microsoft.com/en-us/azure/automation/manage-update-multi#schedule-an-update-deployment">のスケジュール設定」</a> と「更新プログラムのUpdate Management <a href="https://docs.microsoft.com/en-us/azure/automation/automation-tutorial-update-management">してください。</a></p>
