### YamlMime:Yaml
ms.openlocfilehash: 15cc75e743bf12b7af770115b299e8e639503296
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895497"
Slug: keeping-your-cloud-deployments-secure-during-challenging-times
Title: 困難な時間中にクラウド デプロイをセキュリティで保護する
Summary: COVID-19 に対処するために世界が集い、リモート作業が多くの企業にとって重要な機能になる中、お客様は、より多くのリモートワーカーがアクセスできる一方で、クラウド資産のセキュリティ態勢を最適に維持する方法を問い合わせました。
Content: >-
  <p>COVID-19 に対処するために世界が集い、リモート作業が多くの企業にとって重要な機能になる中、お客様は、より多くのリモートワーカーがアクセスできる一方で、クラウド資産のセキュリティ態勢を最適に維持する方法を問い合わせました。</p>


  <p>クラウド セキュリティ制御<a href="https://www.csoonline.com/article/3208905/top-cloud-security-controls-you-should-be-using.html" target="_blank"></a>&rsquo;の構成ミスは、最近のいくつかのデータ侵害の根本にあるので、クラウド資産の使用が増加するにしたがって、セキュリティ態勢の監視を継続することが非常に重要です。</p>


  <p>実行する必要があるアクションに優先順位を付けるために、リモート ワーカーの 3 つの一般的なシナリオと、Azure Security Center セキュリティ制御を活用して、これらのシナリオに関連する推奨事項に優先順位を付ける方法を示します。</p>


  <blockquote>

  <p>1. リソースにリモートでアクセスする必要があるユーザーが多い場合は、ID 保護を強化するために <a href="https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/untrusted-networks" target="_blank">Multi-Factor Authentication (MFA)</a> が有効になっている必要があります。</p>

  </blockquote>


  <ul>
      <li>Azure Security Center MFA の有効化と呼ばれるセキュリティ コントロールがあります。理想的には、次に示すように、このセキュリティ制御の一部であるすべての推奨事項を修復する必要があります。</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5d16c70c-1df3-4a86-bc83-3ef777c79eea.png"><img alt="image" border="0" height="115" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/111d989c-3def-4546-8d39-131be97516c3.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="イメージ" width="519"></a></p>


  <blockquote>

  <p>2. 一部のユーザーは、Azure インフラストラクチャ内のサーバーへの RDP または SSH 経由のリモート アクセスを必要とする場合があります。</p>

  </blockquote>


  <ul>
      <li>これらのサーバーへの完全な 24 x 7 アクセスを許可する代わりに、それらのサーバーへの <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-just-in-time" target="_blank">Just-In-Time (JIT) VM アクセスを使用することを確認します</a>。 このシナリオに関連する推奨事項を修正するには、Azure Security Centerセキュリティで保護された管理ポートの制御を確認してください。</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3db6890c-69bc-4d07-b330-5dedc45894b6.png"><img alt="image" border="0" height="106" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a84d16f7-fcf9-42dc-ae25-97487c3a9257.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="イメージ" width="537"></a></p>


  <blockquote>

  <p>3. ユーザーがリモートでアクセスするワークロード (サーバー、コンテナー、データベース) の中には、重要なセキュリティ更新プログラムが欠落している可能性があります。</p>

  </blockquote>


  <ul>
      <li>インストールする必要がある更新プログラムの優先順位をAzure Security Centerの脆弱性の修復コントロールを確認します。 組み込みの脆弱性評価ですべての推奨事項の結果<a href="https://docs.microsoft.com/en-us/azure/security-center/built-in-vulnerability-assessment" target="_blank"></a>を確認し、それらの項目を修復してください。</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e1c4a96a-2bf5-4c7e-ae7f-b0e9b0844060.png"><img alt="image" border="0" height="223" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/dbf0ab1b-ee96-4bad-87e3-24a8f81f5e8f.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="イメージ" width="553"></a></p>


  <p>セキュリティ体制管理は継続的なプロセスです。 セキュリティ スコア <a href="https://docs.microsoft.com/en-us/azure/security-center/secure-score-security-controls" target="_blank">を確認して</a> 、完全に準拠した環境への進行状況を理解します。</p>


  <p>Azure のユーザーは、ユーザー ベースの一部にすすむ可能性があります。 組織の残りの部分でリモート作業を有効にし、セキュリティで保護するための追加のガイダンスを次に示します。</p>


  <ul>
      <li><a href="https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/12/top-9-ways-microsoft-it-enabling-remote-work-employees/" target="_blank">Microsoft IT が従業員のリモート作業を有効にする上位 9 つの方法</a></li>
      <li><a href="https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/10/staying-productive-while-working-remotely-with-microsoft-teams/" target="_blank">リモートで作業しながら生産性を維持Microsoft Teams</a></li>
      <li><a href="https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/02/working-remotely-during-challenging-times/" target="_blank">困難な時間にリモートで作業する</a></li>
      <li><a href="https://www.microsoft.com/security/blog/2020/03/12/support-working-from-home-securely/" target="_blank">リモートで作業し、CISOs のセキュリティ&mdash;を確保する</a></li>
  </ul>
