### YamlMime:Yaml
ms.openlocfilehash: 2eadef6176270e366f4c40ef9b22656ec1c00d21
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139894347"
Slug: log-alerts-for-application-insights-preview
Title: Application インサイト のログ アラート機能のプレビュー
Summary: Application インサイト (プレビュー) Application インサイト のログ アラートは、複数のプラットフォーム上の Web 開発者向けの拡張可能なアプリケーション パフォーマンス管理 (APM) サービスです。
Content: >-
  <p><em>このブログ記事は、Azure Infrastructure Management のプリンシパル PM マネージャーである、シニア プログラム マネージャーの Vijay Seniorraja 氏と、Kiran Madnani 氏によって共同執筆されました。</em></p>


  <h4>この機能は一般提供されています。 Azure portal に加えて、スケジュールされたクエリ ルール <a href="https://docs.microsoft.com/en-us/rest/api/monitor/scheduledqueryrules">REST API</a> を直接、または Azure CLI、PowerShell、Azure Resource Manager テンプレートから呼び出します (リソース マネージャーを使用したログ アラートの管理に関するページを参照<a href="https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitor-alerts-unified-log-template#managing-log-alert-on-application-insights">してください)。</a> 価格は、価格に関 <a href="https://azure.microsoft.com/en-us/pricing/details/monitor/">するAzure Monitorページで確認できます</a>。</h4>


  <p>Application インサイトは、複数のプラットフォーム上の Web 開発者向けの拡張可能なアプリケーション パフォーマンス管理 (APM) サービスです。 お客様は、Application インサイトを使用して、ライブ Web アプリケーションの監視、パフォーマンスの異常の検出、問題の診断、使用パターンの把握を行います。 さまざまなメトリックに基づくアプリケーションの正常性に関するアラートに加えて、指定した間隔で実行するクエリを設定し、結果に基づいてアラートをトリガーすることで、電子ログ ファイルを監視できます。 たとえば、特定の&rsquo;例外に&rsquo;対して新しい修正プログラムをデプロイし、再び表示されるのを確認するとします。 これで、その例外がアプリケーション のトレース ファイルに表示された場合にトリガーインサイト設定できます。</p>


  <p>Application インサイトのログ アラートには、新しい <a href="https://portal.azure.com/?feature.customportal=false#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/alertsV2">Azure アラート エクスペリエンスからアクセスできます</a>。 <a href="https://azure.microsoft.com/en-us/blog/new-alerts-preview-in-azure-monitor/" target="_blank">詳細については、Azure アラート (プレビュー) に関するページを参照してください</a>。 新しいアラートを作成し、ターゲット リソースを Application インサイト。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8c721d8a-0b78-4e70-8ed8-656696d60116.png"><img alt="Alerts - Select Application Insights" border="0" height="889" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b37b42ef-166f-453e-aa6e-e8f10f9dc8e8.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="[アラート] - [アプリケーション] インサイト" width="527"></a></p>


  <p><br clear="all">

  Log Analytics のお客様は、アラートを作成するための使い慣れたインターフェイスを見つける必要があります。 Log Analytics と同様に、ログ アラートでは次の 2 種類がサポートされます。</p>


  <ul>
   <li><b><u>[レコードの数</u></b>]: Application インサイト でクエリに対して返されたレコードの数に基づいてアラートをトリガーします。 たとえば、Web アプリが 500 応答を返すたびアラートが必要です。 クエリを使用して、レコードの種類数としきい値を 1 に設定したログ アラートを作成します。要求| <i>、resultCode == &quot;500&quot;</i></li>
   <li><b><u>メトリック測定</u></b>: Application インサイト のクエリによって集計された数値のパターンに基づいてアラートをトリガーします。 たとえば、リージョン間の Application インサイト での ping/可用性テストの期間が、15 分の 2 つの連続した期間で平均非常に高い場合にアラートを生成します。 2 つ以上の連続違反に対するトリガーと、クエリを使用した AggregateValue での集計を使用して、種類メトリック測定のログ アラートを作成します。 <i>availabilityResults | summarize AggregatedValue = avg(duration) by bin(timestamp, 15m)</i></li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/090fc8d7-b53c-4a69-8074-14f01d41cf39.png"><img alt="Alerts - Log Alerts - Application Insights (003)" border="0" height="889" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3d252db9-78f3-4012-896a-4391064f4d5c.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="アラート - ログ アラート - アプリケーション インサイト (003)" width="486"></a></p>


  <p><br clear="all">

  ログ アラートの詳細については、ログ アラートに<a href="https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitor-alerts-unified-log">関するMicrosoft Azureドキュメントを参照してください</a>。 ここでは、アプリケーションのログ アラート (プレビュー) の使用を開始するのに役立つ短いビデオを示します。</p>


  <p style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Blogs/Azure/Log-Alerts-for-Application-Insights-Preview/player" width="960"></iframe></p>


  <h6>Application インサイト のログ アラートと新しいアラート エクスペリエンスはどちらもプレビュー中であり、現在からすべてのリージョンにスケジュールされた方法で展開されます。 ご意見をお寄せください。メールをお送りください。 <a href="mailto:azurealertsfeedback@microsoft.com">azurealertsfeedback@microsoft.com</a></h6>
