### YamlMime:Yaml
ms.openlocfilehash: a92fddbaa8bdd695be8c72f892ca1921000ff337
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909699"
Slug: making-azure-the-best-place-for-all-your-applications-and-data
Title: すべてのアプリケーションとデータに対して Azure を最適な場所にする
Summary: クラウド、データ、AI の confluence は、かつてない変化を推進しています。 データを利用して画期的なアクションやエクスペリエンスに変えることができるのは、今日のイノベーションの基礎です...
Content: >-
  <p>クラウド、データ、AI の confluence は、かつてない変化を推進しています。 データを活用して画期的なアクションやエクスペリエンスに変えることができることは、今日のイノベーションの基礎となります。 組織はクラウドテクノロジを使用して、アプリケーションとデータをクラウドに移行するビジネス &mdash; を推進するイノベーションを促進することが、この戦略の重要な取り組みです。<br>

  &nbsp;<br>

  Microsoft は、すべてのアプリケーションとデータについて、ハイブリッドクラウド向けに最適化された一貫性のあるグローバルプラットフォームを提供します。 Microsoft では、一貫性のあるハイブリッドクラウド環境を柔軟に維持しながら、移行と最新化のオプションを豊富に提供しています。 この一貫性により、さまざまなスキルセット、システム、ツールを保持する必要がなくなり、データから分析情報を抽出してイノベーションを促進するという複雑さを避けることができます。</p>


  <p>現在、お客様の SQL Server とオープンソースアプリケーションを Azure に移行することにより、選択と ROI を大幅に拡大する投資を発表しています。 SQL Server のお客様は、 <a href="https://azure.microsoft.com/en-us/blog/migrate-your-databases-to-a-fully-managed-service-with-azure-sql-database-managed-instance/" target="_blank"><strong>SQL Database Azure ハイブリッド特典 Managed Instance のプレビュー</strong></a>を試すことができます。 SQL Server ライセンス特典<a href="https://azure.microsoft.com/en-us/pricing/hybrid-benefit/" target="_blank"><strong>につい</strong></a>ては、お客様が最大 30% *<strong> </strong>を節約でき、 <a href="https://azure.microsoft.com/en-us/services/database-migration/" target="_blank"><strong>Azure Database Migration Service の Managed Instance プレビューを</strong></a>ご利用いただけます。 さらに、 <a href="https://azure.microsoft.com/en-us/blog/public-preview-of-java-on-app-service-built-in-support-for-tomcat-and-openjdk/" target="_blank"><strong>Azure App Service での Apache Tomcat &reg; サポート</strong></a><strong>のプレビュー</strong>と、今後数週間にわたって<strong>azure Database for</strong> <a href="https://azure.microsoft.com/en-us/services/mysql/" target="_blank"><strong>MySQL</strong></a> <strong>と</strong> <a href="https://azure.microsoft.com/en-us/services/postgresql/" target="_blank"><strong>PostgreSQL</strong></a>の一般提供が開始されたことをお知らせします。これにより、オープンソースのアプリケーションを azure に簡単に導入できるようになります。</p>


  <h2>SQL Server ワークロードの移行</h2>


  <p><strong>Azure SQL Database、Managed Instance</strong>の新しいデプロイオプションを使用して、アプリケーションを変更せずに SQL Server アプリケーションを Azure にシームレスに移行することができます。 Managed Instance には、SQLAgent、dbmail、Change Data Capture などの機能を含む既存の SQL Server デプロイとの完全なエンジンの互換性が備わっています。これには、いくつかの名前を付け、生産性の高い SQL Database サービスを組み込むことができます。 制限付きプレビューに参加しているお客様は、市場で利用可能なその他のオプション (完全に管理されたサービス、組み込みの HA、およびデータベースのアラームシステムとして機能する脅威の検出など) を含む、その他のオプションによって提供される差別化された値を Azure SQL Database ます。</p>


  <p>SQL Database Managed Instance の起動によって、 <strong>Azure ハイブリッド特典</strong>プログラムも拡張して SQL Server のサポートが追加されます。 アクティブなソフトウェアアシュアランス付きのオンプレミスの SQL Server ライセンスを Managed Instance に移行できるようになりました。また、SQL Server Integration Services ライセンスについては、料金の割引のために Azure Data Factory していただき、最大 30% * 節約できます。</p>


  <p>ピボットテクノロジソリューションなどの Managed Instance プレビューのお客様は、完全に管理されたデータベースサービスとライセンス割引の組み合わせに支持ます。 <em>&ldquo;SQL Managed Instance は、お探しの楽しいメディアです。SQL Server のパワーと互換性が必要でしたが、24時間365日体制で vm を実行した場合の管理オーバーヘッドとコストは発生しません。 Robert shurbet、シニアソフトウェア開発 Professional、ピボットテクノロジソリューションについて説明します。 &ldquo;この機能を利用して管理を容易にするだけで &rsquo; なく、Azure ハイブリッド特典を使用することもできます。これにより、既存の SQL Server ライセンスをソフトウェアアシュアランスを通じて使用できるようになります。アプリケーションの開発、デプロイ、管理は、Azure と SQL Managed Instance によって、はるかに簡単でコストがかかります。&rdquo;</em></p>


  <p>最後に、データベースの移行を効率化して Managed Instance を SQL Database するために、 <a href="https://azure.microsoft.com/en-us/campaigns/database-migration/" target="_blank"><strong>Azure Database Migration Service</strong></a>を拡張して SQL Database Managed Instance をサポートすることも期待しています。 この Azure Database Migration Service は、オンプレミスの SQL Server を Azure SQL Database に移行するためのシームレスなエンドツーエンドのソリューションとして設計されており、データベースサポートのロードマップ全体の開始として機能します。 完全なサービスロードマップでは、MySQL および PostgreSQL データベースの Azure Database for MySQL と Azure Database for PostgreSQL への今後のサポートを含む、さまざまなデータベースのソースと変換先 &mdash; の間でのデータベースの移行がサポートされます。</p>


  <h2>オープンソースワークロードの移行</h2>


  <p>すべてのアプリケーションとデータを Azure に最適な場所にするには、オープンソースのワークロードを完全にサポートする必要があります。 現時点では、Apache Tomcat と OpenJDK 8 <a href="https://azure.microsoft.com/en-us/blog/public-preview-of-java-on-app-service-built-in-support-for-tomcat-and-openjdk/" target="_blank">の組み込みサポート</a> のプレビューを Azure App Service からご紹介します。これにより、Java 開発者は、web アプリケーションと Api を Azure &rsquo; 市場をリードする PaaS に簡単にデプロイできます。 .Jar ファイルまたは war ファイルを App Service &rsquo; に持ち込むだけで、容量のプロビジョニング、サーバーのメンテナンス、負荷分散が行われます。 Jetty やさまざまなバージョンの JRE など、他の優先イメージがある場合は、<a href="https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image" target="_blank">独自の Docker イメージを作成</a>して、コンテナーレジストリをポイントすることによって App Service にデプロイすることもできます。 &nbsp;java アプリケーションがデプロイされたら、 <a href="https://azure.microsoft.com/en-us/downloads/" target="_blank">azure SDK for java</a>で拡張して、Storage、Azure Database for MySQL、Azure Database for PostgreSQL などのさまざまな azure サービスと連携させることができます。 </p>


  <p>また、今後数週間の間、 <strong>Azure database services for </strong> <a href="https://azure.microsoft.com/en-us/services/mysql/" target="_blank"><strong>MySQL</strong></a> <strong>および</strong> <a href="https://azure.microsoft.com/en-us/services/postgresql/" target="_blank"><strong>PostgreSQL</strong></a>を<strong>一般</strong>公開されています。 これらのプレビューサービスは、昨年 preview を開始した後、大幅な成長を遂げてきました。開発者は、データの可用性、保護、および規模に関する複雑さを解消するシンプルで完全に管理されたサービスプラットフォームでデータベースを選択する必要があります。 Azure database services for MySQL および PostgreSQL は、Azure 上のこれらのサービスを使用して、最もシンプルな移行と最速の開発を実現するためのコミュニティバージョンを提供します。 Azure でサポートされているオープンソースのサービスにより、GeekWire のような企業は、テクノロジスタックや開発者の文化を損なうことなく、ワークロードをクラウドに移行することが非常に簡単になります。</p>


  <p><a href="https://customers.microsoft.com/en-us/story/geekwire" target="_blank">GeekWire</a>開発者である加山 Lisota によれば、 <em>[GeekWire] web サイトはそのようなものです。 &ldquo;サイトの信頼性 (重要な場合)。サイトでは、トラフィックの増加が5倍になること &rsquo; は珍しくありません。サイトを Azure に移行し、このサイトをさまざまな Azure サービスでホストして、非常に予測できないトラフィック急増に対応しています。GeekWire は WordPress 上で実行され、Nginx と PHP &hellip; を実行しています。主要な意思決定者 (Azure への移行) は Microsoft が Azure Database for MySQL 開始したときに行われたものであり、データベースレイヤーをスタック全体と一緒に実行することもできました。 &rdquo; </em></p>


  <h2>Azure は、お客様のアプリケーションとデータに最適な場所です</h2>


  <p>現在 &rsquo; の発表は、すべてのアプリ、データ、およびインフラストラクチャのニーズに合わせて Azure を最適な場所にするためのもう1つの手順です。 2月28日に、 <a href="https://azure.microsoft.com/en-us/blog/confidently-plan-your-cloud-migration-azure-migrate-is-now-generally-available/" target="_blank">Azure Migrate の一般提供</a>も発表しました。 Azure Migrate は、ワークロードの準備に関する規範的なガイダンス、適切なサイズのリソース、コストの見積もりなど、豊富な洞察を持つクラウド移行プロジェクトを自信を持って計画するのに役立ちます。 私たちのビジョンは、オンプレミスのワークロードをすべて検出して評価するための1つの場所を Azure Migrate することです。&nbsp;&nbsp;</p>


  <p>これらの投資によって、オンプレミスとクラウドの間のプラットフォームの一貫性が向上し、豊富なオープンソースのアプリケーションフレームワークとデータベースのサポートが提供され、Microsoft のお客様のコスト削減が拡大します。 お &rsquo; 客様の Azure への移行を可能な限りスムーズに行うと同時に、迅速なイノベーションを実現する方法を連続的なています。 私たちの目標は、今日 &rsquo; の革新者がアプリケーションとデータの力を最大限に活用し、世界を強化する可能性を高めるテクノロジを構築することです。</p>


  <h2>今すぐ開始しましょう!</h2>


  <p>すばらしい新しいテクノロジをお試しください。 今すぐお試しいただき、フィードバックをお寄せください。</p>


  <ul>
      <li><a href="https://azure.microsoft.com/en-us/blog/migrate-your-databases-to-a-fully-managed-service-with-azure-sql-database-managed-instance/" target="_blank">SQL Database Managed Instance プレビュー</a>の詳細</li>
      <li><a href="https://azure.microsoft.com/en-us/services/database-migration/" target="_blank">Managed Instance の Azure Database Migration Service サポートをお試しください</a></li>
      <li><a href="https://azure.microsoft.com/en-us/pricing/hybrid-benefit/" target="_blank">SQL Server の Azure ハイブリッド特典を調べる</a></li>
      <li><a href="https://aka.ms/Glbs6q" target="_blank">Apache Tomcat の組み込みサポート Azure App Service 試す</a></li>
      <li><a href="https://azure.microsoft.com/en-us/services/mysql/" target="_blank">MySQL</a>および<a href="https://azure.microsoft.com/en-us/services/postgresql/" target="_blank">PostgreSQL</a>用の Azure database services をお試しください</li>
      <li><a href="https://azure.microsoft.com/en-us/blog/confidently-plan-your-cloud-migration-azure-migrate-is-now-generally-available/" target="_blank">Azure Migrate</a>を試す</li>
  </ul>


  <p><em>* 米国東部価格での Azure SQL DB の料金 Managed Instance 料金。割引は、全額 (ライセンス込み) と比較した場合に、基本料金として計算されます。上記の SA コストは、Open、NL を対象としています。SA の価格は EA 契約によって異なる場合があります。</em></p>
