### YamlMime:Yaml
ms.openlocfilehash: 4907ee3e5eb89d1dd297e4ce5a48ef169f9b317a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890169"
Slug: manage-app-service-sql-database-application-gateway-and-more-using-simpler-azure-management-libraries-for-java
Title: Azure App Service、SQL Database、その他の管理 - Azure Management Libraries for Java
Summary: Web アプリを作成する 1 つの Java ステートメント。 1 つのステートメントを作成SQL Serverステートメントを作成し、別のステートメントを作成SQL Database。 1 つのステートメントで、Application Gateway作成します。
Content: >-
  <p>Web アプリを作成する 1 つの <a href="https://azure.microsoft.com/en-us/services/app-service/web/">Java ステートメント</a>。 1 つのステートメントを作成SQL Serverステートメントを作成し、別の<a href="https://azure.microsoft.com/en-us/services/sql-database/">ステートメントを作成</a>SQL Database。 1 つのステートメントで、 <a href="https://azure.microsoft.com/en-us/services/application-gateway/">Application Gateway</a>作成します。</p>


  <p>Azure Management Libraries for Java のベータ 4 が利用可能になります。 ベータ 4 では、次の Azure サービスと機能のサポートが追加されています。</p>


  <table border="0" cellpadding="2" cellspacing="0" width="400">
      <tbody>
          <tr>
              <td valign="top" width="133">
              <p><strong>✓ </strong>App Service (Web Apps)</p>
              </td>
              <td valign="top" width="133">
              <p><strong>✓ </strong>SQL Database</p>
              </td>
              <td valign="top" width="133">
              <p><strong>✓ </strong>Application Gateway</p>
              </td>
          </tr>
          <tr>
              <td valign="top" width="133">
              <p><strong>✓ </strong>Traffic Manager</p>
              </td>
              <td valign="top" width="133">
              <p><strong>✓ </strong>DNS</p>
              </td>
              <td valign="top" width="133">
              <p><strong>✓ </strong>CDN</p>
              </td>
          </tr>
          <tr>
              <td valign="top" width="133">
              <p><strong>✓ </strong>Redis Cache</p>
              </td>
              <td valign="top" width="133">&nbsp;</td>
              <td valign="top" width="133">&nbsp;</td>
          </tr>
      </tbody>
  </table>


  <h4><a href="https://github.com/azure/azure-sdk-for-java">https://github.com/azure/azure-sdk-for-java</a></h4>


  <p>ベータ 4 を使用するには、Maven POM ファイル次のコードを追加します。</p>


  <pre class="prettyprint">

  &lt;dependency&gt;
      &lt;groupId&gt;com.microsoft.azure&lt;/groupId&gt;
      &lt;artifactId&gt;azure&lt;/artifactId&gt;
      &lt;version&gt;1.0.0-beta4.1&lt;/version&gt;
  &lt;/dependency&gt;

  </pre>


  <p>昨年、Java 用の新しい簡略化された Azure 管理ライブラリのプレビューを発表しました。 私たちの目標は、読みやすさと書き込み性のために最適化された、より高いレベルのオブジェクト指向 API を提供することで、開発者エクスペリエンスを向上させる方法です。 ライブラリを試して、役に立つフィードバックを提供していただきありがとうございます。</p>


  <h2>Web アプリの作成</h2>


  <p>define() create() &hellip; メソッド チェーンを使用して Web アプリ インスタンスを作成できます。</p>


  <pre class="prettyprint">

  WebApp webApp = azure.webApps()
      .define(appName)
      .withNewResourceGroup(rgName)
      .withNewAppServicePlan(planName)
      .withRegion(Region.US_WEST)
      .withPricingTier(AppServicePricingTier.STANDARD_S1)
      .create();
  </pre>


  <h2>SQL Database の作成</h2>


  <p>別の define() create() &hellip; SQLを使用して、サーバー インスタンスを作成できます。</p>


  <pre class="prettyprint">

  SqlServer sqlServer = azure.sqlServers().define(sqlServerName)
      .withRegion(Region.US_EAST)
      .withNewResourceGroup(rgName)
      .withAdministratorLogin(&quot;adminlogin123&quot;)
      .withAdministratorPassword(&quot;myS3cureP@ssword&quot;)
      .withNewFirewallRule(&quot;10.0.0.1&quot;)
      .withNewFirewallRule(&quot;10.2.0.1&quot;, &quot;10.2.0.10&quot;)
      .create();
  </pre>


  <p>次に、別の define() create() メソッド チェーンSQL使用して、データベース インスタンスに対して新しい&hellip;データベース インスタンスを作成できます。</p>


  <pre class="prettyprint">

  SqlDatabase database = sqlServer.databases().define(&quot;myNewDatabase&quot;)
       .create();</pre>

  <h2>Application Gateway を作成する</h2>


  <p>別の define() create() &hellip; メソッド チェーンを使用して、アプリケーション ゲートウェイ インスタンスを作成できます。</p>


  <pre class="prettyprint">

  ApplicationGateway applicationGateway = azure.applicationGateways().define(&quot;myFirstAppGateway&quot;)
      .withRegion(Region.US_EAST)
      .withExistingResourceGroup(resourceGroup)
      // Request routing rule for HTTP from public 80 to public 8080
      .defineRequestRoutingRule(&quot;HTTP-80-to-8080&quot;)
          .fromPublicFrontend()
          .fromFrontendHttpPort(80)
          .toBackendHttpPort(8080)
          .toBackendIpAddress(&quot;11.1.1.1&quot;)
          .toBackendIpAddress(&quot;11.1.1.2&quot;)
          .toBackendIpAddress(&quot;11.1.1.3&quot;)
          .toBackendIpAddress(&quot;11.1.1.4&quot;)
          .attach()
      .withExistingPublicIpAddress(publicIpAddress)
      .create();
  </pre>


  <h2>サンプル コード</h2>


  <p>Azure Virtual Machines、Virtual Machine Scale Sets、Storage、Networking、Resource Manager、SQL Database、App Service (Web Apps)、Key Vault、Redis、CDN、Batch の管理シナリオを示すサンプル コードが豊富に用意されています。</p>


  <table border="0" cellpadding="2" cellspacing="0" width="400">
      <tbody>
          <tr>
              <td valign="top" width="200">サービス</td>
              <td valign="top" width="200">管理シナリオ</td>
          </tr>
          <tr>
              <td valign="top" width="200">Virtual Machines</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/compute-java-manage-vm">仮想マシンの管理</a></li>
                  <li><a href="https://github.com/Azure-Samples/compute-java-manage-availability-sets">可用性セットの管理</a></li>
                  <li><a href="https://github.com/Azure-Samples/compute-java-list-vm-images">仮想マシン イメージの一覧表示</a></li>
                  <li><a href="https://github.com/Azure-Samples/compute-java-manage-virtual-machine-using-vm-extensions">VM 拡張機能を使用して仮想マシンを管理する</a></li>
                  <li><a href="https://github.com/Azure-Samples/compute-java-create-virtual-machines-from-generalized-image-or-specialized-vhd">一般化されたイメージまたは特殊化された VHD から仮想マシンを作成する</a></li>
                  <li><a href="https://github.com/Azure-Samples/compute-java-list-vm-extension-images">仮想マシン拡張機能イメージの一覧表示</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">
              <p>Virtual Machines - 並列実行</p>
              </td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/azure-samples/compute-java-manage-virtual-machines-in-parallel">複数の仮想マシンを並列で作成する</a></li>
                  <li><a href="https://github.com/azure-samples/compute-java-manage-virtual-machines-with-network-in-parallel">ネットワークを並列に使用して複数の仮想マシンを作成する</a></li>
                  <li><a href="https://github.com/azure-samples/compute-java-create-virtual-machines-across-regions-in-parallel">リージョン間で複数の仮想マシンを並列で作成する</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">Virtual Machine Scale Sets</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/compute-java-manage-virtual-machine-scale-sets">仮想マシン スケール セットの管理 (インターネットに接続するロード バランサーの背後)</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">Storage</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/storage-java-manage-storage-accounts">ストレージ アカウントを管理する</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">ネットワーク</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/network-java-manage-virtual-network">仮想ネットワークの管理</a></li>
                  <li><a href="https://github.com/Azure-Samples/network-java-manage-network-interface">ネットワーク インターフェイスを管理する</a></li>
                  <li><a href="https://github.com/Azure-Samples/network-java-manage-network-security-group">ネットワーク セキュリティ グループの管理</a></li>
                  <li><a href="https://github.com/Azure-Samples/network-java-manage-ip-address">IP アドレスの管理</a></li>
                  <li><a href="https://github.com/Azure-Samples/network-java-manage-internet-facing-load-balancers">インターネットに接続するロード バランサーを管理する</a></li>
                  <li><a href="https://github.com/Azure-Samples/network-java-manage-internal-load-balancers">内部ロード バランサーを管理する</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">ネットワーク - DNS</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/dns-java-host-and-manage-your-domains">ドメインのホストと管理</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">Traffic Manager</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/traffic-manager-java-manage-profiles">Traffic Manager プロファイルを管理する</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">Application Gateway</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/application-gateway-java-manage-simple-application-gateways">アプリケーション ゲートウェイの管理</a></li>
                  <li><a href="https://github.com/Azure-Samples/application-gateway-java-manage-application-gateways">バックエンド プールを使用してアプリケーション ゲートウェイを管理する</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">SQL Database</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/sql-database-java-manage-db">データベースSQL管理する</a></li>
                  <li><a href="https://github.com/Azure-Samples/sql-database-java-manage-sql-dbs-in-elastic-pool">エラスティック プールで SQL データベースを管理する</a></li>
                  <li><a href="https://github.com/Azure-Samples/sql-database-java-manage-firewalls-for-sql-databases">データベースのファイアウォールSQL管理する</a></li>
                  <li><a href="https://github.com/Azure-Samples/sql-database-java-manage-sql-databases-across-regions">リージョン間SQLデータベースを管理する</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">Redis Cache</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/redis-java-manage-cache">管理Redis Cache</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">App Service - Web Apps</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/app-service-java-manage-web-apps">Web アプリの管理</a></li>
                  <li><a href="https://github.com/Azure-Samples/app-service-java-manage-web-apps-with-custom-domains">カスタム ドメインを使用して Web アプリを管理する</a></li>
                  <li><a href="https://github.com/Azure-Samples/app-service-java-configure-deployment-sources-for-web-apps">Web アプリのデプロイ ソースを構成する</a></li>
                  <li><a href="https://github.com/Azure-Samples/app-service-java-manage-staging-and-production-slots-for-web-apps">Web アプリのステージング スロットと運用スロットを管理する</a></li>
                  <li><a href="https://github.com/Azure-Samples/app-service-java-scale-web-apps">Web アプリのスケーリング</a></li>
                  <li><a href="https://github.com/Azure-Samples/app-service-java-manage-storage-connections-for-web-apps">Web アプリのストレージ接続を管理する</a></li>
                  <li><a href="https://github.com/Azure-Samples/app-service-java-manage-data-connections-for-web-apps">Web アプリのデータ接続 (SQL Redis Cache など) を管理する</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">リソース グループ</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/resources-java-manage-resource-group">リソース グループの管理</a></li>
                  <li><a href="https://github.com/Azure-Samples/resources-java-manage-resource">リソースの管理</a></li>
                  <li><a href="https://github.com/Azure-Samples/resources-java-deploy-using-arm-template">ARM テンプレートを使ってリソースをデプロイする</a></li>
                  <li><a href="https://github.com/Azure-Samples/resources-java-deploy-using-arm-template-with-progress">ARM テンプレートを使ってリソースをデプロイする (進行状況表示付き)</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">Key Vault</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/key-vault-java-manage-key-vaults">キー コンテナーを管理する</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">CDN</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/cdn-java-manage-cdn">CDN の管理</a></li>
              </ul>
              </td>
          </tr>
          <tr>
              <td valign="top" width="200">Batch</td>
              <td valign="top" width="200">
              <ul>
                  <li><a href="https://github.com/Azure-Samples/batch-java-manage-batch-accounts">バッチ アカウントの管理</a></li>
              </ul>
              </td>
          </tr>
      </tbody>
  </table>


  <h2>ぜひお試しください</h2>


  <p>上記のサンプルを実行するか、自分のサンプル GitHub<a href="https://github.com/Azure/azure-sdk-for-java">できます</a>。 お試しの上、(以下の電子メールまたはコメントを使用して) お考えの <a href="mailto:java@microsoft.com?subject=Feedback%20on%20Azure%20Management%20Libraries%20for%20Java">方</a> をお知らせください。特に -</p>


  <ul>
      <li>Java 用の新しい管理ライブラリの使いやすさと有効性。</li>
      <li>間もなくサポートされる予定の Azure サービスは何ですか?</li>
      <li>サンプル コードとして示す必要があるその他のシナリオは何ですか?</li>
  </ul>


  <p>今後数週間で、より多くの Azure サービスのサポートを追加し、API に最後のタッチを適用する予定です。</p>


  <p>Azure 上の Java に関する多くの追加情報については、 を参照してください <a href="https://azure.com/java">https://azure.com/java</a>。</p>
