### YamlMime:Yaml
ms.openlocfilehash: 7a383f628e63d2bd6b43f1d7dec6cf7636d48c0e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893920"
Slug: manage-app-service-sql-database-application-gateway-and-more-using-simpler-azure-management-libraries-for-net
Title: .net 用 Azure 管理ライブラリの App Service、SQL Database などの管理
Summary: 1つの C# ステートメントで Web アプリを作成します。 1つのステートメントで SQL Server を作成し、別のステートメントで SQL Database を作成します。 1つのステートメントで Application Gateway を作成します。
Content: >-
  <p>1つの C# ステートメントで <a href="https://azure.microsoft.com/en-us/services/app-service/web/">Web アプリ</a>を作成します。 1つのステートメントで SQL Server を作成し、別のステートメントで<a href="https://azure.microsoft.com/en-us/services/sql-database/">SQL Database</a>を作成します。 1つのステートメントで <a href="https://azure.microsoft.com/en-us/services/application-gateway/">Application Gateway</a>を作成します。</p>


  <p>.NET 用 Azure 管理ライブラリのベータ4が利用可能になりました。 Beta 4 では、次の Azure サービスと機能のサポートが追加されています。</p>


  <table border="0" cellpadding="2" cellspacing="0" width="400">
   <tbody>
    <tr>
     <td valign="top" width="133">
     <p><strong>✓ </strong>App Service (Web Apps)</p>
     </td>
     <td valign="top" width="133">
     <p><strong>✓ </strong>SQL Database</p>
     </td>
     <td valign="top" width="133">
     <p><strong>✓ &nbsp; </strong> Application Gateway</p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="133">
     <p><strong>✓ &nbsp; </strong>Traffic Manager</p>
     </td>
     <td valign="top" width="133">
     <p><strong>✓ &nbsp; </strong>DNS</p>
     </td>
     <td valign="top" width="133">
     <p><strong>✓ &nbsp; </strong>CDN</p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="133">
     <p><strong>✓ &nbsp; </strong>Redis Cache</p>
     </td>
     <td valign="top" width="133">&nbsp;</td>
     <td valign="top" width="133">&nbsp;</td>
    </tr>
   </tbody>
  </table>


  <h2><a href="https://github.com/Azure/azure-sdk-for-net/tree/Fluent" title="https://github.com/Azure/azure-sdk-for-net/tree/Fluent">https://github.com/Azure/azure-sdk-for-net/tree/Fluent</a></h2>


  <p>ベータ4は次のものからダウンロードできます。</p>


  <p>&nbsp;<a href="https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/"><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Microsoft.Azure.Management.Fluent.svg?style=flat-square&amp;label=nuget"></a></p>


  <p>昨年、.NET 用の新しい簡素化された Azure 管理ライブラリのプレビューを発表しました。 この目標は、読みやすさと書き込み機能のために最適化された、より高度なオブジェクト指向 API を提供することで、開発者のエクスペリエンスを向上させることです。 これらのライブラリは、下位レベルの要求-応答スタイルの <a href="https://github.com/Azure/azure-sdk-for-net/tree/AutoRest">自動生成</a> されたクライアント上に構築されており、 <a href="https://github.com/Azure/azure-sdk-for-net/tree/AutoRest">自動生成</a>されたクライアントとサイドバイサイドで実行できます。 ライブラリをお試しいただき、ありがとうございます。</p>


  <h2>Web アプリの作成</h2>


  <p>Define () &hellip; create () メソッドチェーンを使用して、Web アプリインスタンスを作成できます。</p>


  <pre class="prettyprint">

  var webApp = azure.WebApps()
      .Define(appName)
      .WithNewResourceGroup(rgName)
      .WithNewAppServicePlan(planName)
      .WithRegion(Region.US_WEST)
      .WithPricingTier(AppServicePricingTier.STANDARD_S1)
      .Create();</pre>

  <h2>SQL Database の作成</h2>


  <p>別の define () &hellip; create () メソッドチェーンを使用して、SQL サーバーインスタンスを作成できます。</p>


  <pre class="prettyprint">

  var sqlServer = azure.SqlServers.Define(sqlServerName)
      .WithRegion(Region.US_EAST)
      .WithNewResourceGroup(rgName)
      .WithAdministratorLogin(administratorLogin)
      .WithAdministratorPassword(administratorPassword)
      .WithNewFirewallRule(firewallRuleIpAddress)
      .WithNewFirewallRule(firewallRuleStartIpAddress, firewallRuleEndIpAddress)
      .Create();</pre>

  <p>次に、別の define () &hellip; create () メソッドチェーンを使用して、SQL データベースインスタンスを作成できます。</p>


  <pre class="prettyprint">

  var database = sqlServer.Databases.Define(databaseName)
      .Create();</pre>

  <h2>Application Gateway を作成する</h2>


  <p>Application gateway インスタンスを作成するには、別の define () &hellip; create () メソッドチェーンを使用します。</p>


  <pre class="prettyprint">

  var applicationGateway = azure.ApplicationGateways().Define(&quot;myFirstAppGateway&quot;)
      .WithRegion(Region.US_EAST)
      .WithExistingResourceGroup(resourceGroup)
      // Request routing rule for HTTP from public 80 to public 8080
      .DefineRequestRoutingRule(&quot;HTTP-80-to-8080&quot;)
          .FromPublicFrontend()
          .FromFrontendHttpPort(80)
          .ToBackendHttpPort(8080)
          .ToBackendIpAddress(&quot;11.1.1.1&quot;)
          .ToBackendIpAddress(&quot;11.1.1.2&quot;)
          .ToBackendIpAddress(&quot;11.1.1.3&quot;)
          .ToBackendIpAddress(&quot;11.1.1.4&quot;)
          .Attach()
      .WithExistingPublicIpAddress(publicIpAddress)
      .Create();</pre>

  <h2>サンプル コード</h2>


  <p>Azure Virtual Machines、Virtual Machine Scale Sets、Storage、ネットワーク、Resource Manager、SQL Database、App Service (Web Apps)、Key Vault、Redis、CDN および Batch の管理シナリオを示すサンプルコードが多数用意されています。</p>


  <table border="0" cellpadding="2" cellspacing="0" width="400">
   <tbody>
    <tr>
     <td valign="top" width="200">サービス</td>
     <td valign="top" width="200">管理シナリオ</td>
    </tr>
    <tr>
     <td valign="top" width="200">Virtual Machines</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/compute-dotnet-manage-vm">仮想マシンの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/compute-dotnet-manage-availability-sets">可用性セットの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/compute-dotnet-list-vm-images">仮想マシンイメージの一覧表示</a></li>
      <li><a href="https://github.com/Azure-Samples/compute-dotnet-manage-virtual-machine-using-vm-extensions">VM 拡張機能を使用して仮想マシンを管理する</a></li>
      <li><a href="https://github.com/Azure-Samples/compute-dotnet-create-virtual-machines-from-generalized-image-or-specialized-vhd">一般化されたイメージまたは特殊化された VHD から仮想マシンを作成する</a></li>
      <li><a href="https://github.com/Azure-Samples/compute-dotnet-list-vm-extension-images">仮想マシン拡張機能イメージの一覧表示</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">
     <p>Virtual Machines-並列実行</p>
     </td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/azure-samples/compute-dotnet-manage-virtual-machines-in-parallel">複数の仮想マシンを並行して作成する</a></li>
      <li><a href="https://github.com/azure-samples/compute-dotnet-manage-virtual-machines-with-network-in-parallel">ネットワークを使用して複数の仮想マシンを同時に作成する</a></li>
      <li><a href="https://github.com/azure-samples/compute-dotnet-create-virtual-machines-across-regions-in-parallel">リージョン間で複数の仮想マシンを並行して作成する</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">Virtual Machine Scale Sets</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/compute-dotnet-manage-virtual-machine-scale-sets">仮想マシンスケールセットの管理 (インターネットに接続するロードバランサーの背後)</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">Storage</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/storage-dotnet-manage-storage-accounts">ストレージ アカウントを管理する</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">ネットワーク</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/network-dotnet-manage-virtual-network">仮想ネットワークの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/network-dotnet-manage-network-interface">ネットワークインターフェイスの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/network-dotnet-manage-network-security-group">ネットワークセキュリティグループの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/network-dotnet-manage-ip-address">IP アドレスの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/network-dotnet-manage-internet-facing-load-balancers">インターネットに接続するロードバランサーを管理する</a></li>
      <li><a href="https://github.com/Azure-Samples/network-dotnet-manage-internal-load-balancers">内部ロードバランサーを管理する</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">ネットワーク-DNS</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/dns-dotnet-host-and-manage-your-domains">ドメインのホストと管理</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">Traffic Manager</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/traffic-manager-dotnet-manage-profiles">Traffic manager プロファイルの管理</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">Application Gateway</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/application-gateway-dotnet-manage-simple-application-gateways">アプリケーションゲートウェイの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/application-gateway-dotnet-manage-application-gateways">バックエンドプールを使用したアプリケーションゲートウェイの管理</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">SQL Database</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/sql-database-dotnet-manage-db">SQL データベースの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/sql-database-dotnet-manage-sql-dbs-in-elastic-pool">エラスティック プールで SQL データベースを管理する</a></li>
      <li><a href="https://github.com/Azure-Samples/sql-database-dotnet-manage-firewalls-for-sql-databases">SQL データベースのファイアウォールを管理する</a></li>
      <li><a href="https://github.com/Azure-Samples/sql-database-dotnet-manage-sql-databases-across-regions">リージョン間で SQL データベースを管理する</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">Redis Cache</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/redis-cache-dotnet-manage-cache">Redis Cache の管理</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">App Service - Web Apps</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/app-service-dotnet-manage-web-apps">Web アプリを管理する</a></li>
      <li><a href="https://github.com/Azure-Samples/app-service-dotnet-manage-web-apps-with-custom-domains">カスタムドメインを使用した Web アプリの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/app-service-dotnet-configure-deployment-sources-for-web-apps">Web アプリのデプロイソースを構成する</a></li>
      <li><a href="https://github.com/Azure-Samples/app-service-dotnet-manage-staging-and-production-slots-for-web-apps">Web アプリのステージングおよび運用スロットを管理する</a></li>
      <li><a href="https://github.com/Azure-Samples/app-service-dotnet-scale-web-apps">Web アプリのスケール</a></li>
      <li><a href="https://github.com/Azure-Samples/app-service-dotnet-manage-storage-connections-for-web-apps">Web アプリのストレージ接続の管理</a></li>
      <li><a href="https://github.com/Azure-Samples/app-service-dotnet-manage-data-connections-for-web-apps">Web アプリのデータ接続 (SQL データベース、Redis cache など) を管理する</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">リソース グループ</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/resources-dotnet-manage-resource-group">リソース グループの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/resources-dotnet-manage-resource">リソースの管理</a></li>
      <li><a href="https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template">ARM テンプレートを使ってリソースをデプロイする</a></li>
      <li><a href="https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template-with-progress">ARM テンプレートを使ってリソースをデプロイする (進行状況表示付き)</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">Key Vault</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/key-vault-dotnet-manage-key-vaults">キーコンテナーの管理</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">CDN</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/cdn-dotnet-manage-cdn">CDNs の管理</a></li>
     </ul>
     </td>
    </tr>
    <tr>
     <td valign="top" width="200">Batch</td>
     <td valign="top" width="200">
     <ul>
      <li><a href="https://github.com/Azure-Samples/batch-dotnet-manage-batch-accounts">Batch アカウントの管理</a></li>
     </ul>
     </td>
    </tr>
   </tbody>
  </table>


  <h2>ぜひお試しください</h2>


  <p>上記のサンプルを実行するか、 <a href="https://github.com/Azure/azure-sdk-for-net/tree/Fluent">GitHub リポジトリ</a>に直接進むことができます。 ぜひ試してみてください (以下の <a href="mailto:az-libs-for-net@microsoft.com">電子メール</a> またはコメントを使用)。特に</p>


  <ul>
   <li>.NET 用の新しい管理ライブラリの使いやすさと有効性。</li>
   <li>近日中にサポート対象となる Azure サービスは何ですか?</li>
   <li>サンプルコードとして、どのようなシナリオを追加する必要がありますか。</li>
  </ul>


  <p>今後数週間で、さらに多くの Azure サービスのサポートを追加し、API に仕上げを適用する予定です。</p>
