### YamlMime:Yaml
ms.openlocfilehash: 4c95bd0341fed4aee37016837be6114264f5ee43
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889429"
Slug: microsoft-creates-industry-standards-for-datacenter-hardware-storage-and-security
Title: Microsoft は、データセンターのハードウェアとセキュリティの業界標準を作成します
Summary: 今日は、Open Compute Project (OCP) の米国サミット2018をサン Denali でお話ししています。ここでは Project、ソリッドステートデバイス (SSD) ストレージの次世代仕様を発表しています。 ...
Content: >-
  <p>&rsquo;現在のところ、Open Compute Project (OCP) の米国サミット2018をサン阿部でお話ししています。ここでは、ソリッドステートデバイス (SSD) ストレージ Project Denali の次世代仕様を発表します。 &rsquo;また、Project cer/us についても説明しました。これは、セキュリティ保護の重要なコンポーネントであり、サーバーハードウェアからの保護、検出、およびプラットフォームファームウェアに対する攻撃からの回復を提供します。 ストレージとセキュリティはどちらも、ハードウェアイノベーションを実現するための次のフロンティアであり、現在 &rsquo; 、これらの主要な分野における最新の進歩を、将来のクラウドの将来的な業界に向けて強調しています。</p>


  <h2>クラウド SSD ストレージの新しい標準</h2>


  <p>Storage パラダイムはオンプレミスで適切に実行されていましたが、クラウドベースのモデルに必要なパフォーマンスとコストの効率を向上させるためのイノベーションになり &rsquo; ました。 このため、 &rsquo; クラウドベースのワークロードを対象とする flash storage の新しい標準を定義するように設定し直して &rsquo; 、Project Denali が表示されるようにしました。ここ &rsquo; では、cnex Labs を使用して再構築します。 基本的に、Project Denali は、ソフトウェア定義データレイアウトとメディア管理の機能を無効にすることで、SSD ファームウェアインターフェイスを標準化します。 Project Denali を使用すると、お客様はより高いレベルのパフォーマンスを実現しつつ、クラウドスケールのコスト削減に関する経済性を活用できます。</p>


  <p>Project Denali は、標準インターフェイスにおける SSD とそのホストのロールを定義するオープンチャネルの標準化と進化です。 メディア管理、エラー修正、フラッシュ生成に固有の無効なブロックとその他の機能のマッピングは、ホストがランダムな書き込みを受信し、順次書き込みのストリームを送信し、アドレスマップを保持し、ガベージコレクションを実行します。 Denali を使用すると、ホスト側での FPGAs またはマイクロコントローラーのサポートが可能になります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/08daac0d-48ac-43aa-82e4-0684566a1c6d.png"><img alt="Flash storage" border="0" height="459" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fd5f521e-2047-4bfc-8721-2b489e03f6c6.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="フラッシュストレージ" width="816"></a></p>


  <p>これにより、最初は真のクラウドであるアーキテクチャフレームワークが提供されます。 提案されているモジュールアーキテクチャでは、アプリケーションと SSD デバイス間の統合によって、新しい非揮発性メディアの導入 (NAND と Storage クラスのメモリの両方) と、ワークロードのパフォーマンスが向上します。 &nbsp;また、Ssd でソフトウェアによるデータ配置を使用して、従来のモノリシックストレージモデルを disaggregate するモデルも定義します。 データ配置の管理が、NAND 管理アルゴリズムから分離されている場合、非揮発性ストレージメディアは、イノベーションのために独自のスケジュールに従って解放されます。 Project Denali を使用すると、ハードウェア企業はよりシンプルで複雑なハードウェアを構築できます。これにより、コストの削減、市場投入までの時間の短縮、ワークロード固有のチューニングが可能になり、新しい NAND およびメモリテクノロジの迅速な開発が可能になります。</p>


  <p>一連のエコシステムパートナーとの成熟度 Project Denali した後、Project Denali 標準を業界に貢献して、より広範な導入を促進することを目的としています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7a66a35e-a3b4-4285-9f5a-95f72c1ae79c.png"><img alt="Project Denali" border="0" height="459" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4062da79-feb9-4b9e-b159-47f7c38a99cb.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Project Denali" width="816"></a></p>


  <h2>ハードウェアのセキュリティを有効にする</h2>


  <p>Microsoft Azure は、クラウドのセキュリティとプライバシーの最先端を表します。 Microsoft はサイバーセキュリティに10億ドルを費やし、その投資の多くは Azure を信頼されたクラウドプラットフォームにするための根本的な改善に移ります。 このようなセキュリティに重点を置いているので、ハードウェアのセキュリティに関して業界標準のニーズを認識しています。 Microsoft &rsquo; Project cer/us は、プラットフォームセキュリティのためにオープンな業界標準を作成することを目的として開発されています。</p>


  <p>Project cer/us は、コンピュータープラットフォーム上のすべてのハードウェアデバイスに対して自身で信頼のルートを確立し、次のプラットフォームのファームウェアを防御するのに役立つセキュリティ共同プロセッサです。</p>


  <ul>
   <li>管理特権を持つ悪意のある内部関係者またはハードウェアへのアクセス</li>
   <li>オペレーティングシステム、アプリケーション、またはハイパーバイザーでバグを悪用するハッカーとマルウェア</li>
   <li>サプライチェーン攻撃 (製造、組立、移送中)</li>
   <li>侵害されたファームウェアバイナリ</li>
  </ul>


  <p>Cer/us は、セキュリティで保護されたコードを実行する暗号マイクロコントローラーで構成されます。これにより、ホストからのアクセスを傍受して、(ファームウェアが格納されている) SPI バス経由でフラッシュできます これにより、システム内のすべてのファームウェアコンポーネントに対して、堅牢なプリブート、ブート時、およびランタイムの整合性が確保されます。</p>


  <p>この仕様は CPU および i/o アーキテクチャに依存せず、時間の経過と共にさまざまなベンダーの設計に簡単に統合できるように設計されているため、データセンターから IoT デバイスまで、業界全体にわたるすべてのプラットフォームの種類で、より安全なファームウェア実装を実現できます。 この仕様では、同じアーキテクチャ原則を使用してプラットフォームのセキュリティをすべての i/o 周辺機器に拡張できるように、階層的な信頼のルートもサポートしています。</p>


  <p>2017の後半で Project cerverge us が導入されたため、標準をサポートするエコシステムは成長を続けており &rsquo; 、コラボレーションと導入を促進するためにハードウェア実装をコミュニティに貢献することにもなります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8860a4b2-9df5-4020-869a-3183542792d1.png"><img alt="Project Ceberus" border="0" height="459" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3f849ad1-b2f3-4f34-a3ab-d9469c7c935d.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Project cea us" width="816"></a></p>


  <p>2015以来、 &rsquo; OCP コミュニティと連携するサーバーとデータセンターの Microsoft Azure 設計を共有し、データセンターのパフォーマンス、効率性、電力消費を向上させるイノベーションを活用するよう業界を支援しています。&nbsp;</p>


  <p>現在発表されている作業の詳細については、この<a href="https://azure.com/ocp" target="_blank">リンク</a>をご覧ください。または、Project Denali の技術情報の詳細については、<a href="https://azure.microsoft.com/en-us/blog/project-denali-to-define-flexible-ssds-for-cloud-scale-applications/" target="_blank">このブログを参照</a>してください。</p>
