### YamlMime:Yaml
ms.openlocfilehash: 00006e015b034dde6821393f50d517461d0cce56
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890689"
Slug: microsoft-government-cloud-application-center-connects-customers-with-windows-azure-partner-solutions
Title: Microsoft Government Cloud Application Center Azure パートナー ソリューションを使用してWindowsを接続する
Summary: クラウドへの移行を評価する州政府と自治体は、ビジネスに合った適切なクラウドベースのソリューションを持つパートナーとソリューションを見つけ出す中央の場所を持つ必要があります。
Content: <p>クラウドへの移行を評価する州政府と自治体は、ビジネス ニーズを満たす適切なクラウドベースのソリューションを持つパートナーとソリューションを見つけ出す中央の場所を持つ必要があります。&nbsp;このニーズを満たすために、公的部門チームは、政府機関のお客様に<a target="_blank" href="https://azure.microsoft.com/">、Windows Azure</a>&nbsp; プラットフォームなどの Microsoft クラウド コンピューティング テクノロジ上に構築されたパートナー アプリケーションをすばやく見つけて学習する一元的な場所を提供する Microsoft <a target="_blank" href="https://www.microsoft.com/industry/government/solutions/CloudApplications.aspx">Government クラウド</a> アプリケーション センターを発表しました。 パートナー、ソリューション、またはテクノロジで検索可能であり、お客様は互換性を評価し、連絡先情報やパートナー Web サイトへのリンクなどの追加情報を取得します。</p>  <p>Government Cloud Applications Center は、パートナーが Windows Azure のソリューションとサービス、および <a target="_blank" href="https://www.microsoft.com/industry/government/products/bpos/default.aspx">Business Productivity Online Suite (BPOS)</a> に基づく顧客を直接紹介する優良な場所を提供するパートナーにも優れています。 &nbsp;&nbsp;新しいパートナー ソリューションが頻繁に追加される場合は、頻繁に確認してください。</p>
