### YamlMime:Yaml
ms.openlocfilehash: 010bd0aa1455052d851cdf680ba0ba0882127ca9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909631"
Slug: microsoft-open-sources-data-accelerator-an-easy-to-configure-pipeline-for-streaming-at-scale
Title: Microsoft オープン ソースのデータ アクセラレータ。大規模なストリーミング用に構成しやすいパイプライン
Summary: 'データ パイプラインを初めて立ち上げると課題になる可能性があります。また、プロジェクトの最初に行う決定によって、最初のデプロイが展開された後の選択が長い間制限される可能性があります。多くの場合、必要なのは、ソリューション空間で使用可能なオプションと機能について学習して評価するプレイグラウンドです。 '
Content: >-
  <p><em>このブログ記事は、Microsoft のプリンシパル グループ エンジニアリング マネージャーである、1970 年 10 月に共同執筆しました。 &nbsp;</em></p>


  <p>データ パイプラインを初めて立ち上げると課題になる可能性があります。また、プロジェクトの最初に行う決定によって、最初のデプロイが展開された後の選択が長い間制限される可能性があります。多くの場合、必要なのは、ソリューション空間で使用可能なオプションと機能について学習して評価するプレイグラウンドです。 そのため、データ アクセラレータと呼ばれる内部 Microsoft プロジェクトがオープン ソース化されたと発表しました。<a href="https://github.com/Microsoft/Data-Accelerator" target="_blank"></a></p>


  <p><a href="https://github.com/Microsoft/Data-Accelerator" target="_blank">データ アクセラレータ</a> は、2017 年に Microsoft&rsquo; 開発者部門の大規模なデータ処理プロジェクトとして開始されました。最終的には、スケールと速度の理由から Apache Spark でストリーミングが開始されました。 現在、パイプラインは Microsoft 規模で動作します。</p>


  <p>より広範なコミュニティにとって価値があると考える理由の一部を次に示します。</p>


  <ul>
      <li><strong>高速Dev-Testループ:</strong> イベントは、クエリのローカル実行をサポートするためにサンプリングできます。これは、セミコロンが紛失した場合に 7 分後に失敗するために、ジョブをクラスターに送信する待機時間と遅延を短くします。</li>
      <li><strong>ローカル テストと検出のための 1 ボックスのデプロイ:</strong> プロトタイプにコミットする前に学習します。</li>
      <li><strong>デザイナーベースのルールとクエリの作成:</strong> コードを記述せずにエンドツーエンドの ETL パイプラインを立ち上げるか、詳細を詳しくはお読みください。</li>
      <li><strong>次の構文に追加</strong> されたタイム ウィンドウ、参照データ、出力SQL-Sparkします。構文を使用SQL-Sparkキーワード拡張を使用すると、これらの一般的なタスクの複雑性とエラーが発生しやすい管理を回避できます。</li>
  </ul>


  <p>Microsoft の開発者部門は、毎日<a href="https://github.com/Microsoft/Data-Accelerator" target="_blank"></a>、実稼働環境でデータ アクセラレータを使用しています。ツールチェーンは時間の流れる中で引き続き改善されますが、必要に応じてツールセットによってさらに多くのことが可能なことを認識しています。 このプロジェクトを開いて、データ アクセラレータの一部がさらに役 <a href="https://github.com/Microsoft/Data-Accelerator" target="_blank">に立つ場合</a> があります。</p>


  <p>データ アクセラレータのオープン ソーシングの詳細については <a href="https://github.com/Microsoft/Data-Accelerator" target="_blank">、</a> オープン ソースブログのお知らせ <a href="https://cloudblogs.microsoft.com/opensource/2019/04/16/microsoft-open-sources-data-accelerator-for-apache-spark" target="_blank">を参照してください</a>。</p>
