### YamlMime:Yaml
ms.openlocfilehash: 9f898b9a371e7cd67479a5283e02f977c0d2c849
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893425"
Slug: microsoft-introduces-steps-to-improve-internet-routing-security
Title: Microsoft では、インターネット ルーティング のセキュリティを向上させる手順を導入しています
Summary: 'インターネットは、ネットワーク ネットワーク (BGP Border Gateway Protocol実行されます。 ネットワークまたは自律システム (AS) は、その証明を問わずに、ピアによってアドバタイズされたルートを信頼、受け入れ、伝達するためにバインドされます。 '
Content: >-
  <p>インターネットは、ネットワーク ネットワーク (BGP Border Gateway Protocol実行されます。 ネットワークまたは自律システム (AS) は、その証明を問わずに、ピアによってアドバタイズされたルートを信頼、受け入れ、伝達するためにバインドされます。 これは BGP の強みであり、インターネットを迅速に更新し、障害を回復することができます。 ただし、ネットワークが所有&mdash;するプレフィックスへのパスは、トラフィックをリダイレクト、インターセプト、またはブラックホールするために、意図が悪意を持って変更される可能性があります。 昨年だけで、ルートハイジャックやリークなど、何百ものルーティング停止やインシデントが発生しました。 これらのインシデントは、大規模な分散型サービス拒否 (DDoS) 攻撃、盗まれたデータ、収益の失われた、評判の損害などにつながっています。</p>


  <p>ルーティング セキュリティは、インターネットの将来と安定性にとって不可欠であり、Microsoft は長い間、インターネット ルーティング のセキュリティの向上に取り組み続け、 2019 年に、Microsoft はルーティング <a href="https://www.manrs.org/" target="_blank">セキュリティに関連</a> する課題に対処するために、ルーティング セキュリティに関する相互に合意された規範 (MANRS) イニシアティブに参加しました。これは、毎日企業や消費者に影響を与えます。 運用に既存の MANRS フレームワークを実装し、インターネット社会、サイバーセキュリティ<a href="https://www.internetsociety.org/" target="_blank"></a><a href="https://cybertechaccord.org/" target="_blank">技術</a>協定、その他の組織と提携して、ネットワークオペレーターやインターネット交換ポイント (IXP) を超えるアクターがルーティング セキュリティに効果的に貢献する方法を調べるためにしました。</p>


  <p>本日は、MANRS クラウドとクラウド サービス プログラムによって定義された新しい<a href="https://www.manrs.org/2020/12/we-can-do-more-for-routing-security-say-participants-in-the-manrs-cdn-cloud-provider-programme/" target="_blank"></a>アクションを実装するために Microsoft が実行する手順<a href="https://www.manrs.org/cdn-cloud-providers/" target="_blank">をお知らせCDNします</a>。 これらの一連のアクションには、次のものが含まれます。</p>


  <h2>RPKI (リソース公開キー インフラストラクチャ) のオリジン検証</h2>


  <p>RPKI は、インターネット ルーティング インフラストラクチャをセキュリティで保護するように設計された公開キー インフラストラクチャ&rsquo; フレームワークです。 BGP ルートの起点情報をセキュリティで保護するために使用されます。 RPKI は長い道のりを経て、その導入は昨年 <a href="https://rpki-monitor.antd.nist.gov/" target="_blank">に 2 倍に増加しました</a>。 Microsoft は、自律システム番号 (ASN) によって発表された BGP ルート <a href="https://www.peeringdb.com/net/694" target="_blank">の署名を</a> 完了しました。 最近、2021 年中に RPKI フィルター処理を実装するコミットメントでピアリング ポリシーを更新しました。<a href="https://docs.microsoft.com/en-us/azure/internet-peering/policy" target="_blank"></a> これらの変更には時間がかかる可能性があります。また、インターネット ピアと一緒にこの切り替えがスムーズに行われ、確実に動作します。</p>


  <h2>ルート オブジェクトの検証</h2>


  <p>パブリック インターネット ルーティング&nbsp;Registries (IRR)&nbsp; は、ルートの起点情報とリレーションシップの大部分を引き続き保持します。 Microsoft では、IRR データベースを使用して、すべての受信ルートを検証します。 <a href="https://www.radb.net/" target="_blank">RADb</a> のすべてのレコードを更新し、ネットワークを保護するために、ピア ネットワークと一緒にパブリック IR 内のルート レコードを更新します。 Microsoft では、グローバル ネットワークを保護するために、グローバルルート異常検出および修復 (RADAR) システムを開発しました。 RADAR は、インターネット上の Microsoft ルート ハイジャックをリアルタイムで検出して軽減します。 RADAR は、Microsoft ネットワークおよびインターネット上のルート リークも検出します。 BGP ルート リークは、意図したスコープを超えたルーティングアナウンスの伝達です。 RADAR では、パブリック ルート データベースを使用して、目的のネットワーク パス情報 (AS パス) を確立します。</p>


  <p>RADAR では、悪意のあるアクティビティが検出された場合でも、Microsoft から優先パスを介して顧客にトラフィックをルーティングします。 インターネット サービス プロバイダー (ISP)、インターネット 交換パートナー (IXP)、 <a href="https://docs.microsoft.com/en-us/azure/peering-service/about" target="_blank">および Azure Peering Service</a> に参加しているソフトウェア定義クラウド相互接続 (SDCI) プロバイダーを利用しているお客様は、RADAR 情報に登録し、ルートの異常が検出された場合でも通知を受け取る可能性があります。</p>


  <h2>ピア ネットワークとレジストリとのコラボレーションを強化する</h2>


  <p>Microsoft は、170 を超えるエッジ ポイントのプレゼンスの場所を介して、 <a href="https://docs.microsoft.com/en-us/azure/networking/microsoft-global-network" target="_blank">何千ものネットワークと相互接続しています</a>。 Allpeer ネットワークを使用&nbsp;して、インターネット上のトラフィックを保護します。 ピアリング <a href="https://docs.microsoft.com/en-us/azure/internet-peering" target="_blank">ポータルでは、</a> 受信したルートすべてについて RPKI とルート オブジェクト情報が既に提供されています。 ピア ネットワークは、RPKI、ルート オブジェクト、およびネットワーク パスの情報をポータルで確認し、それぞれのレジストリのルートを修正できます。 現在、アドレス空間はさまざまなレジストリ (<a href="https://www.arin.net/" target="_blank">ARIN</a>、 <a href="https://www.lacnic.net/" target="_blank">RIPNIC</a>、 <a href="https://www.ripe.net/" target="_blank">RIPE</a> など) によって管理され、すべてのレジストリでルート オブジェクトを管理するのは簡単ではありません。 すべてのインターネット サービス プロバイダーがこれらのルート オブジェクトを簡単に管理できるよう、レジストリを使用して、インターネット ピアと一般的に簡単に管理します。</p>


  <p>インターネット ルーティング セキュリティでは、標準を絶えず更新する必要があります。 現在インターネットで直面している問題に対処できる単一の標準はありません。また、新しい脅威が発生した場合と同様に、ルーティング セキュリティ標準を更新する必要があります。 最近、MANRS コミュニティと一緒にこれらの標準を更新しました。他の MANRS メンバーと参加して実装できます。 最後に、この重要なテーマにインターネット コミュニティ<a href="https://www.internetsociety.org/" target="_blank"></a>を結び付け、インターネット セキュリティを加速する推進力になれて、<a href="https://www.manrs.org/" target="_blank">MANRS</a> とインターネット社会に感謝したいと考えています。</p>
