### YamlMime:Yaml
ms.openlocfilehash: 50912665936f199e8103736aac93cdede5fa612a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889426"
Slug: microsoft-docker-investing-in-the-future-of-your-applications
Title: Microsoft + Docker – アプリケーションの将来への投資
Summary: この投稿は、Microsoft チームと Docker チームによって作成されました。  Linux と Microsoft クラウド テクノロジに対する Docker のクロス プラットフォーム サポートを組み合Windowsを組み合わせると、 が得されます。
Content: >-
  <p><em>この投稿は、Microsoft チームと Docker チームによって作成されました。 </em></p>


  <p>Linux コンテナーと Windows コンテナーと Microsoft クラウド テクノロジの Dockers&rsquo; クロス プラットフォーム サポートを組み合わせると、事実上すべてのエンタープライズ ワークロードをサポートできる包括的なオファリングを得ましたか?</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/50dc73b3-e74d-438a-88c2-65fa2317f3b1.png"><img alt="Docker   Microsoft 1" border="0" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3d5bd809-b018-4b1b-98c9-4d9262ffd383.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="Docker Microsoft 1" width="309"></a></p>


  <h2>1 つのプラットフォーム、すべてのアプリケーションに 1 つの体験</h2>


  <p>Microsoft と Docker は、開発者や IT のプロが、Windows オペレーティング システムと Linux オペレーティング システムの両方で、オンプレミス、クラウド、またはサービス プロバイダーを通じて、任意のアプリケーションをビルド、出荷、実行するための最新のプラットフォームを提供します。 コンテナー アプリケーションをプラットフォーム間で統合し、開発者ツール、オペレーティング システム、クラウド インフラストラクチャを統合して、開発からテスト、運用まで、アプリケーション環境全体でシームレスなエクスペリエンスを提供します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a7d63649-4d99-4077-b389-30f7e6e6a32c.png"><img alt="Docker   Microsoft 2" border="0" height="306" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8720e292-9bee-42e1-9f18-e49510ef0f38.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="Docker Microsoft 2" width="540"></a></p>


  <p>プライベート データセンター、パブリック クラウド、ハイブリッドでワークロードをホストする場合でも、Microsoft と Docker&rsquo; は、開発者がキーボードからクラウドに向かう最適なエンドツーエンドソリューションまたは個々のコンポーネントを提供します。 Azure Container Service Docker Swarm などのコンテナー オーケストレーション環境をデプロイする最も簡単な方法が提供されます。そのため、アプリ チームはアプリを迅速にデプロイできます。 Windows Server コンテナーには同じ Docker ツールチェーンが搭載されています。そのため、Linux コンテナーの場合と同じ Docker ツールを使用して、それらのコンテナーをビルドして実行し、Eclipse、Visual Studio、Jenkins、Visual Studio Team Service などのツールを選択します。 Windows Server Containers を使用すると、既存のエンタープライズ .NET および企業のサーバー アプリケーションをセキュリティで保護し、最新化し、コードをほとんど変更したり、変更したりしません。 既存のアプリをコンテナーにパッケージ化して、よりアジャイルな DevOps モデルの利点を実現し、オンプレミス、任意のクラウド、またはハイブリッド モデルにデプロイします。 これらのアプリケーションのインフラストラクチャと管理のコストも削減します。</p>


  <h2>実際の動作を確認する @ DockerCon 2017</h2>


  <p>4 月 17 &ndash;日 20 日から TX のテキサス州テキサス州で行う Docker + Microsoft セッション @ DockerCon にアクセスしてください。 従来のアプリケーションを最新化する方法と、次の最適なアプリケーションの構築に役立つ新しいテクノロジを学習する方法について説明します。 &rsquo;Docker Enterprise Edition (Enterprise Edition) と Azure を使用してインフラストラクチャの統合と運用効率を通じて、ROI 目標を達成し、最大 80% のコスト削減を実現できた方法に関する顧客の成功事例について学習します。</p>


  <h2>セッションを確認する</h2>


  <ul>
   <li>Docker + Microsoft &ndash; 4 月 18 日火曜日の午前 <strong>11 時 45 分から午後 12 時 25</strong> 分まで、アプリケーションの将来への投資</li>
   <li>4 &ndash; 月 18 日火曜日の午後 <strong>2 時から午後 2 時 40</strong> 分まで、Docker の Windows と Linux パリティへのパスを超える</li>
  </ul>


  <p>また、Docker を使用してアプリケーションで使用するハンズオン ラボWindows。 Azure&rsquo; で Docker 環境をプロビジョニングし、自習学習ガイドを提供します。 詳細については、Docker での Docker + Microsoft セッションに関する <a href="https://blog.docker.com/2017/03/first-dockercon-windows-containers/">Elton Stonemans&rsquo;</a> ブログを参照してください。.NET のような従来のアプリの最新化から、新しい Windows Server Container アプリの構築までです。</p>
