### YamlMime:Yaml
ms.openlocfilehash: 7b3f41694aa3752172ede21e2fe21f508035532c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909624"
Slug: migrate-application-insights-to-hockeyapp
Title: 現在、アプリケーション インサイトモバイル アプリを HockeyApp に移行する
Summary: 現在、1 回のクリックで既存の Application インサイト モバイル アプリを HockeyApp に移行できます。
Content: >-
  <p>3 月の <a href="https://azure.microsoft.com/blog/transitioning-mobile-apps-from-application-insights-to-hockeyapp/">初めに、</a> HockeyApp でモバイルおよびデスクトップのお客様向け取り組みを重点 <a href="https://hockeyapp.net">的に取り組む予定です</a>。 HockeyApp は、Mobile DevOps ソリューションの重要なコンポーネントです。 アプリケーションを Application インサイトから HockeyApp に 1 回のクリックで移行できます。</p>


  <h2>HockeyApp への移行がライブになる</h2>


  <p>現在、アプリケーションを Application インサイト から HockeyApp に 1 回のクリックで転送できます。 アプリにログインするだけで、アプリの上部に切り替えステータス バーが表示されます。 この 1 回のボタンクリックで、既存のアプリケーションが HockeyApp に転送されます。 SDK を変更する必要はありません。エクスペリエンスを変更する必要はありません (アプリケーション インサイト エクスペリエンスは、終了日に達した 6 月 15 日まで影響を受け取ります)。</p>


  <p><img alt="Transfer to HockeyApp Status Bar" border="0" height="231" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/054d1851-0b24-44ca-be7a-d8ea9e0a967b.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="HockeyApp ステータス バーへの転送" width="610"></p>


  <p>この切り替えで既存のお客様を最適にサポートするために、Application インサイト から HockeyApp に移行されたアプリケーションは HockeyApp で無料でサポートされます。 転送によってこの期間中に移動されたアプリは、HockeyApp サブスクリプション アプリの制限にカウントされません。</p>


  <h2>それはどのように機能しますか?</h2>


  <p>アプリは、同じ Azure アカウントの資格情報 (MSA または AAD) に直接関連付けられている HockeyApp アカウントに転送されます。 &rsquo;HockeyApp アカウントをお持ちない場合は、自動的に作成されます。 その後、新しいアプリケーションを自動的にプロビジョニングし、それを既存の Application インサイトします。 これにより、両方のエクスペリエンスにデータをフローできます。 さらに、HockeyApp アプリは、Application インサイト リソースに送信された履歴データにアクセスできます。 このシームレスなエクスペリエンスが、アプリケーションが 6 月 15 日に終了インサイトまでの移行エクスペリエンスを支援すると期待しています。 移行の詳細については、サポート技術情報のドキュメントを参照 <a href="https://support.hockeyapp.net/kb/general-account-management-2/hockeyapp-for-application-insights-device-customers">してください</a>。</p>


  <h2>まとめ</h2>


  <p>この移行エクスペリエンスと無料のアプリ転送が、移行コストの軽減に役立つ場合があります。 私たちの目標は、HockeyApp を使用してアプリDevOps、テスト、監視、管理するための最適なモバイル アプリ エクスペリエンスを提供します。 この移行プロセス中に問題が発生した場合は、お問い <a href="https://support.hockeyapp.net">合わせください</a>。</p>
