### YamlMime:Yaml
ms.openlocfilehash: ce2b4beba75731ec96526d00b3b2fffb38c30f13
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892886"
Slug: modernize-your-applications-with-the-microsoft-data-accelerator-program
Title: Microsoft データ アクセラレータ プログラムを使用してアプリケーションを最新化する
Summary: 顧客は、お客様が提供するあらゆるソリューションで最新のイノベーションを要求しています。 アプリが顧客の期待を満たし、それを上回る方法を確認するにはどうすれば良いでしょうか。 効率的で信頼性の高いアップグレード サービスである Microsoft Data Accelerator Program を活用して、オンプレミスまたはクラウド アプリケーションを最新化します。
Content: >-
  <p>顧客は、お客様が提供するあらゆるソリューションで最新のイノベーションを要求しています。 アプリが顧客の期待を満たし、&mdash;&mdash;それを超えないようにするにはどうすれば&rsquo;良いでしょうか。 効率的で信頼性の高いアップグレード サービスである Microsoft Data Accelerator Program を活用して、オンプレミスまたはクラウド アプリケーションを最新化します。 今年は、次の 4 つの新しいシナリオをサポートするためにプログラムを拡張しました。</p>


  <p><strong><em>最新バージョンのクラウド にアップグレードして、クラウドへの移行をSQL Server。</em></strong> オンプレミス アプリを最新化するか、Linux 上の 2017 年 2017 年にSQL Serverアプリケーションを拡張します。</p>


  <p><strong><em>レガシ SQL Serverまたは Oracle アプリを移行して、Azure SQL Database。</em></strong> このAzure SQL Databaseを使用すると、柔軟なパフォーマンスとコスト効率を備え、レガシ アプリを SaaS 対応ソリューションに簡単に移行できます。</p>


  <p><strong><em>オープンソースへの投資を活用し、オンプレミス アプリを最新化して、MySQL と PostgreSQL Azure SQL Databaseに対応します。</em></strong> MySQL または Postgre データベースで既に知り合い、好きなツールを使用して、新しいアプリをすばやくSQLします。</p>


  <p><strong><em>オンプレミスのアプリをクラウドにSQL Serverしてクラウドにリフト アンド シフトAzure SQL Database Managed Instance。</em></strong> オンプレミスのアプリをSQL Serverクラウドに移行Azure SQL Database Managed Instance。 アプリを設計SQL、完全に管理された PaaS にアプリケーションを簡単に移行できます。</p>


  <p>Microsoft&#39;データ アクセラレータ プログラムを使用すると、ISV&#39;オンプレミス アプリをアップグレードしたり、クラウド体験を開始したりすることができます。 アプリケーションが&rsquo; クラウドで生まれた場合でも、移行を&#39;場合でも、データ アクセラレータ プログラムを使用すると、顧客のニーズに基づいてアプリを柔軟に最新化できます。 オンプレミス アプリをアップグレードするか、クラウドへの移行を開始するには、今すぐ適用してください。</p>


  <h4><a href="https://info.microsoft.com/microsoft-data-accelerator-program-register.html">詳細を確認し、Microsoft データ アクセラレータ</a> プログラムに申し込みます<strong>。</strong></h4>
