### YamlMime:Yaml
ms.openlocfilehash: 55d01dad33ea66642debb3118e478589bd4f1215
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893881"
Slug: monitor-azure-services-and-applications-using-grafana
Title: Grafana を使用して Azure のサービスとアプリケーションを監視する
Summary: '本日、Azure Monitor と Application Insights 用の Grafana プラグインを紹介します。 Azure Monitor データソースプラグインの v 0.1.0 は、Azure 米国政府、Azure ドイツ、および Azure 中国のクラウドのサポートを追加しました。 '
Content: >-
  <p>本日、Azure Monitor と Application Insights 用の Grafana プラグインを紹介します。 Azure Monitor データソースプラグインの v 0.1.0 は、Azure 米国政府、Azure ドイツ、および Azure 中国のクラウドのサポートを追加しました。 Azure は、お気に入りのツールやフレームワークを使用して構築されたワークロードを、Azure のさまざまなサービスと共にホストできるオープンプラットフォームです。 クラウドへの移行を続けながら、アプリケーションを Azure にオンボードすると、その多くは、既存のオープンソースの devops ツールと管理ツールを活用してビジネス継続性を確保する必要があります。 私たちの使命は、お客様のニーズを満たし、Azure でこれらのツールをシームレスに活用できるようにすることです。 1つの一般的なツールとして、時系列メトリックを視覚化するための優れたオープンソースソフトウェア <a href="https://grafana.com/" target="_blank">Grafana</a>があります。 いくつかのお客様は、既存の監視投資の一部である Grafana の Azure サービスとアプリケーションからのメトリックを使用する機能に関するフィードバックを提供しています。 Azure 用の Grafana データソースプラグインを使用してこれを行うことができるすばらしいニュース &ndash; があります。</p>


  <h2>Azure Monitor および Application Insights preview 用の Grafana プラグイン</h2>


  <p>Grafana を既に使用している場合は、Grafana の背後にある Grafana Labs のチームによって構築された新しい <a href="https://grafana.com/plugins/grafana-azure-monitor-datasource" target="_blank">Azure Monitor データソースプラグイン</a>を使用して、Azure のサービスとアプリケーションを監視することもできます。 現在プレビュー中のこのプラグインを使用すると、Azure Monitor からのメトリックと、Grafana ダッシュボードに Application Insights を含めることができます。 セットアップ手順については、データソースプラグインの <a href="https://grafana.com/plugins/grafana-azure-monitor-datasource/installation" target="_blank">インストールページ</a> を参照してください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/dab37ce8-46f5-4c73-9ec1-6df0e070c805.png"><img alt="Contoso Loans Grafana dashboard" border="0" height="1195" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9040a751-7dfb-42d8-bc2f-66f2d08653c9.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Contoso ローン Grafana ダッシュボード" width="2546"></a></p>


  <p align="center"><em>図 1: Azure Monitor と Application Insights のメトリックを示す Grafana ダッシュボード</em></p>


  <p>このプラグインを使用すると、Collectd、テレ、Prometheus などのさまざまなオープンソースエージェントから収集されたすべてのメトリックと、Azure プラットフォームやアプリケーションからのメトリックを1つのダッシュボードにまとめることができます。</p>


  <h2>Azure Marketplace オファリングを使用した簡単な Grafana セットアップ</h2>


  <p>Grafana Labs のチームは、Azure で Grafana を使い始められるようにして、Azure Marketplace プランを構築することをお望みでした。 <a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/grafana-labs.grafana_oss" target="_blank">Azure Marketplace の Grafana サーバー</a>を活用できます。これは、基本的に、事前にインストールされた Grafana ダッシュボードサーバーと Azure プラグインを備えた VM です。</p>


  <p>Azure Monitor と Application Insights のメトリックを使用して Grafana ダッシュボードを設定するサンプルチュートリアルについては、 <a href="https://aka.ms/grafanawalkthrough" target="_blank"><em>Azure Monitor のドキュメント</em></a>を参照して<em>ください。</em></p>


  <p>Grafana Labs のチームは、このプラグインと Marketplace のプランについてご意見をお待ちしております。 Twitter &nbsp; <a href="https://twitter.com/search?q=%40grafana&amp;src=typd"> @grafana </a>でこれらのユーザーに連絡することも、 <a href="https://github.com/grafana/azure-monitor-datasource">GitHub</a>にフィードバックを送信することもできます。</p>


  <h2>まとめ</h2>


  <p>お客様のプラットフォームとサービスを革新し、コミュニティと提携することによってお好きなオープンソースフレームワークやツールと統合することで、さらに多くのことを支援します。 Grafana 統合は、まだ提供されていない多くの統合の1つにすぎません。 Azure のアプリケーションとリソースでお客様からの <a href="https://feedback.azure.com/forums/231545-diagnostics-and-monitoring" target="_blank">フィードバック</a> をお待ちしております。</p>
