### YamlMime:Yaml
ms.openlocfilehash: d16af0a3401c0f8b2bd3b1f57f540890e58f779c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892883"
Slug: more-reliable-event-driven-applications-in-azure-with-an-updated-event-grid
Title: 更新されたアプリケーションを使用して、Azure のより信頼性の高いイベント駆動型Event Grid
Summary: 'クラウド アプリケーション アーキテクチャのコア ビルディング ブロックとしてのイベント駆動型プログラミングの台頭の一部になれたのは非常に楽しみです。 次の機能を一般提供することで、より高度でパフォーマンスが高く、安定したイベント駆動型アプリケーションを Azure で構築できる必要があります。 '
Content: >-
  <p>クラウド アプリケーション アーキテクチャのコア ビルディング ブロックとしてのイベント駆動型プログラミングの台頭の一部になれたのは非常に楽しみです。 次の機能を一般提供することで、より高度でパフォーマンスが高く、安定したイベント駆動型アプリケーションを Azure で構築できる必要があります。 以下の一連の機能 <strong>の</strong> 一般提供をお知らせします。以前はプレビューで提供されています。</p>


  <ol>
      <li>[Dead lettering]/(致命的な文字)</li>
      <li>再試行ポリシー</li>
      <li>Storageキューを宛先として使用する</li>
      <li>宛先としてのハイブリッド接続</li>
      <li>手動検証ハンドシェイク</li>
  </ol>


  <p>機能の GA 状態を利用するには、2019-01-01 API と SDK を使用している必要 <a href="https://docs.microsoft.com/en-us/azure/event-grid/sdk-overview" target="_blank">があります</a>。 アプリまたは CloudShell&rsquo; Azure portal使用している場合は、既に問題が解決されています。 CLI または PowerShell を使用している場合は、CLI 用のバージョン 2.0.56 以降と PowerShell 用の 1.1.0 がインストールされている必要があります。</p>


  <h2>[Dead lettering]/(致命的な文字)</h2>


  <p>致命的な文字を使用すると、ミッション クリティカルなシステムでイベントを受け取る保証が少なくとも 1 回提供されます。 <a href="https://docs.microsoft.com/azure/event-grid/manage-event-delivery" target="_blank">イベント ハンドラーがダウン</a>した場合、承認に失敗した場合、またはエンドポイント内のバグがボリュームに大きそうになっても、メッセージが失われる可能性があります。</p>


  <p>配信できない場合は、各イベント サブスクリプションをストレージ アカウントに接続できます。これにより、プライマリ イベント パイプラインで障害が発生した場合、Azure Event Grid はそれらのイベントをストレージ アカウントにいつでも配信して使用できます。</p>


  <h2>再試行ポリシー</h2>


  <p>再試行ポリシーにより、一時的な障害が発生した場合にプライマリ イベント パイプラインの堅牢性が向上します。 配信停止は、システムで長時間続く障害が発生した場合に備えてバックストップを提供しますが、分散システムでは一時的な停止のみを確認する方が一般的です。</p>


  <p><a href="https://docs.microsoft.com/azure/event-grid/delivery-and-retry" target="_blank">再試行ポリシーを構成</a> すると、イベントが配信され、破棄される前に再試行する回数、または再試行する期間を設定できます。 イベントの遅れにかかわらず、イベントの再試行を可能な限り長く続ける必要がある場合があります。 それ以外の場合は、イベントが古い場合は値を持たないので、すぐに削除する必要があります。 再試行ポリシーを使用すると、最適な配信スケジュールを選択できます。</p>


  <h2>Storageキューを宛先として使用する</h2>


  <p>Event Gridキューにイベントを直接プッシュAzure Storageできます。 <a href="https://docs.microsoft.com/en-us/azure/event-grid/custom-event-to-queue-storage" target="_blank">キューは、イベント ハンドラーにイベント</a> のイングレスをバッファーして適切にスケールアップする必要がある場合に、強力なイベント ハンドラーになる可能性があります。 同様に、イベント&rsquo; ハンドラーでアップタイムを保証できる場合、ストレージ キューを の間に置くことで、イベントを保持し、イベント ハンドラーの準備ができたらそれらを処理できます。</p>


  <p>Storageキューには仮想ネットワーク (VNet) 統合も用意されています。これにより、仮想ネットワーク イベントの VNet インジェクションEvent Gridできます。 VNet 内のイベント ハンドラーにイベント ソースを接続する必要がある場合は、Event Grid にストレージ キューに発行し、キューを介して VNet 内のイベントを使用します。</p>


  <h2>宛先としてのハイブリッド接続</h2>


  <p>&rsquo;イベントのクラウド リソースに接続している間にローカルでビルドおよびデバッグする場合、HTTP エンドポイントを公開できないオンプレミス サービスがある場合、またはロックダウンされたファイアウォールの背後から作業する必要がある場合、ハイブリッド接続を使用すると、それらのリソースを <a href="https://docs.microsoft.com/en-us/azure/event-grid/custom-event-to-hybrid-connection" target="_blank">Event Grid</a> に接続できます。</p>


  <p>イベント ハンドラーとしてのハイブリッド接続を使用すると、接続する HTTP Event Gridできます。 また、ローカル リソースから同じハイブリッド接続インスタンスへの送信 WebSocket 接続を行うオプションも提供されます。 その後、ハイブリッド接続によって、イベント グリッドからオンプレミス リソースに受信イベントがリレーされます。</p>


  <h2>手動検証ハンドシェイク</h2>


  <p>すべてのイベント ハンドラーが、エンドポイントの所有権の証明を提供するために HTTP 応答をカスタマイズできるではありません。 手動検証ハンドシェイクを使用すると、エンドポイントの承認された所有者であることを証明するために、コピー の貼り付けと同じ方法で簡単に行えるのです。</p>


  <p>サブスクリプションを登録Event Grid、検証コードを使用してエンドポイントに検証イベントが送信されます。 検証コードをエコーバックすることで検証イベントに応答することもできますが、便利ではない場合は、イベントに含まれる検証 <a href="https://docs.microsoft.com/azure/event-grid/security-authentication" target="_blank">URL</a> をコピーして任意のブラウザーに貼り付け、エンドポイントを検証できます。 エンドポイントで GET を実行すると、所有権の証明が検証されます。</p>


  <p>このニュースに <em>うまく</em> 反応してください。</p>


  <p>Azure Event Grid チーム</p>
