### YamlMime:Yaml
ms.openlocfilehash: b999e0800e66bfa38ac5ef828e623b24c79483fa
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910708"
Slug: net-application-migration-using-azure-app-services-and-azure-container-services
Title: Azure アプリ Services と Azure Container Services を使用した .NET アプリケーションの移行
Summary: ビジネスクリティカルなアプリをクラウドに移行する方法を理解する必要がある開発者やソリューションアーキテクト向けに設計されています。このオンラインワークショップシリーズでは、既存の ASP.NET ベースのアプリケーションをコンテナーベースのアプリケーションに移行するための実績のあるプロセスについて説明します。 水曜日と金曜日に90分、5月3日までにご参加ください。専門家によるガイダンスを受け、質問に回答することができます。
Content: >-
  <p>ビジネスクリティカルなアプリをクラウドに移行する方法を理解する必要がある開発者やソリューションアーキテクト向けに設計されています。このオンラインワークショップシリーズでは、既存の ASP.NET ベースのアプリケーションをコンテナーベースのアプリケーションに移行するための実績のあるプロセスについて説明します。 水曜日と金曜日に90分、5月3日までにご参加ください。専門家によるガイダンスを受け、質問に回答することができます。</p>


  <p>このシリーズに付随するオプションの (ただし、非常に推奨される) ハンズオンラボでは、仮想マシンのアーキテクチャから Azure に多層 web アプリソリューションを提供する概念実証 (POC) を構築できます。これにより、Azure Platform サービスと、現在利用可能なさまざまな Azure コンテナーソリューションを利用できます。 また、基になるデータベースを SQL 2014 仮想マシンアーキテクチャから SQL Azure に移行します。</p>


  <p>このシリーズの最後には、コンテナーの概念、Docker のアーキテクチャと運用、azure container Services、azure Kubernetes Services、および SQL Azure PaaS solutioning についてよく理解できるようになります。</p>


  <h2>パート 1: Azure を使用したデジタルアプリの変換</h2>


  <p>最初のセッションでは、既存の .NET Framework アプリケーションを最新化するための戦略的な方法について説明します。 これには、VM リフト &amp; シフトから、サービスとしてのプラットフォーム (PAAS)、および azure によってネイティブに提供されるコンテナーサービスとオーケストレーションの概要について、azure が提供するさまざまな選択肢が含まれます。</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart1DigitalAppTransformationwithAzure.html">オンデマンドで見る</a></p>


  <h2>パート 2: ARM テンプレートを使用したコードとしてのインフラストラクチャ</h2>


  <p>ARM (Azure Resource Manager) テンプレートは、コードとしてのインフラストラクチャに対する Azure &rsquo; の回答であり、インフラストラクチャリソースをデプロイするだけではなく、はるかに多くのことを行うことができます。 このセッションでは、コードとしてのインフラストラクチャによって実行速度の向上、リスクの軽減、コストの削減、および DevOps との統合について説明します。 &rsquo;自動デプロイと継続的インテグレーションのために ARM テンプレートを使用する必要がある理由、GitHub で Azure クイックスタートテンプレートを検索する方法、Visual Studio で arm テンプレートを作成する方法について説明します。</p>


  <p>ARM テンプレートで Azure リソースをデプロイする方法を学習するだけでなく、さらに一歩進んで、VM 構成を自動化する完全なプロセスについて説明します。 このセッション &rsquo; の後、提供されているラボを使用することができます。ここでは、Azure サブスクリプションを設定し、Visual Studio 2017 を使用してソース仮想マシン環境をデプロイし、ワークショップシリーズ全体で使用するベースライン2層アプリケーションのワークロードをデプロイします。</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart2InfrastructureasCodeusingARMtemplates.html">オンデマンドで見る</a></p>


  <h2>パート 3: Azure Database Solutions |SQL Azure</h2>


  <p>まず、セキュリティと分離の問題の除去や、高可用性/ディザスターリカバリーを統合する方法など、SQL、IaaS、PaaS のオプションについて説明 &rsquo; します。 &rsquo;Azure SQL のデプロイに関する詳細なデモが表示されます。ここで主な機能を紹介します。</p>


  <p>次に、移行オプションについて詳しく説明 &rsquo; し、データベース移行ツールを紹介します。これにより、SQL Management Studio を使用して SQL Azure に SQL VM データベースを移行する、付随するラボを完成させること &rsquo; ができます。</p>


  <p>2019 10 年4月17日太平洋東部/午後1時東部</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart3AzureDatabaseSolutionsSQLAzure.html">登録してライブに参加する</a></p>


  <h2>パート 4: Azure アプリ Services |Azure Web Apps</h2>


  <p>このデモで取り上げた &rsquo; セッションでは、デプロイスロット、スケーリングと自動スケール、価格レベル、統合バックアップ、app insights などの主要な機能について説明します。これにより、Azure Web Apps の中核となる機能と長所を理解できます。 このセッションは、サンプルアーキテクチャとデプロイのライフサイクルを含むコンテナーの Azure Web Apps で終了します。 このセッション &rsquo; のラボでは、従来の ASP.NET アプリケーションを Visual Studio で Azure Web Apps に移行します。</p>


  <p>2019 10 年4月19日太平洋東部/午後1時東部</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart4AzureAppServicesAzureWebApps.html">登録してライブに参加する</a></p>


  <h2>パート 5: Docker コンテナー</h2>


  <p>Docker コンテナーはグローバルな標準であり、Azure でネイティブにサポートされています。これにより、企業は、将来のトレーニングとコストの両方の利点を実現するために、従来のアプリを柔軟かつ柔軟に移行できます。 このセッション &rsquo; では、Docker for Windows のインストール、一般的な Docker CLI 操作の実行、cli と Visual Studio 2017 の両方を使用して docker イメージを構築する方法の詳細なデモを紹介します。 Docker ビルドのトラブルシューティングに関する重要なヒントについても説明 &rsquo; します。 このセッション &rsquo; の後、Docker CE for Windows でレガシ ASP.NET アプリケーションをコンテナー化するラボを完成させることができます。</p>


  <p>2019 10 年4月24日太平洋東部/午後1時東部</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart5DockerContainers.html">登録してライブに参加する</a></p>


  <h2>パート 6: Azure Container Registry |Azure Container Instance</h2>


  <p>Azure Container Registry は、オープンソースの Docker レジストリ2.0 に基づく管理された Docker レジストリサービスです。これにより、Azure container Registry を作成して管理し、プライベート Docker コンテナーイメージを格納および管理できます。 Azure Container Instance は、Azure でコンテナーを実行する最速で簡単な方法を提供します。仮想マシンをプロビジョニングする必要はなく、上位レベルのサービスを採用する必要もありません。 ACR と ACI の両方について説明し、連携する &rsquo; しくみについても説明します。 セッション &rsquo; の後、Azure Container Registry をデプロイするラボを完成させ、Azure Container Instance を使用して、コンテナー化されたワークロードを実行できます。</p>


  <p>2019 10 年4月26日太平洋東部/午後1時東部</p>


  <p><a href="https://info.microsoft.com/en-us-landing-ExploreusingAzureContainerInstancetoruncontainerizedapplications.html">登録してライブに参加する</a></p>


  <h2>パート 7: Azure Container Services と Azure Kubernetes Services を使用したコンテナーオーケストレーション</h2>


  <p>このセッションでは、Azure でのコンテナーオーケストレーションの操作に関する詳細なビューを提供し、Azure Container Services (ACS) と Azure Kubernetes Services (AKS) の両方について説明します。 ここでは、両方の類似点、相違点、およびロードマップについて説明し、いくつかの一般的なコンテナー orchestrator のタスクについ &rsquo; て説明します。 Kubernetes を使用して ACS をデプロイし、AKS をデプロイするラボを準備するには、 &rsquo; 詳細なデモを提供し、管理とデプロイのサンプルを提供します。 また、AKS で Docker Hub イメージを実行する &rsquo; デモも紹介します。</p>


  <p>2019 10 年5月1、午前1時 (太平洋標準時)、午後1時 (東部標準時)</p>


  <p><a href="https://info.microsoft.com/en-us-landing-LearntodeployAzureContainerServiceswithKubernetes.html">登録してライブに参加する</a></p>


  <h2>パート 8: Azure Kubernetes Services の管理と監視</h2>


  <p>&rsquo;AKS でのコンテナーのスケーラビリティの有効化、AKS の監視、AKS での Kubernetes ダッシュボードの使用について説明します。 &rsquo;Azure Container Services 内での Container Registry イメージの実行、AKS のスケーリング、azure での AKS の監視に関する多数のサンプルと詳細なデモを紹介します。 このワークショップシリーズの最後のラボでは、AKS の管理と監視について学習します。</p>


  <p>2019 10 年5月3、太平洋標準時 (太平洋標準時)、午後1時 (東部標準時)</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart8ManagingandMonitoringAzureKubernetesServices.html">登録してライブに参加する</a></p>


  <p>すべてのセッションは、ライブ配信後も記録され、オンデマンドで表示できるようになります。ラボやその他の資料は GitHub でご利用いただけます。</p>
