### YamlMime:Yaml
ms.openlocfilehash: 51ca76fa8175dd03fb93044362fd1e55996dc4a0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905231"
Slug: new-azure-investments-deliver-unprecedented-performance-for-all-your-business-critical-applications
Title: 新しい Azure 投資により、ビジネスに不可欠なすべてのアプリケーションに対して前例のないパフォーマンスが実現されます
Summary: お客様のデジタル変革体験をさらに強化する Azure インフラストラクチャの主な機能強化を強調しています。
Content: >-
  <p>テクノロジは、私たちの生活のすべての次元に組み込み、施設から運営施設、冷却装置、車まで、あらゆるものにテクノロジが取り入れられています。 デジタル&rsquo;破壊的な単なる単なる障害ではなくなりました。 すべてのビジネスは、テクノロジの恩恵を受け、顧客とのつながり、満足度、収益性を向上させます。 <a href="https://customers.microsoft.com/story/724138-bp-infrastructure-energy-azure" target="_blank">BP</a>、<a href="https://azure.microsoft.com/case-studies/customer-stories-lufthansa/" target="_blank">Lufthansa</a>、<a href="https://customers.microsoft.com/story/team-rubicon-nonprofit-dynamics-365" target="_blank">TeamRubicon</a> などの組織は、Azure インフラストラクチャを使用してビジネスを最適化および変革し、新しいアプリケーションを構築して、従業員の生産性を向上させ、顧客にサービスを提供する新しい方法で顧客サービス、物流、サービス配信を接続しています。</p>


  <p>Microsoft Ignite のこの週は、お客様&#39;のデジタル変革体験をさらに強化する主要な Azure インフラストラクチャ&rsquo; の機能強化を再び強調しました。</p>


  <h2>ワークロードのパフォーマンスの向上とコストの削減</h2>


  <p>Azure には、小規模から業界最大の仮想マシン (VM) から、ネイティブ <a href="https://azure.microsoft.com/overview/azure-vmware/" target="_blank">VMware</a> ワークロードをサポートできる専用のハードウェア、<a href="https://azure.microsoft.com/services/netapp/" target="_blank">NetApp</a> を搭載したエンタープライズ レベルのファイル、最大 120 TB の SAP スケールアウト デプロイまで、コンピューティング オファリングの最も広範なポートフォリオがあります。<i></i>&rsquo; Coca-Cola Bottlers のサービス アームである <a href="https://customers.microsoft.com/story/cona-services-partner-professional-services-azure" target="_blank">CONA Services</a> は、最大の SAP HANA クラウド デプロイの 1 つである<a href="https://azure.microsoft.com/solutions/sap/" target="_blank"> Azures&rsquo;</a> 専用の SAP HANA インフラストラクチャ上で 40 TB のミッション クリティカルなシステムを実行します。 コンピューティング ポートフォリオを補完するために、Azure Ultra Disks を使用するクラウドで最も高速なディスクの 1 つを含む、最高のパフォーマンス ディスクの 1 つを提供し、最大 160,000 IOPS を実現します。</p>


  <p>お客様は、以前はコストが高かったり、単に実現できない新しい高パフォーマンスのシナリオに対処しています。 新しい Azure HB と HC Virtual Machines により、Azure は、クラウド内の大規模な密結合ワークロードに対して、前例のないパフォーマンス、スケーラビリティ、コスト効率を備えたハイ パフォーマンス コンピューティングを民主化しています。 InfiniBand ネットワークは、業界で最も低い待ち時間と最高の帯域幅を提供し、1 つの MPI ベースのアプリケーションで最大 23,000 コアのワークロードを実現するのに役立ちます。これは、クラウド内の他の場所にあるものよりも 10 倍高くなります。 200 ギガビット InfiniBand を搭載した最初の Azure 仮想マシンである HBv2 では、Azure はジョブあたり最大 80,000 コアのワークロードをサポートします。&nbsp;</p>


  <p>また、サーバーと Linux のワークロードWindows Azure に移行する顧客も表示されます。 現在、Azure コンピューティングの 50%&rsquo; 以上が Linux ワークロードを実行しています。 サーバーとクラウドのWindowsとなるSQL、次の主要なクラウド ベンダーよりも 30% 多くの企業が Azure を選択します。 Azure SQL Managed Instance、App Service、Windows Virtual Desktop と、他に類を見ないセキュリティとシームレスなハイブリッド機能を備えた優れたイノベーションを提供し、Azure を <a href="https://azure.microsoft.com/campaigns/best-on-azure/" target="_blank">Windows および SQL Server</a> ワークロードに最適なクラウドにしています。 パフォーマンスに関しては、Azure SQL Database は、AWS RDS と比較して最大 <a href="https://azure.microsoft.com/blog/azure-sql-database-continuous-innovation-and-limitless-scale-at-an-unbeatable-price/" target="_blank">86%</a> のコストを削減しながら、ビジネス クリティカルなワークロードの価格パフォーマンス リーダーです。</p>


  <p>Microsoft Ignite では、より広範な顧客シナリオに対応するために、コンピューティング、ストレージ、およびネットワークのオファリングを拡張しています。 いくつかの特徴を次に示します。</p>


  <ul>
      <li>&nbsp;メモリを集中的に消費するワークロード向け Ea v4 および Eas v4 Azure Virtual Machine シリーズと、汎用アプリケーション用の Da v4 および Das v4 Azure Virtual Machine シリーズの一般提供。 これらの新しい Azure Virtual Machinesは、最新の AMD EPYC&trade; 7452 プロセッサを搭載したクラウドで最初の機能です。</li>
      <li>&nbsp;仮想デスクトップと HPC ワークロードをサポートする NVv4 および HBv2 VM シリーズのプレビュー。 これらの新しい Azure Virtual Machines AMD EPYC&trade; 7742 プロセッサが搭載されています。 NVv4 は、視覚化ワークロードを行う最もコスト効率の高い方法として設計されています。これは、GPU の小数部を持つ VM をサポートします (GPU は 1/8)。 NVv4 は、AMD RADEON INSTINCT&trade; GPU を提供する Azure&rsquo; 初の視覚化最適化 VM ですが、HBv2 は 200 ギガビット InfiniBand ネットワークを提供する Azures&rsquo; の最初の HPC VM です。</li>
      <li>&nbsp;最も要求の厳しい機械学習モデルと分散 AI トレーニング ワークロードをサポートする NDv2 VM シリーズのプレビュー。 これらの更新された VM には、それぞれ 32 GB のメモリを備えた 8 つの NVIDIA Tesla V100 NVLINK 相互接続 GPU が搭載されています。</li>
      <li>&nbsp;プレミアム SSD、Standard SSD、Ultra ディスク上の新しい 4 GB、8 GB、および 16 GB の新しいサイズのプレビュー。予測可能なトラフィック パターンが少ないワークロードをクラウドに移行する顧客に低コストを提供します。</li>
      <li>&nbsp;該当する SSD での新しいバースト機能のプレビュー。プレミアムワークロードの最大 30 倍のパフォーマンスを備えます。</li>
      <li>&nbsp;Azure Data Lake Storage (ADLS) Gen2 でコア BLOB 機能を提供する ADLS マルチプロトコル アクセスのプレビュー(ログ記録、階層化、イベント グリッド統合など)、エンタープライズ統合の強化。</li>
      <li>&nbsp;Azure Peering Service Azure や SaaS サービスにアクセスするインターネットファーストのネットワーク戦略を顧客を対象とする Azure Office 365 のプレビュー。 インターネット サービス プロバイダーとの提携により、お客様はグローバル ネットワークを利用して、信頼性が高く最適化されたインターネット接続を実現Microsoft サービス。</li>
      <li>&nbsp;サテライト サポートの一般提供Azure ExpressRoute、サービスを、業界をまたがって多くのお客様にとって重要な到達の難しい領域に拡張できます。</li>
      <li>&nbsp;Azure Bastion の一般提供により、この機能をサービスとしてプラットフォームに統合する初めてのパブリック クラウドが Azure に導入され、Azure のインフラストラクチャに Bastion ホストを迅速かつ非常にシンプルにデプロイできます。<a name="_GoBack"></a></li>
  </ul>


  <h1>不一致のセキュリティと、ワークロードに対するスケーラビリティの簡素化</h1>


  <p>世界 54 のリージョンで、6 つの大陸にわたる他のクラウド プロバイダーよりも多くのリージョンを提供しています。 ビジネスクリティカルなワークロードを実行するときに自信を持って実行できるよう、Azure に継続的に投資して、最高の信頼性とスケーラビリティの標準を満たしています。 クラウド セキュリティに関しては、年間 10 億ドルを超える投資を行い、セキュリティに重点を置いた 3,500 人を超える従業員を雇用しています。 ほんの数週間前に、企業全体を保護する組み込みのクラウドネイティブ SIEM Azure Sentinel の一般提供を発表しました。</p>


  <p>今週は、Azure のスケーラビリティ、信頼性、セキュリティに関して行っている機能強化の一部について説明します。</p>


  <ul>
      <li>&nbsp;第 2 世代 Azure Virtual Machines の一般提供、Intel Software Guard Extensions (Intel SGX) のサポートによるセキュリティの向上、および 2 TB を超える大きな VM (最大 12 TB) と OS ディスク サイズを提供する機能。</li>
      <li>&nbsp;Windows および Linux 用の仮想マシン スケール セットの新機能のプレビュー。これは、ランタイムとパフォーマンスの機能を向上しながら VM を簡単に管理するのに役立ちます。 たとえば、プロビジョニング時間を短縮しながら、共有イメージ ギャラリーを使用してカスタム VM イメージを大規模にプロビジョニングできます。</li>
      <li>&nbsp;異なるリージョンへの顧客<a></a>が制御する BLOB レプリケーションを使用した geo 分散アプリケーションをサポートするオブジェクト レプリケーション サービスのプレビュー。</li>
      <li>&nbsp;Qualys を利用した VM の高度な脆弱性評価、Kubernetes コンテナーのサポート、Check Point、Tenable、CyberArk などのパートナーからのセキュリティに関する推奨事項の統合など、Azure Security Center 機能が強化されました。</li>
      <li>&nbsp;Azure Sentinel Citrix と ZScaler のコネクタ、疑わしい URL の調査ツール、強化された検出などの拡張機能が追加されました。</li>
      <li>&nbsp;Azure Managed Disks強化され、カスタマー マネージド キーを使用してサーバー側の暗号化を有効にすることで、お客様のコンプライアンス ニーズを完全に制御できます。 これにより、顧客はデータを活用Azure Key Vaultキーの使用状況を追跡できます。 この新しい機能は、プレミアムソリッド ステート ドライブ (SSD)、Standard SSD、Standard ハード ディスク ドライブ (HDD) ディスクの種類のプレビューで利用できます。</li>
  </ul>


  <h2>すべての環境にわたる統合ハイブリッド管理</h2>


  <p>お客様の IT 環境は、より多くのワークロードがクラウドに移行し、エッジ コンピューティングが増加するにつれて進化しています。 IT 環境は、さまざまな種類のアプリケーション、ハードウェア、マルチクラウド、エッジ環境でますます複雑になり、基本的に IT リソースの広がりを生み出しています。 お客様から、IT リソースを大規模な中央の場所からどこからでも整理、管理、セキュリティ保護するための統一されたアプローチを探しているというメッセージが表示されます。</p>


  <p>Microsoft Ignite では、オンプレミス環境と複数の環境で一貫した管理を行い、クラウドイノベーションを可能にするハイブリッド機能を発表しています。 これらの主な機能の一部を次に示します。</p>


  <ul>
      <li>&nbsp;プレビュー <a href="https://azure.microsoft.com/services/azure-arc/" target="_blank">Azure Arc、</a>Azure 管理を拡張し、オンプレミス、マルチクラウド、エッジ全体で Azure データ サービスを有効にする一連のテクノロジです。 現在、お客様は、Windows および Linux サーバー、Kubernetes クラスター、Azure データ サービスをどこにいても管理および管理するための一元的で統一されたアプローチを採用しています。 Azure Arc、DevOps、Azure ガバナンス、Azure セキュリティなど、クラウド プラクティスの導入を、オンプレミス、マルチクラウド、エッジ全体に拡張します。</li>
      <li>&nbsp;管理センター バージョン 1910 Windowsの一般提供。実行されている場所を問Windows管理するための強力なハイブリッド機能が提供されます。 ディザスター リカバリー、バックアップ、修正プログラムの適用、監視のためにオンプレミス サーバーの Azure への統合が効率化され、現在は Azure Security Center との統合が含まれています。&nbsp;Windows管理センターを使用すると、お客様は Azure Arcを使用して、Azure からの統合ハイブリッド管理を利用できます。</li>
      <li>&nbsp;また、新しいソリューションを含Azure Stackポートフォリオを拡張Azure Stack Edge。 Azure Stack Edgeは、任意のエッジの場所で Azure のコンピューティング、ストレージ、インテリジェンスを提供する Azure マネージド アプライアンスです。 Azure portal からAzure Stack Edgeを管理できます。</li>
  </ul>


  <p>これらの新機能はすべて、新しいサーバーレス、コンテナー、関数の機能など、アプリケーションの最新の開発における Azures&rsquo; の最新の開発と組み合わせることができます。</p>


  <p>これらは、Microsoft Ignite で&rsquo;提供されるハイライトのほんの一部です。 お客様がこれらの機能をデジタル変革体験に統合する方法を楽しみにしています。</p>


  <hr />

  <p><em>Azure。目的を持って発明する。</em></p>
