### YamlMime:Yaml
ms.openlocfilehash: cc77b8e9329e3e3a99c888867fca6d03c4537f5a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904646"
Slug: new-application-insights-functionality-on-azure-websites-with-the-application-insights-website-extension
Title: Application インサイト Web サイト拡張機能を使用した Azure Websites の新しいアプリケーション インサイト機能
Summary: Application インサイトは、開発チームがアプリケーションの 360° ビューを取得するのに役立つ、Azure プレビュー ポータルで使用できるプレビュー サービスです。
Content: >-
  <a href="https://azure.microsoft.com/en-us/services/application-insights/" target="_blank">Application インサイト は</a>、Azure プレビュー ポータルで利用できるプレビュー サービスです。これは、開発チームが、高速で強力なトラブルシューティング、診断、使用状況の分析情報を使用して、可用性、パフォーマンス、使用状況全体でアプリケーションの 360° &amp; ビューを取得できるよう設計されています。


  新しい Application インサイト Websites 拡張機能は、Azure アプリケーション インサイト チームと Azure Websites チームの間の密接なコラボレーションの結果です。


  Web サイトからこの拡張機能を有効にしたら、すべてのアプリケーションの依存関係と関連する統計情報を表示できます。 ドリルダウンして、特定の要求に関係する依存関係と、Web サイトまたは Web アプリケーションのパフォーマンスに影響を与える方法を確認できます。

  <p align="center"><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/01/08/AppInsights.png"><img class="size-large wp-image-242121" alt="New Application Insights functionality on Azure Websites with the Application Insights Website extension" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AppInsights-554x369.png" width="554" height="369" /></a></p>

  上の図は、ドリルダウンの例を示しています。 ここでは、リモート依存関係の呼び出し (この場合は 75 SQLかかったのを確認できます。


  詳細な技術的な詳細と構成手順については、Visual Studio ブログの <a href="https://blogs.msdn.com/b/visualstudioalm/archive/2015/01/07/application-insights-and-azure-websites.aspx">Vlad Joanovic</a> によるブログ投稿を参照してください。


  Azure Applications Insight チームと引き続き取り組み、今後数か月以内に Azure Websites にさらに多くの機能を取り込む予定です。


  &nbsp;
