### YamlMime:Yaml
ms.openlocfilehash: 45785d7031ab8f5b8735b0d169f6c1ec1e15632e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139893381"
Slug: new-azure-stack-developer-features-to-build-intelligent-hybrid-applications
Title: インテリジェントなハイブリッドアプリケーションを構築するための新しい Azure Stack 開発者向け機能
Summary: 今週のビルドでは、開発者がビジネスニーズに応じてあらゆる場所でインテリジェントなアプリケーションを構築できるように、Azure と Azure Stack について説明します。 Azure Stack 昨年,... を起動した後
Content: >-
  <p>今週のビルドでは、開発者がビジネスニーズに応じてあらゆる場所でインテリジェントなアプリケーションを構築できるように、Azure と Azure Stack について説明します。 昨年 Azure Stack 発売以来、Azure との一貫性を Azure Stack および促進するためのイノベーションを継続的に提供しています。</p>


  <p>&rsquo;ここでは、発表のランダウンと、起動後のいくつかの重要な更新の要約について説明します。</p>


  <h2>エッジ上の IoT と AI</h2>


  <p>Azure サービスにデータを取り込むことができる &rsquo; 場合、Azure Stack によって azure アプリケーションプラットフォームが拡張され、azure サービスがデータに取り込まれます。 ネットワーク待機時間が短い、または完全に切断されているエッジシナリオでは、これは特に重要です。</p>


  <p>エッジは、接続が制限されている場所で定期的に運用されているが、クラウドの機能を使用したいと考えているユーザーにとって特に価値があります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ca668cef-6672-4d5d-9249-8c067aa1433c.png"><img align="left" alt="Chevron" border="0" height="69" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/17b4c0d6-3e77-4dad-a216-f8de69ff4000.png" style="margin: 6px 14px 0px 0px; border: 0px currentcolor; border-image: none; float: left; display: inline; background-image: none;" title="シェブロン " width="61"> </a> &quot; シェブロンは従来のテクノロジに投資しています。クラウドは、データを最適化し、新しい方法でビジネスに価値を提供するのに役立ちます。 &rsquo;このように、Microsoft Azure Stack のような強力なハイブリッドクラウドソリューションを使用することをお &rsquo; 勧めします。これにより、場所に関係なくクラウドの能力を活用し、データ主権やその他の規制に準拠した状態を維持することができます。 Azure Stack と Azure を使用する機能は、接続が保証されていない環境でシェブロンが動作するため、お客様のビジネスを変革するためにさらに多くの使用を検討することを目指しています。 &quot; Victoria Harris、マネージャー、パブリッククラウド、シェブロン</p>


  <ul>
   <li>Azure IoT チームは最近2018、 <a href="https://blogs.microsoft.com/iot/2018/04/23/hannover-messe-2018-manufacturers-put-their-trust-in-microsofts-industrial-iot-platform/" target="_blank"><strong>Azure Stack の Azure IoT ハブが開発中で</strong></a>あることを発表しました。 この作業により、お客様とパートナーは、部分的または完全にオンプレミスまたはエッジシナリオで実行される工業型の IoT ソリューションを構築できます。</li>
   <li>エッジで AI を使用してすぐに起動して実行する必要があるお客様は、現在、Microsoft <strong>Machine Learning サーバーを Azure Stack marketplace で入手でき</strong>ます。 この marketplace イメージを使用すると、R server と Azure Machine Learning ワークベンチを使用して作業環境を簡単に作成できます。</li>
  </ul>


  <h2>ハイブリッドクラウドアプリケーションとツール</h2>


  <p>Azure Sdk では、Azure と Azure Stack の両方を対象とすることができます。つまり、両方のクラウドに対して言語と同じ開発モデルを選択できます。 現在、Azure SDK では、Azure Stack での、ゴー、Ruby、Python 用の API プロファイルがサポートされています。 <strong>.NET およびその他の言語の API プロファイル機能をこの夏の後の方で有効にすることで、引き続き Azure SDK サポートを Azure Stack に拡張していき &rsquo; ます。</strong> また、Azure Stack の最新機能を表す <strong>新しい API プロファイルも公開</strong> しています。 API バージョンのプロファイルの詳細については、こちらの <a href="https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-version-profiles" target="_blank">ドキュメント</a>を参照してください。</p>


  <h2>ハイブリッド DevOps</h2>


  <p>ハイブリッドクラウドは、アプリケーションとデータのホスト方法に柔軟性を必要とする組織のために、従来の問題点の多くを削除しましたが、多くの場合、Azure と Azure Stack で最新の DevOps をサポートする方法を尋ねられます。 Visual Studio Team Services (VSTS) でホストされている<strong>DevOps サービスが、Azure と Azure Stack を使用した CI/CD などの DevOps シナリオをサポートするように拡張されて</strong>いることを発表します。</p>


  <p>具体的には、 <strong>VSTS Release Management (RM) で Azure Stack サブスクリプションに接続する機能を追加</strong>しました。 &rsquo;また、 <a href="https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update2" target="_blank">tfs 2018 Update 2 GA リリース</a>でも、オンプレミスの Team Foundation Server (tfs) のお客様に同じ機能を提供しています。 この新機能により、お客様の環境がどのように構成されているか (Azure、Azure Stack またはハイブリッドクラウドのシナリオでも) に関係なく、vsts Release Management のオンデマンドデプロイ、または vsts または TFS を使用した CI/CD パイプラインの一部として、アプリケーションを簡単にデプロイできるようになります。</p>


  <p>この機能を利用するには、既存のアプリケーションに対するコードの変更をゼロにする必要があります。 他の VSTS RM デプロイターゲットと同じ機能を使用して Azure Stack に接続するだけで、リリース定義エディター内の [Azure サブスクリプション &rdquo; ] ドロップダウンから &ldquo; 有効になります。</p>


  <h2>ハイブリッドクラウドアプリケーション</h2>


  <p>&rsquo;また、Azure と Azure Stack の作業を始めるのに役立つ<strong>ハイブリッドクラウドアプリケーションソリューションの最初のラウンドを公開</strong>します。 まず、接続、id、CI/CD の作成に関する基本事項を説明 &rsquo; します。</p>


  <p>今後もさらに高度なパターンがリリースされ、 <a href="https://aka.ms/azsdevtutorials" target="_blank">ソリューションのページ</a>で詳細を確認できるようになります。</p>


  <h2>1つの Azure エコシステム</h2>


  <p>Microsoft では、お客様が適切なソフトウェアをインフラストラクチャと照合して実行するための選択肢と柔軟性を提供しています。 Azure Stack は、次世代のクラウドネイティブアプリケーションについて、その基本的な約束を拡張するのに役立ちます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a557a746-d55f-4b6d-9084-97c8836e7537.png"><img alt="Microsoft Azure Stack" border="0" height="814" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a2a7a8e7-09c3-4ff5-86f5-70037f59cf20.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Microsoft Azure スタック" width="1513"></a></p>


  <ul>
   <li>Azure Stack チームは、<strong>テンプレート化 Service Fabric クラスターと Kubernetes クラスターのプレビューリリースを発表</strong>します。 これは、Azure Stack の IaaS 機能を使用して、マイクロサービスとコンテナーベースのワークロードを実行するのに役立ちます。 このようにして、お客様はクラウドのネイティブワークロードに投資し、オンプレミスにデプロイすることができます。 この作業により、Azure Stack ユーザーの展開と運用が簡素化され、標準化されます。 <a href="https://aka.ms/azsk8" target="_blank">Kubernetes テンプレート</a>と<a href="https://aka.ms/azssf" target="_blank">Service Fabric テンプレート</a>の使用方法の詳細については、こちらを参照してください。</li>
   <li>非常に重要な Cloud Foundry 2.2 は6月に Azure Stack に GA することを発表しました。 &ldquo;非常に優れた Cloud Foundry と Azure Stack を組み合わせることにより、ハイブリッドな一貫性を実現し、オンプレミスとクラウドで運用効率と開発者の生産性を向上させることができます。 PCF と Azure Stack では、すぐに作業を開始できます。 &rdquo;&ndash;アンドリュース、VP 製品、非常に重要です。 Azure および Azure Stack の重要な Cloud Foundry の詳細については、非常に重要な <a href="https://aka.ms/pcfonazurestack" target="_blank">ブログ</a>記事をご覧ください。</li>
  </ul>


  <h2>過去6か月間の継続的イノベーション</h2>


  <p>Azure Stack は、継続的なイノベーションを通じて Azure との一貫性を維持するように設計されています。 これまで数か月にわたって、開発者が調べる重要な項目がいくつかあります。</p>


  <ul>
   <li><strong>Azure Stack では、複数の障害ドメインにわたる可用性セットがサポートされるようになりました。</strong> クラウドアプリケーション開発者は、Azure の可用性セットを使用して、ワークロードの高可用性を確保し、基盤となるメンテナンスや停止から保護することができました。 Azure Stack によって、この機能を独自の施設に持ち込むことができます。</li>
   <li><strong>Azure Stack で Azure Storage Services API バージョン2017-04-17 をリリースしました。</strong> これにより、Azure Stack のユーザーは url から URL へのコピーを実行できるようになり、Azure と Azure Stack 間でのデータの移動が簡単になります。 これは、Azure と Azure Stack にまたがるハイブリッドアプリケーションの作成を検討しているお客様に特に役立ちます。</li>
   <li><strong>Azure Stack のコンプライアンス評価レポートが完了しました。</strong> お客様がクラウドアプリケーションのカスタムの規制要件を満たすのを支援することは、Azure Stack に対するチャーターの1つです。 &rsquo;それに伴い、お客様がこの複雑で時間のかかるタスクを移動するのに役立つ、多くの業務を再実行しています。 レポートの詳細と、それらのレポートをアーキテクチャに組み込む方法については、 <a href="https://azure.microsoft.com/en-us/blog/compliance-assessment-reports-for-azure-stack-are-now-available/" target="_blank">ブログの投稿</a>をご覧ください。</li>
  </ul>


  <p>これ &rsquo; は、バックグラウンドで行われていた作業の一部を共有するのに常に魅力的です。 ご意見やご感想をお聞かせください。また、 <a href="https://aka.ms/AzureStackUserVoice" target="_blank">ユーザーの声</a> コミュニティで Azure Stack を&#39;してください。</p>


  <p>Natalia Mackevicius<br>

  パートナーディレクタープログラム管理、Azure Stack<br>

  @natmack</p>
