### YamlMime:Yaml
ms.openlocfilehash: 88775a7f8a9c3504560d350c36e63b30ff14c095
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905215"
Slug: new-set-of-hybrid-cloud-test-environments
Title: ハイブリッド クラウド トピックでの新しいシミュレートされたビジネス アプリケーション
Summary: Azure サブスクリプションのみを使用すると、簡略化されたイントラネットと別の Azure 仮想ネットワークへの VNet 間接続を備え、ハイブリッド クラウドで一行のビジネス アプリケーションをシミュレートできます。
Content: >-
  <p>「 <a href="https://azure.microsoft.com/documentation/articles/virtual-machines-windows-ps-hybrid-cloud-test-env-lob/">テスト用にハイブリッド クラウドに Web ベースの LOB</a> アプリケーションをセットアップする」トピックでは、Web ベースの業務 (LOB) アプリケーションをテストするためのシミュレートされたハイブリッド クラウド環境を作成する手順について説明します。 この環境では、シミュレートされたオンプレミス ネットワークと Azure 仮想ネットワークで実行されているサーバーの間で VNet&nbsp; 間接続が使用されます。 完成すると次のような構成になります。</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4299a1d5-ec28-4f64-b9bd-3592d7330f9a.png"></p>


  <p>サーバーを設定し、LOB1 に LOB アプリケーションを読み込むと、CLIENT1 コンピューターからのアクセスの実験を開始できます。</p>


  <p>この環境を使用して、Azure 仮想ネットワークから実行されている Web ベースの LOB アプリケーションを実稼働環境にデプロイする前に作成およびテストした経験を得る。</p>
