### YamlMime:Yaml
ms.openlocfilehash: d61366eee044c1d384cc5aceed1c060f3a4022ab
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892868"
Slug: new-azure-web-sites-feature-configurable-environment-variables-2
Title: '新しい Azure Web サイト機能: 構成可能な環境変数'
Summary: Azure で最も人気のある強力な機能の 1 つは XML ドキュメント変換 (XDT) です。この機能を使用すると、Windows Azure Web サイト内の ApplicationHost.config ファイルのコンテンツを変換できます。
Content: >-
  Azure で最も人気のある強力な機能の 1 つは XML ドキュメント変換 (XDT) です。この機能を使用すると、Windows Azure Web サイト サイト内の <strong>ApplicationHost.config</strong> ファイルのコンテンツを変換できます。 このプロセスを使用して、 <a href="https://www.windowsazure.com/en-us/develop/nodejs/common-tasks/publishing-with-git/">Kuduand Monaco などのサイト拡張機能を</a> インストールできます。 サイト拡張機能を使用すると、Azure Web サイトの一般的な機能は事実上制限なしです。


  3rdparty サイト拡張機能の課題の 1 つは、その多くで特定の構成設定が必要な点です。<sup></sup>  たとえば、 <a href="https://docs.newrelic.com/docs/dotnet/azure-web-sites">New Relic .NET</a>  エージェントには、いくつかの構成キー (COR_ENABLE_PROFILING、COR_PROFILER、COR_PROFILER_PATH、NEWRELIC_HOME) が必要です。 これは、(適切な場所にカスタム  <a href="https://azure.microsoft.com/en-us/documentation/articles/web-sites-transform-extend/">XDT</a> を削除して) Azure Web サイトにエージェントをインストールするときに開発者が行うのは難しいものではありませんが、New Relic がエージェントの自動インストーラーを作成する必要がある場合は、これまではそうする方法が必要でした。


  これを支援するために、最近、この種の自動化を可能にする新しい機能が追加されました。 この新機能により、サイト拡張機能の開発者は、XDT を使用して の構成キーを追加できます。 これを使用するには、コードを変更し、次の形式を使用してキーを XDT に追加する必要があります。


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1714/1374.Erez-code.png"><img class="aligncenter" alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1714/1374.Erez-code.png" border="0"></a>


  これは、拡張機能の設計に応じて、サイト ルートの下、またはグローバルの下に置くことができます。 XDT を使用して値を設定すると、Azure によって自動的にこれらの値がプルされ、環境変数としてワーカー プロセスにプラグインされ、拡張機能で使用できます。 サイト拡張機能と XDT の詳細については、この記事 <a href="https://azure.microsoft.com/en-us/documentation/articles/web-sites-transform-extend/">を参照してください</a>。
