### YamlMime:Yaml
ms.openlocfilehash: 7951c2c49183bed869dff42cd61fc960cf4617c2
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904649"
Slug: new-app-usage-monitoring-capabilities-in-application-insights
Title: Application Insights の新しいアプリの使用状況の監視機能
Summary: Azure 監視ツールの目標は、アプリケーションの完全な監視機能を提供することです。 この "stack" の一番上は、アプリのクライアント側ではなく、ユーザー自身です。 理解しています...
Content: >-
  <p>Azure 監視ツールの目標は、アプリケーションの完全な監視機能を提供することです。 この &ldquo; スタック &rdquo; &rsquo; の最上位は、アプリのクライアント側ではなく &rsquo; 、ユーザー自身です。 ユーザーの行動を理解することは、ビジネスにとって関心のあるメトリックを推進するために、アプリに適切な変更を加えることが重要です。</p>


  <p>Application Insights の使用状況分析ツールの最近の機能強化により、チームは全体的な使用状況をより深く理解し、カスタマーエクスペリエンスに対するパフォーマンスの影響について深く掘り下げ、ユーザーフローの可視性を向上させることができます。</p>


  <h2>ユーザー、セッション、イベントに対するより高速で洞察力のあるエクスペリエンス</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/764d0829-35c1-4c30-b251-abeec286f1e0.jpg"><img alt="users" border="0" height="1113" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/884a05b9-bf56-4288-bf48-67679e260b81.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="ユーザ" width="2000"></a></p>


  <p>アプリケーションの使用状況を理解することは、開発チームとのスマートな投資に不可欠です。 アプリケーションは、高速で信頼性が高く、高可用性を実現できますが、多くの &rsquo; ユーザーがいない場合 &rsquo; は、ビジネスに貢献する価値はありません。</p>


  <p>Application Insights のユーザー、セッション、およびイベントの各ツールを &ldquo; 使用すると、最も基本的な使用状況分析の質問に簡単に答えることができます。アプリケーションとその機能がどの程度使用されるか。&rdquo;</p>


  <p>ユーザー、セッション、およびイベントツールを再構築して、応答性を向上させる&#39;ます。 日単位および月単位の使用状況メトリックの新しいサイドバーは、成長と保有期間の傾向を把握するのに役立ちます。 各メトリックをクリックすると、月間アクティブユーザー (MAU) を分析するためのカスタムブックのような詳細が表示されます。 また、新しい &ldquo; [ユーザー &rdquo; への会う] カードによって、一部の顧客の靴が体験され、タイムラインでステップバイステップの手順に従うことができます。</p>


  <p><a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-segmentation" target="_blank">ユーザー、セッション、イベント</a>の詳細については、こちらを参照してください。</p>


  <h2>影響ツールの概要</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a6b7ffec-efc6-41bf-abd7-6cd5cdbe3aa0.jpg"><img alt="impact" border="0" height="1113" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/672a6fdf-6215-4ece-b008-0ecf3dba42e9.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="よる" width="2000"></a></p>


  <p>低速のページでは、アプリでユーザーエンゲージメントの問題の原因が読み込まれますか。</p>


  <p>Application Insights の新しい影響ツールを使用すると、簡単に見つけることができます。アプリ内のページとそのページのユーザー操作を選択するだけで、影響ツールはページの読み込み時間別に変換率をグラフします。 これにより、パフォーマンスが本当にユーザーによって変化する可能性があるかどうかを簡単に特定できます。</p>


  <p>影響ツールは、パフォーマンスへの影響だけでなく、より多くの分析を行うことができます。 テレメトリと換算率の任意のプロパティまたは測定値の相関関係を探すことができます。 これにより、国、デバイスの種類などによって変換がどのように変化するかを確認できます。</p>


  <p>チームでは、影響ツールが、低速のページ読み込み時間が換算率の低下と密接に関連付けられているいくつかの場所を明らかにしています。 さらに、影響ツールは、目標としているページの読み込み時間を定量化しています。これは、まだ高いコンバージョン率を保持している最も低速なページ読み込み時間です。</p>


  <p><a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-impact" target="_blank">影響ツール</a>の詳細については、こちらを参照してください。</p>


  <h2>User Flows のその他の機能</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7a5b4263-832d-4804-9924-aa56ab319989.jpg"><img alt="userflows" border="0" height="1113" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6e203740-d61e-4ede-9f1b-384776fb15e7.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="userflows" width="2000"></a></p>


  <p>User Flows ツールを使用すると、後で行った内容に加えて、サイト内のページまたはカスタムイベントにアクセスする前にユーザーが何をしたかを分析できます。 [新しい &ldquo; セッション開始 &rdquo; ] ノードでは、ユーザーセッションの最初のノードが表示されます。これにより、ユーザーがサイトにどのように入力しているかを特定できます。</p>


  <p>新しい [分割] オプションを使用すると、プロパティ値によってノードをセグメント化することで、より詳細な User Flows 視覚化を作成できます。 たとえば、 &rsquo; チームがボタンをクリック &rdquo; したときのよう &ldquo; に、非常に汎用的な名前を持つカスタムイベント名を収集しているとします。 ボタン名 &rdquo; の &ldquo; カスタムディメンションで分割することによってクリックされたボタンを分離することにより、ユーザーの動作をよりよく理解できます。 次に、視覚エフェクトでは、ボタン名が [保存]、 &ldquo; &rdquo; &rdquo; ボタンがクリックされたときにボタンがクリックされたとき &rsquo; にボタンが &ldquo; クリックされた効果をノードが表示されます。</p>


  <p>User Flows につい &rsquo; てもいくつかの点が改善されました。 視覚エフェクトがより小さい画面サイズに適合するようになりました。 [ツアー &rdquo; ] ボタンを &ldquo; クリックすると、User Flows ツールをさらに活用する方法についての詳細な手順が表示されます。 また、ノードを非表示にしたり表示したりすると、視覚化に関する情報の密度を簡単に制御できるようになります。</p>


  <p>詳細については、 <a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-flows" target="_blank">User Flows</a>を参照してください。</p>
