### YamlMime:Yaml
ms.openlocfilehash: b8ed06c6b1a5da9ec6221ac2bd9dc5b60cf8c770
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905218"
Slug: new-options-to-modernize-your-application-with-azure-sql-database
Title: Azure SQL Database でアプリケーションを最新化するための新しいオプション
Summary: 今日のクラウド中心の世界において、企業は、クラウドプロバイダーに依存しながら、自社のニーズに合わせてスケーリングできる手頃な価格の魅力的なコンピューティングインフラストラクチャを提供しつつ、自社のコアコンピテンシーに注力しています。 管理されたサービスを使用することによって、市場投入までの時間を短縮し、最終的にビジネスを促進することができます。
Content: >-
  <h2>お客様のビジネスに注力し、残りの部分はそのままにしてください</h2>


  <p>今日 &rsquo; のクラウド中心の世界において、企業は自社のクラウドプロバイダーに依存しながら、自社のニーズに合わせてスケーリングできる手頃な価格の魅力的なコンピューティングインフラストラクチャを提供しながら、コアコンピテンシーに注力しています。 管理されたサービスを使用することによって、市場投入までの時間を短縮し、最終的にビジネスを促進することができます。</p>


  <p>Azure SQL Database は、急速に成長し、完全に管理されたサービスとしてのリレーショナルデータベース (dbaas) であり、世界中の38データセンターにわたって何百万もの運用データベースを管理します。 お客様は、単純なトランザクションデータの管理から、高度なデータ処理を世界規模で行う必要がある、大量のデータを処理するミッションクリティカルなアプリケーションの実行まで、さまざまなアプリケーションやワークロードをサポートするために Azure SQL Database を利用できます。</p>


  <p>このブログ投稿では、プラットフォームを区別する業界最先端の機能の例をいくつか紹介し、魅力的な新機能を発表します。また、お客様が業界で最もスケーラブルで安全かつ顧客に対応したデータベースサービスを維持するために、プランの更新を共有します。</p>


  <h2>新しい発表: すべてのアプリケーションの PaaS へのリフトアンドシフトを簡単に</h2>


  <p>クラウド業界が成熟していて、より多くの企業が標準的な手法としてクラウドテクノロジを採用しているので、データベースコミュニティのお客様と話してきまし &rsquo; た。 クラウドで管理されたデータベースサービスのメリットを享受することを望んでいますが、それまでは、インスタンスレベルの機能や分離要件によってこれを行うことができませんでした。 インスタンスレベルの SQL Server 機能に対してディープな投資を行っているお客様 (SQL CLR 統合、SQL Server エージェント、クロスデータベースクエリなど) では、Azure SQL Database で同様の機能が期待されます。 同様に、高度に規制された業界のお客様は、クラウドへの移行時に、セキュリティを確保するために分離を維持する必要があります。</p>


  <h3>マネージド インスタンス</h3>


  <p>本日、Azure SQL Database <strong><em>Managed Instance</em></strong>と呼ばれる新しい配置オプションのプレビューを発表しました。 &nbsp;Managed Instance は、サービスとしてのプラットフォームの利点と 100% SQL Server の互換性を提供します。 これには、SQL CLR、SQL Server エージェント、データベース間クエリなどの機能が含まれます。 マネージ SQL Server 環境で、アプリケーションの設計 &ndash; <strong> &rsquo; </strong>を変更せずに引き続きインスタンスレベルの機能を使用する場合は、実際のゲームチェンジャーです。&nbsp;</p>


  <p>ESignature とデジタルトランザクション管理 (DTM) のグローバルリーダーである DocuSign は、作業環境で Managed Instance プライベートプレビューをテストする最初の顧客でした。 30万を超えるお客様と2億の188ユーザーを対象とする会社では、データベースのスケーラビリティ、パフォーマンス、および管理容易性はミッションクリティカルです。 また、テストでは、DocuSign は、コアプラットフォームの SQL Server コードを変更せずに Managed Instance にリフトアンドシフト &rsquo; し、クエリの実行を数秒 &ndash; で開始する &lsquo; ことができました。この場合、その主要な設計者である Eric Fleishman は、今後のすばらしい約束を示しています。</p>


  <p>また、Managed Instance 移行を自動化し、リスクを軽減し、ダウンタイムを分単位で測定して、新しい<strong>Database Migration Service &nbsp; </strong>を発表 &nbsp;&#39;ます。 &nbsp;このサービスにより、Oracle などの Microsoft 以外のデータベースシステムを Azure SQL Database に SQL Server 移行する処理が効率化されます。</p>


  <p>高度に規制された業界のお客様にとって、 &rsquo; vnet は、プライベート IP アドレスのサポートとサービス更新の制御という2つの重要なイノベーションをもたらします。 Vnet を使用すると、お客様はデータベース層をパブリックインターネットから完全に分離し、そのアプリケーションとユーザーが存在する他のクラウド Vnet またはオンプレミスネットワークに参加することができます。 管理されたサービスの更新により、お客様は、通常の Azure パブリッククラウドサブスクリプションにデプロイされたテスト環境を実行できます。このサブスクリプションでは、継続的なサービス更新を受け取ることができます。 最新の更新プログラムを使用してアプリケーションを検証した後、スケジュールされた方法で更新プログラムを運用 Managed Instance 環境に適用できるようになります。</p>


  <p>Managed Instance は現在、 &rsquo; プライベートプレビュー (<a href="https://sqldatabase-migrationpreview.azurewebsites.net/" target="_blank">サインアップページ</a>) にあります。この段階では、最初に導入された顧客と連携して、既存のアプリケーションの最大セットに対するリフトアンドシフト &rdquo; の要件を満たし &ldquo; ていることを確認します。 アプリケーションが Azure SQL 管理されたデータベースインスタンスで動作することを確認したいと考えている場合、または独自の移行作業に使用する場合、詳細については、今すぐ<a href="https://info.microsoft.com/sql-database-managed-instance-register.html">登録</a>してください。</p>


  <p>Managed Instance オファリングを使用すると、これまでの Azure SQL Database の利点を享受するためのパスを持たない SQL Server お客様にとって、現在はクラウドへのブリッジ (またはラダー) を提供しています。</p>


  <h2>イノベーションと進化</h2>


  <p>新しい Managed Instance オファリングで導入された進化した変更と共に、このプレミアプラットフォームをサービスとして提供することにより、パフォーマンス、インテリジェンス、可用性、スケーラビリティ、およびセキュリティに関する革新的な革新を継続的に提供しています。</p>


  <h3>組み込みのインテリジェントな最適化</h3>


  <p>Azure SQL Database を選択すると、組み込みのパッチ、更新、データベースバックアップ、および高可用性が得られるだけでなく、<em>インテリジェンスも組み込ま</em>れています。 組み込みのインテリジェンスにより、データベースの実行と管理にかかるコストを劇的に削減し、アプリケーションのパフォーマンスとセキュリティの両方を最大限に高めることができます。 &nbsp;この機能により、SQL Database Advisor、自動チューニング、アダプティブクエリ処理が用意されています。</p>


  <h4>[SQL Database Advisor]</h4>


  <p>時間の経過と共に何百万もの顧客ワークロードを実行すると、Azure SQL Database は大量のテレメトリデータを収集して処理しながら、バックグラウンドで顧客のプライバシーを完全に尊重します。 アプリケーションの状況をサービスが学習し、状況に適応することができるように、さまざまなアルゴリズムによって利用統計情報が継続的に評価されます。 この分析に基づいて、サービスは、特定のワークロードに合わせたパフォーマンスの向上に関する推奨事項を考え出すことができます。&nbsp;</p>


  <p>この組み込みインテリジェンスはどの程度の方法で表示されますか。 Azure SQL Database は、<a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-advisor" target="_blank">適切な非クラスター化インデックスを自動的に識別</a>して作成または削除し、実行可能な推奨設定として顧客に提供します。または、顧客が自動チューニングモードにする場合は、データベースへの変更を事前に実装します。 また、機能によって、各アクションが自動的にテストおよび検証され、パフォーマンスが向上し続けます。 これは、データベースのパフォーマンスが注意深く監視され、すべてのチューニング操作の前後に比較されることを意味します。また、パフォーマンス &rsquo; が向上しない場合は、チューニングアクションが元に戻されます。</p>


  <h4>自動チューニング</h4>


  <p>SQL Database Advisor で既に使用可能な自動インデックスチューニングに加えて、Azure SQL Database は新しい適応性機能の配列をすぐに受け取ることになります。 たとえば、クエリプラン<a href="https://docs.microsoft.com/en-us/sql/relational-databases/automatic-tuning/automatic-tuning" target="_blank">の自動チューニング</a>機能を使用すると、クエリプランの選択肢に対して安全 &rdquo; な &ldquo; 手段が提供されるため、プランの回帰を自動的に修正することで、データベースを常に最高のパフォーマンスで実行できます。 現在、Azure SQL Database 上で SaaS マルチテナントアプリを実行しているパートナーの &nbsp; 多くは、アプリケーションが常に安定し、予測可能なパフォーマンスを確保するために、 &nbsp; 自動パフォーマンスチューニングに依存しています。 パートナーにとって、この機能は、真夜中にパフォーマンス上の問題が発生するリスクを大幅に軽減するものです。 さらに、顧客ベースの一部でも SQL Server が使用されるため、Azure SQL Database によって提供されるものと同じインデックス作成の推奨事項を使用して、SQL Server の顧客を支援します。</p>


  <h4>アダプティブ クエリ処理</h4>


  <p>また、<a href="https://blogs.msdn.microsoft.com/sqlserverstorageengine/2017/04/19/introducing-interleaved-execution-for-multi-statement-table-valued-functions/" target="_blank">複数ステートメントのテーブル値関数のインターリーブ実行</a>、<a href="https://blogs.msdn.microsoft.com/sqlserverstorageengine/2016/11/29/introducing-batch-mode-adaptive-memory-grant-feedback/" target="_blank">バッチモードのメモリ許可のフィードバック</a>、<a href="https://blogs.msdn.microsoft.com/sqlserverstorageengine/2017/04/19/introducing-batch-mode-adaptive-joins/" target="_blank">バッチモードのアダプティブ結合</a>など、機能のアダプティブクエリ処理ファミリも Azure SQL Database に追加します。 これらのアダプティブクエリ処理機能は、同様 &ldquo; の学習手法と適合 &rdquo; 手法を適用し、従来の困難クエリの最適化の問題に関連するパフォーマンスの問題に対処するのに役立ちます。</p>


  <h3>グローバルなスケーラビリティと可用性</h3>


  <p>Azure SQL Database には、自動バックアップ、特定の時点への復元、<a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-geo-replication-overview" target="_blank">アクティブ Geo レプリケーション</a>など、すぐに使用できるビジネス継続性とグローバルスケーラビリティの機能が用意されています。これにより、同じまたはグローバルに分散した Azure データセンターで最大4つの読み取り可能なセカンダリデータベースを構成できます。 &nbsp; たとえば、同時実行の読み取り専用トランザクションの数が多いカタログデータベースを持つ SaaS アプリケーションがある場合、アクティブ Geo-Replication では、グローバルな読み取りスケールを有効にし、読み取りワークロードに起因するプライマリ上のボトルネックを削除できます。 &rsquo;さらに、最近リリースされた<a href="https://azure.microsoft.com/en-us/blog/azure-sql-database-now-supports-transparent-geographic-failover-of-multiple-databases-featuring-automatic-activation/">自動フェールオーバーグループ</a>により、高可用性と負荷分散をグローバルなスケールで有効にすることができます。これには、透過的な geo レプリケーションや、大規模なデータベースとエラスティックプールのフェールオーバーが含まれます。 これにより、管理オーバーヘッドを最小限に抑えながら、グローバル分散型 SaaS アプリケーションを作成できるため、すべての複雑な監視、ルーティング、およびフェールオーバーオーケストレーションを SQL Database できます。</p>


  <h3>業界トップレベルの高度なセキュリティ</h3>


  <p>最高レベルのプライバシーを維持したまま顧客データをセキュリティで保護することは、常に Microsoft および Data Services 組織の最優先事項となっています。 私はこれまでの <a href="https://blogs.technet.microsoft.com/dataplatforminsider/2017/02/10/microsofts-sql-platform-continues-to-lead-the-market-with-advanced-data-security/" target="_blank">セキュリティ投資</a> について、業界最高レベルのセキュリティを実現する業界最先端のセキュリティ機能を提供してきました。 サービスには、Transparent Data Encryption、SQL の脅威検出、Always Encrypted、Multi-Factor Authentication などが含まれます。</p>


  <h4>透過的なデータ暗号化</h4>


  <p>セキュリティは、効果的に使用するために簡単に使用できる必要があることを認識しています。 たとえば、今月からは、新しく作成されたすべての Azure SQL データベースが Transparent Data Encryption (tde) で自動的に保護されます。 tde は、記憶域メディアの盗難から保護するために多くのコンプライアンス標準で必要とされる、実証済みの暗号化された暗号化テクノロジを SQL &rsquo; します。 お客様は、Azure Key Vault を使用して、セキュリティで保護された準拠管理で TDE 暗号化キーとその他のシークレットを管理できます。</p>


  <p>gep は、Azure SQL Database と tde を使用するクラウドベースの調達ソフトウェアプラットフォームを提供する多国籍企業です。 &nbsp;独自の言葉で、次のようになります。</p>


  <blockquote>

  <p>&ldquo;Azure managed TDE は、お客様の厳格なデータ暗号化ポリシーに準拠するために役立っています。また、多数のデータベースを安全に管理することも &nbsp; できます。 主な利点は、アプリケーションのパフォーマンスに影響を与えずに、すべてのお客様に TDE 暗号化を提供できることです。 &rdquo; Sathyan Narasingh, Engineering Manager with GEP</p>

  </blockquote>


  <h4>SQL の脅威検出</h4>


  <p>さらに、 <a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-threat-detection" target="_blank">SQL の脅威検出</a>では、機密データへのアクセスが害を及ぼす可能性のあるデータベースを継続的に監視します。 たとえば、電子ラーニング企業の場合、SQL の脅威の検出では、企業が従業員 &rsquo; の資格情報を無効にした後に機密データを盗み出すした、不満を持つ従業員の行動を特定しました。 SQL 脅威の検出は、現在過去のアクセスの場所とクエリパターンを比較し、アラートを生成して、顧客がリークを迅速に終了して損害を最小限に抑えることができるようにしました。</p>


  <h4>Always Encrypted</h4>


  <p>Azure SQL Database は、転送中、保存中、Always Encrypted を使用したクエリ処理中に、機密データの保護を提供する唯一のデータベースシステムです。 Always Encrypted は、重要なデータの盗難を含む侵害に対する、これまでにないデータ セキュリティを提供する業界初の機能です。 たとえば、 <a href="https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine" target="_blank">Always Encrypted</a>では、顧客 &rsquo; のクレジットカード番号は、クエリ処理中であっても、データベースに <u><em>常</em></u>に暗号化されて格納されます。これにより、そのデータを処理する必要がある承認されたスタッフまたはアプリケーションによって使用される時点で復号化が可能になります。</p>


  <p>次に、非常に <a href="https://www.medproctor.com/">急速に成長</a>する医療を開始するための Always Encrypted - 方法を示します。</p>


  <blockquote>

  <p>&quot;多くの場合、医療およびスタートアップ SaaS プロバイダと、最新で監査が容易なデータセキュリティの間にかなりのギャップがあります。 &nbsp;独自のソリューションを作成したり、高価なサードパーティのツールを購入したりすることなく、列の暗号化、管理されたアクセス、キーローテーションのためのツールを提供することにより、Med-v のギャップを Always Encrypted ブリッジします。 &quot; -Andy の、CIO、 <a href="https://www.medproctor.com/">med-v</a></p>

  </blockquote>


  <h4>Multi-Factor Authentication</h4>


  <p>Azure SQL Database のユーザーは、Multi-Factor Authentication (MFA) もサポートする Azure Active Directory 認証を使用したシングルサインオンを利用できます。 MFA は、SSMS や Visual Studio など、SQL Server および Azure SQL Database 全体のツールとサービスの数が増えている場合に機能する認証オプションです。</p>


  <h2>境界のプッシュ</h2>


  <p>Azure SQL Database は、すべてのデータを集中的に使用するアプリケーション用の強力なプラットフォームを提供し、ワークロードをクラウドに簡単に移行できなくなりました。 今後、次 &nbsp; の4つの領域に境界がプッシュされます。</p>


  <p><strong>スケール: </strong>数か月前に、エラスティックプールに対して価格パフォーマンスの選択肢を追加しました。これには、最大で 4000 Dtu、より小さい 50 DTU プール、低い開始価格の低 DTU プール、プールあたりのデータベース制限を増やし、データベースあたりのコストを効果的に削減できます。 4月に、P11 および P15 データベースのストレージの上限を 1 TB から 4 TB に増やしました。 &nbsp;また、場合によっては、最大プレミアムエラスティックプールの記憶域の上限が 750 GB から 4 TB に増加しました。 &nbsp;今後数か月にわたって、Azure SQL Database によってストレージの制限がさらに増加し、スタンドアロンデータベースとエラスティックプールの両方で dtu とは別にストレージを購入できるようになります。</p>


  <p><strong>監視:</strong> 最近、クラウドデータベースからの重要なメトリックを大規模に監視し、集中管理された場所から関心のあるメトリックに対してアラートを設定するために役立つ <a href="https://blogs.technet.microsoft.com/msoms/2017/02/21/azure-sql-analytics-solution-public-preview/" target="_blank">OMS ソリューション</a> をリリースしました。 間もなく、このソリューションは高精度のクエリインサイトで強化され、すべてのクラウドデータベースで実行されている高度な &ldquo; フライトデータレコーダー &rdquo; 機能 (クエリストア) によって継続的に作成される予定です。 これにより、多くのデータベースに対して同じクエリを実行する SaaS アプリケーションで貴重な洞察を得られます。また、集計のすべてのデータベースで最も多くのリソースを消費しているクエリをピンポイントすることができます。</p>


  <p><strong>組み込みのインテリジェンス:</strong> 今後数か月にわたって、自己最適化と自己監視のデータベースサービスについての構想にもより近いものになります。 この革新的なテクノロジは、昨年にわたってテストされ、成熟しています。 このように記述すると、サービス内の約5万のデータベースで既にクロックを実行しています。 <em>すべて</em>のサービスデータベースの既定の設定をパフォーマンス自動チューニングすることを計画しています。 つまり、クラウドスケールでは、非クラスター化インデックスのチューニングとメンテナンスだけでなく、すべての顧客データベースに対する自動プラン修正も提供します。 すべての開発者または Azure SQL Database を使用する Professional は、組み込みのインテリジェンスによってもたらされるパフォーマンスと安定性の向上を実現します。労力を費やす必要はありません。</p>


  <p><strong>セキュリティ:</strong>私たちの目標は、企業のお客様が Azure SQL Database ので利用できるセキュリティ機能を使いやすくして、専門知識のレベルに関係なく、データベースの効果的な防御戦略を実装して維持することです。 たとえば、SQL データベースのセキュリティ保護は、必要な保護レベル (たとえば、ビジネスに大きな影響を与える) を特定し、適切なポリシーを適用してデータベースを保護するのと同じように単純であると考えられます。 レベルを定義すると、システムは、機密データを識別するために必要なデータとデータをセキュリティで保護するために必要な機能を識別するなど、残りの処理を実行します。 データベースが使用されている間、Azure SQL Database は構成の変更と、悪意のある攻撃の兆候となる可能性がある異常なアクティビティを継続的に監視します。</p>


  <h2>はじめにのみ</h2>


  <p>Microsoft では、既定でディープセキュリティを提供する機能への投資を継続し、移行を円滑に行うことができます。また、機械学習とアダプティブ手法を利用してパフォーマンスを最適化し、最先端のリレーショナルデータベーステクノロジを使用して目標を達成することができます。 コスト削減、市場への迅速な時間、組み込みインテリジェンス、および現在提供されている組み込み管理Azure SQL Database活用してください。&nbsp;データ センター&rsquo;や運用チームは必要ない。&nbsp;代わりに、自分と組織にとって最も重要な事項に焦点を当て、残りは私たちに任せいてください。</p>


  <p>Microsoft データ グループに関するその他のお知らせについては、こちらにある「2017 年 1&rsquo; 月 <a href="https://aka.ms/m91203" target="_blank">2017</a> 年の読み上がり」のブログ投稿をお読みください。</p>
