### YamlMime:Yaml
ms.openlocfilehash: 4ce5afe44ddd252edd76b0eadd0a0c5e28255645
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904645"
Slug: new-application-insights-hol-available-in-visual-studio-2015-alm-virtual-machine
Title: Visual Studio 2015 ALM 仮想マシンで新しい Application Insights ホルを利用可能
Summary: この新しいラボは、Application Insights の主要なコンポーネントすべてを迅速に探索できるようにすることを目的としていますが、実際のライブプロジェクトに学習した内容を適用する方法を理解することができます。
Content: >-
  <p abp="709">まだ認識していないお客様にとっては、最新かつ最高の Visual Studio 2015 ALM 仮想マシンが公開されており、開発者、テスト担当者、およびプロジェクト管理者は、どこでもタイヤを開始できます。</p>


  <p abp="709">すべての既存のハンズオンラボが新しいコンテンツによって更新され、5つの新しいラボが追加されました。 プログラムマネージャーが<a abp="711" href="https://azure.microsoft.com/en-us/services/application-insights/">Application Insights</a>の ALM 機能を使用するようになったので、 &rsquo; 次の新しいラボの1つに注目してください。 <a abp="712" href="https://download.microsoft.com/download/6/2/B/62B60ECE-B9DC-4E8A-A97C-EA261BFB935E/Docs/Monitoring%20Applications%20with%20Application%20Insights.docx">Application Insights を使用したアプリケーションの監視</a>。 Application Insights は、VS2015 ALM 仮想マシンでラボを機能させるための最初のサービスベースの製品です。</p>


  <h2 abp="715">ホル: Application Insights の概要 (詳細)</h2>


  <p abp="716">この新しいラボは、Application Insights の主要なコンポーネントすべてを迅速に探索できるようにすることを目的としていますが、実際のライブプロジェクトに学習した &rsquo; 内容を適用する方法を理解することができます。 &rsquo;ラボの既存のプロジェクトから始めて、Application Insights の機能をすぐに利用できるようにします。 ホルは5つの演習に分割されています。</p>


  <blockquote abp="717">

  <p abp="718">1: Project への Application Insights の追加</p>


  <p abp="719">2: Web アプリと Web ページのテレメトリを取得する</p>


  <p abp="720">3: 追加のインストルメンテーションおよびカスタムイベント</p>


  <p abp="721">4: Web アプリを発行し、実稼働環境でイベントを監視する</p>


  <p abp="722">5: 可用性、アラート、データのエクスポートを監視する</p>

  </blockquote>


  <p abp="723">この Application Insights は視覚的に重点を置いた製品であるため、このラボでは、各演習のすべての手順でこのようなスクリーンショットを利用できます。</p>


  <p abp="724"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3535228f-4c9e-48eb-b183-e7f912c69e3b.jpg"><img alt="App Health" border="0" height="501" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7fc067bb-950f-4a59-8b20-aff66a0dc5f4.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="アプリの正常性" width="839"></a></p>


  <p abp="732">インストルメンテーションやカスタムイベント &rdquo; の追加など &ldquo; の演習にはコーディングが必要ですが、必要なコードがあれば、入力するのではなく、テレメトリを調査するのに時間を費やすことができるように、プロジェクトに単純に貼り付けることができます。</p>


  <p abp="735">この演習を初めて実行するときは、30-40 分かかることが予想されます。 &nbsp; その後、リフレッシャーとして使用する予定のすべての実行、または仕事仲間のデモとして使用する予定であれば、ほとんどの場合、20-25 分しか必要ありません。</p>


  <h2 abp="738">フィードバック</h2>


  <p abp="739">私 &rsquo; は、長年にわたり Brian Keller (元の vm の作成者) の仕事をしてきました。そのため、この vm に含まれている多くの HOLs を実行するために多くの時間を費やしています。また、お客様のための概念を紹介 &rsquo; しています。 &nbsp;また、私 &rsquo; は、個人的/専門家向けのデモンストレーション labs が非常にたくさん書かれています。 &nbsp;ただし、これは、パブリックの消費に対して独自のホルを初めて作成するときに、すべてのフィードバックを非常に評価します。 &nbsp;この特定のラボは、今後さらに高度なトピックをカバーするために (または、この記事 &ndash; の省略可能なセクション)、さらに高度なトピックを追加することを計画していることを念頭に置いてください。特に、Application Insights 成長と進化を続けるためです。 &nbsp;ラボドキュメントの下部に、VS2015 ALM VM チームに直接フィードバックを送るリンクがあります。 &nbsp;すべての入力に感謝します。</p>


  <p abp="742">次に、その VM を起動してラボを開き、テレメトリ Application Insights によって提供される非常に優れた機能をご確認ください。</p>
