### YamlMime:Yaml
ms.openlocfilehash: f9cf97a91f3b375c8f354b34fc4c5985f1d54a8f
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139896431"
Slug: new-datadog-integration-with-azure-offers-a-seamless-configuration-experience
Title: 新しい Datadog と Azure の統合により、シームレスな構成エクスペリエンスが提供されます
Summary: 新しい Azure と Datadog の統合により、組織は従来のシステムとクラウドベースのシステムを完全にマップし、クラウドへの移行のすべてのフェーズでリアルタイムのデータを監視し、移行されたアプリケーションがパフォーマンスの目標を満たしていることを確認できるようになりました。
Content: >-
  <p><em>この投稿は、Sreekanth Thirthala 氏 kata、プリンシパルプログラムマネージャー、Visual Studio および .net によって共同作成されました。</em></p>


  <p><i>Azure との Datadog の統合が</i><em>一般 &nbsp; 公開</em>され<i>、この投稿は05/28/2021 に最後に更新されました。</i></p>


  <p>Microsoft Azure を使用すると、多くのパートナーソリューションと連携して、クラウドで実行するアプリケーションを移行し、最新化することができます。 このようなパートナーの1つは <a href="https://www.datadoghq.com/">Datadog</a>です。これは、ユーザーがハイブリッド環境やマルチクラウド環境でアプリケーションの正常性とパフォーマンスを理解するための可観測性およびセキュリティツールを提供します。 ただし、必要な統合を構成するには、Azure portal と Datadog 間を頻繁に移動する必要があります。</p>


  <p>これにより、複雑さが増し、時間がかかり、動作しない場合 &rsquo; のトラブルシューティングが困難になります。 複数のポータルで管理の負担を軽減するために、Datadog を使用して、Azure クラウドプラットフォームで統合 Datadog ソリューションを作成しました。 <a href="https://azuremarketplace.microsoft.com/en-us/marketplace/" target="_blank">Azure Marketplace</a>を通じて提供されているこのソリューションは、Azure で Datadog &rsquo; s クラウド監視ソリューションを使用するためのシームレスなエクスペリエンスを提供します。</p>


  <p style="margin-left: 40px;"><i> &ldquo; Microsoft cloud は、Datadog などのサードパーティ製ソリューションを使用して、お客様にシームレスな構成と管理のエクスペリエンスを実現するための第一歩です。Datadog を使用すると、お客様はこのエクスペリエンスを利用して Azure ワークロードを監視し、クラウドへの移行を加速させることができます。 &rdquo; </i> &mdash;Microsoft の副社長である大統領サンダース氏</p>


  <p>新しい Azure と Datadog の統合により、組織は従来のシステムとクラウドベースのシステムを完全にマップし、クラウドへの移行のすべてのフェーズでリアルタイムのデータを監視し、移行されたアプリケーションがパフォーマンスの目標を満たしていることを確認できるようになりました。 この統合により、Azure &rsquo; のグローバルなプレゼンス、柔軟性、セキュリティ、コンプライアンスを Datadog&#39;s のログ記録と監視機能と組み合わせることで、企業に最適なエクスペリエンスを実現できます。</p>


  <p>この統合された経験により、お客様は次のことができるようになります。</p>


  <ul>
      <li>新しい Datadog 組織をプロビジョニングし、Azure リソースを構成してログとメトリックを Datadog &mdash; に送信します。これにより、顧客がセットアップして操作するためのインフラストラクチャがなくても、完全に管理されたセットアップを行うことができます。</li>
      <li>ログとメトリックを Datadog にシームレスに送信します。 ログ転送プロセスは完全に自動化されています。診断設定、Event Hubs、Functions とのログ転送パイプラインを構築することなく、数回のクリックだけですべてを構成できます。</li>
      <li>Datadog エージェントを VM ホストに簡単にインストールし、シングルクリックで App Services できます。</li>
      <li>シングルサインオン (SSO) を Datadog &mdash; に合理化する Datadog ポータルからの別のサインインは不要になりました。</li>
      <li>Azure サブスクリプションの請求を通じて、Datadog サービスがまとめて請求されます。</li>
  </ul>


  <p style="margin-left: 40px;"><i> &quot; 可観測性は、クラウド移行を成功させるための重要な機能です。Microsoft Azure との新しいパートナーシップにより、お客様は Azure コンソールで直接 Datadog プラットフォームにアクセスできるようになり、新しいワークロードと移行されたワークロードの移行、最適化、およびセキュリティ保護が可能になりました。 &quot; </i> &mdash;Amit Agarwal、最高製品責任者、Datadog</p>


  <p>ここ &rsquo; では、この統合されたエクスペリエンスを簡単に見てみましょう。</p>


  <p><iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" frameborder="0" height="315" src="https://www.microsoft.com/en-us/videoplayer/embed/RE4Gc2z" width="560"></iframe></p>


  <h2 style="margin-bottom: 11px;">Datadog ソリューションを取得してセットアップする</h2>


  <p style="margin-bottom: 11px;">次に、Datadog ソリューションを取得して設定する手順について説明 &rsquo; します。</p>


  <p><strong>調達 The Datadog app</strong>: azure のお客様は、azure Marketplace を通じて Datadog アプリを調達できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/962f55dd-004c-4863-ba35-4b805bbf27a1.png"><img alt="Datadog app on marketplace 1" border="0" height="862" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e4750a7f-eccb-4644-9f52-98c845047b59.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Marketplace での Datadog アプリ1" width="1024"></a></p>


  <p><strong>Azure portal でのプロビジョニング:</strong> Azure Marketplace で調達を実行した後、お客様は、Azure portal を使用して、Datadog を Azure 上の統合サービスとしてシームレスにプロビジョニングできます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/81935ee7-ee7c-4305-856e-0d101e727436.png"><img alt="Datadog overview page" border="0" height="563" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3530747f-aa81-4d24-85cf-716bea088025.png" style="display: inline; background-image: none;" title="Datadog の [概要] ページ" width="1028"></a></p>


  <p><strong>ログとメトリックの構成:</strong> お客様は、Azure で Datadog リソースを作成し、ログとメトリックを送信し、Datadog に送信する Azure リソースを構成します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4b50938a-0f8a-4830-a406-3740d61e2820.png"><img alt="Create datadog resource" border="0" height="1363" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/342da24f-144d-47a8-8dbb-43175b2bc702.png" style="display: inline; background-image: none;" title="Datadog リソースの作成" width="1296"></a></p>


  <p><strong>Datadog エージェントのインストール</strong>: お客様は、Datadog エージェントを仮想マシン (vm) と app services の拡張機能として1回のクリックでインストールできます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6357c143-1ecd-4c52-b379-576f135feeb5.png"><img alt="Installing Diagnostic Agent." border="0" height="908" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b94f951a-43e3-461e-bf72-d42e44beeee4.png" style="display: inline; background-image: none;" title="診断エージェントをインストールしています" width="1662"></a></p>


  <p><strong>SSO 経由でのアクセス:</strong> お客様は、合理化された SSO エクスペリエンスによって Azure portal から Datadog にアクセスし、Azure サービスのログとメトリックの宛先として Datadog を構成します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8c39c56f-e52e-4c76-878c-ae25bb134ac7.png"><img alt="Datadog Azure virtual machines dashboard." border="0" height="1288" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9ab94954-0532-4973-9c06-65be5838ee87.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Datadog Azure virtual machines ダッシュボード。" width="1114"></a></p>


  <h2>次の手順</h2>


  <ul>
      <li><a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/datadog1591740804488.dd_liftr_v2?tab=Overview" style="color:#0563c1; text-decoration:underline" target="_blank">Azure marketplace</a>で &nbsp; 利用可能な azure &quot; と Datadog 統合の &quot; プレビューにサブスクライブします。</li>
      <li>Azure Monitor パートナーと Datadog の統合の詳細については、<a href="https://aka.ms/datadogwithazure" target="_blank">こちらを参照</a>してください。</li>
  </ul>
