### YamlMime:Yaml
ms.openlocfilehash: 7a64e301a699ec67120698b25c786f4ab4c047ff
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904644"
Slug: new-application-insights-metric-widget-for-visual-studio-team-services
Title: Visual Studio Team Services 用の新しい Application Insights メトリックウィジェット
Summary: Visual Studio Team Services (VSTS) ダッシュボード用のメトリックウィジェットを開発しました。これは、Application Insights データをワークフローに統合するのに役立ちます。
Content: >-
  <p>Application Insights の情報を日々のワークフローに統合するための継続的な取り組みの一環として、Visual Studio Team Services (VSTS) ダッシュボードのためのメトリックウィジェットを開発しまし &rsquo; た。 このツール &rsquo; は、インストールとセットアップが非常に簡単で、Azure Portal で表示しなくても &rsquo; 、テレメトリと診断データのタブを維持するのに役立ちます。</p>


  <h3>Application Insights メトリックウィジェットの取得とインストール</h3>


  <p>[App インサイト metrics ウィジェット "> メトリック] ウィジェット </a> のダウンロードとインストール <a href="https://marketplace.visualstudio.com/items?itemName=ms-appinsights.ApplicationInsightsWidgets" target="_blank" title=" を行うには、まず、Visual Studio Marketplace で検索する必要があります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e0f0bdfd-2bfe-4fa0-ac15-111a25618671.png"><img alt="image" border="0" height="399" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c38c5091-99e2-4f48-807f-e5a7c0b21b55.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="絵" width="496"></a></p>


  <p>VSTS ダッシュボードで、画面の右下にある [編集] ボタンをクリックし、一覧に表示される [Application Insights メトリック] ウィジェットを選択します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c4867f95-4eaf-416c-bd8e-7d01571ce802.png"><img alt="image" border="0" height="399" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/710db69b-cb12-4d0b-b039-a76f7de22e1e.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="絵" width="321"></a></p>


  <p><em>[注: ウィジェットが一覧に表示されない場合は、web ページを最新の情報に更新してください。]</em></p>


  <h3>メトリックウィジェットの構成</h3>


  <p>ウィジェットを構成する準備ができました &rsquo; 。 このプロセスは非常に単純です。 Application Insights リソースからメトリックデータを返すためには、ウィジェットにアプリケーション id と API キーを提供する必要があります。 これらの2つのパラメーターを見つけるには、Azure portal で Application Insights リソースの<strong>設定/API アクセス</strong>を探します。</p>


  <p><img alt="API Acces in Azure Portal" height="398" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AppInsights_HowToFindAppIdAndApiKey.png" width="546"></p>


  <p>ウィジェットの構成ダイアログは、ダッシュボードに追加したときに自動的に開かれます。 次の手順では、アプリケーション id と API キーを [config] ダイアログボックスの適切なフィールドにコピーし &nbsp; て貼り付けます。追加の構成フィールドがアクティブになります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0ab6ccf9-535b-4fcd-977d-6f20a10ae3ed.png"><img alt="ConfigurationPageWithNotes_FakeAppIdandArrow" border="0" height="674" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d24ca4c6-f138-45b1-8068-db76c8370b6e.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="ConfigurationPageWithNotes_FakeAppIdandArrow" width="313"></a></p>


  <p>これで、追跡する必要のあるメトリックを簡単に選択できるようになりました (指定したリソースで使用可能なメトリックのみからドロップダウンリストが作成されます)。また、メトリックを追跡するために必要な集計 (合計、平均など) と時間範囲 &rsquo; も選択できます。 &rsquo;これらを入力したら、[保存 &rdquo; ] ボタン &rsquo; を押す &ldquo; だけで完了です。 VSTS ダッシュボードで、メトリックウィジェットが使用可能でアクティブになっている必要があります。</p>


  <h3>ウィジェットの使用</h3>


  <p>この時点で、 &rsquo; ウィジェットに関して必要なことはあまりありません。 当然、ダッシュボード上の目的の場所に再配置することができます。 1つ注意すべき点は、データがウィジェットで自動的に更新されるようにする場合 &rsquo; は、ダッシュボードに対して自動更新オプションを選択する必要があることです。 このオプションを見つけるには、ダッシュボードの右上にある [設定] アイコンをクリックし &ldquo; 、[ダッシュボード &rdquo; の自動更新] ボックスをオンにします。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/02ab230b-955d-47e4-96a3-1b9800c9d121.png"><img alt="image" border="0" height="403" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/74feb298-7104-4e3a-a931-a2d78b777243.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="絵" width="366"></a></p>


  <p>ウィジェットに表示される内容を明確にするために、タイトル、追跡対象のメトリック (集計)、メトリック値、および時間範囲を確認する必要があります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/425b9813-fb00-4faf-be41-ee3be951f5f4.png"><img alt="image" border="0" height="162" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/47985e53-7fa1-4203-a7aa-6afdff416f48.png" style="margin: 0px; border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="絵" width="162"></a></p>


  <p>ウィジェットをダッシュボードに複数回追加して、さまざまなメトリックや複数のリソースを同時に追跡できます。 これにより、同じ API キーに対して1分間に実行できるメトリック呼び出しの数に制限があることに注意する必要があります。 ただし、上限は60なので、非常にビジーで複雑なダッシュボードをまとめて作成 &rsquo; しない限り、 &rsquo; この制限に達しない可能性があります。 ただし、ダッシュボードに非常に多くのメトリックを同時に表示する必要がある場合は、そのシナリオを処理するために追加の API キーを生成することが必要になる場合があります。 ただし、多くの異なるメトリックを追跡している場合は、特に複数の異なるリソースで、関連するすべてのものがどのように関連しているのかを確認することをお勧めします。すべてをまとめて &rsquo; 表示する必要があることを前提として、VSTS で複数のダッシュボードを定義することができます。これにより、複数のダッシュボードを細かく分割することができます。</p>


  <p>また、多くのシナリオでベストプラクティスとなることもあります。アプリインサイトウィジェットの近くに配置する基本的な markdown タイルをダッシュボードに追加することをお勧めします。 期待されるメトリック値またはしきい値を投稿できます。これにより、チームが表示した &rsquo; データを読み取る方法をチームに通知できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/201212e8-336b-4442-9cea-08fb40d2996b.png"><img alt="image" border="0" height="165" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cc329d0a-4e31-4f08-bbdc-ac5d96301cca.png" style="margin: 0px; border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="絵" width="166"></a></p>


  <p>ウィジェット自体がこれらのことを示すために役立つ方法を調査していますが、この最初のリリースでは、この方法を使用して、チームにとっての数値の意味を簡単に伝えることができます。</p>


  <p>最後に、ウィジェットをクリックすると Azure portal が開き、ナビゲーションが高速になります。 このナビゲーションが、ユーザーを特定のリソースに直接移動している可能性を調査しています (たとえば、この概念についてのフィードバックをお &rsquo; 寄せくださいメトリックスエクスプローラー &ndash; )。</p>


  <h3>次の手順</h3>


  <p>これは優れた初期ダッシュボードウィジェットであり、 &rsquo; チーム &rsquo; の日々の操作で非常に便利です。 しかし、開発する他のウィジェット &rsquo; に加えて、追加する可能性のある機能についても考えました。 これらのアイデアについてご意見をお聞かせください。</p>


  <ul>
   <li><strong>カラーコーディング:</strong> 特定の条件に基づいてウィジェットの背景色を変更します。 これにより、より複雑な構成を行うことができますが、追加のデータポイントがウィジェットに追加されます。 ここでは、メトリックが特定のしきい値に達した場合にウィジェットのアイコン (感嘆符など) を表示することもできます (これは、色を見づらい人のアクセシビリティに適しています)。</li>
   <li><strong>アラートのウィジェット: </strong>アラートに基づいてウィジェットを作成するか、選択したメトリックに関連付けられているアラートを使用できるようにします。</li>
   <li><strong>Kusto ウィジェット: </strong>メトリックウィジェットと同じ基本的な機能を持つウィジェットを作成しますが、Kusto (App Analytics) クエリに基づいて、ユーザーは独自のメトリック (おそらく、非常に具体的なもの) を取得して返すことができます。</li>
   <li><strong>グラフ: </strong>一連のデータを返してグラフに表示できるウィジェットを作成します。 これを実現するために、いくつかの内部的な課題がありますが &rsquo; 、作業を進めています。</li>
  </ul>


  <p>新しいウィジェットを使用すると、Application Insights データを最新に保つことができます。 近日公開予定です。新しい発表については、Azure ブログの投稿 &nbsp; を &nbsp; ご覧ください。</p>


  <p>常に、 <a href="https://visualstudio.uservoice.com/forums/357324-application-insights">Application Insights UserVoice ページ</a>で新機能や改善された機能 &nbsp; についてアイデアを共有してください。質問がある場合は、 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights"><u>Application Insights のフォーラム</u></a>にアクセスしてください。</p>
