### YamlMime:Yaml
ms.openlocfilehash: 78aa04bdff178a73d0ca7becd38f01756c5b0f6e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889709"
Slug: new-azure-pipelines-announcements-vs-code-extension-github-releases-and-more
Title: 新Azure Pipelinesのお知らせ – VS Code拡張機能、GitHub リリースなど
Summary: '9 月にAzure Pipelinesを開始して以来、クラウドでホストされるビルドおよびデプロイ サービスの導入が強力に増加しています。 '
Content: >-
  <p>9 <a href="https://azure.microsoft.com/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/" target="_blank">月にAzure Pipelinesを</a>&rsquo;開始して以来、クラウドでホストされるビルドおよびデプロイ サービスの導入が強力に増加しました。 また、GitHub 上のオープン ソース プロジェクトの多くから、無制限のビルド分を利用し始<a href="https://github.com/marketplace/azure-pipelines" target="_blank"></a>め、ホストされている Linux、ウィンドウズ、Mac マシン全体で最大 10 の同時ジョブを使用して学習しました。&rsquo; 多&rsquo;くのクロスプラットフォーム ライブラリとアプリケーションに肯定的な違いがあるのが分かっています。</p>


  <p>Connect();&rsquo;&ndash; では、Azure Pipelines を使用してアプリケーションのビルドとリリースを簡単に行うオープン ソース プロジェクトから直接インスパイアされた、Azure Pipelines 2 つの新機能と統合について発表しました。</p>


  <h2>Azure Pipelines用の Visual Studio Code</h2>


  <p>コードとしての&#39;(<a href="https://docs.microsoft.com/azure/devops/pipelines/yaml-schema?view=vsts&amp;tabs=schema" target="_blank">YAML</a>&rsquo; パイプライン) を構築する前に、お気に入りのオープン ソース プロジェクトの多くで作業を行い、Azure Pipelines サポートを活用しています。 YAML &ndash; ファイルを記述して確認する前に、何かが欠落しているのに気付き、お気に入りのコード エディターで大きな編集<a href="https://code.visualstudio.com/" target="_blank">Visual Studio Code。</a> 多くのツールと同様Visual Studio Code YAML の構造の構文が強調表示されますが、開発者はファイル内のどこにどのキーが有効かを正確に覚えておく必要があります。 これにより、開発者はドキュメントを前後に切り返し、YAML ファイルをコミットしてビルドを実行する前に入力ミスを確認する必要があります。</p>


  <p>次のAzure Pipelinesを入力Visual Studio Code。 これで、構文の強調表示と IntelliSense を使用して、YAML&#39;を認識Azure Pipelinesできます。 つまり、タスクを&rsquo;記述&ldquo;&rdquo;&rdquo;&ldquo;する場合は、赤いインクでアラートが表示されます。ここで、タスクを記述する必要&ldquo;があります。&rdquo; IntelliSense もスキーマ対応です。 ファイル内のどこにいっても、Ctrl-Space キー (macOS の場合は Cmd-Space キー)&rsquo; を押して、ファイル内のその時点で受け入れられることを確認します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c1484e85-b35f-47a6-a1fe-ea4f991a80ef.png"><img alt="Azure Pipelines extension for Visual Studi Code" border="0" height="337" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/56f6786f-dd9a-463c-b349-738264af606c.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure Pipelines Visual Visual Code の Azure Pipelines 拡張機能" width="640"></a></p>


  <p>開始するには、Azure Pipelines <a href="https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines" target="_blank">Marketplace</a> から Visual Studio Code<a href="https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines" target="_blank">インストールします</a>。 拡張機能のソース<a href="https://github.com/Microsoft/azure-pipelines-vscode" target="_blank"></a>&rsquo;はオープン ソースであり、GitHub で使用できます。その動作の詳細を確認したい場合、またはフィードバックを提供したり、変更を提案したりしたい場合は、</p>


  <h2>GitHub リリース</h2>


  <p>GitHubリリースは&ndash;、ソフトウェアをパッケージ化してエンド ユーザーに出荷するための最適な方法であり、オープンソース プロジェクトで多用されています。 新しいリリースを使用して、リリースをシームレスに管理GitHubお知らせAzure Pipelines。 新しいリリースを作成したり、ドラフトを変更したり、古いリリースを破棄したりすることができます。 新しい GitHub リリース タスクでは、バイナリ ファイルのアタッチ、ドラフト リリースの発行、リリースをプレリリースとしてマークするなどの、一般的に実行されるすべてのアクションがサポートされます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/75fd1989-5428-4007-8efe-1ab9c3690f90.png"><img alt="Creating a GitHub Release example" border="0" height="382" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/05038541-f343-47b6-a97d-f8b701289b53.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="新しいリリースGitHubの作成" width="673"></a></p>


  <p>私たちの経験から、リリース ノートの作成は困難な場合があるというわかっています。 このタスクでは、コミットへのリンクやリンクされた問題など、このリリースで行われた変更の一覧を自動的に計算し、GitHub のリリース ノートに追加できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d84b7406-16b4-499f-b014-1df86347c1a3.png"><img alt="Release notes on GitHub" border="0" height="464" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/954d253a-4f1e-4121-a851-14ca704b70b7.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="GitHub に関するリリース ノート" width="640"></a></p>


  <p>この新しい GitHub リリース タスクを含む Azure Pipelines の組み込みタスクはすべてオープン ソースであり、変更を提案したり、機能要求を参加させる場合は <a href="https://github.com/Microsoft/azure-pipelines-tasks" target="_blank">GitHub</a> で使用できます。</p>


  <h2>Azure DevOps プロジェクトAzure IoT &ndash; サポート</h2>


  <p>プロジェクト<a href="https://azure.microsoft.com/en-us/features/devops-projects/" target="_blank">Azure DevOpsを使用</a>して、パイプラインから直接完全に機能するDevOpsを簡単に設定Azure portal。 作成するパイプラインは、使用するプログラミング言語とアプリケーション プラットフォームに合わせてカスタマイズされ、Azure の機能を活用してデプロイする必要があります。 これらは非常に簡単で非常に簡単な開始方法ですが、Azure portal で Azure DevOps Projects を使用してパイプラインを作成することで、将来プロジェクトを拡張および拡張できる必要があるすべてのスキャフォールディングを確実に設定できます。</p>


  <p>IoT ベースのソリューションを構築およびデプロイするためにAzure DevOpsを使用しているお客様からの関心が高まっています。 現在、これらのシナリオを簡単に開始するために、Azure DevOps プロジェクト ワークフローの <a href="https://docs.microsoft.com/en-in/azure/iot-edge/" target="_blank">Azure portal Azure IoT Edge</a> のサポートが追加されました。&nbsp;</p>


  <p>Azure DevOps プロジェクトでの Azure IoT Edge のサポートにより、Node.js、Python、Java、.NET Core、または C で記述された IoT Edge モジュールをデプロイするときに簡単に開始できます。これにより、IoT Edge アプリケーションの開発、ビルド、デプロイに必要なすべてが設定されます。</p>


  <ul>
   <li>上記の任意の言語のサンプル IoT Edgeを含む Git コード リポジトリ</li>
   <li>Azure へのデプロイ用のビルドとリリース パイプラインのセットアップ</li>
   <li>Azure IoT Edge に必要なすべての Azure リソースのプロビジョニング</li>
  </ul>


  <p>Azure portal から Azure DevOps プロジェクトを設定するためにいくつかの質問に回答したら、Azure DevOps のプロジェクトを使用してサンプル コードとスケルトン CI/CD パイプラインにアクセスできます。このパイプラインも自動的に自動的に構成されます。 作成されたパイプラインを調べ、作成された Azure リソースに移動して、アプリケーションの複雑化と時間の経過に伴う進化に合わせて増分変更を行えます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8ece20b3-91a7-4dfb-a70a-747ebeb87600.png"><img alt="Azure DevOps project" border="0" height="519" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bee2165b-ad71-4ad4-8cd9-4459a148f1f6.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure DevOps プロジェクト" width="1024"></a></p>


  <p>既定では、ci/CD パイプラインが構成され、Azure Repos の Git リポジトリにプッシュされたコードによって継続的インテグレーション ビルドと継続的デプロイ プロセスが発生し、追加の運用オーバーヘッドなしで変更が開発 Azure IoT Edge 環境にデプロイされます。 &rsquo;そこから非常に簡単に、承認者またはリリース ゲートを備える追加の実稼働環境を追加して、コードからクラウド、現場のデバイスへの次の Azure IoT Edge アプリケーションの配信を自動化できます。</p>


  <h2>ServiceNow と Azure Pipelines</h2>


  <p>最後に、パートナーの 1 つ ServiceNow との新しい統合について触れたい。 ServiceNow は、最新の IT サービスの提供を迅速化し、簡素化することで、企業の働き方を変えつつあります。 ServiceNow は、日常的なアクティビティ、タスク、プロセスを自動化することで、企業が効率性を高め、従業員の生産性を向上させるのに役立ちます。</p>


  <p>ServiceNow と Azure Pipelines ServiceNow Change Management 拡張機能と組み合わせて使用できます。 運用を更新する必要があるたび、Azure Pipelines を使用してデプロイ プロセスを自動化し、ServiceNow Change Management を使用してリスク評価、スケジュール設定、承認、および監視を行います。</p>


  <p>パイプラインでステージを定義すると、ServiceNow Change Management をリリース ゲートとして使用して、ServiceNow から別のステージへの変更の昇格を制御できます。 リリース パイプラインの実行中に、ServiceNow に新しい変更要求が作成され、変更が実装の準備が完了するまでパイプラインは一時停止されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cd16e1ff-7143-4244-8e82-532e95d0f24e.png"><img alt="ServiceNow integration with Azure Pipelines" border="0" height="491" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4eb37cd7-7331-48fc-b7d7-849db8fb1e3b.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="ServiceNow と Azure Pipelines" width="1369"></a></p>


  <p>&ldquo;Azure Pipelines のデプロイ プロセスに ServiceNow&rdquo; 変更要求の更新タスクを追加することで、デプロイの状態と結果で ServiceNow 変更要求を更新した状態を維持できます。 パイプラインに関するリリース情報は、追跡可能性のための変更要求でキャプチャされ、ServiceNow と Azure Pipelines の間の完全な双方向のエンドツーエンド統合が提供されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2a89e2dd-3fcd-44a2-990f-1e62bca0fbed.png"><img alt="Updating a ServiceNow change request" border="0" height="617" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fe4a0225-4a7e-47bd-8235-21a5035fa5dc.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="ServiceNow 変更要求の更新" width="1430"></a></p>


  <p>詳細については、ServiceNow ストアのAzure Pipelines<a href="https://aka.ms/servicenow-pipelines-app" target="_blank">を確認してください</a>。 ServiceNow Change Management のリリース ゲートと変更要求タスクを Azure Pipelines にインストールするには、Azure DevOps <a href="https://aka.ms/servicenow-pipelines-tasks" target="_blank">Marketplace の ServiceNow Change Management 拡張機能にアクセスしてください</a>。</p>
