### YamlMime:Yaml
ms.openlocfilehash: 8e2efc00e6d843a16edecf7aec7f29f15855088a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890338"
Slug: new-azure-iot-offerings-simplify-iot-application-development
Title: 新しいAzure IoTを使用すると、IoT アプリケーションの開発が簡素化されます
Summary: '企業が概念実証から実稼働に移行する IoT の切り離し地点にいます。 現在、IoT アプリケーションを大規模に管理し、大量のデータを収集し、このデータをリアルタイムで理由付けして、プロセス、環境を最適化し、新しいソリューションを作成することができます。 '
Content: >-
  <p>企業が概念実証から実稼働に移行する IoT の切り離し地点にいます。 現在、IoT アプリケーションを大規模に管理し、大量のデータを収集し、このデータをリアルタイムで理由付けして、プロセス、環境を最適化し、新しいソリューションを作成することができます。 さらに、デバイスとセンサーはますます洗練され、エッジで AI を実行する可能性が高まり、農業、スマート製造、スマートビルや空間などの主要な業界でブレークスルーの新たな機会を生み出しています。</p>


  <p>この 4 月には、新しい製品、ソリューション、パートナーシップ、プログラムなどのイノベーションを行い、お客様が IoT を利用しやすくするために、IoT とインテリジェント エッジへの <a href="https://blogs.microsoft.com/iot/2018/04/04/microsoft-will-invest-5-billion-in-iot-heres-why/" target="_blank">50</a> 億ドルの投資を発表しました。 お&rsquo;客様にこれを実現するイノベーションのペースを思い出してください。 &rsquo;その勢いを基に、<a href="https://azure.microsoft.com/en-us/services/azure-sphere/" target="_blank">Azure Sphere</a> と <a href="https://azure.microsoft.com/en-us/services/digital-twins/" target="_blank">Azure Digital Twins</a> を含む IoT とエッジの新しいブレークスルーを実現し、<a href="https://azure.microsoft.com/en-us/services/iot-edge/" target="_blank">Azure IoT Edge</a>、<a href="https://azure.microsoft.com/en-gb/services/azure-maps/" target="_blank">Azure マップ</a>、Azure IoT <a href="https://azure.microsoft.com/en-us/services/iot-central/" target="_blank">Central</a> を一般提供しました。</p>


  <p>現在、Connect() 開発者向けカンファレンスでは、クラウドからエッジへの IoT アプリケーションへの豊富なデータ ストリームを取り込む追加機能と、IoT 開発プロセスを加速するソリューションを発表しています。</p>


  <h2>IoT ソリューションでデータを管理および活用するための新機能</h2>


  <ul>
   <li><a href="https://aka.ms/asa-on-iot-edge" target="_blank"><strong>Azure Stream Analytics on IoT Edge</strong></a>一般提供<strong>: Azure Stream Analytics (</strong>ASA) は強力なストリーム処理機能を Azure IoT Edge に取り込み、開発者がデータを処理し、条件にローカルで対応できます。 asa on Azure IoT Edge を使用すると、エッジとクラウドの間で分析を簡単に移動できます。これは、顧客が待ち時間の短いコマンドと制御を必要とするシナリオ、クラウドへの接続が制限されている、帯域幅が制限されている、または特定のコンプライアンスニーズがあるシナリオで重要になる可能性があります。</li>
   <li><a href="https://azure.microsoft.com/en-us/blog/simplifying-confidential-computing-azure-iot-edge-security-with-enclaves-public-preview/" target="_blank"><strong>IoT Edge</strong></a>プレビューでのエンクレーブ セキュリティの保証<strong>:</strong>&rsquo;&ndash; &ndash; 現在、エッジにあるデバイス用の Open Enclave SDK を使用して、機密コンピューティングを行う方法や、データとコードを保護する方法が提供されています。 Open Enclave は Azure IoT Edge セキュリティ マネージャーと統合され、エッジ開発者がアクセスできます。</li>
   <li><a href="https://aka.ms/tsi-update-blog" target="_blank"><strong>Azure Time Series インサイト</strong></a> のパブリック プレビューの新機能<strong>:</strong> Azure Time Series インサイト は、IoT デバイスによって生成された数十億もの時系列測定からすばやく洞察を得られる、フル マネージドのエンドツーエンドの IoT 分析ソリューションです。 Microsoft では、このデータの価値を最大限に高め、運用インテリジェンスを向上するために、さまざまな産業用 IoT データ分析シナリオをサポートするために Time Series インサイト オファリングを更新しています。 お客様は、時系列モデルを使用して受信テレメトリ データに豊富なコンテキスト化を追加して、運用上の分析情報を取得し、アプリケーションのニーズに応じて IoT &ndash;&rsquo; データを多層ストレージウォームまたはコールドに格納し、高度な機械学習および分析ソリューションとシームレスに統合して予測分析を実行できます。 Time Series インサイトは、資産ベースの運用分析情報と豊富なアドホック分析を組み合わせた強化されたユーザー エクスペリエンスを追加します。 このリリースの一環として、Microsoft &lsquo;&rsquo; は新しい移動可能な料金モデルも導入しています。これにより、IoT ビジネスで要求される価格のスケーラビリティと柔軟性が顧客に提供されます。</li>
   <li><a href="https://aka.ms/s1tier" target="_blank"><strong>Azure マップ S1 SKU</strong></a><strong>:</strong> Azure マップ は、シンプルで安全な場所 API を使用してデータに地理空間コンテキストを追加し、IoT デバイスに地理空間インテリジェンスを追加する、マッピング、ナビゲーション、トラフィック サービスのポートフォリオです。 お客様に強化されたサービス オプションを提供するために、Microsoft は Standard S0 オファリングを補完するために、Azure マップ 用の新しい S1 価格レベルを導入しています。 S1 オファリングは、2018 年 12 月 4 日から提供され、エンタープライズ規模のデプロイ、高度な機能を必要とするソリューション、ミッション クリティカルなアプリケーションに対して、1 秒あたり 50 クエリを超える Azure マップ を必要とするアプリケーションの実稼働スケール デプロイ用に強化されたサービス レベルを提供します。</li>
   <li><strong>Azure マップ パートナーシップ:</strong> Azure マップ は、開発者向けのツールを強化し、モビリティ データと分析プロバイダーとの緊密な関係を構築することで、位置情報サービスにおけるリーダーシップを強化し続け続けています。 Microsoft は、公共輸送分析のグローバル リーダーである Moovit との新しいパートナーシップを発表します。 <a href="https://moovit.com/" target="_blank">Moovit</a> は、リアルタイムの公共輸送データを Azure マップ に直接統合し、2019 年から輸送およびフィールド サービスの物流を管理する企業向けのより高度なアプリを開発者が構築するのを支援します。 このパートナーシップにより、開発者は場所情報とスマート シティの分析情報をエンドツーエンドで提供し、都市交通プランナーが人々のフローを最適化し、小売業者、消費者、その他のアプリケーションに対してより優れたソリューションを実現できます。</li>
  </ul>


  <h2>IoT ソリューションの開発の高速化</h2>


  <p>6 月に、<a href="https://azure.microsoft.com/en-us/blog/azure-iot-edge-generally-available-for-enterprise-grade-scaled-deployments/" target="_blank">Azure IoT Edge</a> の一般提供とオープン ソース ランタイムを発表しました。お客様は、Azure Stream Analytics や Azure Machine Learning のようなクラウド ワークロードを IoT デバイスで直接実行できます。 今後も、エッジ ソリューションの開発を加速するために、事前構築済みのエッジ モジュールを認定して示し、<a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/category/internet-of-things?page=1&amp;subcategories=iot-edge-modules" target="_blank">Azure Marketplace。</a> ソリューション開発者は、今すぐエッジ IP を紹介して収益化&mdash;できます。ここから<a href="https://docs.microsoft.com/en-us/azure/marketplace/iot-edge-module" target="_blank">始めましょう</a>。</p>


  <p>Microsoft は、しばらくの間、完全に<a href="https://www.azureiotsolutions.com/Accelerators" target="_blank"></a>カスタマイズ可能な IoT ソリューションを迅速に開発してデプロイする方法として、Azure IoTソリューション アクセラレータを顧客に提供しています。 このConnect、&rsquo;次の 2 つの拡張機能のセットを発表します。</p>


  <ul>
   <li><strong>Azure IoT シミュレーション:</strong> Microsoft では、開発者が開発時に IoT ソリューションをテストするための高度なデバイス シミュレーションを作成し、堅牢でスケーラブルなソリューションの開発を簡略化しています。 詳細については、Azure ブログの&ldquo;<a href="https://azure.microsoft.com/en-us/blog/accelerating-iot-solution-development-and-testing-with-azure-iot-device-simulation/" target="_blank" title="">https://azure.microsoft.com/en-us/blog/accelerating-iot-solution-development-and-testing-with-azure-iot-device-simulation/preview/「Azure IoT Device Simulation</a>&rdquo; を使用した IoT ソリューションの開発とテストの高速化」を参照してください。

   <ul>
    <li>サンプル シミュレーションを使用すると、すばやく稼働できます</li>
    <li>クイック カスタム デバイスを作成するか、JavaScript を使用して高度なデバイス モデルを作成する</li>
    <li>保存されたデバイス モデルを使用してシミュレーションを再実行する</li>
    <li>複数の種類のデバイスを使用して複雑なデバイスの作成をシミュレートする</li>
    <li>スループット メトリックと統合されたグラフを <a href="https://azure.microsoft.com/en-us/services/iot-hub/" target="_blank">IoT Hub</a> する</li>
   </ul>
   </li>
   <li><strong>Azure IoT監視: </strong>このオープン ソース ソリューションを更新すると、オペレーターが IoT ソリューションのすべてのファセットを管理しやすくなっています。&nbsp; <ul>
    <li>エッジ モジュールを IoT エッジ デバイスにデプロイする</li>
    <li>デバイスアラートに応答して電子メール通知などのアクションをトリガーする</li>
    <li>[自動更新プログラム] を使用してデバイスの更新デバイス管理</li>
    <li>Azure Time Series を使用してデバイス データを視覚化インサイト</li>
   </ul>
   </li>
  </ul>


  <p>IoT&rsquo; 市場にもう 1 つの説得力のある機能のセットを取り込み、楽しみにしています。 これらの最新のお知らせを確認 <a href="https://www.azure.com/iot" target="_blank">して、今すぐ顧客体験を開始してください</a>。</p>
