### YamlMime:Yaml
ms.openlocfilehash: 2bd5cd052cdb2f35dbc11a35a3a3163d72fb3def
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890063"
Slug: our-2019-resolution-help-you-transform-your-2008-server-applications-with-azure
Title: '2019の解決策: 2008 サーバーアプリケーションを Azure に変換するのに役立ちます。'
Summary: 新しい年の開始は常に、microsoft の計画に反映されるまでの時間です。 Microsoft では、2008サーバー looming のサポートが終了したため、サーバーの更新にどのように役立つかを検討しています。 Azure で利用できるすべての最先端のイノベーションを利用できるようにするにはどうすればよいですか。
Content: >-
  <p><em>このブログ投稿は、Erin Chapple、cvp、microsoft Windows Server、rohan Kumar、cvp、microsoft データによって共同作成されました。</em></p>


  <p>新しい年の開始は常に、microsoft の計画に反映されるまでの時間です。 Microsoft では、 <a href="https://www.microsoft.com/en-us/cloud-platform/windows-sql-server-2008" target="_blank">2008 サーバー looming</a> &rsquo; のサポートが終了したため、サーバーの更新にどのように役立つかを検討しています。 Azure で利用できるすべての最先端のイノベーションを利用できるようにするにはどうすればよいですか。</p>


  <p>また、Azure が2008サーバーアプリケーションを変換するのに最適な場所は、次の3つの理由であると考えています。</p>


  <ol>
      <li><strong>セキュリティ:</strong> セキュリティ上の脅威がますます洗練されているので、組織 &rsquo; のセキュリティポリシーを強化する必要があります。 <a href="https://azure.microsoft.com/en-us/overview/security/" target="_blank">Azure</a>は、他のパブリッククラウドよりも多くの認定を提供する、市場において最も信頼されているクラウドです。</li>
      <li><strong>イノベーション:</strong><a href="https://www.azure.com/migrate" target="_blank">Azure</a>の利用を支援するための、最適化された危険度の低いパスが用意されています。 また、 <a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance" target="_blank">Azure SQL Database</a>、 <a href="https://www.azure.com/cosmosdb" target="_blank">Azure Cosmos DB</a> 、 <a href="https://azure.microsoft.com/en-us/overview/ai-platform/" target="_blank">Azure AI</a>など、完全に管理されたサービスを使用して、革新を続けることができます。</li>
      <li><strong>コスト削減:</strong><a href="https://azure.microsoft.com/en-us/pricing/hybrid-benefit/" target="_blank">Azure ハイブリッド特典</a>と拡張された<a href="https://www.microsoft.com/en-us/cloud-platform/windows-sql-server-2008" target="_blank">セキュリティ更新プログラム</a>を利用することで、大幅に節約できます。 たとえば、100台の2008サーバーを Azure に移行すると、オンプレミスで実行した場合のコストと比較して、3年以上にわたって $ 300K を超えるコストを削減できます (独自のモデリングを行うには、 <a href="https://azure.microsoft.com/en-us/pricing/tco/calculator/" target="_blank">azure の TCO 計算ツール</a> を確認してください)。 &rsquo;また、Windows Server と SQL Server については Azure 過去のものと考える必要がありません。 AWS の<a href="https://azure.microsoft.com/en-us/overview/azure-vs-aws/cost-savings/" target="_blank">コストは5倍</a>になります。&nbsp;&nbsp;&nbsp;&nbsp;</li>
  </ol>


  <h2>今すぐ &ndash; &rsquo; ご利用ください。</h2>


  <p><strong>SQL Server 2008/r2 のサポートは、2019年7月9日に終了し、2020年1月14日の Windows Server 2008/r2 でサポートが終了するようになりまし</strong>た。 <a href="https://www.microsoft.com/en-us/microsoft-365/blog/2019/01/14/move-to-modern-windows-10-iot-safer-smarter-cloud-ready/" target="_blank">Windows 7</a>、 <a href="https://www.microsoft.com/en-us/microsoft-365/blog/2019/01/14/2019-is-the-year-to-make-the-shift-to-a-modern-desktop/" target="_blank">Office 2010</a> 、 <a href="https://aka.ms/Exchange2010EndOfSupportBlog" target="_blank">Exchange Server</a>も、すぐに拡張サポートを終了します。 Microsoft とパートナーは、この方法のすべての手順をお手伝いします。 次に、最新の資産にシフトするための3つの手順を示します。</p>


  <h3>手順 1: 環境を評価する</h3>


  <p>最初の手順では、2008サーバー環境の完全なインベントリを取得します。 各ワークロードを戦略的な価値で組織にランク付けします。 次のような質問に回答します。このワークロードがクラウドでどのように実行されるかを確認できます。 オンプレミスにとどまる必要があるものは何ですか? 各サーバーを現在のバージョンにアップグレードするには、どのような方法がありますか。 開始時に優先度と目標を確立することにより、移行を確実に成功させることができます。</p>


  <p>詳細なガイダンスについては、 <a href="https://datamigration.microsoft.com/" target="_blank">Azure Database migration guide</a>、 <a href="https://azure.microsoft.com/mediahandler/files/resourcefiles/azure-migration-guide-for-windows-server/Azure_Migration_Guide_for_Windows_Server.pdf" target="_blank">Windows Server 移行ガイド</a>、 <a href="https://docs.microsoft.com/en-us/sql/sql-server/sql-server-technical-documentation" target="_blank">Microsoft SQL Server docs</a> 、および<a href="https://docs.microsoft.com/en-us/windows-server/get-started/modernize-windows-server-2008" target="_blank">Windows Server のドキュメント</a>を参照してください。</p>


  <h3>手順 2: オプションを確認する</h3>


  <p>Microsoft では、お客様の条件に基づいて2008サーバーアプリケーションを最新化するための幅広いソリューションを提供しています。</p>


  <p><strong>Azure SQL Database の Managed Instance:</strong> PaaS 機能 (自動修正とバージョン更新、自動バックアップ、高可用性) と、管理のオーバーヘッドと TCO を大幅に削減する AI ベースの機能を有効にすると同時に、既存の SQL Server デプロイと完全なエンジンの互換性を確保します (SQL Server 2008 以降)。</p>


  <p><strong>Azure Virtual Machines でのサーバーと SQL Server の Windows:</strong>さまざまなコンピューティングソリューション &mdash; の開発とテスト、アプリケーションの実行、データセンターの拡張によって、仮想化の柔軟性が得られます。</p>


  <p><strong>オンプレミスの Windows サーバーと SQL Server:</strong>革新的なセキュリティとコンプライアンスの機能、業界トップレベルのパフォーマンス、ミッションクリティカルな可用性、高度な分析組み込み、コンテナーなどの新しいデプロイオプションを提供します。 <a href="https://www.microsoft.com/en-us/cloud-platform/windows-server" target="_blank">Windows Server 2016 と 2019</a>を使用して、ハードウェアとソフトウェアのインフラストラクチャを最新の状態に更新し、 <a href="https://www.microsoft.com/en-us/sql-server/sql-server-2019" target="_blank">2017 と2019を SQL Server</a>ます。</p>


  <h3>手順 3: 移動を行う</h3>


  <p>広く採用されている4つの戦略を使用して、クラウド移行計画を構築します: <a href="https://azure.microsoft.com/en-us/migration/get-started/" target="_blank">再ホスト、リファクタリング、再設計、アプリケーションのリビルド</a>。 新しいデータベースと OS のオプションを考慮して、ビジネスに適した組み合わせを選択します。 今後のウェビナーやイベントにご参加ください。</p>


  <ul>
      <li>1月15日 ~ 3 月21日: <a href="https://www.microsoftevents.com/profile/web/index.cfm?PKwebID=0x1130083abcd" target="_blank">SQL Server と Azure Data Services の道路の表示</a></li>
      <li>1月24日: ウェビナー: <a href="https://cloudblogs.microsoft.com/sqlserver/2019/01/07/four-ways-to-take-your-apps-further-with-cloud-data-and-ai-solutions-from-microsoft/" target="_blank">最新のデータ資産でビジネスを変革する</a></li>
      <li>1月29日: ウェビナー: <a href="https://info.microsoft.com/ww-landing-transform-windows-server-2008-apps-with-hybrid-cloud-innovation.html" target="_blank">Windows Server 2008 のアプリとインフラストラクチャの変換</a></li>
  </ul>


  <p>すべてを追加すると、Microsoft は世界中で最も包括的で説得力のあるクラウド、データ、AI プラットフォームを備えています。 Microsoft は、既存の投資に対して従来の価値を提供する広範なプログラムを提供しています。最新の情報に更新するには、ここを参照してください。 お客様と組織がお客様の世界の改革と変革を継続する方法をご紹介します。</p>
