### YamlMime:Yaml
ms.openlocfilehash: c1909471eb73150de111ff284972c528f52430ad
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903444"
Slug: payment-processing-blueprint-for-pci-dss-compliant-environments
Title: Azure のセキュリティとコンプライアンスのブループリントに準拠したPCI DSS処理環境向け
Summary: '本日は、PCI DSS に準拠した支払い処理環境向け新しい Azure のセキュリティとコンプライアンスのブループリント の一般提供をお知らせします。唯一の監査者が確認し、Payment Card Industry Data Security Standard - PCI DSS 3.2 技術コントロール用の 100% 自動化されたソリューションです。 '
Content: >-
  <p>本日は、新しい Azure のセキュリティとコンプライアンスのブループリント PCI DSS 準拠の支払い処理環境の一般提供についてお知らせします。唯一の監査者が確認し、Payment Card Industry Data Security Standard - <a href="https://aka.ms/pciblueprint">PCI DSS&nbsp;</a> 3.2 技術コントロール用の 100% 自動化されたソリューションです。 アーキテクチャ フレームワークは、企業が支払い処理システムまたはクレジット カード処理ソリューションをクラウドにデプロイして運用Microsoft Azure。 この自動化ソリューションは、お客様が Azure ソリューションを導入し、わかりやすい参照アーキテクチャを示し、PCI DSS コンプライアンス標準に準拠しながら、セキュリティで保護された準拠ワークロードをデプロイする方法を管理者に教えるのに役立ちます。</p>


  <p>このソリューションは、パートナーの Avyan Consulting と共同で開発され、その後、Microsoft&rsquo; の PCI-DSS 監査人<a href="https://www.coalfire.com/">である Coalfire</a> によってレビューされました。 PCI へのコンプライアンスのレビューには、このソリューションおよび対応する必要があるコンポーネントの、独立したサードパーティによるレビューが記載されています。</p>


  <p>このソリューションのしくみを簡単に確認するには、この <a href="https://aka.ms/pciblueprintvideo">5</a> 分間のビデオで説明し、そのデプロイを示します。</p>


  <p>この自動アーキテクチャには、Azure Application Gateway、ネットワーク セキュリティ グループ、Azure Active Directory、App Service Environment、OMS Log Analytics、Azure Key Vault、Azure SQL DB、Azure Load Balancer、Application インサイト が含まれます。、Azure Web App、Azure Automation、Azure Runbooks、Azure DNS、Azure Virtual Network、Azure 仮想マシン、Azure リソース グループとポリシー、Azure Blob Storage、Azure Active Directory アクセス制御 (RBAC)、Azure Security Center。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e126b899-9350-4ab6-ac16-dadf7a9b8045.png"><img alt="Azure Solutions Blueprint" border="0" height="1124" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/37ef57e0-287f-4234-911c-4eda133eb413.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="Azure ソリューションブループリント" width="2685"></a></p>


  <p>この基本アーキテクチャは次のコンポーネントで構成されています。</p>


  <ul>
   <li><strong>アーキテクチャ図。</strong> この図は、Contoso Webstore ソリューションで使用される参照アーキテクチャを示します。</li>
   <li><strong>デプロイ テンプレート。</strong> このデプロイでは、<a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview#template-deployment">Azure Resource Manager テンプレート</a> を使用してアーキテクチャのコンポーネントを Microsoft Azure に自動的にデプロイします (これは、セットアップ時に構成パラメーターを指定することによって行います)。</li>
   <li><strong>自動デプロイ スクリプト。</strong> これらのスクリプトを使用して、エンド ツー エンド ソリューションをデプロイします。 次のスクリプトが含まれます。 <ul>
    <li>モジュールのインストールと<a href="https://docs.microsoft.com/en-us/azure/active-directory/active-directory-assign-admin-roles-azure-portal">グローバル管理者</a>のセットアップ スクリプト。インストールを行い、必要な PowerShell モジュールとグローバル管理者ロールが正しく構成されていることを確認するために使用します。</li>
    <li>インストール PowerShell スクリプトは、エンド to エンド のソリューションをデプロイするために使用されます。この<a href="https://github.com/Microsoft/azure-sql-security-sample"></a>ソリューションには、Azure SQL Databaseチームによって構築されたセキュリティ コンポーネントが含されます。</li>
   </ul>
   </li>
   <li><a href="https://aka.ms/pciblueprintcrm32"><strong>3.2 ブックPCI DSSお客様の責任のサンプル。</strong></a> このブックでは、262 および 3.2 の各コントロールで、ソリューションを使用して準拠状態を実現する方法PCI DSS説明します。 このブックでは、Azure と顧客の間の共同責任を正常に実装する方法について詳しく説明します。</li>
  </ul>


  <ul>
   <li><a href="https://aka.ms/pciblueprintprocessingoverview"><strong>PCI コンプライアンス レビュー。</strong></a> PCI 準拠の完全なビジネスに向けた基礎アーキテクチャを構築するために必要なトピックの概要を示します。 Coalfires のレビュー&rsquo;では、最終的な PCI 評価に対してより良い結果を生み出す、さらなるソリューション設計の前に、追加のディメンションを調査します。</li>
   <li><strong>顧客対応の脅威モデル。 </strong>ソリューションの境界と接続に関する詳細な説明を提供する Contoso Webstore ソリューションのこのデータ フロー図 <a href="https://aka.ms/pciblueprintthreatmodel">(DFD)</a> とサンプル脅威モデル。</li>
  </ul>


  <p>デプロイされたアプリケーションは、組み込みのセキュリティとコンプライアンスに関する考慮事項を含み、エンドツーエンドの Azure ソリューションとしてデプロイできる 4 層アーキテクチャのカード番号、有効期限、CVC (カード検証チェック) 番号を含むクレジット カード データの安全な管理を示しています。</p>


  <p><a href="https://aka.ms/azureblueprint">Azure</a> のセキュリティとコンプライアンスのブループリントと Azure Government&nbsp; を最新の情報に保つには、必ず <a href="https://blogs.msdn.microsoft.com/azuregov/feed/">RSS</a> &ldquo;&rdquo; フィードをサブスクライブし、<a href="https://blogs.msdn.microsoft.com/azuregov/">Azure Government</a> ブログの [電子メールでサブスクライブする] をクリックして電子メールを受信してください。さらに、Azure の自動化された基礎アーキテクチャの詳細については、頻繁に確認してください。</p>


  <p>Azure Government の機能を組織で体験するには、<a href="https://azuregov.microsoft.com/trial/azuregovtrial">Azure Government 試用版</a>にサインアップします。</p>
