### YamlMime:Yaml
ms.openlocfilehash: 1bfacc3d5cacbee4b905e495e4d9992776f38da9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891414"
Slug: performance-buckets-in-application-insights
Title: Application Insights のパフォーマンスバケット
Summary: 'MTTD を最小化: 検出、トリアージ、問題の影響を軽減し、最後にパフォーマンスバケットを使用して問題を診断します。これにより、検出トリアージ/診断プロセスの効率を高めることができます。'
Content: >-
  <p>このブログ投稿では、mttd を最小限に抑える方法について説明します。平均の検出、トリアージ、問題の影響の評価を行い、最後に Application Insights を使用して問題を診断します。 このシナリオでは、新しい機能である<strong>パフォーマンスバケット</strong>が導入さ<strong></strong>れます。 パフォーマンスバケットは、検出、トリアージ、診断プロセスをより効率的にするのに役立ちます。</p>


  <p>アプリケーションインサイトは、開発者がアプリケーションのパフォーマンス、可用性、使用状況を監視できるようにするサービスです。 これは、 <a href="https://azure.microsoft.com/en-us/blog/service-monitoring-and-diagnostics-2/">アプリケーションのライフサイクル</a>の重要な部分になります。 ここでは、web アプリケーションのパフォーマンスに関連するシナリオの検出、トリアージ、診断のプロセスについて説明します。<br>

  &nbsp;</p>


  <p><img alt="01-pipe1" border="0" height="99" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b3595967-10c9-47c9-affd-516050294428.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="01-pipe1" width="480"></p>


  <h1><br>

  検出: サーバーの応答時間が遅い</h1>


  <p>Application Insights のサービスの概要ブレードは、アプリケーションの状態の概要を提供するように設計されています。 このブレードの主要なグラフの1つは、サーバー &rsquo; の平均応答時間です。 お気に入りのアプリケーションをスタートページにピン留めしたり、毎日見たいメトリックの [お気に入り] ビューを作成したりすることができます。 これにより、アプリケーションのテレメトリにすばやくアクセスできます。<br>

  <br>

  <img alt="detect2" border="0" height="610" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b127a6ea-48da-44ec-af2a-eb9427a4b347.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="detect2" width="474"></p>


  <p>&nbsp;</p>


  <p>Application Insights サービスを実行している場合は、各朝に対応して、主要なサービスの正常性を確認します。 注目すべき異常について確認し、対処するための主要なダッシュボードが用意されています。 応答時間は、追跡するメトリックの1つです。チームのプロセスが類似している可能性があります。</p>


  <p>毎日の同期により、異常に気付くことができます。 ただし、パフォーマンス関連の問題を検出する平均時間を短縮するために、サーバーの応答時間にアラートを設定することをお勧めします。 Application Insights には、サーバーの平均応答時間が望ましくない方法で動作していることを認識できるようにするための警告機能があります。</p>


  <h2>アラートの設定</h2>


  <p>&rsquo;平均応答時間が長すぎる場合にアラートを受け取るようにします。<br>

  <br>

  すべてのメトリックの異常な値を電子メールで通知するには、アラートを追加します。 アカウント管理者または特定の電子メール アドレスのいずれかに電子メールを送信することを選択できます。 <a href="https://azure.microsoft.com/documentation/articles/app-insights-alerts/">アラートルールを追加するには、</a> [アラートルール &rsquo; &gt; &ndash; &lsquo; ] [アラートの追加 &rsquo; ] をクリックし &lsquo; ます。<br>

  <br>

  <img alt="appinsights-413setmetricalert" border="0" height="610" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e45c8ca1-edc4-4545-b46c-cf4b54984f29.png" style="border-width: 0px; margin: 0px auto; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="appinsights-413setmetricalert" width="554"></p>


  <h1><br>

  トリアージ: 問題の重要度を理解する</h1>


  <p>アラートを受け取ったら、問題がどの程度深刻であるかを知りたいと思います。 すべてのユーザーとすべてのページ、またはその一部のみに影響しますか。 どのブラウザー &rsquo; を使用しているか、またはどこにあるかによって異なりますか。 Application Insights を使用すると、URL、ブラウザー、市区町村などのプロパティでメトリックを分割して、相関関係を表示できます。 さまざまなプロパティの平均応答時間を表示するには、[サーバー応答] ブレードにグラフを追加します。<br>

  <br>

  <img alt="PB_5" border="0" height="475" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/efd05cad-bd83-45fb-bc4d-a37224d35e1b.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="PB_5" width="610"><br>

  グループ化する特定のプロパティを選択したら、[サーバー] まで下へスクロールし、[サーバーの応答時間] を選択する必要があります。<br>

  &nbsp;</p>


  <p><img alt="PB_6" border="0" height="329" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f871126a-229a-4c55-850e-1da2fe33a7eb.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="PB_6" width="480"></p>


  <p>選択したプロパティによって、サーバーの応答時間の平均値が表示されるようになります。 この例では、City を選択しました。<br>

  &nbsp;</p>


  <p><img alt="test" border="0" height="328" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4d71ff4a-f5e8-43bb-952d-a293ab281c71.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="テスト" width="480"></p>


  <p>パフォーマンスに影響するプロパティを見つけると、このプロパティによってすべての要求をフィルター処理できます。</p>


  <p>トリアージ段階の目標の1つは、根本原因を特定するために、目的のサーバー応答時間を超える特定のページ要求を見つけることです。 この個別の要求を見つけたら、診断する準備ができています。</p>


  <p>以前に個々の要求を検索したことは、応答時間が満たされていないサーバーを見つけるために、個々のサーバー要求の一覧を検索することを意味します。 線形検索は最も効率的な方法ではなく、何千もの個別の要求の共通インスタンスで特に面倒な場合があります。 このため、 <strong>パフォーマンスバケット</strong>という新機能が導入されています。</p>


  <h2>パフォーマンスバケット</h2>


  <p>パフォーマンスバケットを使用すると、特定のウィンドウ (バケット) に収まるサーバー応答時間の量を確認できます。 上に示すように新しいグリッドグラフを追加しますが、要求のパフォーマンスをグループ化します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3dd3c715-93b3-45c1-a880-b33d000e87b2.png"><img alt="Request Performance" border="0" height="370" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f7afb971-1b55-41e3-af46-9d079ddc0427.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="要求のパフォーマンス" width="480"></a></p>


  <p><br>

  これにより、応答時間の分布の概要を示すだけでなく、応答時間をバケットに並べ替えることもできます。 この機能を使用すると、必要な応答時間を超えて要求に直接アクセスできます (高速な応答時間で数千の要求をスクロールする必要はありません)。</p>


  <p>また、パフォーマンスバケット内でフィルター処理を行うこともできます。 バケットを選択すると、その応答時間枠内で行われたすべての要求が表示されます。 特定のプロパティを持つ要求だけを表示する場合は、[フィルター] を選択します。 次の図は、500ミリ秒サーバー応答時間内の要求を表示し、Redmond の市からの要求のみを追加したフィルターを追加するプロセスを示しています。<br>

  &nbsp;</p>


  <p><img alt="filter_bucket1" border="0" height="371" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e0948a22-05a7-4cec-af4f-1ec9f73dcea6.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="filter_bucket1" width="610"></p>


  <p><br>

  フィルター処理を完了するには、[更新] をクリックします。 次の図は、250ミリ秒500ミリ秒範囲に分類され、Redmond 市から作成された要求の一覧を示しています。<br>

  &nbsp;</p>


  <p><img alt="filtered" border="0" height="610" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3d5848d4-da81-4d24-839a-eafb6d8423a8.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="フィルター選択" width="399"></p>


  <p><br>

  パフォーマンスバケットによるグループ化とフィルター処理を使用すると、高速ページと低速ページの平均パフォーマンスを把握できます。 さまざまな可能性を調査することができます。 高速ページの数が減少し、キャッシュミスの数が増加しているか。 また、低速ページへの呼び出しの数が増加している可能性もあります。 または、低速のレポートページを実行しているお客様が多いでしょう。 サーバーの応答時間の問題を解決することを目指している場合、これらのパフォーマンスバケットを使用すると、応答時間が遅い要求を見つけるプロセスが迅速化されます。 これで診断対象 (サーバーの応答時間が好ましくない要求) が検出されたので、最後のフェーズである診断に進むことができます。</p>


  <h1>診断: 応答時間が遅い理由</h1>


  <p>サーバーの応答時間が遅いインスタンスを特定したら、それが低速である理由の調査を開始できます。 サーバーの応答時間が悪いという正確な理由は、解決方法を決定できるように、理解しておくことが重要です。 さまざまなテレメトリを使用して、問題領域を特定することができます。</p>


  <p>新しい SQL クエリまたは http 要求/サービスの呼び出しが、サーバーの平均応答時間に影響することがあります。 この原因となっているクエリを特定するには、依存関係の監視を使用することができます。<strong> </strong><a href="https://azure.microsoft.com/documentation/articles/app-insights-dependencies/">依存関係の監視</a> では、外部サービス (データベース、REST サービスなど) への呼び出しをカウントし、各呼び出しの成功または失敗と、応答にかかる時間をログに記録します。 要求がサービスに対して4.2 秒かかったことを確認でき、その4s がウェアハウスサーバーにあることがわかっている場合は、問題が発生している場所を把握しています。</p>


  <p>サーバーの応答時間が増えると、キャッシュミスが増加する可能性があります。 <a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/">ログトレースイベントまたはメトリック</a>を使用して、以前よりも多くのキャッシュミスが発生しているかどうかを判断できます。 <strong>ログトレースイベント</strong> は、プロセス内のキーポイントを記録したり、内部インターフェイスで問題を追跡したりするために特に役立ちます。 ログトレースイベントの使用は、バックエンドまたはフロントエンドで問題が発生しているかどうかを検出しようとする場合にも役立ちます。</p>


  <p>診断の役割は、この問題がコード障害であるかどうかを特定することです。これは、スケールアップによって解決できるリソースの問題か、外部サービスに関する問題です。</p>


  <p>&rsquo;詳細<a href="https://azure.microsoft.com/blog/service-monitoring-and-diagnostics-2">については、「」を &rsquo; </a>参照してください。</p>


  <h1>まとめ</h1>


  <p>パフォーマンスのバケットにより、トリアージから診断への移行がかなりスムーズになりました。 パフォーマンスバケットの新しいビューでは、サーバーの応答時間の概要と配布が簡単になります。 検出、トリアージ、診断を行った後、問題を解決できます。 これで、実際の問題に対して作業している自信を持って、修正プロセスに進むことができます。</p>
