### YamlMime:Yaml
ms.openlocfilehash: 4e17973ad2f1c997a867f8cf5217c5570c8b28a2
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909548"
Slug: powering-all-your-applications-from-cloud-to-edge-with-azure-infrastructure
Title: 'Azure インフラストラクチャを使用したクラウドからエッジへのすべてのアプリケーションの電源投入 '
Summary: 組織は、クラウドからエッジへの変換、既存のワークロードの移行と最適化、新しいクラウドネイティブアプリの構築、エッジでの新しいシナリオのロック、またはこれらの戦略の組み合わせによって、あらゆるビジネスニーズに対応しています。 Microsoft は、継続的なテクノロジイノベーションによって、これらの機能をどのような方法でもサポートすることを約束しています。 現在、Azure インフラストラクチャポートフォリオ全体の製品の更新プログラムと機能強化について発表し、迅速なビジネス変革を実現しています。
Content: >-
  <p>組織は、クラウドからエッジへの変換、既存のワークロードの移行と最適化、新しいクラウドネイティブアプリの構築、エッジでの新しいシナリオのロック、多様なビジネスニーズに対応 &nbsp; するための戦略の &nbsp; 組み合わせを行っています。 Microsoft は、継続的なテクノロジイノベーションによって、すべての手順を支援 &nbsp; することを約束しています。</p>


  <p>現在、microsoft で &rsquo; は、パフォーマンス、スケーラビリティ、およびセキュリティを向上させるため &nbsp; に、 <a href="https://azure.microsoft.com/en-us/overview/what-is-azure/iaas/#overview" target="_blank">Azure インフラストラクチャポートフォリオ</a>全体で製品の更新プログラムと機能強化を発表しています。 ビジネスニーズに合わせて新しいシナリオを有効 &nbsp; にする&#39;&nbsp; 、長期的な成功に対する柔軟性と選択肢を提供しています。</p>


  <h2>パフォーマンス、スケーラビリティ、およびセキュリティを実現</h2>


  <p>クラウドで実行するアプリケーションワークロードにかかわらず、基盤となるクラウドインフラストラクチャのパフォーマンス、スケーラビリティ、およびセキュリティは、成功に不可欠です。 そのため、Azure は新しいサービスとしてのインフラストラクチャ (IaaS) 機能によって革新を続けます。</p>


  <p><strong>新しい Azure Virtual Machines (Vm) を使用すると、価格パフォーマンスが向上します。</strong> 新しい Intel ベースの Dv5 Vm と Ev5 Vm が一般公開されており、以前の世代と比較して、より優れた価格パフォーマンスを提供します。 新しい AMD ベースの Dasv5 と Easv5 Vm も &nbsp; 利用できます。これにより、以前の世代より優れた価格パフォーマンスが提供され、低価格でローカルディスクストレージを使用せずに &nbsp; オプションを提供できるようになります。 また、新しいメモリ最適化 <a href="https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR5v6ZePlPKxOoBzSWQpMAaRURFRSMEk0STk1WFRFQkpJTENPMThNM1hNWC4u" target="_blank">EBSV5 VM シリーズ</a>のプレビューを発表しました。これにより、以前の VM 世代と比較して、より高いリモートストレージパフォーマンス (最大 4000 MB/秒) が提供されます。 <a href="https://aka.ms/NewVMsBlog21" target="_blank">Vm ポートフォリオが拡張</a>されると、 <a href="https://aka.ms/vm-selector" target="_blank">vm セレクター</a>を使用して、さまざまなワークロードに適した vm とディスクストレージオプションを簡単に識別できます。</p>


  <p><strong>Azure Virtual Machine &nbsp; Scale Sets を使用すると、柔軟なオーケストレーションモードでアプリケーションの可用性を高めることができます。</strong> 一般公開されています。この新機能により、スケールセット内の個々の Vm を完全に制御できるようになり、数千台の Vm で大規模なアプリケーションの回復性を向上させる <a href="https://aka.ms/VMSSFlexGABlogNov21" target="_blank">ことができ</a> ます。</p>


  <p><strong>新しい Azure storage の機能により、スケーラビリティとパフォーマンスが向上します。</strong> 現在一般公開されているオンデマンドのディスクバースティングでは、要求の増加に対応するために、プロビジョニングされた制限を超えるディスクパフォーマンスを向上させることができます。 プレビューで Azure Disk Storage ライブサイズ変更機能を使用すると、必要な変更に簡単に適応できるように、ダウンタイムなしで容量を動的に増やすことができます。 詳細については、 <a href="https://aka.ms/AzureDiskStorage-Ignite2021blog" target="_blank">Azure Disk Storage</a>を参照してください。</p>


  <p><strong>透過的なネットワークアプライアンスの大規模な挿入。</strong> <a href="https://aka.ms/gatewaylbblog" target="_blank">新しいゲートウェイ Load Balancer</a>プレビューでは、サードパーティのネットワークアプライアンスを簡単に拡張およびデプロイし、トラフィックを正常な状態のアプライアンスインスタンスに自動的に再ルーティングして、アプリケーションの高可用性と信頼性を確保することができます。</p>


  <p><strong>大規模な仮想ネットワークの管理。 </strong><a href="https://aka.ms/avnm" target="_blank">Azure Virtual Network Manager</a>は、プレビュー段階でも、ネットワーク管理を一元化するためのワンストップショップです。 拡張性と可用性に優れたネットワーク管理ソリューションを使用すると、仮想ネットワークトポロジを簡単に作成および管理し、大規模なネットワークリソースを保護することができます。&nbsp;</p>


  <p><strong>継続的なイノベーションにより、優れたセキュリティを実現します。</strong> すべての第2世代の Azure Vm に対して信頼された起動を使用すると、これまでよりも簡単にワークロードを強化し、悪意のある攻撃から保護すること &rsquo; ができます。 プライバシーとセキュリティをさらに確保するために、既存のワークロードを <a href="https://aka.ms/ACCIgnite2021" target="_blank">新しい機密 vm</a>にリフトアンドシフトすることができます。プレビューで利用できます。 また、プレビュー段階では、Intel SGX Vm 上の Azure Kubernetes Service (AKS) と AMD 重大度 Vm で、機密コンテナーのオーケストレーションをセキュリティで保護するのに役立ちます。 最大のネットワークセキュリティを確保するために、 <a href="https://aka.ms/BastionStdSkuBlog" target="_blank">新しい Azure 要塞 STANDARD SKU</a>、プライベートピアリングの IPv6 サポート、Advanced macsec のサポートがすべて一般公開されています。 追加のネットワークセキュリティ拡張機能には、拡張された ExpressRoute FastPath サポートのプレビューと、パフォーマンス向上のための <a href="https://aka.ms/WAFIgniteBlog" target="_blank">新しい Application Gateway WAF エンジン</a> が含まれています。</p>


  <h2>ワークロードの移行、最新化、または最適化</h2>


  <p>ほとんどの組織では、従来のワークロードから最新のアプリケーション &mdash; に至るまで、さまざまなアプリケーション &mdash; を実行していますが、それぞれの要件とクラウドの導入戦略は異なります。 私たちの使命は、すべて &nbsp; のアプリケーションを活用するためのプラットフォーム機能を提供することです。 以下は、さまざまなワークロードのニーズ&#39;&nbsp; 顧客に対応する最新の製品更新プログラムを示しています。</p>


  <p><strong>Windows サーバーおよび Linux のワークロードに対する IT 運用の簡素化。</strong> it 管理を自動化して最適化するために、it および DevOps によって<a href="https://aka.ms/AutomanageTCBlog-Ignite21" target="_blank">Azure automanage</a>が使用されます。 一般提供が開始された azure 用の拡張ネットワークと &mdash; azure の自動管理機能の Windows server &mdash; では、Windows サーバーワークロードの移行を簡素化します。 プレビューでは、カスタム構成プロファイルや Azure Arc 対応サーバーのサポートなどの新しい機能強化により、 <a href="https://azure.microsoft.com/en-us/services/azure-automanage/" target="_blank">Windows と Linux vm</a>をより柔軟に管理できるようになりました。</p>


  <p><strong>Azure VMware ソリューションを使用した移行に関するその他のリージョンのカバレッジと機能。</strong> 本日、 &rsquo; ドイツ西部リージョンへの Azure VMware ソリューションの拡張を発表しました。このソリューションは、18の azure リージョンでグローバルに利用できるようになりました。 また、最近、プレビュー段階で azure VMware ソリューション用の<a href="https://aka.ms/diskpool-blog" target="_blank">azure Disk pool integration</a>を開始しました。これにより、データを集中的に使用するワークロードのために Azure Disk Storage を拡張することができます。 さらに、新しく展開されたワークロードシナリオには、Azure VMware ソリューションでの <a href="https://azure.microsoft.com/en-us/services/virtual-desktop/citrix-virtual-apps-desktops-for-azure/" target="_blank">Citrix 仮想デスクトップインフラストラクチャ</a> のサポートが含まれます。</p>


  <p><strong>新しい Azure 仮想デスクトップの機能強化によるリモート作業の最適化。</strong> <a href="https://aka.ms/AVD-Ignite2021-BlogPost" target="_blank">azure 仮想デスクトップ</a>は、完全な Windows 10 と Windows 11 のエクスペリエンスをサポートする唯一のクラウド VDI ソリューションであり、複数のセッションをサポートすることで、azure VM ごとに複数のユーザーをホストできます。 さらにコストの最適化をサポートするために、自動スケールサポートのプレビューについてお知らせ &rsquo; します。これにより、組織は、ピーク時のワークロードに関する可用性をスケジュールし、必要なリソースに対してのみ料金を支払うことができます。 ローカルで実行するデータとアプリケーションのワークロードについては、Azure Virtual Desktop for Azure Stack HCI for preview が役に立ちます。</p>


  <p><strong>最新化は、Azure 上のクラウドネイティブテクノロジを使用します。</strong> Azure で最も高速に機能するサービスの1つである azure Kubernetes Service <strong>&nbsp;</strong> (AKS) を使用すると、完全に管理された Kubernetes サービスを使用して、コンテナー化されたアプリケーションをより簡単にデプロイおよび管理できます。 <a href="https://myignite.microsoft.com/sessions/9c12d736-4ecc-4075-b6a4-5b1fa8ec665e?source=sessions" target="_blank">Microsoft に焦点を当てる: デジタルとアプリのイノベーション</a>、 <a href="https://aka.ms/containerapps/ignite-blog" target="_blank">Azure Container Apps のプレビュー</a>や<a href="https://aka.ms/ignitenov21/cloudnativeappsblog" target="_blank">AKS のオープンサービスメッシュ統合</a>の一般提供を含む最新の AKS &nbsp; およびクラウドネイティブの更新について説明します。</p>


  <p><strong>移行と近代化に関するその他のオプション。</strong>最近、新しい app コンテナー化 tool を発表し、SQL と .net の web の最新化を実現するための検出と評価の機能が向上し、Azure Migrate でエージェントレスのソフトウェアインベントリと依存関係分析が一般公開されました。 また、Azure Migrate アプライアンスのオンボードエクスペリエンスをさらに簡略化しまし &rsquo; た。 <a href="https://aka.ms/IgniteNov21/MigrateModernizeBlog" target="_blank">Azure Migration And 近代化 Program (AMMP)</a>の追加のシナリオに関する新たに発表されたサポートの詳細については、SAP、azure Arc を使用したハイブリッド、セキュリティ、アプリケーションの最新化サポートの強化に関するページを参照してください。</p>


  <h2>ハイブリッド、マルチクラウド、エッジをまたいで新しいシナリオのロックを解除する</h2>


  <p>今週は、azure Azure Stack Arc の最新の機能とイノベーションを、 <a href="https://myignite.microsoft.com/sessions/27b4aeb9-ba89-403c-9cdf-4c629eb538c1?source=sessions" target="_blank">Microsoft Azure セッションを使用したハイブリッドおよびマルチクラウドで</a>の HCI のセキュリティで保護された開発とイノベーションによって共有し、完全な Azure ハイブリッドポートフォリオについて学習し、最新情報を入手するための<a href="https://aka.ms/arcskilling" target="_blank">1 つのリソース</a>を提供しました。</p>


  <p>さらに、より多くのエッジシナリオをサポートするために、引き続き IoT 機能を拡張します。 <a href="https://techcommunity.microsoft.com/t5/internet-of-things/building-multi-tenant-solutions-with-azure-iot-central/ba-p/2617416" target="_blank">Azure IoT Central</a>では、組織のサポートが導入されています。 この高度に要求された機能によって、メインストリーム導入用の IoT が簡略化されます IoT ソリューションを1回作成し、複数のテナントをオンボードすることで、コストを抑え、管理オーバーヘッドを削減できるように &mdash; なりました。 さらに、 <a href="https://techcommunity.microsoft.com/t5/internet-of-things/windows-server-iot-2022-now-generally-available/ba-p/2703521" target="_blank">Windows Server iot 2022</a>と<a href="https://techcommunity.microsoft.com/t5/internet-of-things/windows-for-iot-now-goes-to-11-with-windows-11-iot-enterprise/ba-p/2850335" target="_blank">Windows 11 iot Enterprise</a>が一般公開されました。 &nbsp;<a href="https://azure.microsoft.com/en-us/resources/iot-signals/" target="_blank">Microsoft iot の信号</a>を使用してエッジ戦略を強化するために、IoT 戦略、ビジネスの成長、持続性とサイバーセキュリティに関する考慮事項について詳しく説明します。</p>


  <h2>詳細については、追加のリソースにアクセスしてください</h2>


  <p>私たちは、Microsoft Ignite で今週のご参加をお願いしており、後でオンデマンドセッションを監視する予定です。 Microsoft の「<a href="https://myignite.microsoft.com/sessions/5fbb6a38-0535-4df0-8d86-7743745c7de0?source=sessions" target="_blank">インフラストラクチャセッション</a> &nbsp; 」を参照して、 <a href="https://aka.ms/ignite-book-of-news" target="_blank">microsoft Ignite のニュース</a>に記載されているすべてのお知らせをご覧ください。 コンピューティング、ストレージ、およびネットワーク &mdash; &rsquo; にわたる iaas ソリューションの詳細については、2021年11月 &nbsp; 17 日に、<a href="https://info.microsoft.com/ww-landing-azure-iaas-day.html" target="_blank">無料の Azure iaas Day</a>デジタルイベントを見逃しません。 <a href="https://info.microsoft.com/ww-landing-azure-iaas-day.html" target="_blank">今すぐ登録</a>してください!</p>


  <hr>

  <p><em>Microsoft.目的を持つ在庫。</em></p>
