### YamlMime:Yaml
ms.openlocfilehash: 3cdcefefff7ec3f0fc061e979856ec6f43eaee8e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909559"
Slug: power-your-business-applications-data-with-analytical-and-predictive-insights
Title: 分析と予測の分析情報を使用してビジネス アプリケーション のデータを活用する
Summary: 過去 2 年間、お客様からのフィードバックにより、データ バリアが解消された場合、分析の影響が指数関数的に増加する可能性が明らかになってきました。 現在、microsoft Dataverse 用の Azure Synapse Link を使用してビジネス アプリケーションと分析システムの間の障壁を排除することで、データの分析情報をすべてのユーザーに提供する次のステップを発表します。
Content: >-
  <p>デジタル変革を成功するには、不要な障壁を排除する必要があります。 その結果、2019 <a href="https://azure.microsoft.com/services/synapse-analytics/" target="_blank">年</a> 11 月にAzure Synapse Analytics発表しました。そこで、データ ウェアハウスとビッグ データ分析の間の障壁が取り除かれました。 また、2020 年にこれを一歩進め、Azure Synapse <a href="https://azure.microsoft.com/en-us/blog/azure-analytics-clarity-in-an-instant/" target="_blank">Link for Azure Cosmos DB</a> を発表し、運用データと分析システムの間に長い間存在していた障壁を打破しました。</p>


  <p>過去 2 年間、お客様からのフィードバックにより、データ バリアが解消された場合、分析の影響が指数関数的に増加する可能性が明らかになってきました。 本日、&rsquo;microsoft Dataverse 用 Azure Synapse Link を使用してビジネス アプリケーションと分析システムの間の障壁を排除することで、データの分析情報をすべてのユーザーに提供する次のステップを発表しました。</p>


  <h2>Dataverse Azure Synapseリンクの紹介</h2>


  <p>ビジネス アプリケーション データと分析システムの間の障壁は、分析情報の迅速化を妨える重要な要因です。 開発者が Microsoft Power Apps、Microsoft Power Automate、Microsoft Dynamics 365 などのプラットフォームを使用してビジネス アプリケーションを作成および管理する場合、これらのアプリケーションから取得されるデータは膨大です。 現在、お客様は、すべての Microsoft ビジネス アプリケーションの <a href="https://powerplatform.microsoft.com/en-us/dataverse/" target="_blank">Dataversea</a>&mdash; 共通ストアにこのデータを格納および管理しています。 ただし、お客様が Dataverse 内のデータから深い分析情報を検出する場合は、多数のサービスを組み合わせて、またはデータを絶えずコピーする必要があります。このため、データ チームのメンテナンスが絶えず行き来し、より多くの作業が必要になります。</p>


  <p>Dataverse 内のデータは、分析によって簡単に表面化できる潜在的な分析情報の金色です。 Azure Synapse Link for Dataverse を使用すると、ビジネス アプリケーションに流れるデータが分析ソリューションにも流れ込むのを自動的に確認できます。 これにより、お客様は&mdash;、高度な分析タスクをビジネス アプリケーション内のデータの管理と並行して実行できます。これらは個別のワークストリームにする必要があります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e7c61190-7058-424d-a3b2-653af7c059b3.gif"><img alt="Azure Synapse Link for Dataverse GIF" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a7e04bbb-a0e9-4e05-a352-c5f2b6ab4e19.gif" style="display: inline;" title="" width="1024"></a></p>


  <h2>それはどのように機能しますか?</h2>


  <p>数回のクリックで、Power Apps または Dynamics 365 で作業している開発者は、Dataverse 環境全体をAzure Synapse。 お客様はボタンをクリックし、自分の&nbsp;Azure Synapseを入力します。 また、シームレスなエクスペリエンスを&rsquo;実現するために、開発者は Power Apps または Dynamics 365 ポータルを離れる必要がAzure Synapse。 [Go <strong>to Azure Synapse Analytics ワークスペース</strong><em></em>] をクリックするだけで、エンドツーエンドの分析サービスを使用して分析情報の検出を開始できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c0f5ae3c-3815-4976-b9bd-f297b142dc68.png"><img alt="Screenshot of developers working in Power App bringing their entire Dataverse environment to Azure Synapse. " border="0" height="937" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/36168fa8-713d-48a8-89e3-d2cd6f7ff898.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="DataverseSynapseLink" width="1920"></a></p>


  <p>Azure Synapse Link for Dataverse の詳細については、最新のブログ記事「<a href="https://aka.ms/synapse-dataverse-tech" target="_blank">Dataverse</a>&quot; と Azure Synapse Analytics を接続して分析情報の取得までの時間を加速する」を参照してください。&quot;</p>


  <h2>概要今日</h2>


  <ul>
      <li>概要無料 <a href="https://azure.microsoft.com/en-us/free/synapse-analytics/" target="_blank">でAzure Synapse Analyticsを</a> 開始できます。</li>
      <li>Azure Synapse Link for Dataverse の詳細については、ドキュメントを <a href="https://aka.ms/synapse-dataverse-docs" target="_blank">参照してください</a>。</li>
  </ul>


  <hr>

  <p><em>Azure。目的を持って発明する。</em></p>
