### YamlMime:Yaml
ms.openlocfilehash: e368f4b35cbef9e4f26d335e55cc91795c079046
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910636"
Slug: preview-of-custom-content-in-azure-policy-guest-configuration
Title: Azure Policy のゲスト構成におけるカスタムコンテンツのプレビュー
Summary: 現在、Azure Policy の新機能のプレビューを発表しています。 Linux と Windows の仮想マシン (vm) 内の設定を監査するゲスト構成機能は、ユーザーがカスタムコンテンツを作成および発行できるようになりました。
Content: >-
  <p>現在、Azure Policy の新機能のプレビューが発表されています。 Linux と Windows の仮想マシン (vm) 内の設定を監査するゲスト構成機能は、ユーザーがカスタムコンテンツを作成および発行できるようになりました。</p>


  <p>ゲスト構成プラットフォームは、Microsoft によって提供される組み込みコンテンツで一般公開されています。 お客様は、このプラットフォームを使用して、サーバーへのアクセス権を持つユーザー、インストールされているアプリケーション、証明書が最新のものであるかどうか、サーバーがネットワークの場所に接続できるかどうかなど、一般的なシナリオを監査します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d2d0531c-4e01-48be-9e08-e26d6760c504.png"><img alt="An image of the Definitions page in Azure Policy." border="0" height="683" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9a7b8abf-99f0-4aa6-9b62-30222d45fac6.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Azure Policy の [定義] ページの画像。" width="1024"></a></p>


  <p>現在、お客様は、PowerShell ギャラリーに発行された新しいツールを使用して、開発者のワークステーションと、Azure DevOps などの CI/CD プラットフォームの両方で独自のコンテンツパッケージを作成、テスト、および発行することができます。</p>


  <p>たとえば、組織によって開発された Azure の仮想マシンでアプリケーションを実行している場合、Azure でそのアプリケーションの構成を監査し、保有している Vm の1つが準拠していないときに通知を受けることができます。</p>


  <p>これは、構成基準を監査する必要があるコンプライアンスチームの重要なマイルストーンでもあります。 Microsoft &rsquo; が推奨するセキュリティ構成基準を使用して Windows マシンを監査する組み込みのポリシーが既にあります。 &nbsp;カスタムコンテンツを利用すると、一般的な構成の詳細情報であるグループポリシーからコンテンツにシナリオを拡張できます。 グループポリシー形式から Azure Policy のゲスト構成で使用される desired state configuration 構文に変換するための <a href="https://docs.microsoft.com/en-us/powershell/dsc/quickstarts/gpo-quickstart">ツールが用意</a> されています。 グループポリシーは、規制標準を公開する組織によって使用される一般的な形式であり、企業組織がプライベートデータセンターのサーバーを管理するための一般的なツールです。</p>


  <p>最後に、カスタムコンテンツパッケージを発行しているお客様には、サードパーティ製のツールを含めることができます。 多くのお客様は、運用環境にリリースする前に、仮想マシン内の設定の監査を実行するために使用される既存のツールを備えています。 例として、 <a href="https://github.com/microsoft/gcinspec" target="_blank">gcInSpec</a> モジュールは、Microsoft と Chef の管理を含むオープンソースプロジェクトとして公開されています。 お客様は、このモジュールをコンテンツパッケージに含めて、Chef InSpec への既存の投資を使用して Windows 仮想マシンを監査することができます。</p>


  <p>詳細について、Azure Policy のゲスト構成でカスタムコンテンツを使用する方法については、ドキュメントページ &rdquo; の「<a href="https://docs.microsoft.com/en-us/azure/governance/policy/how-to/guest-configuration-create" target="_blank">ゲスト構成ポリシーの作成方法</a>」を参照してください。&rdquo;</p>
