### YamlMime:Yaml
ms.openlocfilehash: b8f5153e01301d729af1835a1aaa2c793c2be389
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139897050"
Slug: proactive-notifications-on-cloud-service-issues-with-azure-diagnostics-and-application-insights
Title: クラウド サービスに関するクラウド サービスの問題に関するプロアクティブな通知Azure Diagnosticsとアプリケーションのインサイト
Summary: 'アプリケーション インサイト、問題の解決に役立つ診断情報を提供する他に、Azure Cloud Services ロールに一般的な問題が発生した場合に通知が送信されます。 '
Content: >-
  <p>お使いのアプリケーションは、Azure Cloud Services (Web ロールと worker ロール) で実行されていますか?</p>


  <p>現在、Application インサイト では、起動エラー、クラッシュ、ハング、頻繁なリサイクルなど、アプリケーションに影響を与える可能性がある一般的な問題が発生したロールに関する電子メールが送信されます。 また&rsquo;、スタック トレースやエラー メッセージなどの診断情報も含まれるので、サーバーにログインすることなく問題を診断できます。</p>


  <p>さらに何か必要ですか? <a href="https://azure.microsoft.com/documentation/articles/app-insights-cloudservices/" target="_blank">Application インサイト SDK</a>&rsquo; をサービスに追加すると、アプリケーションが問題の影響を受けた方法、すべての例外へのリンク、失敗した HTTP 要求、および失敗した依存関係呼び出しが、その時点でキャプチャされた状態でお知らせします。 これは、原因の診断に役立つさらに多くの資料が提供されるだけでなく、ユーザーに対する重大度と影響をよりよく理解するのに役立ちます。</p>


  <p><img alt="Proactive Notification Email" border="0" height="480" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ff04c85e-ba5c-466b-9fe1-d52a513d06f0.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="プロアクティブ通知メール" width="464"></p>


  <p>この機能により、11 月に発表した Azure Diagnostics と <a href="https://azure.microsoft.com/en-us/blog/azure-diagnostics-integration-with-application-insights/" target="_blank">Application インサイト</a> の統合が追加されます。 Azure portal で Application インサイト に移動すると、ロールの失敗やパフォーマンスの低下などのプラットフォームの問題と共に、アプリのパフォーマンスのタイムラインがプロットされているのを確認できます。</p>


  <p>電子&rsquo;メールで送信されるプロアクティブ通知を追加することで、この機能を拡張しています。 これにより、ポータルを継続的に監視することなく、問題を確認できます。 これらの&rsquo;通知は、Azure Cloud Service を設定するときに自動的に取得し、診断データを Application インサイト に送信するように構成します。 他に何も必要ありません。</p>


  <p>&nbsp;</p>


  <p>Application インサイト UserVoice ページで新機能または改善された機能に関するアイデアを共有し、Application インサイト フォーラムに質問<a href="https://social.msdn.microsoft.com/Forums/en-US/ApplicationInsights/" target="_blank">を送信してください</a>。</p>
