### YamlMime:Yaml
ms.openlocfilehash: 752d9fad5564002e66d57eeaf9a594a3969179dd
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909536"
Slug: protecting-applications-and-data-on-azure-stack
Title: Azure Stack でのアプリケーションとデータの保護
Summary: Azure Stack は、クラウドコンピューティングに投資している多くの企業にとって、戦略に大きな変化をもたらします。 この記事では、さまざまなアプリケーションの種類と回復の目標を達成するために、ビジネスニーズに合ったソリューションについて考えてみましょう。
Content: >-
  <p>Azure は、54のリージョンにわたって Microsoft データセンターで実行されているグローバル規模のクラウドコンピューティングを提供しています。 Azure Stack は、お客様 &rsquo; またはサービスプロバイダーのデータセンターで実行されている統合システムで実行できるサービスのコアセットを作成することにより、Azure の価値を幅広い顧客やシナリオに拡張します。 多くの企業やサービスプロバイダーは、Azure Stack Development Kit (ASDK) を評価して詳細を把握しています。 これらの企業の多くは、最新のアプリとオンプレミスのクラウドサービスを対象としたハイブリッドクラウドの戦略、設計、実装によって評価されることはありません。 ビジネス継続性とディザスターリカバリー (BC/DR) 計画は、包括的な戦略の重要な部分です。</p>


  <p>事業継続とディザスター リカバリー計画は、密接に関連するプロセスで、予期しないリスクに備えるために会社によって使用されます。 この記事では、 &rsquo; さまざまなアプリケーションの種類と回復の目標を達成するために、ビジネスニーズに合ったソリューションについて考えてみましょう。 これらの目標は、選択した BC/DR 戦略に直接影響します。</p>


  <h2>Azure Stack BC/DR 領域</h2>


  <p>BC/DR 戦略で考慮すべき主な領域には、次の4つがあります。</p>


  <ul>
   <li>IaaS 仮想マシン、PaaS サービス、およびテナントアプリケーションとデータをホストする、基になるインフラストラクチャを保護します。</li>
   <li>IaaS ベースのアプリケーションとデータを保護します。</li>
   <li>PaaS ベースのアプリケーションとデータを保護します。</li>
   <li>長期的な保有期間の PaaS データをアーカイブします。</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/189e1431-5877-4e52-a9a0-82eacda3423c.png"><img alt="azure-stack" border="0" height="257" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cb4adbbb-1970-43a7-bb4f-c5069a93be7c.png" style="border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="azure stack " width="414"> </a> このブログでは、バックアップと復元のための Microsoft およびパートナー製品を使用した IaaS 仮想マシンベースのアプリケーションとデータの保護、レプリケーションとフェールオーバーについて重点的に説明しています。 Azure Stack チームは複数のパートナーと連携して、サード パーティのソリューションが Azure Stack 上で確実に機能するようにしています。&nbsp;</p>


  <h2>IaaS 仮想マシンベースのアプリケーションのバックアップと復元</h2>


  <p>Azure Stack は、IaaS Azure Resource Manager 仮想マシンとしてプロビジョニングされた仮想マシンにデプロイされた Windows および Linux ベースのアプリケーションをサポートしています。 ゲストオペレーティングシステム (OS) にアクセスできるバックアップ製品では、今日使用する類似のポリシーを使用して、ファイル、フォルダー、OS の状態、およびアプリケーションデータを簡単に保護できます。 Azure Backup や System Center data Center Protection Manager、サードパーティ製品などの Microsoft 製品を使用して、オンプレミス、サービスプロバイダー、または Azure に直接データをバックアップすることができます。 このアプローチでは、使い慣れた製品を使用してアプリケーションやデータを保護するための柔軟な選択肢が提供されます。</p>


  <h2>IaaS 仮想マシンベースのアプリケーションのレプリケーションとフェールオーバー</h2>


  <p>ダウンタイムを最小限に抑え、データ損失を最小限に抑える必要があるアプリケーションでは、追加の保護が必要です。 バックアップと復元は、長期にわたってアプリケーションのダウンタイムを許容できるお客様に最適です。 ただし、最小限のダウンタイムを実現するには、データを2次拠点にレプリケートし、障害発生時にアプリケーションのフェールオーバーを調整する必要があります。 Azure Stack では、Azure Site Recovery を使用して直接 Azure にデータをレプリケートし、アプリケーションをフェールオーバーして Azure で実行することができます。この機能は現在 technical preview で使用できます。 Microsoft SQL などのネイティブレプリケーションをサポートする Azure Stack に配置されたアプリケーションは、アプリケーションが実行されている別の場所にデータをレプリケートできます。 サードパーティのレプリケーションおよびオーケストレーション製品を使用して、アプリケーションを別の場所にフェールオーバーすることもできます。 この方法では、バックアップと復元と同様に、アプリケーションとデータを柔軟に保護することができます。</p>


  <h2>Azure Stack のパートナーと展開シナリオ</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/749cc111-f291-4440-aad5-8baa089f97d4.png"><img alt="IaaS-virtual-machines" border="0" height="453" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6d4b013c-280d-45c1-93d0-2eafb662f1fc.png" style="border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="IaaS-仮想マシン" width="1024"></a></p>


  <h2>パートナーからの追加情報</h2>


  <p><a href="https://aka.ms/azurestackbcdrpartners" target="_blank">Azure Stack データセンター統合パートナー エコシステム</a> データシートに記載されている、サポートされているパートナーの完全な一覧。</p>


  <h2>一般提供に関する重要な考慮事項</h2>


  <ul>
   <li>ゲスト内保護 &mdash; Azure Stack では、IaaS 仮想マシンのゲストレベルの保護テクノロジのみがサポートされます。 Azure Stack は、基盤となるインフラストラクチャサーバーへのエージェントのインストールをサポートしておらず、ハイパーバイザーベースのテクノロジに依存しません。</li>
   <li>Azure Site Recovery &mdash; Azure Site Recovery technical preview では、azure へのフェールオーバーと azure でのテストフェールオーバーがサポートされています。 Azure から Azure Stack にフェールバックするには、IaaS 仮想マシンをシャットダウンし、データを Azure Stack インスタンスに手動でコピーしてから、IaaS 仮想マシンを再作成する必要があります。 その時点で、新しいインスタンスとして IaaS 仮想マシンの保護を有効にすることができます。</li>
   <li>サイト間の保護 &mdash; 2 つの Azure Stack クラウド間で IAAS VM リソースを保護するには、いずれかのパートナーの製品を使用します。&nbsp;</li>
  </ul>


  <h2>致命的なデータ損失からの復旧</h2>


  <p>BC/DR 計画では、Azure Stack クラウド全体を完全にオフラインにする障害から復旧するように会社を準備する必要があります。これにより、完全かつ回復不可能なデータ損失が発生します。 Azure Stack クラウドを展開するには、ハードウェアベンダーに問い合わせる必要があります。 セカンダリサイトがある場合は、そこに Azure Stack インスタンスをデプロイすることを検討してください。これにより、新しいクラウドのデプロイを待機することなく、テナントアプリケーションとデータを回復できます。</p>


  <h2>次の手順</h2>


  <p>ASDK を今すぐダウンロードしてインストールし、ハイブリッドクラウドでアプリケーションをホストする方法について理解を深めましょう。 Azure Stack にデプロイする予定のアプリケーションについての洞察を得るために、アプリケーションの回復目標を検討してください。 意味のあるさまざまな保護スキームを特定し、これらの目標を達成するために役立つテクノロジと製品を検討してください。</p>


  <p>Azure Stack での BC/DR シナリオのサポート方法については、ベンダーにお問い合わせください。 ASDK でアプリケーションとデータ保護のテストを開始します。&nbsp;</p>


  <p><strong>ドキュメント</strong></p>


  <ul>
   <li>ユーザー IaaS Vm <ul style="list-style-type:circle;">
    <li><a href="https://docs.microsoft.com/azure-stack/user/azure-stack-manage-vm-protect">Azure Stack にデプロイされた VM の保護</a></li>
    <li><a href="https://docs.microsoft.com/azure/backup/backup-mabs-install-azure-stack">Azure Stack への Azure Backup Server のインストール</a></li>
    <li><a href="https://docs.microsoft.com/azure/site-recovery/azure-stack-site-recovery">Azure Stack VM を Azure にレプリケートする</a></li>
   </ul>
   </li>
   <li>インフラストラクチャ <ul style="list-style-type:circle;">
    <li><a href="https://docs.microsoft.com/azure-stack/operator/azure-stack-backup-infrastructure-backup">Infrastructure Backup サービスを使用した Azure Stack のデータの回復</a></li>
    <li><a href="https://docs.microsoft.com/azure-stack/operator/azure-stack-backup-reference">インフラストラクチャ バックアップ サービスのリファレンス</a></li>
    <li><a href="https://docs.microsoft.com/azure-stack/operator/azure-stack-backup-enable-backup-console">管理者ポータルで Azure Stack のバックアップを有効にする</a></li>
   </ul>
   </li>
  </ul>


  <h2>詳細情報</h2>


  <p>追加のガイダンスについては、「 <a href="https://aka.ms/azurestackbcdrconsiderationswp" target="_blank">ビジネス継続性とディザスターリカバリーに関する Azure Stack の考慮事項」ホワイトペーパー</a> を参照してください。</p>


  <ul>
   <li>Azure Stack の BC/DR に関する最新情報については、IaaS VM ブログシリーズの第4部をご覧ください。 <ul style="list-style-type:circle;">
    <li><a href="https://azure.microsoft.com/blog/azure-stack-iaas-part-four/">パート 4 &ndash; で自分の内容を保護する</a></li>
   </ul>
   </li>
  </ul>
