### YamlMime:Yaml
ms.openlocfilehash: 0ec43e81abda8d0c631bcd109e28bdaa0f4996e2
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139889007"
Slug: real-time-serverless-applications-with-the-signalr-service-bindings-in-azure-functions
Title: リアルタイムのサーバーレス アプリケーションと、SignalR ServiceのバインドAzure Functions
Summary: 'Microsoft Ignite 2018 のパブリック プレビュー発表以降、世界中の何千人もの開発者が、Azure Functions の Azure SignalR Service バインドを利用して、サーバーレス アプリケーションにリアルタイム機能を追加してきました。 '
Content: >-
  <p>Microsoft Ignite 2018 のパブリック プレビュー発表以降、世界中の何千人もの開発者が、Azure Functions の Azure SignalR Service バインドを利用して、サーバーレス アプリケーションにリアルタイム機能を追加してきました。 本日は、これらのバインディングが利用可能なすべてのグローバル リージョンで一般Azure SignalR Serviceお知<a href="https://azure.microsoft.com/en-us/global-infrastructure/services/?products=signalr-service&amp;regions=all" target="_blank"></a>らせします。</p>


  <p>SignalR Serviceは、HTTP を使用してアプリケーションにリアルタイム Web 機能を追加するプロセスを簡略化する、フル マネージドの Azure サービスです。 このリアルタイム機能により、サービスは WebSocket などのテクノロジを使用して、接続されたクライアントにメッセージとコンテンツの更新をプッシュできます。 その結果、クライアントは、サーバーをポーリングしたり更新プログラムについて新しい HTTP 要求を送信したりしなくても更新されます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fb574bf4-b92d-417f-a380-e23713366813.gif"><img alt="20190306-real-time-app-gif" border="0" height="453" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/691a8794-113e-4065-a402-7f78a3069288.gif" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="20190306-real-time-app-gif" width="867"></a></p>


  <p>Azure Functionsは、イベント駆動型アプリケーションの高速開発とサーバーレス ホスティングのためのトリガーとバインドに基づく生産性の高いプログラミング モデルを提供します。 これにより、開発者は、ローカルでのビルドとデバッグからクラウドへのデプロイと監視まで、エンド to エンドの開発者エクスペリエンスを使用して、好みでプログラミング言語とツールを使用してアプリを構築できます。 これらのバインディングAzure SignalR Service Azure Functionsを組み合わせると、わずか数行のコードでアプリケーションの UI に更新プログラムを簡単にプッシュできます。 イベントに応答するスクリプトの実行を開始する Azure Functions でサポートされているトリガーにより、これらの更新のソースは、さまざまな Azure サービスまたは HTTP を介して通信できる任意のサービスからのデータである可能性があります。</p>


  <p>言及する価値のある一般的なシナリオは、データベースに対して行われた変更に基づいてアプリケーションの UI を更新する場合です。 Cosmos DB 変更フィード、Azure Functions、および SignalR Service を組み合わせて使用すると、これらの更新プログラムを受信し、更新プログラム自体をプッシュするクライアントを登録するためのコードを数行だけ使用して、これらの UI 更新をリアルタイムで自動化できます。 このフル マネージド エクスペリエンスは、イベント駆動型のシナリオに最適であり、リアルタイム機能を備え、サーバーレス バックエンドとアプリケーションを作成し、開発時間と操作のオーバーヘッドを削減できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6426254d-271f-4fa6-bf8f-699f400851e4.png"><img alt="20190306-real-time-app-graphic" border="0" height="455" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/88842d74-05c7-418c-b3e7-5776efaf9d30.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="20190306 - リアルタイムアプリグラフィック" width="854"></a></p>


  <p>次のAzure SignalR ServiceのAzure Functionsを使用できます。</p>


  <ul>
   <li>フル マネージドSignalR Serviceサーバーレス エクスペリエンスを得る場合は、アプリケーション サーバーに依存せずにアプリケーション を使用します。</li>
   <li>一般に利用可能なすべての言語 (JavaScript、C#、Java) Azure Functionsを使用して、サーバーレスリアルタイム アプリケーションを構築 <a href="https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-java-support-in-azure-functions/" target="_blank">します</a>。</li>
   <li>Azure Functions でサポートされているすべてのイベント トリガーと組み合SignalR Serviceバインドを利用して、接続されているクライアントにリアルタイムでメッセージをプッシュします。</li>
   <li>セキュリティApp Serviceを強化SignalR Serviceフル マネージドAzure Functions認証を行う場合は、SignalR Service と Azure Functions 認証を使用します。</li>
  </ul>


  <h2>次の手順</h2>


  <ul>
   <li>ドキュメント「Build &ldquo;<a href="https://aka.ms/af-binding" target="_blank">real-time apps with Azure Functions and Azure SignalR Service」を参照</a>してください。&rdquo;</li>
   <li>クイック スタート「JavaScript を使用&ldquo;してチャット ルームを作成Azure Functions<a href="https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-javascript" target="_blank">、SignalR Serviceを</a>&rdquo;使用して開始します。</li>
   <li>その他のコード サンプルについては、GitHub<a href="https://github.com/Azure-Samples/signalr-service-quickstart-serverless-chat" target="_blank">してください</a>。</li>
   <li>Azure アカウントに <a href="https://azure.microsoft.com/free/serverless" target="_blank">無料で</a> サインアップします。</li>
  </ul>


  <p>フィードバック&#39;コメントをお寄せください。 製品チームに連絡するには、GitHub<a href="https://github.com/azure/azure-signalr/issues" target="_blank">または</a>電子メールを使用<a href="mailto:asrs@microsoft.com">します</a>。&nbsp;</p>
