### YamlMime:Yaml
ms.openlocfilehash: 15a05fdecaa365e08199f098b927976fae0a13c9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910453"
Slug: research-shows-cloud-computing-reduces-time-and-money-spent-managing-security
Title: 調査によると、クラウド コンピューティングでは、セキュリティの管理に費やされる時間とコストが削減されます
Summary: 'セキュリティは、多くの場合、企業向けクラウド コンピューティングの導入に関する主な懸念事項または障壁の 1 つとして報告されます。 この認識を払い払い出す助けとして、現在、Microsoft は、中小企業がクラウドを使用して IT セキュリティ上の大きなメリットを得たと示す研究を発表しました。 '
Content: >-
  <p>セキュリティは、多くの場合、<a href="https://azure.microsoft.com/en-us/overview/what-is-cloud-computing"></a>&nbsp;企業のクラウド コンピューティング機能に対する主な懸念事項または障壁の 1 つとして報告されます。 この認識を払い払い出す助けとして、<span style="background-color: #ffffff;">Microsoft <a href="https://www.microsoft.com/en-us/news/Press/2012/May12/05-14SMBSecuritySurveyPR.aspx" target="_blank"></a></span>は今日、中小企業 (SMB) がクラウドを使用して IT セキュリティ上の大きなメリットを得たと示す research をリリースしました。</p>


  <p>この調査は、Microsoft によって委託され、調査会社 comScore によって実施され、米国、シンガポール、シンガポール、インド、香港市場の SMB 企業に投票しました。</p>


  <p>米国の調査結果は、次の 3 つの主な領域で利点を示しています。</p>


  <ul>
   <li>時間の節約: 米国企業の 32% が、サイバー攻撃の脅威について心配する時間を減らしたと言っています。</li>
   <li>コスト削減: クラウドを使用する SBS は、クラウドを使用していない SBS よりも、セキュリティに費やされた総量の 6 倍近く減少している可能性が高い。</li>
   <li>セキュリティの向上: 米国企業の 35% が、クラウドへの移行以降、大幅に高いレベルのセキュリティを経験しています。</li>
  </ul>


  <p>クラウド サービスを使用する前にセキュリティを管理するために費やされた時間とコストは、ビジネスを拡大し、競争力を高め、SBS によって再投資されています。</p>


  <p>この調査の詳細については、Microsoft ニュース<a href="https://www.microsoft.com/en-us/news/Press/2012/May12/05-14SMBSecuritySurveyPR.aspx" target="_blank">および</a> Trustworthy Computing ブログを参照してください<span style="background-color: #ffffff;"><i>。</i>&nbsp;</span>&nbsp;</p>
