### YamlMime:Yaml
ms.openlocfilehash: aee0cfeb027a5f349a5943a0a848d2795c7fca37
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910378"
Slug: run-remote-applications-anytime-anywhere-with-frame-for-azure-government
Title: Azure Government のフレームを使用していつでもリモートアプリケーションを実行
Summary: 'Microsoft Government Tech サミットでは、このフレームが Azure Government で利用可能であることが発表されました。 フレームを使用すると、オンプレミスの仮想デスクトップインフラストラクチャ (VDI) のコストをかけることなく、セキュリティで保護されたサービスとしてのデスクトップ (DaaS) 機能をデプロイできます。 '
Content: >-
  <p><em>このブログ投稿は、Azure Global (主要プログラムマネージャー) によって作成されました。 </em></p>


  <p>Microsoft Government Tech サミットでは、この <a href="https://fra.me/">フレーム</a> が Azure Government で利用可能であることが発表されました。 フレームを使用すると、オンプレミスの仮想デスクトップインフラストラクチャ (VDI) のコストをかけることなく、セキュリティで保護されたサービスとしてのデスクトップ (DaaS) 機能をデプロイすることができます。また、フレーム政府エディションでは、この機能が強化され、政府 Microsoft Azure クラウド &ndash; にデプロイすることができます。</p>


  <p>フレームのお客様には、Azure Government でホストされ、NV シリーズの仮想マシンによって支えられているグラフィックス集中型アプリケーションを利用するための web ブラウザーが必要です。 高価なハイエンドワークステーションは不要になりました。 また、<a href="https://blog.fra.me/launch-apps-on-frame-directly-from-office-365-f53d0ce46c83">ユーザー &rsquo; の Office 365 アプリランチャーにフレームアプリケーションを追加することで</a>、ユーザーエクスペリエンスを簡素化することもできます。</p>


  <p>Jason Holloway は、フレームの公共セクターの先頭で<i>あり、フレームプラットフォーム政府エディションは、 &quot; エンタープライズ対応の仮想化ソリューションを提供します。これにより、クラウド内の Windows デスクトップアプリケーションの移行と管理が簡単になります。フレームプラットフォームを Azure Government で使用できるようにすることは、市場</i> <i>-</i> をリードするコマーシャルプラットフォームを公共のセクターに届けるための主要なマイルストーン<i>です。 &rdquo; </i></p>


  <p>詳細については、「 <a href="https://fra.me/frame-azure-gov-GA">Frame&#39;s のお知らせ </a>」を参照し、アクセス権を要求する方法を確認してください。</p>


  <p>また、米国のセキュリティ &amp; ソリューションのディレクターである<a href="https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchannel9.msdn.com%2Fblogs%2FAzure-Government%2FVDI-with-Frame-on-Azure-Government&amp;data=04%7C01%7Ctina.meek%40microsoft.com%7C65c230618689442119c208d57fc15081%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636555390641305455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&amp;sdata=ynYE4ttCALLUqqB2uXK7YUHTMtimzMkve829tfcGBcs%3D&amp;reserved=0">最近のインタビュー</a>を視聴することもできます。これにより、政府ユーザーにとって興味深いデモと共に、フレーム&#39;s オファリングについての洞察を得ることができます。</p>


  <h2>詳細情報</h2>


  <ul>
      <li><a href="https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmedium.com%2F%40jason.holloway%2F136157954bf4&amp;data=04%7C01%7Ctina.meek%40microsoft.com%7C65c230618689442119c208d57fc15081%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636555390641305455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&amp;sdata=G2S7wU7eNeKg025j4VYd2EUSAv9ilc%2Fh7EzQqDqbvJ4%3D&amp;reserved=0">公共のセクターに合わせた調整: フレームは Microsoft Azure Government で一般提供されています。</a></li>
      <li><a href="https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchannel9.msdn.com%2Fblogs%2FAzure-Government%2FVDI-with-Frame-on-Azure-Government&amp;data=04%7C01%7Ctina.meek%40microsoft.com%7C65c230618689442119c208d57fc15081%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636555390641305455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&amp;sdata=ynYE4ttCALLUqqB2uXK7YUHTMtimzMkve829tfcGBcs%3D&amp;reserved=0">Azure Government デモのフレーム</a></li>
  </ul>
