### YamlMime:Yaml
ms.openlocfilehash: 21801126577cf5e0b9895cdbcc3cd508073da253
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910364"
Slug: run-your-core-applications-on-azure
Title: Azure でコア アプリケーションを実行する
Summary: Microsoft Ignite では、Microsoft Ignite で、増え続ける顧客と独立系ソフトウェア ベンダー (ISV) が、Azure でミッションおよびビジネスクリティカルなアプリケーションを実行する方法について説明しました。
Content: >-
  <p><a href="https://aka.ms/NavneetIgnite2020Session" target="_blank">Microsoft Ignite</a> では、この週、ますます増え続ける顧客と独立系ソフトウェア ベンダー (ISV) が、Microsoft Azure でミッションクリティカルでビジネスクリティカルなアプリケーションを実行する方法について説明しました。</p>


  <p>お客様全体で、ミッション システムとビジネス クリティカルなシステムを結び付け合う共通のスレッドは、コア ビジネス プロセスをサポートしているという点です。 たとえば、エンタープライズ リソース計画 (ERP)、サプライ チェーン管理 (SCM)、顧客関係管理 (CRM) アプリケーションだけでなく、分析、eコマース システム、財務管理、調達、支払いなどの記録システムなどです。 デジタル化されたカスタマー エクスペリエンスをサポートするシステムは、ビジネスの成功にもこれまで以上に重要です。</p>


  <ul>
      <li>JetBlue のような組織は、eコマース サイトのような従来のビジネスクリティカルなアプリケーションと、全体的なカスタマー エクスペリエンスを向上させる予測モデルを Azure に依存しています。</li>
      <li><a href="https://customers.microsoft.com/en-us/story/allscripts-partner-professional-services-azure" target="_blank">Allscripts のような企業は、</a>Azure 上のオープン ソース ソフトウェアを使用して、医療関連の重要なアプリケーションを提供します。</li>
      <li><a href="https://customers.microsoft.com/en-us/story/757588-manulife-insurance-azure-microsoft-365-teams" target="_blank">Manulife</a> は、新しいビジネス モデルのサポートを加速しながら、機敏性、スケーラビリティ、リスク管理、コスト効率を向上させるために、ビジネスクリティカルなアプリケーションを移行して最新化することを Azure に選択しました。</li>
      <li><a href="https://customers.microsoft.com/en-us/story/792300-walgreens-boots-alliance-azure-sap-migration-technical-retailer" target="_blank">Walgreens Boots Alliance</a> は Azure で SAP HANA を実行し、12 TB のメモリと 28 TB のストレージを備える仮想マシン (VM) に依存して、100 TB を超えるスケールアウト SAP ランドスケープを実行します。</li>
  </ul>


  <p>Azure でビジネスを実行すると、将来の準備が整い、ビジネスの回復性を高めることができます(特に不確実な状況の間)。 たとえば、2020 年 2 月に 米国 で COVID-19 のケースが増加し始めた場合、Adaptive Adaptiveies は、診断、治療、および治療を開発している世界中の研究者がこの情報を公開するために、COVID-19 に対するその反応をマップするために、その適応性の高い医療プラットフォームを作り出しました。</p>


  <p>数週間以内に、適応型は 5 億シーケンスを処理し、29 のコンピューティング年を使用して感染の予防署名を識別しました。 その結果、アダプティブは、T セルシグナルが、感染中および感染後の特定の時点で COVID-19 ウイルスへの露出を評価するための最適なマーカーになる可能性を示しました。そのため、会社は世界で初めて、任意の病気に対する T セルベースの診断に関して、世界の T セルベースの診断から緊急&rsquo;使用承認の実施を開始できます。</p>


  <blockquote>

  <p style="margin-left: 40px;">Azure のクラウド コンピューティング リソースと機械学習の機能は、私たちの治療用プラットフォームを強化しています。このプラットフォームを使用すると、私たちは、<em>COVID-19 や Lyme 病&rdquo;などの病気に対して、私たちのがんの治療を迅速にマップし、次世代の診断を支援することができます。&rsquo;&ldquo; </em>-Mark Adams、アダプティブ アダプティブ アダプティブの最高技術責任者</p>

  </blockquote>


  <h2>課題と機会</h2>


  <p>2020 年の初めに、Forrester の副社長兼プリンシパル アナリストである Dave Bartoletti、JetBlue の IT 部門、テクノロジと統合担当副社長の Ramki Ramaswamy 氏、Trimble Inc. のソフトウェア アーキテクチャ戦略の上級副社長である Prakash Iyer &amp; がクラウド移行ウェビナー シリーズに参加しました。<a href="https://info.microsoft.com/ww-ondemand-azure-webinar-series-five-key-factors-in-migrating-mission-critical-workloads-to-the-cloud.html?lcid=en-us" target="_blank"></a> 現在のミッション クリティカルなインフラストラクチャを管理する際に IT 組織が直面する主な課題について説明しました。 IT プロフェッショナルが環境を更新する必要があるときに直面するセキュリティの問題、高コスト、困難は、最も重要です。</p>


  <p>&nbsp;<a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/eb264860-7a06-46ea-ab92-5c7c0443c434.png"><img alt="MC1" border="0" height="329" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/70caf24a-0e34-48b0-9033-cf219905d9e9.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="MC1" width="727"></a><br>

  &rsquo;逆に、ミッション クリティカルなワークロードをクラウドに移行することで企業が実現した主な利点を見た場合、クラウドへの移行がこれらの課題の多くへの対処に役立ったのは明らかです。 彼らが挙げた主な利点は次の例です。</p>


  <ul>
      <li>セキュリティとコンプライアンスの強化。</li>
      <li>ミッション クリティカルなシステムのパフォーマンスと待機時間の向上。</li>
      <li>機敏性の向上 (既存のシステムの最新化、新機能の開発など)</li>
      <li>全体的な IT コストを削減します。</li>
      <li>インフラストラクチャの実装時間が短縮されます。</li>
  </ul>


  <p>そのため&rsquo;、Microsoft Ignite では、これらすべてのディメンションでさらに多くのサービスを提供し続ける理由として、利害関係者のニーズをよりよく満たすために、いくつかの新しいサービスとしてのインフラストラクチャ (IaaS)&rsquo; 機能のプレビューを発表しました。</p>


  <h2>Azure 上のビジネスに不可欠なアプリケーションの可用性、セキュリティ、スケーラビリティ、パフォーマンスを向上させる新しいコア IaaS 機能</h2>


  <p>最近、ビジネス クリティカルなワークロードの要件を満たすいくつかの新機能 <a href="https://aka.ms/BusinessCritical" target="_blank">を発表しました</a>。</p>


  <h3>Azure 専用ホスト: より詳細な制御、柔軟性、および選択</h3>


  <p>Azure のお客様は、専用ホストと分離された仮想<a href="https://azure.microsoft.com/en-us/services/virtual-machines/dedicated-host/" target="_blank"></a>マシン (VM) に対してプラットフォームのメンテナンス操作をスケジュールし、Azure Virtual Machine Scale Sets でゲスト OS イメージの更新をいつ展開できるのか制御できます。Azure Dedicated Hosts で <a href="https://azure.microsoft.com/en-us/services/virtual-machine-scale-sets/" target="_blank">Virtual Machine Scale Sets</a> がサポートされ、お客様は VM をデプロイするホスト グループをプラットフォームで選択することで、専用ホストでの Azure Virtual Machines のデプロイを簡略化できます。 これらすべての新機能は <a href="https://forms.microsoft.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAEUB0xASRFUMVNXMlZVSFcyRE00QzBMRURWODVEVVVBWS4u" target="_blank">、現在プレビューの中です</a>。 最後に、ほぼ近い将来、お客様は Fsv2 シリーズの VM を使用して、Intel Cascade Lake プロセッサを搭載した Azure 専用ホストでコンピューティング集中型のワークロードを実行して、パフォーマンスを向上させることができます。</p>


  <h3>パフォーマンスの高い汎用仮想マシンとメモリ最適化仮想マシン</h3>


  <p>また、Microsoft は最近、Intel Cascade Lake プロセッサを搭載した新しい <a href="https://azure.microsoft.com/en-us/services/virtual-machines/" target="_blank">Azure Virtual Machines</a> を汎用およびメモリ集中型のワークロードに利用するようにしました。 その結果、Azure にはローカルの一時ディスクが含まれるので、エントリの価格を下げる新しいカテゴリの VM が提供されます。 これらの VM シリーズは、前の世代と比較して最大 20% の CPU パフォーマンスを提供します。</p>


  <h3>新しいディスク Storageとネットワーク機能により、セキュリティ、パフォーマンス、可用性が強化されます</h3>


  <p>一般提供開始された新しい <a href="https://azure.microsoft.com/en-us/services/storage/disks/" target="_blank">Azure Disk Storage</a> の更新プログラムには、セキュリティを強化するためにプライベート仮想ネットワークを使用したデータの安全なインポートとエクスポートを可能にする Azure Private Link 統合と、Azure Ultra Disks 上の 512E のサポートが含まれており、古いバージョンの Oracle&reg; DB などのレガシ ワークロードをクラウドに移行できます。 詳細については<a href="https://aka.ms/AzureDiskBlog-TechCommunity" target="_blank">、Azure Communityの投稿</a>を参照してください。</p>


  <p>最後に、お客様は、リージョン間負荷分散 (プレビュー)&rsquo; を使用して、グローバルに分散されたワークロードで Azure Load Balancer を使用して、アプリケーションのパフォーマンスと可用性を向上させることができます。</p>


  <h2>新しい Linux ツールとコスト効率の高いライセンス モデルは、Azure での Linux インフラストラクチャとワークロードの管理に役立ちます</h2>


  <p>Azure ハイブリッド特典 Linux が追加され、Azure Image Builder と共に、Azure 上の Linux インフラストラクチャとワークロードを移行、運用、管理するための新しいツールとコスト効率の高いライセンス モデルが提供されます。</p>


  <p>Azure ハイブリッド特典、よりシンプルでコスト効率の高い Linux サブスクリプションの移植 <a href="https://aka.ms/ahb-linux-form" target="_blank">性が可能になります</a>。 この新機能はプレビューで利用できます。お客様は、既存の Red Hat Enterprise Linux および SUSE Linux Enterprise Server on Azure を実行している既存の Pay-as-You-Go インスタンスを、既存の Red Hat Enterprise Linux および SUSE Linux Enterprise Server サブスクリプションを使用して、独自のサブスクリプション (BYOS) 課金に変換できます。 お客様は、既存のサブスクリプションを Azure に持ち込み、特別な価格割引を維持し、クラウドに移行したオンプレミス サブスクリプションの二重請求を回避することで、Red Hat と SUSE への既存の投資を活用できます。</p>


  <p>2020 年第 4 四半期に一般提供される Azure Image Builder は、Linux および Windows イメージの作成、更新、修正プログラムの適用、管理、操作を効率化する無料のイメージ構築サービスです。 Azure Image Builder使用すると、サブスクリプションにリソースがデプロイされます。イメージ構築パイプラインの実行中に消費される VM と関連するストレージおよびネットワーク リソースに対してだけ料金が支払います。</p>


  <h2>次の手順と追加のリソース</h2>


  <p>企業が技術の強度を高めるに当たって、ビジネスクリティカルなアプリケーションの範囲は拡大し続ける。 エコシステムベースのアプローチにより、お客様とパートナーが同様に、および を使用して幅広いソリューションを構築できます。 私たちは、私たちの前にある可能性と、一緒に達成できるものに感じ取っています。</p>


  <p>オファリングの詳細については、ビジネス クリティカルな<a href="https://aka.ms/BusinessCritical" target="_blank"></a>アプリケーション サイトにアクセスして、参照アーキテクチャ、ISV ソリューション、製品機能にアクセスしてください。 また、トレーニング ビデオを見て、Azure で最新の機能を <a href="https://aka.ms/AzureComputeChannel" target="_blank">体験できます</a>。</p>


  <ul>
      <li>ホスト更新プログラムの <a href="https://aka.ms/updateschedules/" target="_blank">スケジュールされたメンテナンスの詳細を確認してください</a>。</li>
      <li>スケール セットを使用した <a href="https://aka.ms/vmsssupdatecontrol/" target="_blank">スケジュールされたメンテナンスの詳細を参照してください</a>。</li>
      <li>最新のディスクCommunity更新プログラムに関する Azure Storage<a href="https://aka.ms/AzureDiskBlog-TechCommunity" target="_blank">をお読みください</a>。</li>
      <li>メンテナンス コントロール機能 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/maintenance-control" target="_blank">のドキュメントを参照してください</a>。</li>
      <li><a href="https://forms.microsoft.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAEUB0xASRFUMVNXMlZVSFcyRE00QzBMRURWODVEVVVBWS4u" target="_blank">Azure Virtual Machine Scale Sets</a> on Dedicated Hosts プレビューへのアクセスを要求します。</li>
      <li>Linux サブスクリプションの移植性Azure ハイブリッド特典 (プレビュー) を使用 <a href="https://aka.ms/ahb-linux-form" target="_blank">して、オプションを</a> 確認します。</li>
  </ul>


  <hr>

  <p><i>Azure。目的を持って発明する。</i></p>


  <ul>

  </ul>
