### YamlMime:Yaml
ms.openlocfilehash: 43c34a4d96c55aef3b133db4c52018d2de0bf444
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910338"
Slug: saas-patterns-accelerate-saas-application-development-on-sql-database
Title: SaaS パターンを使用して、SQL Database での SaaS アプリの開発を促進する
Summary: Saas アプリケーションのサンプルを実装する管理スクリプトとチュートリアル、saas に重点を置いた一連の設計と管理のパターンを実装した管理スクリプトとチュートリアルの可用性について、SQL Database での SaaS アプリケーション開発を促進するために使用できます。
Content: >-
  <p>&rsquo;喜びの saas アプリケーション SQL Database 開発を加速させることができる saas に重点を置いた設計と管理のパターンを示す一連の saas アプリケーションと、一連の管理スクリプトとチュートリアルの可用性を発表します。 これらのパターンによって、SQL Database の利点が拡張され、さまざまなデータを集中的に使用するマルチテナント SaaS アプリケーション用に、最も効果的で管理しやすいデータプラットフォームが実現します。</p>


  <h2>テナントごとのデータベースモデルはテナントの分離を提供します</h2>


  <p>パターンについては、まず、使用する <a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-design-patterns-multi-tenancy-saas-applications" target="_blank">データモデル</a> について検討します。 マルチテナントアプリケーションは、従来、マルチテナントデータベースを使用して実装されています。 マルチテナントデータベースは、特にテナントごとに格納されるデータの量が少ない場合に、一部のアプリケーションで有効ですが、多くの SaaS アプリケーションはテナントごとにデータベースを使用することに固有の分離を利用できます。 SQL Database の完全に管理された性質とエラスティックプールの使用により、多数のデータベースを実用的に管理できるようになりました。 多くの isv は、SQL Database で SaaS アプリケーションを実行しています。エラスティックプールには、数十のテナントデータベースが含まれています。 大手オーストラリア会計 ISV である MYOB は、汗を壊すことなく、13万のテナントデータベースを管理しています。 テナントごとのデータベースモデルを使用すると、これらのお客様は、マルチテナントデータベースでは実現できないレベルのテナント分離を実現でき、データセキュリティ、プライバシー、パフォーマンス管理、拡張性などが向上します。</p>


  <h2>カスタマーエクスペリエンスからのラーニング</h2>


  <p>これらの多くのお客様と緊密に連携し、経験から学んで、テナントごとのデータベースアプローチの導入を簡素化し、大規模に使用するビジネスドメインに適用される設計と管理のパターンを収集しました。 これらのパターンに基づいて、サンプルの SaaS アプリケーションと一連の管理スクリプトを使いやすくなりました。このチュートリアルでは、すべてのコードを<a href="https://github.com/Microsoft/WingtipSaaS" target="_blank">GitHub</a>と<a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-wtp-overview" target="_blank">チュートリアル</a>をオンラインで利用できます。</p>


  <p>サンプルアプリケーションを5分未満でインストールし、アプリを使用してパターンを調査し、Azure portal、SQL Server Management Studio、および Visual Studio を使用してその &rsquo; ビルドを実行することができます。 アプリと管理スクリプトを学んで、チュートリアルを使って作業することで、独自の SaaS アプリプロジェクトを始めることができます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/45b2bf51-dc88-4b06-8907-4084c5e16ba7.png"><img alt="Screenshot_5" border="0" height="204" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bef70b03-510a-4293-9906-dc8d93792e6e.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="Screenshot_5" width="549"></a></p>


  <p>このサンプルアプリは、SaaS アプリの簡単なイベント一覧とチケット発行です。各会場には、イベント、チケット価格、顧客、チケット販売を含む独自のデータベースがあり、そのすべてが他の会場 &rsquo; データから安全に分離されています。 このアプリでは、データ層に正規の SaaS アプリアーキテクチャを使用します。 各テナントは、ルックアップと接続に使用されるカタログデータベースを使用して、データベースにマップされます。 その他のシナリオを可能にするために、他のデータベースがインストールされています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0d7adfc8-ceb8-4ae3-b771-59e6438f84ee.png"><img alt="Apps" border="0" height="289" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8a623335-44d8-4b2b-9d6f-aa774679dcf2.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="選ぶ" width="517"></a></p>


  <h2>探索済みの SaaS シナリオ</h2>


  <p>アプリと管理スクリプトは、SaaS に関連する多くの一般的なシナリオに対応しています。次に例を示します。</p>


  <ul>
   <li>テナント登録 (データベースのプロビジョニングと初期化、カタログ登録など)</li>
   <li>アプリから正しいテナントデータベースへのルーティングと接続</li>
   <li>クロスプールの監視やアラートなど、データベースパフォーマンスの監視、アラート、および管理</li>
   <li>スキーマの変更の配置、すべてのテナントデータベースへの参照データを含むスキーマ管理</li>
   <li>すべてのテナントデータベースにわたって分散クエリを実行し、アドホックなリアルタイムクエリと分析を可能にする</li>
   <li>分析データベースまたはデータウェアハウスにテナントデータを抽出する</li>
   <li>特定の時点へのシングルテナントデータベースの復元</li>
  </ul>


  <p>ロードジェネレーターは、予測不可能なテナントアクティビティをシミュレートします。これにより、毎日または毎週のワークロードパターンを処理したり、負荷を分散したり、個々のテナントワークロードで大規模なバリエーションを管理したりできるように、リソース管理シナリオを調べることができます。 チケットジェネレーターを使用すると、大量のデータを含む分析シナリオを調べることができます。</p>


  <p>アプリでは、自動インテリジェントインデックスチューニングなど、テナントごとのデータベースのコンテキストに特に関連する他の SQL Database 機能を利用して、テナントの実際のワークロードプロファイルに &rsquo; 基づいてテナントデータベースのパフォーマンスを最適化することもできます。</p>


  <h2>他の Azure サービスと統合して、エンドツーエンドの SaaS シナリオに対応</h2>


  <p>他のいくつかの Azure サービスは、アプリの一部としても導入されています。これには、アプリレイヤーでの App Services と Traffic Manager、大規模な監視とアラートのための Log Analytics (OMS)、クロステナント分析のための SQL Data Warehouse、デプロイ用の Azure リソース管理 (ARM) テンプレートが含まれます。</p>


  <p>アプリは時間の経過と共に拡張され、追加の管理パターンから、Power BI、Azure Machine Learning、Azure Search、Active Directory などの他の Azure サービスとの緊密な統合が可能になり、完全な E2E SaaS シナリオを構築できます。 また、そのためには、マルチテナントデータベースモデルで同じシナリオを試してみる必要があります。</p>


  <p>これらの SaaS パターンでは、SQL Database サービスに対する将来の機能強化の計画についても知られています。</p>


  <h2>はじめに</h2>


  <p>まず、GitHub からワンクリックで<a href="https://github.com/Microsoft/WingtipSaaS" target="_blank">アプリをインストール</a>します。ここで、コードと管理スクリプトをダウンロードできます。 &nbsp;<a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-wtp-overview" target="_blank">パターンの詳細を確認し、チュートリアルを参照し</a>てください。 ここで <a>saasfeedback@microsoft.com</a> は、サンプルとパターン、およびその後に追加されるもの &rsquo; についてご意見をお聞かせください。</p>
