### YamlMime:Yaml
ms.openlocfilehash: 5726e13a00a80cdc8da579b55a581c849e4e89ed
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910328"
Slug: sampling-in-application-insights
Title: 'Application インサイト でのサンプリング: テレメトリの量を制御下に置く方法'
Summary: '多くのユーザーを含む最新のアプリケーションでは、多くのテレメトリ データを生成できます。 アプリケーション テレメトリのすべての部分を絶対に収集する必要があるという非常に一般的な (そしてほとんど常に間違った) 認識ですが、そうすると高い価格が発生する可能性があります。 '
Content: >-
  <p>多くのユーザーを含む最新のアプリケーションでは、多くのテレメトリ データを生成できます。 アプリケーション テレメトリのすべての部分を絶対に収集する必要があるという非常に一般的な (そしてほとんど常に間違った) 認識ですが、そうすると高い価格が発生する可能性があります。 Application インサイト により多くのデータを格納するコストの増加に対処できるだけでなく、アプリケーションのネットワーク消費が増加し、監視によるパフォーマンスへの影響が高くなる可能性があります。</p>


  <p>さらに、テレメトリの量が調整の制限を超<a href="https://go.microsoft.com/fwlink/?LinkID=691451"></a>えた場合、Application インサイトはデータの削除を開始します。 これが発生すると、アプリケーション テレメトリは完全に制御しきれなきます。 探しているテレメトリ項目が調整された可能性&#39;、メトリックに正確な値が反映されなくなりました。診断エクスペリエンスが無効になります。収集されたデータの量を制御し、テレメトリの生成が多すぎる問題から保護するために、<a href="https://go.microsoft.com/fwlink/?LinkID=691452">Application インサイト SDK 2 ベータ</a>版の最近のリリースでは、サンプリングの概念が導入されています。<em></em></p>


  <p>アプリケーションの観点からは、サンプリングは SDK の機能であり、ポータルでアプリケーション データの統計的に正しい分析を維持しながら、テレメトリの削減セットを収集して格納できます。 現在、サンプリングは、クライアント側とサーバー側の両方で ASP.NET Web アプリケーションと共に使用するか、他の (.NET 以外の) サーバー側プラットフォームで記述された Web アプリケーションのクライアント側からのみ使用できます。</p>


  <p>サンプリングを&nbsp;使用してアプリケーション テレメトリ&nbsp;&nbsp;の量を維持する方法と、Web アプリケーションでサンプリングを構成する方法の詳細については、こちらを参照<a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-sampling/">してください</a>。</p>
