### YamlMime:Yaml
ms.openlocfilehash: 4a2367f8cb0e5b24e0a91424eb02efafd35f5986
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892759"
Slug: sap-and-microsoft-bring-iot-data-to-the-core-of-the-business-applications
Title: SAP と Microsoft は、IoT データをビジネスアプリケーションの中核にします
Summary: 'Microsoft では、IoT クラウドエコシステムのリーダーとして、インテリジェントなエッジとインテリジェントクラウドを通じて、さまざまな業界内のビジネスアプリケーションを完全に積み重ねることができます。 IoT 業界の継続的な成長は、すべての組織の革新的な力になります。 '
Content: >-
  <p>Microsoft では、IoT クラウドエコシステムのリーダーとして、インテリジェントなエッジとインテリジェントクラウドを通じて、さまざまな業界内のビジネスアプリケーションを完全に積み重ねることができます。 IoT 業界の継続的な成長は、すべての組織の革新的な力になります。 Microsoft と SAP は、企業の SAP ソリューションのデプロイを可能にするために2年間以上の協力をしてきました。また、パートナーシップは、 <a href="https://www.iiconsortium.org/index.htm" target="_blank">工業のインターネットコンソーシアム</a>、 <a href="https://opcfoundation.org/" target="_blank">OPC Foundation</a>、および <a href="https://www.plattform-i40.de/PI40/Navigation/EN/Home/home.html" target="_blank">プラットフォーム Industrie 4.0</a>で拡張されています。</p>


  <p>2月の Mobile World 議会では、SAP と Microsoft は、モノのインターネット (IoT) の領域における物理的な資産への拡張コラボレーションを <a href="https://azure.microsoft.com/blog/microsoft-and-sap-extend-partnership-to-internet-of-things/" target="_blank">発表</a> しました。 現在、 <a href="https://azure.microsoft.com/services/iot-hub/" target="_blank">Azure IoT hub</a>との<a href="https://www.sap.com/products/leonardo/iot.html" target="_blank">SAP レオナルド IoT</a>統合の一般提供を発表しています。</p>


  <p>sap レオナルド iot は Azure IoT サービスと統合されており、お客様は、sap business data を使用して IoT データを contextualize、強化し、新しいビジネスの結果を促進することができます。 Azure IoT Hub と Azure IoT edge を活用することで、大規模な安全な接続、強力なデバイス管理機能、業界をリードするエッジコンピューティングサポートを利用できます。 ビジネスデータをインテリジェントに結合して、SAP ビジネスアプリケーションによって使用される工業の IoT 機能とサービスを提供することにより、お客様は、物理的な資産からビジネスプロセスまで、完全なデジタルフィードバックループを提供できるようになりました。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3ca26537-680f-495e-97eb-9cde7ac6f089.png"><img alt="Microsoft intelligent edge diagram" border="0" height="1169" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b527a629-ce76-4b0f-968c-e94dea9bbbf7.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Microsoft インテリジェントエッジの図" width="2511"></a></p>


  <p>SAP および Microsoft &rsquo; が共通する目標は、物理的な資産からビジネスプロセスにデータの360ビューを提供することです。これにより、顧客はデータサイロを削除し、インテリジェントなクラウドとインテリジェントなエッジで完全なデジタルフィードバックループを実現できます。 SAP の重要なビジネス機能を Microsoft Azure IoT Edge で実行することにより、お客様は、最も重要な資産に最も近い S4/hana および C4/hana ビジネスプロセスを拡張して、ビジネスの要求とガバナンスの機能をエッジで実現することができます。</p>


  <p><a href="https://azure.microsoft.com/resources/videos/sap-bef-edge-demo/" target="_blank">Azure IoT と SAP レオナルド IoT の相互運用性</a>に関する詳細をご覧ください。</p>
