### YamlMime:Yaml
ms.openlocfilehash: 39d4494c68eee085839ee25dab2c1a1f7546a22c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892743"
Slug: sap-on-azure-architecture-designing-for-security
Title: SAP on Azureアーキテクチャ - セキュリティのための設計
Summary: 優SAP on Azureアーキテクチャは、セキュリティ、パフォーマンスとスケーラビリティ、可用性と回復性、効率性と運用の重要な柱を基に構築されています。
Content: >-
  <p><em>このブログ投稿は、Technical Specialist, SAP on Azure によって投稿されました</em>。</p>


  <p>これは、4 部構成のブログ シリーズで初めて、SAP on Azure アーキテクチャを設計し、セキュリティのための設計に重点を置いています。</p>


  <p>優SAP on Azureアーキテクチャは、セキュリティ、パフォーマンスとスケーラビリティ、可用性と回復性、効率性と運用の重要な柱を基に構築されています。</p>


  <h2>Azure Security への Microsoft の投資</h2>


  <p>Microsoft は、セキュリティの研究と開発に年間 10 億ドルを投資し、会社全体で 3,500 人のセキュリティプロフェッショナルを雇用しています。 高度な AI は、Microsoft クラウド プラットフォームから 6.5 兆個のグローバルシグナルを分析し、脅威を検出して対応するために利用されます。 Enterpriseレベルのセキュリティとプライバシーは、Red Team の演習など、現実世界のテストによる永続的で厳格な検証を含む、Azure <a href="https://gallery.technet.microsoft.com/Cloud-Red-Teaming-b837392e" target="_blank">プラットフォームに組み込されています</a>。 これらのテストにより、Microsoft は侵害の検出と対応をテストできるだけでなく、実際の攻撃の対応性と影響を正確に測定できます。これは、Azure にクラス最高のセキュリティを提供する多くの運用プロセスの 1 つです。</p>


  <p>Azure は信頼のプラットフォームであり、国、地域、および健康、財務、政府、製造などの特定の業界にまたがる <a href="https://www.microsoft.com/en-us/trustcenter/compliance/complianceofferings" target="_blank">90</a> のコンプライアンス認定を持っています。 さらに、 <a href="https://azure.microsoft.com/en-au/services/blueprints/" target="_blank">Azure のセキュリティとコンプライアンスのブループリント</a> を使用して、準拠環境を簡単に作成、デプロイ、更新できます。</p>


  <h2>共有 &ndash; 責任のセキュリティ</h2>


  <p>お&rsquo;客様と Microsoft の間の共同責任モデルを理解することが重要です。 責任の分担は、使用されるクラウド モデル (SaaS、PaaS、または IaaS) によって異なります。 お客様は、選択したクラウドデプロイに関係なく、常にデータ、エンドポイント、アカウント/アクセス管理に責任を負います。</p>


  <p>SAP on Azureは IaaS クラウド モデルを使用して提供されます。つまり、セキュリティ保護は、物理データセンター、物理ネットワーク、物理ホストで Microsoft によってサービスに組み込まれます。 ただし、Azure ハイパーバイザーを超えるすべての領域 (オペレーティング システムやアプリケーションなど) については、お客様がエンタープライズ セキュリティ制御を実装する必要があります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/60d7bef4-2237-4103-a17c-28aa4a6fa1e3.jpg"><img alt="A diagram looking at the responsibilities of the customer versus the service they are using." border="0" height="480" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7ae64021-b5bc-44f8-b4b5-eb615302eb4c.jpg" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="顧客と使用しているサービスの責任を示す図。" width="900"></a></p>


  <h2>アプリケーションをデプロイする際の主なセキュリティSAP on Azure</h2>


  <h3>リソース ベースのアクセス制御 &amp; リソース ロック</h3>


  <p><a href="https://docs.microsoft.com/en-us/azure/role-based-access-control/overview" target="_blank">ロールベースのアクセス制御 (RBAC) は</a> 、Azure リソースの管理にきめ細かいアクセスを提供する承認システムです。 RBAC を使用して、IT 運用内のさまざまなチームに対する Azure リソースへのアクセスを制限し、アクセス許可を制御できます。</p>


  <p>たとえば、SAP ベースのチーム メンバーには、Azure 仮想ネットワーク (VNet) に仮想マシン (VM) をデプロイするアクセス許可を付与できます。 ただし、SAP ベース のチームは、VNet の作成または構成を制限できます。 逆に、ネットワーク チームのメンバーは VNet を作成して構成することができますが、SAP アプリケーションが実行されている VNet に VM をデプロイまたは構成することは禁止されています。</p>


  <p>プロジェクトのライフサイクルの早い段階で RBAC 設計を検証してテストSAP on Azure勧めします。</p>


  <p>もう 1 つの重要な考慮事項は <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-lock-resources" target="_blank">、VM</a> やディスクなどの Azure リソースの誤った削除や変更を防ぐために使用できる Azure リソースロックです。&nbsp; SAP プロジェクトの最初に、必要な Azure リソースを作成してください。 すべてのアドイン、移動、変更が完了し、SAP on Azureデプロイが動作すると、すべてのリソースをロックできます。 次に、スーパー管理者だけがリソースのロックを解除し、リソース (VM など) の変更を許可できます。</p>


  <h3>セキュリティで保護された認証</h3>


  <p>シングル サインオン (SSO) は、SAP と Microsoft 製品を統合するための基盤を提供します。Microsoft Active Directory の Kerberos トークンは、何年もの間、サード パーティのセキュリティ製品と組み合わせた場合に SAP GUI と Web ブラウザー ベースのアプリケーションの両方に対してこの機能を有効にしてきました。</p>


  <p>ユーザーがワークステーションにログオンし、Microsoft Active Directory に対して正常に認証されると、Kerberos トークンが発行されます。 その後、Kerberos トークンをサードパーティのセキュリティ製品で使用して、ユーザーが再認証することなく SAP アプリケーションへの認証を処理できます。 さらに、ユーザーフロントエンドから SAP アプリケーションへの転送中のデータは、セキュリティ製品を DIAG (SAP GUI)、RFC、HTTPS 用 SPNEGO 用のセキュリティで保護されたネットワーク通信 (SNC) と統合することで暗号化できます。</p>


  <p>Azure Active Directory (Azure AD) と SAML 2.0 を使用して、SAP NetWeaver、SAP HANA、SAP Cloud Platform などのさまざまな SAP アプリケーションとプラットフォームに SSO を提供できます。</p>


  <p>この<a href="https://www.youtube.com/watch?v=AGCZA8CCIYo" target="_blank">ビデオ</a>では、AZURE AD と <a href="https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sap-netweaver-tutorial#configure-and-test-azure-ad-single-sign-on-for-sap-netweaver" target="_blank">SAP NetWeaver の間の SSO のエンド Azure ADを示します</a></p>


  <h3>アプリケーションとデータをネットワークの脆弱性から保護する</h3>


  <p>ネットワーク セキュリティ グループ (NSG) には、Azure VNet 内のリソースへのネットワーク トラフィックを許可または拒否するセキュリティ規則の一覧が含まれている。 NSG は、サブネットまたは VM に接続されている個々のネットワーク インターフェイスに関連付けできます。 セキュリティ規則は、送信元/送信先、ポート、プロトコルに基づいて構成できます。<br>

  NSG は&rsquo;、SAP システムのネットワーク トラフィックに影響します。 次の図では、3 つのサブネットが実装され、それぞれに NSG (FE (フロントエンド)、アプリ、DB が割り当てられます。</p>


  <ol>
      <li>パブリック インターネット ユーザーは、ポート 443 で SAP Web-Dispatcherにアクセスできます</li>
      <li>SAP Web-Dispatcher、ポート 443 を使用して SAP アプリケーション サーバーに到達できます</li>
      <li>アプリ サブネットは、10.0.0.0/24 からポート 443 のトラフィックを受け入れる</li>
      <li>SAP アプリケーション サーバーは、ポート 30015 のトラフィックを SAP DB サーバーに送信します</li>
      <li>DB サブネットは、10.0.1.0/24 のポート 30015 でトラフィックを受け入れる。</li>
      <li>パブリック インターネット アクセスは、アプリ サブネットと DB サブネットの両方でブロックされます。</li>
  </ol>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/057224a5-7281-4cb7-9794-2488ec92a815.png"><img alt="A diagram showing three subnets with NSGs influencing network traffic." height="531" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/95f118f5-8c72-42da-9ca9-4f5fb95a66cd.png" style="border-width: 0px; border-style: solid; border-image: none; width: 1024px; height: 604px; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="740 ブログ" width="900"></a></p>


  <p><a href="https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter" target="_blank">Azure 仮想 Ddatacenter アーキテクチャを使用した</a> SAP デプロイは、ハブ アンド スポーク モデルを使用して実装されます。 ハブ VNet は、sap アプリケーションが存在するスポーク <a href="https://docs.microsoft.com/en-us/azure/firewall/overview" target="_blank">VNet</a> へのトラフィックのルーティングを検査および制御するために、Azure Firewall または他の種類のネットワーク仮想 <a href="https://azure.microsoft.com/en-us/solutions/network-appliances/" target="_blank">アプライアンス (</a> NVA) が実装されている接続の中心点です。</p>


  <p>SAP on Azure プロジェクト内では、検査デバイスと NSG セキュリティ規則が必要に応じて動作し、SAP リソースがネットワークの脆弱性に対して適切にシールドされるのを確認することが推奨されます。</p>


  <h3>暗号化方法によるデータの整合性の維持</h3>


  <p><a href="https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption" target="_blank">Azure Storageサービス暗号化は</a>、無効にできない Azure Storageアカウントで既定で有効になっています。 そのため、256 ビット AES を使用してデータが透過的に暗号化/暗号化解除される場合、Azure Storage の保存データは既定で保護されます。 暗号化/暗号化解除プロセスはパフォーマンスに影響をAzure Storage、コストはかからない。&nbsp;暗号化キーを管理する Microsoft のオプション、または暗号化キーを使用して独自のキー<a href="https://docs.microsoft.com/en-gb/azure/key-vault/key-vault-overview" target="_blank">を管理Azure Key Vault</a>。 Azure Key Vault、SAP システム内のインターフェイスと内部通信をセキュリティで保護するために使用される SSL/TLS 証明書を管理するために使用できます。</p>


  <p>Azure では、仮想マシン<a href="https://docs.microsoft.com/en-us/azure/security/fundamentals/azure-disk-encryption-vms-vmss" target="_blank"></a>のオペレーティング システムとデータ ディスクのボリューム暗号化を提供するために、Linux 用の Windows および DM-Crypt 用の BitLocker を使用した仮想マシン のディスク暗号化も提供されています。&nbsp;</p>


  <p>保存中の SAP データを暗号化するための推奨される方法は次のとおりです。</p>


  <ul>
      <li>SAP データベース サーバー - DBMS プロバイダーによって提供されるネイティブ暗号化テクノロジを利用して、データファイルとログ ファイルをセキュリティで保護し、バックアップも確実に暗号化します。</li>
      <li>Linux 仮想マシン ディスクを暗号化するには、「ディスク暗号化の概要」で説明されているさまざまな <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disk-encryption-overview" target="_blank">選択肢があります</a>。&nbsp;</li>
      <li>特定の Linux ディストリビューションAzure Disk Encryption/バージョン/イメージでサポートされている場合は、Linux VM のAzure Disk Encryption <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-overview" target="_blank">を確認してください</a>。</li>
  </ul>


  <h3>オペレーティング システムのセキュリティ強化</h3>


  <p>セキュリティは、お客様がオペレーティング システム、データベース、SAP アプリケーションレイヤーに適用する必要があるお客様と Microsoft の間で共同責任を負います。 たとえば、SAP データベースに対する攻撃につながる可能性がある脆弱性を排除するために、オペレーティング システムが強化されている必要があります。</p>


  <p>Windows、SUSE Linux、RedHat Linux などが Azure で SAP アプリケーションを実行する場合にサポートされ、これらのオペレーティング システムのさまざまなイメージが Azure Marketplace 内で使用できます。 これらのイメージをさらに強化して、企業のセキュリティ ポリシーに準拠し、インターネット セキュリティセンター <a href="https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-overview" target="_blank">(CIS) - Microsoft Azure基盤</a>ベンチマークのガイダンスに従います。</p>


  <p>企業では、一般に、オペレーティング システムを含む IT ソフトウェアの更新と修正プログラムの適用のための運用プロセスが導入されています。 オペレーティング システムの脆弱性が公開された後は、セキュリティ アドバイザリで公開され、通常は迅速に修復されます。 オペレーティング システム ベンダーは、セキュリティ更新プログラムと修正プログラムを定期的に提供しています。 azure の Update Management <a href="https://docs.microsoft.com/en-us/azure/automation/automation-update-management" target="_blank">ソリューションAzure Automation</a>使用して、Azure 内の Windows および Linux VM のオペレーティング システムの更新プログラムを管理できます。 ベスト プラクティスアプローチは、オペレーティング システムのセキュリティ更新プログラムを定期的に選択的にインストールし、メンテナンス期間中の新機能などの他の更新プログラムをインストールすることです。</p>


  <h2>詳細情報</h2>


  <p>このブログでは、セキュリティ トピックのデプロイに関連するセキュリティ トピックの選択に触SAP on Azure。 セキュリティプラクティスを確実に組み込むことで、Azure へのセキュリティで保護された SAP デプロイが可能になります。</p>


  <p><a href="https://azure.microsoft.com/en-us/services/security-center/" target="_blank">Azure Security Center</a> は、Azure デプロイをセキュリティで保護および監視するためのベスト プラクティスについて学習する場所です。 また、Azure Sentinel と共に <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-intro" target="_blank">Azure Security Center</a> の技術ドキュメントを読み<a href="https://azure.microsoft.com/en-us/services/azure-sentinel/" target="_blank"></a>、脆弱性を検出し、悪用が発生した場合にアラートを生成し、修復に関するガイダンスを提供<a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-recommendations" target="_blank">してください。</a></p>


  <p>このシリーズのブログ番号 2 では、パフォーマンスとスケーラビリティのための設計について説明します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4f60791e-7113-4e08-868f-1c4a3a734b2c.png"><img alt="An image of the Security Center Overview page." border="0" height="536" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7be3fbfc-f9ec-460a-818d-ce587feaba4e.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="[概要] ページSecurity Center画像。" width="1024"></a></p>
