### YamlMime:Yaml
ms.openlocfilehash: a21bcffa497e1c091c7b467882bef3f68f28175e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892707"
Slug: scale-your-critical-applications-cost-effectively-with-azure-disk-storage
Title: Azure Disk Storage を使用して、重要なアプリケーションをコスト効率Storage
Summary: 'ビジネス継続性の確保やキャッシュ フローの削減の管理など、今日の課題に対処するために、組織はクラウドへの移行を加速しています。 クラウドに移行する幅広いワークロードでは、コストを管理しながら、これらのワークロードの固有のスケール ニーズを満たすることが重要です。 '
Content: >-
  <p>ビジネス継続性の&rsquo;確保やキャッシュ フローの削減管理など、今日の課題に対処するために、組織はクラウドへの移行を加速しています。 クラウドに移行する幅広いワークロードでは、コストを管理しながら、これらのワークロードの固有のスケール ニーズを満たすることが重要です。 現在、<a href="https://azure.microsoft.com/en-us/services/storage/disks/" target="_blank">Azure Disk Storage</a>&mdash; で新しい機能を共有しています。これは、パフォーマンスをコスト効率の高い方法でスケーリングするのに役立ちます。ワークロードのニーズをオンデマンドで満たし、必要な分だけ支払う必要があります。</p>


  <h2>新しいディスク バースト エクスペリエンスを使用して、ディスクパフォーマンスをオンデマンドで向上プレミアムSSD</h2>


  <p>2020 年 4 月に、より小さい <a href="https://azure.microsoft.com/en-us/blog/general-availability-of-new-azure-disk-sizes-and-bursting/#:~:text=Azure%20Premium%20SSD%20Managed%20Disks%20%20%20Burst,%2032%20GiB%20%204%20more%20rows%20" target="_blank">Premium SSD ディスク サイズ (512 GiB</a> 以下) でのディスク バーストの一般提供を発表しました。 現在、ディスク バーストのサポート (プレビュー) を、新しいオンデマンド エクスペリエンスを使用して、より大きな Premium SSD ディスク サイズ (512 GiB を超える) に拡張しています。 クレジットを蓄積した場合にのみバーストできるクレジット ベースのシステムとは異なり、新しいオンデマンド バースト機能を使用すると、必要に応じて、プロビジョニングされた量の最大 6 回 (最大 30,000 IOPS と 1,000 MB のスループット) をバーストできます。 これにより、需要に合わせてパフォーマンスを柔軟にスケーリングし、コストを最適化できます。</p>


  <p>ディスク バーストは、予想外の需要の急増でもパフォーマンスの低下を許容できないミッション クリティカルなワークロードに最適です。 オンライン トランザクション処理 (OLTP) システムをホストしている場合は、需要の増加により、注文要求が急増する可能性があります。 ストレージ システムがバックエンド データベースへの負荷の増加に確実に対処して、顧客に一貫したエクスペリエンスを提供したいと思っています。</p>


  <p>この新しいオンデマンド バースト機能は、サポートされている SSD ディスク上で有効にすることでプレミアム利用できます。 バースト有効化料金が発生し、プロビジョニングされたターゲットに対する追加のトランザクションは個別に課金されます。 <a href="https://aka.ms/diskburstingP30" target="_blank">プレビュー スコープ</a> 、有効化手順、価格モデルの詳細を確認してください。</p>


  <p>既存のクレジット ベースのバーストを既に採用している場合は、最近、新しいディスク バースト メトリックが導入されました。 これらのメトリックを使用すると、蓄積されたバースト クレジットを可視化し、バーストする能力をより良く予測できます。 ベースラインおよびバースト パフォーマンスのターゲットと未使用のバースト クレジットを簡単に表示できます。 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-metrics" target="_blank">新しいディスク</a> メトリックを使用してディスク バーストを監視する方法の詳細を確認します。</p>


  <h2>Premium SSD のパフォーマンス レベルを使用して、持続的に高いパフォーマンスを実現する</h2>


  <p>季節的な販売促進やトレーニング環境の実行などの計画的なイベントの場合は、数時間または数日間の持続的な高いパフォーマンスを達成してから、通常のパフォーマンス レベルに戻る必要があります。 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-change-performance?toc=/azure/virtual-machines/linux/toc.json&amp;bc=/azure/virtual-machines/linux/breadcrumb/toc.json" target="_blank">Premium</a> SSD のパフォーマンス レベル (11 月に発表<a href="https://azure.microsoft.com/en-us/updates/performance-tiers-for-premium-ssds-is-now-generally-available/" target="_blank"></a>された一般提供) では、より高いパフォーマンス レベルを選択することで、ディスク サイズを増やさずにディスクのパフォーマンスを柔軟にスケーリングできます。 また、いつでもレベルを変更したり、ベースライン パフォーマンス レベルに戻したりして、より高いパフォーマンスとコスト削減を実現できます。</p>


  <p>ベースライン パフォーマンス レベルは、プロビジョニングされたディスク サイズに基づいて設定されます。 サイズを増やさずに高い需要を満たすためにアプリケーションで必要な場合は、より高いパフォーマンス レベルを設定できます。 たとえば、P10 ディスク (128 GiB) をプロビジョニングする場合、ベースライン パフォーマンス レベルは P10 (500 IOPS と 100 MB) に設定されます。 P50 (7500 IOPS と 250 MB) のパフォーマンスに合わせてレベルを更新し、より高いパフォーマンスが不要になった場合は P10 に戻することができます。 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-performance-tiers-portal?toc=/azure/virtual-machines/linux/toc.json&amp;bc=/azure/virtual-machines/linux/breadcrumb/toc.json" target="_blank">ディスク パフォーマンス レベル</a> を変更する方法の詳細については、次を参照してください。</p>


  <h2>ワークロードのパフォーマンスを動的にスケーリングするための最適なオプションの選択</h2>


  <p>パフォーマンス レベルとオンデマンド ディスク バーストでは、ディスクパフォーマンスをスケーリングするための 2 つのオプションが提供されます。 ワークロードに最適なオプションを評価する場合は、次の条件を考慮することをお勧めします。</p>


  <ul>
      <li><strong>計画済みと計画外のパフォーマンススケーリング:</strong>&nbsp;計画的なイベントでディスク パフォーマンスの継続的な向上 (たとえば、休日の季節) が必要な場合は、パフォーマンス レベルの方が適したオプションになります。 ディスク層をより高いパフォーマンス レベルに設定して、負荷の増加に対応し、いつでも元のレベルに戻します。 ただし、ワークロードのパフォーマンス パターンを計画できない場合や正確に予測できない場合は、プロビジョニングされたターゲットを超える高い許容量が提供されるディスク バーストの方が適しています。</li>
      <li><strong>期間：&nbsp;</strong>パフォーマンスの需要の期間によっては、2 つのオプションのコスト効率が異なる場合があります。 ジョブの実行時間が短かったり、IO スケジューリングでジッターが発生したりして需要が高いシナリオでは、バースト トランザクションに対する支払いのみを行うので、オンデマンド のディスク バーストの方がコスト効率が向上します。 ワークロードがプロビジョニングされたターゲットを超えない場合は、バースト有効化料金 (ディスク コストのごく一部) に対してだけ支払います。 対照的に、ワークロードのバーストが数日またはそれ以上続くことが予想される場合は、パフォーマンス レベルがより適切なオプションになります。 たとえば、税レポート ソリューション&nbsp;をホストする場合、レポート の季節の前月に大幅に増加する可能性があります。 この状況では、より高いパフォーマンス レベルを選択することでパフォーマンスをスケーリングする方がコスト効率が高くなります。</li>
  </ul>


  <p>ワークロードのニーズに最適なオプションを評価するには <a href="https://azure.microsoft.com/en-us/pricing/calculator/" target="_blank">、Azure</a> 料金計算ツールを参照することをお&rsquo;勧めします。</p>


  <h2>はじめに</h2>


  <p>新しいパフォーマンス スケーリング機能の使用を開始するには、オンデマンド のディスク バーストとパフォーマンス レベルに関<a href="https://aka.ms/diskburstingP30" target="_blank">するガイダンス</a><a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-change-performance" target="_blank">を参照してください</a>。 さらに、Azure Disk Storage&mdash; には、共有ディスク、<a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-enable-ultra-ssd?toc=%2Fazure%2Fvirtual-machines%2Flinux%2Ftoc.json&amp;bc=%2Fazure%2Fvirtual-machines%2Flinux%2Fbreadcrumb%2Ftoc.json&amp;tabs=azure-portal" target="_blank">Azure Ultra ディスク</a>での<a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-shared?toc=/azure/virtual-machines/linux/toc.json&amp;bc=/azure/virtual-machines/linux/breadcrumb/toc.json" target="_blank"></a>動的スケーリング、より小さな <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disk-bursting?toc=/azure/virtual-machines/linux/toc.json&amp;bc=/azure/virtual-machines/linux/breadcrumb/toc.json" target="_blank">Premium SSD</a>&mdash; ディスク サイズでのバーストなど、その他の独自の機能が用意されています。また、ビジネス クリティカルなアプリケーションをコスト効率の高い方法でスケーリングして実行することもできます。</p>


  <p>すべてのディスク操作<a href="https://aka.ms/azuredisksdocs" target="_blank">の詳細Storageについては、Azure Disk</a> Storageドキュメントを参照してください。 フィードバックを共有したり、AzureDisks@microsoft.comフィードバック フォーラムのコメントを残したりするには、 <a href="https://feedback.azure.com/forums/217298-storage" target="_blank">Azure Storageしてください</a>。</p>
