### YamlMime:Yaml
ms.openlocfilehash: 24a56234c9e7c6d51ec8dcaa85c81902de005e65
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892612"
Slug: security-center-playbooks-and-azure-functions-integration-with-firewalls
Title: Security Centerプレイブックと Azure Functionsファイアウォールとの統合
Summary: '1 秒ごとに、攻撃が検出された場合にカウントされます。 検出された脅威に対して迅速に対処できる必要があるというご意見をお聞きしました。 Ignite 2017 では、Azure Security Center Playbook を発表しました。このプレイブックを使用すると、Security Center によって検出された脅威に対応する方法を制御できます。 '
Content: >-
  <p>1 秒ごとに、攻撃が検出された場合にカウントされます。 検出された脅威に対して迅速に対処できる必要があるというご意見をお聞きしました。 <a href="https://youtu.be/e8iFCz5RM4g" target="_blank">Ignite 2017</a> では、<a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-playbooks" target="_blank">Azure Security Center Playbook を</a>発表しました。このプレイブックを使用すると、Security Center によって検出された脅威に対処する方法を制御できます。 Security Center アラートがトリガーされると、Security Center プレイブックを手動で実行し、応答時間を短縮し、セキュリティ態勢の制御を維持できます。 現在、Palo Alto VM-Series ファイアウォールに対して検出された脅威に迅速に対応するために、Azure Functions が Security Center プレイブックを使用する方法の具体的な例を確認します。</p>


  <p>このシナリオでは、Azure Security Center RDP ブルート フォース攻撃を検出して通知しました。 Palo Alto VM-Series ファイアウォールで、その攻撃の送信元 IP アドレスをブロックするには、いくつかの手順を完了する必要があります。 まず、C# プログラミング言語を使用した HTTP トリガー用に、Azure portal の Functions Apps で完了できる <a href="https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function" target="_blank">Azure</a> 関数を作成する必要があります。 Azure 関数は、Security Center プレイブックが Palo Alto VM-Series ファイアウォールと通信し、最終的に悪意のあるアクティビティがファイアウォールを通過するのをブロックする機能です。&nbsp;</p>


  <p>次に、以下のサンプル コードを Azure 関数に配置して、Security Center プレイブックをデプロイするときに、プレイブックによって悪意のある IP が <a href="https://www.paloaltonetworks.com/documentation/80/pan-os/xml-api/get-started-with-the-pan-os-xml-api/explore-the-api/use-the-api-browser" target="_blank">Palo Alto VM-Series</a> ファイアウォールを通過するようにブロックします。</p>


  <pre>

  using System.Net;


  using System.Security.Cryptography.X509Certificates;


  using System.Net.Security;


  public static async Task&lt;HttpResponseMessage&gt; Run(HttpRequestMessage req, TraceWriter log)


  {

   string key = &quot;<b>YOUR_PaloAlto_KEY</b>&quot;;

   string xmlElementForamt = @&quot;

  &lt;source&gt;

   &lt;member&gt;{0}-{0}&lt;/member&gt;

  &lt;/source&gt;


  &lt;destination&gt;

   &lt;member&gt;any&lt;/member&gt;

  &lt;/destination&gt;


  &lt;application&gt;

   &lt;member&gt;any&lt;/member&gt;

  &lt;/application&gt;


  &lt;service&gt;

   &lt;member&gt;any&lt;/member&gt;

  &lt;/service&gt;


  &lt;action&gt;deny&lt;/action&gt;


  &lt;source-user&gt;


  &lt;member&gt;any&lt;/member&gt;


  &lt;/source-user&gt;


  &lt;disabled&gt;no&lt;/disabled&gt;


  &lt;log-start&gt;yes&lt;/log-start&gt;


  &lt;log-end&gt;yes&lt;/log-end&gt;


  &lt;description&gt;IP Blocked as response from Azure Security Center&lt;/description&gt;


  &lt;from&gt;


  &lt;member&gt;any&lt;/member&gt;


  &lt;/from&gt;


  &lt;to&gt;

   &lt;member&gt;any&lt;/member&gt;

  &lt;/to&gt;&quot;;

   ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

   dynamic data = await req.Content.ReadAsAsync&lt;object&gt;();

   string ip = data?.ip;

   string ruleName = string.Format(&quot;IP {0} blocked from ASC&quot;, ip);

   string xmlElement = string.Format(xmlElementForamt, ip);

   string url = string.Format(

  &quot;https://<b>YOUR_PALO_ALTO_URL</b>/api/?type=config&amp;action=set&amp;key={0}&amp;xpath=/config/devices/entry/vsys/entry/rulebase/security/rules/entry[@name=&#39;{1}&#39;]&amp;element={2}&quot;,key, ruleName, xmlElement);

   var request = (HttpWebRequest)WebRequest.Create(Uri.EscapeUriString(url));

   request.ServerCertificateValidationCallback += (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) =&gt; true;

   var response = (HttpWebResponse)(await request.GetResponseAsync());

   response.Close();

  return req.CreateResponse(HttpStatusCode.OK);


  }</pre>


  <p>サンプル コードが Azure 関数内にあるので、次に示すワークフローを使用して新しいプレイブックを作成Security Centerに移動する必要があります。 プレイブックでは、Palo Alto ファイアウォールに関する問題への対応を調整する方法を定義します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/599dee6f-79ec-46a0-a86b-f43412d39671.png"><img alt="image" border="0" height="242" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4782947c-c090-4b65-a2bb-f5997b9ed928.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="イメージ" width="624"></a></p>


  <p>上に示すように、アラートが生成されると、セキュリティ<a href="https://docs.microsoft.com/en-us/azure/connectors/connectors-create-api-office365-outlook" target="_blank"></a>管理者に承認メールが送信され、攻撃のソース IP をブロックまたは無視する必要がある場合があります。 その電子メールに対する回答がブロックされている場合、作成された Azure 関数はソース IP を受け取り、Palo Alto VM-Series ファイアウォールにブロック規則を作成します。 その承認メールの回答が無視された場合、別の電子メールがセキュリティ管理者にアラートの説明と一緒に送信されます。</p>


  <p>セキュリティ アラートがトリガーされると、Azure Functions とプレイブックが設定されているので、Palo Alto VM-Series ファイアウォールにブロックルールを作成することで、検出された脅威にすばやく対応し、ネットワーク セキュリティを制御できます。</p>


  <p>プレイブックと関数の詳細については、ドキュメントを参照 <a href="https://docs.microsoft.com/en-us/azure/security-center/" target="_blank">してください</a>。</p>


  <p>プレイブックの使用Azure Security Centerするには、Standard レベルの <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-pricing" target="_blank">セキュリティを試してください</a>。</p>
