### YamlMime:Yaml
ms.openlocfilehash: aa67cd7687c0d7e6b55d5250b638cf0848f8d014
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892574"
Slug: september-update-for-web-apps-and-app-service-environments-in-the-azure-preview-portal
Title: Azure プレビュー ポータルWeb Apps App Service環境の 9 月の更新
Summary: このブログ投稿は少し時間が過ぎた投稿ですが、出荷された機能と機能強化を組み合っています。 .net framework 4.6 のサポート.Net Framework 4.6 を使用するアプリを構成できます。
Content: >-
  <p>このブログ投稿は少し時間が過ぎた投稿ですが、出荷された機能と機能強化を組み合っています。</p>


  <h2>.net framework 4.6 のサポート</h2>


  <p>.Net Framework 4.6 を使用するアプリを構成できます</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/82880d17-f89b-4902-9929-de9dcd746516.png"><img alt="image_thumb1" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4573b625-d46d-4d73-83a0-4667f3225a83.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="image_thumb1" width="1366"></a></p>


  <h2>プロセス エクスプローラー</h2>


  <p><strong>プロセス エクスプローラー</strong> には、信頼性の修正と、プロセスのアイコンを含める顔表示が用意されています。 これにより、Web サイト プロセス、サイト拡張機能、Web ジョブ、kudu プロセスを簡単に区別できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0648b1d2-29a0-4852-84f4-f38d85d797f2.png"><img alt="clip_image002_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/53bbb20c-4069-45f6-a253-a0decc7e30ca.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image002_thumb2" width="1366"></a></p>


  <h2>認証/承認</h2>


  <p>大きなディレクトリをより適切に処理するためにいくつかの機能強化が行われ、このシナリオでは UI の応答性が大幅に向上します。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8fd6aad7-c176-4aa6-93c9-ad2ac16929a0.png"><img alt="clip_image003_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b63a3dd3-be04-4a55-8e20-4eba368807eb.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image003_thumb2" width="1366"></a></p>


  <h2>新しい CI プロバイダー: OneDrive</h2>


  <p>継続的デプロイ用の OneDrive フォルダーを設定できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a996def4-68c6-43ee-b242-173678b48761.png"><img alt="clip_image004_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/61cc4635-b526-4847-ad43-fe0942804570.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image004_thumb2" width="1366"></a></p>


  <h2>App Service Plan Essentials</h2>


  <p><strong>App Serviceの要</strong>は、Web/モバイルとスロット全体でアプリ数を提供する機能です。&nbsp;<strong>参照</strong>では、このすべての型も統合リストに含まれます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bdbe0b92-7686-463b-81e5-0763026d2980.png"><img alt="clip_image005_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/703f93dd-5c65-4afd-a93a-3321119369a1.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="" width="1366"></a>clip_image005_thumb2 Tools</p>


  <h2>[ツール] メニュー</h2>


  <p>[ツール] <strong>メニューに [</strong><strong>イベントとアラート</strong>] が含まれています</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/faeb2961-27cb-4d8c-9bb4-69e1c0a315d7.png"><img alt="clip_image006_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b696baa2-7839-45dd-babf-3f9288b95f73.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image006_thumb2" width="1366"></a></p>


  <h2>App Service環境の更新</h2>


  <h3>新しい ASE 作成エクスペリエンス</h3>


  <p>WebApp 作成エクスペリエンスの&#39;を形成し、それらを作成に適用して、すべての学習App Service Environmentしました。<strong> </strong> その結果、非常に合理化されたエクスペリエンスが得られます&ldquo;&rdquo;。すべてのロックが排除され、最小限の入力が必要になります。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3e035b51-2d04-4b9d-9825-d1b3e2b72e12.png"><img alt="clip_image007_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c4ed7a0a-ce08-46ce-8f0d-745a3673e1b6.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image007_thumb2" width="1366"></a></p>


  <h3>ASE 自動スケーリングのサポート</h3>


  <p>ワーカー プールとフロントエンドでメトリックとスケジュールベースの自動スケールApp Service Environmentを実行できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9c588a44-62f0-4677-86ca-d17d9c7efbcc.png"><img alt="clip_image008_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/af62eaad-326d-4c93-bc65-657da60475af.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image008_thumb2" width="1366"></a></p>


  <h3>ワーカー プールとフロントエンドの完全なリソース ブレード</h3>


  <p>フロントエンドとワーカー プールを個々のリソースとして管理できます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e30e89fb-b3d5-4003-a1fd-0b46bbf1f506.png"><img alt="clip_image009_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8767708b-b41e-45a3-88b9-5344f840c573.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image009_thumb2" width="1366"></a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f57c91c4-d8fb-4451-b393-b1798c8f53af.png"><img alt="clip_image010_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6f4ffb20-0a2e-46bf-be95-cca72adc5ba6.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image010_thumb2" width="1366"></a></p>


  <h3>IP アドレス管理エクスペリエンス</h3>


  <p>新 <strong>しいApp Service Environment</strong> IP 管理エクスペリエンスを使用して、IP アドレスをスケーリングし、アプリケーションでホストされているアプリで使用 <strong>App Service Environment</strong></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8ea19ab3-7225-44e0-aa06-50287971881b.png"><img alt="clip_image011_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c10988d1-f085-482a-80a5-ba6bb13697c7.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image011_thumb2" width="1366"></a></p>


  <h3>すべてのリソースの種類に対するApp Service Environmentサポート</h3>


  <p>App Service 環境、ワーカー <strong>プール、</strong>フロントエンドに基づいてメトリック ベースのアラートを設定し、電子メール通知を取得したり、新しい Web フック機能をトリガーしたりできます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1edef53c-d33c-420c-af41-278518ea3a27.png"><img alt="clip_image012_thumb2" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c7d20026-f99e-4fa1-b8ed-48df1cb8a522.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image012_thumb2" width="1366"></a></p>


  <p>&nbsp;</p>


  <h2>Clear DB Cluster Support</h2>


  <p>ClearDB 用の新しい Hi-Performance MySQL SKU も提供しました。 これには、ミッション クリティカルなデータベースのサポートと、WebApp の作成エクスペリエンスのリバンプを形成する&#39;に基づく新しい洗練された作成エクスペリエンスが含まれます。</p>


  <p>お知らせのブログ投稿は次の場所です。 <a href="https://azure.microsoft.com/en-us/blog/announcing-new-mysql-premium-tiers-from-cleardb/">https://azure.microsoft.com/en-us/blog/announcing-new-mysql-premium-tiers-from-cleardb/</a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b87612d0-f11b-4eea-a144-d240bc0944a4.png"><img alt="clip_image0015_thumb" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7b1c7b88-bfdc-41a2-9b77-269fba7056ff.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; margin: 0px; display: inline; padding-right: 0px" title="clip_image0015_thumb" width="1366"></a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/837bcd08-c589-4ead-a078-acf38eaa5644.png"><img alt="image_thumb" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ad07364c-ff68-403b-939b-993ba6c22526.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="image_thumb" width="1366"></a></p>


  <p>&nbsp;</p>


  <p>以下のコメント セクションまたは User Voice サイトを通じて、ご自分の考え、質問、アイデアをお <a href="https://feedback.azure.com/forums/169385-web-apps-formerly-websites" target="_blank">知</a> らせください。</p>
