### YamlMime:Yaml
ms.openlocfilehash: 7637afbce72eedb0c15c81152ed8669d7bb31d33
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892573"
Slug: september-update-web-apps-and-app-service-environments
Title: Web Apps および App Service 環境向けの9月の更新プログラム
Summary: 'このブログ投稿は少し過ぎていますが、提供されている機能と改善点について説明しています。 '
Content: >-
  <p>このブログ投稿は少し期限が過ぎていますが、提供されている機能と機能強化に対応しています。</p>


  <h2>.Net framework 4.6 のサポート</h2>


  <p>.Net framework 4.6 を使用するようにアプリを構成できるようになりました。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/71008f04-2cac-4212-a8c8-7595c06faea8.png"><img alt="image" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/06907213-39b2-4975-8c26-97065b7750b8.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="絵" width="1024"></a></p>


  <h2>プロセス エクスプローラー</h2>


  <p><strong>プロセスエクスプローラー</strong> には、いくつかの信頼性修正プログラムと、web サイトプロセス、サイト拡張機能、web ジョブ、kudu プロセスを区別しやすくするためのプロセスアイコンが含まれています。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/56623a2d-742c-40d9-8d40-6cdd19bb1fca.png"><img alt="clip_image002" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/04a9a342-c574-4d77-8bbe-2e55f969c15b.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image002" width="1024"></a></p>


  <h2>認証/承認</h2>


  <p>大規模なディレクトリの処理を改善し、UI の応答性が大幅に向上しました。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/26922c2b-f5b3-4590-bdb1-c2d188ccd07a.png"><img alt="clip_image003" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e0abf0e5-c8ae-49aa-9bd7-13da0dc7ee1e.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image003" width="1024"></a></p>


  <h2>新しい CI プロバイダー: OneDrive</h2>


  <p>継続的なデプロイのために OneDrive フォルダーをセットアップできるようになりました。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/601f1c80-30ac-4b4c-a37c-5be6495d1e10.png"><img alt="clip_image004" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/eb926266-2de7-41ca-835f-b54ea6990de1.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image004" width="1024"></a></p>


  <h2>プランの基本 App Service</h2>


  <p><strong>App Service Plan</strong> essentials では、Web/モバイルおよびスロット全体でアプリ数を提供するようになりました。 [<strong>参照</strong>] には、統合されたリスト内のすべての型も含まれます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e5eba08e-b568-4692-8a79-cf1618e312d0.png"><img alt="clip_image005" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0461eb50-3e3d-48b2-bd94-0e23e181d77c.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image005" width="1024"></a></p>


  <h2>[ツール] メニュー</h2>


  <p>[ツール] メニューには、 <strong>イベント</strong> と <strong>警告</strong> が含まれていました。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/86d5975f-a8b5-4e17-a4ad-99a36ef0d925.png"><img alt="clip_image006" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4d67ba69-cdd0-49e7-a7b6-9f0a0d9d7339.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image006" width="1024"></a></p>


  <h2>App Service Environment の更新プログラム</h2>


  <h3>新しい ASE の作成エクスペリエンス</h3>


  <p>学習は、Web アプリの作成エクスペリエンスの再 vamp からすべてのものを受け取り、それを作成<strong> App Service Environment</strong> に適用しました。 結果として、すべて &ldquo; のロック &rdquo; を排除し、最小限の入力を必要とする、はるかに効率的なエクスペリエンスが得られます。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b9097714-33bd-422a-8050-a75060224a01.png"><img alt="clip_image007" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/85e86598-0cd4-499d-a7ae-2b913809f4ca.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image007" width="1024"></a></p>


  <h3>ASE 自動スケールのサポート</h3>


  <p>App Service Environment Worker プールとフロントエンドでメトリックを作成し、自動スケールに基づくスケジュールを設定できるようになりました。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/eca91eaa-c173-42b8-b895-efbb571a72f0.png"><img alt="clip_image008" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a1921360-2f93-47b6-a24a-1f893a5735f2.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image008" width="1024"></a></p>


  <h3>ワーカープールとフロントエンドの完全なリソースブレード</h3>


  <p>フロントエンドとワーカープールを個々のリソースとして管理できるようになりました。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/92a2f1f2-b402-4b5b-a3dc-37415cd59e18.png"><img alt="clip_image009" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/15b4cc58-2842-42ef-bb61-5bd291f4c996.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image009" width="1024"></a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d0052f38-04f1-41ee-aadd-4505a89cda5a.png"><img alt="clip_image010" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2963ec8e-f16e-443e-be00-9487cf567469.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image010" width="1024"></a></p>


  <h3>IP アドレスの管理エクスペリエンス</h3>


  <p>Ip アドレスを拡張し、 <strong>App Service Environment</strong>でホストされているアプリでそれらを使用するための新しい<strong>App Service Environment</strong> ip 管理エクスペリエンス。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c1ba1f3b-7698-4f49-b4c1-8dd94876c9d8.png"><img alt="clip_image011" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b9a016cf-5341-4a61-987c-05a5e6c2ece3.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image011" width="1024"></a></p>


  <h3>すべての App Service Environment リソースの種類のアラートサポート</h3>


  <p><strong>App Service 環境</strong>、ワーカープール、フロントエンドでメトリックベースのアラートを設定して、電子メール通知を受信したり、新しい web フック機能をトリガーしたりできるようになりました。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9adeff62-6e21-4666-9689-1e729719f0f6.png"><img alt="clip_image012" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/38de8a3c-96ae-4dfb-b110-685aa5a4ae65.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image012" width="1024"></a></p>


  <h2>ClearDB クラスターのサポート</h2>


  <p>また、ClearDB 用の新しいハイパフォーマンス MySQL SKU も提供しています。 これには、ミッションクリティカルなデータベースのサポートと、Web アプリ作成エクスペリエンスの再 vamp からの学習に基づく洗練された作成エクスペリエンスが含まれます。</p>


  <p>ClearDB MySQL プレミアムレベルの発表については、<a href="https://azure.microsoft.com/en-us/blog/announcing-new-mysql-premium-tiers-from-cleardb/">こちら</a>を参照してください。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2ded2993-009d-41bb-855d-4f9cab44b3be.png"><img alt="clip_image001[5]" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5faf1032-793f-4c95-8108-4cd7232b6145.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image001 [5]" width="1024"></a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9f7c0dc5-0d85-4e21-9323-a31b5d68aaf5.png"><img alt="image" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6e4e71cd-e3e6-4578-8514-67442e3eebcf.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="絵" width="1024"></a></p>


  <p>&nbsp;</p>


  <h4>下のコメントセクションまたは <a href="https://feedback.azure.com/forums/169385-web-apps-formerly-websites" target="_blank">ユーザーの声</a> サイトで、お客様のご意見、質問、アイデアをお知らせください。</h4>
