### YamlMime:Yaml
ms.openlocfilehash: 6793ce57cf02d1342531f866aeb1073007ebd3a7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892530"
Slug: setting-up-active-directory-for-a-disaster-recovery-environment-2
Title: ディザスター リカバリー環境用の Active Directory の設定
Summary: この投稿では、フェールオーバー イベントの後もアプリケーションが引き続き正常に機能するために、さまざまなシナリオで Active Directory を設定する方法について説明します。
Content: >-
  ディザスター リカバリー環境を設定する場合は、Active Directory のセットアップ方法も考える必要があります。 後から考えるべきではありません。


  ほとんどのアプリケーションは、正しく機能するために AD と DNS インフラストラクチャに依存しています。 この投稿では、フェールオーバー イベントの後もアプリケーションが引き続き正常に機能するために、さまざまなシナリオで Active Directory を設定する方法について説明します。


  次の要因は、ドメイン コントローラーを復旧サイトにレプリケートする方法を制御します。 このセクションの次の表では、これらの要因が決定に与える影響について説明します。

  <ol>
   <li><b>回復サイト</b>: オンプレミス サイト間または直接、オンプレミス サイト間の保護を構成Microsoft Azure</li>
   <li><b>フェールオーバーの種類</b>: テスト フェールオーバーを実行しようとしているかどうか、計画されたフェールオーバー、または計画されていないフェールオーバー<i></i>に応じて、ドメイン <i></i> コントローラーをレプリケートするための推奨される方法と復旧手順が変更される可能性があります<i></i></li>
   <li><b>フェールオーバーユニット</b>: 部分サイトを柔軟にフェールオーバーするか、または関心のある唯一のシナリオが完全なサイト フェールオーバーである場合</li>
   <li><b>フォレスト</b>内のドメイン コントローラーの数: 推奨されるレプリケーション テクノロジは、小規模または中規模の企業でドメイン コントローラーが 1 つだけあるか、環境内に複数のドメイン コントローラーがある場合によって異なります。 既に 2 つ以上のサイトがある場合は、複数のドメイン コントローラーが存在する可能性があります</li>
  </ol>

  &nbsp;


  次の表は、ドメイン コントローラーをさまざまなシナリオでレプリケートする方法をまとめたものです。


  &nbsp;

  <table class="aligncenter" width="711" border="1" cellspacing="0" cellpadding="0"><colgroup><col width="105" /> <col width="127" /> <col width="87" /> <col width="182" /> <col width="210" /></colgroup>

  <tbody>

  <tr>

  <th width="105" height="41">シナリオ</th>

  <th width="127">フェールオーバーの種類</th>

  <th width="87">フェールオーバー ユニット</th>

  <th width="182">フォレスト内のドメイン コントローラーの現在の数</th>

  <th width="210">推奨されるレプリケーション テクノロジ</th>

  </tr>

  <tr>

  <td width="105" height="81">オンプレミスからオンプレミスへ</td>

  <td width="127">テスト フェールオーバー</td>

  <td width="87">該当なし</td>

  <td width="182">1 つ</td>

  <td width="210">アプリケーションでサポートされているテクノロジから選択したレプリケーション テクノロジAzure Site Recovery</td>

  </tr>

  <tr>

  <td width="105" height="121">オンプレミスからオンプレミスへ</td>

  <td width="127">テスト フェールオーバー</td>

  <td width="87">該当なし</td>

  <td width="182">複数</td>

  <td width="210">復旧サイトのドメイン コントローラーの vhd ファイルの Azure Site Recoveryまたはスナップショットでサポートされているテクノロジから選択したレプリケーション テクノロジ</td>

  </tr>

  <tr>

  <td width="105" height="81">オンプレミスからオンプレミスへ</td>

  <td width="127">計画されたフェールオーバーと計画されていないフェールオーバー</td>

  <td width="87">完全なサイト</td>

  <td width="182">1 つ</td>

  <td width="210">アプリケーションでサポートされているテクノロジから選択したレプリケーション テクノロジAzure Site Recovery</td>

  </tr>

  <tr>

  <td width="105" height="41">オンプレミスからオンプレミスへ</td>

  <td width="127">計画されたフェールオーバーと計画されていないフェールオーバー</td>

  <td width="87">完全なサイト</td>

  <td width="182">複数</td>

  <td width="210">AD レプリケーション</td>

  </tr>

  <tr>

  <td width="105" height="41">オンプレミスからオンプレミスへ</td>

  <td width="127">計画されたフェールオーバーと計画されていないフェールオーバー</td>

  <td width="87">部分サイト</td>

  <td width="182">該当なし</td>

  <td width="210">AD レプリケーション</td>

  </tr>

  <tr>

  <td width="105" height="101">オンプレミスから Azure へ</td>

  <td width="127">テスト フェールオーバー</td>

  <td width="87">該当なし</td>

  <td width="182">該当なし</td>

  <td width="210">アプリケーションでサポートされているテクノロジから選択したレプリケーション テクノロジAzure Site Recovery</td>

  </tr>

  <tr>

  <td width="105" height="81">オンプレミスから Azure へ</td>

  <td width="127">計画されたフェールオーバーと計画されていないフェールオーバー</td>

  <td width="87">完全なサイト</td>

  <td width="182">1 つ</td>

  <td width="210">アプリケーションでサポートされているテクノロジから選択したレプリケーション テクノロジAzure Site Recovery</td>

  </tr>

  <tr>

  <td width="105" height="41">オンプレミスから Azure へ</td>

  <td width="127">計画されたフェールオーバーと計画されていないフェールオーバー</td>

  <td width="87">完全なサイト</td>

  <td width="182">複数</td>

  <td width="210">AD レプリケーション</td>

  </tr>

  <tr>

  <td width="105" height="41">オンプレミスから Azure へ</td>

  <td width="127">計画されたフェールオーバーと計画されていないフェールオーバー</td>

  <td width="87">部分サイト</td>

  <td width="182">該当なし</td>

  <td width="210">AD レプリケーション</td>

  </tr>

  </tbody>

  </table>

  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/01/20/table.png"> </a>


  &nbsp;


  上記の推奨事項を提供する理由を次に示します。

  <ol>
   <li>環境内に複数のドメイン コントローラーが既に存在し、ドメイン コントローラーをレプリケートするために Hyper-V レプリカなどのレプリケーション テクノロジを使用している場合。 計画外のフェールオーバー (データ損失が最大 15 分のフェールオーバー) の場合、フェールオーバーされたドメイン コントローラーは古い時点に戻されます。 このようなシナリオでは、異なるドメイン コントローラーが互いに矛盾する可能性があります。
  <blockquote>そのため、環境内に複数のドメイン コントローラーがある場合は常に、AD レプリケーションを使用してドメイン コントローラーを回復サイトにレプリケートする必要があります</blockquote>

  </li>
   <li>AD レプリケーションを使用する場合は、復旧サイトでも仮想マシンを実行する必要があります。 両方のサイトが既にアクティブに使用されている場合は、両方のサイトでドメイン コントローラーが実行されている可能性があります。 ただし、復旧サイトがディザスター リカバリー目的でのみ使用されている場合は、常に復旧サイトで仮想マシンを実行すると、コストが追加されます。
  <blockquote>そのため、アクティブなサイトが 1 つのみで、ドメイン コントローラーが 1 つのみである場合は、AD レプリケーション以外のレプリケーション テクノロジを使用してドメイン コントローラーをレプリケートできます。</blockquote>

  </li>
   <li>部分サイトのフェールオーバーを実行する場合は、一部のアプリケーションがプライマリ サイトで実行され、フェールオーバーされた他のアプリケーションが復旧サイトで実行される場合があります。 このようなシナリオでは、両方のサイトでアクティブなドメイン コントローラーが必要になります。
  <blockquote>そのため、部分サイトのフェールオーバーを実行する場合は、AD レプリケーションを使用し、両方のサイトでアクティブなドメイン コントローラーを保持する必要があります</blockquote>

  </li>
   <li>テスト フェールオーバーを実行するには、分離テスト環境でドメイン コントローラーのインスタンスが必要になります。 このインスタンスは、ドメイン コントローラー仮想マシンの 1 つでAzure Site Recoveryによって提供されるテスト フェールオーバー ジェスチャを使用して作成できます。
  <blockquote>これを実現するには、ドメイン コントローラー仮想マシンを、アプリケーションでサポートされているテクノロジから選択したレプリケーション テクノロジを使用してレプリケートするAzure Site Recovery。</blockquote>

  </li>

  </ol>

  復旧サイトがオンプレミスで、既に回復サイトで実行されているドメイン コントローラーがある場合は、仮想マシンのスナップショットを作成し、vhd を使用してドメイン コントローラーのテスト インスタンスを作成することで、テスト ドメイン コントローラーを作成することもできます。


  ディザスター リカバリー用の<a href="https://aka.ms/ad_e2a_networking_blog"></a>ネットワークの設定の詳細については、アプリケーションが Active Directory に依存している場合にテスト フェールオーバーを実行する方法を理解してください。


  さらに、いくつかのことを念頭に置く必要があります。

  <ol>
   <li>企業内に複数のドメインがある場合は、各ドメインを復旧サイトで表す必要があります。 フォレスト内の各ドメインに対して少なくとも 1 つのドメイン コントローラーが復旧サイトに含けられている必要があります。</li>
   <li>また、プライマリ サイトと復旧サイトの両方の少なくとも 1 つのドメイン コントローラーに DNS ロールがインストールされていることを確認する必要があります。</li>
  </ol>

  それまでは、さまざまなシナリオでドメイン コントローラーのレプリケーションを設定する方法について説明しました。 ここでの問題は、フェールオーバー後の復旧手順が、どのシナリオでも必要かどうかです。


  この質問に対する答えは、プライマリ上のドメイン コントローラーがフェールオーバー後も引き続き使用できるかどうかによって異なる場合があります。 プライマリ サイトが完全にシャットダウンされた完全なサイトで計画されたフェールオーバーが発生した場合、またはプライマリ サイトが使用できなくなった可能性がある計画外のフェールオーバーが発生した場合は、復旧サイトのドメイン コントローラーで <a href="https://aka.ms/ad_seize_fsmo">FSMO Active Directory</a> の役割を取得し、不足しているドメイン コントローラーのメタデータクリーンアップを行う必要がある場合があります。


  一部のレガシ アプリケーションは、FSMO ロールがない場合に機能しない場合があります。これらのアプリケーションは特定のドメイン コントローラーにバインドされている可能性があります。 このような場合は、プライマリ サイトが後でバックアップされる場合でも、復旧サイト ドメイン コントローラーの修正を完了している可能性があります。 これらの修正を復旧サイトで実行する必要があるかどうかを結論付けるには、次に示す決定ツリーに従います。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/01/20/Ad-Fixup-Decision-Tree.jpg"><img style="padding-top: 0px; padding-left: 0px; padding-right: 0px; border: 0px;" title="Ad Fixup デシジョン ツリー" alt="Ad Fixup Decision Tree" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Ad-Fixup-Decision-Tree_thumb.jpg" width="684" height="772" border="0" /></a>


  この投稿では、別のサイトへのディザスター リカバリーのためにサイト上に 1 つまたはアプリケーションを設定するときに、Active Directory を設定する方法を確認しました。 さまざまなシナリオで使用できるさまざまなレプリケーション テクノロジについて説明しました。 次に、プライマリ サイトが使用できなくなった場合に実行する必要があるフェールオーバー後の修正プログラムがある場合は、 で終了しました。


  さらに質問がある場合は、 <a href="https://aka.ms/ad_forum">MSDN</a> の Azure Site Recovery フォーラムにアクセスして、追加情報を確認し、他のお客様と連絡を取り合います。


  また、追加<a href="https://aka.ms/ad_productinfo">の製品情報を確認</a>し、<a href="https://aka.ms/ad_trial">無料の Azure</a> 試用版にサインアップして、Microsoft Azureを使用Azure Site Recovery。
