### YamlMime:Yaml
ms.openlocfilehash: ee8b6e0f5819e968a69044bf0c47ed896a5c2a86
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892295"
Slug: sql-azure-connection-security
Title: SQL Azure接続のセキュリティ
Summary: '[この記事は、チームによってSQL Azureされました。]Selcin Turkarslan は、接続のセキュリティに関する考慮事項に関する詳細な TechNet wiki 記事を作成し、SQL Azure。 記事は...'
Content: <p>[この記事は、チームによってSQL Azureされました。]</p><p>Selcin Turkarslan は、接続のセキュリティに関する考慮事項に関する詳細な TechNet wiki 記事を作成し、SQL Azure。 この記事では、主に、データベースのセキュリティで保護された接続文字列の作成SQL Azureします。 ID&rsquo; では、データを使用して接続する際の優れた手順とベスト プラクティスについて詳SQL Azure。 </p>  <p><a href="https://social.technet.microsoft.com/wiki/contents/articles/sql-azure-connection-security.aspx">ここをクリックして、"SQL Azure接続セキュリティ" を読み取る</a></p>  <p>アプリケーション内の接続セキュリティに関する質問がある場合はSQL Azureコメントを残してください。  Wed&rsquo; は、ご質問がある場合は、お手伝いします。</p>  <p>-Steve</p>
