### YamlMime:Yaml
ms.openlocfilehash: 4a579bb5985b3ffa82afc33b4f9858d95b9d3737
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139892024"
Slug: swagger-s-success-gives-birth-to-openapi
Title: Swagger の成功によって OpenAPI が誕生
Summary: これまで数年で、Swagger と呼ばれる API 記述形式が急速に勢いを獲得しました。 この仕様は、最近、その所有者によって OpenAPI イニシアチブグループに寄付されている可能性があります。
Content: >-
  <p>これまで数年で、 <a href="https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md">Swagger</a> と呼ばれる API 記述形式が急速に勢いを獲得しました。 この問題に対応するために、仕様が最近、その <a href="https://openapis.org/news/blogs/2016/07/you-can-get-involved-creating-openapi-specification-and-heres-how">所有者 Smartbear によって</a> <a href="https://openapis.org/">openapi イニシアチブ</a> グループに寄付された&#39;ます。 OAI は、 <a href="https://www.linuxfoundation.org/">Linux Foundation</a> の責任下で新しく形成されたグループであり、Microsoft、GOOGLE、IBM、Paypal、Atlassian、Captial One、わかり、smartbear、その他多くの人をスポンサーメンバーとして含みます。</p>


  <h2>Community では、</h2>


  <p>スマートな仕様を区別するために、Smartbear が所有するツールから、Swagger 仕様の名前が OpenAPI 仕様に変更されました。 Swagger という用語は、OpenAPI 仕様を操作するために Smartbear が所有する <a href="https://github.com/swagger-api/">ツール</a> のみを参照するようになりました。 OpenAPI 仕様での作業は、関連するすべてのユーザーによって <a href="https://github.com/OAI/OpenAPI-Specification">Github リポジトリ</a> 上で行われています。</p>


  <h2>すべての手が役に立ちます</h2>


  <p>今年の初めに OpenAPI テクニカルデベロッパー委員会に参加し、通常の会議に参加し、問題に対応し、新しい問題を作成し、Pr を見直し、Pr を作成しました。 <a href="https://azure.microsoft.com/en-us/services/api-management/">Azure API Management</a>チームの開発者は、毎日のジョブで openapi 仕様を定期的に使用しています。 開発者が現在のバージョンの仕様に直面している課題を理解し、次のバージョンがどこにあるかを確認することにより、Azure API Management お客様にとってより良い製品になります。</p>


  <h2>Microsoft&#39;の血液に&#39;s</h2>


  <p>Microsoft では、多くの製品で、OpenAPI 仕様のバージョン2.0 をプライマリ API 記述形式として採用しています。 <a href="https://azure.microsoft.com/en-us/documentation/articles/api-management-howto-import-api/">Azure API Management</a>、 <a href="https://azure.microsoft.com/en-us/documentation/articles/connectors-native-http-swagger/">Logic Apps</a>、 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-service-api-dotnet-get-started/">API Apps</a>、 <a href="https://powerapps.microsoft.com/en-us/tutorials/customapi-how-to-swagger/">Power Apps</a>、 <a href="https://powerapps.microsoft.com/en-us/tutorials/customapi-how-to-swagger/">Microsoft Flow</a>、 <a href="https://blogs.msdn.microsoft.com/visualstudio/2015/03/24/introducing-the-azure-api-apps-tools-for-visual-studio-2013/">Visual Studio</a> 、および<a href="https://github.com/Azure/autorest/blob/master/Documentation/defining-clients-swagger.md">AutoREST</a>はすべて openapi をサポートしていますが、ほとんどの場合、Swagger という用語は引き続き使用されます。</p>


  <h2>変更せずに進行状況を変更することはできません</h2>


  <p>過去8か月間、コアチームと多くのコミュニティメンバーが OpenAPI 仕様に大幅な更新を行ってきました。 <a href="https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md">Openapi</a> v2.0 の安定化が開始され、2017年1月に新しいバージョンがリリースされるようになりました。</p>


  <h2>すべてのユーザーのためのもの</h2>


  <p>新しいバージョンでは、ドキュメント全体の <a href="https://openapis.org/news/blogs/2016/10/tdc-structural-improvements-explaining-30-spec-part-2">構造</a>が簡略化されています。 API を文書化し、例を提供する新しい方法が追加されました。 API をホストするためのより柔軟なオプションがあります。 要求と応答のペイロードを、 <a href="https://openapis.org/news/blogs/2016/10/tdc-request-parameters-explaining-30-spec-part-3">よりシンプルで柔軟な方法</a>で記述できるようになりました。 Uri パラメーターは、 <a href="https://tools.ietf.org/html/rfc6570">Uri テンプレート</a> によって定義された多くの機能をサポートするようになり、JSON スキーマの使用に課せられる多くの制限が解除されました。</p>


  <p>仕様の2.0 で Api がどのように記述されたかに対するこれらの機能強化に加えて、まったく新しいシナリオをサポートするための機能強化も行われています。 新しいコールバックオブジェクトを使用して webhook を記述できるようになりました。 リンクの概念が追加され、操作間の関係を静的に記述できるようになりました。 これにより、ドキュメントを使用して、より多くのコンテキスト情報を提供したり、クライアントライブラリのユーザーフレンドリ度を大幅に向上させることができます。</p>


  <h2>より進んで作業する</h2>


  <p>仕様を完了するための作業量は依然として残っていますが、すべての問題が終了したと見なされるためには、ツールに大きな作業が行われることが期待されています。 ただし、進行状況は良好で、ターゲットの完了日は実現可能です。</p>


  <h2>連絡を取り、参加する</h2>


  <p>詳細については、 <a href="https://openapis.org/news-faq/blog">Oai ブログ</a> を参照してください。計画された変更の詳細については、こちらをご覧ください。 Don&#39;は、 <a href="https://github.com/OAI/OpenAPI-Specification">Github リポジトリ</a> をチェックアウトして問題に関するフィードバックを提供し、変更の要求を取得し、製品とツールの3.0 サポートを利用しているかどうかをチームに知らせます。</p>
