### YamlMime:Yaml
ms.openlocfilehash: b2887a9fb2e66a39ecea73ec095744718a0091d9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139890049"
Slug: train-an-iot-equipped-drone-and-compete-to-win-at-microsoft-build
Title: IoT 搭載のドローンをトレーニングし、Microsoft のビルドで勝利に勝つ
Summary: Microsoft の ultimate developer イベントの準備ができていますか? 私たちは既に Microsoft のビルドを知られているかもしれませんが、ワシントン州シアトルでは5月9日に発生しています。
Content: >-
  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/07e079d6-c34d-4e03-a115-e4a92080d0f0.png"><img alt="Build-Drone-Contest-Banner%202%202000x590%20" border="0" height="590" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b9e56a74-5964-472d-9dad-ed83d7eb026f.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="ビルド-Drone-コンテスト %202% 202000x590% 20" width="2000"></a></p>


  <p>Microsoft &rsquo; の ultimate developer イベントの準備ができていますか? 私たちは既に <a href="https://www.microsoft.com/en-us/build/?icid=azure_blog_drone_copy1" target="_blank">Microsoft のビルド</a>を知られているかもしれませんが、ワシントン州シアトルでは9月 7 &ndash; 日で、エキスパートとのつながり、新しいツールの発見、クラウドテクノロジ、AI、mixed reality などに関するスキルの向上を行う必要があります。</p>


  <p>確かに、快適な講演者と技術セッションは大量 &mdash; ていますが、drone に勝つことはできましたか。</p>


  <p>これで、ドローンコンテストを作りまし &rsquo; た &rsquo; 。 参加者は、特に Microsoft Build 向けに設計されたアウトドア検索とレスキューコースを完了できる、他の人のカンファレンスと戦うことができます。 Microsoft &rsquo; のインテリジェントなクラウドプラットフォーム Azure IoT を使用して、エンドツーエンドのエクスペリエンスを体験し、DJI Mavic Air を獲得できるようになりました &rsquo; 。</p>


  <p>すばらしいですね。</p>


  <h2>&rsquo;動作のしくみ</h2>


  <p>熱狂的は、オープンソースの航空写真おいとロボットシミュレーションプラットフォームであるエア Sim を使用してトレーニングイメージを作成します。 その後、熱狂的は Custom Vision を使用して、現実的な ai ドローンモデルを構築し、クラウドでトレーニングします。次に、 <a href="https://www.microsoft.com/en-us/internet-of-things/intelligentedge" target="_blank">Microsoft Azure IoT Edge</a>に ai デプロイ用のコンテナーを作成します。 このインテリジェントなクラウドプラットフォームでは、クラウドのエッジで人工知能を実行し、分析を実行し、クラウドからエッジ対応デバイスに IoT ソリューションをデプロイし、クラウドから一元的に管理することができます。</p>


  <p>Azure IoT Edge developer toolkit は、カンファレンス中に<a href="https://aischool.microsoft.com/learning-paths" target="_blank">AI School</a>からダウンロードできます。また、2018年5月9日の午前11時 (太平洋標準時) に、drone のブースのコンテストでモデルを入力してください。 正午には、午後10時の熱狂的をランダムに描画して、 &rsquo; 夜のライブドローンでモデルをテストします。 &rsquo;Microsoft のビルドを終了したときにコンテストに参加することで、全員が行動をライブストリームことができるようになります。</p>


  <p>優勝者は DJI Mavic の航空交通を受けます。第2位と第3位の優勝者は、home DJI Spark ドローンを受け取ります。 すべての受賞者は、排他的な swag の goodie バッグを受け取ります。 詳細およびコンテストルールの詳細については、 <a href="https://www.microsoft.com/en-us/build" target="_blank">Microsoft Build web サイト</a>を参照してください。</p>


  <h2>コンテスト以外</h2>


  <p>コンテストに応募する場合でも、Microsoft のビルドエクスペリエンスを他のアクティビティとともに入力する場合でも、エキスポの AI 領域にあるドローンのブースを確認してください。 &rsquo;また、ドローン博物館、ライブミニドローンは、独自の特殊なケージ、コンペティションビデオなどを備えています。</p>


  <p>350を超える非常に <a href="https://www.microsoft.com/en-us/build/sessions" target="_blank">優れた技術セッションとインタラクティブなワークショップ</a> により、 <a href="https://www.microsoft.com/en-us/build/speakers" target="_blank">あまりの講演者や数十</a> 以上の講演者を選ぶこと &rsquo; ができ、マイクロソフトのビルドから離れています。これにより、技術の方向性や、変換の一部としての方法をより深く理解することができます。</p>


  <p>それでも、それだけでドローン。 Developer 天国のようなサウンド。 ただし、 <a href="https://www.microsoft.com/en-us/build/?icid=azure_blog_drone_copy1" target="_blank">今すぐ Microsoft Build に登録</a>する場合にのみ使用してください。</p>
