### YamlMime:Yaml
ms.openlocfilehash: 167911a234bb012a0021ed86dcf2a337cc59a703
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895279"
Slug: transitioning-application-insights-from-the-vso-portal-to-the-azure-portal
Title: VSO ポータルから Azure portal への Application Insights の移行
Summary: Visual Studio オンラインポータルの Application Insights は、10月15日に読み取り専用モードに移行します。 Azure プレビューポータルでホストされている新しいバージョンを使用するようにアプリケーションを更新する方法について説明します。
Content: >-
  Visual Studio オンラインポータルで古いバージョンの<a href="https://azure.microsoft.com/services/application-insights/">Application Insights</a>を引き続き使用している場合は、 <a href="https://portal.azure.com/">Azure プレビューポータル</a>でホストされている新しいバージョンを<strong>10 月 15</strong>日までに使用するように<a href="https://azure.microsoft.com/documentation/articles/app-insights-upgrade-vso-azure/">アプリケーションを更新</a>する必要があります。


  最初に、Application Insights が Visual Studio オンラインポータルから新しい Azure プレビューポータルで提供されるサービスの1つに移行するという<a href="https://blogs.msdn.com/b/visualstudioalm/archive/2015/02/06/application-insights-moving-from-visual-studio-online-portal-to-azure-preview-portal.aspx">2 月のブログ</a>記事で発表しました。 microsoft は引き続き、Azure portal のエクスペリエンスに Application Insights の機能に投資しています。また、世界中のアプリケーションのパフォーマンス、可用性、使用状況において包括的な360°のビューのビジョンを<a href="https://azure.microsoft.com/blog/2015/04/29/announcing-application-insights-public-preview-2/">実現して</a>います。 さらに、Azure プレビューポータルの新しいバージョンの Application Insights では、サポートされるアプリケーションの種類の範囲を継続的に拡張して、iOS、Android、Windows デバイスアプリ、オンプレミスまたはクラウドでホストされている web アプリケーションを J2EE または .net に含めます。

  <h2>移行スケジュール</h2>

  本日は、VSO ポータルから Azure portal への Application Insights の移行について詳しく発表します。 VSO ポータルの<strong>2015 年10月 15</strong>日 Application Insights、読み取り専用モードに移行します。 MMA エージェントやテレメトリ Sdk からの新しいデータは受け入れられず、VSO ポータルで構成された web テストを実行できなくなります。 VSO ポータルの Application Insights を使用して、10月15日より前に収集されたデータを表示することもできます。


  VSO portal の Application Insights は<strong>、2015年11月 30</strong>日に廃止される予定です。


  注: まだ行っていない場合は、VSO ポータルで Application Insights からアプリケーションを移動して、Azure portal で Application Insights できるように<strong>なりまし</strong>た。

  <h2>Azure portal で Application Insights を使用するようにアプリケーションを移行操作方法</h2>

  <a href="https://azure.microsoft.com/documentation/articles/app-insights-upgrade-vso-azure/">ここ</a>では、アプリケーションを移行するプロセスについて詳しく説明します。 ASP.NET アプリの主な手順は次のとおりです。

  <ol>
   <li>にログインできるように、 <a href="https://azure.microsoft.com/pricing/free-trial/">Microsoft Azure のサブスクリプションを取得</a>します。 <a href="https://portal.azure.com/">https://portal.azure.com</a></li>
   <li>古い SDK をアプリケーションから削除します。 NuGet パッケージを削除し、ApplicationInsights.config を削除して、web ページからスクリプトを削除します。</li>
   <li>新しい SDK を追加します。 Visual Studio 2013 Update 3 以降では、web アプリプロジェクトを右クリックし、[Application Insights の追加] を選択します。 アプリを作成します。 コードで古い API を使用していた場合は、 <a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/">新しい api</a>に更新する必要があります。</li>
   <li>デバッグモードで実行し、新しいポータルでデータを表示する: プロジェクトを右クリックし、[Application Insights ポータルを開く] を選択します。</li>
   <li>ポータルで、[使用状況] をクリックし、指示に従ってスクリプトを web ページに追加します。 [可用性] をクリックして web テストを設定します。 <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/21/Availability-Usage.png"><img class="alignnone size-medium wp-image-321641" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Availability-Usage-238x369.png" alt="Availability-Usage" width="238" height="369" /></a></li>
  </ol>

  <h2>Azure portal の Application Insights について</h2>

  移行をさらに簡単にするために、<a href="https://www.youtube.com/channel/UCbd7i2SMUgSEDVixqzk7RPQ">一連の短いビデオ</a>を作成して、VSO ポータルを使用したのと同じタスクを実現するために Azure portal の Application Insights エクスペリエンスを使用する方法を説明しました。 特定のビデオは次のとおりです。

  <ol>
   <li><a href="https://www.youtube.com/watch?v=WYjYaiOLxpU">アプリケーションの使用状況を監視する方法</a></li>
   <li><a href="https://www.youtube.com/watch?v=k_3mdVQSuLk">アプリケーションのパフォーマンスを理解する方法</a></li>
   <li><a href="https://www.youtube.com/watch?v=7DtiYQVMKJo">アプリケーションの可用性を監視する方法</a></li>
   <li><a href="https://www.youtube.com/watch?v=AGSGhmBiJco">アラートを使用する方法</a></li>
   <li><a href="https://www.youtube.com/watch?v=nJxLcoR0l68">アプリの診断ログデータを検索する方法</a></li>
   <li><a href="https://www.youtube.com/watch?v=CfsbPmWNkrQ">ダッシュボードの Azure portal には何がありますか。</a></li>
   <li><a href="https://www.youtube.com/watch?v=L_weK6gY4sI">Azure Portal バージョンの Application Insights に移行する際に、sdk はどのように変更されますか?</a></li>
  </ol>

  <h2>引き続きプレートで作業する: ダッシュボード</h2>

  VSO の Application Insights と Azure portal のエクスペリエンスの間に正確な機能の違いはありませんが、お客様のデータによって、新しい Azure portal エクスペリエンスで適切な一連の機能が実装されています。検索とメトリックの分析機能は、VSO ポータルで提供されているものよりはるかに強力であり、VSO (特に Android と iOS) よりも多くのプラットフォームをサポートするようになりました。


  Azure portal には、ダッシュボードとして最も要求の多い機能があります。 タイルギャラリーを介してブレードにタイルを追加するプロセスを簡略化するなど、この方向に多数の作業を行ってきました。そのため、今後数週間の間、Application Insights グラフのタイルはすぐにカスタマイズおよび自動更新されるようになります。 アプリケーションのさまざまなコンポーネントのグラフや、異なる Azure リソースなど、最大のブレードを使用してダッシュボードを作成できます。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/08/04/Dashboard-Example.png"><img class="alignnone size-medium wp-image-325391" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Dashboard-Example-636x316.png" alt="Dashboard Example" width="636" height="316" /></a>


  追加の種類のタイルやサイズオプションを含めて、さらに多くの作業を行うことができます。また、不足しているキーは、このダッシュボードのエクスペリエンスを他のユーザーと共有することもできます。 これについても解決策をご確認ください。 それまでの間は、Power BI を使用して共有可能なダッシュボードを作成し、 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-export-power-bi/">Application Insights からエクスポートされたデータを Stream Analytics</a>できます。

  <h2>まとめ</h2>

  <a href="https://portal.azure.com/">Azure プレビューポータル</a>で<a href="https://azure.microsoft.com/services/application-insights/">Application Insights</a>を使用するようにアプリケーションを移行していない場合は、ここで実行して<strong>ください。</strong> Application Insights ' 組み込みの分析、高速で強力な診断、および360°ビューのボード全体の機能強化により、アプリケーションの可用性、パフォーマンス、使用状況をより深く理解できるようになりました。


  最後に、新しい機能や改善された機能についてのアイデアを、Application Insights ユーザーの声のページで共有してください。質問がある場合は、 <a href="https://social.msdn.microsoft.com/Forums/en-US/ApplicationInsights/">Application Insights フォーラム</a>にアクセスしてください。
