### YamlMime:Yaml
ms.openlocfilehash: 8378a56e4fe7526eac93861e3d63e9121e404a74
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139904391"
Slug: troubleshooting-common-configuration-issues-with-azure-backup
Title: Azure Backup の一般的な構成に関する問題のトラブルシューティング
Summary: このブログ記事は、Microsoft Cloud バックアップソリューション、Azure Backup の一般的な構成の問題を解決するのに役立ちます。 通常は、Azure Backup のインストールまたは登録時にユーザーに表示されます。
Content: >-
  このブログ記事は、Microsoft Cloud バックアップソリューション、Azure Backup の一般的な構成の問題を解決するのに役立ちます。 通常は、Azure Backup のインストールまたは登録時にユーザーに表示されます。 問題を診断して解決する方法に関する推奨事項を次に示します。


  <strong> </strong>

  <h3>Azure Backup のインストールは、選択したインストールフォルダーに対して無効な属性が指定されていると失敗します。</h3>

  ' システム、非表示、圧縮、または暗号化された属性を持つフォルダーに Azure Backup エージェントをインストールしようとすると、"選択したインストールフォルダーに対して無効な属性が指定されています" というメッセージが表示されます。

  インストールフォルダーで、属性システム、非表示または圧縮、または暗号化を削除してください。 フォルダーのプロパティを削除する方法については、次のステップバイステップガイドを参照してください。

  <ol>
   <li> 暗号化属性を削除するには、サポート技術情報の記事「 <a title=" ファイルとフォルダーの暗号化を削除する Windows " href="https://support.microsoft.com/kb/308993"> Windows </a> でファイルとフォルダーの暗号化を削除する」を参照してください。 これらの手順は、サーバーにも適用できます。</li>
   <li>TechNet のドキュメントを <a title=" 参照してください。フォルダーと " href="https://technet.microsoft.com/en-us/library/cc976811.aspx"> ファイルの圧縮と圧縮解除を行うフォルダーとファイルの圧縮と </a> 圧縮解除によって、フォルダーの圧縮属性が削除されます。</li>
   <li>フォルダーの非表示または読み取り専用の属性を削除するには、TechNet のドキュメント「 <a title=" Attributes volume " href="https://technet.microsoft.com/en-us/library/gg252643.aspx"> Attributes volume </a> 」を参照してください。</li>
   <li>Azure Backup のインストールフォルダーの場所に system 属性がある場合は、新しいフォルダーを作成し、新しいフォルダーの場所に Azure Backup をインストールしてください。</li>
  </ol>

  <strong>

  </strong>

  <h3>Azure Backup 登録が失敗し、"無効な資格情報コンテナー資格情報が指定されました。 ファイルが破損しているか、復旧サービスに関連付けられている最新の資格情報がありません。 "</h3>

  誤った時刻設定を使用してサーバーを登録しようとすると、次のエラーメッセージが表示されることがあります。


  <img alt="Invalid vault credentials provided. The file is either corrupted or does not have the latest credentials associated with recovery service. (ID: 34513) We recommend you download a new vault credentials file from the portal and use it within 2 days." src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/RegistrationError.png" width="519" height="188" />


  "日付と時刻の設定の変更..." を使用して時刻を再設定してください。 サーバーを再起動します。次に、この問題を解決するための詳細なガイダンスを示します。

  <ol>
   <li>時計の " href="https://windows.microsoft.com/en-us/windows/set-clock#1TC=windows-7"> 設定を参照して、日付と時刻の設定を更新してください。時計の設定に関する記事 </a> を <a title=" ご覧ください。</li>
   <li>ローカルタイムゾーンとクローゼットの時刻の設定が一致していることを確認してください。</li>
   <li>サーバーを再起動して、サーバーの登録状態を更新します。 <strong>サーバーを再起動するようにしてください。これは一般的な手順であり、失敗する可能性</strong>があります。</li>
   <li>Azure Backup サービスにサーバーを登録します。</li>
  </ol>

  &nbsp;

  <h3>Azure Backup 操作が失敗し、"認証サービスと通信できません。" というエラーメッセージが表示されます。</h3>

  プロキシの背後にあるサーバーを操作しようとすると、"認証サービスと通信できません" という結果になる場合があります。

  正しいプロキシアドレスを設定してください。 また、プロキシが認証されている場合は、ユーザー名とパスワードを指定します。 Azure Backup のプロキシサーバーアドレスを設定する手順を次に示します。

  <ol>
   <li>Windows Azure Backup エージェント UI を開きます。<img alt="Azure Backup UI with Change Properties link on the right hand side." src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AzureBackupUI-636x356.png" width="636" height="356" /></li>
   <li>[アクション] タブの [プロパティの変更] リンクをクリックします。                                         <img alt="Azure Backup Proxy Configuration" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AzureBackupProxySettings-380x369.png" width="380" height="369" /></li>
   <li>プロキシアドレスとポートを指定します。 認証済みのプロキシの場合は、ユーザー名とパスワードを指定します。                                                                                                                                            <img alt="Azure Backup Proxy Setting Username" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AzureBackupProxyUserName.png" width="373" height="217" /></li>
   <li>[Ok] をクリックします。 サーバーは、指定されたプロキシの詳細を使用して Azure Backup サービスと通信できるようになります。</li>
  </ol>

  &nbsp;


  &nbsp;


  これは Azure Backup に関する一般的な問題の解決に役立つことを願っています。 Azure Backup の詳細については、Azure Backup サポートオプションに関するページを参照してください。 <a href="https://azure.microsoft.com/en-us/support/options/">https://azure.microsoft.com/en-us/support/options/</a>

  <ul>
   <li><a title="テクニカルサポートと " href="https://manage.windowsazure.com/?getsupport=true">   課金サポートの Azure Backup テクニカルおよび課金のサポート</a></li>
   <li><a title="Azure Backup サポートリンク " href="https://social.msdn.microsoft.com/Forums/windowsazure/en-US/home?forum=windowsazureonlinebackup&amp;filter=alltypes&amp;sort=lastpostdesc">   フォーラムのサポート</a></li>
  </ul>

  &nbsp;


  &nbsp;


  &nbsp;


  &nbsp;
