### YamlMime:Yaml
ms.openlocfilehash: f6b3ac2ce08b749d12d462fc40ee95d02f7c5af8
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891940"
Slug: understand-your-sharepoint-usage-with-application-insights-2
Title: Application Insights を使用した SharePoint の使用状況を理解する
Summary: Application Insights を使用すると、SharePoint サイトの使用状況とパフォーマンスについて簡単かつ強力な洞察を得ることが非常に簡単になります。
Content: >-
  SharePoint ベースのサイトと web アプリケーションは、簡単に起動して実行できるため、Enterprise レベルで非常によく利用されます。<a href="https://azure.microsoft.com/en-us/services/application-insights/">Application Insights</a>を使用すると、SharePoint サイトの使用状況とパフォーマンスについて簡単かつ強力な洞察を得ることが非常に簡単になります。 <a href="https://azure.microsoft.com/en-us/services/application-insights/">Application Insights</a>は、アプリまたはクライアント側の java スクリプトコードに SDK を追加することによって機能します。 web ページでは、 <a href="https://portal.azure.com/">Azure portal</a>にテレメトリを送信します。 サポートされているプラットフォーム、言語、Ide の多くの組み合わせに対して、さまざまな <a href="https://github.com/Microsoft/AppInsights-Home">sdk</a> が用意されています。

  <h2>はじめに</h2>

  まず、 <a href="https://azure.com/">Microsoft Azure</a>にアカウントが必要です。 既にお持ちの組織のグループ アカウントにアクセスすることも、従量課金制アカウントを取得することもできます。 (プレビュー段階の Application Insights は無料です)。

  <h3>Microsoft Azure で Application Insights リソースを取得する</h3>

  <ul>
   <li><a href="https://azure.com/">Microsoft Azure</a>にサインアップし、<a href="https://portal.azure.com/">プレビューポータル</a>にアクセスして、Application Insights ASP.NET リソースを追加します。</li>
   <li>SharePoint のページに追加する Application Insights web クライアントコードを取得する</li>
  </ul>

  &nbsp;


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/GetStarted.png"><img class="alignnone size-full wp-image-276841" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/GetStarted.png" alt="GetStarted" width="924" height="500" /></a> <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/GetAppInsightsCode.png"><img class="alignnone size-full wp-image-276851" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/GetAppInsightsCode.png" alt="GetAppInsightsCode" width="574" height="471" /></a>

  <h2>SharePoint ページに Application Insights クライアントコードを追加する</h2>

  クライアントコードでを追加するには、次の2つの簡単な方法があります。


  1) マスターページにアクセスできる場合は、この方法をお勧めします。既定では、すべてのページのテレメトリを取得します。

  <ul>
   <li>シアトルにコードを追加します。 マスター ページ</li>
   <li>SharePoint デザイナーまたは任意のエディターを使用してマスターページをチェックアウトします。</li>
   <li>最初のステップからコピーしたコードスニペットを終了 &lt; /ヘッド &gt; タグの前に挿入します。</li>
  </ul>

  &nbsp;


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/16/SharepointMasterPage.png"><img class="alignnone size-large wp-image-276891" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/SharepointMasterPage-340x369.png" alt="SharepointMasterPage" width="340" height="369" /></a><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AddAppInsightsCode.png"><img class="alignnone size-full wp-image-276881" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AddAppInsightsCode.png" alt="AddAppInsightsCode" width="785" height="367" /></a>


  2)  web パーツを挿入し、コードスニペットを埋め込むだけで、Application Insights コードスニペットを個々のページに追加できます (マスターページへのアクセス権がない場合)。


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/EmbedAppInsightsCode.png"><img class="alignnone size-full wp-image-276871" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/EmbedAppInsightsCode.png" alt="EmbedAppInsightsCode" width="513" height="647" /></a>


  これで、SharePoint サイトに関する強力な洞察を表示する準備ができました。

  <h2>Application Insights を使用して SharePoint の使用状況を表示する</h2>

  SharePoint の使用状況を確認する準備ができたら、<a href="https://portal.azure.com/">プレビューポータル</a>にアクセスし、最初の手順で作成した Application Insights リソースを参照します。 Application Insights 使用状況分析では、ユーザー、セッション、およびページビューの迅速なスナップショットが提供されます。


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/16/Users1.png"><img class="alignnone size-medium wp-image-276911" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Users1-338x369.png" alt="Users1" width="338" height="369" /></a> <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/16/PageViews1.png"><img class="alignnone size-medium wp-image-276921" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/PageViews1-264x369.png" alt="PageViews1" width="264" height="369" /></a>


  Application Insights 診断検索を使用すると、ページビューの生データを取得できます。


  <img class="alignnone size-medium wp-image-276901" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Search1-584x369.png" alt="Search1" width="584" height="369" />

  <h2>まとめ</h2>

  Application Insights を使用すると、さまざまなディメンションでメトリックをスライスして表示することで、<a href="https://blogs.msdn.com/b/visualstudioalm/archive/2014/12/15/application-insights-metric-explorer-me-part-2.aspx">独自の洞察を作成</a>できます。また、単純なコードをマスターページに挿入するだけで済みます。


  今すぐ Application Insights を<a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-get-started/">開始</a>して、SharePoint サイト/アプリケーションのパフォーマンス、使用状況、可用性を分析します。
