### YamlMime:Yaml
ms.openlocfilehash: 838b5906fee13b55e783641bbf7aa672a68c1fc3
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139896358"
Slug: video-new-business-and-application-models-with-microsoft-sql-azure
Title: 'ビデオ: Microsoft SQL Azure を使用した新しいビジネスモデルとアプリケーションモデル'
Summary: '[この記事は SQL Azure チームによって提供されました。]SQL Azure を使用すると、企業は収益性を高め、新しい収益ストリームを実現し、セグメントを広げることができます。 このビデオでは、Sudhir...'
Content: '<p>[この記事は SQL Azure チームによって提供されました。]</p><p>SQL Azure を使用すると、企業は収益性を高め、新しい収益ストリームを実現し、セグメントを広げることができます。 このビデオで Sudhir hasbe は、市場に構築して展開するために必要な時間を短縮することで、最初のムーバーの利点を SQL Azure 方法について説明します。 柔軟なスケーラビリティ、動的消費モデル、ビジネスの準備ができたサービスレベル、web ベースのアクセシビリティと柔軟性を備えた、ゲームに変化する機会について説明します。 SQL Azure。</p>  <p>ビデオ: 表示</p>'
