### YamlMime:Yaml
ms.openlocfilehash: 6b2fb1d0f31450fb6d5fd183ca28a8f82259ef40
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139894242"
Slug: video-how-do-i-configure-sql-azure-security
Title: 'ビデオ: セキュリティを構成するSQL Azure方法'
Summary: '[この記事は、チームによってSQL Azureされました。]このビデオでは、Max Adams が、このビデオ内のセキュリティをSQL Azure。 ログイン、データベース、およびユーザーの作成について説明し、デモを行います。 ...'
Content: <p>[この記事は、チームによってSQL Azureされました。]</p><p>このビデオでは、Max Adams が、このビデオ内のセキュリティをSQL Azure。 ログイン、データベース、およびユーザーの作成について説明し、デモを行います。 master データベースsys.sql_loginsのログインとデータベースの表示を可能にするためのビューと sys.databases も説明します。</p>  <p>ビデオはこちらで <a href="https://technet.microsoft.com/en-us/ff772115.aspx">確認できます</a>。</p>
