### YamlMime:Yaml
ms.openlocfilehash: ad239100426d90706079d07e03b3883ef9609ad6
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139891372"
Slug: view-chooses-microsoft-azure-iot-to-accelerate-development-of-smart-building-applications
Title: IoT をMicrosoft Azureしてスマート ビルディング アプリケーションの開発を加速させるビュー
Summary: スマート ビルディングのイノベーションは、クラウド、AI、IoT の民主化によって、近年増加しています。 最近の発表Azure Digital Twins、Microsoft による IoT イノベーションへの取り組みを強調しています。
Content: >-
  <p>スマート ビルディングのイノベーションは、クラウド、AI、IoT の民主化によって、近年増加しています。 Microsoft の最近の <a href="https://azure.microsoft.com/en-us/services/digital-twins/" target="_blank">Azure Digital Twins</a> 発表では、IoT イノベーションに対する Microsoft&rsquo; の取り組みを強調しています。 組織は、物理的な環境を仮想的に表して、スマート ビルディングを含むさまざまな IoT シナリオを実現する利点があります。 組織は、&rsquo;さまざまなセンサーやデバイスからデータを収集することで、占有する空間をより正確に理解して最適化し、人々のニーズに最適に対応するために変更することができます。 コンピューティング能力がユーザーが使用するあらゆる物理環境に広がり、建物は効率の向上と満足感を生み出す可能性を最も重要な位置に置くものになります。 サイズや背景に関係&rsquo; なく、IoT を任意の顧客にアクセス可能にするには、パートナーの創造性と独自のドメインの専門知識に大きく依存しています。 新しい革新的デバイスを使用すると、より豊富で意味のあるデータをキャプチャし、革新的なスマートビルディング アプリケーションを作成できます。 私&rsquo;たちは、&rsquo;&ndash;ビューで行っている作業の一部を共有するためにうれしく思いました。これは、ウィンドウに変更されなきものを再発明した会社です。</p>


  <h2>ビューは、美しい人間の環境を作成するミッションです</h2>


  <p><a href="https://viewglass.com/" target="_blank">ビュー</a> は、人間の健康と健康がスマート ビルディングの中心である必要がある、と考えます。 これは&rsquo;、動的なガラスを使用して、これまでよりもインテリジェントで接続性が高く、パーソナライズされた建物の人間のエクスペリエンスを向上させるというミッションに取り組む理由です。 動的&rsquo;なガラスウィンドウを表示すると、ビューを維持しながら自然光の最適な量を得ることができます。これは、建物のエネルギー使用量を削減しながら、乗員を構築する機能を大幅に向上させるために使用されます。 <a href="https://hbr.org/2018/09/the-1-office-perk-natural-light?utm_medium=email&amp;utm_source=newsletter_weekly&amp;utm_campaign=weeklyhotlist_not_activesubs&amp;referral=00202&amp;deliveryName=DM13857" target="_blank">H natural business Review は</a> 、自然光を望ましいオフィス の 1 つとして識別する研究を公開したばかりです。 もう 1 つの最近<a href="https://viewglass.com/assets/pdfs/daylight-research.pdf" target="_blank"></a>の調査では、通常のウィンドウでの動的なガラスの表示に関連する重要な健康上の利点が見つかりました。その中には、目の負担、頭の痛み、および不安の 50% &ndash; を超える減少が含め、従業員の健康と生産性の向上に寄与しています。</p>


  <p>&rsquo;データを生成し、コンテキストを適用することで、従業員の健康と生産性、エネルギー効率、状況に応じたパーソナル化まで、あらゆるレベルで人々のニーズに対応するために、建物空間の使い方をよりよく分析し、最適化する組織を支援できるという Microsofts &ndash;&rsquo; &mdash; のビジョンを共有しています。</p>


  <h2>新しいパートナーシップ</h2>


  <p>今日は、View との新しいパートナーシップを発表し、スマート ビルディング用の革新的なアプリケーションを開発するために協力する見込みについてお知らせします。 このパートナーシップの一環として、View はスマート ビルディングに関する専門知識を活用し、Azure IoT プラットフォームの複数の側面を利用してソリューション開発を加速します。 たとえば、View では、アクセス制御や他のスマート ビルディング アプリケーションに Azure Digital Twins を利用し、そのウィンドウおよびフロア コントローラー デバイスに Azure IoT Edge と Azure Sphere を利用します。</p>


  <p>最初のソリューションである <a href="https://view.com/assets/pdfs/microsoft-view-announcement.pdf" target="_blank">View SmartProtect は</a>、本日発表されます。 View SmartProtect は、ガラスの破損を自動的に瞬時に検出する、スマート なウィンドウ ベースのセキュリティ ソリューションです。 ビル内の任意のウィンドウでガラスが割れたらすぐに、Azure IoT を介して Views SmartProtect&rsquo; アプリケーションに信号が送信され、ガラスの破損イベントが発生したビル内の特定の時間、ウィンドウ、場所が顧客に通知されます。</p>


  <p>View SmartProtect は、Azure IoT プラットフォームを活用するアプリケーションを使用して、建物の正常性、スマート化、生産性の向上を目指す View のいくつかの IoT ソリューションの最初のソリューションです。 これは、次のレベルのインテリジェンスとパーソナル化を建物の空間に取り込む最初のステップにすすめてです。 このパートナーシップを通じて、View のお客様は、将来のニーズを満たすために堅牢で安全でスケーラブルな最適な生産性ソリューションの恩恵を受けます。</p>


  <h2>無限の可能性</h2>


  <p>次の取り組みでは、データ中心のアプローチを採用して、個々の人の建物空間を最適化し、高度に自動化された簡単な方法で、正常性と生産性を最大化します。 ビューでは、対話型のガラスディスプレイと、カメラ、マイク、大気質センサーを含むセンサー アレイをウィンドウ フレームに含むインテリジェントなエッジが作成されます。</p>


  <p>&ldquo;これらのスマート ウィンドウ&rdquo;は、Azure IoT、Office 365、Cortana、および Dynamics 365 と統合され、スペースを使用して、乗員により良いサービスを提供し、新しい方法で環境と対話するユーザーを支援します。 これは、インテリジェント クラウドと動作中のインテリジェント エッジのショーケースの例です。 パブリック クラウドによって&ndash;&ndash;実現されるユビキタス分散コンピューティングと、建物のウィンドウや壁を含む、継続的に拡大する一連の接続されたシステムとデバイスを通じて、環境環境と非常に豊富な方法で継続的に対話します。 ビューでは、高密度で電源が供給され、常に接続されたプラットフォームが提供され、いくつかの変換可能なアプリケーションが可能です。</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2dbf0532-b0e2-49ae-a143-440ca84214cc.png"><img alt="Charlotte, NC airport terminal " src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/804d88d3-01f1-45d2-bab8-3476f71bbc1f.png" style="border: 0px; border-image: none; width: 1043px; height: 588px; background-image: none; display: inline;" title="CLT"></a></p>


  <p>たとえば、 &ldquo;乗員がスマート ビルディングに入ると、建物は人が初めてスペースに入り、音声コマンドによって制御できると伝える可能性があります。 お客様の好みに合&rsquo;わせて環境を調整し、あまりにコールドまたはホットすぎるか教えて。&rdquo; この音声操作では、ウィンドウの tint、HVAC レベル、照明条件を自動的に調整して、最適な環境を作成できます。</p>


  <p>この&rsquo;パートナーシップの可能性に感心し、Azure Digital Twins&rsquo; がビューを強化して、乗員の健康と福祉を向上させるソリューションを提供する方法を楽しみにしています。 ビュー&rsquo;イノベーションは、無限のスマート ビルディング イノベーションのための新しい基盤を提供します。 次の&rsquo;情報が表示されるのを待&rsquo;つ必要があります。</p>


  <h2>詳細情報</h2>


  <p>詳細については <a href="https://azure.microsoft.com/services/digital-twins/" target="_blank">、「Azure Digital Twinsビュー</a> 」を <a href="https://viewglass.com/" target="_blank">参照してください</a>。 &rsquo;Smart City Expo Word の世界に来た場合は、Microsoft のブースに立ち寄って、業界初のスマート ウィンドウベースのガラス切れ検出ソリューションである Smart&#39;Protect のプレビューを表示してください。</p>
