### YamlMime:Yaml
ms.openlocfilehash: f2ff4ba657ca3621b07ad4f9549658251ac7b58f
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139909466"
Slug: web-vulnerability-scanning-for-azure-app-service-powered-by-tinfoil-security
Title: Tinfoil Security を使用した Azure App Service に対する Web の脆弱性のスキャン
Summary: Azure アプリサービスで Tinfoil Security を利用できるようになったことをお知らせします。 これにより、Azure アプリの Web の脆弱性のスキャンが可能になり、開発時に web アプリをセキュリティで保護することができます。
Content: >-
  <p>&rsquo; <a href="https://www.tinfoilsecurity.com">Tinfoil security</a>を利用した web 脆弱性スキャンが Azure アプリサービスで利用できるようになったことをお知らせします。 これにより、Azure Web Apps をスキャンし、開発時に Web アプリをセキュリティで保護することができます。 Web アプリケーションのセキュリティコンソーシアムによれば、すべてのレビュー対象サイトの13% 以上が自動的に &rdquo; &ldquo; 侵害される可能性があり、 &ldquo; web アプリケーションの49% には高いリスクレベル &rdquo; の脆弱性が含まれています。 Tinfoil Security &rsquo; の独自の統計情報は、スキャンした web アプリの75% が最初のスキャンに脆弱性を持っていることを示しています。 Web アプリケーションは、より多くの企業の基盤となるため、企業の IT セキュリティに対する脅威の原因になる可能性があります。 Azure App Service による Tinfoil Security のスキャンは、開発者と管理者に対して、悪意のあるアクターによって悪用される前に、これらの問題を検出して対処するための、迅速で統合された経済的な手段を提供します。 Microsoft Azure App Service は、web アプリケーションセキュリティの信頼できる名前であるため、Tinfoil security を選択し、ユーザーが web アプリをセキュリティで保護するための強力なサービスセットを提供しています。 Azure Web Apps の場合、Tinfoil Security は、Azure App Service 管理エクスペリエンスに組み込まれている唯一のセキュリティ脆弱性のスキャンオプションです。 開発中に Tinfoil Security を利用することをお勧めします。お客様のご意見をお待ちしております。 &nbsp;</p>


  <h2>設定方法</h2>


  <p><a href="https://portal.azure.com">Azure 管理ポータル</a>にアクセスして、スキャンを有効にする Web アプリを選択します。 [問題の<em>診断と解決</em>] オプションを選択すると、次の &ldquo; ように<em>診断ツール</em> &rdquo; ボックスが表示されます。</p>


  <p style="text-align: center;"><i><img alt="f0fd3ca166e7477afac134a6061fadd2.png" border="0" id="_x0000_i1025" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f0fd3ca166e7477afac134a6061fadd2.png"></i></p>


  <p>そこから、[セキュリティスキャン &quot; ] を選択し &quot; ます。</p>


  <p style="text-align: center;"><i><img alt="dfc077bb46a2bff3ea693b68f23ba511.png" border="0" id="_x0000_i1025" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/dfc077bb46a2bff3ea693b68f23ba511.png"></i></p>


  <p>このオプションを選択すると、いくつかのプランが表示されます。 ライセンス契約をクリックすると、購入が完了します。 完了すると、[Tinfoil Security] ブレードに管理ダッシュボードへのリンクが表示されます (下図参照)。 このサイトを参照すると、Tinfoil management ダッシュボードに移動します。 <img alt="TinfoilManagement" border="0" height="280" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/TinfoilManagement.png" style="border-width: 0px; margin: 0px auto; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="TinfoilManagement" width="312"> &nbsp; 管理ダッシュボードを参照すると、最新バージョンのダッシュボードが自動的にインストールされ、インストールを通知するダイアログボックスが表示される場合があります。 このインストールが完了すると、次の画像のようなダッシュボードが表示されます。 <img alt="TinfoilDashboard2" border="0" height="263" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/TinfoilDashboard2.png" style="margin: 0px auto; border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="TinfoilDashboard2" width="610"> &nbsp;ここからすぐにスキャンを開始するか、[設定] タブでスキャンをスケジュールすることができます。完了すると、[結果] タブにスキャンの結果が表示されます。</p>


  <p>&nbsp;</p>
