### YamlMime:Yaml
ms.openlocfilehash: 92c4991208ba7f1996222e4c41c95b3b3c9dd6d7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/11/2022
ms.locfileid: "139895695"
Slug: world-cities-day-2020-committing-to-sustainable-urban-environments
Title: 'World Cities Day 2020: 持続可能な都市環境への取り組み'
Summary: 'Microsoft は、持続可能性に関する重要な問題に対する焦点とコミットメントを拡大し続けています。 私たちは、持続可能性が、多くの世代にとって成長する将来を確実に実現するための最も重要な方法の 1 つだとわかっています。 '
Content: >-
  <p>10 月 31 日は World Cities Day です。これは、懸念事項について一般の人々を教育し、グローバルな問題に対処するために、また、人間性の成果を尊重し、強化するために、公共の人々を動員するために確立されています。 &rsquo;&lsquo;今年は、Better City、Better Life: Valuing Our Communitys and Cities&rsquo;&rsquo;&nbsp; をテーマに、グローバル都市化に対する国際コミュニティの関心を大幅に促進し、機会を得て各国間の協力を推進し、都市化の課題に対処し、世界中の持続可能な都市開発に貢献することを期待されています。 これは、世界中の人々が、このような社会の緊急の問題に集う重要な瞬間です。</p>


  <p>Microsoft は、持続可能性に関する重要な問題に対する焦点とコミットメントを拡大し続けています。 私たちは、持続可能性が、多くの世代にとって成長する将来を確実に実現するための最も重要な方法の 1 つだとわかっています。 また、持続可能な開発には、経済的および社会的な開発と共に、環境上の懸念事項に取り組む統合アプローチが必要なとわかっています。</p>


  <p>今年のワールド シティ デーでは、気候行動に関する影響を推進しているテクノロジ パートナーの数を示しています。 <a href="https://aka.ms/partners/buildfor2030" target="_blank">#これは、BuildFor2030</a>&rsquo; キャンペーンの焦点にもなっています。これは、米国の持続可能な開発<a href="https://www.un.org/sustainabledevelopment/sustainable-development-goals/" target="_blank">目標 (</a>SDG) に合わせて機会と肯定的なビジネス成果を生み出して、より包括的な経済を可能にするソリューションを強調しています。</p>


  <h2>Microsoft パートナー: 都市向け革新的なソリューションの構築を支援</h2>


  <p>Microsoft は <a href="https://www.microsoft.com/en-us/sustainability/approach?activetab=pivot1%3aprimaryr4" target="_blank">、炭素陰性</a> 、水陽性、ゼロ廃棄物会社になることをコミットしています。 2025 年に使用するよりも多くの土地を保護する予定であり、大気、水、および陸上の管理に関するスマートな決定を知らせるのに役立つプラネティ コンピューターを構築しています。 これらの目標を達成するには、協力&rsquo;するパートナーのサポートが必要です。</p>


  <p>Microsoft パートナーは、企業や都市に独自のアイデアを取り入れ、事業の変革に役立つ太字の計画を実行しています。</p>


  <p>Redmond Campus&mdash;&mdash; で使用するエネルギーを減らします。これは、パートナーと協力してスマート シティ ソリューションを作成する独自の小さな都市です。 このソリューションでは、クラウド サービスを使用して、1 日に 5 億件のトランザクションを生成する 200 万を超えるデータ ポイントを接続し、18 か月未満の実装の支払いで 6 &ndash; 10&nbsp;% の省電力を実現<sup>します。1</sup></p>


  <p>パートナー ソリューションは、持続可能な未来の構築をサポートしています。 1 つの例は、排出量を減ら&rsquo;してユーティリティの供給を監視して都市のインフラストラクチャをサポートする場合です。 その他のソリューションには、大気質の監視と改善、リサイクルの管理、太陽、風力、その他の再生可能エネルギーの使用の最適化が含まれます。 最後に、パートナーは、水とエネルギーの&rsquo; 消費量を最小限に抑えながら、住人の快適さを最大化するのに役立つスマート ビルディング ソリューションをサポートしています。 パートナーは、市民の参加を支援し、都市全体の持続可能性イニシアチブへの参加を測定する場合にも役立ちます。</p>


  <p>Microsoft パートナー ソリューションは、持続可能で安全で住みやすい都市のサポートを支援しています。 <a href="https://aka.ms/partners/buildfor2030" target="_blank">#BuildFor2030</a> キャンペーンで取り上がっているその他の Microsoft パートナー ソリューションについては、microsoft <a href="https://aka.ms/appsource" target="_blank">Microsoft AppSource、</a>&nbsp;Azure Marketplace<a href="https://aka.ms/azuremarketplace" target="_blank">。</a></p>


  <hr>

  <p>1. Microsoft が将来の都市 <a href="https://www.microsoft.com/en-us/stories/88acres/88-acres-how-microsoft-quietly-built-the-city-of-the-future-chapter-4.aspx" target="_blank">を落ち着いた場所に構築した方法に関する追加情報を参照してください</a>。</p>
